### ISSUE TITLE
Mark exploratory tunnels in the webconsole

### ISSUE THREAD

**Issue by mppdidi** [PurpleI2P/i2pd#1000]
Would it be possible to mark or show exploratory tunnels seperately on the webconsole ?

Thanx.

**Comment by r4sas** [comment]
https://github.com/PurpleI2P/i2pd/commit/6220f8b844acf61ca8da55ce265812d6c73522c3

**Comment by mppdidi** [comment]
Working great so far.
On the landing page the client tunnels includes the exploratory ones afaikt.
Would it make sense to split them up there so we can see the real client tunnels and exploratory tunnels ?

**Comment by mppdidi** [comment]
The reason I asked for this was to get a better understanding of the tunnel creation success rate - is it mainly comprised of failed exploratory or real client tunnels.
