### ISSUE TITLE
BOB getnick not picking up existing nickname

### ISSUE THREAD

**Issue by mppdidi** [PurpleI2P/i2pd#1002]
After a nicknamed destination has been setup via bob it is not possible to pick it up in a later session with getnick.

Here is the example sequence using telnet for simplicity:

telnet 127.0.0.1 2827
setnick mynickname
inhost 127.0.0.1
inport 12345
newkeys
start
quit

The tunnel for the nickname is up and running.

Stopping and closing the tunnel in a later session should be possible via getnick:

telnet localhost 2827
getnick mynickname 

but this produces an error and i2pd crashes.

**Comment by mppdidi** [comment]
It seems the quit command causes nicks and destinations to be 'lost'.
When remaining in the session things work okay.

**Comment by orignal** [comment]
It shouldn't/ Let me try to reproduce

**Comment by orignal** [comment]
I can't reproduce it. 
Second session
nc 127.0.0.1 2827
BOB 00.00.10
OK
getnick test
OK Nickname set to test

**Comment by mppdidi** [comment]
It turns out that when using nc instead of telnet it works as expected.
With telnet the commands also have to have a trainling " " otherwise I get an error 'unknow command'

Thanx.
