### ISSUE TITLE
Tunnel quantity in leaseset

### ISSUE THREAD

**Issue by mppdidi** [PurpleI2P/i2pd#1003]
According to the i2pc spec https://geti2p.net/de/docs/protocol/i2cp up to 16 tunnels in a leaseset should be supported ( minus a few to be on the safe side ).
My understanding is that currently i2pd is hard limited to 5.
Are there any plans to raise this limit ?
Maybe the code change is significant - I don't know to be honest.

Thanx.

**Comment by majestrate** [comment]
up to 16 is supported in i2pd too, 5 is the default.

**Comment by mppdidi** [comment]
Can I set the httpproxy to use more than 5 ?

**Comment by majestrate** [comment]
httpproxy tunnels don't publish themselves to the netdb so they don't have a lease set they publish

this option only makes sense for services that accept inbound traffic like a website or irc server.

**Comment by mppdidi** [comment]
Thank you for clarifying this.
The reason I am asking is even if I define httpproxy inbound/outbound quantity to more than 5 it does not build more than 5.
Maybe I have misconception of the quantity directive regarding httpproxy ?

**Comment by majestrate** [comment]
Not sure why that happens, probably related to client tunnel option limiting.

**Comment by majestrate** [comment]
oh I know why, you need to use another destination for it to take effect, you can't use the shared destination with different properties.

add keys=whatever,dat to the tunnel config for it to take effect

i want to add an option to periodically rotate tunnel destination for client tunnels but that's a lot of work.

**Comment by mppdidi** [comment]
The scenario is basically this:

1) httpproxy has outbound quantity of 7
2) The application connects to 15 different i2p destinations

According to webui the destinations show up and are transferring just fine.
But the number of httpproxy tunnels brickwalls at 5.
Then again I have no clue how i2pd handles / distributes the requests across those tunnels.

**Comment by majestrate** [comment]
By default if an application tunnel does not provide destination keys it will use the shared local destination
which defaults to 5 tunnels each way. this is why it is brickwalling at 5.

**Comment by mppdidi** [comment]
That explains a lot...
So I guess I'm stuck with in this scenario.
Case closed ?!

**Comment by majestrate** [comment]
Not quite, as previously mentioned it may be possible in the future to have an application tunnel rotate its destination

adding that would be a lot of work

**Comment by mppdidi** [comment]
Okay thanks for the effort !
I'm still digging around with i2pd - I'm still a happy user :-)
