### ISSUE TITLE
Tag starvation

### ISSUE THREAD

**Issue by mppdidi** [PurpleI2P/i2pd#1004]
I often encounter tag starvation for destinations over a long period of time.
Is there any way I can diagnose the cause of this ?

Thanx.

**Comment by orignal** [comment]
That's a generic problem for I2P due unreliable communications.
But unlike Java we use confirmed tags only.
In my opinion switching to ECIES will solve that problem more efficiently.

**Comment by mppdidi** [comment]
Original,
thank you for the explanation - i2pd is constantly improving and I am gratefull for that ! 
Spasibo.
