### ISSUE TITLE
OS X Segmentation fault: 11

### ISSUE THREAD

**Issue by iShift** [PurpleI2P/i2pd#101]

**Comment by iShift** [comment]
Again, Segmentation fault: 11

With sudo 
20:03:47/error - Can't open file /Users/Shift/Library/Application Support/i2pd/router.info

After 
touch /Users/Shift/Library/Application\ Support/i2pd/router.info 

20:06:02/error - File/Users/Shift/Library/Application Support/i2pd/router.info is malformed
20:06:02/error - Identity buffer length 0 is too small

**Comment by orignal** [comment]
Meeh, please take a look, why it doesn't create it automatically

**Comment by iShift** [comment]
hmm  after i create in manual i have:
20:06:02/error - File/Users/Shift/Library/Application Support/i2pd/router.info is malformed
20:06:02/error - Identity buffer length 0 is too small

**Comment by orignal** [comment]
Разумеется это не пустой файл должен быть, там в нем ключи содержатся.

**Comment by iShift** [comment]
Неа, при первом запуске он создает файл router.keys и умирает без ошибки. 

При повторном запуске умирает с ошибкой
15:54:19/error - Can't open file /Users/Shift/Library/Application Support/i2pd/router.info
15:54:19/error - Identity buffer length 0 is too small

**Comment by orignal** [comment]
Да они опять там что то с clang намутили. Сказал уже чтобы разбирались.

**Comment by orignal** [comment]
Собрал под 10.10, пофиксил баг с директориями, все работает как надо.
