### ISSUE TITLE
B32 destinations

### ISSUE THREAD

**Issue by mppdidi** [PurpleI2P/i2pd#1013]
Is there a way to gather the .b32.i2p destinations the router sees besides the webui ?

Thanx

**Comment by majestrate** [comment]
keyinfo tool in the i2pd-tools repo

**Comment by mppdidi** [comment]
I rather meant desitnations that pass the router when a local destination is used like e.g. the httpproxy 

http://127.0.0.1:7070/?page=local_destination&b32=mydest.b32.i2p

in the Tags section where .b32.i2p destinations are listed

**Comment by l-n-s** [comment]
Please, be more specific, what information do you need and what for.

**Comment by mppdidi** [comment]
This would be helpfull to build a stats graph about the network status on how many destinations are online.
