### ISSUE TITLE
Tunnel Pool GetNextTunnel

### ISSUE THREAD

**Issue by mppdidi** [PurpleI2P/i2pd#1015]
In libi2pd/TunnelPool.cpp the tunnel is chosen randomly for half of the pools size + 1.
What is the reason for this - in case of tunnel failure to switch over to a healthy tunnel ?

Thanx.

**Comment by orignal** [comment]
Just to select random "good" tunnel, assuming that more than half are good.

**Comment by mppdidi** [comment]
Okay so in terms of bandwidth and tunnel utilization it would be okay to randomly select on the whole poole size ?

**Comment by orignal** [comment]
A stream is trying to find working tunnels pair. That's the goal. Nothing about bandwidth utilization, etc.

**Comment by mppdidi** [comment]
Okay, thanks for clarifying.
