### ISSUE TITLE
android can't save ri / peerProfile

### ISSUE THREAD

**Issue by nonlinear-chaos-order-etc-etal** [PurpleI2P/i2pd#1018]
E i2pd    : [472] RouterInfo: Can't save to /sdcard/i2pd/netDb/ry/routerInfo-yTwDM1myjndyRklzCqMm-a4RIkWA0YovGh1Gd0hk2Nk=.dat

**Comment by hypnosis-i2p** [comment]
поискать ограничения файлух андройда

**Comment by hypnosis-i2p** [comment]
```
<unknown542a> не потому ли что на андройде /sdcard это vfat
<unknown542a> sdcardfs в линайдж
```

**Comment by hypnosis-i2p** [comment]
```
<unknown542a> LinageOS 14.1 последней сборки
```

**Comment by hypnosis-i2p** [comment]
https://en.wikipedia.org/wiki/Filename : = is a reserved char in FAT32

**Comment by hypnosis-i2p** [comment]
= запрещено

**Comment by orignal** [comment]
У джавистов тоже с =

**Comment by hypnosis-i2p** [comment]
E i2pd : [015] Profiling: /sdcard/i2pd/peerProfiles/pm/profile-mR0vPMFdMAr3-Hu8p3xZV8pgmOhHDZIvKVd24pxejbE=.txt: cannot open file

**Comment by r4sas** [comment]
@nonlinear-chaos-order-etc-etal есть смысл держать иссуй?
Как мне кажется, если sdcard монтируется системой, а не скриптами втыкающими ExtSD с vfat, то проблем никаких не должно быть.

**Comment by r4sas** [comment]
Android uses VFAT LNS, so `=` is not prohibited.
