### ISSUE TITLE
Is there a GUI?

### ISSUE THREAD

**Issue by emkei-cz** [PurpleI2P/i2pd#1026]
Hi all,

I'm a beginner in using i2PD.
I use Linux Mint 18.3 and "i2pd_2.17.0-1xenial1_amd64.deb"

Is there a GUI exist in this package?

**Comment by hypnosis-i2p** [comment]
You need to build [1] from sources

[1] https://github.com/PurpleI2P/i2pd/tree/openssl/qt/i2pd_qt

**Comment by emkei-cz** [comment]
And some instruction how to do it? thx.

**Comment by orignal** [comment]
I will build it

**Comment by emkei-cz** [comment]
Ooo thank you so much

**Comment by majestrate** [comment]
On Fri, Dec 08, 2017 at 04:50:07PM -0800, emkei-cz wrote:
> And some instruction how to do it? thx.

to build it you check out the source:

git clone https://github.com/purplei2p/i2pd
cd i2pd/qt/i2pd_qt

then build with qmake:

qmake && make

**Comment by orignal** [comment]
https://github.com/PurpleI2P/i2pd/releases/download/2.17.0/i2pd_qt_2.17.0_ubuntu16.04.zip

**Comment by emkei-cz** [comment]
That's really great, I'll thank you for the others

**Comment by Generator-X** [comment]
Hi,
Today I found the information that there is a GUI on Linux
https://forum.root.cz/index.php?topic=16983.msg238492;topicseen#msg238492

There is some tutorial how to use it i2pd ?
I was looking at the site: https://i2pd.readthedocs.io
But it's too technical for a layman...

**Comment by orignal** [comment]
Basically i2pd GUI for Linux is not highly demanded. It's assumed to run as daemon instead.

**Comment by l-n-s** [comment]
Moving the issue to docs repo https://github.com/PurpleI2P/i2pd_docs_en/issues/11
