### ISSUE TITLE
Transient tunnels not working after SIGHUP

### ISSUE THREAD

**Issue by ghost** [PurpleI2P/i2pd#1028]
After SIGHUP signal all transient tunnels stop working.

**Comment by majestrate** [comment]
I think that this happens because it regenerates the destination keys and there is no proper handover for
transient tunnels.

Kinda figured this would happen.

**Comment by mppdidi** [comment]
Thanks for the explanation.
Am I to understand this correctly that this feature is implemented despite the fact beforehand that it doesn't work ?

**Comment by orignal** [comment]
That's bug

**Comment by mppdidi** [comment]
My appologies original, I was kind of excited about this feature ;-)
Looking forward to a fix.

Thanx.

**Comment by mppdidi** [comment]
any news on this front ?

**Comment by l-n-s** [comment]
Why did you close it? It is still not fixed.

**Comment by r4sas** [comment]
Please check that. It must be already fixed.
