### ISSUE TITLE
Show nicknames in the I2CP destinations on the webui

### ISSUE THREAD

**Issue by mppdidi** [PurpleI2P/i2pd#1032]
Having the nicknames of I2CP destinations on the webui would be very helpfull.
Is it doable ?

Thanx.

**Comment by orignal** [comment]
Where are they come from?

**Comment by mppdidi** [comment]
the come via i2cp from external apps - BBT for example.

**Comment by orignal** [comment]
what parameter is it?

**Comment by mppdidi** [comment]
inbound.nickname and/or outbound.nickname not sure wich one exactly.

Thanx.

**Comment by r4sas** [comment]
Need to check before closing, due to vuze havent any setting which allow set nickname of destination.

**Comment by r4sas** [comment]
Added in i2psnark:
`I2CP options: inbound.nickname=i2psnark`
Seems like it works:
![local_destinations](https://user-images.githubusercontent.com/7023612/33938145-68bfa470-e017-11e7-8326-799d323d21c9.png)

**Comment by mppdidi** [comment]
Doesn't work for BBT - maybe it sets only the outbound.nickname.
Could you verify this or deliver a patch for that ?

Thanks

**Comment by r4sas** [comment]
@mppdidi as said in reference, outbound.nickname ignored unless inbound.nickname is unset.
https://github.com/PurpleI2P/i2pd/blob/openssl/libi2pd/Destination.cpp#L62

**Comment by orignal** [comment]
@mppdidi please confirm it. If so, I will add outbound.nickname

**Comment by mppdidi** [comment]
I confirm, some app sends only outbound.nickname.

Thanx for your support !!!
Spasibo

**Comment by orignal** [comment]
Fixed
