### ISSUE TITLE
function multiversioning?

### ISSUE THREAD

**Issue by yangfl** [PurpleI2P/i2pd#1046]
Hi,
I've packaged i2pd into Debian main repo, see https://packages.debian.org/unstable/i2pd .
As https://bugs.debian.org/886378 says, non-baseline instruction set pervent binary portability. After some investigation, I managed to fix that by function multiversioning[1]. This will let compiler optimise according to different isa (sseX, avxX) with one line, without manually manipulate assembly code. I've tested them on my own machine.
I know this is (maybe) a breaking change so I'm here to ask for your idea. And I'm also OK if you decide not to accept this.

[1] https://github.com/yangfl/i2pd/blob/master/debian/patches/0001-function-multiversioning.patch

**Comment by majestrate** [comment]
It's a good start but the AVX code also needs to be abstracted out like the AESNI is.

**Comment by majestrate** [comment]
Also, does this change break clang builds?

**Comment by yangfl** [comment]
According to https://lwn.net/Articles/691932/ you don't need to abstract AVX code. That's the magic of compiler optimisation.
My memory is tight and I don't get clang. Maybe I will try later...

**Comment by yangfl** [comment]
closed as CPU detection available. Thanks!
