### ISSUE TITLE
silently quit when pidfile can't be created

### ISSUE THREAD

**Issue by yangfl** [PurpleI2P/i2pd#1047]
With default install, run `i2pd --pidfile=/nonexist/file`, nothing shows, no warnings/errors, and return code is 0. This is confusing.

**Comment by LLE8** [comment]
I have seen similar behavior in OpenWRT

**Comment by orignal** [comment]
what is correct return code in this case?

**Comment by majestrate** [comment]
probably -1

**Comment by LLE8** [comment]
As i noticed earlier in OpenWrt package building process, there are no errors or warnings in log, although LogPrint() call. Is it bug?
