### ISSUE TITLE
BOB keeps CLOSE_WAIT after broken connection

### ISSUE THREAD

**Issue by ghost** [PurpleI2P/i2pd#1049]
BOB keeps CLOSE_WAIT after broken connection of a client application.
If an application error causes a stale tunnel connection and then closes it BOB keeps the connection on CLOSE_WAIT indefinetly leading to OOM / crash / TCP overflow.

**Comment by mppdidi** [comment]
Stopping and clearing the BOB tunnel also keeps the conneciton(s) CLOSE_WAIT.

**Comment by mppdidi** [comment]
the bob stop command is not stopping the tunnel actually.
only a clear command works.
