### ISSUE TITLE
Enforce "accept-encoding: gzip" for eepSites

### ISSUE THREAD

**Issue by dimzon** [PurpleI2P/i2pd#1054]
Схема следующая. Nginx крутится на одном сервере, i2pd на другом. Между серверами прокинут защищенный туннель (shadowsocks например). Хочется уменьшить трафик между сайтами. Можно конечно сделать упаковку/распаковку  средствами туннеля (например zebede вместо shadowsocks). Однако для Http-сайтов есть характерная фишка - статику (скрипты, стили) можно сжать заранее на стороне сервера (и сжать очень сильно с использованием zopfly) и при наличии соответствующего заголовка сервер будет отдавать предварительно сжатый файл без затрат СPU на упаковку "на лету" как это было бы при сжатии средствами туннеля (zebede).

Однако далеко не все клиенты (большиство) посылают этот заголовок... Технически  ip2d может всегда посылать его принудительно и в этом случае распаковывать gzip перед передачей дальше...

**Comment by r4sas** [comment]
Такое врядли будет сделано из-за принципа обратной совместимости с Java I2P.

**Comment by orignal** [comment]
оно почти сделано, просто ранее не наблюдалось к этому никакого интереса

**Comment by dimzon** [comment]
Ну вот появился интерес ;)
Кстати, можете подсказать чем защищенно и максимально эффективно прокинуть между машинами unix domain socket? Новый  ssh умеет но он зараза  statefull и с точки зрения эффективности есть подозрение что "дешевле" shadowsocks-libev для проброски tcp socket использовать?
Т.е. задача которая стоит - максимально эффективно и экономно обеспечить схему: nginx на одном сервере, i2pd роутер на другом.

**Comment by r4sas** [comment]
Закрываю м пометкой wontfix, поскольку:
* ни каких движений в реализцации не было
* это все таки должны делать браузер и вебсервер
