### ISSUE TITLE
Q: Should i allow Java in firewall?

### ISSUE THREAD

**Issue by slrslr** [PurpleI2P/i2pd#1061]
Hello, i seen that the [I2P application](https://geti2p.net/en/) is using Java and my Firewall (Comodo) ask me too many times to allow the connections tov arious IPs and ports. And i do not know if it is good idea (security wise) to automatically allow all future Java requests. Because if there is any virus that will use Java i will not be prompted and will not spot such sudden Java connection. Or there is too low or no probability any malicious software will use Java to send out my private data?

**Comment by K1773R** [comment]
This is i2pd which is written in C++ and not the I2P (that you have) which is written in Java.
Anyway, to respond to your question:
Its absolutely normal that you get many different connections, after all its a peer to peer (p2p) network. Yes you should allow it. If you have a "good" firewall, just allow i2p itself, not all java apps.
