### ISSUE TITLE
How to use i2pd on Windows?

### ISSUE THREAD

**Issue by slrslr** [PurpleI2P/i2pd#1062]
Hello,

i can not find answer in [Documentation](https://i2pd.readthedocs.io/en/latest/user-guide/run/), [Wiki](https://github.com/PurpleI2P/i2pd/wiki), readme.txt nor at Google.

On Windows 10 64bit i installed file setup_i2pd_v2.17.0.exe (found in [precompiled binaries](https://github.com/PurpleI2P/i2pd/releases/latest)) and i found installed app in Program Files. I opened the .exe and it shown tray icon and a web page http://127.0.0.1:7070/ where it seems to be working. HTTP & SOCKS Proxy has status "Enabled". Network status is "Firewalled", i am using OpenVPN GUI. Now i am stuck and do not know how to gain access to .i2p sites as i tried many (i2hosts.i2p, stats.i2p, no.i2p ..) and none opened indicating browser or something do not have access into i2p network.

How i can start using i2p sites now please?

**Comment by majestrate** [comment]
use http proxy at http://127.0.0.1:4444/ in your browser.

**Comment by slrslr** [comment]
@majestrate thank You, it says this:

> Proxy error: Outproxy failure
Host 127.0.0.1 not inside I2P network, but outproxy is not enabled

**Comment by majestrate** [comment]
what browser? you want to exclude 127.0.0.1 from the proxy settings.

**Comment by slrslr** [comment]
@majestrate it Firefox i have set No proxy. In Tor browser i have set custom proxy to socks: 127.0.0.1:9150 and "No proxy for:" is set to: 127.0.0.1 - yet that message i mentioned in my previous post appears..

**Comment by slrslr** [comment]
I missed this guide: https://github.com/PurpleI2P/i2pd/wiki/Using-i2pd
It instructs that web browser have to be configured to use proxy: 127.0.0.1:4444
**Once i do it, i2p websites started loading**, but normal websites like github.com stop working. Is there any way to run both on one browser?

**Comment by r4sas** [comment]
@slrslr, not recommended to use i2p and clearnet in one browser. Please use other or portable browser for it.
But if you still want use both networks in one browser, install FoxyProxy Standard extension and import  configuration from that archive
[foxy_i2p.zip](https://github.com/PurpleI2P/i2pd/files/1649193/foxy_i2p.zip)
.
