### ISSUE TITLE
Optimize for Multihoming - раздача одного eepSite несколькими i2pd-роутерами 

### ISSUE THREAD

**Issue by dimzon** [PurpleI2P/i2pd#1068]
В java-версии i2p в настройках туннеля есть чекбоксик "Optimize for Multihoming". Два вопроса - в чем заключается оптимизация и будет ли она в i2pd.

**Comment by orignal** [comment]
я спрошу в чем она - вроде в нем нет никаких особенностей

**Comment by orignal** [comment]
У нас эта "оптимизация" всегда.
