### ISSUE TITLE
Популяризация I2P - portable i2p browser

### ISSUE THREAD

**Issue by dimzon** [PurpleI2P/i2pd#1069]
Коль скоро тут русскоязычные соотечественники спрошу, а нету ли в планах пересобрать TorBrowser bundle под комбинацию Firefox + Tor + i2pd? Потому как простой домохозяйке объяснить как пользоваться i2pd это тот еще ребус...

Заодно вопрос, так как в стране объявлена война  анонимайзерам, возможно ли например настроить i2pd так чтобы оно пыталось бутстрап через tor получить (и вообще использовать механизмы obfs итп)

Ну и еще мысль больше об увеличении доступности I2P - сделать мостик - запустить tor2web но чтобы он не на onion-ы ходил а на i2p. А сам tor2web чтобы был tor-овским hiddenService-ом. Т.е. адрес blalbalba.lalala.onion открывает blalbalba.i2p. Таким образом появится простой (установка TorBrowser доступна домохозяйке) и нецензурируемый (потому что hiddenService) доступ к i2p-сайтам ;)

**Comment by r4sas** [comment]
См. [сюда](https://github.com/PurpleI2P/i2pdbrowser).
В плане использования клирнета и I2P одновременно в одном браузере - это небезопасно.

**Comment by dimzon** [comment]
> В плане использования клирнета и I2P одновременно в одном браузере - это небезопасно.

все зависит от целей.  если готовить революцию то да. если тупо кино скачать (т.е. используется для обхода цензуры и недосягаемости **сайта** со стороны DMCA итп) то пофиг...

**Comment by dimzon** [comment]
Т.е. darknet это роскошный абузо-устойчивый, цезуро-устойчивый хостинг. Учитывая активно-наполняемые черные списки роскомпозора в этой стране надо максимально облегчить доступ неквалифицированного населения (домохозяек) к даркнет-ресурсам. При этом сколь-либо серьезной проблемы безопасности пользователей не стоит. Естественно нужно/желательно чтобы пользователи понимали что при подобном доступе их безопасность не гаратируется. Но слава богу пока у нас сам факт посещения сайтов не преследуется...

**Comment by uis246** [comment]
dimzon, не "роскомпозора", а роскомпидора

**Comment by l-n-s** [comment]
Юзерфрендли решения нужны, это точно.  :+1: 

Обсуждения сборки браузера непосредственно к i2pd не относятся, для этого у нас есть [i2pdbrowser](https://github.com/PurpleI2P/i2pdbrowser).
