### ISSUE TITLE
LeaseSet publishing fails randomly when creating a new destination, because no outbound tunnels are available

### ISSUE THREAD

**Issue by l-n-s** [PurpleI2P/i2pd#1072]
Sometimes I can access destinations instantly after start, but sometimes it lags for 600 seconds. Looks like the first time it can't publish the destination correctly (which is weird, since we have lab environment in the testnet with 100% success rates)

[ls_lag.zip](https://github.com/PurpleI2P/i2pd/files/1660070/ls_lag.zip)

Logs (error_host is the i2pd node with the hidden service, error_proxy is the node which proxy i use to access that hidden service)

**Comment by majestrate** [comment]
do you have logs on the floodfill nodes too?

**Comment by l-n-s** [comment]
Same happens when I test SAM applications in testnet. Right when I start XD, session is created, but LS is not published for 10 minutes.

```
10:44:52@538/error - Destination: Can't publish LeaseSet. No outbound tunnels
10:44:52@538/error - Destination: Can't publish LeaseSet. No outbound tunnels
10:44:52@538/error - Destination: Can't publish LeaseSet. No outbound tunnels
10:44:52@538/error - Destination: Can't publish LeaseSet. No outbound tunnels
10:44:52@538/error - Destination: Can't publish LeaseSet. No outbound tunnels
```

The problem is that i2pd tries to publish destination before any OB tunnels are available. It makes testnet benchmarking a pain. idk maybe we can have a workaround?

**Comment by l-n-s** [comment]
[logs.zip](https://github.com/PurpleI2P/i2pd/files/2919815/logs.zip)

**Comment by rszibele** [comment]
I am also experiencing this bug, but randomly. As of late (past few days) I can't create outbound tunnels in general without this error, I don't know if that is related as the error isn't always in the logs.

**Comment by r4sas** [comment]
Too much things changed. Reopen if problem still exists.
