### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by uis246** [PurpleI2P/i2pd#1075]
‘boost::asio::ssl::context::context(boost::asio::io_service&, boost::asio::ssl::context_base::method)’
System: Opensuse
Boost: 1.66.0-2.1
/home/uis/i2pd/libi2pd/Reseed.cpp:525:75: error: no matching function for call to ‘boost::asio::ssl::context::context(boost::asio::io_service&, boost::asio::ssl::context_base::method)’

**Comment by LLE8** [comment]
Same bug in fresh OpenWrt
https://github.com/PurpleI2P/i2pd/issues/345#issuecomment-355761246

**Comment by LLE8** [comment]
Что-то они в 1.66 переделали  https://www.linux.org.ru/news/development/13898187

**Comment by uis246** [comment]
Пытаюсь всё исправить

**Comment by orignal** [comment]
Надо поправить аналогично
https://github.com/PurpleI2P/i2pd/commit/0f2d2156e6b4c75568a8c87606b1196cabff1948#diff-b478595290b32b6b75bdc5af2f073f62

**Comment by LLE8** [comment]
В OpenWrt понятно откуда, там @yangfl написал Makefile  для 2.17.0, которая образовалась 4 декабря.

**Comment by orignal** [comment]
попробуй собрать транк. 2.18 будет вместе с 0.9.33 джавы

**Comment by LLE8** [comment]
А можно 2.17.1 ?

**Comment by orignal** [comment]
а зачем 2.17.1 ?

**Comment by LLE8** [comment]
Если 2.18 будет скоро, то 2.17.1 незачем. 
Транк с моим собственным openwrt-шным Makefile-ом компилится для LEDE/OpenWrt с boost 1.66, запускается, флибуста открывается.
Бинарник весит 2 МБ.

**Comment by orignal** [comment]
так c 2.18 мы ждем исключтельно джавистов

**Comment by LLE8** [comment]
А они по времени предсказуемы или не очень?

**Comment by orignal** [comment]
29 ого + несколькго дней

**Comment by l-n-s** [comment]
@LLE8 since @yangfl is not a Russian, you could probably duplicate that message in English (if that is important)

**Comment by LLE8** [comment]
@l-n-s  написал туда  https://github.com/openwrt/packages/issues/5511
Думаю, можно закрывать этот баг.
