### ISSUE TITLE
Ubuntu install fails

### ISSUE THREAD

**Issue by azazar** [PurpleI2P/i2pd#1079]
# dpkg -i i2pd_2.17.0-1xenial1_amd64.deb 
    dpkg: package ssh-import-id depends on python3:any, which is not installed or flagged to be installed

    # dpkg -i --force-depends i2pd_2.17.0-1artful1_amd64.deb 
    Unpacking i2pd (from i2pd_2.17.0-1artful1_amd64.deb)...
    Setting up i2pd (2.17.0-1artful1)...
    postinst called with unknown argument ''

    # lsb_release -a
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 16.04.3 LTS
    Release:        16.04
    Codename:       xenial

**Comment by r4sas** [comment]
> `# dpkg -i i2pd_2.17.0-1xenial1_amd64.deb`
`apt-get install python3`
> `# dpkg -i --force-depends i2pd_2.17.0-1artful1_amd64.deb`
Don't try isntall artful package on xenial distribution.

**Comment by azazar** [comment]
# dpkg -i --force-depends i2pd_2.17.0-1xenial1_amd64.deb 
    Unpacking i2pd (from i2pd_2.17.0-1xenial1_amd64.deb)...
    Setting up i2pd (2.17.0-1xenial1)...
    postinst called with unknown argument ''

**Comment by azazar** [comment]
python3 is installed already. I guest, it's dpkg's error, and irrelevant

**Comment by azazar** [comment]
However I managed to resolve deps using aptitude, and now it's installed. But that message from postinst is strange anyway. And there is a section, automatically added by dh_installinit, with "abort-upgrade" argument condition, that's not reachable. Is that supposed to be unreachable?

**Comment by r4sas** [comment]
is here same issue if u will try install package from repo or launchpad?

**Comment by azazar** [comment]
# apt install i2pd
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    Suggested packages:
      privoxy
    The following NEW packages will be installed:
      i2pd
    0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
    Need to get 0 B/760 kB of archives.
    After this operation, 2,500 kB of additional disk space will be used.
    Selecting previously unselected package i2pd.
    (Reading database ... 184705 files and directories currently installed.)
    Preparing to unpack .../i2pd_2.17.0-1xenial1_amd64.deb ...
    Unpacking i2pd (2.17.0-1xenial1) ...
    Processing triggers for systemd (229-4ubuntu21) ...
    Processing triggers for ureadahead (0.100.0-19) ...
    Processing triggers for man-db (2.7.5-1) ...
    Setting up i2pd (2.17.0-1xenial1) ...
    usermod: no changes
    Processing triggers for systemd (229-4ubuntu21) ...
    Processing triggers for ureadahead (0.100.0-19) ...

**Comment by azazar** [comment]
Package removal, removes modified configuration files, which is wrong behaviour. AFAIK, it should be removed only on purge.
