### ISSUE TITLE
Clients: Can't read tunnel *** params: No such node (host)

### ISSUE THREAD

**Issue by azazar** [PurpleI2P/i2pd#1080]
I can't configure server tunnel. Looks like, it's a bug.

Configuration:

    [ssh]
    
    type = server
    address = 127.0.0.1
    port = 22
    key = ssh-keys.dat

Log output:

    21:44:42@778/info - Clients: starting HTTP Proxy at 127.0.0.1:4444
    21:44:42@778/info - Clients: starting SOCKS Proxy at 127.0.0.1:4447
    21:44:42@778/error - Clients: Can't read tunnel ssh params: No such node (host)
    21:44:42@778/info - Clients: 0 I2P client tunnels created
    21:44:42@778/info - Clients: 0 I2P server tunnels created
    21:44:42@778/info - Clients: starting SAM bridge at 127.0.0.1:7656

OS: Ubuntu 16
I2PD was started via systemd

**Comment by r4sas** [comment]
drop line after block defining

**Comment by azazar** [comment]
It didn't help

**Comment by l-n-s** [comment]
Server tunnel should define `host`, but you defined `address`

**Comment by majestrate** [comment]
change address to host

**Comment by azazar** [comment]
Thank you, it works. Lack of samples in default configuration files gives some trouble configuring it.
