### ISSUE TITLE
Ubuntu - i2pd does not start

### ISSUE THREAD

**Issue by NeoProgramming** [PurpleI2P/i2pd#1081]
When I try to start i2pd, there is a fall with the following message:

terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::create_directory: Permission denied: "/home/user/.i2pd"
Aborted (core dumped)

reinstallation does not help.

LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

**Comment by majestrate** [comment]
Which version of i2pd? is this using the debs from 2.17?

**Comment by NeoProgramming** [comment]
Yes, 2.17.0-1xenial1

**Comment by majestrate** [comment]
I think that the app armour profile was wrong, next release should have fixed that.

For know you can build from source for it to work "all the way".

**Comment by l-n-s** [comment]
Yes, it is caused by profile, you can disable it if you have some exotic use case.

i2pd package is intended to be run as system daemon, not executed by random users. So there is nothing wrong with the profile IMO.

**Comment by K1773R** [comment]
i had to add this to make it work with apparmor in /etc/apparmor.d/usr.sbin.i2pd
```
  /usr/share/i2pd/** r,
  /run/i2pd/** rw,
  /var/log/i2pd/i2pd.log rw,
```

**Comment by r4sas** [comment]
btw, needed to update it to new paths

**Comment by K1773R** [comment]
thanks for adding it, @r4sas

**Comment by BOPOHA** [comment]
```
Resolving Dependencies
--> Running transaction check
---> Package i2pd.x86_64 0:2.17.0-20171206git.el7.centos will be updated
---> Package i2pd.x86_64 0:2.18.0-1.el7.centos will be obsoleting
---> Package i2pd-systemd.x86_64 0:2.17.0-20171206git.el7.centos will be obsoleted
--> Finished Dependency Resolution

Dependencies Resolved

==========================================================================
 Package   Arch        Version                     Repository        Size
==========================================================================
Installing:
 i2pd      x86_64      2.18.0-1.el7.centos         vorona-i2pd      915 k
     replacing  i2pd-systemd.x86_64 2.17.0-20171206git.el7.centos

Transaction Summary
==========================================================================
Install  1 Package

Total download size: 915 k
Is this ok [y/d/N]:
```
and config dir moved from /var/lib/i2pd/ to /etc/i2pd/
@l-n-s  very nice! ;)
