### ISSUE TITLE
[Docker] Image build fails for 2 months

### ISSUE THREAD

**Issue by l-n-s** [PurpleI2P/i2pd#1083]
Build [fails](https://hub.docker.com/r/meeh/i2pd/builds/) for 2 months already.

```
The command '/bin/sh -c apk --no-cache --virtual build-dependendencies add make gcc g++ libtool boost-dev build-base openssl-dev openssl git && mkdir -p /tmp/build && cd /tmp/build && git clone -b ${GIT_BRANCH} https://github.com/PurpleI2P/i2pd.git && cd i2pd && make -j4 && mkdir -p ${I2PD_PREFIX}/bin && mv i2pd ${I2PD_PREFIX}/bin/ && cd ${I2PD_PREFIX}/bin && strip i2pd && rm -fr /tmp/build && apk --purge del build-dependendencies build-base fortify-headers boost-dev zlib-dev openssl-dev boost-python3 python3 gdbm boost-unit_test_framework boost-python linux-headers boost-prg_exec_monitor boost-serialization boost-signals boost-wave boost-wserialization boost-math boost-graph boost-regex git pcre libtool g++ gcc pkgconfig' returned a non-zero code: 1
```

The problem is that apk returns non-zero code if `--no-cache` key is not specified. I've already fixed that in `contrib/docker/Dockerfile`, and it also has reseed certificate verification.

@meeh420 @mikalv you may want to configure your repo to use `contrib/docker/Dockerfile` for security reasons. It has a lot of pulls, 500K.

**Comment by mikalv** [comment]
Should be solved now, successfully builded just now :) https://hub.docker.com/r/meeh/i2pd/builds/bwcytnrffyj9anuydlrzse4/
