### ISSUE TITLE
Android: Stop menu item restarts the app instead termination

### ISSUE THREAD

**Issue by orignal** [PurpleI2P/i2pd#1094]

**Comment by hypnosis-i2p** [comment]
```
> а, я понял какой у тебя тесткейс. ты жмёшь стоп и потом тыкаешь видимо в нотифай
> потестю

**Comment by hypnosis-i2p** [comment]
проблема была не в этом.
сервис просто всегда рисовал что "i2pd started" - вне зависимости от того застопан демон или нет.

стоп меню айтем стопает демон.
мессагу сервиса сейчас починю.

приложение не рестартуется - к нему никаких действий обработчик меню айтема не применяет - приложение просто остаётся как есть, запущенным.

**Comment by hypnosis-i2p** [comment]
fixed
