### ISSUE TITLE
No xenial armhf binary anymore?

### ISSUE THREAD

**Issue by puffosiffredi** [PurpleI2P/i2pd#1105]
I am using i2pd on  odroid Xu4, and I was using the release, up to the 2.0.16... now I see there are no updates for the xenial .... is it a permanent decision?

**Comment by majestrate** [comment]
It should have been released, looks like R4SAS forgot :D

**Comment by puffosiffredi** [comment]
Well, I actually compiled it from the source, It was just a question, 'cause if this is permanent I will put some build automation tool to do it automatically....  (it takes a little to compile on Odroid XU4). Thank you for the answer, anyhow. :)

**Comment by r4sas** [comment]
@puffosiffredi https://launchpad.net/~purplei2p/+archive/ubuntu/i2pd/+sourcepub/8752251/+listing-archive-extra - all packages available. How and where you look for them?

**Comment by puffosiffredi** [comment]
I followed the link from the website, so I've seen this link:

https://github.com/PurpleI2P/i2pd/releases/tag/2.18.0

**Comment by r4sas** [comment]
ah... maybe not selected them... will upload now
