### ISSUE TITLE
[CentOS 7] i2pd service does not work after installing from Copr repo, server reboot is required

### ISSUE THREAD

**Issue by l-n-s** [PurpleI2P/i2pd#1118]
After installing i2pd from Copr repo, systemd service just doesn't start (neither automatically, nor manually), I have no clue what happens. After server is rebooted - i2pd starts to work correctly.

This problem only happens on CentOS 7 - Fedora seems to work fine.

**Comment by r4sas** [comment]
Clean install of CentOS 7 + repo starts i2pd without any problems.

**Comment by l-n-s** [comment]
yeh it needs more testing

**Comment by r4sas** [comment]
If there are more details, ideas or reasons for such behavior, then please reopen.
