### ISSUE TITLE
I2PService::HandleReadyCheckTimer times out timers that are not timed out

### ISSUE THREAD

**Issue by vmon** [PurpleI2P/i2pd#1124]
Here https://github.com/PurpleI2P/i2pd/blob/openssl/libi2pd_client/I2PService.cpp#L90

It says if(itr->second >= now) then send a timeout error to the handler. But Doesn't itr->second >= now means that the handler time out time is still in future? shouldn't it be if (itr->second <= now)? Am I missing some logic here?

**Comment by majestrate** [comment]
no logic being missed you're probably right

**Comment by majestrate** [comment]
actually wait, i think the code should be correct, as it's comparing the time for expiration to the current time

if expireTime >= now then remove the handler and call callback with timeout

**Comment by vmon** [comment]
sorry I had a typo in my comment. But as you said:

"if expireTime >= now"

this means it is not expired yet.

**Comment by majestrate** [comment]
you're right, that's a simple fix. you can submit a PR if you want to. I'll merge it. Or I can do it.

**Comment by vmon** [comment]
Thanks a lot. I'll submit the PR.

**Comment by vmon** [comment]
As we are at it this. I was wondering if this behavoir was intended:
 When 
m_ConnectTimeout = 0

Which is its default value, and callback handler which added using AddReadyCallback will never gets called even if the tunnel gets ready.

Personally if I don't set the timeout, I expect that the callback gets called whenever the tunnel gets ready no matter how long does it take.

Should I change the code to follow this logic, i.e.,

"If timeout is not set, never times out, but call the callback when the tunnel gets ready no matter how long it takes."
?

**Comment by majestrate** [comment]
if the connect timeout is never set the timeout settings are not applied and the sockets act as they would without the connect timeout settings

**Comment by l-n-s** [comment]
Status? Should we close the issue?
