### ISSUE TITLE
SAM VERSION is not handled correctly

### ISSUE THREAD

**Issue by cwassert** [PurpleI2P/i2pd#1126]
When sending the request `HELLO VERSION MIN=1.0 MAX=2.0` to i2pd, it replies with `HELLO REPLY RESULT=OK VERSION=3.0`, because (as stated in the source code) only 3.0 is supported.

But the expected reply according to the [spec](https://geti2p.net/en/docs/api/samv3) would be `HELLO REPLY RESULT=NOVERSION`.

**Comment by majestrate** [comment]
should be fixed now, let us know.

**Comment by cwassert** [comment]
Looks good.
Is there a reason that i2pd returns `3.0` when requesting `MIN=3.0 MAX=3.2`? Because for `MIN=3.1 MAX=3.2` it returns `3.1`. As far as I can tell 3.0 is a subset of 3.1.

But this is not a problem. You can close the issue.
