### ISSUE TITLE
i2pd creates pidfile by default

### ISSUE THREAD

**Issue by dartraiden** [PurpleI2P/i2pd#1136]
But docs and config say:

```
## Where to write pidfile (don't write by default)
# pidfile = /var/run/i2pd.pid
```

**Comment by r4sas** [comment]
Он не создается (по крайней мере на винде)

**Comment by orignal** [comment]
По хорошему лучше доки поправить.  Это полезная вещь чтобы случайно не запустить дважды.

**Comment by dartraiden** [comment]
Может, тогда по умолчанию включить pidfile на всех платформах?

**Comment by r4sas** [comment]
Винды это никак не коснется, ибо тут это реализуется посредством WinAPI

**Comment by radfish** [comment]
Повторный запуск не должен сработать с без пид файла из-за повторного использования портов, нет?

**Comment by orignal** [comment]
скорее всего просто напишет ошибку
