### ISSUE TITLE
Memory leaks in 2.18.0

### ISSUE THREAD

**Issue by nwmcsween** [PurpleI2P/i2pd#1144]
Using OpenWRT with I2pd running XD I2P torrent client results I2pd leaking roughly 1MB/30m. Debugging would be hard to impossible on the OpenWRT device so I could only provide basic info.

**Comment by majestrate** [comment]
Yes this is known, it's a long persisting bug in SAM I have been tracking for about a year now. ;~;

**Comment by nwmcsween** [comment]
The hacky workaround for this is to add a i2pd service restart to cron every x hours (3-4)

**Comment by radfish** [comment]
FWIW, I'm not seeing leaks on 2.18.0.r132.gca1fa11c with XD running. XD is seeding a couple torrents, without much (or any) activity, though.
Arch Linux on aarch64

**Comment by r4sas** [comment]
status?

**Comment by r4sas** [comment]
t/o
