### ISSUE TITLE
Hardcoded "datadir" path

### ISSUE THREAD

**Issue by AcidBear** [PurpleI2P/i2pd#1148]
Привет.

Опять я со своей NetBSD. Проблема в следующем: в дефолтном конфиге для этой системы я указал `datadir` как `/usr/pkg/var/i2pd`, но с опцией --service клиент все равно продолжает ломиться в `/var/lib/i2pd`.

Можно ли сделать так, чтобы клиент брал `datadir` из конфига? Ну, или при условии, что нет директории `/var/lib/i2pd`. Если я правильно понял, то за это отвечает вот [этот](https://github.com/PurpleI2P/i2pd/blob/fd1aeeac92ba062de81bb976d3168ef0cec2b51e/libi2pd/FS.cpp#L81) код

**Comment by orignal** [comment]
Согласен. Следует поправить. Этот код там давным давно когда datadir еще не было.

**Comment by r4sas** [comment]
Выносим `--service`?

**Comment by r4sas** [comment]
Результат таков:
https://wip.pkgsrc.org/cgi-bin/gitweb.cgi?p=pkgsrc-wip.git;a=blob;f=i2pd/files/i2pd.in;h=7a69ad0879df469539dbe6e34c7825888db5bef5;hb=HEAD

Если верить данному init скрипту, проблема в том, что вы не передаете `--datadir` при запуске, а пытаетесь указать его в конфиге.
Конфиг не имеет приоритета перед ключами запуска, поэтому чтение данного параметра из конфига всегда будет игнорироваться при указании `--service`.

В вашем случае, есть только 2 варианта - либо делать патч FS.cpp (что делается сейчас), либо указывать `--datadir=@PREFIX@/var/lib/i2pd` в rcd скрипте.
