### ISSUE TITLE
https://reseed.memcpy.io/ reseed certificate is removed

### ISSUE THREAD

**Issue by l-n-s** [PurpleI2P/i2pd#1177]
f537e7b2c698f1902e042c1183a85f5738e75718 removes `contrib/certificates/reseed/hottuna_at_mail.i2p.crt`, but we still have https://reseed.memcpy.io/ url in config

**Comment by l-n-s** [comment]
@orignal why it was removed and should we remove it from config?

**Comment by orignal** [comment]
Probably by mistake, If it still works put it back

**Comment by l-n-s** [comment]
It is working, I've restored the cert
