### ISSUE TITLE
qt gui bug: multiline paste at single line editbox - crash

### ISSUE THREAD

**Issue by mewmew-i2p** [PurpleI2P/i2pd#1180]
it saves multiline into tunnels.conf file but then crashes the app

**Comment by nonlinear-chaos-order-etc-etal** [comment]
test case:
 * created new client tunnel called "name1"
 * pasted the following into tunnel's name after name1 w/o quotes: "a
b
c
d
e
".
 * we see that tunnel settings now contain 0 content = 0 tunnels.
