### ISSUE TITLE
qt gui needs to be pixel perfect

### ISSUE THREAD

**Issue by mewmew-i2p** [PurpleI2P/i2pd#1187]
```
<Christophor_Bonifatyevitch_> villain, нада этот гуй делать pixel perfect
<Christophor_Bonifatyevitch_> как в телеге и вк
<Christophor_Bonifatyevitch_> а то щас тяп ляп
```

**Comment by nonlinear-chaos-order-etc** [comment]
Also the MainWindow needs to be resizable.

**Comment by nonlinear-chaos-order-etc-etal** [comment]
WONTFIX FOR NOW, IF YOU NEED THIS DO A PR. ПОНТЫ ЭТО ВСЁ НЕНУЖНЫЕ, ГЛАВНОЕ ЧТОБЫ ДЕЛО ДЕЛАЛО, USSR WAR MACHINES RULE

**Comment by nonlinear-chaos-order-etc-etal** [comment]
@r4sas ПРОСЬБА ПРИБИТЬ ЭТОТ ИССУЕ, ЗАКРОЙ ПЛИЗ... ДОЛГО ИСКАТЬ ПАРОЛЬ ОТ @mewmew-i2p , ВОЗМОЖНО УТЕРЯН.
