### ISSUE TITLE
Accessing clearnet sites over HTTP doesn't work

### ISSUE THREAD

**Issue by Cole128** [PurpleI2P/i2pd#1191]
Basically the title. I have setup 127.0.0.1:4444 as my proxy, but I can't visit any sites that don't use SSL, or HTTPS. If I try to, I get this error on the webpage:

Proxy error: Outproxy failure
Host domain.com not inside I2P network, but outproxy is not enabled

The log gives me this kind of error:
HTTPProxy: outproxy failure for 127.0.0.1: no outprxy enabled
or
HTTPProxy: outproxy failure for domain.com: no outprxy enabled

I've starting using privoxy, and it works fine, as only i2p sites are passed to i2pd, but I still think this issue shouldn't be happening.

**Comment by r4sas** [comment]
> Host domain.com not inside I2P network, but outproxy is not enabled

Please read documentation firstly.

**Comment by orignal** [comment]
you must specify outproxy in for httpprxoy config explicitly
