### ISSUE TITLE
I2Pd не стартует после перезагрузки Ubuntu 18.04

### ISSUE THREAD

**Issue by dimqua** [PurpleI2P/i2pd#1192]
`AVC apparmor="DENIED" operation="file_lock" profile="/usr/sbin/i2pd" name="/run/i2pd/i2pd.pid" pid=2706 comm="i2pd" requested_mask="k" denied_mask="k"`

Решение [здесь](https://github.com/PurpleI2P/i2pd/commit/d8b4765f23952ad6ae5c816cfd30ef88facd2d89#diff-3dd6f7bd744e97f20a55659e62057d55R25), но не попало в версию 2.18.

**Comment by r4sas** [comment]
Ну так релиз был в конце февраля, а этот коммит - месяц назад.

**Comment by rodin-ia** [comment]
Ubuntu 18.04 
kernel 4.17.1-041701-generic
i2pd version 2.18.0 (0.9.33)
i2pd стартует но в dmsg сообщение от apparmor: 
kernel: [   39.144579] audit: type=1400 audit(1528874757.884:28): apparmor="DENIED" operation="open" profile="/usr/sbin/i2pd" name="/run/systemd/resolve/stub-resolv.conf" pid=1085 comm="i2pd" requested_mask="r" denied_mask="r" fsuid=120 ouid=101
Возможно имеет смысл добавить правило:
/run/systemd/resolve/stub-resolv.conf r,

**Comment by l-n-s** [comment]
Ох уж этот systemd...
