### ISSUE TITLE
i2pd looking for older libboost_system version than Arch Linux has

### ISSUE THREAD

**Issue by makeworld-the-better-one** [PurpleI2P/i2pd#1193]
i2pd gave me an error on startup today:
`/usr/sbin/i2pd: error while loading shared libraries: libboost_system.so.1.66.0: cannot open shared object file: No such file or directory`

I am on Arch Linux, and the newest boost-libs is version 1.67, while i2pd is still looking for 1.66. I can solve this by downgrading boost and boost-libs to version 1.66, but I just thought you should know.

**Comment by r4sas** [comment]
If you builded package, for example from AUR, it will be linked to libraries which exists in system at compile time. So if you upgrading libraries, you must rebuild package yourself.

**Comment by l-n-s** [comment]
Status of the issue? Should we close it?

**Comment by makeworld-the-better-one** [comment]
@l-n-s Yeah, I can close it, sorry I forgot to.
