### ISSUE TITLE
Doesn't start in Debian

### ISSUE THREAD

**Issue by LLE8** [PurpleI2P/i2pd#1196]
Fresh trunk.  Debian Stretch and Jessie.
In /etc/init.d/i2pd in do_start() function
```
  start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --chuid "$USER" -- \
    --service --daemon --log=file --logfile=$LOGFILE --conf=$I2PCONF --tunconf=$TUNCONF \
    --pidfile=$PIDFILE $DAEMON_OPTS > /dev/null 2>&1 \
    || return 2
```
but should be, i think
```
  start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --chuid "$USER" -- \
    --service=1 --daemon=1 --log=file --logfile=$LOGFILE --conf=$I2PCONF --tunconf=$TUNCONF \
    --pidfile=$PIDFILE $DAEMON_OPTS > /dev/null 2>&1 \
    || return 2
```
Or revert to old --service and --daemon options format in i2pd binary?
Look at i2pd --help in 2.18 and fresh trunk.

And why fresh trunk generates i2pd_2.19.0-1_amd64.deb package? Is it new release 2.19?
But i2pd --help says 2.18.

**Comment by r4sas** [comment]
Пакет собрался как 2.19.0 потому что я залил заготовку с изменениями в debian/Changelog.
По поводу добавления `=1` - сейчас гляну.

**Comment by LLE8** [comment]
Или может быть =on или =true

**Comment by r4sas** [comment]
Знаю о этом, но там как раз думаем как лучше сделать. По идее коррекно было бы через true, а с другой стороны удобнее без указания чего либо.

**Comment by LLE8** [comment]
Да лишь бы запускалось, а иначе не стартует без каких-либо намеков на причину.

**Comment by LLE8** [comment]
Можно закрывать, думаю.
