### ISSUE TITLE
repo.i2pd.xyz problem

### ISSUE THREAD

**Issue by LLE8** [PurpleI2P/i2pd#1210]
```
# apt-get update
......
Err https://repo.i2pd.xyz jessie/main amd64 Packages
  HttpError400
Fetched 155 kB in 12s (12.8 kB/s)
W: Failed to fetch https://repo.i2pd.xyz/debian/dists/jessie/main/binary-amd64/Packages  HttpError400

E: Some index files failed to download. They have been ignored, or old ones used instead.

#apt-get install i2pd
......
WARNING: The following packages cannot be authenticated!
  i2pd
Install these packages without verification? [y/N]
```

**Comment by r4sas** [comment]
У меня временно проблемы с сетью там, так что ждем когда исправят.
После этого поправлю слетевшую конфигурацию у nginx, и все будет работать в штатном режиме.

**Comment by r4sas** [comment]
`journalctl -xn` что нибудь говорит при запуске через systemd?

**Comment by LLE8** [comment]
это?
```
Jul 10 17:26:11 serv07 systemd[1]: [/lib/systemd/system/i2pd.service:11] Unknown lvalue 'LogsDirectory' in section 'Service'
Jul 10 17:26:11 serv07 systemd[1]: [/lib/systemd/system/i2pd.service:12] Unknown lvalue 'LogsDirectoryMode' in section 'Service'
```

**Comment by r4sas** [comment]
Оно и не должно запускаться автоматически при установке.

То что ругается - это параметры, которые доступны в более новых версиях systemd, и на работу не влияют.

**Comment by LLE8** [comment]
А на Stretch, тоже systemd, запускается автоматически при установке.

**Comment by LLE8** [comment]
Причем на Jessie он пытается запуститься, но неудачно
```
root@serv07:~# apt-get install i2pd
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  ca-certificates-java default-jre-headless fontconfig-config fonts-dejavu fonts-dejavu-core fonts-dejavu-extra
  glassfish-javaee java-common libasyncns0 libavahi-client3 libavahi-common-data libavahi-common3 libcups2 libflac8
  libfontconfig1 libgetopt-java libice6 libjpeg62-turbo liblcms2-2 libnspr4 libnss3 libogg0 libpulse0 libsctp1
  libservice-wrapper-java libservice-wrapper-jni libsm6 libsndfile1 libvorbis0a libvorbisenc2 libx11-6 libx11-data
  libx11-xcb1 libxau6 libxcb1 libxdmcp6 libxext6 libxi6 libxtst6 openjdk-7-jre-headless service-wrapper ttf-dejavu
  ttf-dejavu-core ttf-dejavu-extra tzdata-java x11-common
Use 'apt-get autoremove' to remove them.
The following NEW packages will be installed:
  i2pd
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/794 kB of archives.
After this operation, 2,813 kB of additional disk space will be used.
Selecting previously unselected package i2pd.
(Reading database ... 55997 files and directories currently installed.)
Preparing to unpack .../i2pd_2.19.0-1jessie1_amd64.deb ...
Unpacking i2pd (2.19.0-1jessie1) ...
Processing triggers for man-db (2.7.0.2-5) ...
Processing triggers for systemd (215-17+deb8u7) ...
Setting up i2pd (2.19.0-1jessie1) ...
usermod: no changes
Job for i2pd.service failed. See 'systemctl status i2pd.service' and 'journalctl -xn' for details.
invoke-rc.d: initscript i2pd, action "start" failed.
dpkg: error processing package i2pd (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for systemd (215-17+deb8u7) ...
Errors were encountered while processing:
 i2pd
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@serv07:~#
```

**Comment by r4sas** [comment]
>Большинство популярных сервисов, если не все, также запускаются при установке автоматически.

Не знаю, я как раз таки во всех случаях добавлял их в автозапуск и запускал вручную, и это было на Stretch.

>Причем на Jessie он пытается запуститься, но неудачно
>journalctl говорит в т.ч. такое

Посмотрю на досуге.

**Comment by l-n-s** [comment]
@LLE8 

>  Большинство популярных сервисов, если не все, также запускаются при установке автоматически.

С i2pd другая история. Нужно дать пользователю возможность настроить, не сразу ломиться в сеть дефолт конфигом.

**Comment by LLE8** [comment]
Возможно, лучше сразу не ломиться в сеть. Но спецмально так НЕ сделано, это просто баг какой-то так проявляется, предполагаю. В Stretch сразу успешно ломится, а в Jessie пытается сразу ломиться, но у него не получается почему-то. А в разных Убунтах как?

**Comment by LLE8** [comment]
Свежий транк ведет себя так же
```
Jul 12 20:00:03 serv07 systemd[1]: [/lib/systemd/system/i2pd.service:11] Unknown lvalue 'LogsDirectory' in section 'Service'
Jul 12 20:00:03 serv07 systemd[1]: [/lib/systemd/system/i2pd.service:12] Unknown lvalue 'LogsDirectoryMode' in section 'Servic
e'
Jul 12 20:00:03 serv07 systemd[1]: Starting I2P Router written in C++...
-- Subject: Unit i2pd.service has begun with start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit i2pd.service has begun starting up.
Jul 12 20:00:03 serv07 systemd[1]: Failed to reset devices.list on /system.slice: Invalid argument
Jul 12 20:00:03 serv07 systemd[5971]: Failed at step RUNTIME_DIRECTORY spawning /usr/sbin/i2pd: File exists
-- Subject: Process /usr/sbin/i2pd could not be executed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- The process /usr/sbin/i2pd could not be executed and failed.
--
-- The error number returned while executing this process is 17.
Jul 12 20:00:03 serv07 systemd[1]: i2pd.service: control process exited, code=exited status=233
Jul 12 20:00:03 serv07 systemd[1]: Failed to start I2P Router written in C++.
-- Subject: Unit i2pd.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit i2pd.service has failed.
--
-- The result is failed.
Jul 12 20:00:03 serv07 systemd[1]: Unit i2pd.service entered failed state.
```

**Comment by r4sas** [comment]
Попробуй закоментить перед сборкой пакета, потом посмотри.
https://github.com/PurpleI2P/i2pd/blob/0b367329114f44a1d4cc7b6cbd21de4289e50833/contrib/i2pd.service#L9-L10

**Comment by LLE8** [comment]
Похоже помогло.

**Comment by r4sas** [comment]
Ну здесь только такой вариант.
В понедельник соберу пакеты с исправлением, и залью в репу.

**Comment by r4sas** [comment]
@LLE8 если есть возможность, можешь глянуть как ведет себя эта фигня на убунтах 16, 18?

**Comment by LLE8** [comment]
Ubuntu 16.04
В процессе установки не запускается, пишет такое
```
root@cs283275:~# systemctl status i2pd.service
● i2pd.service - I2P Router written in C++
   Loaded: loaded (/lib/systemd/system/i2pd.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2018-07-15 20:09:42 MSK; 8min ago
     Docs: man:i2pd(1)
           https://i2pd.readthedocs.io/en/latest/

Jul 15 20:13:06 cs283275 systemd[1]: [/lib/systemd/system/i2pd.service:11] Unknown lvalue 'LogsDirectory' in section 'Service'
Jul 15 20:13:06 cs283275 systemd[1]: [/lib/systemd/system/i2pd.service:12] Unknown lvalue 'LogsDirectoryMode' in section 'Service'
Jul 15 20:17:12 cs283275 systemd[1]: [/lib/systemd/system/i2pd.service:11] Unknown lvalue 'LogsDirectory' in section 'Service'
Jul 15 20:17:12 cs283275 systemd[1]: [/lib/systemd/system/i2pd.service:12] Unknown lvalue 'LogsDirectoryMode' in section 'Service'
Jul 15 20:17:12 cs283275 systemd[1]: [/lib/systemd/system/i2pd.service:11] Unknown lvalue 'LogsDirectory' in section 'Service'
Jul 15 20:17:12 cs283275 systemd[1]: [/lib/systemd/system/i2pd.service:12] Unknown lvalue 'LogsDirectoryMode' in section 'Service'
Jul 15 20:17:12 cs283275 systemd[1]: [/lib/systemd/system/i2pd.service:11] Unknown lvalue 'LogsDirectory' in section 'Service'
Jul 15 20:17:12 cs283275 systemd[1]: [/lib/systemd/system/i2pd.service:12] Unknown lvalue 'LogsDirectoryMode' in section 'Service'
Jul 15 20:17:12 cs283275 systemd[1]: [/lib/systemd/system/i2pd.service:11] Unknown lvalue 'LogsDirectory' in section 'Service'
Jul 15 20:17:12 cs283275 systemd[1]: [/lib/systemd/system/i2pd.service:12] Unknown lvalue 'LogsDirectoryMode' in section 'Service'
```
по команде `systemctl start i2pd.service` запускается

**Comment by LLE8** [comment]
Ubuntu 18.04
Запускается при установке автоматически, ошибок не заметил

**Comment by r4sas** [comment]
@LLE8, спасибо. Тогда пересоберу только их. Видать в старых версиях все печально с этими параметрами.

**Comment by LLE8** [comment]
Права доступа к pid-файлу важны? `-rw-------` или `-rw-r--r--` ?

**Comment by LLE8** [comment]
Для 17.04 пакета нет?

**Comment by r4sas** [comment]
Не важны.

17.04 не существует ;)
17.10 вышел из поддержки.

**Comment by LLE8** [comment]
http://old-releases.ubuntu.com/releases/17.04/
https://habr.com/company/selectel/blog/326408/
хотя он тоже закончился 13 января

**Comment by LLE8** [comment]
Когда зальете пересобранные, скажите, попробую.

**Comment by r4sas** [comment]
@LLE8, залил, можно проверять.

**Comment by r4sas** [comment]
Убунту я еще не делал, на данный момент только деб. Но поскольку все в норме, то тогда и их пересоберу.

**Comment by LLE8** [comment]
LogsDirectory и LogsDirectoryMode появились в systemd 235  2017-10-06, т.е. только в Ubuntu 18.04 и Debian testing/sid
RuntimeDirectory= и RuntimeDirectoryMode= появились в systemd 211  2014-03-12, т.е. во всех актуальных убунтах и дебианах должны быть.
https://github.com/systemd/systemd/blob/master/NEWS
https://distrowatch.com/table.php?distribution=ubuntu
https://distrowatch.com/table.php?distribution=debian
Поэтому 
RuntimeDirectory=i2pd и RuntimeDirectoryMode=0700 можно оставить скорее всего, 
а LogsDirectory и LogsDirectoryMode пока убрать.
Кажется, я вас обманул :), убрал LogsDirectory и LogsDirectory, а не так, как вы попросили RuntimeDirectory и RuntimeDirectoryMode.
Попробую еще раз.

**Comment by r4sas** [comment]
Да вообще, я решил для пакетов их убрать, ибо они не делают погоды. Небольшой патч в папку debian не такая уж большая проблема.

**Comment by LLE8** [comment]
Уточнение.
Debian Jessie, systemd  215-17+deb8u7.

Так
```
#RuntimeDirectory=i2pd
#RuntimeDirectoryMode=0700
LogsDirectory=i2pd
LogsDirectoryMode=0700
```
работает,
а так
```
RuntimeDirectory=i2pd
RuntimeDirectoryMode=0700
#LogsDirectory=i2pd
#LogsDirectoryMode=0700
```
не работает, ругается непонятно на что.
Согласен, лучше все это отключить пока.

**Comment by LLE8** [comment]
Здесь https://github.com/PurpleI2P/i2pd/releases/tag/2.19.0  пакеты не заменили?

**Comment by r4sas** [comment]
Я еще до убунтовских пакетов даже не дотянулся, куда уж там то.

**Comment by LLE8** [comment]
Может в инструкцию по сборке
https://i2pd.readthedocs.io/en/latest/devs/building/unix/#debian-ubuntu
добавите слова про отключение этих опций для Jessie и старых Ubuntu?
```
#RuntimeDirectory=i2pd
#RuntimeDirectoryMode=0700
#LogsDirectory=i2pd
#LogsDirectoryMode=0700
```

**Comment by r4sas** [comment]
А надо ли? Тот, кто наткнется на проблему надеюсь поиском умеет работать. А в репу я перезаливал опять пакеты с отключением.

**Comment by LLE8** [comment]
Может и айдет в хвосте темы с совершенно непохожим названием.
