### ISSUE TITLE
AEAD does not works correctly with OpenSSL 1.1 on NTCP2

### ISSUE THREAD

**Issue by r4sas** [PurpleI2P/i2pd#1217]
AEADChaCha20Poly1305 not correctly works as said @orignal.

**Comment by majestrate** [comment]
Not a surprise, it's openssl after all.

This is why i provided chacha20 and poly1305 code :^)

**Comment by orignal** [comment]
@majestrate, no, that's not openssl, that's my code where I call openssl. And I did something worng there. Will fix it shortly.
You code is used with openssl below 1.0.2 but @r4sas uses 1.1
