### ISSUE TITLE
Web Console won't work on 0.0.0.0

### ISSUE THREAD

**Issue by yangfl** [PurpleI2P/i2pd#1227]
I have a server with dynamic IP that runs i2pd. While I could protect web console with authentication, I can't specify listening address to be 0.0.0.0, otherwise I'll always get a simple error "host mismatch".

Please consider adding an opt-out option for this protection.

**Comment by radfish** [comment]
On Fri, Aug 17, 2018 at 08:50:29PM -0700, yangfl wrote:
> I have a server with dynamic IP that runs i2pd. While I could protect
> web console with authentication, I can't specify listening address to
> be 0.0.0.0, otherwise I'll always get a simple error "host mismatch".

I bind to LAN interface (like 192.168.x.x), and only get 'host
mismatch' if I access the i2pd host from another LAN host via hostname
as opposed to via IP. Do you get this error when you access by IP?
I'm not sure, but it might not be related to bind address, but only
related to the domain in your browser's GET requests.

**Comment by yangfl** [comment]
@radfish Yes, that is yet another problem with it, that it strictly checks the host in the request against IP address, ignoring possible hostname.

**Comment by l-n-s** [comment]
Option `http.hostname` must match "localhost" by default, you can adjust this to your use case.

`http.strictheaders` option disables strict check, but opens a possibility for cross-domain deanonymization attack vectors.
