### ISSUE TITLE
Add SSL tunnels support

### ISSUE THREAD

**Issue by ReK2Fernandez** [PurpleI2P/i2pd#1228]
Hello on the old java client I remember I was able to create a tunnel to port 443 and then add a https proxy to visit it.. I went to do the same thing on my i2pd setup and was not  able to find examples with https. I know you doing to say no need to use https on i2p.. true. but this is a already live website on clearnet that I want to pipe also into i2p and only listens for https connections and forwards all http to https on nginx. I may be blind and did not see the example. can someone tell me if this is still possible? I did true with regular server type not http and did not load.
Thanks! and I love i2pd

**Comment by orignal** [comment]
You can't create "https" server tunnel, you must use regular one, because "Host" header is inside encrypted content. Beside it, https works both for client and server side. For example, we used it for telegram recently

**Comment by l-n-s** [comment]
Java implementation has some kind of SSL tunnels, which i2pd doesn't have yet. Not sure how they work, will look into this issue and update later.

**Comment by ReK2Fernandez** [comment]
@l-n-s hey thanks for looking, but I do not want to use the java version of i2p I only came back to use i2p after you guys started to develop a non java client/router. I refuse to install java on any of my systems, specially because is bloated, and does not follow unix conventions. i2pd does :) and I love it.

**Comment by ReK2Fernandez** [comment]
@orignal so the "type http" should work for sure? for both? like if I give my .i2p address to someone and say hey connect to https://myb32.i2p  or http:myb32.i2p:443 will work? I tried both ways .. and times out maybe I did something wrong?
example:

```
[http-in]
type = http
host = 127.0.0.1
port = 443
keys = mysite.dat
```

**Comment by l-n-s** [comment]
`http` type tunnel won't work with https server, cause it deals with plaintext http headers.

`server` type tunnel to the same host/port should work, and your clients will have to use i2pd Socks proxy.

**Comment by orignal** [comment]
you must create tunnel with type=server

**Comment by ReK2Fernandez** [comment]
thanks guys I will try when I get home tonight.

**Comment by r4sas** [comment]
idk, but it possible open HTTPS with default setting:
![image](https://user-images.githubusercontent.com/7023612/44588057-60d48c80-a7bd-11e8-8572-9bd331ebca25.png)

**Comment by ReK2Fernandez** [comment]
@l-n-s @orignal it works!!! https://tibqaokyoc74mljuwng5ugulim4jfv6ql7j5vocqfjyrjwxrz6qa.b32.i2p:443
is our mastodon server on clear-net, now on i2p... any tricks to speed it up? create more tunnels or some other way?
thanks <3

**Comment by majestrate** [comment]
if you don't mind the server being less anonymous lower the tunnel length.

also the TLS CA monopoly frowns on the .i2p tld and google chrome gives a SNI warning with a scary page.

**Comment by ReK2Fernandez** [comment]
@majestrate yeah I can image, but I guess if anyone wants to use it, will just have to ignore it or something.
Regarding the speed, yeah I don't mind been anonymous since this is a clear net service is just to give the option to people that do want to not log their ip on my server the opportunity to do so, etc.

**Comment by majestrate** [comment]
If you don't care about anonymity of the server you can use 0 hop tunnels for max performance.

**Comment by ReK2Fernandez** [comment]
@majestrate something like this?
```
[http-in]
type = server
host = 127.0.0.1
port = 443
inbound.length = 0
inbound.quantity = 5
outbound.length = 0
outbound.quantity = 5
keys = website.dat
```

**Comment by majestrate** [comment]
yes

**Comment by orignal** [comment]
I wouldn't recommend 0 hops, because you might not be reachable from everywhere. That's today's Internet's reality.

**Comment by l-n-s** [comment]
1 hop tunnels are recommended for optimal reliability and speed
