### ISSUE TITLE
[Docker] build from Dockerfile fails.

### ISSUE THREAD

**Issue by Paul-Stern** [PurpleI2P/i2pd#1232]
After trying to build the image I get this error:
`Step 14/20 : COPY entrypoint.sh /entrypoint.sh`
`COPY failed: stat /var/lib/docker/tmp/docker-builder291681106/entrypoint.sh: no such file or directory`
Not sure I've done everything right. I just downloaded the Dockerfile and started building. That's all the steps I did. Didn't find any building instructions.
Thank you beforehand.

**Comment by r4sas** [comment]
You must place [entrypoint.sh](https://raw.githubusercontent.com/PurpleI2P/i2pd/openssl/contrib/docker/entrypoint.sh) near Dockerfile.

**Comment by l-n-s** [comment]
Yep, docker build directory must have entrypoint.sh file. Let us know if you have any other issues.
