### ISSUE TITLE
Можно ли увеличить скорость в ущерб анонимности?

### ISSUE THREAD

**Issue by ljgdasfhk** [PurpleI2P/i2pd#1236]
Можно ли сделать так, чтобы клиенты соединялись друг с другом напрямую, а не через десяток других узлов ?

**Comment by orignal** [comment]
поставить длину тоннелей в 0

**Comment by ljgdasfhk** [comment]
Как это сделать?
Я вижу в настройках только exploratory.inoutbound.length
Но это наверно не то, что я ищу.

4 сентября 2018 г. 14:06:50 GMT+03:00, orignal <notifications@github.com> пишет:

**Comment by orignal** [comment]
inbound.length, outbound.length для соответствующего тоннеля

**Comment by l-n-s** [comment]
https://i2pd.readthedocs.io/en/latest/user-guide/tunnels/#i2cp-parameters

Это делается для каждого отдельного туннеля в конфиге `tunnels.conf`. Рекомендуется делать длину в 1 хоп, а не 0, для большей надежности.

**Comment by ljgdasfhk** [comment]
т.е. должно быть inbound.length=1, outbound.length=1 ?

**Comment by l-n-s** [comment]
да

**Comment by orignal** [comment]
можно ставить что угодно и будут соединяться. с 0 проблема в том что в наше время не всегда любой IP адрес может соединиться с другим IP адресом

**Comment by ljgdasfhk** [comment]
Поясните, пожалуйста,
На компьютере A длина исходящего туннеля 0 , а на компьютере B длина входящего туннеля 1.
Какой будет маршрут А->B или А->C->B ?
Почему некоторые адреса нельзя соединить ?

**Comment by orignal** [comment]
будет A->C->B где C - произврльно выбранный узел тоннеля на B

Бывает нельзя соедининить потому что стало слишком много любителей блокировать.

**Comment by ljgdasfhk** [comment]
Если блокируется трафик A или B, то разве получится их соединить с помощью промежуточных узлов C ?

**Comment by l-n-s** [comment]
@ljgdasfhk имеется в виду, что блокируется прямое соединение между А и B. В таком случае C выступит как прокси-сервер.

**Comment by ljgdasfhk** [comment]
И если я уверен, что прямое соединение А и B не блокируется, то можно смело ставить длину туннелей 0

**Comment by orignal** [comment]
Почему не подходит? Эта фраза означает лишь что оба конца тоннеля на одном и том же узле

**Comment by ljgdasfhk** [comment]
Что-то я потерял мысль.
Надо соединить два компа. Это значит - соединить два узла - или нет ?
Если у узла A начальная и конечная точка туннеля будут находиться на узле А (0-hop tunnel) и тоже самое будет на узле B, то чем будут соединяться A и B ?

**Comment by orignal** [comment]
Есть узлы, это физические процессы с IP адресами, а есть I2P адреса которые работают через тоннели, построенные через узлы. Соединять разумеется надо I2P адреса, но с тоннелями нулевой длины это фактически соединение узлов.

**Comment by ljgdasfhk** [comment]
Если ставлю в конфиге сервера нулевую длину для вх. И исх., то соединиться с ним не получается.

**Comment by ljgdasfhk** [comment]
Один из узлов должен иметь белый ip ?

**Comment by orignal** [comment]
Не обязательно. Могут и оба быть Firewalled, но соединяться будет дольше

**Comment by ljgdasfhk** [comment]
Интересно... два узла с нулевыми туннелями найдут друг друга без ip адресов ?

**Comment by orignal** [comment]
Они же не вакууме находятся, а знают об отсальной сети. Потому во первых они свои внешние IP знают, а во вторых могут пробивать дыры в NAT с помощью introducer-ов

**Comment by ljgdasfhk** [comment]
Если на сервере за натом поставить 0 в длине туннелей, то подключиться к нему не получается. Если 1, то подключается.
Как на стороне киента узнать, что подключение к серверу уже установлено?

**Comment by ljgdasfhk** [comment]
> Не обязательно. Могут и оба быть Firewalled, но соединяться будет дольше

> Они же не вакууме находятся, а знают об отсальной сети. Потому во первых они свои внешние IP знают, а во вторых могут пробивать дыры в NAT с помощью introducer-ов

Оказывается, они таки в вакууме находятся и пробивать НАТы без узлов с "белыми" адресами не могут.
