### ISSUE TITLE
chocolatey package for i2pd is deprecated

### ISSUE THREAD

**Issue by chantisnake** [PurpleI2P/i2pd#1237]
I was the maintainer for the [chocolatey](https://chocolatey.org/) package for i2pd.
  I am deprecating the chocolatey package for i2pd because I no longer have time to maintain it.

  I have requested for another package maintainer here: https://github.com/chocolatey/chocolatey-package-requests/issues/419
  The chocolatey package page for i2pd : https://chocolatey.org/packages/i2pd

  Sorry for all the inconvenience I have caused.

  (This issue is created automatically, some of the links may be wrong, please inform me if You want me to change them.)

**Comment by r4sas** [comment]
I can handle it, but can you explain how to maintain it?

**Comment by chantisnake** [comment]
To maintain it, you need a chocolatey account. Then you can just go to https://github.com/chocolatey/chocolatey-package-requests/issues/419, tell them you want to be the maintainer, and provide them your account Id.

**Comment by r4sas** [comment]
And about package itself. It contain one powershell script only?

**Comment by chantisnake** [comment]
This is the latest version of the package https://github.com/chantisnake/chocolateyPackage/tree/master/i2pd-choco/Versions/2.11.0, you can use this as a template.

When i2pd updated,
- go into this file https://github.com/chantisnake/chocolateyPackage/blob/master/i2pd-choco/Versions/2.11.0/tools/chocolateyinstall.ps1 update the install link, the sha256 hash.
- go into this filehttps://github.com/chantisnake/chocolateyPackage/blob/master/i2pd-choco/Versions/2.11.0/i2pd.nuspec update the version and the release note.

finally run this two commands (make sure chocolatey has agreed to make you the maintainer of this package)
- choco pack
- choco push
and type in your chocolatey api key.

For details about maintain in chocolatey packages, refers to this document: https://chocolatey.org/docs/create-packages

**Comment by r4sas** [comment]
@chantisnake finally I created repo here: https://github.com/r4sas/chocolatey-packages/tree/master/i2pd
To finish transfer I must publish package with same version or I must wait till our next release and publish it?

**Comment by chantisnake** [comment]
I think next version would be the best.

**Comment by chantisnake** [comment]
If you need to publish a change to current version (for example 1.0.0), you can publish a version 1.0.0.07092018 (07092018 is today's date)

**Comment by K1773R** [comment]
if you do date versioning, do it right: 20180907 ISO

**Comment by chantisnake** [comment]
lol, sorry, my bad...

**Comment by r4sas** [comment]
New version submitted, so closing that issue.
