### ISSUE TITLE
Out-of-date URLs in *.conf

### ISSUE THREAD

**Issue by phongiswindy** [PurpleI2P/i2pd#1238]
https://github.com/PurpleI2P/i2pd/blob/db5a40d743e8e03f4614ea595997f3e26a0b73fe/android/assets/i2pd.conf

 and 

https://github.com/PurpleI2P/i2pd/blob/b226e22d2fead08013c23d13888c90429c29ea36/contrib/i2pd.conf

https://i2pd.readthedocs.io/en/latest/configuration.html
Should be: https://i2pd.readthedocs.io/en/latest/user-guide/configuration/ ?

**Comment by l-n-s** [comment]
Sure, thanks
