### ISSUE TITLE
ssh over i2p

### ISSUE THREAD

**Issue by ljgdasfhk** [PurpleI2P/i2pd#1241]
I want to connect using the SSH from computer A to computer B.

<details>
  <summary>Tunnel configuration on A:</summary>

```
[ssh]
type = client
address = 127.0.0.1
port = 12467
inbound.length = 0
outbound.length = 0
inbound.quantity = 4
outbound.quantity = 4
destination = address-B.b32.i2p
keys = ssh-keys.dat
```

</details>

<details>
  <summary>Tunnel configuration on B:</summary>

```
[ssh]
type = server
host = 127.0.0.1
port = 12467
inbound.length = 0
outbound.length = 0
inbound.quantity = 4
outbound.quantity = 4
keys = ssh-keys.dat
```

</details>

<details>
  <summary>i2pd.conf</summary>

  ```
daemon = true
ipv4 = true
ipv6 = false
nat = true
bandwidth = X
share = 10
floodfill = true

[http]
address = 127.0.0.1
port = 7070

[httpproxy]
address = 127.0.0.1
port = 43434

[socksproxy]
address = 127.0.0.1
port = 4447

[sam]
enabled = true

[upnp]
enabled = true

[reseed]
verify = true

[ntcp2]
enabled=true
published=true
port=443
```

</details>

For some reason I can not connect to these parameters.
But if you put the length of tunnels 1 on the server, then the connection is immediately established.
Why?

**Comment by K1773R** [comment]
lenght 0 means direct. is one of your instances firewalled (i2pd port)?

**Comment by ljgdasfhk** [comment]
I just need a direct connection.
in a neighboring topic I was told that this is possible.
both computers are behind NAT

**Comment by l-n-s** [comment]
Yeah, NAT is the reason. They can't directly connect to each other, since they need an "introducer" node in between. That can happen only if you have the length of 1 and more.

**Comment by ljgdasfhk** [comment]
What is  "introducer" node. My computer can not be "introducer" node ?

**Comment by orignal** [comment]
It can, if it's not behind NAT

**Comment by ljgdasfhk** [comment]
The introducer-node must have a "white" IP address?
If there are no such nodes, then the network will stop working?

**Comment by ljgdasfhk** [comment]
Please check out my settings.
How many should be the number of inbound.quantity=... , outbound.quantity=... ?
(for greater ssh-connection speed)

**Comment by orignal** [comment]
set to 3

**Comment by ljgdasfhk** [comment]
why exactly three

**Comment by l-n-s** [comment]
RTFM before asking same question again and again

https://geti2p.net/en/docs/how/tech-intro

https://geti2p.net/en/docs/transport
