### ISSUE TITLE
Add documentation for Linux static builds

### ISSUE THREAD

**Issue by iyesin** [PurpleI2P/i2pd#1244]
Hello.

I found no way to run i2pd without installing any deps.
Is there any way to build single statically linked binary of i2pd?

**Comment by orignal** [comment]
make USE_STATIC=yes

**Comment by majestrate** [comment]
a note:

for my unofficial static arm builds i use:

`make USE_AVX=no USE_AESNI=no USE_STATIC=yes INCFLAGS="-I$HOME/local/rpi/include" LIBDIR=$HOME/local/rpi/lib CXX=$HOME/local/rpi/arm-bcm2708hardfp-linux-gnueabi/bin/arm-bcm2708hardfp-linux-gnueabi-g++ CC=$HOME/local/rpi/arm-bcm2708hardfp-linux-gnueabi/bin/arm-bcm2708hardfp-linux-gnueabi-gcc CXXFLAGS=-Os -j16`

where `$HOME/local/rpi` is the root for my toolchain with boost, openssl and friends pre-compiled.
and `$HOME/local/rpi/arm-bcm2708hardfp-linux-gnueabi` contains my compiler

**Comment by r4sas** [comment]
t/o. Reopen if still required.
