### ISSUE TITLE
[SAM] Support for STREAM FORWARD is missing

### ISSUE THREAD

**Issue by Nyanraltotlapun** [PurpleI2P/i2pd#1252]
Missing support for STREAM FORWARD functionality.

**Comment by orignal** [comment]
what do you need it for?

**Comment by peacekeeperatlas** [comment]
I am just horsing around. Trying to understand how to use SAM and write some lib for it.

The idea was, that if I use forward, then it will work like ordinal TCP routine so I will be able to accept all incoming connections from forwarded socket.
But now I begin to think that this is not how its work.

**Comment by orignal** [comment]
I can add it, but I can't test it, because AFAIK there is no app using it

**Comment by majestrate** [comment]
from what I can tell every library uses `STREAM ACCEPT` as it is easier to implement being a closer analog to what the libraries use, i.e. emulating `accept(2)`

we can add `STREAM FORWARD` though.

**Comment by sehraf** [comment]
Are there any plans for implementing FORWARD support?
I want to move RetroShare from BOB to SAMv3 and FORWARD fits its networking code best. ACCEPT works too be requires some network related changes that are unnecessary with FORWARD.
(Also related, #1402, https://github.com/RetroShare/RetroShare/issues/2087 )

**Comment by orignal** [comment]
Thank you for reminding. Just forgot. Will take a look today.
Do you need SAM 3.1 or SAM 3.3?

**Comment by sehraf** [comment]
SAM 3.1 is enough.

**Comment by orignal** [comment]
Initial implementation is ready, but didn't test it yet

**Comment by sehraf** [comment]
Well that was fast! 
I've tested e41bbcb2bb12ae8a981c04f3aeec787fb53bbd92 with silent=true and false. While it works (i2pd forwards incoming connections and honors the silent option), the FORWARD request send to i2pd is not finished/answered, the actual `Forward Response` is not sent and the tcp connection is kept open.
(For the record: the webui displays the FORWARD session as `unknown`)

**Comment by orignal** [comment]
Do you mean you don't receive STREAM STATUS back to a "forwardring" connection?
WebUI will be fixed, thank you for hint.

**Comment by sehraf** [comment]
> Do you mean you don't receive STREAM STATUS back to a "forwardring" connection?
exactly!

**Comment by orignal** [comment]
Should work now, forgot that FORWARD must always reply regardless the silent flag.

**Comment by sehraf** [comment]
Yep, works now, thanks!
Any (rough) idea when there will be a new release?

**Comment by orignal** [comment]
Tommorow

**Comment by orignal** [comment]
Implemented in 2.34.0
