### ISSUE TITLE
[SAM] SESSION CREATE does not give any error if SIGNATURE_TYPE is incorrect value

### ISSUE THREAD

**Issue by peacekeeperatlas** [PurpleI2P/i2pd#1253]
SAM does not give any error if SIGNATURE_TYPE is incorrect value. And also wont return any destination as a result.

Example request:
"SESSION CREATE STYLE=STREAM ID=test DESTINATION=TRANSIENT SIGNATURE_TYPE=SOME-CHARS"

After this, no response from router.
Log shows "SAM: runtime exception: stoi"

As I understand, it is because it trying to parse SIGNATURE_TYPE as integer.

Expected:
Some error, or using default value and return valid destination.

**Comment by orignal** [comment]
It's more generic issue than just SAM, it fallbacks to DSA-SHA1.
https://github.com/PurpleI2P/i2pd/blob/openssl/libi2pd/Identity.cpp#L613

**Comment by peacekeeperatlas** [comment]
I am so sorry, i find this bug some time ago, and missremember details.

Example request:
"SESSION CREATE STYLE=STREAM ID=test DESTINATION=TRANSIENT SIGNATURE_TYPE=SOME-CHARS"

After this, no response from router.
Log shows "SAM: runtime exception: stoi"

As I understand, it is because it trying to parse SIGNATURE_TYPE as integer.

**Comment by orignal** [comment]
that's a good finding. will be fixed
