### ISSUE TITLE
Post installation setup error ...

### ISSUE THREAD

**Issue by aiamuzz** [PurpleI2P/i2pd#1262]
Hi,

I was trying to install with the command on my debian based linux distro (Deepin OS), i am getting the following error ...

```
Setting up i2p (0.9.34-1) ...
Job for i2p.service failed because the control process exited with error code.
See "systemctl status i2p.service" and "journalctl -xe" for details.
invoke-rc.d: initscript i2p, action "start" failed.
● i2p.service - load-balanced unspoofable packet switching network
   Loaded: loaded (/lib/systemd/system/i2p.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2018-10-30 21:01:52 IST; 8ms ago
  Process: 3633 ExecStopPost=/bin/rm -rf /run/i2p (code=exited, status=0/SUCCESS)
  Process: 3630 ExecStart=/usr/sbin/wrapper $I2P_ARGS (code=exited, status=231/APPARMOR)
  Process: 3629 ExecStartPre=/bin/chmod 750 /var/log/i2p (code=exited, status=0/SUCCESS)
  Process: 3624 ExecStartPre=/bin/chown -R ${I2PUSER}:${I2PUSER} /var/log/i2p /run/i2p /tmp/i2p-daemon (code=exited, status=0/SUCCESS)
  Process: 3620 ExecStartPre=/bin/mkdir -p /tmp/i2p-daemon (code=exited, status=0/SUCCESS)

Oct 30 21:01:52 aAH15 systemd[1]: Starting load-balanced unspoofable packet switching network...
Oct 30 21:01:52 aAH15 systemd[3630]: i2p.service: Failed to prepare AppArmor profile change to system_i2p: No such file or directory
Oct 30 21:01:52 aAH15 systemd[3630]: i2p.service: Failed at step APPARMOR spawning /usr/sbin/wrapper: No such file or directory
Oct 30 21:01:52 aAH15 systemd[1]: i2p.service: Control process exited, code=exited status=231
Oct 30 21:01:52 aAH15 systemd[1]: i2p.service: Failed with result 'exit-code'.
Oct 30 21:01:52 aAH15 systemd[1]: Failed to start load-balanced unspoofable packet switching network.
dpkg: error processing package i2p (--configure):
 installed i2p package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 i2p
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by l-n-s** [comment]
You are installing i2p, but this is **i2pd**

i2p's bugtracker is http://trac.i2p2.de/

**Comment by aiamuzz** [comment]
oops ... sorry ... but i followed the 'download' button from the website ... hmmmm

So should i be installing 'i2pd' ?

I just came across this 'Invisible Internet Protocol' ... sounded interesting ... so i am new to this you see ...

How do i use this 'Invisible Internet Protocol' ?

**Comment by l-n-s** [comment]
yep, you can install i2pd by using [these instructions](https://i2pd.readthedocs.io/en/latest/user-guide/install/#debian)

**Comment by r4sas** [comment]
Deepin OS repository have i2pd 2.18. But current version is 2.21.1 and avaliable at https://repo.i2pd.xyz/

**Comment by aiamuzz** [comment]
@r4sas  ...

thanks i did try installing i2pd ... and it was present in my distribution's repo's ... i installed it ...

Now i need to wrap my head around using it as it should be used ...

1. I am a frequent user of qBittorrent ... i would certainly like to use it anonymously ... but not at the cost of speed of download and availability of peers ... 

2. can i browse all websites through this anonymous system or ... is it limited to only certain websites inside I2P network ?

**a little help in understanding things to get them up and running will not hurt !!!**

:) :) :)

**Comment by aiamuzz** [comment]
**this whole I2P network thing seems like Deja Vu to me ... is it same as what is adapted in the technology-comedy tv series's ... 'Silicon Valley' ... a.k.a ... pied pipers de centralized open network system ???

:) :) :)**

**Comment by majestrate** [comment]
@aiamuzz if you're looking for an i2p bittorrent client try out https://github.com/majestrate/XD

**Comment by aiamuzz** [comment]
@majestrate  ... do you have the link to i2p-messenger for debian system ?

**Comment by majestrate** [comment]
@aiamuzz i do not sorry
