### ISSUE TITLE
i2p reseed servers

### ISSUE THREAD

**Issue by IojkinKot** [PurpleI2P/i2pd#1270]
All i2p reseed servers are dead. Any alternative servers?

**Comment by majestrate** [comment]
you may be able to bootstrap via floodfill node, be careful when picking the floodfill as it can segment you off into a sub partition of the network they control.

**Comment by orignal** [comment]
are they? reseeded successfully right now. Probably something wrong with your network.
As alternative you can reseed from .zip file with netdb in it

**Comment by IojkinKot** [comment]
[errors.txt](https://github.com/PurpleI2P/i2pd/files/2579317/errors.txt)
Connection errors in attached file

**Comment by r4sas** [comment]
Reseeds have protection from downloading with default tools.

**Comment by IojkinKot** [comment]
Thnx. With correct user-agent string all ok.

`wget --no-check-certificate --tries=1 --user-agent=Wget/1.11.4 https://i2p.mooo.com/netDb/i2pseeds.su3`

**Comment by Sfinx** [comment]
Getting "Reseed: failed to reseed from /var/lib/i2pd/i2pseeds.su3" at 2.38.0. is it expected ? The same when downloaded from i2pseed.creativecowpat.net

**Comment by r4sas** [comment]
Are you sure?
https://github.com/PurpleI2P/i2pd/blob/b0874410f1a48a158461c4971a74604b6e7a9542/libi2pd/Reseed.cpp#L259
https://github.com/PurpleI2P/i2pd/blob/b0874410f1a48a158461c4971a74604b6e7a9542/libi2pd/Reseed.cpp#L275
https://github.com/PurpleI2P/i2pd/blob/b0874410f1a48a158461c4971a74604b6e7a9542/libi2pd/Reseed.cpp#L280

Enabling logs can help fixing problems.
