### ISSUE TITLE
Questions about transit tunnels

### ISSUE THREAD

**Issue by Agagamand** [PurpleI2P/i2pd#1271]
Я где-то уже читал как ответственные за i2pd люди писали, что их клиент используют в подавляющем большинстве случаев блокируя транзитные туннели. Однако на самом деле есть и такие пользователи которые хотят помогать сети, хотят принимать транзиты. Почему i2pd неспособен удовлетворить желание этих людей быть полезными?

https://lh3.googleusercontent.com/-DfXVtl0pjgo/W-_uw6EbO7I/AAAAAAAB_zc/200gls2zYMIDnddXlwSx7ZPcsMDxeiv5ACHMYCw/s0/AkelPad_2018-11-17_12-34-46.png
https://lh3.googleusercontent.com/-fx_a6e2FWnA/W-_4O5VvM5I/AAAAAAAB_zo/E8Q8XWl-c4EJkrIlo_6VwifHpQ7W5pndQCHMYCw/s0/2018-11-17_13-15-11.png

**Comment by orignal** [comment]
И в чем вопрос?

**Comment by Agagamand** [comment]
Ага, значит транзитные тоннели всё же поддерживаются. А ускорить их появление можно? Клиент на Джаве пускает через меня транзит довольно быстро, сами видите на скриншотах.

**Comment by Agagamand** [comment]
i2pd у меня вчера работал 14 часов под ряд. Джаву я не запускал уже несколько дней. И тем не менее для Джавы я оказался достаточно интегрированным в сеть чтобы через меня пускать тоннели, а для i2pd всё ещё недостаточно хорош?

Спустя 110 минут работы клиента на Джаве, через меня шло 110 транзитных тоннелей. А i2pd за это же время не пустил ни одного, при этом интеграция в сети дошла до 46% и более не движется.

Я всё же склоняюсь к мнению что тут дело не в "сети и кучи факторов", а в клиентской программе через которую в эту сеть подключаюсь.

Выставил bandwidth = X, но это на транзите вообще никак не сказалось.

Использую Win10 1809

**Comment by Agagamand** [comment]
Изначальный заголовок темы лучше отображает её суть. Транзита нет https://lh3.googleusercontent.com/-k6qbLY8DMXs/W_BLhjPE_YI/AAAAAAAB_z8/CD329Y0odDAYD0ZaPbw5JtRULC6Dpc8AQCHMYCw/s0/i2pd_2018-11-17_19-10-29.png Не вижу более смысла продолжать использовать i2pd.

**Comment by r4sas** [comment]
Лучше бы показали что в вебконсоли на 127.0.0.1:7070 на главной и в Router Commands.
* Статус роутера с вебконсоли
* Действительно ли на странице команд включен прием транзита (должно показывать Decline transit tunnels)

На всякий запустить Run peer test, перепроверить Network status и Router Caps.

Если дейставительно хотите сравнить то, как быстро появятся туннели и транзит, то лучше дропнуть router.keys, router.info и netDb. Иначе это просто голословное сравнение.

**Comment by l-n-s** [comment]
@Agagamand если Status: OK, то транзит должен появиться. Если не появляется, тут надо разбираться. 

Название тикета желательно писать на английском, только поэтому изменил. Переименуй в какое тебе угодно.
