### ISSUE TITLE
i2pd behind NAT

### ISSUE THREAD

**Issue by ReichKV** [PurpleI2P/i2pd#1276]
Hi,

My computer is behind the strict firewall so that even UDP is blocked. I run i2pd and  see in the webconsole that the Network status is Testing for about 2 days. Also i cannot connect to any i2p site.What can be a problem?

**Comment by l-n-s** [comment]
Seems like your only option will be using i2pd with `ntcpproxy` parameter. Or use it with a VPN tunnel.
