### ISSUE TITLE
blob jar file

### ISSUE THREAD

**Issue by yangfl** [PurpleI2P/i2pd#1279]
Hi,

I see there's a blob jar file in qt/i2pd_qt/android/libs/android-support-v4.jar
Prebuilt binary is not welcomed in Debian and has to be removed from source tarball. While I can do this downstream, it's always better to not include them from the upstream. If such file is needed by other parts, I'd recommend downloading it during compiling.
Please consider removing it from repo (or source tarball).

**Comment by orignal** [comment]
It can be removed completly, android-qt is not used anymore

**Comment by hypnosis-i2p** [comment]
rm -rm qt/i2pd_qt/android/ ; check that desktop i2pd_qt builds ok ; then commit+push
