### ISSUE TITLE
Low transit traffic

### ISSUE THREAD

**Issue by bol-van** [PurpleI2P/i2pd#1287]
I have years of experience using i2pd and java i2p router.
What is always stable : java router always attracts ~200 kbytes/sec traffic, i2pd only 0.5-1 kbyte/sec
I tried every possible option but I cant change this.

Why ? What is the difference between java and i2pd ?

**Comment by LLE8** [comment]
My best result with i2pd was 20 Mbit/s up + 20 Mbit/s down
Now i2pd 2.22, Debian Stretch 64bit 
12 Mbit/s up + 12 Mbit/s down, uptime 69 days

**Comment by r4sas** [comment]
@bol-van а у тебя всё нормально в плане проброса портов?
Какой статус пишет на главной? Какие флаги у роутера (в спойлере на 7070)?

**Comment by LLE8** [comment]
еще от хостера может зависеть

**Comment by bol-van** [comment]
i2pd работает на linux на внешнем ip без проброса портов. порты открыты, входящие есть. флудфил включен. что еще нужно ?
Router Caps: XfR

**Comment by bol-van** [comment]
Нет никакого хостера. Домашний инет 100 мбит

**Comment by bol-van** [comment]
Routers: 259 Floodfills: 191 LeaseSets: 0
Всего 259 роутеров

У меня есть еще экземпляр на vps с hidden service. Туда регулярно заходят и тем самым поднимают количество роутеров.
Routers: 2551 Floodfills: 1384 LeaseSets: 0
Transit: 16.00 GiB (1.45 KiB/s)

**Comment by LLE8** [comment]
Кусок из моего конфига
```
ifname = ens3
nat = false
bandwidth = X
notransit = false
floodfill = false
transittunnels = 5000
ipv4 = true
ipv6 = false
```
Где-то здесь видел замечание, что с floodfill = true хуже.
У вас интерфейс наверняка по-другому называется, этот ifname у меня в Debian Stretch в виртуалке

В /etc/default/i2pd      ulimit -n 8192
или в /lib/systemd/system/i2pd.service      LimitNOFILE=8192

И в /etc/sysctl.conf
net.core.somaxconn = 8192
net.ipv4.tcp_max_orphans = 128

**Comment by LLE8** [comment]
> Нет никакого хостера.

Зато есть провайдер

**Comment by LLE8** [comment]
> Нет никакого хостера

Зато есть провайдер

**Comment by bol-van** [comment]
ifname  - not set
nat = false
bandwidth = X
notransit = false
floodfill - not set (default false)
transittunnels = 2500
ipv4 = true
ipv6 = true  (ipv6 есть)

на впс работало без флудфила с тем же результатом
улимит поднял, но к моему случаю это наверняка не имеет отношения. слишком мало всего, чтобы упереться в 4096

net.core.somaxconn  - плох i2pd, если он так редко выполняет accept , что ему необходима такая очередь.  но пока временно поставил 1024, уверен ни на что не повлияет

**Comment by bol-van** [comment]
> > Нет никакого хостера
> 
> Зато есть провайдер

Провайдер в порядке. К тому же эффект идентичен на vps и дома

**Comment by bol-van** [comment]
На 2 инстансах сейчас :

home:
netstat -tnp | grep i2pd | wc -l
24

vps:
netstat -tnp | grep i2pd | wc -l
680

**Comment by LLE8** [comment]
netstat -tnp | grep i2pd | wc -l
4029
на это за 70 суток

Оно не очень быстро разгоняется, если с пустого места, то хотя бы дней 10-20 на vds должно поработать, тогда что-то будет понятно.

**Comment by bol-van** [comment]
Оно месяцами работало, привлекая 1-2 кб в сек

**Comment by bol-van** [comment]
Флудфид и включал и выключал без особой разницы

**Comment by LLE8** [comment]
все-таки попробуйте на другом хостере, я сейчас экспериментирую на vscale.io на самом дешёвом 512 МБ

Получается, что с net.core.somaxconn я погорячился, подсмотрев здесь даже 32768 у кого-то?

**Comment by LLE8** [comment]
https://github.com/PurpleI2P/i2pd/issues/1254
в конце темы скриншоты

**Comment by bol-van** [comment]
Действительно стоило отключить ipv6, и о чудо
3.49 MiB (23.87 KiB/s)

**Comment by LLE8** [comment]
Посмотрите у себя в i2pd.log через некоторое время
https://github.com/PurpleI2P/i2pd/issues/977
```
[08/Jan/2019:13:45:49 +0300]@648/warn - NTCP2: outgoing messages queue size exceeds 500
[08/Jan/2019:13:46:17 +0300]@231/warn - Transports: delayed messages queue size exceeds 50
[08/Jan/2019:14:04:22 +0300]@478/warn - NTCP: outgoing messages queue size exceeds 200
```
и еще плавающий какой-то https://github.com/PurpleI2P/i2pd/issues/825
в /var/log/messages `TCP: too many orphaned sockets`

**Comment by r4sas** [comment]
@bol-van а у вас ipv6 нативный или через туннельного брокера?
На всякий предупреждаю что туннельный брокер (he.net) как-то лимитирует подключения извне. Но почему отключение у вас повлияло так сильно - мне неизвестно.

**Comment by bol-van** [comment]
На vps нативный, дома he.net
лимитирует он только некоторые порты. 25 точно закрыт. irc закрывали, с возможностью открыть

**Comment by bol-van** [comment]
Transit: 113.77 MiB (67.24 KiB/s)

Time to rename topic : low transit traffic when ipv6 enabled

**Comment by orignal** [comment]
Tunnel creation success rate: 50%
   Received: 72.83 GiB (43.67 KiB/s)
   Sent: 71.08 GiB (38.27 KiB/s)
   Transit: 66.55 GiB (32.02 KiB/s)

Router Caps: OR

Это на впс с ipv6.

**Comment by LLE8** [comment]
Tunnel creation success rate: 37%
Received: 9202.44 GiB (1553.41 KiB/s)
Sent: 9622.07 GiB (1658.10 KiB/s)
Transit: 9482.04 GiB (1606.27 KiB/s)
Router Caps: XR

Это на впс без ipv6

Как сделать неправильный ipv6 адрес? Как проверить правильность?

**Comment by orignal** [comment]
Он не то что неравильный, он скорее эфемерный. Дело в том что я сейчас публикую свой локальный адрес, а не внешний.

**Comment by orignal** [comment]
Насколько я понимаю джавовские узлы видя в списке адресов v6 пытаются стучаться на него, если не получается видимо бросают эту затея и отмечают недоступность у себя в профилировщике

**Comment by LLE8** [comment]
Весело. 
А если у джавовского i2p получается соединиться по ipv6, то какие будут его действия по ipv4?
Кстати во всех двух известных мне ОС ipv6 по умолчанию приоритетнее ipv4.
А нет ли случайно чего-нибудь, чем можно почитать эти бинарные файлы профилировщика?
Локальный ipv6 - это который fe80: ?

**Comment by r4sas** [comment]
Нет, имеется в виду это: #1251.

**Comment by bol-van** [comment]
У меня на линухах нигде нет эфемерного адреса. Отключено. И все равно такое

**Comment by bol-van** [comment]
Скорость вновь упала

vps, с hidden service :
Routers: 3455 Floodfills: 1368 LeaseSets: 78
Client Tunnels: 34 Transit Tunnels: 99
Transit: 141.82 MiB (9.07 KiB/s)

home, без hidden service
Routers: 474 Floodfills: 283 LeaseSets: 1
Client Tunnels: 20 Transit Tunnels: 2
Transit: 5.10 MiB (0.06 KiB/s)

**Comment by LLE8** [comment]
У меня тоже все цифры всегда плавают, но сравнить с вашими не могу
А где VPS хостится, если не гос тайна?

**Comment by LLE8** [comment]
Вопрос не про страну, а про конкретного хостера.

**Comment by LLE8** [comment]
Совсем недавно где-то видел рекламу vds, с которым дают сеть /64, сейчас не найду.

А можно в порядке эксперимента попробовать публиковать реальный единственный ipv6 адрес?

**Comment by orignal** [comment]
Так я счас так и делаю: когда соединяюсь с кем нибудь в ipv6 то беру локальный с сокета и публикую.

**Comment by LLE8** [comment]
Локальный с сокета - это не внешний, который дал хостер?

**Comment by orignal** [comment]
В ipv6 NAT как правило не используется. И в целом это работает потому что я вижу много входящих по ipv6

**Comment by orignal** [comment]
Значит придется это сделать как положено

**Comment by bol-van** [comment]
Зачем задавать вопросы "вокруг да около" ? Типа какой хостинг там и тд
Спрашивайте прямо технические вопросы,
На хостинге /64, дома he,net /64.
Публикуется доступный ipv6, не temporary, temporary отключены. Входящие проходят. Реально висит несколько подключений от других узлов по ipv6.  И при этом всем low traffic.
А если выключаешь ipv6, то сначала всплеск, потом опять low.

**Comment by LLE8** [comment]
Не ищите скрытый смысл. Я хотел сам посмотреть на описанное вами поведение, если это будет стоить не дороже пары долларов. Может быть так, что этот хостер не может или не хочет несколько тысяч соединений с одного vds? Они на вид все нормальные, а что там внутри, кто его знает.

**Comment by bol-van** [comment]
Ограничение на количество tcp может существовать разве что если имеется какая-то система анализа трафика, ddos защиты и тому подобное. В остальных случаях лишь оконечная точка знает про подключения к ней, для остальных узлов это прозрачно на уровне ip.
Да, у хостера есть некоторые дурные фильтр правила, но вроде они для меня отключили ddos защиту. А на домашнем провайдере ничего такого нет.
Впрочем, речь идет о максимум 100 подключениях. Обычно висит около 20

**Comment by LLE8** [comment]
@bol-van Процессор на вашем vds какой? Насколько занят? Какой поток самый тяжелый? Например этот https://www.cishost.ru/Virtualnie-serveri/tarifs-vds.html 400 МГц в Болгарии не внушают.

**Comment by orignal** [comment]
@bol-van  это надо разбираться с работой джавовского профилировщика. Може @l-n-s  подскажет

**Comment by LLE8** [comment]
@bol-van 
А что у вас на vps с hidden service в i2pd.conf в этом месте? 100% по умолчанию или что-то другое? У меня однажды было какое-то подозрение, но без достаточных оснований. 
```
## Max % of bandwidth limit for transit. 0-100. 100 by default
# share = 100
```

**Comment by bol-van** [comment]
на одном 50, на другом 80

**Comment by LLE8** [comment]
Uptime 2 суток и 3 часа, i2pd trunk от 2 февраля
Другой хостер, новый vds, Debian Stretch 64-bit
![image](https://user-images.githubusercontent.com/25343511/52305874-52fb7800-29a7-11e9-873f-1e42d0e10c6d.png)

**Comment by LLE8** [comment]
Это за неделю
![default](https://user-images.githubusercontent.com/25343511/52538022-86ab1900-2d7e-11e9-8569-63e5753c253b.png)
График в КБайтах/с

**Comment by LLE8** [comment]
Приблизительно сутки назад: graceful shutdown, установил floodfill в значение false (было true) и запустил снова.
![floodfill_false](https://user-images.githubusercontent.com/25343511/52592023-6a7aab00-2e56-11e9-81fb-d9552b361ad0.png)
IPv6 по-прежнему выключен, share по умочанию

**Comment by LLE8** [comment]
@bol-van Удалось что-нибудь понять? 
У меня ваш баг не воспроизводится, с ipv6=false, floodfill=false, nat=false, bandwidth=X в течение недели или меньше разгоняется до 10 Мбит/с приблизительно. 
Параметр share похоже не виноват, при share=90 все примерно также, как и без его явного указания.

**Comment by bol-van** [comment]
У меня изменение настроек не меняет картину, Все то же самое, близко к 0

**Comment by LLE8** [comment]
Хостера другого попробуйте однозначно. Только не OpenVZ/Virtuozzo, а KVM/Vmware/Xen/HyperV
Попадаются с почасовой или посуточной оплатой, для таких экпериментов удобно.
.

**Comment by bol-van** [comment]
Что вы твердите одно и то же на протяжении множества постов.
Что это за программа, если она работает "только на некоторых хостерах".
Дело в том, что она не работает на обычных типичных, ничем не ограниченных соединений с достаточной пропускной способностью
У меня другой вопрос. Неужели нет никого, у кого то же самое, что и у меня ?

**Comment by orignal** [comment]
У всех с транзитом нормально. 
Раз не идет транзит значит профилировшики других узлов сети считают его плохим.
Вот почему это другой вопрос.

**Comment by LLE8** [comment]
>  она работает "только на некоторых хостерах"

может быть наоборот,  она НЕ работает "только на некоторых хостерах"

**Comment by bol-van** [comment]
Все выяснилось.
Удалил ключи роутера, чтобы они пересоздались заново, и оно заработало
Тк инсталяция у меня давно, генерились они какой-то старой версией, и видимо там чего-то не было

**Comment by LLE8** [comment]
Я иногда при очередном релизе i2pd удаляю её полностью apt-get purge i2pd и устанавливаю заново, иногда беру конфиг от старой версии. За 2-3 суток разбегается.
Через 2-3 суток что у вас будет?

**Comment by bol-van** [comment]
Пока за 1.5 суток   60-100 кб/с  c ipv6 и флудфил
где hidden service там не могу удалить роутер кей, иначе потеряю hidden

**Comment by LLE8** [comment]
60-100 кб/с - это Кбит/с или Кбайт/с?
Мне кажется, ipv6 здесь вообще лишний пока https://github.com/PurpleI2P/i2pd/issues/851#issuecomment-463958349 , думаю, что лучше его отключить.
И через некоторое время посмотрите, как повлияет floodfill=false, у меня это выглядело так https://github.com/PurpleI2P/i2pd/issues/1287#issuecomment-462486187

**Comment by LLE8** [comment]
До какой скорости разогналось? С каким конфигом?

**Comment by LLE8** [comment]
@bol-van   ?

**Comment by LLE8** [comment]
приблизительно 4000 транзитных туннелей, 26-27  МБит/с

**Comment by LLE8** [comment]
Как увеличить limits.transittunnels без перезапуска демона? В отдельные моменты количество транзитных туннелей превышает 4900, а предел в конфиге 5000.

Показания iftop и веб-интерфейса i2pd заметно различаются, например (27 и 32) или (25 и 30) или (31 и 38), т.е. веб-интерфейс показывает приблизительно на 5-7 Мбит/с больше, чем iftop. Чем еще можно измерить реальную загрузку сети?

**Comment by orignal** [comment]
никак. счас этого не сделано

**Comment by r4sas** [comment]
А в iftop случаем не MiB/s?

**Comment by LLE8** [comment]
Возможно, но на 5 Мбит/с не тянет. Возможно, это не самый важный вопрос, пока к 100 Мбит/с не приблизится.

**Comment by LLE8** [comment]
Показания мониторинга хостера и показания iftop близки, показания веб-интерфейса i2pd приблизительно на 20% выше (20 и 24)

**Comment by LLE8** [comment]
5100-5200 туннелей и 31-36 Мбит/с по iftop

**Comment by LLE8** [comment]
В отдельные моменты транзитный трафик приближался к 40 Мбит/с, пока не начались проблемы с SSU и все испортилось. Возможно, больше 40 Мбит/с не давал хостер. Веб-интерфейс i2pd, как мне кажется, несколько завышает показания по трафику.
@bol-van , можно закрывать тему?

**Comment by r4sas** [comment]
Прошел почти год, так что думаю можно точно закрыть.
