### ISSUE TITLE
How can I export the reseed zip file from I2PD?

### ISSUE THREAD

**Issue by tsr7r3tss5ulwod8** [PurpleI2P/i2pd#1291]
How can I export the reseed zip file from I2PD?

**Comment by r4sas** [comment]
Use external tool, like this: https://github.com/PurpleI2P/pyseeder
Other way - read about reseed on geti2p.net and find software provided by Java I2P.

**Comment by l-n-s** [comment]
There's no need for anything special if you just want a ZIP file. 

Go to i2pd's data directory (`/var/lib/i2pd` in Linux) and compress the `netDb` subdirectory. The resulting ZIP file will work just fine.

**Comment by r4sas** [comment]
That will be very big file for simple reseed ;)

**Comment by LLE8** [comment]
Is netDb fully portable between different hosts running i2pd?  Is it useful for fast increasing transit traffic without slow acceleration after start on new host?

**Comment by l-n-s** [comment]
Sure, it is!

Since there is no reply, I guess the question is answered.

**Comment by tsr7r3tss5ulwod8** [comment]
> That will be very big file for simple reseed ;)

I will like combine l-n-s' way and java I2P to export small reseed zip file
