### ISSUE TITLE
i2pd does not connect at all on Fedora (flatpak installation)

### ISSUE THREAD

**Issue by Nokia808** [PurpleI2P/i2pd#1296]
Hi. I'm new user for i2pd & started to use it few days ago when I started to use flatpak.

I installed it on my Fedora 28 X64 Cinnamon edition as flatpak. It was installed correctly by GNOME software center without any error messages.

I can launch it okay, but application try to connect but failed all the time inspite that Internet speed very fast & no signal power issue !

It always show: 
"Network status: error
Clock Skew"

Please your kind help.

**Comment by l-n-s** [comment]
Check if your time is synchronized with the Internet 

    timedatectl set-ntp true

**Comment by Nokia808** [comment]
@l-n-s  
Many thanks ! Yes, you was correct. Just when I enabled Internet time, it worked.

I think I should read the documentation of this application.

Please is there specific forum for discussion, or can I use this site for asking further questions not answered by documentations, like how to run VPN over i2p & how to run application at every boot automatically in regard to flatpak mode of installation .......
