### ISSUE TITLE
Need a build for arm5

### ISSUE THREAD

**Issue by xaozai** [PurpleI2P/i2pd#1298]
Could you please make a release for arm5 88f6281?

**Comment by r4sas** [comment]
arm5 for what? Which type of device/system?

**Comment by xaozai** [comment]
Synology NAS
Marvell Kirkwood 88F6282
Linux 2.6.32.12

**Comment by xaozai** [comment]
There is a toolchain here: https://sourceforge.net/projects/dsgpl/files/DSM%206.2%20Tool%20Chains/Marvell%2088F628x%20Linux%202.6.32/

**Comment by r4sas** [comment]
Try build yourself if it contain toolchain. You also need boost, openssl, zlib, miniupnpc (optional),

**Comment by LLE8** [comment]
This program is portable, it compiled without problems and tested in  OpenWrt non-x86

**Comment by majestrate** [comment]
did a new staric arm build of 2.23.0 
contains `openssl 1.1.1a` and `boost 1.60.0` linked in.
compiled using `-oS` to reduce size.
build has been stripped of debug symbols for size.

uploaded to https://i2p.rocks/files/i2pd-rpi/2.23.0/
verify signatures please

```
$ file i2pd && gpg --verify i2pd.sig
i2pd: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.3, for GNU/Linux 3.1.9, stripped
gpg: assuming signed data in 'i2pd'
gpg: Signature made Sat 23 Feb 2019 08:18:38 AM EST
gpg:                using EDDSA key 67EF6BA68E7B0B0D6EB4F7D4F357B3B42F6F9B05
gpg: Good signature from "Jeff Becker (probably not evil) <jeff@i2p.rocks>" [ultimate]

$ b2sum i2pd
e4cf21c06ae441030253dcb636eb05f0b5dc6405879b86b3b8f734a3195856ab20163c780c1c144e47f50dd9f8dc748bd243739262e2bd98fe05dac473c5c4b8  i2pd
```

**Comment by r4sas** [comment]
@majestrate that's for which ABI? Standart linux?

**Comment by majestrate** [comment]
@r4sas should be standard linux

**Comment by r4sas** [comment]
It would not work in @xaozai case.

**Comment by xaozai** [comment]
[majestrate](/majestrate), Unfortunately, it doesn't work.
```
$ ./i2pd --conf=/opt/etc/i2pd_not_daemon.conf --tunconf=/opt/etc/i2pd_tunnels.conf
Illegal instruction
$
```
I think it is necessary to compile it with arm-marvell-linux-gnueabi.
