### ISSUE TITLE
i2pd ignore the Addresshelper link?

### ISSUE THREAD

**Issue by movisozoxi** [PurpleI2P/i2pd#1299]
[blue.proxynet.i2p(ignored Addresshelper, i2pd just try to directly access this domain name)](http://blue.proxynet.i2p/?i2paddresshelper=Qgr~nlaA1RMkDe5Ys0f1ZM7y8s~6O6f3b9pS7sBEye51oFRGgGRWqY4IxeDuQt49VohqkVATtMwpGC0mSxzlJZ0fFMs-dyyXs8OFae0gOxh8Lb6NEFNvKE3yl4kI8Dju-B90njDEDiFl~em8dV8yRwSpCjyBZ5i2Tq58GSqIGLkUYghUuSiWunLZZHfel9WOfiiy303pQ0Hft9GLv36cbNhwfI4z62V-xNt~KRHcXNsnzEI~JhqOwYX92RuAVWkYI63nMiQOvAducsUiVKti-7VhZiH7VDbObVlrW0eNQFb54TCKEwr0jo~YOhc6hue5OHKpRX2Uvm4E4hNYN62J9QzGFmb0Dfcilgh3ccqD9-6zzuPSiBTQ6-L1U4F-TnMXnztoWsY9gN7cv8UO6uVa~oCBp0ap8h7nJKdrRPjE8OMtMxpV7KjMgNcDd~zJIAzVFzXtL~TcV7~tvkCIcwb88pRw~Nch48EfPVbY1gNHCKQAv~0j3inXOkDaIOWLjc30BQAEAAcAAA==)
[brown.proxynet.i2p(Normal Addresshelper,prompt me to update my record)](http://brown.proxynet.i2p/?i2paddresshelper=C0zBhK0aUOED-HnGns1v5bIfsEHDP4uRg0boqHirnDNGjrnWMQN04VPf5nEy3iLEM4Fl921CILlC2ET5GBXuPTb6HMUUBizcLXpR9Z0qkdnds6z~S1H9oicR40lDYamtrp3P6nNqYdfvF5MRj6PNTl5I22m-rS9Jcu2b70eb0ypq7qo~~hSA3hiBnrol6PjQNjsTMalGUJpABCJc8DUg3soMdmSt3arA5tNY1WTo-0NrKs8SLbcRGIB9sKiloZAkn1p1WCaiY4vnsZgjPjbeOAS-edTPNOTAkMrwBPZ6-TaOp3wIRdFLXF6wu8cHWab-E59QXDby7ttSH2D08WELUG28NOJWhcVTK76eviaYWTjPWukSNTbJe3JvlnbErZ83W7ijbr3iTuN4Eiau2lo6kdEvfkIY~Z3emR-CvGTM48gsXYAC~JDIiHFAJ-aIDxwwjuh-WuAsi9qVb-79VCnomCMI9oKyb6M-VZMFixMSeZ5IcMDC4hAexePX5AghG4kMBQAEAAcAAA==)

I'm not sure what is happened, but now everything normal.
But I will keep this issue opening let some peoples report same problem to more find out this problem.

**Comment by movisozoxi** [comment]
I'm not sure, maybe one Firefox cache issue but I at that time reload page with "ctrl+shift+R", the Addresshelper still been ignored.

**Comment by r4sas** [comment]
Haven't that problem. Using FF and Chromium.

**Comment by r4sas** [comment]
t/o
