### ISSUE TITLE
Is i2pd recommended run as root?

### ISSUE THREAD

**Issue by movisozoxi** [PurpleI2P/i2pd#1300]
https://github.com/PurpleI2P/i2pd/releases/download/2.23.0/i2pd_2.23.0-1buster1_i386.deb
The debian buster deb package put i2pd in `/usr/sbin/i2pd` only, normal user can't run it with the default `PATH` environment variable.
```
root@debian:/# type i2pd
i2pd is /usr/sbin/i2pd
root@debian:/# sudo -i -u test
test@debian:~$ type i2pd
-bash: type: i2pd: not found
test@debian:~$ 
```

**Comment by LLE8** [comment]
It's a daemon.

**Comment by orignal** [comment]
You don't need root to run i2pd

**Comment by l-n-s** [comment]
It runs as a daemon with UID of a system user "i2pd", not as root.
