### ISSUE TITLE
[Question] is there a way to make flatpak i2pd autostart at each boot?

### ISSUE THREAD

**Issue by Nokia808** [PurpleI2P/i2pd#1303]
Hi. I'm using i2pd as flatpak package from Flathub because it is not available from Fedora official repositories & I dislike to use COPR 

Is there a way to make my i2pd automatically started at each boot in my case or not ?

**Comment by l-n-s** [comment]
@Nokia808 I'm not sure if it can be started as a system daemon, probably not.

Flatpak package is a desktop application, so it can be configured to autostart when your desktop environment is started. E.g. when you are logged in to GNOME/KDE/whatever you use. 

https://developer.gnome.org/autostart-spec/

https://docs.kde.org/trunk5/en/kde-workspace/kcontrol/autostart/index.html

**Comment by Nokia808** [comment]
@l-n-s 
Dear I'm on Cinnamon DE. Do you have a link about this in regard to Cinnamon ?

**Comment by l-n-s** [comment]
it's basically gnome
