### ISSUE TITLE
Can't build from source

### ISSUE THREAD

**Issue by createS0ftware** [PurpleI2P/i2pd#1305]
I am trying to build an Android apk, using the ndk-build command but i get this error 
** No rule to make target `/Users/xxx/Workspace//i2pd/android/jni/../daemon/Daemon.cpp', needed by `../i2pd/android/obj/local/arm64-v8a/objs/i2pd//Users/xxx/Workspace/i2pd/android/jni/__/daemon/Daemon.o'.

How can i fix this ? 

Thanks

**Comment by orignal** [comment]
you shoulnd't use ndk-build but gradle and change the path first.
https://i2pd.readthedocs.io/en/latest/devs/building/android/#building-the-app-without-qt

**Comment by createS0ftware** [comment]
Thanks i got it.
