### ISSUE TITLE
iOS - CMakeLists.txt Missing

### ISSUE THREAD

**Issue by donaldking** [PurpleI2P/i2pd#1306]
Hi,  I'm building for iOS following your guide <https://i2pd.readthedocs.io/en/latest/devs/building/ios/> However, I'm getting an error:
```
{foo}/i2pd/build" does not appear to contain CMakeLists.txt"
```

Can you please advice on how to resolve this for iOS Build. Thanks

**Comment by r4sas** [comment]
I think easier way to use homebrew for building binary.
https://i2pd.readthedocs.io/en/latest/devs/building/unix/#mac-os-x

**Comment by r4sas** [comment]
Can you check `build` folder? Is it contain that file?

**Comment by donaldking** [comment]
Hi, I've checked the folder. It does have a CMakeList.txt file, but using that to build for iOS throws a TargetArchitecture Error. I've attached the CMakeList File. And the error I'm getting.
[CMakeLists.txt](https://github.com/PurpleI2P/i2pd/files/2961862/CMakeLists.txt)
<img width="519" alt="Screen Shot 2019-03-13 at 14 22 18" src="https://user-images.githubusercontent.com/4445659/54286340-91361980-459b-11e9-8ba9-487156b53b39.png">

**Comment by orignal** [comment]
We don't build for iOS. If you know how to fix it please do it

**Comment by orignal** [comment]
@mikalv maybe you can help?

**Comment by r4sas** [comment]
t/o. Feel free reopen issue if someone want fix that problem.
