### ISSUE TITLE
How to make a http request programatically from a client using this library as a module in Android

### ISSUE THREAD

**Issue by createS0ftware** [PurpleI2P/i2pd#1308]
Hi 

I can't find a hook in point for a direct http request in this code. I looked at the java implementation and there you have the EEPGet class that you can use. 

I can't find the equivalent. Once the node is running, outbound tunnels become available but i don't know how to use them with this library.

Can you give me some pointers or an example ?

Thanks

**Comment by majestrate** [comment]
On Fri, Mar 15, 2019 at 04:02:10AM -0700, Hanson Aboagye wrote:
> Hi 
> 
> I can't find a hook in point for a direct http request in this code. I looked at the java implementation and there you have the EEPGet class that you can use. 
> 
> I can't find the equivalent. Once the node is running, outbound tunnels become available but i don't know how to use them with this library.
> 
> Can you give me some pointers or an example ?

You could use the SAM api to open an ephemeral tunnel and send it via that but that'd take a bit to work and that api needs a good rewrite.

**Comment by createS0ftware** [comment]
Thanks @majestrate I'll check it out but i was hoping to implement a similar flow to the java  library

Any other suggestions are appreciated

**Comment by orignal** [comment]
@majestrate I assume he wants to do it from his own app.
@createS0ftware  No, we don't provide such support. If you wish read the code and write your own manual.

**Comment by l-n-s** [comment]
Yep, we don't have android libraries. 

The best option is to use SAM (version 3) library from Java I2P, it should work the same.

**Comment by orignal** [comment]
actually we do. but this is separate topic

**Comment by l-n-s** [comment]
Do you mean libi2pd?

**Comment by orignal** [comment]
libi2pd and libi2pd_client could be built separately using ndk-build and link to an app

**Comment by createS0ftware** [comment]
There is code in the Java version that shows one way of building such an interface. But i guess i will have to write my own
