### ISSUE TITLE
After I set ntcp=false and restart i2pd, it is still present in the router.info

### ISSUE THREAD

**Issue by l-n-s** [PurpleI2P/i2pd#1311]

**Comment by createS0ftware** [comment]
How are you able to read router.info ? Whilst debugging in code ? I can't get plain text out of it

**Comment by orignal** [comment]
routerinfo from i2pd-tool

**Comment by createS0ftware** [comment]
Thanks @orignal

**Comment by r4sas** [comment]
NTCP was dropped, some changes in current code must fix issue. Open new issue if problem still exists.
