### ISSUE TITLE
arm64 binary build for Android

### ISSUE THREAD

**Issue by admzzz** [PurpleI2P/i2pd#1314]
publish android arm64 binary, pls

**Comment by r4sas** [comment]
Чисто бинарник, или APK?

**Comment by admzzz** [comment]
бинарник, иф ю плиз ;-)

**Comment by l-n-s** [comment]
Гайз, камон

**Comment by admzzz** [comment]
а можно пропросить ещё и добавить необходимое для arm64 в Application.mk ?

**Comment by r4sas** [comment]
Так там не надо ничего добавлять, просто указать ABI
`APP_ABI += arm64-v8a`

**Comment by admzzz** [comment]
спасибо.
а "Гайз, камон" означает, что бинарник собран и выложен? ...в релизах не вижу...

**Comment by r4sas** [comment]
Нет, он просто написал ибо в ответ на твой "иф ю плиз" :rofl:

**Comment by admzzz** [comment]
ещё раз большое спасибо. 
нужно было для https://4pda.ru/forum/index.php?showtopic=940927 (если интересно, в последних постах наши с разработчиком непонятки с двухархитектурностью i2pd и тора)...

...м.б. стоило б выкладывать регулярно 64битную апкашку вместе с прочими релизами, как это делается для dnscrypt-proxy...

**Comment by r4sas** [comment]
Весьма интересное направление.
А вообще, зачем вам для приложения бинарник если можно (все таки) изучить нативное использование библиотек и собирать именно либу?

> Да что они завелись обновлять! Только 23 версию в InviZible 0.1.17 засунул.

Мы делаем релизы параллельно с основным (Java) клиентом.

> Так i2pd я сам и собираю. Они не дают бинарник на андроид вообще. Вот в этой папочке android binary only есть файлик Application.mk, где и можно выбрать платформу. И arm64 там нет. 

На это я ответил [выше](https://github.com/PurpleI2P/i2pd/issues/1314#issuecomment-475696767).

> но аналога линуксового i2pd не вижу... он джавой реализован у них, что ли?

Не понял вопроса.

Видал что еще используется у вас x86_64, так что можно и его собрать как бинарник.

**Comment by Gedsh** [comment]
Я разработчик InviZible. Это мой первый проект, так что многого не знаю. Например нативное использование библиотек. В будущем вполне возможно изучу. Дело времени.
Но использование бинарника, в данном случае, позволяет его запустить с рут правами. Что обладает определенными преимуществами.

> Мы делаем релизы параллельно с основным (Java) клиентом.

Да я только за! Что мне стоит скомпилить. Кстати совет по arm64 помог. Все собралось. Спасибо! Думал там что-то еще править надо.

**Comment by r4sas** [comment]
> Но использование бинарника, в данном случае, позволяет его запустить с рут правами, и без.

В этом случае в чем проблема разграничить функционал на "с root" и "без root"?
Сейчас у вас все очень захардкожено на наличие рут прав (проверил на телефоне с 8м ведром без рут прав).

**Comment by Gedsh** [comment]
> Сейчас у вас все очень захардкожено на наличие рут прав

Все верно. Без рут ничего не работает. Но так как все основано на использовании iptables, то рут все ровно необходим. Вот и использую его на полную катушку. Может и напрасно.

> Например i2pd не нужны root права вообще, как и tor

Верно, вот только тогда нужен локальный VPN, что пока для меня сложно. Или использовать проксификацию. А ее поддерживают мало приложений. A c invizible есть доступ в сети tor и i2p с любого приложения. И без головной боли.

> В этом случае в чем проблема разграничить функционал на "с root" и "без root"?

Без рута iptables нельзя использовать. Теряется вся задумка.

**Comment by admzzz** [comment]
r4sas,
а можно попросить ткнуть мордой в:
1) душеспасительное чтиво о преимуществах использования либ по сравнению с бинарниками;
2) пример(ы) изменения кода при переходе с бинарников на либы?

...просто Gedsh играет в ленивого фому-неверующего, а моих знаний не хватает, чтоб убедить его, что это и не больно, и не слишком долго... ;-)

**Comment by r4sas** [comment]
>душеспасительное чтиво о преимуществах использования либ по сравнению с бинарниками
>пример(ы) изменения кода при переходе с бинарников на либы?

Вообще ничего не могу скзать по обоим пунктам, ибо не занимаюсь ведром, все на уровне "потыкать палкой".

@Gedsh а у вас есть трекер вне 4pda?

**Comment by Gedsh** [comment]
**r4sas**
Пока нету. Но планируется сайт, там будет. А чуток позже думаю выложить исходники. Скорее всего здесь, на github.

**Comment by r4sas** [comment]
@Gedsh а не могли бы вы создать у себя пустой репо хотя бы, чтобы можно было репортить напрямую, мимо 4pda?

**Comment by Gedsh** [comment]
Да, создам. Уже заканчиваю возиться с своим сайтом. Буду здесь разбираться, как правильно это сделать.

**Comment by Gedsh** [comment]
Выложил здесь исходники [InviZible](https://github.com/Gedsh/InviZible) . Постараюсь потихоньку доводить до ума.
