### ISSUE TITLE
Sample floodfill file 

### ISSUE THREAD

**Issue by createS0ftware** [PurpleI2P/i2pd#1316]
Hi 
I would like to learn more about initialising a node from no connection to many connections. I'd like to create a router.info file but i can't seem to find one that i can read. 

I have been trying to create one by inferring the structure from the code (model class) but i have some questions
1) what is the Key and how can i generate/obtain it for each node ?
2) Is there a sample router.info file i could look at ?

Thanks

**Comment by createS0ftware** [comment]
Also , is there a sample .SU3 file ?

Thanks

**Comment by l-n-s** [comment]
Read the [docs for the NetDb](https://geti2p.net/en/docs/how/network-database). 

This is an i2pd issue tracker. You may want to join the official [I2P development forum](https://i2pforum.net/) and internal zzz.i2p forum.

**Comment by createS0ftware** [comment]
Thanks but after 3 days of trying, i have not been able to register on that forum. I am not sure if it's still working or accepting registrations

**Comment by r4sas** [comment]
Please ask about that on #i2p in Irc2P IRC network inside I2P.
