### ISSUE TITLE
[Question] How to use i2p plug-ins on i2pd ?

### ISSUE THREAD

**Issue by Nokia808** [PurpleI2P/i2pd#1317]
Hi. Currently I'm using i2pd for browsing i2p sites by IceCat. 

However, i2p has other possibilities apart from browsing i2p sites. Most important are:

1) Susi mail 
2) ability to build i2p sites

These need plug-ins.

But can these plug-ins used with i2pd ? & how to set them ?

To me, I feel that it will be better for i2pd project to include, at least, the above 2 functions instead to be merely an i2p diamond .......

**Comment by majestrate** [comment]
you can use a pop3 tool like getmail in place of susimail

**Comment by orignal** [comment]
Plugins can't be used with i2pd

**Comment by Nokia808** [comment]
@orignal 

Is there possibility to convert these plugins to ++C language then add them by default to i2pd project ?

**Comment by orignal** [comment]
If you wish to do it, try to implement it

**Comment by Nokia808** [comment]
@orignal 

Unfortunately, I'm not programmer.

**Comment by Nokia808** [comment]
Okay, does it is possible to use thandebird to send/receive emails by Gmail, Yahoo, ...... using i2p or not ? 

It is clear to me that using i2p for browsing is primarily to brows i2p sites (& only via outproxy used for clear net which currently not available on i2pd). But email is unclear. I read that Susi mail able to send email to out side i2p network so that user can use it to send email to Gmail or Yahoo mail address .....

**Comment by r4sas** [comment]
*Susimail* is only router-based web interface that used postman's mail service.
About service itself please read at http://hq.postman.i2p/

So, you can send mail to clearnet only if you have account at @mail.i2p service.
If you said about sending mail on clearnet services using i2p via outproxy - that's different.

**Comment by Nokia808** [comment]
@r4sas 

I understand now from your replay (+from my search) that I have 2 option to utilize postman mail account that I will create:

1) either use mail client like thunderbird, claw mail, getmail, ........ I read that it is better from security point of view to use dedicated client for i2p email only & not use it for clear net emails. I'm using thunderbird for clear net emails, so I will try to use getmail because it is available in Fedora official repositories ......
or
2) use web interface like susi mail on susi.i2p

But I visited http://susi.i2p & it was down ! See bellow screenshot:

![susi](https://user-images.githubusercontent.com/25375330/55261733-9e255f00-5263-11e9-954a-f6a73adf1d34.png)

**Comment by Nokia808** [comment]
I will close this. But only I need to know what mail client you recommend for i2p ? postmain recommend susi.i2p web interface but this still down ! postmail recommend from it's side Claw mail (rate it 95%) & did not mention bestmail at all ......

**Comment by r4sas** [comment]
I don'k know about susi.i2p, previuosly I mentioned i2p-router integrated susimail.

Everyone used mail clients which they want. For example, I use TheBat! (windows), someone Thunderbird.

All that you need in both ways is create tunnels for fetch and send mail. Example tunnels already provided in tunnels.conf.

**Comment by Nokia808** [comment]
@r4sas 
Dear, to make it more clear, let we take thunderbird as example. It has network setting like Firefox browser - see screenshot bellow:

![setting](https://user-images.githubusercontent.com/25375330/55629678-4cb92a80-57a3-11e9-8692-708c35b4911b.png)

It is - as you see - set to default. So, is it should configured in same way that we use to make Firefox use i2p for browsing i2p sites ? I mean do it should be as following:

select "manual proxy configuration"
set "HTTP Proxy" at 127.0.0.1 & port 4444
set "SSL Proxy" at 127.0.0.1 & port 4444
Then select "No proxy for 127.0.0.1 ......"
& finally "OK"

**Comment by orignal** [comment]
you must create client tunnel and connect your thunderbird to 127.0.0.1

**Comment by Nokia808** [comment]
I clicked on "Add client tunnel" & new tunnel added beside default created one that named "ICR-ICR2P".

But what I have to enter/modify in parameters of this new tunnel ? port, destination port, key, ...... ??

**Comment by xaozai** [comment]
Place in tunnels.conf:

```
[SMTP]
type = client
address = 127.0.0.1
port = 7659
destination = smtp.postman.i2p
destinationport = 25

[POP3]
type = client
address = 127.0.0.1
port = 7660
destination = pop.postman.i2p
destinationport = 110
```
And then configure the email client to use 127.0.0.1:7660 (pop3) and 127.0.0.1:7659 (smtp).

**Comment by Nokia808** [comment]
I tried to modify already created by me new tunnel to be SMTP. Then I added new tunnel to be POP3 but in the meddle of it's setting application crashed !!

I relaunch application again & found that ALL NEW TUNNEL ARE DELETED !! Then I received system error that an error occurred !

I restart application then quit it then relaunch it after 3 minutes, then add only one new tunnel to be SMTP & after finishing this I quit application then wait 3 minutes then relaunch it again BUT NEW TUNNEL WAS DELETED !! Only default tunnel is existing !! Please your help ! Does this need me to open bug report ?

**Comment by orignal** [comment]
edit tunnels manually. QT is not mature enough to use it

**Comment by Nokia808** [comment]
I suspect this ! Restart option seem to be not work ! When I click on restart, no thing happened ......

I found tunnels.conf at:
/home/myusername/.var/app/website.i2pd.i2pd/data
is the above path is the correct one ?

**Comment by Nokia808** [comment]
@xaozai 
You said: "And then configure an email client to use 127.0.0.1:7660 (pop3) and 127.0.0.1:7659 (smtp)"
This should applied for both HTTP Proxy & SSL fields ....

-----------------------
I suggest on you to add on your documents, explanation include all useful data that you kindly learned me in this issue. This will be useful ....

**Comment by xaozai** [comment]
127.0.0.1:7660 и 127.0.0.1:7659 are the addresses and ports of the POP3 and SMTP "servers" respectively. These are not proxy servers.
In this case, you do not need to specify a proxy server in the mail client. 
The encryption settings (SSL, TLS) in this case are also not specified, i.e., everywhere you need to specify 'none' / 'not used'.

**Comment by Nokia808** [comment]
@xaozai 
Okay I understand now. I have to keep network setting of client at "use system default". 

But there is further thing unclear: in there are 2 setting in thunderbird, incoming & outcoming. The outcoming is fixed (SMTP), while incoming is of 2 choices (either IMAP or POP3).

I review i2p site of postman & read it's instructions. It give 2 setting smtp & pop3 as you gave me.

But what about ingoing ?? 

I make 2 fake screenshot to what I suspect to be correct parameters:

sceenshot for smtp:

![smtp](https://user-images.githubusercontent.com/25375330/55646928-ebf21800-57cb-11e9-91ec-7c5a9f3c58e0.png)

screenshot for pop3:

![pop3](https://user-images.githubusercontent.com/25375330/55646964-ff04e800-57cb-11e9-8ba5-58578af4d815.png)

Please ignore user name. It is fake screenshot.
Is this correct ?

**Comment by xaozai** [comment]
![555](https://user-images.githubusercontent.com/8542452/55647856-6a0fe800-57e7-11e9-9381-7e861107b317.png)
~~Блять, сколько упорства, ради того, чтобы на хуй в жопе маргинала посмотреть.~~

**Comment by Nokia808** [comment]
@xaozai 
Now every thing is clear ! I understood now why postman has no web GUI ! It use pop3 protocol for security purpose because this protocol lead to download messages from server to PC in such a way that evacuate server from messages so that no thing remain in server. This the way by which pop3 work which opposite to IMAP protocol which just copy from server not evacuate.

Indeed i2p network very strong & much secure than Tor ! It is very excellent network to build connections for a college members to email their Academic examinations' questions instead of VPN ! And all for free !

However, it is a shortage from postman that not clarify on their site that their service is only POP3 method.

I insist that i2pd project should document on it's site how to set email client to work on i2p email service via i2pd ......

**Comment by K1773R** [comment]
@xaozai it is wrong to believe that pop3 "deletes" mail after fetching them. It is often a default in mail clients, but for the protocol itself the standard is to leave them on the server.
On the postman website you can get all information on how to connect. As IMAP is not mentioned there is no such support obviously.

Regarding documentation, there is plenty of it around already.

**Comment by Nokia808** [comment]
Dear it is not written in clear language for beginner users. I feel that it is written for users came from i2p java to i2pd. 
However, I get excellent support from you & you are very patient with users who asking how to .....
Thank you very much again.
