### ISSUE TITLE
[Question] About use i2pd via foxyproxy

### ISSUE THREAD

**Issue by Nokia808** [PurpleI2P/i2pd#1318]
I set foxyproxy to utilize i2pd & it work okay.

Only one thing I'm concerned about:
In built in "Network Setting" of Firefox (IceCat) i2p recommend the following:
HTTP: 127.0.0.1   /   Port: 4444
SSL Proxy: 127.0.0.1   /   Port: 4444

But in foxyproxy there is no "HTTP+SSL Proxy" single option. We have individual options for "Type of Proxy" as following:
- HTTP
- SOCKS5
- SOCKS4
- SSL
- PAC script for PAC URL
- WPAD
- No proxy
- Use system setting

Guides in Internet speaking about use of HTTP Proxy type for setting i2p on foxyproxy. But what about SSL ? Is there a need to set SSL Proxy also ?

**Comment by r4sas** [comment]
HTTP proxy can handle SSL requests via CONNECT method too.

**Comment by Nokia808** [comment]
@r4sas

Okay, from your response I understood that "HTTP Proxy" type by foxyproxy is very enough & fully equal to Firefox built in setting configuration, in the aim to utilize HTTP & SSL.

Only two further question before closing this issue: what documented in i2p official site is to set browser is to use port: 4444. But yesterday I read document carefully. It say that port: 4444 is for HTTP addresses while port: 4445 is for handling HTTPS addresses !

https://geti2p.net/en/about/browser-config

As you see, regarding Internet explorer, it asking to use port: 4444 for HTTP while port: 4445 for HTTP (secure). The same is applied for OLD version of Firefox: port: 4444 for HTTP while port: 4445 for SSL 

But, as appear in above link, for recent up to date version of Firefox: port: 4444 for both HHTP & SSL.

My questions now are two:

1) does using of port: 4444 for both HTTP & SSL in up to date Firefox internal buil in setting is enough to utilize both HTTP & HTTPS addresses ?

2) does HTTP Proxy type setting for i2p using port 4444 only is enough to utilize both HTTP & HTTPS addresses ?

**Comment by r4sas** [comment]
I realy dont know about differencies in i2p's 4444 and 4445 ports.


> * does using of port: 4444 for both HTTP & SSL in up to date Firefox internal buil in setting is enough to utilize both HTTP & HTTPS addresses ?
> * does HTTP Proxy type setting for i2p using port 4444 only is enough to utilize both HTTP & HTTPS addresses ?

For both answer is one - yes if used i2pd.

**Comment by Nokia808** [comment]
@r4sas 

Okay I will closed this issue. But please edit your previous replay regarding question 2 as I updated it in my post: I added [in foxyproxy] so that to be:

does "HTTP Proxy" type setting [in foxyproxy] for i2p using port 4444 only is enough to utilize both HTTP & HTTPS addresses ?

This better to make it clear for readers & to avoid confusion.

Thank you for kind help !

**Comment by r4sas** [comment]
> But please edit your previous replay regarding question 2 as I updated it in my post

Edited previous post.
Answer will be same, because our 4444 HTTP proxy can handle CONNECT requests, which used by HTTPS SSL connections.

Have a try with https://stats.i2p/ or https://r4sas.i2p/

**Comment by Nokia808** [comment]
Okay, I tried the sites you suggested & in both cases IceCat block them due to invalid certificates !! I think that there is an error ! I tried both IceCat built in setting & foxyproxy HTTP Proxy but same result ! See following:

![4rsas](https://user-images.githubusercontent.com/25375330/55262189-f0b34b00-5264-11e9-960c-7881774ad48f.png)
![stats](https://user-images.githubusercontent.com/25375330/55262190-f0b34b00-5264-11e9-9e69-bdc9ce8d64bd.png)

**Comment by orignal** [comment]
click "advanced" and allow those certificates explicitly or install them in advance

**Comment by Nokia808** [comment]
@orignal 

From my knowledge - please correct to me if this not applied to i2p sites - that what you command me is too extremely dangerous & very risky ......

Is the case different on i2p ? I read - in mail setting - something like that: "no need for activate SSL/TSL because  i2p network do encryption by itself & no need to additional layer ..." But I feel that this not the case for eepsites ?! Is it needed to do what you command me to do for every https:// i2p site ?

**Comment by r4sas** [comment]
@Nokia808 reason is because everyone in i2p used self signed certificates. No one able to request validated by third-party CA service because it spoils anonymity.
