### ISSUE TITLE
[SAM] Incorrect response on stream connect with invalid key.

### ISSUE THREAD

**Issue by nglen** [PurpleI2P/i2pd#1319]
Within SAMSocket::ProcessStreamConnect, the incorrect status is returned for invalid keys.

**Given Response**
> SESSION STATUS RESULT=INVALID_KEY

**Expected Response**
> STREAM STATUS RESULT=INVALID_KEY

**Comment by orignal** [comment]
Could you point to specs? I'm not sure what we are supposed to return in case of invalid destination

**Comment by nglen** [comment]
https://geti2p.net/en/docs/api/samv3 under **Connect Response** states that the valid response to STREAM CONNECT is

> STREAM STATUS RESULT=$result [MESSAGE=...]

where the result value may be one of

> OK
> CANT_REACH_PEER
> I2P_ERROR
> INVALID_KEY
> INVALID_ID
> TIMEOUT

The current response is only specified as a valid response for session creation.
The only issue is that STREAM should be used in this context instead of SESSION.

The other responses already use STREAM as shown in SAM.h
