### ISSUE TITLE
Compiler too old on too new compiler

### ISSUE THREAD

**Issue by yangfl** [PurpleI2P/i2pd#1321]
Fail to build with `make` on gcc 9

refs:
https://github.com/PurpleI2P/i2pd/blob/openssl/Makefile.linux#L22
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=925715

**Comment by r4sas** [comment]
Yes, it can be because currently gcc 9 is not added in Makefile (which used by make, not cmake).

**Comment by r4sas** [comment]
Resolved in https://github.com/PurpleI2P/i2pd/commit/ed116e7cea4de322ccaad44e929add978477ac53
