### ISSUE TITLE
[Question] what is difference between "Quit" & "Graceful quit" ?

### ISSUE THREAD

**Issue by Nokia808** [PurpleI2P/i2pd#1323]
I tried Wiki, Documentation, FAQ, & finally i2pd-dev - freenode Web IRC but no answer ....

**Comment by l-n-s** [comment]
Graceful quit is the right way to shut down I2P. It waits 10 minutes for all transit tunnels to expire, so that you don't harm the network.

**Comment by r4sas** [comment]
> i2pd-dev - freenode Web IRC but no answer ....

Gate to i2p on this channel is not works, so no one seen your messages on Irc2P.

**Comment by orignal** [comment]
@mikalv could you  check your relay bot?

**Comment by Nokia808** [comment]
Okay, but one note further on this: currently I added i2pd to my "Startup Applications" to run at each boot/restart/login.
In this case, it will be like "systemd enable". In both case. it is unlikely user "quit gracefully" before every restart or logout/login
