### ISSUE TITLE
Is the "Received" and the "Sent" include the "Transit"?

### ISSUE THREAD

**Issue by nkwjnpxrgfbfid** [PurpleI2P/i2pd#1324]
Is the "Received" and the "Sent" show in i2pd's webconsole's  Main page include the "Transit"?
For example:
```
Received: x.xx MiB (x.xx KiB/s)
Sent: x.xx MiB (x.xx KiB/s)
Transit: x.xx MiB (x.xx KiB/s)
```

**Comment by orignal** [comment]
Yes, transit appears in sent and received and the rest is own traffic
