### ISSUE TITLE
[Feature request] Please add "Start to system try" option. 

### ISSUE THREAD

**Issue by Nokia808** [PurpleI2P/i2pd#1326]
Hi. 
I add i2pd to my "Startup Applications" to be run at boot/restart system.

It working to start automatically at boot/restart/log in system okay.

The only annoying issue is that at each automatic start up, the i2pd's application window emerges to me, which is not good. To overcome this behaviour you can add new option: "Start to system try" by which when i2pd launched, it's window do not appear. Instead it's icon appear in system try panel only, & user can bring application window of i2pd thereafter by click it's icon in system try panel as usual ............... This feature is existing in some applications like Golden Dictionary (GoldenDict).

**Comment by nonlinear-chaos-order-etc-etal** [comment]
WONTFIX FOR NOW. IF SOMEONE WANTS DO A PR

**Comment by nonlinear-chaos-order-etc-etal** [comment]
@r4sas PLEASE CLOSE THIS, SEE ABOVE
