### ISSUE TITLE
[Question] 2 options disabled by default, is there problem from use them?

### ISSUE THREAD

**Issue by Nokia808** [PurpleI2P/i2pd#1330]
Hi. There are, currently, 2 disabled by default options under general setting:

1st option is "Use ElGamal precomputed tables"
2nd option is "Should we hide our router from other routers?

I have feeling that these 2 options - if enabled - will increase security, arn't they?
Is there any problem from using them?

In i2p official page they said what mean "it is normal to see ip of other routers ...... this is the way in which decentralized peer to peer working ......" So, is the 1st option in i2pd is feature not existing in java i2p application ?

Also, I read that i2p use ElGamal encryption by default .... so why it is disabled in i2pd ?

Please appreciate that I'm beginner with i2p & for that my asking some not perfect questions, & for that if occurring accept my sorry ....

**Comment by orignal** [comment]
ElGamal is not disabled, ElGamal **precomputation**  is disabled, because it consumes 16M extra memory on x64. If you have enough memory you should enable it because it makes ElGamal and DH much faster

**Comment by Nokia808** [comment]
Okay, I will try. But what about second option "hide ip from other routers" ?

**Comment by orignal** [comment]
Don't use it unless you know what do you need it for. Bottom line is lack of transit traffic

**Comment by Nokia808** [comment]
So 2nd option is lowering security not enhance it, right ?

**Comment by orignal** [comment]
I told you already, don't use thing you don't understand

**Comment by Nokia808** [comment]
Okay. Thank you. I will close this issue.

**Comment by Nokia808** [comment]
@orignal 
Dear regarding 1st option that I should use if I have enough memory, do you said 16 MB ? I have 8 GB RAM on my system. I wish you was right & it is 16 MB not 16 GB ....

**Comment by orignal** [comment]
16 MB. You might be aware about it on low-level vps or routers

**Comment by Nokia808** [comment]
No I have no experience at all. I'm simple desktop user interested in replace VPN usage by such network like i2p. Specially I'm interested by i2p email application because they seem suitable to secure connection preventing from hackers.

Can you explain kindly what 16 MB mean? Is it not suitable for slow connections ?

**Comment by K1773R** [comment]
He already explained it, twice...

**Comment by Nokia808** [comment]
Okay!
