### ISSUE TITLE
webconsole enabled by default but 127.0.0.1:7070 do not displaced !

### ISSUE THREAD

**Issue by Nokia808** [PurpleI2P/i2pd#1331]
I use flatpak package. "webconsole is enabled by default. But when I try:
127.0.0.1:7070
I received "127.0.0.1:7070" is out of i2p. Outproxy not enabled"
Is this normal ?

**Comment by orignal** [comment]
you are trying to connect through the proxy

**Comment by Nokia808** [comment]
You mean I should browser set to be use normal default connection (not i2p network) ?

**Comment by xaozai** [comment]
don't use proxy for local destinations

**Comment by Nokia808** [comment]
Yes, I tried it on my normal Firefox & it work. It is misunderstanding from my side because I'm beginner with i2p & not system or server admin.

I will close this issue.

Thank you.
