### ISSUE TITLE
[Feature request] make "POP3" & "SMTP" client tunnels set by default on i2pd

### ISSUE THREAD

**Issue by Nokia808** [PurpleI2P/i2pd#1332]
Dear developers team. Email i2p service is very important feature of i2p network. Also, no other i2p service providers are available (please correct to me if wrong). Also, plugin not work with i2pd. So, it will be much better for your project & its users to make POP3 & SMTP client tunnel to be both set by default in i2pd along side with the current IRC-IRC2P tunnel.

**Comment by K1773R** [comment]
It is not on per default since most people dont need it. In the default tunnel.conf the entries are already there so you can just uncomment and enable them.

**Comment by Nokia808** [comment]
I'm not sure about the mind of i2p network users. But I see i2p email applications are much more important for work than browsing i2p sites. By using i2p email & maintain communication within i2p is there further need to VPN !! I do not think there is need further for VPN. 
I2P work like Retroshare .....

If you like, close this issue. Or you can change it's title to be a request to enable (uncomment) these 2 tunnels by default ....

**Comment by K1773R** [comment]
It would probably make more sense to have a nice entry in the docu about how to enable pop3/smtp instead of enabling it for everyone.

**Comment by l-n-s** [comment]
It's an optional feature of the current I2P network. Some may find it useful, some may not.

**Comment by Nokia808** [comment]
Hi again. I tried to uncomment them but there is strange behaviour ! 
I open:
/home/myusername/.var/app/website.i2pd.i2pd/data/.i2pd/tunnels.conf
using xed text editor. I uncomment them, then save changes & close file.

But when I launch i2pd I did not see these tunnels in "Tunnels settings" !! For that I open the above file (tunnels.conf) & I shocked when I saw them commented again !! 

How this happened ? What this behaviour ? I repeat trails but same failure happened !

Please your kind advice.

**Comment by l-n-s** [comment]
I guess you'll need to edit and save config files BEFORE you start i2pd

**Comment by Nokia808** [comment]
@l-n-s 
Dear not work at all ! I edit file while application OFF. Then save changes & reopen file to see if changes saved or not & they were saved. After that I launched i2pd but this will override all changes & reset them to be commented !! I restart my PC & re-traid but same error!! What is this ??

**Comment by r4sas** [comment]
Show how you edited it.

**Comment by Nokia808** [comment]
Hi. Look for screenshot to see how I edit it:

![uncomment](https://user-images.githubusercontent.com/25375330/55667348-af193600-584a-11e9-8914-54c5c3f7afe8.png)

I click "Save" to save changes, then close file after "Save". After that, I re-open the file to be sure that it is really saved, & it was really saved - all my changes are saved.

But after that I close file, then launch i2pd, & I did not see POP3 & SMPT tunnels. So, I "quit" the i2pd then go to see the file & I saw that it return as it was before my changes & all my changes are disappeared !!

**Comment by r4sas** [comment]
@l-n-s ideas?

I think this is snap env issue.

**Comment by Nokia808** [comment]
No ! No at all it is not snap ! I have no snap on my system. It is flatpak package from Flathub.org installed on Fedora Linux 28 X64 bit Cinnamon edition. Also, I have no any error message from SELinux on my system related to i2pd or flatpak or other sector in my env

**Comment by r4sas** [comment]
Doesn't matter, thats not i2pd itself problem, but flatpack as you said.

**Comment by Nokia808** [comment]
Okay, the next question is that: does flatpak package of i2pd that existing in Flathub is official or not ? If official that is all & remaining fix on your side. But if not official, then I have to open bug report on Flathub. They respond quickly.

At 1st I thought the flatpak package is official because GNOME software center show it to be labelled as "Activity release". But I brows the available packages on your "Release" section in this page, but I did not find flatpak package. For that I'm asking here .....

**Comment by r4sas** [comment]
As I know, all flatpack stuff in `i2pd/qt/i2pd_qt/data/` folder.
