### ISSUE TITLE
Enable UPnP in raspberry pi stretch deb package

### ISSUE THREAD

**Issue by prurovou** [PurpleI2P/i2pd#1333]
I've installed i2pd successfully on raspbian and it does work, however, the network shows as "Firewalled". To remedy this I've tried activating UPnP, but this fails with this showing up in the logs: "warn - UPnP: this module was disabled at compile-time".

Looking through the make files, it seems like UPnP is off by default and was not enabled for the i2pd_2.24.0-1stretch-rpi1_armhf.deb. If it's possible please enable UPnP for this build.

**Comment by r4sas** [comment]
Sorry, I missed that issue earlier.

> Looking through the make files, it seems like UPnP is off by default and was not enabled for the i2pd_2.24.0-1stretch-rpi1_armhf.deb. If it's possible please enable UPnP for this build.

All debian/ubuntu/raspbian packages built with same one configuration, so this requires creating different package configurations.

@orignal what do you think about enabling upnp at compile time, but disabling by default for linux in config?

**Comment by r4sas** [comment]
bump.

**Comment by r4sas** [comment]
https://github.com/PurpleI2P/i2pd/commit/da0b36cb91697a000cd79b4e782effc143e4dc66
