### ISSUE TITLE
nc: connection failed, unsupported address type

### ISSUE THREAD

**Issue by pfactum** [PurpleI2P/i2pd#1336]
Trying to get `ssh` working on top of `i2p`.

#### `i2pd.conf`

```
log = syslog
loglevel = error
notransit = true

[http]
enabled = false

[socksproxy]
enabled = false

[httpproxy]
enabled = false

[sam]
enabled = false
```

#### `tunnels.conf`

```
[ssh]
type = server
host = 127.0.0.1
port = 22
keys = ssh-privkey.dat
```

#### `i2pd.conf`

```
log = syslog
loglevel = error
notransit = true

[http]
enabled = false

[httpproxy]
enabled = false

[sam]
enabled = false
```

#### `tunnels.conf`

The file is empty.

#### `.ssh/config`

```
Host example
        HostName xxx.b32.i2p
        Port 22
        ProxyCommand nc -X 5 -x 127.0.0.1:4447 %h %p
```

Error message on the client:

```
$ ssh example
nc: connection failed, unsupported address type
ssh_exchange_identification: Connection closed by remote host
```

The very same `ProxyCommand` configuration (except the port, obviously) works just fine with `Tor`. Also, I'm sure `i2p` works too because `curl` works:

```
$ curl --socks5-hostname 127.0.0.1:4447 xxx.b32.i2p:22
SSH-2.0-OpenSSH_7.9
Protocol mismatch.
```

So this might be something that dissatisfies `nc`.

Could you please suggest on how to make `ssh+nc` working in this case?

Thanks.

**Comment by pfactum** [comment]
Also, connecting to the server via client tunnel also works:

### Client

#### `tunnels.conf`

```
[ssh-example]
type = client
address = 127.0.0.1
port = 25001
destination = xxx.b32.i2p:222
keys = ssh-example.dat
```
Proof:

```
$ ssh -p 25001 127.0.0.1    
Last login: Wed Apr 10 14:21:58 2019 from 127.107.6.210
```

So definitely must be some `nc` thing.

**Comment by r4sas** [comment]
I'm using connect-proxy:
```
Host address.b32.i2p
        User user
        IdentityFile ~/.ssh/key.i2p
        ProxyCommand connect-proxy -4 -R remote -S 127.0.0.1:4447 %h %p
```

**Comment by pfactum** [comment]
Thanks for the suggestion, I can confirm that `connect-proxy` works too.

But what's wrong with `nc`?

**Comment by r4sas** [comment]
Really don't know. Maybe protocol misunderstanding?

**Comment by r4sas** [comment]
A think this is nc's bug:

https://github.com/solrex/netcat/blob/ed802bae8320d4ea36d94977edb7feac5579787e/socks.c#L230-L243
->
https://github.com/solrex/netcat/blob/ed802bae8320d4ea36d94977edb7feac5579787e/socks.c#L179-L219
->
https://github.com/solrex/netcat/blob/ed802bae8320d4ea36d94977edb7feac5579787e/socks.c#L160-L162
->
https://github.com/solrex/netcat/blob/ed802bae8320d4ea36d94977edb7feac5579787e/socks.c#L72

**Comment by pfactum** [comment]
@r4sas any info is needed from me? Are you able to reproduce the issue on your own?

**Comment by r4sas** [comment]
> @r4sas any info is needed from me? Are you able to reproduce the issue on your own?

yes, I can.
btw, you can use HTTP proxy with CONNECT mode (our 4444 HTTP proxy supports it):
`nc -X connect -x 127.0.0.1:4444 <b32.i2p> <port>`

**Comment by pfactum** [comment]
Okay, thanks for letting me know. `CONNECT` indeed works.

**Comment by r4sas** [comment]
I think that cant be solved due to unsupported by netcat domain resolving via socks5 proxy (socks5h).
https://salsa.debian.org/debian/netcat-openbsd/blob/master/socks.c#L72-80

As you can see, nc calling `getaddrinfo` which resolves domain name in IP address. It will fail due to unsupported zone by DNS resolver (`.i2p`).
That's why we hit [line 212](https://salsa.debian.org/debian/netcat-openbsd/blob/master/socks.c#L212) and got error after checking host [address type](https://salsa.debian.org/debian/netcat-openbsd/blob/master/socks.c#L293).

**Comment by pfactum** [comment]
@r4sas but TOR works for me in a similar way (I use `ProxyCommand nc -X 5 -x 127.0.0.1:9050 %h %p` for SSH, for instance). Do I miss something?

**Comment by r4sas** [comment]
With .onion address?

**Comment by pfactum** [comment]
> With .onion address?

Yes, like this:

```
Host host-tor
        HostName longtoraddress.onion
        Port 22
        ProxyCommand nc -X 5 -x 127.0.0.1:9050 %h %p
```

**Comment by r4sas** [comment]
![image](https://user-images.githubusercontent.com/7023612/71447693-b7036800-2742-11ea-9e31-e4afacea2985.png)

@majestrate ping.

**Comment by r4sas** [comment]
That makes trick:
```diff
diff --git a/libi2pd_client/SOCKS.cpp b/libi2pd_client/SOCKS.cpp
index 8a67901c..88b3f06c 100644
--- a/libi2pd_client/SOCKS.cpp
+++ b/libi2pd_client/SOCKS.cpp
@@ -246,6 +246,9 @@ namespace proxy
                                size = 7+addr.dns.size;
                                m_response[4] = addr.dns.size;
                                memcpy(m_response+5,addr.dns.value, addr.dns.size);
+                               // replace type to IPv4 for support socks5 clients
+                               // without domain name resolving support (like netcat)
+                               m_response[3] = ADDR_IPV4;
                                break;
                }
                htobe16buf(m_response+size-2,port); //Port
```

**Comment by r4sas** [comment]
btw, custom socksproxy tunnel works correctly - here address wrapped as IPv6:
```write(3, "\5\1\0", 3)                   = 3
read(3, "\5\0", 2)                      = 2
write(3, "\5\1\0\3\tr4sas.i2p\0P", 16)  = 16
read(3, "\5\0\0\4", 4)                  = 4
read(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 18) = 18
poll([{fd=0, events=POLLIN}, {fd=3, events=0}, {fd=3, events=POLLIN}, {fd=1, events=0}], 4, -1) = 1 ([{fd=3, revents=POLLIN}])
read(3, "", 16384)                      = 0
```

**Comment by r4sas** [comment]
That fix can broke SOCKS usage in some implementations, so I reverted it.

Will think again later.

**Comment by xanoni** [comment]
Has this been fixed? I'm still getting the same error on MacOS. See version info below.

```bash
$ i2pd --version                                                                                                                                                                      ~
i2pd version 2.38.0 (0.9.50)
Boost version 1.75.0
OpenSSL 1.1.1k  25 Mar 2021
```

**Comment by r4sas** [comment]
Yes, it was.
If you still have problems, give more information about software used with SOCKS proxy and traffic dump between your application and i2pd's SOCKS proxy.

**Comment by xanoni** [comment]
> give more information about software used with SOCKS proxy

I was testing this with Telegram for Desktop (https://github.com/telegramdesktop/tdesktop). It works fine with Tor's SOCKS5 proxy on `localhost:9050`, but didn't work with I2P on `localhost:4447` despite `false.i2p` being turned on as an exit.

> and traffic dump between your application and i2pd's SOCKS proxy.

Don't have access to the machine now but can share that later this week if the above info doesn't already solve it.

**Comment by r4sas** [comment]
You can't use `false.i2p` as outproxy in `[socksproxy]` section because `outproxy` + `outproxyport` options must point to SOCKS proxy server, not HTTP.

**Comment by xanoni** [comment]
> You can't use `false.i2p` as outproxy in `[socksproxy]` section because `outproxy` + `outproxyport` options must point to SOCKS proxy server reachable locally, not inside I2P, and not HTTP.

Yeah I got very confused. It's actually pointing at a local Tor SOCKS proxy (localhost:9050). The same proxy that works with Telegram if used directly.

**Comment by r4sas** [comment]
So in your `i2pd.conf` you have such configuration?
```
outproxy.enabled = true
outproxy = 127.0.0.1
outproxyport = 9050
```

Yes... I see that i2pd didn't handling response from upstream proxy... I'll open new issue about that.

**Comment by r4sas** [comment]
Opened #1683
