### ISSUE TITLE
[Feature request] Implement i2p-bote in i2pd

### ISSUE THREAD

**Issue by Nokia808** [PurpleI2P/i2pd#1337]
Hi. We have talked about plug-in of i2p & I know that plug-ins not working with i2pd.

But i2p-bote plug-in seem to be very secure e-mail alternative being DECENTRALIZED (SERVERLESS) like tox & Jami messengers. More over, on the road of it's development is adding outproxy to it to allow it to communicate with clearnet email servers like Yahoo, Gmail, .......

Also, it provide basic support to human readable email user names, opposite to bot message .......

It is great loss & shortage for i2pd not support this plug-in ! Many users how search for VPN alternative will feel that original java i2p package is currently providing broader abilities than i2pd.

In fact i2pd being ++C language is something very good. But non compatibilities with plug-in is big problem !

Susi mail could be replaced by email client like claw mail or thunderbird (though this not 100% like Susi mail). But fully decentralized service like i2p-bote (that could be in future communicate with clear net emails & currently support human readable user name) is great loss if not integrated with i2pd ........

For that I suggest to include i2p-bote in i2pd.

**Comment by majestrate** [comment]
ideally it should be standalone, you may be interested in my attempt https://github.com/majestrate/i2pboted

**Comment by Nokia808** [comment]
This is O.K but it is not available in flatpak & last commit at 2017 & nothing in "release" section ! Is this program alive ?? Is it fully developed ?? If yes, can you kindly add it to flatpak ?

**Comment by majestrate** [comment]
it's not finished and I haven't had much time latenly to finish it. also i cannot find any libraries that implement the ntru encryption that it uses

**Comment by orignal** [comment]
@majestrate so you have implemented your own bote?

**Comment by Nokia808** [comment]
@orignal 
You can help him to complete it. It will be useful add to your current i2pd.

**Comment by r4sas** [comment]
@Nokia808 go ahead and help him.
Everyone have own work and time.
