### ISSUE TITLE
Boot time increased too after autostart of i2pd

### ISSUE THREAD

**Issue by Nokia808** [PurpleI2P/i2pd#1338]
When I added i2pd to start up by my Cinnamon DE start up applications (adding i2pd to it's list), boot time become long .......

Is there a way to improve this by fix or patch ?

**Comment by r4sas** [comment]
No info - no help.

**Comment by l-n-s** [comment]
Be more specific. Do you use Flatpak package? Does it start quickly when you run it manually?

**Comment by Nokia808** [comment]
Good morning.

- I'm using flatpak package because nor i2pd nor i2p available in official Fedora repositories,
- when I launch i2pd manually it start without delay (bringing UI to me),
- Fedora using SELinux which lead to slowing in boot in comparison with other distros,
- I have no SELinux error message,
- my laptop using HHD not SSD,
- my booting time without i2pd autostart is 2 minutes + 37 seconds (long). But when I activate i2pd autostart, it increased by 1 minute !

Is there any further data can I supply you ?

**Comment by l-n-s** [comment]
I'm pretty sure it's not i2pd's issue. Probably this is how Flatpak works, try adding other Flatpak apps instead of i2pd to autostart and test it.

**Comment by r4sas** [comment]
> * I'm using flatpak package because nor i2pd nor i2p available in official Fedora repositories,

https://copr.fedorainfracloud.org/coprs/supervillain/i2pd/

**Comment by Nokia808** [comment]
@r4sas 
This is COPR repository not OFFICIAL Fedora repository. I tried some 3rd party repositories (apart from RPMFusion repositories) & all them created problems. Moreover, adding 3rd party repository that it's owner not official Fedora packager is risky (give root access for someone you not able to trust).

I know about this repository & contact it's owner. He is unable to become Fedora packager.

**Comment by r4sas** [comment]
Flatpak is NOT OFFICIAL repository TOO. All software maintained by someone, in most cases - not original authors of software.
That repository, at copr, created by @l-n-s and maintained by me.
