### ISSUE TITLE
Hash of release package

### ISSUE THREAD

**Issue by linsui** [PurpleI2P/i2pd#1339]
Could you please provide checksum for packages?

**Comment by SilmorSenedlen** [comment]
And maybe you can add PGP signatures too?
If it's not too much trouble for you, this would be great solution for authentication of downloaded files.

**Comment by r4sas** [comment]
> And maybe you can add PGP signatures too?

Added sig for SHA512SUMS. Signed with [66F6C87B98EBCFE2](http://keyserver.ubuntu.com/pks/lookup?op=vindex&search=0x66F6C87B98EBCFE2)

**Comment by SilmorSenedlen** [comment]
Thx!
