### ISSUE TITLE
Don't use IPv4 from special address space as external IP

### ISSUE THREAD

**Issue by r4sas** [PurpleI2P/i2pd#1346]
https://en.wikipedia.org/wiki/IPv4#Special-use_addresses

todo: check if the found external IP address is in these subnets, and treat them as invalid.
Generally:
* 10.0.0.0/8
* 100.64.0.0/10
* 127.0.0.0/8
* 172.16.0.0/12
* 192.168.0.0/16

add: https://github.com/i2p/i2p.i2p/blob/master/installer/resources/blocklist.txt

**Comment by l-n-s** [comment]
It also needs an option to allow private networks for the testnet
