### ISSUE TITLE
Web console doesn't work in Windows build

### ISSUE THREAD

**Issue by orignal** [PurpleI2P/i2pd#135]
Port 7070 just non-responding.

**Comment by ygrishin** [comment]
mine

**Comment by ygrishin** [comment]
Fixed my VM finally, back on this.

**Comment by orignal** [comment]
Please create pull request

**Comment by netwire-wwl** [comment]
Open HTTPServer.cpp and remove those 2 images (base64 encoded), you can write anything instead, i did "test" and "test1" to see result, and never changed later :)

Recompile, and enjoy localhost:7070

**Comment by orignal** [comment]
Good pont, will do.

**Comment by ygrishin** [comment]
Fix suggested netwire-wwl doesn't work for me.

**Comment by netwire-wwl** [comment]
Example how it looks like..

	const std::string HTTPConnection::itoopieImage =  "test";

	const std::string HTTPConnection::itoopieFavicon = "test1";

I couldn't also access "web console" and couldn't open any i2p site, after removing images, all good.

**Comment by ygrishin** [comment]
That's exactly what I'm having. I am afraid this does not fix the problem this ticket was started: the http connection on port 7070 keeps being reset. Could you please explain why would it fix that?

**Comment by orignal** [comment]
I think VS has some limitation for length of string constants.
I remember chertov mentioned something like this.

**Comment by ygrishin** [comment]
original, are you able to "assign" me for the ticket because it's now showing that's "nobody's assigned". I am actively working on it but it will take some time that I need to familiarize myself with the code base and understand what's it does VS what it supposed to. We do not want to apply just random "fixes", do we?

**Comment by netwire-wwl** [comment]
The maximum length of a string literal is 65535 bytes.
Src >> https://msdn.microsoft.com/en-us/library/69ze775t.aspx

**Comment by ygrishin** [comment]
Well, that definitely does not apply here as:
[code]const std::string HTTPConnection::itoopieImage[/code] is around 12k and
[code]const std::string HTTPConnection::itoopieFavicon[/code] close to 24k.

**Comment by orignal** [comment]
I think that's the problem
boost::asio::async_write (*m_Socket, m_Reply.to_buffers(status),
			boost::bind (&HTTPConnection::HandleWriteReply, this,
				boost::asio::placeholders::error));

must be called with transfer_all  condition

**Comment by ygrishin** [comment]
You can test your hypothesis against reality in no time.

**Comment by kytvi2p** [comment]
Now that https://github.com/PurpleI2P/i2pd/pull/151 has been merged I can access http://127.0.0.1:7070 in Windows. :)

**Comment by ygrishin** [comment]
Good good. This issue can be closed, I guess.

**Comment by kytvi2p** [comment]
> Good good. This issue can be closed, I guess.

I contemplated closing it but I didn't know if I should making that call. *Erring on the side of caution* and all. ;)

**Comment by orignal** [comment]
kytv, do you see any other windows-specific issues, like lack of tunnels what Cryptoslave mentioned?
If so it's good time to let ygrishin take a look.

**Comment by ygrishin** [comment]
I can't confirm that. There are tunnels on both Windows and Linux. Repo is from last Friday or Saturday with my patch.
