### ISSUE TITLE
i2pd BOB implementation doesn't accept some commands from telnet

### ISSUE THREAD

**Issue by rszibele** [PurpleI2P/i2pd#1351]
If you connect to BOB via. telnet like described here https://geti2p.net/en/docs/api/bob then it doesn't work as expected. Some commands work, but others do not:

![image](https://user-images.githubusercontent.com/1387224/58061144-327db500-7b75-11e9-89f2-0b4a4d508480.png)

![image](https://user-images.githubusercontent.com/1387224/58061531-d2880e00-7b76-11e9-8f39-80852f60ca47.png)
![image](https://user-images.githubusercontent.com/1387224/58061634-4f1aec80-7b77-11e9-9f9d-3e368534f429.png)

I'm working on a BOB C++ (QTcpSocket) client library and I use `\n` terminators and all commands work. Here's a Wireshark grab:
![image](https://user-images.githubusercontent.com/1387224/58061365-27775480-7b76-11e9-816f-908169dd9515.png)
![image](https://user-images.githubusercontent.com/1387224/58061413-4ece2180-7b76-11e9-8beb-1cd27d04293a.png)

The only difference between telnet and my working library are the line terminators `\r\n` vs `\n`. I assume it's due to `help`, `start` and `newkeys` requiring no arguments while `setnick`, `inhost` and `inport` require an argument, so it's a different code path where `\r\n` isn't handled.

**Comment by r4sas** [comment]
https://github.com/PurpleI2P/i2pd/blob/60ec03237e61d0cec24feacb68abacdf872cbb27/libi2pd_client/BOB.cpp#L256-L260

**Comment by orignal** [comment]
You must use nc instead

**Comment by LLE8** [comment]
May be helpful
```
man telnet
....
                crlf          If this is TRUE, then carriage returns will be
                              sent as <CR><LF>.  If this is FALSE, then car‐
                              riage returns will be send as <CR><NUL>.  The
                              initial value for this toggle is FALSE.
```

**Comment by rszibele** [comment]
Is this by design or should i2pd BOB be compatible with Java I2P BOB reference implementation?

**Comment by orignal** [comment]
I guess Java just replaces "\r\n" to "\n" when read next string

**Comment by majestrate** [comment]
On Tue, May 21, 2019 at 06:13:44AM -0700, orignal wrote:
> I guess Java just replaces "\r\n" to "\n" when read next string
is BOB properly buffered or does it require the line sent in the same tcp segment?

**Comment by rszibele** [comment]
@majestrate I forgot to reply. The both the [Java implementation](https://github.com/i2p/i2p.i2p/blob/7c5162e1557ed5b93f03c13c33a7b95dc147a17d/apps/BOB/src/net/i2p/BOB/DoCMDS.java#L351) and the i2pd implementation are properly buffered.
