### ISSUE TITLE
BOB list command has wrong output format

### ISSUE THREAD

**Issue by rszibele** [PurpleI2P/i2pd#1352]
With the `list` command i2pd only outputs the nickname and without a `:` after the key so it's not compatible with the Java I2P reference implementation.

```
$ nc localhost 2827
BOB 00.00.10
OK
list
NICKNAME test
OK Listing done
```

It should be:
```
list
DATA NICKNAME: test STARTING: false RUNNING: true STOPPING: false KEYS: true QUIET: false INPORT: 33555 INHOST: localhost
OK Listing done
```

**Comment by orignal** [comment]
will fix

**Comment by rszibele** [comment]
Will the other keys and values `STARTING`, `RUNNING`, `STOPPING`, `QUIET`, `INPORT` and `INHOST` also be added?

**Comment by orignal** [comment]
It reequires more work.  Maybe later. Use 'status' for now
