### ISSUE TITLE
http://127.0.0.1:7070 say host mismatch

### ISSUE THREAD

**Issue by RicFer** [PurpleI2P/i2pd#1356]
I can browse eepsites but I can not see the status of the router. Where to look?

**Comment by rszibele** [comment]
Are you talking about the web console at http://127.0.0.1:7070 ?

**Comment by RicFer** [comment]
Yes

**Comment by r4sas** [comment]
What are you using?
Configuration?

Telepaths on vacation.

**Comment by RicFer** [comment]
Sorry. ;-)

OS: Raspbian stretch
Software version:  i2pd version 2.25.0 (0.9.40) / Boost version 1.62.0 / OpenSSL 1.1.0j  20 Nov 2018

i2pd.conf:
```
port = ******     
ipv4 = true                                             
ipv6 = false                   
bandwidth = O                                    
share = 90                                   
[http]
address = 0.0.0.0
port = 7070                                      
[httpproxy]                                                    
address = 127.0.0.1
port = 4444
[socksproxy]                                                                         
address = 127.0.0.1
port = 4447  
[sam]
enabled = true                    
[reseed]            
verify = true 
```

**Comment by RicFer** [comment]
Searching through the code I found the line with the string **"host mismatch**".  911 line in **HTTPServer.cpp** file

As far as we can see, if "strictheaders" is true and my ip is not in "http.hostname" return "host_mismatch".

Adding this line in i2pd.conf is all fixed.
`
strictheaders = false`

Thank you ;-)
