### ISSUE TITLE
i2pd building process exhausts memory on machines with low RAM

### ISSUE THREAD

**Issue by holymonson** [PurpleI2P/i2pd#1358]
I was building i2pd on Raspberry Pi and failed, finally found that compiling I2PControl.cpp would exhaust nearly __1G__ of memory and generate a __1.2M__ size .o file. It is too large and unfriendly for small machines. The code in I2PControl.cpp seems alreadly divided in several parts, is it appropriate to split up into several files?

**Comment by r4sas** [comment]
All code in that source file belongs to one class `I2PControlService`, so I don't think it's possible to split it.

I'm building i2pd for releases (armhf, arm64, armhf-rpi) on rpi (3b+) too.
If you building from sources, better use swap (256M is enough) and only one thread (-j1).

**Comment by orignal** [comment]
We should have an option to exclude it from build instead

**Comment by l-n-s** [comment]
A good point @r4sas made about swap. It's not possible to build i2pd without swap on a lower RAM VPSes. I usually add a swap file twice larger than RAM size

like that:
```
dd if=/dev/zero of=/swapfile bs=256M count=4 && \
chmod 600 /swapfile && \
mkswap /swapfile && \
swapon /swapfile
```

**Comment by holymonson** [comment]
Using swap is a not-friendly-enough solution and I did use it finally. But `I2PControl.cpp` is still too large, although it all belongs to class `I2PControlService`, we could split it into `I2PControl/XXX.cpp` or `I2PControl-XXX.cpp`.

In my own conpany, auto-building machines usually acquire 1G memory, so we tend to split files into a suitable size. This issue is raised merely as a suggestion, you can close it if remaining a whole file is preferable.

**Comment by orignal** [comment]
The size comes from  boost JSON parser, not from I2PControl.cpp itself

**Comment by strasharo** [comment]
I'm building it fine by mounting a 2G swap file on an external USB hard drive:
```
fallocate -l 2G swapfile
chmod 600 ./swapfile
mkswap ./swapfile
sudo swapon ./swapfile
```
