### ISSUE TITLE
2.26.0 crashes on launch on macOS when ipv6=true is enabled

### ISSUE THREAD

**Issue by rex4539** [PurpleI2P/i2pd#1363]
[i2pd_2019-06-08-084007_MacBook-Pro-2011.log](https://github.com/PurpleI2P/i2pd/files/3268230/i2pd_2019-06-08-084007_MacBook-Pro-2011.log)

**Comment by orignal** [comment]
how about 2.25?

**Comment by rex4539** [comment]
All previous builds are running fine.

This is a regression.

**Comment by orignal** [comment]
do you happen to use ipv6=true ?

**Comment by rex4539** [comment]
You are right. This causes the crash in 2.26.0

I tried disabling `ipv6=true` and it's not crashing.

Enabling it back, causes immediate crash.
