### ISSUE TITLE
high CPU usage

### ISSUE THREAD

**Issue by tomfun** [PurpleI2P/i2pd#1364]
I use docker. I see 100% load for one core for the last month. And I have PC with old build wich shows me low CPU usage. Old PC has an old CPU, and docker image was built directly without hub.docker.com, if matters.
I see no relation with the traffic speed, so i2pd can use 1 CPU core for 8 KiB/s, and for 140 KiB/s.

**Comment by r4sas** [comment]
Can you check descriptors amount?

**Comment by tomfun** [comment]
How to do it?

**Comment by tomfun** [comment]
```bash
docker-compose exec i2pd sh -c "ulimit -n"
# 1048576
```

**Comment by orignal** [comment]
please disable ntcp first, ntcp=false in config file

**Comment by tomfun** [comment]
Done. Now CPU is ok, but also instead of 300 (KiB/s) now I have 30 :(

**Comment by orignal** [comment]
make sure  ntcp2.enabled=true and ntcp2.published=true.

**Comment by tomfun** [comment]
ntcp2 is ok. but speed is really bad
anyway, thanks, the problem with CPU solved ;)
