### ISSUE TITLE
disrupt correlation of subsequent TCP communications?

### ISSUE THREAD

**Issue by benediamond** [PurpleI2P/i2pd#1370]
i2pd is good at breaking the association between an endpoint / destination and the IP address of the router.

But can you disrupt correlation of a sender's _own_ identity across subsequent TCP communications? In other words, I am interested in eliminating all persistent / linkable identity across the successive communications of some particular party.

[Docs » User Guide » I2P tunnels configuration](https://i2pd.readthedocs.io/en/stable/user-guide/tunnels/) says:

> If _keys_ is empty, transient keys will be created on every restart. If keys file is not found, new keys will be created and stored into specified file. Client tunnels might share same local destination, if keys file contains same identity.

Yet this requires a restart. Is it possible to replace / regenerate the `.dat` file and disrupt the sender's identity, but without restarting / recreating tunnels?

Thank you.

**Comment by orignal** [comment]
if you specify keys=transient, new one should be regenerated by kill -s HUP <pid>, but  it doesn't work well. Need to take a look and fix.

**Comment by benediamond** [comment]
interesting, so something like `kill -s HUP $(pidof i2pd)`?

will this re-generate _all_ transient keys? or is there a way to specify particular ones...?

let me know what you find. thanks again.

**Comment by orignal** [comment]
Basically kill -s HUP is supposed to reload all configs, including regeneration of transient and shared local destination. I can try to implement it individually from the web interface

**Comment by benediamond** [comment]
simpler question: is the client / http proxy tunnel `xxx.b32.i2p` even visible to the server? if not, then this is not an issue. right?

**Comment by orignal** [comment]
Yes, it does. Otherwise it would not know where to send responses to.

**Comment by benediamond** [comment]
i see, thanks.

what about the address of the native HTTP proxy tunnel? can _its_ `.dat` file be set as `transient` + reset?

**Comment by orignal** [comment]
Yes, httpproxy.keys in i2pd.conf can be set to transient. And it's transient by default

**Comment by benediamond** [comment]
excellent, thank you.

so a secure solution would be simply to execute `kill -s HUP $(pidof i2pd)` between all successive HTTP queries? meanwhile, persistent tunnels can be created by explicitly specifying a non-transient keys file.

this seems like a suitable solution for now...

**Comment by benediamond** [comment]
another thing, sorry. I noticed that after executing `kill -s HUP $(pidof i2pd)` on the client, not only does the HTTP tunnel identifier of the client change, but also the IP address _which the server sees_ also changes, and there is some downtime, during which the request fails.

does this mean that new tunnels are being created, as opposed to simply the identifier changing...?

**Comment by orignal** [comment]
"IP address which server sees" is 127.x.x.x where x.x.x are first 3 bytes of I2P address ident hash. You can disable it by enableuniquelocal=false in server tunnel's config

**Comment by benediamond** [comment]
ok, but are you saying---these x.x.x. are generated deterministically from the client's http proxy tunnel id? (so they do not reveal any more information than the tunnel id itself?)

do you know what accounts for the downtime (about 10 seconds) after executing `kill -s HUP $(pidof i2pd)` on the client?

**Comment by benediamond** [comment]
yes, I see.

Is there a secure way to unlink / dissociate the identity of the client _without_ recreating the tunnel? Perhaps just by "renaming" the client tunnel address, but still maintaining the tunnel. does this make sense? thanks.

**Comment by orignal** [comment]
Let me think if it possible to reuse existing tunnel with new address.

**Comment by majestrate** [comment]
i don't think it is possible to reuse tunnels as long as elgamal is in use on the garlics

**Comment by orignal** [comment]
It's possible, you just send your new LeaseSet, but useless because server can link old and new addresses easily

**Comment by benediamond** [comment]
How would this linking be done?

As an alternative measure: would it be possible to continually create new http tunnels in the background, which can be dicarded after one use? (I won't do this on the I2P "mainnet", only in private testnets.)

**Comment by benediamond** [comment]
A naive way to amortize would be to create _many_ new http proxy tunnels upon each kill -s HUP (is this even possible?), so that restarting would be only necessary once every N communications, instead of every 1.

Either way, it'd be nice to think about the "best" way to do this. If it requires writing new code I'll be happy to contribute.

**Comment by orignal** [comment]
What are you trying to achieve? Unique address per every HTTP request?

**Comment by benediamond** [comment]
Essentially, yes.

Imagine a blockchain setting where transactions are broadcast to peers. I want to prevent these peers from correlating two subsequent transactions---i.e. being able to discern that they came from the same party.

**Comment by benediamond** [comment]
This can be an important security property, under certain threat models

**Comment by benediamond** [comment]
@orignal bumping this---is there no better way than recreating tunnels? i'd just like confirmation. thanks for your time.

**Comment by benediamond** [comment]
> What are you trying to achieve? Unique address per every HTTP request?

so specifically, these would be TCP requests, as in https://golang.org/pkg/net/#Dial. each node should set up a [generic `server` tunnel](https://i2pd.readthedocs.io/en/latest/user-guide/tunnels/#servergeneric-tunnels) to accept incoming TCP requests, I presume.

Now: the sending nodes should be able to contact this TCP endpoint using a "fresh" address for each communication. So actually, each client should create a separate TCP [`client` tunnel](https://i2pd.readthedocs.io/en/latest/user-guide/tunnels/#client-tunnels) pointing to _each_ of the other peers. _Each_ of these tunnels will only be used once, and so all will have to be re-created after each transmission.

Perhaps it would be easier to use an `httpproxy` tunnel, which does _not_ have a fixed `destination` address, and can be used to communicate with arbitrary endpoints. Thus there will be one tunnel destruction + creation after each broadcast, as opposed to [number of peers].

Either way, it appears that tunnel destruction + recreation is the only real way to go here---correct me if I'm wrong.

**Comment by l-n-s** [comment]
Right, you must create a new transient destination for each connection. You can create new tunnel keys, but better just use the SAM API.

**Comment by benediamond** [comment]
@l-n-s thank you for this.

Yes, SAM appears to be the best way to create new identities---though connecting still takes about 20 seconds per identity, in my experiments (e.g. using [leaflet](https://github.com/MuxZeroNet/leaflet)).

What about [Non-Repliable Datagrams](https://geti2p.net/spec/datagrams#raw)? Could a malicious server correlate two of these (i.e., determine that they came from the same client)? Thanks.
