### ISSUE TITLE
Is both i2pd.conf and command line prameters can contain the dot(.)?

### ISSUE THREAD

**Issue by zatakedux** [PurpleI2P/i2pd#1371]
The [documentation](https://i2pd.readthedocs.io/en/latest/user-guide/configuration/) say:
>  All command-line parameters are allowed as keys, but for those which contains dot (.), there is a special syntax.

The real just I can use things in i2pd.conf similar to "httpproxy.enabled=0" and "--httpproxy.enabled=0" in command line parameter. 
Is the documentation obsoleted?
I'm running i2pd 2.26.0

**Comment by r4sas** [comment]
I think here was meaning about i2cp variables which can be provided to httpproxy and socksproxy config blocks.
