### ISSUE TITLE
i2pd 2.26.0 ignore the i2cp options in i2pd.conf?

### ISSUE THREAD

**Issue by zatakedux** [PurpleI2P/i2pd#1372]
The httpproxy just ignore my i2cp options in i2pd.conf and take the default 3 hops.
The httpproxy type i2pc options in tunnels.conf is work as expected.
> floodfill=0
> bandwidth=X
> 
> [socksproxy]
> enabled=0
> 
> [sam]
> enabled=1
> 
> [httpproxy]
> inbound.length=1
> outbound.length=1
> inbound.quantity=16
> outbound.quantity=16
> port=4444
> 
> [exploratory]
> inbound.length=1
> outbound.length=1
> inbound.quantity=16
> outbound.quantity=16

**Comment by r4sas** [comment]
Any logs?

**Comment by zatakedux** [comment]
> Any logs?
I'm sorry for no log due too long and maybe danger for me.(however I'll reconsider the danger if fix this problem is need one log)
I find out this problem by in http://localhost:7070/?page=i2p_tunnels click the "HTTP proxy" then see the "Inbound tunnels" and the "Outbound tunnels"

**Comment by orignal** [comment]
because you have missed keys parameter, add keys=transient and it will work

**Comment by zatakedux** [comment]
@orignal 
> because you have missed keys parameter, add keys=transient and it will work
thank for the workaround.
Just a report: However the tunnels.conf don't require "keys=transient" and work as well.

**Comment by orignal** [comment]
Because they are transient by default there while proxy uses share local destination
