### ISSUE TITLE
Is inbound.quantity greater than 16 have real effect in i2pd?

### ISSUE THREAD

**Issue by zatakedux** [PurpleI2P/i2pd#1373]
The [java i2p documentation](https://geti2p.net/en/docs/protocol/i2cp) say the limit of `inbound.quantity` is 1 to 16

**Comment by orignal** [comment]
It can't be published for sure. If we don't check yet, I will add.

**Comment by zatakedux** [comment]
> It can't be published for sure. If we don't check yet, I will add.
What do "I will add" meaing? if greater than 16 quantity is work in i2pd why limit it in i2pd as java i2p?

**Comment by orignal** [comment]
It's limited by protocol
