### ISSUE TITLE
Implement stream isolation

### ISSUE THREAD

**Issue by za3ter2p** [PurpleI2P/i2pd#1376]
This issue is effecting I2Pd so as I2P-Java which is give critical attack issue on fingerprinting and identity  correlation attack. 

I2P-Java responded as wont fix this issue: 

https://trac.i2p2.de/ticket/1149

Side Note: Tor with TBB solved this issue completely since ages: 

https://trac.torproject.org/projects/tor/ticket/1865

**Comment by orignal** [comment]
i2pd runs each destination  in separate thread. Beside this I don't understand what you are asking abotu

**Comment by l-n-s** [comment]
You can implement your own Socks proxy with isolated streams. 

Use [SAM API](https://geti2p.net/en/docs/api/samv3), and for each Socks client connection you can create a new I2P destination.
