### ISSUE TITLE
Embeddable/library version

### ISSUE THREAD

**Issue by SoniEx2** [PurpleI2P/i2pd#1378]
It'd be nice to just be able to embed i2p into an IRC client or something to provide avatars without leaking IPs on either side, but it seems i2pd cannot be used as a library?

a library would provide an i2p node and APIs to interact with i2p, create an endpoint/address(?), etc so the IRC client can host its own avatar.

**Comment by orignal** [comment]
i2pd can be used as library, libi2pd and libi2pd_client

**Comment by SoniEx2** [comment]
and where's that documented? the docs only seem to mention the standalone version.

**Comment by orignal** [comment]
No, it's not documented. Look at api.h/.cpp to initialize it and use i2pd's internals by youself
