### ISSUE TITLE
[libi2pd] dangerois warning: possibly uninitialized value

### ISSUE THREAD

**Issue by nonlinear-chaos-order-etc-etal** [PurpleI2P/i2pd#1380]
See screenshot below:

![image](https://user-images.githubusercontent.com/19966907/60390020-c8571900-9aff-11e9-8910-978cccc6550d.png)

**Comment by nonlinear-chaos** [comment]
x пишет: варнинг потому что gcc version 9.1.0

**Comment by r4sas** [comment]
@orignal говорит что ничего серьезного.
