### ISSUE TITLE
i2pd_qt various errata+crash

### ISSUE THREAD

**Issue by nonlinear-chaos-order-etc-etal** [PurpleI2P/i2pd#1383]
Nokia808 commented on 5 Apr https://github.com/PurpleI2P/i2pd/issues/1317#issuecomment-480289587 :

«I tried to modify already created by me new tunnel to be SMTP. Then I added new tunnel to be POP3 but in the meddle of it's setting application crashed !!

I relaunch application again & found that ALL NEW TUNNEL ARE DELETED !! Then I received system error that an error occurred !

I restart application then quit it then relaunch it after 3 minutes, then add only one new tunnel to be SMTP & after finishing this I quit application then wait 3 minutes then relaunch it again BUT NEW TUNNEL WAS DELETED !! Only default tunnel is existing !! Please your help ! Does this need me to open bug report?»

**Comment by nonlinear-chaos-order-etc** [comment]
Разбор полётов.

BUG1: «1. created new tunnel (non-smtp). 2. Modified it to be SMTP. 3. Added new tunnel as POP3 but in the middle of setting the tunnel the app crashed.»

inplace editor

**Comment by nonlinear-chaos-order-etc** [comment]
Some of the described crashes might be because of #1387 .

**Comment by nonlinear-chaos-order-etc** [comment]
Often crashes when entering key filename or http server tunnel port/inport

**Comment by nonlinear-chaos-order-etc-etal** [comment]
Seems to be a dup of #1580
