### ISSUE TITLE
GUI has no "About" section to verify version number !

### ISSUE THREAD

**Issue by Nokia808** [PurpleI2P/i2pd#1385]
Hi. Currently, GUI has no "About" section from which user can verify (read) version number of application. This is needed in certain cases like this:

https://github.com/flathub/website.i2pd.i2pd/issues/5

Yes, user can use command line options, like "flatpak list" to know version number, but as long as application already has GUI, it will be more elegant to have "About" section .......

**Comment by r4sas** [comment]
You can see version if open 7070 on page title.

**Comment by Nokia808** [comment]
@r4sas 
You mean:
127.0.0.1:0707 
in address bar of browser ? I tried it on Firefox which not configured to use i2pd while i2pd was not running & it show me nothing apart from white empty page & Firefox in "connecting ........" infinite state !
Please explain more !

Any how, it is not brilliant way, & it is better to add "About" section.

**Comment by nonlinear-chaos** [comment]
@Nokia808 I agree about About section. I think about resuming the GUI development, and About should be added.

**Comment by r4sas** [comment]
@Nokia808 
127.0.0.1:7070, not 0707.
