### ISSUE TITLE
Segfault in UPnP::Stop()

### ISSUE THREAD

**Issue by nonlinear-chaos-order-etc** [PurpleI2P/i2pd#1387]
> Stopping the daemon...
> Segmentation fault (core dumped)

**Comment by nonlinear-chaos** [comment]
```
git log|head
commit a090114066e94a3686f465ad94b89928315f7f56
Author: orignal <i2porignal@yandex.ru>
Date:   Wed Jul 10 13:31:49 2019 -0400

    send data message wih raw type fpr raw datagrams
```

**Comment by nonlinear-chaos** [comment]
```
Quit pressed. Hiding the main window
Closing and waiting for daemon worker thread...
Waiting for daemon worker thread finished.
Stopping the daemon...

[1]+  Segmentation fault      (core dumped) ./i2pd_qt  (wd: ~/git/i2pd_qt_git/i2pd/qt/i2pd_qt)
```

**Comment by nonlinear-chaos-order-etc** [comment]
stack trace: see scr shot:

![изображение](https://user-images.githubusercontent.com/19966907/63753664-190fa600-c8e6-11e9-8c82-4dfdd15083b8.png)

**Comment by nonlinear-chaos-order-etc** [comment]
url - see scr shot:

![изображение](https://user-images.githubusercontent.com/19966907/63754003-b7037080-c8e6-11e9-8fd4-fa33dbb58d9d.png)

**Comment by nonlinear-chaos-order-etc** [comment]
@orignal кто там upnp прогал? пусть займётся чтоль

**Comment by nonlinear-chaos-order-etc** [comment]
@r4sas @l-n-s Уберите метку QT, это чисто проблемы с UPnP в ядре i2pd.

**Comment by r4sas** [comment]
> кто там upnp прогал? пусть займётся чтоль

Его добавляли еще в 2014-м, портировав код откуда-то.
Я тебе ранее говорил уже, протестируй коммиты с UPnP из ветки transports_and_ri.

**Comment by nonlinear-chaos-order-etc** [comment]
```
<cryptoroom> orignal, кто upnp писал?
<cryptoroom> в нём креш
<orignal> мех скопировал из гвк
<cryptoroom> в upnp устойчивый креш
<cryptoroom> сука
<cryptoroom> придётся разбираться
<orignal> так почини если устройчивый
<cryptoroom> ну вот придётся
<cryptoroom> ок всё вопросов не имею
<cryptoroom> или ты почини
<cryptoroom> я сперва кутешные баги
```

@r4sas я опять кладу upnp в долгий ящик - или пусть ктото починит - я сперва с куте поразбираюсь.
