### ISSUE TITLE
bug?? in v2.26.0-1bionic1 — IRC connections stop working

### ISSUE THREAD

**Issue by nonlinear-chaos-order-etc** [PurpleI2P/i2pd#1390]
R4SAS-hex> а ты корку пишешь?

R4SAS-hex> если именно падает

user> R4SAS-hex: он не падает. Просто коннекции перестают данные гонять - стоят

**Comment by l-n-s** [comment]
Файловые дескрипторы сожрало?

**Comment by nonlinear-chaos-order-etc** [comment]
Закроем, я полагаю.

**Comment by nonlinear-chaos-order-etc** [comment]
Просто ничё не понятно.

**Comment by orignal** [comment]
Напиши перед запуском ulimit -n 4096 и будет тебе счастье
