### ISSUE TITLE
command in sbin has manpage in incorrect section

### ISSUE THREAD

**Issue by yangfl** [PurpleI2P/i2pd#1391]
https://github.com/PurpleI2P/i2pd/blob/97d9795fc9a2c672e2e97a31b3da9141364f1814/debian/i2pd.1#L1

lintian suggestes [`command-in-sbin-has-manpage-in-incorrect-section`](https://lintian.debian.org/reports/tags/command-in-sbin-has-manpage-in-incorrect-section.html), which is described 

> The command in `/sbin` or `/usr/sbin` are system administration commands; their manpages thus belong in section 8, not section 1".

Since i2pd can be theoretically run as a normal user by picking a non-privileged port and working dir,

https://github.com/PurpleI2P/i2pd/blob/97d9795fc9a2c672e2e97a31b3da9141364f1814/debian/i2pd.install#L1

maybe we should make i2pd install to `/usr/bin`.

**Comment by l-n-s** [comment]
Our Debian package is designed to be used as a system daemon, so in my opinion, sbin is the right choice

**Comment by janicez** [comment]
i2pd.1/8 is meant to be in section 1m on illumos or Solaris (the former of which i2pd does not presently compile on; latter unverified).
