### ISSUE TITLE
my plans - qt, android

### ISSUE THREAD

**Issue by nonlinear-chaos-order-etc** [PurpleI2P/i2pd#1397]
сперва доделаю i2pd_qt и i2pd_android — в андр недавно возникло желание залезть в консоль и2пд и глянуть, а ском жаловался что молния для этого не пашет — хз чо у скома с ней было.

**Comment by nonlinear-chaos-order-etc** [comment]
и неплохо бы внедряемый движок оберонскрипта, но это на будущее…

**Comment by nonlinear-chaos-order-etc** [comment]
а нахрен. не буду qt + i2pd_android делать

пусть донатят

тогда посмотрим

**Comment by l-n-s** [comment]
биполярочка intensifies
![243](https://user-images.githubusercontent.com/13422305/62365267-aa5f4880-b4f1-11e9-82c0-76fe972f53cf.jpeg)
