### ISSUE TITLE
Deprecate and Replace Old Vulnerable Encryption

### ISSUE THREAD

**Issue by TNTBOMBOM** [PurpleI2P/i2pd#1401]
Tunnels uses weak encryption , almost all of them having issues: 

- DSA-SHA1 = Weak and broken
Refs: https://en.wikipedia.org/wiki/SHA-1#Attacks
- ECDSA = broken against quantum computers:
Refs:Page 2 (check the table): https://csrc.nist.gov/csrc/media/publications/nistir/8105/final/documents/nistir_8105_draft.pdf  , https://en.wikipedia.org/wiki/Elliptic_Curve_Digital_Signature_Algorithm#Security
- RedDSA: has as well known attacks, zzz had a proposal to replace it: 
https://geti2p.net/spec/proposals/148-eddsa-blake2b-ed25519

Its preferable to just remove the old insecure tunnels Encryption. And keeps the only strongest one.

**Comment by orignal** [comment]
Trolling
