### ISSUE TITLE
about sam stream forward Features

### ISSUE THREAD

**Issue by tadli** [PurpleI2P/i2pd#1402]
i2pd seems that  sam stream forward  feature is not implemented. 
I tried to add this feature, but it is a bit difficult. Can someone help me?
sam.cpp
void SAMSocket::ProcessStreamForward (char * buf, size_t len)
	{
		LogPrint (eLogDebug, "SAM: stream Forward: ", buf);
		std::map<std::string, std::string> params;
		ExtractParams (buf, params);
		std::string& id = params[SAM_PARAM_ID];
		std::string& silent = params[SAM_PARAM_SILENT];
		if (silent == SAM_VALUE_TRUE) m_IsSilent = true;
		m_ID = id;
		auto session = m_Owner.FindSession (id);
		if (session)
		{
			m_SocketType = eSAMSocketTypeAcceptor;
			if (!session->localDestination->IsAcceptingStreams ())
			{
				m_IsForwarding = true;	
				session->localDestination->AcceptOnce (std::bind (&SAMSocket::HandleI2PForward, shared_from_this (), std::placeholders::_1));
			}
			SendMessageReply (SAM_STREAM_STATUS_OK, strlen(SAM_STREAM_STATUS_OK), false);
		}
		else
			SendMessageReply (SAM_STREAM_STATUS_INVALID_ID, strlen(SAM_STREAM_STATUS_INVALID_ID), true);
	}

**Comment by orignal** [comment]
No, it's not implemented yet
