### ISSUE TITLE
segfault in TCPIPAcceptor::Stop

### ISSUE THREAD

**Issue by nonlin-lin-chaos-order-etc-etal** [PurpleI2P/i2pd#1411]
screenshot stack trace:

![изображение](https://user-images.githubusercontent.com/19966907/63762512-78c17d80-c8f5-11e9-9b94-ddb6da9d153a.png)

**Comment by nonlinear-chaos-order-etc** [comment]
more details on stack calls (img):

![изображение](https://user-images.githubusercontent.com/19966907/63762771-f71e1f80-c8f5-11e9-93a7-6f630fb8b46a.png)

**Comment by nonlinear-chaos-order-etc** [comment]
```
 и в tcpip acceptor креш
 i2psevice.cpp
<orignal> этот i2pservice поделие одного шведа
<orignal> давно хочу выпилить
```

**Comment by r4sas** [comment]
Nobody reported same issue, closing as old.
