### ISSUE TITLE
[Qt-GUI] Install guide - fails (1 fix)

### ISSUE THREAD

**Issue by imstanz** [PurpleI2P/i2pd#1422]
Hello - I'm hoping to have a GUI for my i2pd install.
Following [instructs](https://i2pd.readthedocs.io/en/latest/devs/building/qt-desktop-gui/) fail, and hoped to find a fix here!

**Qt Desktop GUI build instructions...**
Section:  _Under Ubuntu_ -> Without Qt Creator_
Errors on: `make USE_UPNP=yes`

> ../../libi2pd/Gzip.h:4:10: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
compilation terminated.
make: *** [Makefile:1054: DaemonQT.o] Error 1

Debian Pkg of interest: `zlib1g-dev:amd64 (1:1.2.11.dfsg-1)`

FIX: `~$ sudo apt install zlib1g-dev` ...also, no reboot needed.
Re-run: `make USE_UPNP=yes` ..and go bake a cake!

**Flatpak install method::**
`$ flatpak --user install org.kde.Sdk/x86_64/5.11`
`Looking for matches…`
`error: No remote refs found similar to ‘org.kde.Sdk/x86_64/5.11’`

Same result for: [kde org_howtos](https://community.kde.org/Guidelines_and_HOWTOs/Flatpak)

`$ flatpak install flathub org.kde.Sdk//5.12`
`Looking for matches…`
`error: No remote refs found similar to ‘flathub’`

I never used flatpak or use kde.
I'm using Linux 64 Debian10, openbox

**Comment by l-n-s** [comment]
Flatpak install commands:

    flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    flatpak install flathub website.i2pd.i2pd

**Comment by nonlinear-chaos-order-etc** [comment]
@l-n-s если ты ещё не исправил доки то я щас сделаю

**Comment by nonlinear-chaos-order-etc** [comment]
@imstanz You took *build* instructions. To *install*, you need to only do two lines that @l-n-s suggested - it should take the binaries from the flatpak repo.

**Comment by nonlinear-chaos-order-etc** [comment]
@l-n-s забирай! https://github.com/PurpleI2P/i2pd_docs_en/pulls

**Comment by nonlinear-chaos-order-etc** [comment]
@imstanz Fixes were merged into docs at https://i2pd.readthedocs.io/en/latest/devs/building/qt-desktop-gui/ and https://i2pd.readthedocs.io/en/latest/user-guide/install/#gui-application

I think it should be OK to close the issue, please do if it's resolved

**Comment by nonlinear-chaos-order-etc** [comment]
See also: #1423

**Comment by imstanz** [comment]
Ok, thanks.
`@imstanz You took developer build instructions...`
am I gonna be sick? :)  Lol, sorry - I had to laugh at myself!

This will give users a gui?

For my notes:
Require sudo for pkg install.
> $ flatpak install flathub website.i2pd.i2pd
Looking for matches…
Required runtime for website.i2pd.i2pd/x86_64/stable (runtime/org.kde.Platform/x86_64/5.12) found in remote flathub
Do you want to install it? [Y/n]:

>`website.i2pd.i2pd permissions:`
   ` ipc       network              wayland              x11`
    `dri       file access [1]      dbus access [2]`
   ` [1] xdg-config/kdeglobals:ro, xdg-run/dconf, ~/.config/dconf:ro`
   ` [2] com.canonical.AppMenu.Registrar`

>`        ID                                                   Arch   Branch Remote  Download`
`1.     org.kde.Platform                      x86_64 5.12   flathub < 429.8 MB`
`2.     org.freedesktop.Platform.html5-codecs x86_64 18.08  flathub   < 3.3 MB`
`3.     org.kde.KStyle.Adwaita                x86_64 5.12   flathub   < 5.6 MB`
`4.     org.kde.Platform.Locale               x86_64 5.12   flathub < 334.1 MB (partial)`
`5.     website.i2pd.i2pd                     x86_64 stable flathub  < 20.8 MB`
`Proceed with these changes to the Default system installation? [Y/n]:`

>`1. [✓] org.kde.Platform                        x86_64   5.12    flathub  414.5 MB / 429.8 MB`
 `2. [✓] org.freedesktop.Platform.html5-codecs   x86_64   18.08   flathub    3.2 MB / 3.3 MB`
 `3. [✓] org.kde.KStyle.Adwaita                  x86_64   5.12    flathub    5.6 MB / 5.6 MB`
 `4. [✓] org.kde.Platform.Locale                 x86_64   5.12    flathub  179.2 MB / 334.1 MB`
 `5. [✓] website.i2pd.i2pd                       x86_64   stable  flathub   21.4 MB / 20.8 MB`
`Installation complete.`

**Comment by imstanz** [comment]
Are these steps to "get the gui installed" or to "prepare the system, to then - get the gui?

**Comment by nonlinear-chaos-order-etc** [comment]
@l-n-s Please answer to @imstanz

**Comment by l-n-s** [comment]
You don't have to build it yourself, installing from Flathub (as I mentioned in the first comment) is the best choice for you.

**Comment by l-n-s** [comment]
@imstanz After it's installed, i2pd should appear in you applications menu. If it doesn't, you can run i2pd GUI via command line 

    flatpak run website.i2pd.i2pd
