### ISSUE TITLE
[SAM] i2pd crashes when incorrect string passed to name lookup request

### ISSUE THREAD

**Issue by Nyanraltotlapun** [PurpleI2P/i2pd#1424]
**Setup**
System : FreeBSD 12.0
i2pd ver : 2.26.0

**To reproduce**
1. Init sam connection.
2. Send name lookup request : `"NAMING LOOKUP NAME=http://zmw2cyw2vj7f6obx3msmdvdepdhnw2ctc4okza2zjxlukkdfckhq.b32.i2p\n"`

After this i2pd daemon crashes with no explicit message in log.

**Comment by orignal** [comment]
Better to say "incorrect address ending with .b32.i2p"

**Comment by Nyanraltotlapun** [comment]
It is work fine with ".b32.i2p" ending. On i2pd and on java i2p...
Actually, it seams that at java realization it works only with .b32.i2p ending...
And ordinary address in the form "i2p-javadocs.i2p". But "http://i2p-javadocs.i2p" - give (KEY_NOT_FOUND)
