### ISSUE TITLE
Ability to restart tunnels that have transient keys

### ISSUE THREAD

**Issue by gh338** [PurpleI2P/i2pd#1425]
Would be nice to be able to trigger a tunnel restart via api/cli.

**Comment by orignal** [comment]
kill -s HUP

**Comment by gh338** [comment]
i2pd crashes regularly with this ... sometimes immediately but most of the time at the 2nd attempt or later.
I can post debug logs, but I am not sure exactly how or what to debug.

**Comment by orignal** [comment]
Yes, it must be fixed.
