### ISSUE TITLE
Make logclftime = true  by default

### ISSUE THREAD

**Issue by LLE8** [PurpleI2P/i2pd#1426]
because uptime can reach many days
2.27 uptime 74 days

**Comment by LLE8** [comment]
Не добавите ли в ближайший релиз?

**Comment by r4sas** [comment]
Вроде как @orignal высказывался против этого (не помню где именно).

**Comment by orignal** [comment]
слишком сильно будет лог засоряться

**Comment by r4sas** [comment]
В случае с длительным выполнением программы лучше использовать logrotate настроенным окончанием имени файла.
