### ISSUE TITLE
SSU connects to localhost

### ISSUE THREAD

**Issue by chisa0a** [PurpleI2P/i2pd#1427]
Shortly after startup, and for the rest of router uptime, SSU attempts to establish connections to localhost.

```
XX:XX:XX@358/warn - SSU: session with 0.0.0.0:0 was not established after 5 seconds
```

Without digging too deeply into the code, this might be from remote RouterInfos reporting their address as `0.0.0.0:0`. Possibly related to #1346

**Comment by r4sas** [comment]
duplicate of #1346 #1349
