### ISSUE TITLE
Manual saving to flash

### ISSUE THREAD

**Issue by uis246** [PurpleI2P/i2pd#1428]

**Comment by r4sas** [comment]
Saving what?

**Comment by r4sas** [comment]
Please clearify your issue and reopen.

**Comment by uis246** [comment]
Peer profiles

**Comment by LLE8** [comment]
Может быть NetDB? И какие устройства вы имеете в виду?

**Comment by r4sas** [comment]
Если разговор именно о Peer Profiles, то оно уже есть:
https://github.com/PurpleI2P/i2pd/blob/569088eaca25e63ac9c396df6b8c0451f5201a8f/libi2pd/Config.cpp#L257
