### ISSUE TITLE
Windows XP

### ISSUE THREAD

**Issue by hufGwbykIB5MsVXjEU3PNTR46zD1iF9ApLQgCH** [PurpleI2P/i2pd#1429]
The program cannot start in Windows XP in all versions after 2.24.0 . Is it possible to compile the new versions for Windows XP? I realise that this is "ancient" operation system, but no problem to run the i2pd router up to 2.24.0 ( released in Mar 2019 ), that is why I think that it probably not a huge problem to compile newer versions for XP. Please, remember , that compatibility with Windows XP probably give the compatibility with free and opensource ReactOS... Thanks in advance.

**Comment by r4sas** [comment]
Please provide logs and details about error, otherwise - no.

**Comment by hufGwbykIB5MsVXjEU3PNTR46zD1iF9ApLQgCH** [comment]
The error in Windows XP is very simple: "The procedure entry point GetTickCount64 could not be located in the dynamic link library KERNEL32.dll" 
No such error in versions up to 2.24.0
I read about this error - it means incompatibility with Windows XP, however, there are some possibilities to compile for Windows XP (for example, I read about it here https://stackoverflow.com/questions/17842981/the-procedure-entry-point-gettickcount64-could-not-be-located-in-the-dynamic-l    https://stackoverflow.com/questions/13130713/how-to-compile-for-win-xp-with-visual-studio-2012   https://stackoverflow.com/questions/54039545/windows-xp-entry-point-gettickcount64-could-not-be-located-kernel32-dll  ) But I cannot do it by myself.

**Comment by orignal** [comment]
That's about monotonic timer I guess

**Comment by r4sas** [comment]
Issue is not solved, looks like problem in GetTickCount:
https://github.com/PurpleI2P/i2pd/blob/569088eaca25e63ac9c396df6b8c0451f5201a8f/Win32/Win32App.cpp#L164
https://github.com/PurpleI2P/i2pd/blob/569088eaca25e63ac9c396df6b8c0451f5201a8f/Win32/Win32App.cpp#L242

Testing possible solution now.

**Comment by hufGwbykIB5MsVXjEU3PNTR46zD1iF9ApLQgCH** [comment]
Sorry, but I have to confirm that program still do not work in Windows XP - still the same error. Also I want to ask all developers not to make worse for other win32 operating systems (Windows 7, Windows 10). Please, make the separate file for Windows XP (as in the version 2.23.0 you have the separate file i2pd_2.23.0_win32_winxp_mingw.zip for Windows XP users). It is better not to disable useful features (such as monotonic timer) in operating systems, which can support these features - so it is rather better to make separate compiling for Windows XP users. Thanks in advance

**Comment by r4sas** [comment]
Here problem that MSYS2 MinGW libraries has in import GetTickCount64. That causes that this function always imported  from kernel32.dll.
So I think removing code or trying redefine functions doesnt solve problem...

**Comment by r4sas** [comment]
https://github.com/msys2/MSYS2-packages/issues/1784

**Comment by r4sas** [comment]
https://github.com/msys2/MSYS2-packages/issues/1784#issuecomment-553750725

**Comment by r4sas** [comment]
Created separate MSYS2 installation for building for WinXP with recompiled headers as said [here](https://github.com/msys2/MSYS2-packages/issues/1784#issuecomment-553871965).

Thanks @mati865 for that solution.

[i2pd_2.29.0-10-gdd94b77b_winxp_mingw.zip](https://github.com/PurpleI2P/i2pd/files/3863390/i2pd_2.29.0-10-gdd94b77b_winxp_mingw.zip)
(will add in release also)

**Comment by hufGwbykIB5MsVXjEU3PNTR46zD1iF9ApLQgCH** [comment]
Thank you! I'm not a programmer, but it seems to me that orignal disabled monotonic timer for all win32 operating systems. I'm not sure about it, but if it so, could you reenable monotonic timer for all win32 systems (Windows 7, Windows 10), except Windows XP?

**Comment by r4sas** [comment]
Monotonic timer works correctly on XP, so it can be fully used. @orignal already reverted that part of code.
