### ISSUE TITLE
general protection fault with create ppp sessions 

### ISSUE THREAD

**Issue by ne-vlezay80** [PurpleI2P/i2pd#1433]
The error:
 general protection fault ip:562c9f87a5dc sp:7fd130ff8b00 error:0 in i2pd[562c9f69a000+26c000]

Haw to play:
1. Create tunnel and start pppd into tunnel:
pppd noauth pty "nc 127.0.0.1 33100"
2. Remote
pppd noauth "nc -l 127.0.0.1 -p 65400" 10.7.1.1:10.7.1.2
3. Start iperf3 into ppp session.

I2pd crashed.

**Comment by r4sas** [comment]
Система? Откуда взят пакет? Возможность собрать/установить с дебажными символами и предоставить полный трейс?

**Comment by ne-vlezay80** [comment]
Arch Linux
Пакет был собран с: https://aur.archlinux.org/packages/i2pd-git/

**Comment by ne-vlezay80** [comment]
i2pd не падает, если указать mtu = 576 для ppp интерфейса

**Comment by r4sas** [comment]
У... Это видать где то с MTU кодом в util.cpp дело. А трейс получить не удастся?

**Comment by ne-vlezay80** [comment]
Я к i2pd подключился через gdb, он как ни странно не падает. Вчера упал с такой ошибкой.

**Comment by r4sas** [comment]
Бывает :D

**Comment by ne-vlezay80** [comment]
А может ли это быть аппаратная проблема?

**Comment by r4sas** [comment]
Интерфейс же виртуальный.

**Comment by r4sas** [comment]
@ne-vlezay80 в текущем релизе MTU был поднят до 1280/640 для ipv6/v4 соответственно.

Есть ли какие-либо изменения?

**Comment by r4sas** [comment]
t/o
