### ISSUE TITLE
i2pd package

### ISSUE THREAD

**Issue by noraj** [PurpleI2P/i2pd#1440]
1) i2pd package is now in Alpine Linux edge in testing repo: https://pkgs.alpinelinux.org/package/edge/testing/x86_64/i2pd

2) https://repology.org/project/i2pd/versions give the list of distro where i2pd is packaged

They give a badge:

[![Packaging status](https://repology.org/badge/vertical-allrepos/i2pd.svg)](https://repology.org/project/i2pd/versions)

It's maybe too verbose but more complete than:
![image](https://user-images.githubusercontent.com/16578570/69481781-90d16c00-0e14-11ea-83e1-603a34da740e.png)

**Comment by r4sas** [comment]
> 1. i2pd package is not in Alpine Linux edge in testing repo

huh? https://github.com/alpinelinux/aports/pull/11953

> They give a badge

Yeah, we know about it. But this badge is too big for README. Also that badge only shows where packages available, but our README section shows which systems are supported by us (where we can ourself build and test.
I think "Packaging status" badge ([![Packaging status](https://repology.org/badge/tiny-repos/i2pd.svg)](https://repology.org/project/i2pd/versions)) is enough for us...

**Comment by noraj** [comment]
@r4sas 
1. Sorry typo error: `-t +w`.
2. You're right.
3. I would just add Alpine to the list of supported systems.
4. ArchLinux, openSUSE, Gentoo, Debian, Ubuntu are maybe worth mentioning.
