### ISSUE TITLE
NTCP2 and hidden mode of a router

### ISSUE THREAD

**Issue by hufGwbykIB5MsVXjEU3PNTR46zD1iF9ApLQgCH** [PurpleI2P/i2pd#1444]
I've read the following: https://geti2p.net/en/blog/post/2018/08/20/NTCP2
<B>NTCP2 address can be declared as a separate NTCP2 address or as an old-style NTCP address with additional parameters, in which case it will accept both NTCP and NTCP2 connections. Java I2P implementation uses the second approach, i2pd (C++ implementation) uses the first.</B>

Is it true? So what about the situation when a person reside in a "bad country", where use of I2P is forbidden, and DPI is used by authorities to uncover such internet users. Is it possible to block NTCP and SSU in i2pd program and use only NTCP2 and hidden mode of a router in such country?

**Comment by hufGwbykIB5MsVXjEU3PNTR46zD1iF9ApLQgCH** [comment]
And my question is how it can be done in i2pd.conf file ?

**Comment by hufGwbykIB5MsVXjEU3PNTR46zD1iF9ApLQgCH** [comment]
And the second related question: is it possible to use 2 routers: one in a "bad" country and one in a "good", both in  hidden mode, the first accepts connections only to the second via NTCP2, the second can connect to all I2P network and make transient tunnels to the first?

**Comment by hufGwbykIB5MsVXjEU3PNTR46zD1iF9ApLQgCH** [comment]
Or, for example, it is possible to use some kind of "intermediate" router in "good" country, which in hidden mode accepts only connections to certain router in "bad" country and certain router in I2P network and makes transient tunnels between them. Is it possible?

**Comment by r4sas** [comment]
All that I can say is that intermediate router can't be in hidden mode, becuse in that case you will not be able connect to it.

**Comment by hufGwbykIB5MsVXjEU3PNTR46zD1iF9ApLQgCH** [comment]
Please explain. I've read here https://trac.i2p2.de/ticket/1314 that transient tunnels disabled in hidden mode. I'm not sure that I understand it correctly, also I'm not sure that it applies to i2pd (and not only to Java I2P). Please, make it clear for me. 
Also I want to understand, if it is possible to create some kind of analogue of Tor bridge in I2P - some kind of secret node (which is not published anywhere and which is known only by certain persons in "bad" country) with obfuscated traffic to it. How can it be done, using i2pd?

**Comment by hufGwbykIB5MsVXjEU3PNTR46zD1iF9ApLQgCH** [comment]
Please explain. I've read here https://trac.i2p2.de/ticket/1314 that transit tunnels disabled in hidden mode. I'm not sure that I understand it correctly, also I'm not sure that it applies to i2pd (and not only to Java I2P). Please, make it clear for me.
Also I want to understand, if it is possible to create some kind of analogue of Tor bridge in I2P - some kind of secret node (which is not published anywhere and which is known only by certain persons in "bad" country) with obfuscated traffic to it. How can it be done, using i2pd?

**Comment by tomfun** [comment]
> Is it possible to block NTCP and SSU in i2pd program and use only NTCP2

Yes, it is possible. See configuration docs for details.  
You can leave NTCP2 only enabled (and it is good to do).  

As I understand, there is a lot of old versions (maybe i2pd, not java) that are using NTCP1, and it is possible that you need some time (an hour or a days) to find node with NTCP2 support, I think, it is reason NTCP1 is enabled by default (and also it is backward compatible)

**Comment by orignal** [comment]
No, NTCP1 is disabled by default in last few versions

**Comment by tomfun** [comment]
> if it is possible to create some kind of analogue of Tor bridge in I2P - some kind of secret node
...
> with obfuscated traffic to it

Yes, it is possible: you can create AWS instance, set up a VPN server, take your phone, set up a VPN client, go to google chrome or android proxy settings and set your internal VPN i2pd IP address as an outgoing proxy. It is a specific example that is not related mainly to i2p itself but fits your needs: obfuscated encrypted (carried by VPN) traffic and secret node (made by the configuration of I2PD). Also can be in a "good" country (carried by AWS region).

**Comment by hufGwbykIB5MsVXjEU3PNTR46zD1iF9ApLQgCH** [comment]
I still do not understand why user in good country cannot create NTCP2 router in hidden mode, then give user in bad country his router.info file. Then user in bad country add this file to netDb folder and then specify this parameter in i2pd.conf:
--------------------------------------------
## Make direct I2P connections only to routers specified here. Comma separated list of base64 identiti
es.
routers = identifier of user in good country
----------------------------------------------
Why it cannot work to provide user in bad country access to i2p network? Maybe I do not understand some fundamental features of i2p network. Can anyone explain it to me? BTW, how to find out base64 identifier of my own router? As far as I understand base64 identifiers of other routers in netDB folder can be found just from the name of the respective file: routerInfo-base64identifier.dat

**Comment by hufGwbykIB5MsVXjEU3PNTR46zD1iF9ApLQgCH** [comment]
I still do not understand why user in good country cannot create NTCP2 router in hidden mode, then give user in bad country his router.info file. Then user in bad country add this file to netDb folder and then specify this parameter in i2pd.conf:

## Make direct I2P connections only to routers specified here. Comma separated list of base64 identiti
es.
routers = identifier of user in good country

Why it cannot work to provide user in bad country access to i2p network? Maybe I do not understand some fundamental features of i2p network. Can anyone explain it to me? BTW, how to find out base64 identifier of my own router? As far as I understand base64 identifiers of other routers in netDB folder can be found just from the name of the respective file: routerInfo-base64identifier.dat

**Comment by hufGwbykIB5MsVXjEU3PNTR46zD1iF9ApLQgCH** [comment]
I still do not understand why user in good country cannot create NTCP2 router in hidden mode, then give user in bad country his router.info file. Then user in bad country add this file to netDb folder and then specify this parameter in i2pd.conf:

 # Make direct I2P connections only to routers specified here. Comma separated list of base64 identities.
routers = identifier of user in good country

Why it cannot work to provide user in bad country access to i2p network? Maybe I do not understand some fundamental features of i2p network. Can anyone explain it to me? BTW, how to find out base64 identifier of my own router? As far as I understand base64 identifiers of other routers in netDB folder can be found just from the name of the respective file: routerInfo-base64identifier.dat

**Comment by hufGwbykIB5MsVXjEU3PNTR46zD1iF9ApLQgCH** [comment]
I still do not understand why user in good country cannot create NTCP2 router in hidden mode, then give user in bad country his router.info file. Then user in bad country add this file to netDb folder and then specify this parameter in i2pd.conf:

.... Make direct I2P connections only to routers specified here. Comma separated list of base64 identities.
routers = <i>identifier of user in good country</i>

Why it cannot work to provide user in bad country access to i2p network? Maybe I do not understand some fundamental features of i2p network. Can anyone explain it to me? BTW, how to find out base64 identifier of my own router? As far as I understand base64 identifiers of other routers in netDB folder can be found just from the name of the respective file: routerInfo-base64identifier.dat
