### ISSUE TITLE
i2pd_qt: Log pane is empty in Debug builds. (Log pane works okay in Release.)

### ISSUE THREAD

**Issue by nonlinear-chaos-order-etc-etal** [PurpleI2P/i2pd#1446]
Log pane is linked to [Log] button

**Comment by nonlinear-chaos-order-etc** [comment]
Вот пример сетапа:

скриншот - 
![изображение](https://user-images.githubusercontent.com/19966907/71421768-ffc20f00-26b7-11ea-9ed9-ee57578a1493.png)

при этом почему-то вывод идёт на stdout/stderr.

flatpak info website.i2pd.i2pd
Ref: app/website.i2pd.i2pd/x86_64/stable
ID: website.i2pd.i2pd
Arch: x86_64
Branch: stable
Origin: flathub
Collection ID: org.flathub.Stable
Date: 2019-08-28 09:31:58 +0000
Subject: Update to 2.28.0 (880bfbc9)
Commit: 114ec428fa4260b41b2c81da635391c9af511e5ea1a0194f863dc33b4ff791d2
Parent: ee3942d1499d5fb0b1048a3de2d427966f49eb00fd6cd81c37d8ae90373f6170
Location: /var/lib/flatpak/app/website.i2pd.i2pd/x86_64/stable/114ec428fa4260b41b2c81da635391c9af511e5ea1a0194f863dc33b4ff791d2
Installed size: 130,4 МБ
Runtime: org.kde.Platform/x86_64/5.12
Sdk: org.kde.Sdk/x86_64/5.12

**Comment by nonlinear-chaos-order-etc-etal** [comment]
same with this i2pd_qt version:

![изображение](https://user-images.githubusercontent.com/19966907/102552269-e2255b00-40fb-11eb-8111-98d3ccdc5c4c.png)

**Comment by nonlinear-chaos-order-etc-etal** [comment]
This is caused in Debug builds by this line in .pro file:

```
DEFINES += DEBUG_WITH_DEFAULT_LOGGING
```

**Comment by nonlinear-chaos-order-etc-etal** [comment]
It's all okay, no changes needed.
