### ISSUE TITLE
.deb files doesn't installs in AntiX Linux

### ISSUE THREAD

**Issue by DaniellMesquita** [PurpleI2P/i2pd#1447]

**Comment by r4sas** [comment]
They mustn't, just because your systems uses different ABI/packages versions/etc.

**Comment by DaniellMesquita** [comment]
AntiX is based on Debian, but doesn't uses systemd.

**Comment by r4sas** [comment]
Please provide full info, telepaths on vacation.

**Comment by r4sas** [comment]
t/o.
