### ISSUE TITLE
Доступ к сети i2p с другой машины

### ISSUE THREAD

**Issue by otakubeam** [PurpleI2P/i2pd#1452]
Есть один VPS с i2pd. Я хочу сделать так, чтобы я мог подключаться через него к сети с другого компьютера (желательно просто выбрав в настройках firefox http прокси с ip сервера и нужным портом).
Знаю, что можно поднять прокси через apache, но насколько там всё сложно?

--------------------
Это не напрямую связано с i2pd, но прошу помочь всё равно, ведь наверняка такой сетап довольно распространён.
Отвечу на любые вопросы. Если что система сервер Ubuntu 18.04.

**Comment by orignal** [comment]
параметр httpproxy.address в настройках.  Указывается адрес локального интрерфейса через который будет подключение, например httpproxy.address=192.168.0.1
По умолчанию там 127.0.0.1
Аналогичный параметр address есть у всех других тоннелей

**Comment by otakubeam** [comment]
Ок, я запустил с такими параметром --httpproxy.address [здесь то что мне показал 2ip.ru], в браузере выбрал http proxy: 84.38.181.49(адрес сервера) port 4444, но желаемого эффекта не последовало. Возможно мне нужно как-то в системе на сервере разрешить обращения из вне? Ещё у меня параметры --floodfill --bandwidth X, не думаю, что это влияет, но just in case

**Comment by orignal** [comment]
попробовать написать --httpproxy.address 0.0.0.0 для начала.
Если получится подключиться то посмотреть какой адрес интефрейса через ifconfig
Если не получится то разбираться почему, может файрволл где то.
Ну и разумеется прежде чем пробовать в браузере проверить доступность порат 4444 telnet-ом

**Comment by r4sas** [comment]
скорее всего еще порт надо открыть в ufw либо iptables.

**Comment by otakubeam** [comment]
--httpproxy.address 0.0.0.0 помог, с портом всё хорошо. Всем спасибо!

**Comment by orignal** [comment]
Надо будет разбираться почему с адресом интрефейса не работало

**Comment by egazeba** [comment]
```
[httpproxy]
address = 10.0.0.10
port = 4444
```
Всё работает

**Comment by r4sas** [comment]
> --httpproxy.address [здесь то что мне показал 2ip.ru], в браузере выбрал http proxy: 84.38.181.49(адрес сервера)

Как бы причина в том, что в `httpproxy.address` надо указывать не адрес клиента, а внешний белый IP адрес сервера, т.е. `84.38.181.49`.

**Comment by otakubeam** [comment]
Хмм, а что можно сделать, если в течение нескольких часов после запуска демона через прокси идёт подключение, а потом - бесконечная загрузка? Навреное, есть какой-то параметр session-timeout? Понятно только то, что ничего не понятно.

**Comment by orignal** [comment]
Сделать обновление страницы. Это известная проблема

**Comment by otakubeam** [comment]
Обновление страницы в браузере? Вроде бы это не помогает.

**Comment by otakubeam** [comment]
Поставил ulimit. Посмотрим, что получится

**Comment by r4sas** [comment]
> а потом - бесконечная загрузка

а к этому моменту i2pd сам по себе как работает? вебморда (7070) открывается? сколько процесс потребляет?

**Comment by otakubeam** [comment]
7070 открывается через текстовый браузер на сервере. К этому моменту роутер раскачегаривается и съедает всё процессорное время, но остальные тоже работают без особых тормозов (ssh, lynx, htop). Я пробовал опцию "decline transit tunnels", которая существенно снизила нагрузку на проц, но прокси от этого работать не перестал.
----
Ну, на самом деле, установка в системе лимита на открытие файлов командой 
`ulimit -n 4096`
вроде бы помогла. Ещё раз спасибо всем небезучастным

**Comment by otakubeam** [comment]
Через 2 дня всё-таки прокси отвалился =(
