### ISSUE TITLE
Low tunnel creation success rate

### ISSUE THREAD

**Issue by otakubeam** [PurpleI2P/i2pd#1457]
![image](https://user-images.githubusercontent.com/59658457/72663235-67425480-3a01-11ea-8630-c41a7a1d6a36.png)
Not only is it low, but also decreasing from about ~27%. And so I was wondering is there a way to fix it? I checked the system clock is fine. Could there be anything else?

**Comment by orignal** [comment]
That's fine. Low is less than 10%

**Comment by xaozai** [comment]
I have this value about 50 when I start i2pd, but it drops daily. After 50 days, the value is 21%.
