### ISSUE TITLE
Compilation broken on sparc in gentoo

### ISSUE THREAD

**Issue by yhaenggi** [PurpleI2P/i2pd#1462]
Tried to update i2pd today on my sparc machines, got failures with multiple version due to boost issues:
https://gist.github.com/yhaenggi/f083254fc7928413853c60b8dd2a47ea

**Comment by r4sas** [comment]
`/usr/include/boost/asio/impl/executor.hpp:XXX:XX: error: ‘class std::reference_wrapper<boost::asio::io_context>’ has no member named ‘<...>’`

`-- Boost version: 1.72.0`

**Comment by r4sas** [comment]
Not our issue: https://github.com/zaphoyd/websocketpp/issues/794

**Comment by r4sas** [comment]
So, I tested with develop branch of websocketpp on Windows with MSYS2 using boost 1.72. Only on develop branch that issue was fixed.
Contact with webcryptopp package maintainer of your system.
