### ISSUE TITLE
[Feature Request] Add I2Pd Firejail profile for sandboxing

### ISSUE THREAD

**Issue by za3ter2p** [PurpleI2P/i2pd#1465]
Its great for I2Pd to have sandboxing feature using Linux Namespaces through Firejail. 

I think the idea is just to create I2Pd profile and push it with Firejail-Profiles: 

https://github.com/netblue30/firejail/wiki/Creating-Profiles
https://firejail.wordpress.com/documentation-2/building-custom-profiles/

**Comment by r4sas** [comment]
No one in touch with it, so if anyone want to add it, please send PR.
