### ISSUE TITLE
Question: HTTP signatures is not presented in .conf

### ISSUE THREAD

**Issue by za3ter2p** [PurpleI2P/i2pd#1467]
Im trying to figure which type of crypto signature used for example.i2p so i went to i2pd.conf: 

```
[httpproxy]
## Uncomment and set to 'false' to disable HTTP Proxy
# enabled = true
## Address and port service will listen on
address = 127.0.0.1
port = 4444
## Optional keys file for proxy local destination
# keys = http-proxy-keys.dat
## Enable address helper for adding .i2p domains with "jump URLs" (default: true)
# addresshelper = true
## Address of a proxy server inside I2P, which is used to visit regular Internet
# outproxy = http://false.i2p
## httpproxy section also accepts I2CP parameters, like "inbound.length" etc.
```

and tunnels.conf doesnt contain http (only IRC-IRC2P , IRC-ILITA , SMTP , POP3)  

So should i add " signature = 7 or 11" manually in order to enforce only this type of signature that i want my router to connect only to those peers using this particular type of signature or  where can i find that? 

Sorry if im lost but hope someone help me with this.

**Comment by r4sas** [comment]
> using this particular type

You can't.
Changing `signature` parameter affects only on your end, but doesn't provide availability to enforce only particular types.
