### ISSUE TITLE
Add EOL to old routers to avoid backward insecurity (SHA-1 Garbage)

### ISSUE THREAD

**Issue by za3ter2p** [PurpleI2P/i2pd#1468]
SHA-1 is presented heavily in the old I2P routers, its better to end this by not having peers with shitty encryption in user netdb.

Tor for example has made an [End-Of-Life](https://blog.torproject.org/removing-end-life-relays-network) to eliminate bad relays. 

Why SHA-1 is bad? 

Good discussions about that in I2P Trac can be found [here](https://trac.i2p2.de/ticket/2643) and [here](https://trac.i2p2.de/ticket/2525). 

Just recently newer SHA-1 been discussed: 

https://www.schneier.com/blog/archives/2020/01/new_sha-1_attac.html

**Comment by orignal** [comment]
I2P uses SHA1 in the DSA signatures only  considered obsolete for last 5 years
