### ISSUE TITLE
Address Book Web Page

### ISSUE THREAD

**Issue by Zero3K** [PurpleI2P/i2pd#1469]
It would be nice if a web page that shows the addresses in the address book and allowed adding/deleting of them and subscriptions was added to the console.

**Comment by r4sas** [comment]
I think that won't be done, because webconsole is not this things.
@orignal ?

**Comment by orignal** [comment]
i2pd webconsole is for diagnostics only, it's not supposed to make any configuration changes,
If you wish to edit the addressbook through GUI, create similar request for i2pd-qt
