### ISSUE TITLE
Why use I2PD and not I2P?

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [PurpleI2P/i2pd#1471]
I will run I2PD on my Android Device.

What I can't find nowhere is any short info (just one sentence) why I should prefer I2PD for supporting I2P instead of the normal I2P Client!
I think at least one sentence about it should get added to the homepage and the Readme.md.

**Comment by r4sas** [comment]
https://i2pd.readthedocs.io/en/latest/user-guide/FAQ/#how-i2pd-differs-from-original-i2p-implementation
