### ISSUE TITLE
App can't access extSD on my Android Device

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [PurpleI2P/i2pd#1472]
Seems the I2PD App can't access the extSD on my Android Device!

I attach screenshots from the error, permissions app have in system and one that shows the paths my device have by default.

Maybe there should be in the menu a option to open the default Android File Picker, navigate to the right path, if app can't find it, and give read/write permissions, if needed.

![2020_02_19_04_54_49](https://user-images.githubusercontent.com/11881073/74803789-896c1280-52de-11ea-9cb5-b30844162cd0.jpg)

![2020_02_19_04_57_27](https://user-images.githubusercontent.com/11881073/74803837-b91b1a80-52de-11ea-99c7-47ea7654d125.jpg)

![2020_02_19_04_59_45](https://user-images.githubusercontent.com/11881073/74803859-c6d0a000-52de-11ea-87fe-058b84f9d5f2.jpg)

**Comment by dbermond** [comment]
It looks like you're using Android 10. If so, this is a known problem for version 2.29.0 and earlier on Android 10 and was already fixed in git master by commit https://github.com/PurpleI2P/i2pd/commit/26ad793d82bb0b1df23613ed77bcd6364a1b8b55.

**Comment by Tobias-B-Besemer** [comment]
Yes, Android 10!
Didn't knew that!
As I not compile: When will fixed client get published ???

**Comment by r4sas** [comment]
> As I not compile: When will fixed client get published ???

New version will be on next week (parallel with Java I2P).

**Comment by Tobias-B-Besemer** [comment]
Thank you very much! :)
