### ISSUE TITLE
Output of status Firewall/UPnP

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [PurpleI2P/i2pd#1473]
Not long ago I made a new attempt to support the I2P Network from/with my Home Network.
I tested the I2P Android App and the Windows Client.
Both Clients wasn't able to use much from the recources I be willing to give!
Seems the reason was, that both clients thought they are behind a firewall, because they weren't able to open a port in the router with UPnP!
Background Info: My Home Network is a MESH Network build with multiple WiFi Routers.
I be pretty sure I set up the network right, but for any reason they connected always to the wrong router to open a port in the firewall!
I guess there is something "wrong" in the lib used by all clients and the lib just don't respect my config...
So far the background story to this issue...
...now to the real issue... ^^

I think I2PD should give at least one line output if the client things he is firewalled, or if he is able to connect as should to the other clients!

And if I have this info, I can dig deeper into the prob why I2P will not use the recources I really be willing to give and this is f*cking 100MBit Glass Fiber, but the st*pid clients send & receive maybe just ~1KB/s... :-/

**Comment by r4sas** [comment]
About UPnP: miniupnp searches IGD with its own algorithm, so we is not in touch with it.
About speeds: you must take i2pd online for 5 days online at least, so other routers can profile it (in java i2p profiler is used to make preferences).
