### ISSUE TITLE
JNI methods for android.

### ISSUE THREAD

**Issue by wipedlifepotato** [PurpleI2P/i2pd#1480]
We must to add JNI methods for the android application.

**Comment by nonlinear-chaos-order-etc-etal** [comment]
wtf? please explain

**Comment by nonlinear-chaos-order-etc-etal** [comment]
which jni methods do you need? there are already a number of jni methods, what do you want?

@r4sas please close this issue, this is a completely void issue, until @wipedlifepotato reopens it with something less void.

**Comment by nonlinear-chaos-order-etc-etal** [comment]
@r4sas i would mark this so-called "issue" as INVALID
