### ISSUE TITLE
Q: any way to export the reseed.zip file to share with others ?

### ISSUE THREAD

**Issue by Cavefishy** [PurpleI2P/i2pd#1481]
I really like this project, it's amazing, the connection speed is faster than i2p. 
However, a friend of mine live in a place with serious internet censorship and needs me export the latest reseed.zip seeding to him. 
I didn't find the way of exporting reseed file in i2pd after reading the doc.
Is there any way to generate the reseed file?
Thank you in advance.

**Comment by r4sas** [comment]
duplicate of https://github.com/PurpleI2P/i2pd/issues/1291
