### ISSUE TITLE
[documentation] flatpak/flathub entry: проставить лицензию и скриншот в флатхаб рефе

### ISSUE THREAD

**Issue by nonlin-lin-chaos-order-etc-etal** [PurpleI2P/i2pd#1486]
скриншот:

![изображение](https://user-images.githubusercontent.com/19966907/75809685-20979680-5dc4-11ea-8675-53c4d72fe223.png)

**Comment by r4sas** [comment]
Нужно читать доки по поводу конфигурации: https://github.com/flathub/website.i2pd.i2pd/blob/master/website.i2pd.i2pd.json

**Comment by r4sas** [comment]
https://github.com/flathub/flathub/wiki/AppData-Guidelines

**Comment by nonlinear-chaos-order-etc-etal** [comment]
R4SAS> BreakCoreTime: че, будешь appdata писать?

R4SAS> Вот пример: https://github.com/flathub/com.google.AndroidStudio/blob/master/com.google.AndroidStudio.appdata.xml

**Comment by nonlinear-chaos-order-etc-etal** [comment]
Hmm.

1. On https://flathub.org/apps/details/website.i2pd.i2pd , screenshot is present and license *is* set. However the INSTALL button there leads to a screen *without* screenshot and license.

2. However https://github.com/flathub/website.i2pd.i2pd/blob/master/website.i2pd.i2pd.appdata.xml shows a 404, and https://github.com/flathub/website.i2pd.i2pd/ doesn't have a website.i2pd.i2pd.appdata.xml file.

3. There exists https://github.com/PurpleI2P/i2pd/blob/openssl/qt/i2pd_qt/data/website.i2pd.i2pd.appdata.xml .

4. However I failed to verify it:

```
flatpak run org.freedesktop.appstream-glib validate website.i2pd.i2pd.appdata.xml
bwrap: Can't create file at /run/systemd/journal/socket: No such device or address
```

So I currently leave this all to stay as is.

**Comment by nonlinear-chaos-order-etc-etal** [comment]
Android Studio flatpakref doesn't even load that screen from INSTALL button at https://flathub.org/apps/details/com.google.AndroidStudio , see this image:

![image](https://user-images.githubusercontent.com/19966907/96741696-ac623f80-13f4-11eb-9cac-5fe69d331e68.png)
