### ISSUE TITLE
LAN proxy failed，help，help

### ISSUE THREAD

**Issue by nickle1106** [PurpleI2P/i2pd#1489]
I2PD is installed on UNBUNTU SERVER 16.04
1. Control via remote webpage;
2. See the attachment for the running status of the program.
![I2PDscreen](https://user-images.githubusercontent.com/9586489/75938839-ae0de000-5ec3-11ea-9571-6e0d59373bd5.png)

3. The computer in the local area network cannot pass the server IP: 4444
Can someone help me to see, what is the solution?

**Comment by nickle1106** [comment]
Service | State
-- | --
HTTP Proxy |  
SOCKS Proxy |  
BOB |  
SAM |  
I2CP |  
I2PControl |

**Comment by nickle1106** [comment]
i2pd webconsole
Main page

Router commands
Local destinations
LeaseSets
Tunnels
Transit tunnels
Transports
I2P tunnels
Uptime: 1 hours, 2 min, 39 seconds
Network status: OK
Tunnel creation success rate: 50%
Received: 118.42 MiB (36.25 KiB/s)
Sent: 106.30 MiB (34.82 KiB/s)
Transit: 91.33 MiB (29.81 KiB/s)
Data path: /var/lib/i2pd
Hidden content. Press on text to see.Routers: 2844 Floodfills: 1572 LeaseSets: 0
Client Tunnels: 72 Transit Tunnels: 218

**Comment by nickle1106** [comment]
## Configuration file for a typical i2pd user
## See https://i2pd.readthedocs.io/en/latest/user-guide/configuration/
## for more options you can use in this file.

## Lines that begin with "## " try to explain what's going on. Lines
## that begin with just "#" are disabled commands: you can enable them
## by removing the "#" symbol.

## Tunnels config file
## Default: ~/.i2pd/tunnels.conf or /var/lib/i2pd/tunnels.conf
# tunconf = /var/lib/i2pd/tunnels.conf

## Tunnels config files path
## Use that path to store separated tunnels in different config files.
## Default: ~/.i2pd/tunnels.d or /var/lib/i2pd/tunnels.d
# tunnelsdir = /var/lib/i2pd/tunnels.conf.d

## Where to write pidfile (don't write by default)
# pidfile = /var/run/i2pd.pid

## Logging configuration section
## By default logs go to stdout with level 'info' and higher
##
## Logs destination (valid values: stdout, file, syslog)
##  * stdout - print log entries to stdout
##  * file - log entries to a file
##  * syslog - use syslog, see man 3 syslog
# log = file
## Path to logfile (default - autodetect)
# logfile = /var/log/i2pd.log
## Log messages above this level (debug, *info, warn, error, none)
## If you set it to none, logging will be disabled
# loglevel = info
## Write full CLF-formatted date and time to log (default: write only time)
# logclftime = true

## Daemon mode. Router will go to background after start
daemon = true

## Specify a family, router belongs to (default - none)
# family =

## External IP address to listen for connections
## By default i2pd sets IP automatically
# host = 1.2.3.4

## Port to listen for connections
## By default i2pd picks random port. You MUST pick a random number too,
## don't just uncomment this
port = 4567

## Enable communication through ipv4
ipv4 = true
## Enable communication through ipv6
ipv6 = true

## Network interface to bind to
# ifname =
## You can specify different interfaces for IPv4 and IPv6
# ifname4 = 
# ifname6 = 

## Enable NTCP transport (default = true)
# ntcp = true
## If you run i2pd behind a proxy server, you can only use NTCP transport with ntcpproxy option 
## Should be http://address:port or socks://address:port
# ntcpproxy = http://0.0.0.0:8118
## Enable SSU transport (default = true)
# ssu = true

## Should we assume we are behind NAT? (false only in MeshNet)
# nat = true

## Bandwidth configuration
## L limit bandwidth to 32KBs/sec, O - to 256KBs/sec, P - to 2048KBs/sec,
## X - unlimited
## Default is X for floodfill, L for regular node
bandwidth = P
## Max % of bandwidth limit for transit. 0-100. 100 by default
share = 100

## Router will not accept transit tunnels, disabling transit traffic completely
## (default = false)
# notransit = true

## Router will be floodfill
# floodfill = true

[http]
## Web Console settings
## Uncomment and set to 'false' to disable Web Console
enabled = true
## Address and port service will listen on
address = 0.0.0.0
port = 7070
## Path to web console, default "/"
#webroot = /
## Uncomment following lines to enable Web Console authentication 
#auth = true
#user = 
#pass = 
strictheaders = false

[httpproxy]
## Uncomment and set to 'false' to disable HTTP Proxy
# enabled = true
## Address and port service will listen on
 address = 0.0.0.0
 port = 4444
## Optional keys file for proxy local destination
# keys = http-proxy-keys.dat
## Enable address helper for adding .i2p domains with "jump URLs" (default: true)
# addresshelper = true
## Address of a proxy server inside I2P, which is used to visit regular Internet
# outproxy = http://false.i2p
## httpproxy section also accepts I2CP parameters, like "inbound.length" etc.
inbound.length = 1
outbound.length = 1
inbound.quantity = 8
outbound.quantity = 8
outproxy = false.i2p
keys = http-proxy-keys.dat

[socksproxy]
## Uncomment and set to 'false' to disable SOCKS Proxy
enabled = false
## Address and port service will listen on
 address = 0.0.0.0
 port = 4447
## Optional keys file for proxy local destination
# keys = socks-proxy-keys.dat
## Socks outproxy. Example below is set to use Tor for all connections except i2p
## Uncomment and set to 'true' to enable using of SOCKS outproxy
# outproxy.enabled = true
## Address and port of outproxy
# outproxy = 0.0.0.0
# outproxyport = 9050
## socksproxy section also accepts I2CP parameters, like "inbound.length" etc.

[sam]
## Uncomment and set to 'true' to enable SAM Bridge
enabled = false
## Address and port service will listen on
# address = 0.0.0.0
# port = 7656

[bob]
## Uncomment and set to 'true' to enable BOB command channel
# enabled = false
## Address and port service will listen on
# address = 0.0.0.0
# port = 2827

[i2cp]
## Uncomment and set to 'true' to enable I2CP protocol
# enabled = false
## Address and port service will listen on
# address = 0.0.0.0
# port = 7654

[i2pcontrol]
## Uncomment and set to 'true' to enable I2PControl protocol
enabled = false
## Address and port service will listen on
# address = 0.0.0.0
# port = 7650
## Authentication password. "itoopie" by default
# password = itoopie

[precomputation]
## Enable or disable elgamal precomputation table
## By default, enabled on i386 hosts
elgamal = true

[upnp]
## Enable or disable UPnP: automatic port forwarding (enabled by default in WINDOWS, ANDROID)
# enabled = false
## Name i2pd appears in UPnP forwardings list (default = I2Pd)
# name = I2Pd

[reseed]
## Options for bootstrapping into I2P network, aka reseeding
## Enable or disable reseed data verification.
verify = true
## URLs to request reseed data from, separated by comma
## Default: "mainline" I2P Network reseeds
# urls = https://reseed.i2p-projekt.de/,https://i2p.mooo.com/netDb/,https://netdb.i2p2.no/
## Path to local reseed data file (.su3) for manual reseeding
# file = /path/to/i2pseeds.su3
## or HTTPS URL to reseed from
# file = https://legit-website.com/i2pseeds.su3
## Path to local ZIP file or HTTPS URL to reseed from
# zipfile = /path/to/netDb.zip
## If you run i2pd behind a proxy server, set proxy server for reseeding here
## Should be http://address:port or socks://address:port
proxy = http://127.0.0.1:8087
## Minimum number of known routers, below which i2pd triggers reseeding. 25 by default
# threshold = 25
urls = https://github.com/r4sas/i2pd-reseed/releases/download/1.0/i2pseeds.su3/,https://reseed.i2p-projekt.de/,https://i2p.mooo.com/netDb/,https://netdb.i2p2.no/


[addressbook]
## AddressBook subscription URL for initial setup
## Default: inr.i2p at "mainline" I2P Network
# defaulturl = http://joajgazyztfssty4w2on5oaqksz6tqoxbduy553y34mf4byv6gpq.b32.i2p/export/alive-hosts.txt
## Optional subscriptions URLs, separated by comma
# subscriptions = http://inr.i2p/export/alive-hosts.txt,http://stats.i2p/cgi-bin/newhosts.txt,http://rus.i2p/hosts.txt

[limits]
## Maximum active transit sessions (default:2500)
# transittunnels = 2500
## Limit number of open file descriptors (0 - use system limit)  
# openfiles = 0
## Maximum size of corefile in Kb (0 - use system limit) 
# coresize = 0
## Threshold to start probabalistic backoff with ntcp sessions (0 - use system limit) 
# ntcpsoft = 0
## Maximum number of ntcp sessions (0 - use system limit) 
# ntcphard = 0

[trust]
## Enable explicit trust options. false by default
# enabled = true
## Make direct I2P connections only to routers in specified Family.
# family = MyFamily
## Make direct I2P connections only to routers specified here. Comma separated list of base64 identities.
# routers = 
## Should we hide our router from other routers? false by default
# hidden = true

[exploratory]
## Exploratory tunnels settings with default values
# inbound.length = 2 
# inbound.quantity = 3
# outbound.length = 2
# outbound.quantity = 3

[persist]
## Save peer profiles on disk (default: true)
# profiles = true

**Comment by nickle1106** [comment]
Last login: Thu Mar  5 22:58:51 2020 from 192.168.1.102
root@nickle1106-D420:~# netstat -tunlp | grep i2pd
tcp        0      0 0.0.0.0:4567            0.0.0.0:*               LISTEN      7497/i2pd
tcp        0      0 192.168.1.113:4444      0.0.0.0:*               LISTEN      7497/i2pd
tcp        0      0 0.0.0.0:7070            0.0.0.0:*               LISTEN      7497/i2pd
tcp6       0      0 :::4567                 :::*                    LISTEN      7497/i2pd
udp        0      0 0.0.0.0:4567            0.0.0.0:*                           7497/i2pd
udp6       0      0 :::4567                 :::*                                7497/i2pd

**Comment by r4sas** [comment]
As you can see, your configuration is not applied.
* Are you really edited `/etc/i2pd/i2pd.conf`?
* Have you restarted i2pd after changing settings?

**Comment by nickle1106** [comment]
![image](https://user-images.githubusercontent.com/9586489/76132487-30c2a680-604e-11ea-90b7-0b00e5f53abb.png)
![image](https://user-images.githubusercontent.com/9586489/76132529-65cef900-604e-11ea-8997-fdc41e91087f.png)

**Comment by nickle1106** [comment]
i2pd.conf

## Configuration file for a typical i2pd user
## See https://i2pd.readthedocs.io/en/latest/user-guide/configuration/
## for more options you can use in this file.

## Lines that begin with "## " try to explain what's going on. Lines
## that begin with just "#" are disabled commands: you can enable them
## by removing the "#" symbol.

## Tunnels config file
## Default: ~/.i2pd/tunnels.conf or /var/lib/i2pd/tunnels.conf
# tunconf = /var/lib/i2pd/tunnels.conf

## Tunnels config files path
## Use that path to store separated tunnels in different config files.
## Default: ~/.i2pd/tunnels.d or /var/lib/i2pd/tunnels.d
# tunnelsdir = /var/lib/i2pd/tunnels.conf.d

## Where to write pidfile (don't write by default)
# pidfile = /var/run/i2pd.pid

## Logging configuration section
## By default logs go to stdout with level 'info' and higher
##
## Logs destination (valid values: stdout, file, syslog)
##  * stdout - print log entries to stdout
##  * file - log entries to a file
##  * syslog - use syslog, see man 3 syslog
# log = file
## Path to logfile (default - autodetect)
# logfile = /var/log/i2pd.log
## Log messages above this level (debug, *info, warn, error, none)
## If you set it to none, logging will be disabled
# loglevel = info
## Write full CLF-formatted date and time to log (default: write only time)
# logclftime = true

## Daemon mode. Router will go to background after start
daemon = true

## Specify a family, router belongs to (default - none)
 family = none 

## External IP address to listen for connections
## By default i2pd sets IP automatically
# host = 1.2.3.4

## Port to listen for connections
## By default i2pd picks random port. You MUST pick a random number too,
## don't just uncomment this
port = 4567

## Enable communication through ipv4
ipv4 = true
## Enable communication through ipv6
ipv6 = true

## Network interface to bind to
# ifname =
## You can specify different interfaces for IPv4 and IPv6
# ifname4 = 
# ifname6 = 

## Enable NTCP transport (default = true)
 ntcp = true
## If you run i2pd behind a proxy server, you can only use NTCP transport with ntcpproxy option 
## Should be http://address:port or socks://address:port
# ntcpproxy = http://0.0.0.0:8118
## Enable SSU transport (default = true)
 ssu = true

## Should we assume we are behind NAT? (false only in MeshNet)
 nat = false

## Bandwidth configuration
## L limit bandwidth to 32KBs/sec, O - to 256KBs/sec, P - to 2048KBs/sec,
## X - unlimited
## Default is X for floodfill, L for regular node
bandwidth = 8192
## Max % of bandwidth limit for transit. 0-100. 100 by default
share = 100

## Router will not accept transit tunnels, disabling transit traffic completely
## (default = false)
 notransit = false

## Router will be floodfill
 floodfill = false

[http]
## Web Console settings
## Uncomment and set to 'false' to disable Web Console
enabled = true
## Address and port service will listen on
address = 0.0.0.0
port = 7070
## Path to web console, default "/"
#webroot = /
## Uncomment following lines to enable Web Console authentication 
#auth = true
#user = nickle1106
#pass = 152939
strictheaders = false

[httpproxy]
## Uncomment and set to 'false' to disable HTTP Proxy
 enabled = true
## Address and port service will listen on
 address = 192.168.1.113
 port = 4444
## Optional keys file for proxy local destination
# keys = http-proxy-keys.dat
## Enable address helper for adding .i2p domains with "jump URLs" (default: true)
# addresshelper = true
## Address of a proxy server inside I2P, which is used to visit regular Internet
# outproxy = http://false.i2p
## httpproxy section also accepts I2CP parameters, like "inbound.length" etc.

[socksproxy]
## Uncomment and set to 'false' to disable SOCKS Proxy
enabled = false
## Address and port service will listen on
 address = 0.0.0.0
 port = 4447
## Optional keys file for proxy local destination
# keys = socks-proxy-keys.dat
## Socks outproxy. Example below is set to use Tor for all connections except i2p
## Uncomment and set to 'true' to enable using of SOCKS outproxy
# outproxy.enabled = true
## Address and port of outproxy
# outproxy = 0.0.0.0
# outproxyport = 9050
## socksproxy section also accepts I2CP parameters, like "inbound.length" etc.

[sam]
## Uncomment and set to 'true' to enable SAM Bridge
enabled = false
## Address and port service will listen on
# address = 0.0.0.0
# port = 7656

[bob]
## Uncomment and set to 'true' to enable BOB command channel
# enabled = false
## Address and port service will listen on
# address = 0.0.0.0
# port = 2827

[i2cp]
## Uncomment and set to 'true' to enable I2CP protocol
# enabled = false
## Address and port service will listen on
# address = 0.0.0.0
# port = 7654

[i2pcontrol]
## Uncomment and set to 'true' to enable I2PControl protocol
enabled = false
## Address and port service will listen on
# address = 0.0.0.0
# port = 7650
## Authentication password. "itoopie" by default
# password = itoopie

[precomputation]
## Enable or disable elgamal precomputation table
## By default, enabled on i386 hosts
elgamal = true

[upnp]
## Enable or disable UPnP: automatic port forwarding (enabled by default in WINDOWS, ANDROID)
# enabled = false
## Name i2pd appears in UPnP forwardings list (default = I2Pd)
# name = I2Pd

[reseed]
## Options for bootstrapping into I2P network, aka reseeding
## Enable or disable reseed data verification.
verify = true
## URLs to request reseed data from, separated by comma
## Default: "mainline" I2P Network reseeds
# urls = https://reseed.i2p-projekt.de/,https://i2p.mooo.com/netDb/,https://netdb.i2p2.no/
## Path to local reseed data file (.su3) for manual reseeding
# file = /path/to/i2pseeds.su3
## or HTTPS URL to reseed from
# file = https://legit-website.com/i2pseeds.su3
## Path to local ZIP file or HTTPS URL to reseed from
# zipfile = /path/to/netDb.zip
## If you run i2pd behind a proxy server, set proxy server for reseeding here
## Should be http://address:port or socks://address:port
# proxy = http://127.0.0.1:8087
## Minimum number of known routers, below which i2pd triggers reseeding. 25 by default
# threshold = 25
urls = https://github.com/r4sas/i2pd-reseed/releases/download/1.0/i2pseeds.su3/,https://reseed.i2p-projekt.de/,https://i2p.mooo.com/netDb/,https://netdb.i2p2.no/


[addressbook]
## AddressBook subscription URL for initial setup
## Default: inr.i2p at "mainline" I2P Network
# defaulturl = http://joajgazyztfssty4w2on5oaqksz6tqoxbduy553y34mf4byv6gpq.b32.i2p/export/alive-hosts.txt
## Optional subscriptions URLs, separated by comma
# subscriptions = http://inr.i2p/export/alive-hosts.txt,http://stats.i2p/cgi-bin/newhosts.txt,http://rus.i2p/hosts.txt

[limits]
## Maximum active transit sessions (default:2500)
# transittunnels = 2500
## Limit number of open file descriptors (0 - use system limit)  
# openfiles = 0
## Maximum size of corefile in Kb (0 - use system limit) 
# coresize = 0
## Threshold to start probabalistic backoff with ntcp sessions (0 - use system limit) 
# ntcpsoft = 0
## Maximum number of ntcp sessions (0 - use system limit) 
# ntcphard = 0

[trust]
## Enable explicit trust options. false by default
# enabled = true
## Make direct I2P connections only to routers in specified Family.
# family = MyFamily
## Make direct I2P connections only to routers specified here. Comma separated list of base64 identities.
# routers = 
## Should we hide our router from other routers? false by default
# hidden = true

[exploratory]
## Exploratory tunnels settings with default values
# inbound.length = 2 
# inbound.quantity = 3
# outbound.length = 2
# outbound.quantity = 3

[persist]
## Save peer profiles on disk (default: true)
# profiles = true

**Comment by nickle1106** [comment]
tunnels.conf

#[IRC-IRC2P]
#type = client
#address = 0.0.0.0
#port = 6668
#destination = irc.postman.i2p
#destinationport = 6667
#keys = irc-keys.dat

#[IRC-ILITA]
#type = client
#address = 0.0.0.0
#port = 6669
#destination = irc.ilita.i2p
#destinationport = 6667
#keys = irc-keys.dat

#[SMTP]
#type = client
#address = 0.0.0.0
#port = 7659
#destination = smtp.postman.i2p
#destinationport = 25
#keys = smtp-keys.dat

#[POP3]
#type = client
#address = 0.0.0.0
#port = 7660
#destination = pop.postman.i2p
#destinationport = 110
#keys = pop3-keys.dat

# see more examples at https://i2pd.readthedocs.io/en/latest/user-guide/tunnels/

**Comment by nickle1106** [comment]
On the server, I also run the XXNET service, is there any conflict?

**Comment by nickle1106** [comment]
![image](https://user-images.githubusercontent.com/9586489/76132965-a7f93a00-6050-11ea-9537-008c12616c07.png)

[conf.zip](https://github.com/PurpleI2P/i2pd/files/4301199/conf.zip)

**Comment by r4sas** [comment]
From local network you trying open with address 192.168.1.113:4444?

Maybe you have enabled firewall which block connections?

**Comment by nickle1106** [comment]
![image](https://user-images.githubusercontent.com/9586489/76154608-3daccc00-611a-11ea-8bdf-37c390878e51.png)

The firewall was never turned on

I try I2P, can you tell me where is the configuration file of this program? Thank you.

I2P is installed on the server. I want to configure the remote management configuration of the LAN, and proxy other LANs to access the Internet scientifically.

**Comment by nickle1106** [comment]
![image](https://user-images.githubusercontent.com/9586489/76154796-8914a980-611d-11ea-96cb-d71be31b443a.png)
According to this screenshot, the configuration should be no problem, XXNET can use.

**Comment by r4sas** [comment]
> The firewall was never turned on

Check for `iptables`.

> I try I2P

I don't know where Java I2P store config.

> According to this screenshot, the configuration should be no problem, XXNET can use.

Also I see that i2pd started on 0.0.0.0:4444. So here problem somethere else, recheck your network/firewall/port restriction for LAN.

**Comment by nickle1106** [comment]
Perhaps in China, I2PD is closely monitored, my router was automatically shut down 2 times, XXNET's effective IP instantly zero.

I'm ready to give up.

**Comment by nickle1106** [comment]
Perhaps in China, I2PD is closely monitored, my router was automatically shut down 3 times, XXNET's effective IP instantly zero.

I'm ready to give up.

**Comment by yhaenggi** [comment]
Most cheap commodity router hardware cant handle many NAT sessions. That would explain shutdown/reboot of your router.
You could test from another machine with this:
```http_proxy=http://192.168.1.113/ curl -v zzz.i2p```
FYI: i have a i2pd node behind the GCFW and dont face issues (yet).

**Comment by nickle1106** [comment]
Asus AC68U should not be the lowest-end router

XXNET's effective IP suddenly dropped to 0 what happened, such a situation followed by the router automatic shutdown appeared.

**Comment by johnrosen1** [comment]
@nickle1106 你有公网ip吗？有的话应该不会连接失败,试试dmz。
