### ISSUE TITLE
What is going on with my traffic

### ISSUE THREAD

**Issue by ookangzheng** [PurpleI2P/i2pd#1492]
Hi,

Im using Debian 10 64bit, both have Ipv4, IPv6. I ran i2pd for half day and it already cost a lot of traffic, whats going wrong or I contribute to I2P traffic?

<img width="677" alt="image" src="https://user-images.githubusercontent.com/6301735/77406538-c486c780-6def-11ea-81ae-74d292b7dce9.png">

my i2pd conf: https://0x0.st/iahs.conf

**Comment by r4sas** [comment]
What's wrong? Can't understand your question.

If you about transit traffic - that is amount of transfered data through your node. For example, on your picture, you received and send 1.29 Gb.

**Comment by ookangzheng** [comment]
I didnt surfing I2P site that much, and why it still cause that amount of data?
Do you mean other garlic routing (other user) will pass through my server as well, aka proxy or middleman?

**Comment by r4sas** [comment]
If you disable transit, nothing will be sent via your router. But tunnels anyway will generate traffic because updated every 10 minutes, netdb updated, etc...
