### ISSUE TITLE
dual stack

### ISSUE THREAD

**Issue by babut85** [PurpleI2P/i2pd#1498]
простите, что на русском, но вижу, что такое здесь практикуется :\ 
если поддерживается ipv6 и ipv4, то как же тогда указать куда биндиться сервисам? address принимает только одно значение, мне не хватило фантазии найти комбинацию, когда, к примеру, socks proxy открывается одновременно и на 127.0.0.1, и на ::1.
вопрос не занудства ради, а из-за того, что есть ошибки, природу которых я не понимаю:
NTCP: failed to bind to ip6 port 8010
Transports: SSU server already exists
SSU: server runtime exception: send_to: Can't assign requested address
и debug никак не подводит к природе данных ошибок.
кроме того, открывается на прослушку udp/8012, даже когда такого порта в моём конфиге нет.
где-нибудь можно раздобыть полную документацию на i2pd? а то по --help явно какая-то урезанная версия

**Comment by babut85** [comment]
зы: в моём случае есть особенность- для ipv4 и ipv6 используются разные ифейсы: физический локали- для ipv6(вот с ним-то менее всего проблем ожидаешь, а гляди-ка), и не совсем физический(pppoe)- для ipv4. однако ж данная особенность отражена через ifname4 и ifname6. и ошибка с внешним 8010 портом- это не про дуальность наверное. но остальное на то похоже

**Comment by r4sas** [comment]
А версия какая?

**Comment by babut85** [comment]
2.26 на опёнке. не, ту документацию я смотрел, в ней нет ничего про то, как дважды указать конкретный ip, каждый из фейсов имеет ipv4 и как минимум один ipv6 link-local, а то и больше. хотелось бы принудительно посадить всё на 127.0.0.1 и ::1 -дабы избежать неопределённости, а оно садится только на что-то одно, но нельзя же на этом одном работать сразу по ipv4 и ipv6

**Comment by r4sas** [comment]
Можете свой конфиг показать?
Просьба форматировать вывод используя тройной апостроф ( ` ) в начале и конце вывода.

**Comment by babut85** [comment]
странное дело. на днях свет отрубали и роутер перезапустился. и вот сейчас я этих ошибок не наблюдаю(а ipv6 есть, и вроде всё как всегда). бред какой-то %\ остались только многочисленные "end of file". при этом худо-бедно i2p работает
