### ISSUE TITLE
Compiler too old on too new compiler (again)

### ISSUE THREAD

**Issue by yangfl** [PurpleI2P/i2pd#1507]
Fail to build with `make` on gcc 10

refs:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=957345

**Comment by r4sas** [comment]
Fixed in https://github.com/PurpleI2P/i2pd/commit/716378bd6bb2e8417fd208fabcda9c80d7593b64

**Comment by r4sas** [comment]
@orignal found that ubuntu 18.04 returns in g++ just "7", so https://github.com/PurpleI2P/i2pd/commit/1e4d2fd05380c9702ed6cfb4d83b9fc30c51e14f was added.
