### ISSUE TITLE
How to reduce high CPU usage on i2pd process

### ISSUE THREAD

**Issue by ookangzheng** [PurpleI2P/i2pd#1508]
![2020-04-21 23 09 43](https://user-images.githubusercontent.com/6301735/79882579-6c120c80-8425-11ea-8e62-37f9c14e181a.gif)

How to reduce high CPU usage?

Env: Debian 10 64bit, latest version 
Install i2pd with: wget -q -O - https://repo.i2pd.xyz/.help/add_repo | sudo bash -s -

Thanks

**Comment by r4sas** [comment]
Limit or disable transit tunnels.

**Comment by ookangzheng** [comment]
This does fix this issue. 
Thanks
