### ISSUE TITLE
vmware machine  not  remote  connect port 4444 4447 9050

### ISSUE THREAD

**Issue by vanxv** [PurpleI2P/i2pd#1516]
vmware machine 
 not  remote  connect port 4444 4447 9050

~/.i2pd/i2pd.conf

```
[http]
## Web Console settings
## Uncomment and set to 'false' to disable Web Console
enabled = true
## Address and port service will listen on
address = 0.0.0.0
port = 7070
## Path to web console, default "/"
# webroot = /
## Uncomment following lines to enable Web Console authentication 
# auth = true
# user = i2pd
# pass = changeme

[httpproxy]
## Uncomment and set to 'false' to disable HTTP Proxy
enabled = true
## Address and port service will listen on
address = 0.0.0.0
port = 4444
## Optional keys file for proxy local destination
# keys = http-proxy-keys.dat
## Enable address helper for adding .i2p domains with "jump URLs" (default: true)
# addresshelper = true
## Address of a proxy server inside I2P, which is used to visit regular Internet
# outproxy = http://false.i2p
## httpproxy section also accepts I2CP parameters, like "inbound.length" etc.

[socksproxy]
## Uncomment and set to 'false' to disable SOCKS Proxy
enabled = true
## Address and port service will listen on
address = 0.0.0.0
port = 4447
## Optional keys file for proxy local destination
# keys = socks-proxy-keys.dat
## Socks outproxy. Example below is set to use Tor for all connections except i2p
## Uncomment and set to 'true' to enable using of SOCKS outproxy
outproxy.enabled = true
## Address and port of outproxy
outproxy = 0.0.0.0
outproxyport = 9050
## socksproxy section also accepts I2CP parameters, like "inbound.length" etc.

[sam]
## Uncomment and set to 'true' to enable SAM Bridge
enabled = true
## Address and port service will listen on
# address = 127.0.0.1
# port = 7656

[bob]
## Uncomment and set to 'true' to enable BOB command channel
# enabled = false
## Address and port service will listen on
# address = 127.0.0.1
# port = 2827

[i2cp]
## Uncomment and set to 'true' to enable I2CP protocol
# enabled = false
## Address and port service will listen on
# address = 127.0.0.1
# port = 7654

[i2pcontrol]
## Uncomment and set to 'true' to enable I2PControl protocol
# enabled = false
## Address and port service will listen on
# address = 127.0.0.1
# port = 7650
## Authentication password. "itoopie" by default
# password = itoopie
```

**Comment by r4sas** [comment]
Please concretize from/to where, network configuration.


> 9050

Outproxy is not provide proxy, it connects to it. So here you must set address to your Tor or SOCKS proxy installation.

**Comment by vanxv** [comment]
> Please concretize from/to where, network configuration.
> 
> > 9050
> 
> Outproxy is not provide proxy, it connects to it. So here you must set address to your Tor or SOCKS proxy installation.

——————————
@r4sas 

thank you answer

port：4444 4447 why not remote connect？

**Comment by r4sas** [comment]
> port：4444 4447 why not remote connect？

> Please concretize from/to where, network configuration.

**Comment by vanxv** [comment]
> > port：4444 4447 why not remote connect？
> 
> > Please concretize from/to where, network configuration.
> 
> Telepaths on vacation.

@r4sas 

sorry, i learning english，Many words are not recognized。

from=i2pd proxy socks？
to=i2pd open proxy socks port？

————————

environment：

vm1：
OS：centos 
install shadowsocks open socks 1080 port

vm2
OS：centos 
i2pd use vm1 1080 socks ports 

vm3
os：win7
need use VM2 i2pd socks  proxy connect Internet

**Comment by r4sas** [comment]
As I understand, you trying to connect to i2pd's ports 4444, 4447 from win7 vm3?

Have you checked if i2pd correctly bind via netstat?

Habe you checked if your vm2 grant access to ports from your vmware network (iptables)?

If you need clearnet access when using i2pd's SOCKS proxy at port 4447, you must set up `outproxy` and `outproxyport` to your SOCKS proxy address, which providing connection to internet (for example shadowsocks running on vm1).

**Comment by vanxv** [comment]
> > port：4444 4447 why not remote connect？
> 
> > Please concretize from/to where, network configuration.
> 
> Telepaths on vacation.

————————

thanks reply,issue solved.


welcome to china paly. Please play together^_^
