### ISSUE TITLE
Memory leak in HTTPServer::CreateConnection(boost::asio::ip::tcp::socket *)

### ISSUE THREAD

**Issue by ygrishin** [PurpleI2P/i2pd#152]
`new HTTPConnection (m_NewSocket);`

**Comment by orignal** [comment]
m_Socket->get_io_service ().post ([=](void)
			{
				m_Stream.reset ();
				m_Stream = nullptr;
				// delete this
			});

Commented out for another reason, will replace it to shred pointer. Had to wait until http proxy is not derived from HTTPServer anymore

**Comment by orignal** [comment]
fixed
