### ISSUE TITLE
[Question] How to set a serverless messenger/chat on i2pd ?

### ISSUE THREAD

**Issue by Nokia808** [PurpleI2P/i2pd#1521]
Hi. 
Currently, new messengers that not using any server are available. For example qTox. qTox already has proxy setting, so that could be set to connect over Tor.

But regarding i2p, what are the needed setting for that ? In setting for proxy within GUI of qTox there are:
- Proxy type (NONE & SOCKS & HTTP)
- Address
- Port

Also, is there need to add new tunnel(s) or there is already pre-existing tunnel(s) for such use ?

**Comment by r4sas** [comment]
4444, 4447?

**Comment by Nokia808** [comment]
I do not know ! I searched & found this about Retroshare but when I tried to applied it on i2pd, I faced a difficulty - for example: I did not found "SOCKS 4/4a/5" option ! I found only "SOCKS" - see:
https://retroshare.readthedocs.io/en/latest/tutorial/i2p-hidden-rs-node/

Can you kindly translate to i2pd language what user should done from side of setting of i2pd ?

**Comment by r4sas** [comment]
https://i2pd.readthedocs.io/en/latest/tutorials/retroshare/
?

**Comment by r4sas** [comment]
What about qTox - really don't know. How instances communicate between each other if you only provide "how to connect", but not "connect to"?

**Comment by Nokia808** [comment]
@r4sas 
Regarding Reatroshare: document said "Find .b32.i2p address of your RetroShare node. Go to webconsole -> I2P tunnels page. Look for Sever tunnels and you will see address like \<long random string>.b32.i2p next to "retroshare".
So, does b32.i2p address is changeable at every time i2pd run or it will be fixed ?

**Comment by Nokia808** [comment]
@r4sas 
What we have to do regarding qTox ? Asking it's developer ? I'm already open an issue to add preconfigured proxy setting within GUI of qTox .....

**Comment by Nokia808** [comment]
@r4sas 
The b32.i2p address for Retroshare is fixed & not changeable. I launched/closed gracefully for multiple times (3 times) & address is the same.

**Comment by r4sas** [comment]
Is qTox listening some address+port locally? How it connect to other tor-using nodes?

**Comment by nonlinear-chaos-order-etc-etal** [comment]
Also, there is old versions of "I2P Qt Messenger" all over the I2P which were working...

**Comment by nonlinear-chaos-order-etc-etal** [comment]
Though pity they had "seedless servers"...

**Comment by Nokia808** [comment]
@r4sas 
regarding "retroshare" server tunnel that I created I entered the following data that documented in link you gave me, USING GUI QT:
[retroshare]  
type=server  
host=127.0.0.1  
port=10123
keys=retroshare.dat
& leave all other parameters as them untouched in the newly created tunnel by GUI. GUI show me many other parameters. So, is this okay (is it okay to leave other parameters untouched) ?

1) qTox has in it's advanced option a proxy setting .... By default it set not to use a proxy.
Moreover, other Tox clients for Android support this like TRIFA which support connection over Tor ....
Jami, qTox are designed to be used offline over local network so they certainly able to connect over i2p .... 
Jami currently has no proxy setting but it is on their road of development ....

3) I'm already asked qTox developer to join this issue, to assist us ....

@nonlinear-chaos-order-etc-etal 
1) we need fully featured Skype like & serverless messenger like Retroshare.
qTox & uTox & Jami are the targets.

2) where can I find "I2P Qt messenger" ? Even if it still available & working, by no mean could be compared to Jami, qTox, Retroshare .....

**Comment by nonlinear-chaos-order-etc-etal** [comment]
@Nokia808 

http://echelon.i2p/qti2pmessenger/macos → Mac OS X versions;
http://echelon.i2p/qti2pmessenger/ → eche|on's site (versions up to 0.2.24);
https://launchpad.net/~i2p.packages/+archive/ubuntu/i2p/+sourcepub/4824794/+listing-archive-extra → Kill Your TV's PPA (v.0.2.25).
http://git.repo.i2p/w/I2P-Messenger-QT.git/shortlog → original repo

**Comment by nonlinear-chaos-order-etc-etal** [comment]
@Nokia808 

I also develop I2P Qt Messenger under brand of https://github.com/i2pchat/i2pchat/

But I have VERY little time and it's FULLY broken currently

**Comment by Nokia808** [comment]
@nonlinear-chaos-order-etc-etal 
Dear no need to bother yourself ! We are already have excellent application like:
- Retroshare,
- qTox,
- Jami

Instead wasting time bu building new application from scratch, let we improve already existing & maintained application like qTox & Jami ....
Regarding Jami, look for this issue:
https://git.jami.net/savoirfairelinux/ring-project/wikis/technical/4.3.-Features-requests
See under "Can be implemented, contributions welcome (or will take months/years to come)"
https://git.jami.net/savoirfairelinux/ring-project/issues/630

So, Jami welcome adding support for i2p & accept PR & patches. If you have time you can contribute to it such patch or PR & they will implement it.

**Comment by Nokia808** [comment]
@r4sas 
See this screenshot from qTox GUI:

![qTox-proxy-setting](https://user-images.githubusercontent.com/25375330/82750033-0ce54600-9d9d-11ea-8897-83e7c3f5bf79.png)

**Comment by Nokia808** [comment]
For more details on Tox protocol, qTox client & Jami see:

1) Tox protocol:
https://tox.chat/
https://github.com/TokTok/c-toxcore

2) qTox:
https://qtox.github.io/
https://github.com/qTox/qTox

3) Jami:
https://jami.net/
https://git.jami.net/savoirfairelinux

Such great serverless application what they will be if run within i2p network ?! Heroes !!

**Comment by r4sas** [comment]
I think qTox (and Tox itself) somehow used bootstrap nodes to make connections between users, but that need investigation and support from tox developers, who will create I2P nodes available 24/7 and add them to bootstrap.
I think that's what they need. Currently I have no much time to do such research.

**Comment by Nokia808** [comment]
@r4sas 
@nonlinear-chaos-order-etc-etal 
Just a minute ! I think we mixed in confusional way between 2 concept: run serverless messenger WITHIN darknet (Retroshare) & utilizing darknet by a serverless messenger JUST TO HIDE IP ......

1) Retroshare is by default an independent darknet like project. Any activity within Retroshare network is completely hidden even without Tor/i2p. Retroshare act like a hidden social network (hidden facebook). So, when Retroshare utilize Tor/i2p it aim is to add additional security wall around already security wall, & hence it aim at run itself (Retroshare) completely hidden WITHIN Tor/i2p network to be hidden inside hidden ..... Hince the complex setting of using "hidden service address" !

2) Tox client like TRIFA or qTox are using Tor just to hide real user IP, NOT to run hidden within hidden Tor network as Retroshare do. So, with Tox client, we have no need to utilize "hidden service address". Just to set address at 127.0.0.1 & port at 9050 & that is all !

So, regarding qTox we should target the usage of it with i2p to be just hide real user IP address in a way similar to that of Tor usage. Certainly, outproxy should be enabled in this case. **Now the question is: what are the address & port that should be used for Tox client ? & does we need to create s new tunnel ? & which type of tunnel - if any - should we create & what are it's values ?**

**Comment by Nokia808** [comment]
I think this issue should be closed now, because:

1) every thing now clear regarding Retroshare, & the nature of it's use over i2p (& Tor)
2) Tox is, currently, not suitable to be used COMPLETELY HIDDEN WITHIN i2p (& also within Tor) due to it used bootstrap nodes to make connections between users, but that need investigation and support from tox developers, who will create I2P nodes available 24/7 and add them to bootstrap.
3) Tox when utilize Tor is not to run completely hidden within Tor network, but JUST to hide real user IP.
4) Jami is theoretically very very fit to make use of i2p in the SAME WAY THAT OF RETROSHARE but not implemented yet ....

My be this issue was of help to bring your attention to Jami suitability to utilize i2p in same way that Retroshare currently do (run COMPLETELY HIDDEN WITHIN i2p) & this may stimulate you to generate patches & PR to implement this ability to Jami ... See: again

Regarding Jami, look for this issue:
https://git.jami.net/savoirfairelinux/ring-project/wikis/technical/4.3.-Features-requests
See under "Can be implemented, contributions welcome (or will take months/years to come)"
https://git.jami.net/savoirfairelinux/ring-project/issues/630

So, Jami welcome adding support for i2p & accept PR & patches. If you have time you can contribute to it such patch or PR & they will implement it.

Please look to my new issue:
https://github.com/PurpleI2P/i2pd/issues/1522
