### ISSUE TITLE
[Question] How to use i2p to connect "clear net server dependent" chat/messenger to it's server?

### ISSUE THREAD

**Issue by Nokia808** [PurpleI2P/i2pd#1522]
Hi. The following scenario:

1) user like to use Jitsi meet through Ferdi messenger & like to utilizes https://meet.jit.si as central server (Jitsi instance) on clear net.
2) Ferdi already offer proxy setting
3) there is firewall block connection to https://meet.jit.si
4) user has i2pd installed & run with outproxy enabled
5) user like to connect Ferdi messenger to https://meet.jit.si through i2pd to bypass firewall block

How we can achieve above scenario ?

------------

Note: Ferdi messenger is available on:
https://getferdi.com/
https://github.com/getferdi/ferdi

**Comment by Nokia808** [comment]
Dears please notice that, currently, Jitsi can not run from within Ferdi due to a bug that will be fixed in near future - see:
https://github.com/getferdi/recipes/issues/141
https://github.com/getferdi/recipes/pull/167

So, let we consider other example from within Ferdi, let to say: Telegram

**Comment by r4sas** [comment]
Telegram can be used via MTProxy. See https://t.me/i2p_telegram and http://telegram.i2p.
@orignal, me, and one more user running MTProxy available over I2P. In that case you can use client tunnels pointed to them.

**Comment by Nokia808** [comment]
@r4sas 
This is not related to this question ! I did not used Telegram other than just example ! The question is about centralized chat/messenger that HAVE NO I2P SERVER.

To avoid confusion: let we considered Google Meet service. It is centralized & it's server(s) all are on clear net & have no i2p server(s). I like to use i2p to bypass block on Google meet. How can I do this? This is the question in this issue ...

**Comment by majestrate** [comment]
On Mon, May 25, 2020 at 06:07:36AM -0700, Nokia808 wrote:
> @r4sas 
> This is not related to this question ! I did not used Telegram other than just example ! The question is about centralized chat/messenger that HAVE NO I2P SERVER.

you'll have to find an outproxy

> 
> To avoid confusion: let we considered Google Meet service. It is centralized & it's server(s) all are on clear net & have no i2p server(s). I like to use i2p to bypass block on Google meet. How can I do this? This is the question in this issue ... 

i2p is not tor, exits are optional.

**Comment by Nokia808** [comment]
@majestrate 
I know this. But at certain situation Tor network can be blocked itself & even Tor bridge can not help ! While i2p is too stronger than Tor though it's users are less ! For that I'm asked how to use i2p (with outproxy enabled by user) to bypass a firewall block on centralized chat/messenger service that has it's servers all on clear net. My I ask again how this could be done ?

1) what address should be used ? I suspect 127.0.0.1 also, but I'm not sure,
2) what port should I use ?
3) do I need to create new tunnel or not ?  If yes, then what type of tunnel & what are it's parameters?

These are not difficult questions on you, but to me it is difficult because I'm not system admin but only user like to use i2p instead VPN as much as possible. As you are already help me with Retroshare which I was not know how to set it till few days ago, I would like to know how to use i2p to overcome block on centralized chat/messenger service, let we say Google Meet accessed by Ferdi which allow user to set a proxy for each chat/messenger service .... That is all !

**Comment by Nokia808** [comment]
I found this link on Internet:
https://i2p.rocks/blog/anonymous-instant-messaging-with-end-to-end-encryption.html

It deal with different thing (deal with chat WITHIN i2p) like Telegram utilizing an ((i2p's Telegram server)) .....

However, it seem that to utilize i2p for centralized chat/messenger that using server on clearnet, all what we need is:

1) enable outproxy,
2) set the following in proxy setting of chat/messenger application:
- proxy type: SOCKS 5
- address: 127.0.0.1
- port: 4444

But what about HTTP proxy type ? Can we using it as ?:
- proxy type: HTTP
- address: 127.0.0.1
- port: 4447

**Comment by r4sas** [comment]
You messed everything, SOCKS5 uses 4447, HTTP uses 4444.

**Comment by Nokia808** [comment]
@r4sas 
Okay, I correct them. It was a typing mistake because this topic cause me headache !
Just inform me: which I should used for Google Meet ? HTTP or SOCKS 5 ?

**Comment by orignal** [comment]
You shouldn't use I2P for this purpose at all

**Comment by Nokia808** [comment]
@orignal 
Okay, but just explained to me why ? I like to learn. You are already learn me too much & I'm thankful to you. 
Just explain to me why, so as to close this issue after I understand why.

**Comment by orignal** [comment]
Because somebody has to provide a gateway or proxy for an access from I2P

**Comment by Nokia808** [comment]
@orignal 
You mean hacker/spying outproxy ? I know this risk. It is also existing with Tor network. But it has no value as long as you are already using OpenPGP or other form of end-to-end encryption. Jitsi already implement this feature (e2ee) - see:
https://jitsi.org/blog/e2ee/

**Comment by orignal** [comment]
I mean I2P is not Tor and doesn't have an access to clearnet. Therefore somebody must provide it like we do for Telegram. That what you should start from.

**Comment by Nokia808** [comment]
@orignal 
Dear why you did not inform me directly from beginning that outproxies for i2p currently only 3 types: HTTP, HTTPS, & email & no one of them support chat/messenger applications ? If you inform me from start, I was not rotating around this topic all this time ......

I searched Internet & read FAQ of i2p official page, & reached to following result: outproxy option in i2p is currently only set to HTTP proxy to used to BROWS clear net sites (not for chat/messenger applications). At other place it say: "currently 3 types available: HTTP, HTTPS, & email ......

Thank you for being patient with me all this time, but kindly next time be more direct with me in answers & from start cut the path if I'm in the wrong way .....

Issue is closed with following result: "regarding chat/messenger application, whether central or serverless i2p network is suitable ONLY to run such application HIDDEN INSIDE IT but not to connect such applications to clear net. Currently we Retroshare is ideal for this job & for future Jami has excellent position from this regard but unfortunately not implemented yet."

Recommendation: I would like to ask developers team of i2pd to give from them time a space to develop patches & PR for Jami to make it able to run completely hidden inside i2p like Retroshare .....

**Comment by orignal** [comment]
You don't need to set proxy, you need to set **tunnel** connected to a proxy of particular  network.
For example for telegram we set regular server tunnel connected to mtproxy's port.
