### ISSUE TITLE
flatpak i2pd broken

### ISSUE THREAD

**Issue by pragmatic-strain** [PurpleI2P/i2pd#1523]
```
<catalyst> сломали блять флатпаковую прогу
<catalyst> абдейтнулась и крашится на старте грит не приемлю ваши вебсокеты
<catalyst> i2pd_qt flatpak
<orignal> так уже поправили вроде
<catalyst> ну флатпак реп то старый не поправленный
<orignal> ну
```

**Comment by Nokia808** [comment]
Please please write in English ! This is international forum ! How we can understand you !

From the title I suspect that you have same issue here:
https://github.com/flathub/website.i2pd.i2pd/issues/8

**Comment by r4sas** [comment]
That's copypaste from IRC, he wouldn't translate that just for issue.

**Comment by r4sas** [comment]
Flatpack package with fix built and published.

**Comment by Nokia808** [comment]
@r4sas 
What I have to do now ?? A new attach of incompatibility now because I'm already delete websockets block yesterday ??

**Comment by r4sas** [comment]
> Will I suffer from a new attack of incompatibility now because I'm already delete websocket block yesterday ??

No.

**Comment by Nokia808** [comment]
@r4sas 
Are you re-establish the websocket options back or you merely correct the build ??

**Comment by r4sas** [comment]
I added them back, but they will not do anything in i2pd itself, just for compatibility with old users configuration.
