### ISSUE TITLE
Add "maximize" icon at upper right corner of GUI !

### ISSUE THREAD

**Issue by Nokia808** [PurpleI2P/i2pd#1524]
Hi. when I updated to current version I noticed that at right upper corner of GUI only - x icons but no maximize icon which should be between - & x icons. 

I installed i2pd from FlatHub.

Thanks.

**Comment by nonlinear-chaos-order-etc-etal** [comment]
There was never a maximize button there. This is planned for distant future.

**Comment by Nokia808** [comment]
@nonlinear-chaos-order-etc-etal 
Why for DISTANT future !! If i2p to become famous among users of i2p network & if it to become used by them instead of java version, then you need to improve GUI beside developing daemon ...

**Comment by nonlinear-chaos-order-etc-etal** [comment]
@Nokia808 if users of i2p network feed me with food and other stuff, i would develop it fulltime

**Comment by nonlinear-chaos-order-etc-etal** [comment]
@Nokia808 I receive ZERO donations

**Comment by Nokia808** [comment]
@nonlinear-chaos-order-etc-etal 
How it cost for fully development GUI ?

**Comment by nonlinear-chaos-order-etc-etal** [comment]
@Nokia808 there are a lot of subprojects I can help with as I am multi-field specialist - I can do qt, android gui, flutter cross-platform gui (flutter allows for android, ios, desktops - windows, macos, linux, also web ui), various side-i2p apps (torrents, bote, and many others), i2pchat (current version and future generations of app), etc. At Russia, I can easily live at as low as about 600 USD/mo. But I do not know whether fund raisers could be successful for i2pd ecosystem. And I do not know whether are there points of growth for investors.

**Comment by Nokia808** [comment]
@nonlinear-chaos-order-etc-etal 
Your statement:

> "But I do not know whether fund raisers could be successful for i2pd ecosystem. And I do not know whether are there points of growth for investors." 

is really really really surprising !!! Who will donate you when you saying such ??!! I'm myself was ready to donate, but when I read this statement I changed my mind !! Look for this post by me:
https://gitlab.com/scarpetta/pdfmixtool/-/issues/36

I was really thinking to donate you, but with this statement neither me nor any one will donate you !! Really surprising !!

**Comment by nonlinear-chaos-order-etc-etal** [comment]
@Nokia808 Well I don't think I want to set up any donation infrastructure just to collect 1.5 USD the community will give. This doesn't pay for efforts. Donations don't work for software development project as they work for Twitch et al.

**Comment by nonlinear-chaos-order-etc-etal** [comment]
@Nokia808 Iraq people and many other people in the world, including my Russia, are tired of stupid state regulations and so normal non-technical people *NEED* normal GUI software, not just console daemons with complex configuration. I understand this. And I am ready to build software to make things easier for non-tech people, that's why I started the GUI QT project, and why I started the Android project. These are not perfect programs as are some other programs/ecosystems in the world. But steps can be done to simplify the use without compromising privacy.

Another question is "who are ready to pay for development of privacy software". There are not many I guess. And if you look at i2pd's bitcoin wallet - it haven't received quantities more than very small bits.

And doing a full-fleged business with advertising which is like Facebook-for-privacy, or VK-for-privacy, or Telegram-with-ads - is on a criminal side of state regulations in my Russia, so I wouldn't want to start such a business.

Not much can be done with the "underground" software area I think.

**Comment by nonlinear-chaos-order-etc-etal** [comment]
@Nokia808 so I think underground software can only be funded by black market. And I prefer to be lawful...

**Comment by nonlinear-chaos-order-etc-etal** [comment]
@Nokia808 There are also countries where this kind of software is not criminal. You need to seek for people at these to develop this...

**Comment by Nokia808** [comment]
@nonlinear-chaos-order-etc-etal 
No one like any think "underground" or "illegal" at all. i2p is legal software in Iraq as in USA & Switzerland. Regarding Russia I do not know what it's laws saying regarding i2p, but if i2p illegal in Russia then all what I can say to you will be: "my heart is in pain for you & all Russian peoples ..."

Personally, I have no thing underground, but I used i2p (via i2pd) instead VPN. Before becoming Linuxer & learn about i2p, qTox, Jami, OpenPGP, .... I was pay for VPN 270 Euro per year to encrypt my connection so as to protect my Internet communication when sending Academic questions for my college when I working as Academic lecturer because I'm very afraid from being stolen by my ISP..... When I discovered i2p, Tor I found that I can replace VPN by such projects if I use with them OpenPGP ..... Indeed my use for VPN decline greatly so that I'm now paying for VPN only monthly (1 or 2 months per years no more) ...... For that I like to evolute GUI of i2pd .....

**Comment by nonlinear-chaos-order-etc-etal** [comment]
@Nokia808 Nice I will consider. Please do not expect quick progress though — however these features are mostly trivial to implement (except for maybe(?) outproxy enable/disable and (?) showing the chain of IPs). But indeed all of the stuff to consider to be done eventually.

**Comment by Nokia808** [comment]
@nonlinear-chaos-order-etc-etal 
I will change title of this issue to be fit with reality.

Also, I would like to say that issue #1326 if addressed it will help us to strength i2p network as with Tor network. These network will be better fighter as their user number increased. When users use to enable tor system package as a service by (sudo systemctl tor enable) so that it will run in background, she/he will help Tor network (please correct to me if I'm wrong).
Currently, enabling i2pd at start (to me from my Cinnamon DE start up applications) is annoying due to emergent of GUI at each launching process ..... Adding "Start to system try" option will fix this.

**Comment by nonlinear-chaos-order-etc-etal** [comment]
@Nokia808 To be fit with reality, pay 10 000 USD per feature, and you'll be happy. Good luck, and don't wash my brains.

**Comment by nonlinear-chaos-order-etc-etal** [comment]
@r4sas закрывай к хренам, нефиг этому иссую быть открытым. обойдутся.

**Comment by nonlinear-chaos-order-etc-etal** [comment]
@Nokia808 IF YOU'RE REALLY ACTUALLY A PROFESSOR, ASK YOUR STUDENTS TO DO PULL REQUESTS TO FIX YOUR ISSUES. I WON'T DO THIS DURING A LONG PERIOD OF MY TYME

**Comment by nonlinear-chaos-order-etc-etal** [comment]
@Nokia808 I am Jalaleddin RUMY and I am not waxxabit but IF THERE WILL BE A DANGER FOR BIOSPHERE AND ECOLOGY I WILL PUT QURAN AND RUMI ONTO THE DISTANT SHELF TO WAIT FOR BETTER TIMES THY `ME`S WITH HELP OF JAVA I2P AND I2PD AT WAR FOR EVERYONE'S `LIFE`

**Comment by nonlinear-chaos-order-etc-etal** [comment]
@Nokia808 and my TWO POEMS WITH FUTURE COMMON THIRD POEM got started to be recorded as GPLv3 repos here : https://github.com/EGYPTPHOENICKSVALLEYOFSPHINX and here : https://github.com/2boloto/hypnoaxolotl/commits?author=nonstigmatic-nonaristotelian-nonmath , THIRD ONE IS BEING THOUGH OUT ; IN WORKS

**Comment by nonlinear-chaos-order-etc-etal** [comment]
@Nokia808 AND THE THIRD POEM GETS RECORDED HERE https://github.com/THREEPOEMS/THIRDPOEM

**Comment by r4sas** [comment]
@nonlinear-chaos-order-etc-etal нафига капсить то?

**Comment by nonlinear-chaos-order-etc-etal** [comment]
@Nokia808 What can you pay to get a feature delivered in a top notch fashion? Please enumerate your answer for every feature you want.

**Comment by nonlinear-chaos-order-etc-etal** [comment]
@Nokia808 Maximize button feature is not so simple, it would take 1/2/3 months to implement.
