### ISSUE TITLE
[Questions] About some Firefox extensions

### ISSUE THREAD

**Issue by Nokia808** [PurpleI2P/i2pd#1526]
Hi dears. I have questions about some Firefox extensions & need you, kindly, to answer them. To avoid confusion, please to answer my concerns in points corresponding to the following:

1) i2psetproxy:
https://github.com/eyedeekay/I2P-in-Private-Browsing-Mode-Firefox
Do you recommend this add-on over FoxyProxy Standard ? Currently, I'm using FoxyProxy Standard.
I asked developer of i2psetproxy & said to me that his add-on compatible with i2pd but because i2pd has no plugins, many options (that intended for java i2p) will not work.

2) ClearURLs (officially recommended by Mozilla team):
https://gitlab.com/KevinRoebert/ClearUrls
Does this add-on give additional layer of security over i2p network ?

3) Cookie-AutoDelete: (officially recommended by Mozilla team)
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues

4) Privacy Badger: (officially recommended by Mozilla team)
https://github.com/EFForg/privacybadger
Also, does this extension add security layer of protection over i2p network, as already it doing on clear net ?

5) DNSSEC:
https://addons.mozilla.org/en-US/firefox/addon/dnssec/
Is it useful ? Does DNSSEC used over i2p network ?? I do not think so, & if it is supported then certainly there should be other than 2 Evils Cloud flare & Google to be used, something working from within (inside i2p) - what it(they) is(are) if any ??
This point (5) may extend over the topic of "DNSSEC FF add-on" .....

Thank you.

**Comment by r4sas** [comment]
1. You can use it without any worries, but if you didn't need all that functional foxyproxy is enough for you.
2. No.
3. I think better do not store them and drop on browser closing.
4. 50/50. No JS - no problems.

**Comment by Nokia808** [comment]
@r4sas 
Many thanks !
I will close this issue.

But only one thing need to clarify: you said regard point (1) "if you didn't need all that functional"
I understood from that as you said "if you did not using java version" because i2pd has no all that functions (has no plugins). Is this what you meant ?

**Comment by r4sas** [comment]
I about I2P browser tabs, bookmarks, router statistics (Java stuff), etc

**Comment by Nokia808** [comment]
This mean, in short, not to use i2psetproxy if you do not using the java version.
