### ISSUE TITLE
Dead code in void HTTPConnection::HandleWrite (const boost::system::error_code& ecode)

### ISSUE THREAD

**Issue by ygrishin** [PurpleI2P/i2pd#153]
Looks like this function never gets called. Does anybody know why it's there?

**Comment by orignal** [comment]
Try to download something big.

void HTTPConnection::HandleStreamReceive (const boost::system::error_code& ecode, std::size_t bytes_transferred)
	{
		if (!ecode)
		{
			boost::asio::async_write (*m_Socket, boost::asio::buffer (m_StreamBuffer, bytes_transferred),
        		boost::bind (&HTTPConnection::HandleWrite, this, boost::asio::placeholders::error));
		}

**Comment by ygrishin** [comment]
I did see the bind, was not able to trigger this anyway.

**Comment by ygrishin** [comment]
So I am somewhat back on track. Could you please provide exact steps on how to trigger this?

**Comment by orignal** [comment]
Try to download a file or page longer than 8192.
But since you are back can you take a look at this windows-specific issue https://github.com/PurpleI2P/i2pd/issues/192 ?

**Comment by ygrishin** [comment]
Will do.

**Comment by ygrishin** [comment]
It gets called indeed, was able to see it just now. Closing.
