### ISSUE TITLE
[Question] New Reseed server ready - some open questions

### ISSUE THREAD

**Issue by diva-exchange** [PurpleI2P/i2pd#1530]
We have set up a new reseed server at https://reseed.diva.exchange. It is set up as reverse proxy and the backend is the reseed server "i2p-tools", https://github.com/MDrollette/i2p-tools, written in Go. We reviewed the Go code.

There are a few questions related to this new reseed server:

a) we didn't see the point in checking the user agent string within the Go reseed server code. So we removed this user agent check. IMHO it's fine to get the i2pseeds.su3 using whatever client, like "wget https://reseed.diva.exchange/i2pseeds.su3", will simply work. The security of the server under management is handled differently and has nothing to do with the user agent string. Any opinions regarding that behavior? 

b) the reseed server runs on a letsencrypt cert. We didn't see the privacy point in a self-signed cert. So - how do you see that?

c) can we just submit a PR to add our public su3-CRT to this repo? And shall we also submit a PR to the Java I2P repo?

**Comment by r4sas** [comment]
Please read Java I2P documentation about reseeds: https://geti2p.net/en/get-involved/guides/reseed
a) Recommended to filtrate User-Agent due to possibility of DoS. Read docs above for more info.
b) We didn't require webserver certificate, only su3 signature cerificate required.
c) If you can provide stable service which will exisist for months - you're welcome. About adding - if you want, you can do it. Contact zzz@i2pmail.org because currently he manage JavaI2P reseeds now.

**Comment by diva-exchange** [comment]
Thanks a lot - this closes this question for us. We will submit our su3 CRT, talk to zzz and keep our instance stable and available.

Only a remark re DoS: IMHO the application-level "user agent check" does not really help. We believe that DoS protection should happen on infrastructure-level. We also need to test our instance properly.

**Comment by r4sas** [comment]
At DoS part also is rate limitting, not only user-agent check-up's...

**Comment by diva-exchange** [comment]
Yes - just saw a few moments ago that there is some rate limiting implemented in the Go code (referring to https://github.com/MDrollette/i2p-tools). But I also believe (just my opinion) that rate limiting belongs to the infrastructure-level. We handle the reseed rate limiting currently with nginx... but there might be different views and solutions.

**Comment by orignal** [comment]
>  It is set up as reverse proxy and the backend is the reseed server "i2p-tools", https://github.com/MDrollette/i2p-tools, written in Go.

AFAIK, it's gone for a long time

**Comment by r4sas** [comment]
I'm using [pyseeder](https://github.com/PurpleI2P/pyseeder) for creating reseed file and nginx+php-fpm for serving with a bit protection. Also it uploads reseed file [here](https://github.com/r4sas/i2pd-reseed/releases/tag/1.0).

**Comment by eyedeekay** [comment]
To my knowledge MDrollette's is no longer developed, but it's also not broken in any way that I am aware of. I have an active fork of it here: https://github.com/eyedeekay/i2p-tools-1. It has some features the other one does not, pertinent to @diva-exchange question, it does this: https://reseed.i2pgit.org/ when the user-agent doesn't match the one it expects. I'm happy to hear feature suggestions and help support for that reseed software. If you choose to use the Go reseed software, I'm able to support it there.

**Comment by diva-exchange** [comment]
Thank you very much for the feedback and that you share your experience! Since yesterday morning we're live and stable with https://reseed.diva.exchange/ . Yesterday we have been running quite some security tests and audits on reseed.diva.exchange. We have messaged "zzz" (cert and contact info) and we also would be fine with updating the source code/configs (C++, java) by ourselves as PR to i2pd and i2p.

All code we use is fully published on https://codeberg.org/diva.exchange/i2p-reseed . We use an exposed network edge infrastructure (which is reseed.diva.exchange) and a very well protected backend where the Go code is located (see codeberg repo) and which delivers the i2pseeds.su3. Currently, we feel comfortable with the Go code. We will see during the next weeks, months and years whether and how it will be attacked and to implement improvements.

**Comment by orignal** [comment]
Also, FYI, i2pd  reseed doesn't check https ceritficates at all, it only checks SU3.
About that Go reseed, I remember few years ago they have some issue with RSA padding, so I had to add some hack to my signature verification code

**Comment by diva-exchange** [comment]
Hmm, very, very interesting. Do you recommend to switch our reseed backend to the python version? What can we do to help testing the stability and reliability of a reseed instance? 

We reviewed the Go code (although we're not Go pros) - and we felt that the code is fine. But if it produces some RSA padding issues... we would never have spotted that. Then we removed a dependency (throttling) and re-published the code on codeberg. Now that's what we have in prod.

**Comment by orignal** [comment]
Look at this line
https://github.com/PurpleI2P/i2pd/blob/openssl/libi2pd/Reseed.cpp#L239
Maybe it's fixed already, but I remember it was an issue with it in 2015. 
The only reseed server on Go was it's author's https://cowpuncher.drollette.com/netdb/ many years ago. All others use python.

**Comment by diva-exchange** [comment]
Thank you. So we will test like this:

1. we will configure several independent i2pd, v2.32.1, test instances with a single reseed server (reseed.diva.exchange).
2. we start them and look at the i2pd logs.
3. If the independent instances are properly bootstrapped - we're all good.

OK?

**Comment by orignal** [comment]
Current i2pd should work with both python and go

**Comment by r4sas** [comment]
Feel free to post new comments if any. Closing as answered.
