### ISSUE TITLE
Defining two server tunnels with same  key but different ports seems to define only one tunnel.

### ISSUE THREAD

**Issue by eaxillaris** [PurpleI2P/i2pd#1531]
When trying to configure two server tunnels with the same destination key file but different `port` values (e.g., for prosody), i2pd will pick up the first tunnel config it encounters but ignore the second unless `inport` is also set for each tunnel.  The inport need not even be different than port.

**Comment by r4sas** [comment]
Current logic make first added tunnel responsive at any I2P port (search for JavaI2P specs). For any other tunnel on same key you must manually set `inport` option.
`inport` can be different from `port`.
