### ISSUE TITLE
Sending SIGHUP to i2pd process makes client and server tunnels unusable.

### ISSUE THREAD

**Issue by eaxillaris** [PurpleI2P/i2pd#1532]
Sending signal HUP to a running i2pd process renders the client http proxy unusable, making it impossible to connect to eepsites without restarting i2pd. My webserver also becomes unreachable even though its destination key isn't supposed to change.
For completeness, the server tunnel config for my webserver:
```
[lighttpd]
type = http
host = 127.0.0.1
port = 8080
inport = 80
keys = lighttpd-keys.dat
```

**Comment by r4sas** [comment]
Known bug.
