### ISSUE TITLE
Too many open files error on OpenBSD

### ISSUE THREAD

**Issue by codesoap** [PurpleI2P/i2pd#1537]
I'm running i2pd version 2.26.0 (as available from the ports) on an OpenBSD 6.7 server. After a few minutes of running, `/var/lib/i2pd/i2pd.log` gets spammed with these messages:

```
11:07:05@353/error - HTTP Server: error handling accept Too many open files
```

I am no longer able to use the HTTP Proxy (I tried visiting zzz.i2p via browser; it just keeps loading forever). According to the web console, the server is still routing transit traffic successfully. I see, that this problem was discussed for Linux on #937 before, and I tried increasing the number of allowed opened files, but that does not seem to help. i2pd does not even have many open files, when the errors occur in the log:

```
$ sysctl kern.maxfiles kern.nfiles kern.maxproc kern.nprocs
kern.maxfiles=20000
kern.nfiles=252
kern.maxproc=1310
kern.nprocs=52
```

PS: The log is filled with the mentioned error message so rapidly, that it fills up my 6GiB `/var/` partition within a few hours or so.

**Comment by codesoap** [comment]
I just learned, that on OpenBSD there is also [login.conf](https://man.openbsd.org/login.conf.5), which regulates the resource limits for groups. I'll try to understand this and report back soon.

**Comment by r4sas** [comment]
We always recommended to increase `nofile` limit to 4096, because every connection uses file descriptors.

**Comment by codesoap** [comment]
I still have to test this longer, but it seems like the [login.conf](https://man.openbsd.org/login.conf.5) really was the problem. When installing the i2pd port on OpenBSD, the daemon will be run by a user `_i2pd`. His userinfo is:

```
$ userinfo _i2pd
login   _i2pd
passwd  *
uid     838
groups  _i2pd
change  NEVER
class   daemon
gecos   i2pd account
dir     /var/lib/i2pd
shell   /sbin/nologin
expire  NEVER
```

The problematic part here is `class   daemon`, because this login-class is restricted to `openfiles-cur=128` and `openfiles-max=1024`. I thus created a new class for i2pd at the end of `/etc/login.conf`:

```
i2pd:\
        :openfiles=4096:\
        :tc=daemon:
```

Then I changed the class of the `_i2pd` user with `usermod -L i2pd _i2pd`.

**Comment by codesoap** [comment]
Now there is a README on the port, which could have prevented this ticket: https://github.com/openbsd/ports/commit/ac2eb4ed0c5d2ac8681350399232d50acc10e7ba
