### ISSUE TITLE
Warning during installation (adduser)

### ISSUE THREAD

**Issue by Xrum-xrum** [PurpleI2P/i2pd#1547]
Debian 10 (Buster)

$ sudo apt-get install i2pd
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libboost-program-options1.67.0
The following NEW packages will be installed:
  i2pd libboost-program-options1.67.0
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 1,259 kB of archives.
After this operation, 5,652 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://deb.debian.org/debian buster/main amd64 libboost-program-options1.67.0 amd64 1.67.0-13+deb10u1 [357 kB]
Get:2 https://repo.i2pd.xyz/debian buster/main amd64 i2pd amd64 2.32.1-1buster1 [902 kB]              
Fetched 1,259 kB in 1s (944 kB/s)                                                                     
Selecting previously unselected package libboost-program-options1.67.0:amd64.
(Reading database ... 207945 files and directories currently installed.)
Preparing to unpack .../libboost-program-options1.67.0_1.67.0-13+deb10u1_amd64.deb ...
Unpacking libboost-program-options1.67.0:amd64 (1.67.0-13+deb10u1) ...
Selecting previously unselected package i2pd.
Preparing to unpack .../i2pd_2.32.1-1buster1_amd64.deb ...
Unpacking i2pd (2.32.1-1buster1) ...
Setting up libboost-program-options1.67.0:amd64 (1.67.0-13+deb10u1) ...
Setting up i2pd (2.32.1-1buster1) ...
adduser: Warning: The home directory `/var/lib/i2pd' does not belong to the user you are currently creating.

**Comment by LLE8** [comment]
IMHO Not a bug
https://github.com/PurpleI2P/i2pd/issues/1275#issuecomment-444891998
