### ISSUE TITLE
wtf hole in firefox? i haven't read this yet

### ISSUE THREAD

**Issue by nonlinear-chaos-order-etc-etal** [PurpleI2P/i2pd#1548]
"An Awful 3 years unfixed Mozilla Firefox vulnerability. And mozilla refuses to fix it. Tor Browser also affected."
https://mastodon.technology/@whonix/103051379003106812

**Comment by nonlinear-chaos-order-etc-etal** [comment]
please close if you think it's rubbish report

**Comment by r4sas** [comment]
Ничего интересного, обычный сквоттинг через punny code с заменой латиницы на схожие символы.
