### ISSUE TITLE
Log flooded with `Too many open files`

### ISSUE THREAD

**Issue by yangfl** [PurpleI2P/i2pd#1549]
I ran a 24/7 i2pd server along with other services. Recently I found the / is out of space and it turns out that `/var/log/i2pd/i2pd.log` is flooded with
```
17:50:11@33/error - NTCP2: Accept error Too many open files
17:50:11@33/error - NTCP2: Accept error Too many open files
17:50:11@33/error - NTCP2: Accept error Too many open files
17:50:11@33/error - NTCP2: Accept error Too many open files
17:50:11@33/error - NTCP2: Accept error Too many open files
17:50:11@33/error - NTCP2: Accept error Too many open files
17:50:11@33/error - NTCP2: Accept error Too many open files
17:50:11@33/error - NTCP2: Accept error Too many open files
17:50:11@33/error - NTCP2: Accept error Too many open files
```
and that takes ~9G to store such thing. Maybe there should be a mechanism to prevent log flooding.

**Comment by LLE8** [comment]
show `prlimit --pid <pid_of_i2pd> `

maybe reconfigure  logrotate?

**Comment by r4sas** [comment]
> maybe reconfigure logrotate?

It's different, about logging.

**Comment by vshuraeff** [comment]
even if `ulimit -n 131072` set, error `17:17:05@442/error - NTCP2: Runtime exception: open: Too many open files [system:24]` still appear

**Comment by r4sas** [comment]
Are you starting with systemd?

**Comment by felix** [comment]
This occurs for me on OpenBSD too, so not necessarily systemd related:

```shell
$ uname -a
OpenBSD xxx 7.1 GENERIC.MP#465 amd64
$ pkg_info |grep i2pd
i2pd-2.41.0         client for the I2P anonymous network
```

It does not seem to make a difference the openfiles limit either:
```shell
$ cat /etc/login.conf.d/i2pd.conf
i2pd:\
        :openfiles=4096:
```

**Comment by vazhnov** [comment]
I had the same problem with flooding logs with "Accept error Too many open files".
i2pd version 2.44.0 in Devuan 4 Chimaera (based on Debian 11 Bullseye).

Fix: edit `/etc/default/i2pd`, default value is:
```sh
# If you have problems with hunging i2pd, you can try enable this
ulimit -n 4096
```
Increase the value.
Then restart the service: `sudo service i2pd restart`.

**Comment by r4sas** [comment]
https://github.com/PurpleI2P/i2pd/commit/737603e81b9b33b1b25fb4a501930dcfffb50016 + https://github.com/PurpleI2P/i2pd/commit/857df5c7341353e8b18af812829797c4da3ccb84

**Comment by Sfinx** [comment]
Same here with v2.51.0 (0.9.62):

```
09:31:14@451/error - NTCP2: Accept error Too many open files
09:31:14@451/error - NTCP2: Runtime exception: open: Too many open files
09:31:15@70/error - Profiling: /var/lib/i2pd/peerProfiles/pA/profile-AllCBRjr~zbhlZBdfN7VDWYYX~ixygYkwu9uK~SSRcY=.txt: cannot open file
09:31:15@451/error - NTCP2: Runtime exception: open: Too many open files
09:31:15@81/error - Profiling: /var/lib/i2pd/peerProfiles/pj/profile-j1H4BuYIj0CgirXPJfgmZJb4S0Rl~YYnLoKqgCYo2LY=.txt: cannot open file
09:31:15@81/error - Profiling: /var/lib/i2pd/peerProfiles/pw/profile-w253t9Kn4dvSBY9ijp30n6yMvRgjr~fmmx9eV72cFOA=.txt: cannot open file
```

/lib/systemd/system/i2pd.service:

```
[Service]
User=i2pd
Group=i2pd
...
LimitNOFILE=infinity
```

I guess this is the file descriptor leak

**Comment by Vort** [comment]
I doubt Linux do what you ask.
Probably there are some additional limit somewhere (`nr_open`?).
And there are lots of files in `peerProfiles` because of attack, so error messages make sense.

**Comment by Sfinx** [comment]
It is not Linux but systemd - you are right, this is really stupid daemon. Forgot about attack
