### ISSUE TITLE
HTTPS Outproxy

### ISSUE THREAD

**Issue by gitbugged** [PurpleI2P/i2pd#1552]
I know it's possible to setup and use an [[httpproxy] outproxy](https://github.com/PurpleI2P/i2pd/issues/1505#issuecomment-633234756), but there appears to be no [httpsproxy]. On the modern web that's fairly useless since everything is using TLS. Java I2P implements this as port 4445.

As an alternative using socks5 with an outproxy (besides Tor) would be useful as well. Such as a b32 address, similar to http proxy.

**Comment by majestrate** [comment]
i THINK that the http outproxy does http connect. unless it doesn't i forget it has been a very long time since i looked at that code.

**Comment by gitbugged** [comment]
Perhaps I set it up wrong, but I am only able to browse HTTP websites. I get `«The proxy server is refusing connections»` when using HTTPS.

Based on this tutorial: https://i2p.rocks/blog/hosting-an-outproxy-for-i2p-part-1.html

**Comment by r4sas** [comment]
4444 has CONNECT support and works without issues. Please reheck your serverside tunnel for `inport` option along with tunnels without it. Requests mapping order between ports on same destination is firstly to first tunnelfor any port, then to tunnels with inport.

```
[HTTP]
type = http
host = 127.0.0.1
port = 8000
inport = 80 # will process request to any port
gzip = false
keys = webserver.dat

[HTTPS]
type = server # here must be server type because this is not plain connection!
host = 127.0.0.1
port = 8443
inport = 443
gzip = false
keys = webserver.dat
```

**Comment by gitbugged** [comment]
I can confirm the outproxy on the server itself is capable of using HTTPS (running tinyproxy).
However I am still unable to get client-side working. 

On server side I have /etc/i2pd/tunnels.conf:
```
[outproxy]
type=server
host=127.0.01
port=8888 # Tinyproxy running here (supports HTTPS, verified working)
keys=outproxy.dat
signaturetype=7
inbound.length=1
outbound.length=1
```

I have in my client's i2pd.conf:
```
[httpproxy]
outproxy = xxx.b32.i2p:8888 # HTTPS capable Proxy server running on this remote port
address = 127.0.0.1
port = 4444
```

When using Port 4444 as an HTTPS Proxy it fails.
```
export http_proxy=http://127.0.0.1:4444
export https_proxy=http://127.0.0.1:4444
curl -v https://ipchicken.com
* Uses proxy env variable https_proxy == 'http://127.0.0.1:4444'
*   Trying 127.0.0.1:4444...
* Connected to 127.0.0.1 (127.0.0.1) port 4444 (#0)
* Closing connection 0
curl: (56) Received HTTP code 500 from proxy after CONNECT
```

I imagine it could be done something like:
```
[httpsproxy]
outproxy = xxx.b32.i2p:8888 # HTTPS capable Proxy server running on this remote port
address = 127.0.0.1
port = 4445
```

Then we could use `export https_proxy=http://127.0.0.1:4445` to pass to curl.
Open to suggestions if there is another way.

**Comment by majestrate** [comment]
i am pretty sure that the explicit port on the client side outproxy isn't needed

**Comment by gitbugged** [comment]
Thanks! Also now it started working on port 4444 with HTTPS all of a sudden. Very odd, but ... all good. :+1:
Closing. Bad config. Also there were some additional ports on tinyproxy to enable (443 + 563).

**Comment by majestrate** [comment]
I remember now:

on client side it's something like:

outproxy=http://xxx.b32.i2p/

**Comment by gitbugged** [comment]
A bit off-topic, but I don't suppose it's possible to make this work with socksproxy from client side? Socks5 works everywhere, a bit more convenient than http proxies.

**Comment by majestrate** [comment]
socks support exists but is buggy
