### ISSUE TITLE
i2pd core dump with irc

### ISSUE THREAD

**Issue by Strykar** [PurpleI2P/i2pd#1554]
I'm running version 2.33.0 on Arch Linux, kernel 5.8.10 and often, when my IRC client tries to connect (it starts at login), i2pd core dumps.
I can reproduce the issue, which does not occur if the IRC client connects to i2pd after a few minutes of it starting and establishing tunnels.
```
Sep 24 05:14:03 i5 systemd[1]: i2pd.service: Main process exited, code=dumped, status=3/QUIT
Sep 24 05:14:03 i5 systemd[1]: i2pd.service: Failed with result 'core-dump'.
```
Dump seems incomplete, it's just 320 Kb, or I might need to rebuild i2pd with symbols  - https://drive.google.com/file/d/1KymHNasYOpvdYwAT2LcflgNDV6t9BjVY/view?usp=sharing

I'm happy to get a proper dump if there's interest.

**Comment by r4sas** [comment]
Hello. Yes, getting full coredump would be better for solving problem.

Also you must try open it using gdb on your system because coredumps linked to local versions of libraries.

**Comment by r4sas** [comment]
t/o
