### ISSUE TITLE
Enable "outproxy" option from GUI seem to suffer from bug ??

### ISSUE THREAD

**Issue by Nokia808** [PurpleI2P/i2pd#1569]
Hi. I installed last version from FlatHub which has GUI to enable outproxy. I used this new option as following:
1) launched i2pd,
2) general setting,
3) dictated http://false.i2p within the field for that under "HTTP Proxy" section,
4) check "Outproxy enabled" under "Socks Proxy" section,
5) exit application,
6) re-launching application

But since morning till now & I can not visit any free net site ! I'm still able to visit i2p sites but when I try to visit free net site only a white screen appearing & browser continue in "waiting" state for several minutes then display to me "time out ....." message!

When I checked GUI, the enabling of outproxy is still okay & http://false.i2p still in it's field .....

Is this a bug in new option or it is related to http://false.i2p address specifically ?

I tested issue at morning when Internet speed is fast.

Best.

**Comment by r4sas** [comment]
false.i2p can be overloaded, so we can't do anything in that case. Try use any other outproxy.

**Comment by Nokia808** [comment]
@r4sas 
So, it is not a bug in your application. Okay, I will close this issue.
If you can give me a link to know other outproxy, I will be thankful to you ....
