### ISSUE TITLE
AESNI/AVX compile time check

### ISSUE THREAD

**Issue by bol-van** [PurpleI2P/i2pd#1571]
Why do you check for presense of cpu extensions at compile time ?
Binaries are not necessary intended to run on the same device or can be cross-compiled
Runtime checks exist in the code, no need in compile-time checking

```
ifeq ($(USE_AESNI),yes)
#check if AES-NI is supported by CPU
ifneq ($(shell $(GREP) -c aes /proc/cpuinfo),0)
	machine := $(shell uname -m)
	ifeq ($(machine), aarch64)
		CXXFLAGS += -DARM64AES
	else
		CPU_FLAGS += -maes
	endif
endif
endif
```

**Comment by r4sas** [comment]
That can make too much problems, like this: https://github.com/PurpleI2P/i2pd/issues/1335

**Comment by bol-van** [comment]
Да, будет coredump из-за -mavx, это я знаю. Это происходит потому, что компилятор использует команды avx для создания кода из C/C++.  Команды AES не используются, поэтому -maes не вызывает коредампа
Что сделано сейчас, разве это решение ?

Я компилю i2pd на системе с поддержкой avx, переношу на систему без avx, получаю тот же самый core dump
Я компилю i2pd на системе без avx, переношу на систему с avx, получаю неработающий avx

Не надо включать опции компилятора -mavx и -maes.
Нужно сделать так, как это сделано в openssl. Создаются куски кода внешним ассемблером , вкомпиливаются в EXEшник, вызываются в зависимости от наличия инструкций на текущей системе

**Comment by r4sas** [comment]
Понятное дело что надо, только ни кто не хочет этим заниматься...

**Comment by bol-van** [comment]
Я смотрю там переписаны криптографические примитивы вроде AESEncrypt. 
Зачем было велосипед изобретать ? Почему бы не вызывать openssl ?
Не напрямую AESEncrypt, которые без AESNI, а через evp

```
openssl speed aes-128-cbc
Doing aes-128 cbc for 3s on 16 size blocks: 19668376 aes-128 cbc's in 2.84s
openssl speed -evp aes-128-cbc
Doing aes-128-cbc for 3s on 16 size blocks: 61338539 aes-128-cbc's in 2.91s

```

**Comment by r4sas** [comment]
```
12:41:32 <~orignal> все дело в тоннелях
12:41:59 <~orignal> я не виноват что jrandom сначала шифрует IV затем данные затем снова IV
12:42:12 <~orignal> AVX это проблема HMAC
12:42:17 <~orignal> он в I2P кривой
```

**Comment by bol-van** [comment]
Не думаю, что -mavx сам по себе даст что-то серьезное в плане производительности
На нее влияют обычно критические участки кода, в которых в основном проводится процессорное время
Если принять за такие фрагменты, написанные на встроенном ассемблере, то для их компиляции не нужно -maes (проверил).

Потому, малой кровью можно заменить дефайны с __AVX__, __AES__ на что-то свое, не связанное с опциями компилятора -mavx и -maes, компилировать код все время без них. Рантайм проверки в коде уже есть, они активируют ассемблерный код. При этом не забыть подумать что будет при сборке под другую архитектуру, например arm или mips

**Comment by r4sas** [comment]
https://gcc.gnu.org/onlinedocs/gcc-6.1.0/gcc/x86-Options.html
>GCC depresses SSEx instructions when -mavx is used. Instead, it generates new AVX instructions or AVX equivalence for all SSEx instructions when needed.

>These options enable GCC to use these extended instructions in generated code, even without -mfpmath=sse. Applications that perform run-time CPU detection must compile separate files for each supported architecture, using the appropriate flags. In particular, the file containing the CPU detection code should be compiled without these options.

**Comment by bol-van** [comment]
Можно провести бенчмарки на типичных задачах. Понять что это вообще дает, если дает
с выключенным ассемблером, но с -mavx, и без него
стоит ли вообще заморачиваться

**Comment by r4sas** [comment]
Надо протестировать сборку для arm: https://github.com/PurpleI2P/i2pd/commit/7651871cd6765c97b7e4a20d316b273ee281092a

**Comment by LLE8** [comment]
не бенчмарк с точными количественными результатами, но наблюдение
https://github.com/PurpleI2P/i2pd/issues/880#issuecomment-478258505

**Comment by bol-van** [comment]
> не бенчмарк с точными количественными результатами, но наблюдение
> [#880 (comment)](https://github.com/PurpleI2P/i2pd/issues/880#issuecomment-478258505)

perf-ом надо профилировать
в perf top-е четко виден aes_encrypt, жрущий какой-то ощутимый процент. с aes другие процедуры, нет такого четкого выделения.
но кроме aes там много другого видно. надо бы разобраться что там больше всего кушает

мое наблюдение - на 500-600 кб/с транзита i2pd жрет около 15% ядра не самого паршивого ксеона
разница с aes и без не очень ощутима. но может несколько процентов выигрывается

**Comment by bol-van** [comment]
> Надо протестировать сборку для arm: [7651871](https://github.com/PurpleI2P/i2pd/commit/7651871cd6765c97b7e4a20d316b273ee281092a)

sudo apt-get install g++-arm-linux-gnueabihf

CXX=arm-linux-gnueabihf-g++ make
arm-linux-gnueabihf-g++: error: unrecognized command line option ‘-maes’

**Comment by LLE8** [comment]
Orignal  там же чуть ниже предположил, что openssl "сам внутри распознает",
и похоже, что еще с версии 1.0.2  https://www.openssl.org/docs/man1.0.2/man3/OPENSSL_ia32cap.html

**Comment by bol-van** [comment]
> ignal там же чуть ниже предположил, что openssl "сам внутри распознает",

он распознает, но не везде. есть низкоуровневые процедуры типа AES_Encrypt, в которых нет распознавалки

**Comment by r4sas** [comment]
> > Надо протестировать сборку для arm: [7651871](https://github.com/PurpleI2P/i2pd/commit/7651871cd6765c97b7e4a20d316b273ee281092a)
> 
> sudo apt-get install g++-arm-linux-gnueabihf
> 
> CXX=arm-linux-gnueabihf-g++ make
> arm-linux-gnueabihf-g++: error: unrecognized command line option ‘-maes’

я сейчас тестирую сборку на малине, правки по ходу движения делаю. Но кросскоспиляция всегда такое будет творить... надо как то вычислять целевую систему а не текущую.

**Comment by bol-van** [comment]
> надо как то вычислять целевую систему а не текущую.

https://sourceforge.net/p/predef/wiki/Architectures/

**Comment by r4sas** [comment]
> https://sourceforge.net/p/predef/wiki/Architectures/

имеется в виду в make...

**Comment by bol-van** [comment]
> Так наверно не делается

Зачем вообще нужен -maes ? На доступность команд в inline asm это не влияет

**Comment by r4sas** [comment]
Как пример...
```
g++ -Os -Wall -Wextra -Wno-unused-parameter -pedantic -Wno-misleading-indentation -Wno-psabi -DUSE_UPNP -DARM64AES -D__AES__ -std=c++11 -fPIC -Ilibi2pd -Ilibi2pd_client   -c -o obj/libi2pd/Crypto.o libi2pd/Crypto.cpp
libi2pd/Crypto.cpp: In member function ‘void i2p::crypto::ECBCryptoAESNI::ExpandKey(const AESKey&)’:
libi2pd/Crypto.cpp:769:4: error: unknown register name ‘%xmm4’ in ‘asm’
   );
    ^
libi2pd/Crypto.cpp:769:4: error: unknown register name ‘%xmm3’ in ‘asm’
libi2pd/Crypto.cpp:769:4: error: unknown register name ‘%xmm2’ in ‘asm’
libi2pd/Crypto.cpp:769:4: error: unknown register name ‘%xmm1’ in ‘asm’
libi2pd/Crypto.cpp: In member function ‘void i2p::crypto::ECBEncryption::Encrypt(const i2p::crypto::ChipherBlock*, i2p::crypto::ChipherBlock*)’:
libi2pd/Crypto.cpp:804:7: error: unknown register name ‘%xmm0’ in ‘asm’
      );
       ^
...
```

**Comment by bol-van** [comment]
> error: unknown register name ‘%xmm3’ in ‘asm’

На arm нет и не может быть xmm регистров
ассемблер нужно вносить в блоки #ifdef от архитектуры
нельзя дефайнить __AES__ на не-x86, если  потом по нему будет компилиться x86 ассемблер

**Comment by r4sas** [comment]
> > Так наверно не делается
> 
> Зачем вообще нужен -maes ? На доступность команд в inline asm это не влияет

Винда так не думает...
```
Thread 39 received signal SIGSEGV, Segmentation fault.
0x0000000000428965 in i2p::crypto::ECBCryptoAESNI::ExpandKey (this=0xb594848,
    key=...) at libi2pd/Crypto.cpp:726
726                     __asm__
```

**Comment by r4sas** [comment]
Просьба испытать код из https://github.com/PurpleI2P/i2pd/tree/avx.

**Comment by bol-van** [comment]
> Это модифицированный код без **AES** и -maes с проверкой только на x86.

-maes не влияет на возможность компилировать aesni инструкции во встроенном асме. естественно, при их выполнении на несовместимом проце будет invalid opcode
надо смотреть почему i2p::cpu::aesni был выставлен.

**Comment by bol-van** [comment]
> Просьба испытать код из https://github.com/PurpleI2P/i2pd/tree/avx.

в qemu на vps-ке с отключенными экстенжинами работает
avx и aes не детектит, по --loglevel info   сообщений enabled нет
если поменять в коде на принудительный детект aes - тоже работает

на этой VPSке реально aes работает, avx вызывает падения
для openssl есть способ принудить детекшин aes через переменную OPENSSL_ia32cap
было бы здорово добавить свой оверрайд для i2pd. например, через настройку в конфиге
есть много хостеров, которые ни в какую не желают в qemu включать "-cpu host" без объяснения причин, приходится извращаться

**Comment by r4sas** [comment]
> на несовместимом проце будет invalid opcode

Не знаю, но ведь эти опкоды надо перевести в байты для исполнения процессором. А если компилятор не знает, то как он преобразует то их? Этот вывод корки выше был получен на компе как раз таки с поддержкой AES.

> было бы здорово добавить свой оверрайд для i2pd. например, через настройку в конфиге
Это можно устроить.

**Comment by bol-van** [comment]
> Не знаю, но ведь эти опкоды надо перевести в байты для исполнения процессором. А если компилятор не знает, то как он преобразует то их? Этот вывод корки выше был получен на компе как раз таки с поддержкой AES.

если он исполняется, значит компилятор успешно собрал бинарик. значит он не ругнулся на команды.
можно дизассемблировать objdump-ом, найти функцию, посмотреть что там нагенерили
можно когда оно упадет в gdb посмотреть дизассембле

**Comment by r4sas** [comment]
Залил код с отключением через конфиг, параметры aesni и avx.

**Comment by bol-van** [comment]
> Залил код с отключением через конфиг, параметры aesni и avx.

я просил наоборот, чтобы включать принудительно AES там, где cpuid говорит, что его нет

**Comment by r4sas** [comment]
А есть возможность проверить что возвращает cpuid и встроенная проверка через `__builtin_cpu_supports`?

**Comment by bol-van** [comment]
> А есть возможность проверить что возвращает cpuid и встроенная проверка через `__builtin_cpu_supports`?

на той VPSке

int info[4];
__cpuid(0, info[0], info[1], info[2], info[3]);
printf("%d %d %08X %08X %08X %08X ",__builtin_cpu_supports("aes"),__builtin_cpu_supports("avx"),info[0],info[1],info[2],info[3]);

0 0 0000000D 756E6547 6C65746E 49656E69

**Comment by bol-van** [comment]
Собрал на mingw avx бранч. Собралось. На компе с AES ничего не упало
винда 2019 сервер

**Comment by r4sas** [comment]
Судя по всему встроенка проверяет по тому же принципу, раз и там всё по нулям...

**Comment by r4sas** [comment]
> включать принудительно AES там, где cpuid говорит, что его нет

Добавлено. секция `cpuext` в конфиге, ранее добавленные опции переехали туда же.

**Comment by LLE8** [comment]
i2pd version 2.50.1-7-gc5cab05a (0.9.61)
Boost version 1.74.0
OpenSSL 3.0.11 19 Sep 2023
Debian 12.4 64-bit
Сборка пакета по инструкции `debuild --no-tgz-check -us -uc -b`
Опции получаются такие 
`g++ -g -O2 -ffile-prefix-map=/home/user1/i2pd=. -fstack-protector-strong -Wformat -Werror=format-security -Wall
-pedantic -std=c++17 -fPIC -maes -MMD -MP -DUSE_UPNP -D__AES__ -DOPENSSL_SUPPRESS_DEPRECATED -DGITVER=2.50.1-7-g
c5cab05a -Ilibi2pd -Ilibi2pd_client -Ii18n -c -o obj/libi2pd/api.o libi2pd/api.cpp`

Процессор AMD Ryzen 9 5950X с AES, AVX, AVX2
/proc/cpuinfo:
```
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 25
model           : 33
model name      : AMD Ryzen 9 5950X 16-Core Processor
stepping        : 0
microcode       : 0xa201025
cpu MHz         : 3393.622
cache size      : 512 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 16
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm rep_good nopl cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw perfctr_core ssbd ibrs ibpb stibp vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves clzero xsaveerptr wbnoinvd arat npt lbrv nrip_save tsc_scale vmcb_clean pausefilter pfthreshold v_vmsave_vmload vgif umip pku ospke vaes vpclmulqdq rdpid fsrm arch_capabilities
bugs            : sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass srso
bogomips        : 6787.24
TLB size        : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management:
```
В i2pd.log признаков AVX не обнаружено:
```
22:09:36@551/info - Log: Logging level set to debug
22:09:36@551/info - Log: Sending messages to /var/log/i2pd/i2pd.log
22:09:36@551/none - i2pd v2.50.1-7-gc5cab05a (0.9.61) starting...
22:09:36@551/debug - FS: Main config file: /etc/i2pd/i2pd.conf
22:09:36@551/debug - FS: Data directory: /var/lib/i2pd
22:09:36@551/debug - FS: Certificates directory: /var/lib/i2pd/certificates
22:09:36@551/info - AESNI enabled
22:09:36@551/info - Daemon: Router configured as floodfill
22:09:36@551/debug - Tunnel: Max number of transit tunnels set to 20000
22:09:36@551/info - Daemon: Bandwidth set to 1000000KBps
22:09:36@551/info - Daemon: Using system limit in 8192 max open files
22:09:36@551/info - Daemon: Starting NetDB
22:09:36@551/info - Family: 6 certificates loaded
22:09:36@551/info - NetDb: 324 routers loaded (213 floodfils)
22:09:36@551/info - Daemon: Starting Transports
22:09:36@551/info - NTCP2: Proxy is not used
22:09:36@551/info - NTCP2: Start listening v4 TCP port 19340
22:09:36@551/debug - SSU2: Opening IPv4 socket at Start
22:09:36@551/info - SSU2: Start listening on 0.0.0.0:19340
22:09:36@551/info - Transports: Started peer test IPv4
22:09:36@551/info - Daemon: Transports started
22:09:36@551/info - Daemon: Starting Webconsole at 127.0.0.1:7070
22:09:36@551/info - Daemon: Starting Tunnels
22:09:36@551/info - Daemon: Starting Router context
22:09:36@551/info - Daemon: Starting Client
```
Явное указание force = true в секции cpuext в i2pd.conf ничего не меняет.

**Comment by Vort** [comment]
> В i2pd.log признаков AVX не обнаружено:

Эти оптимизации были убраны непосредственно из кода i2pd.
Их было мало и они мало чем помогали.
Главные оптимизации идут из openssl.
