### ISSUE TITLE
[Question] SOCKS4 or SOCKS5 to be used for i2p-to-Tor configuration ?

### ISSUE THREAD

**Issue by Nokia808** [PurpleI2P/i2pd#1572]
Hi. In short, after the failure to utilize http://false.i2p as outproxy due to either being very overloaded or downhill from it's root, I tried to use Tor as outproxy. I'm using FoxyProxy add-on. I added new settings as following:

Address: 127.0.0.1
Port: 4447
I did not set any specific pattern

The problem is that I have 2 choices by FoxyProxy when creating this setting: either SOCKS4 or SOCKS5. I select SOCKS5 blindly & it worked.

Note: SOCKS proxy is enabled by default in my i2pd & I'm already enabled SOCKS outproxy which set by default on 127.0.0.1:9050 & system Tor package already installed on my system & it's service is enabled also.

Just I like to know which is more secure SOCKS4 or SOCKS5? Which is better for using i2p-to-Tor setting?

Thank you.

**Comment by orignal** [comment]
outproxy parameter might be set to http://  or sock://  
http:// must provide remote I2P address, while socks:// must provide some local endpoint, either Tor or I2P client tunnel to remote outproxy.

**Comment by Nokia808** [comment]
You did not answer my question. However, I discovered that I'm in fact forget that Tor using SOCKS5 because the current Tor browser remove "network setting" but I have screenshots for Tor "network setting" when it was still existing & it showing me that it use SOCKS5.

Issue resolved.
