### ISSUE TITLE
Users are identifiable if server is running i2pd

### ISSUE THREAD

**Issue by qorg11** [PurpleI2P/i2pd#1573]
If you, somehow, print the REMOTE_ADDR environment variable, it will print a bogon ip address (127.x.x.x)
however, this bogon IP is different for every client (meaning a client has 127.x.y.z and another client has 127.y.x.z), java i2p set the remote IP address as 127.0.0.1 for everyone

**Comment by qorg11** [comment]
it seems like i2pd can force your IP address to be 127.0.0.1 if your tunnels.conf looks like this:

```
[test]
type = http
address = 0.0.0.0
host = 0.0.0.0
destination = 0.0.0.0
port = 80
keys = test.dat
```
Please update the docs: https://i2pd.readthedocs.io/en/latest/user-guide/tunnels/#serverhttp-tunnels
they recommend creating the service as 
```
[http-in]
type = http
host = ourwebsite.com
port = 80
keys = our-website.dat
```
which causes the issue.

**Comment by orignal** [comment]
enableuniquelocal=false  in tunnel's config  will always produce 127.0.0.1

**Comment by qorg11** [comment]
@original that config shold be enabled by default

**Comment by yhaenggi** [comment]
How is it more "anonymous"? This is local only information.

**Comment by yhaenggi** [comment]
Also i'd like to note that this isn't a "bogon IP address". 127.0.0.0/8 is for your localhost to use, all of them. The mapping of clients helps if you want IP based selection/banning/etc. This information is only available locally on your network stack.

**Comment by majestrate** [comment]
> Also i'd like to note that this isn't a "bogon IP address". 127.0.0.0/8 is for your localhost to use, all of them. The mapping of clients helps if you want IP based selection/banning/etc. This information is only available locally on your network stack.

this is one thing that tor doesn't have that is actually super useful in maintaining services on the server side. the information is already there so it's probably fine to expose it by default.

**Comment by orignal** [comment]
>It is more anonymous that way.

No, it's not. It's for you as server owner only. It doesn't affect client's anonymity, since you have this info anyway.
