### ISSUE TITLE
Daemon option crash i2p on windows.

### ISSUE THREAD

**Issue by oooaoaSH** [PurpleI2P/i2pd#1576]
"daemon = true" in i2pd.conf crash i2pd on windows. Log file is empty.

**Comment by r4sas** [comment]
On Windows `daemon` option is useful only when i2pd is running as service.
https://github.com/PurpleI2P/i2pd/blob/7e874eaa7ce707f45a3b2a46db74ae8d48b114a3/Win32/DaemonWin32.cpp#L64-L78

**Comment by r4sas** [comment]
https://github.com/PurpleI2P/i2pd/commit/cb8651ec68d4c2ebe7cdb7fe3b015c8f1e686244#diff-996e22524939442d5b220622cd749de9dae75fc4cedafc2c1703c5d8650f1c6a
