### ISSUE TITLE
Too many files errors

### ISSUE THREAD

**Issue by andrewheadricke** [PurpleI2P/i2pd#1579]
Running self compiled from latest master branch on OSX Catalina (10.15.7)

```
10:25:01@354/error - Tunnel: runtime exception: random_device failed to open /dev/urandom: Too many open files
10:25:01@420/error - NTCP2: Accept error Too many open files
10:25:01@354/error - Profiling: /Users/noone/.i2pd/peerProfiles/pG/profile-G~QTn0wqz70q-KYCsBYygWfmxmu~6B-rVj~cmWuG3GA=.txt: cannot open file
10:25:01@354/error - Profiling: /Users/noone/.i2pd/peerProfiles/pz/profile-z0a4FGUHSex1VSZtU1-~K42usz4nS19tO~zSMsXsB4k=.txt: cannot open file
10:25:01@354/error - Tunnel: runtime exception: random_device failed to open /dev/urandom: Too many open files
10:25:01@420/error - NTCP2: Accept error Too many open files
```

I've read OSX Catalina defaults to 256 file limit, and these errors do start to appear when i2pd reaches 256 open file descriptors. I've tried several tricks to increase file descriptors but errors remain.

**Comment by r4sas** [comment]
Have you tried to execute `ulimit -n 4096` before starting i2pd?

Found useful topic: https://wilsonmar.github.io/maximum-limits/

**Comment by andrewheadricke** [comment]
Looks like messing around with the file descriptor limits fixed it. i2pd using about 560 open files at the moment, by far the most of all running processes, but seems stable nonetheless.
