### ISSUE TITLE
error - Phase 4 read error: End of file. Check your clock

### ISSUE THREAD

**Issue by mittorn** [PurpleI2P/i2pd#159]
Часы вроде правильно установлены, gmt+6.
Тунелли не открываются, LeaseSet not found.
Периодически  выкидывает в выхллоп подобны ошибки.
03:11:47/info - TunnelMessage: handle fragment of 2657 bytes. Msg type 23
03:11:47/error - No NTCP and SSU addresses available
03:11:47/debug - TransitTunnel endpoint for 2354422583
03:11:47/debug - TransitTunnel endpoint for 2354422583
03:11:47/debug - TransitTunnel endpoint for 2354422583
03:11:47/info - TunnelMessage: handle fragment of 2657 bytes. Msg type 23
И изредка то, что в загголовке.
Версия boost:
[U] dev-libs/boost
     Available versions:  1.52.0-r6(0/1.52) 1.52.0-r7(0/1.52) ~1.53.0-r1(0/1.53) ~1.54.0-r1(0/1.54) ~1.55.0-r1(0/1.55.0)^t ~1.55.0-r2(0/1.55.0)^t [M]~1.56.0(0/1.56.0)^t {context debug doc icu mpi +nls python static-libs +threads tools ABI_MIPS="n32 n64 o32" ABI_PPC="32 64" ABI_S390="32 64" ABI_X86="32 64 x32" PYTHON_TARGETS="python2_7 python3_2 python3_3 python3_4"}
     Installed versions:  1.52.0-r6(21:13:34 28.10.2013)(nls python threads -debug -doc -icu -mpi -static-libs -tools PYTHON_TARGETS="python2_7 python3_2 -python2_6 -python3_3")
     Homepage:            http://www.boost.org/
     Description:         Boost Libraries for C++
crypptopp:
[I] dev-libs/crypto++
     Available versions:  *5.6.1-r1 ~*5.6.1-r3 ~5.6.2 (~)5.6.2-r1 {static-libs}
     Installed versions:  5.6.2-r1(22:35:22 24.02.2015)(static-libs)
     Homepage:            http://cryptopp.com
     Description:         C++ class library of cryptographic schemes
Собирал так:
make CXXFLAGS="-O2 -mcpu=cortex-a7 -mfpu=neon-vfpv4 -mvectorize-with-neon-quad -ftree-vectorize -mfloat-abi=hard -funsafe-math-optimizations -fgraphite-identity -floop-interchange -floop-block -mthumb -ffast-math -pipe -fstack-protector --param=ssp-buffer-size=4" -j2
gcc 4.8.3
glibc 2.19-r1

**Comment by orignal** [comment]
Понятно. MIPS. Никогда не пробовал на нем, может бага с выравниванием где то.
Какие то данные явно идут. 
Надо идти на http://127.0.0.1:7070 в раздел 'Local destinations' и смотреть как там обстоят дела с тоннелями. Если они там есть то смотреть почему не получается найти LeaseSet, тут бывает две причины: либо его и правда нет, либо не может разыменовать переданный адрес.

**Comment by mittorn** [comment]
cortex-a7 - arm, но там тоже могут быть проблемы с выравниванием, например все реализации TTH падают с sigbus если нет специального патча, хотя тогда бы тут тоже прцесс должен был падать. Собрать отладочную версию пока что не получится, с флагом -g компилятор съедает всю память и падает. Возможно виноваты оптимизации, попробую потом без них. Ошибка из заголовка - нормальное поведение? Может надо часы на другой часовой пояс перевести?

**Comment by orignal** [comment]
Такая ошибка это нормально. Если есть другие NTCP соединения, то там могут быть и иные причины. Часовой пояс тут непричм - время все равно в UTC

**Comment by MIR371** [comment]
Перестал работать i2pd, в статусе **_Clock skew_** в логах вот такая хрень: 
_14:44:51@874/error - Transports: Unable to resolve SSU address: Этот хост неизвестен
14:44:51@525/error - NTCP: Phase 4 read error: End of file. Check your clock_ 
Если запустить с новым пустым профилем - стоит на статусе **_Testing_**
Раньше всё работало нормально, такая хрень появилась не раньше месяца назад, когда точно ХЗ, т.к i2pd использую не часто. 

Версия 2.15 и 2.14, WinXP SP3 x32

**Comment by r4sas** [comment]
Как же вы задрали с хрюшей...

```batch
@echo off
rem Скрипт настройки NTP клиента Windows
echo Скрипт настройки NTP клиента Windows
echo.

rem -- ввод адреса NTP сервера
set /p ntp_server="Введите адрес NTP сервера: "

rem -- ввод периуда обновления времени в минутах
set /p ntp_update="Задайте период обновления (min): "

rem -- задаем в качестве сервера по умолчанию 0 элемент
echo.
echo =======================================================
echo Задаем в качестве сервера по умолчанию 0 элемент
REG ADD HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\DateTime\Servers /ve /t REG_SZ /d 0 /f

rem -- редактируем значение сервера обновлений из списка под новером 0
echo.
echo =======================================================
echo Изменяем текущие значение сервера обновлений списка серверов на %ntp_server%
REG ADD HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\DateTime\Servers /v 0 /t REG_SZ /d %ntp_server% /f

rem -- включаем NTP клиент
echo.
echo =======================================================
echo Включаем NTP клиент
REG ADD HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\Parameters /v Type /t REG_SZ /d NTP /f

rem -- задаем текущий сервер обновления
echo.
echo =======================================================
echo Задаем текущий сервер обновления %ntp_server%
REG ADD HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\Parameters /v NtpServer /t REG_SZ /d %ntp_server%,0x9 /f

rem -- устонавливаем период обновления
echo.
echo =======================================================
echo Устонавливаем периуд обновления %ntp_update% минут
rem -- перевод времени в секунды
set /a ntp_update*=60
REG ADD HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\TimeProviders\NtpClient /v SpecialPollInterval /t REG_DWORD /d %ntp_update% /f

rem -- задаем службе времени автоматический запуск
echo.
echo =======================================================
echo Задаем службе времени автоматический запуск 
sc config w32time start= auto

rem -- запускаем/перезапускаем незапущеную/зупущеную службу времени 
echo. && echo======================================================= && echo Попытка перезапуска службы времени && echo. && sc stop w32time && PING -n 5 -w 1000 127.0.0.1 >nul && sc start w32time || echo. && echo ======================================================= && echo Попытка запуска службы времени && echo. && sc start w32time 

echo.
pause
```

**Comment by MIR371** [comment]
Скрипт помог, но теперь по какойто причине i2pd начал падать в рандомные промежутки времени. 
Последние строчки из лога: 

> 18:04:44@528/error - Tunnels: Can't create outbound tunnel, no inbound tunnels found
> 18:04:56@525/error - NTCP: Phase 4 read error: End of file. Check your clock
> 18:04:56@525/error - NTCP: Phase 4 read error: End of file. Check your clock
> 18:05:08@528/error - Destination: Can't publish LeaseSet. No outbound tunnels
> 18:05:08@528/error - Destination: Can't publish LeaseSet. No outbound tunnels
> 18:05:08@525/error - NTCP: Phase 4 read error: Удаленный хост принудительно разорвал существующее подключение. Check your clock
> 18:05:12@525/error - NTCP: Phase 4 read error: End of file. Check your clock
> 18:05:29@107/error - SSU: unexpected message 1

**Comment by r4sas** [comment]
призываю @orignal

**Comment by orignal** [comment]
так написано же что не может соединиться ни с кем

**Comment by mppdidi** [comment]
Can someone elaborate in english please - I'm still having this error on different machines.

**Comment by orignal** [comment]
@mppdidi that's about windows-specific issue. But if you still have that issue check your NTP settings

**Comment by mppdidi** [comment]
The ntp is fine, clock is in sync.
What can I do to debug this issue further ?
How relevant is this if it occurs every 10 minutes or so ?

Thanx

**Comment by mppdidi** [comment]
remote           refid      st t when poll reach   delay   offset  jitter
================================================================
*xxx.xxx.xxx.xxx    78.46.53.8       3 u   61  512  377    0.381   -0.074   0.270
associd=0 status=0615 leap_none, sync_ntp, 1 event, clock_sync,
version="ntpd 4.2.8p4@1.3265-o Wed Apr  5 13:30:46 UTC 2017 (1)",
processor="armv7l", system="Linux/4.4.0-1009-raspi2", leap=00, stratum=4,
precision=-20, rootdelay=27.252, rootdisp=43.103, refid=192.168.64.2,
reftime=dda5f1fc.42ccb395  Thu, Nov  2 2017 20:35:24.260,
clock=dda5f239.cdcb9691  Thu, Nov  2 2017 20:36:25.803, peer=47788,
tc=10, mintc=3, offset=-0.074297, frequency=-3.378, sys_jitter=0.000000,
clk_jitter=0.419, clk_wander=0.052

This looks okay - doesn't it ?
But i keep getting 'check your clock' messages.

Could this error be caused by oter i2pd peers ?

Thanx
