### ISSUE TITLE
Crash when exit

### ISSUE THREAD

**Issue by k79e** [PurpleI2P/i2pd#1590]
It usually crash on exit except grace exit.

[dmps.zip](https://github.com/PurpleI2P/i2pd/files/5647344/dmps.zip)

**Comment by r4sas** [comment]
Is I2CP or SAM is used?

**Comment by k79e** [comment]
sam enabled but not used
i2cp is disabled

**Comment by r4sas** [comment]
Testing with current release please. Reopen if it still happens.
