### ISSUE TITLE
NTCP proxy don't work

### ISSUE THREAD

**Issue by k79e** [PurpleI2P/i2pd#1591]
I disabled the ssu and in console the ssu connections disappeared
But all ntcp is using direct connection rather over proxy.
I'v set ntcpproxy = http://xxxxx:xxxx

Is this ntcpproxy only for ntcp1 but not ntcp2!??

**Comment by r4sas** [comment]
`ntcpproxy` was deprecated, use `ntcp2.proxy` instead.

**Comment by k79e** [comment]
Wow it worked!!
