### ISSUE TITLE
QT project: народ, плиз выбросьте карточку из QT проекта в репе - я думаю это будед не в QT аппе, а в новой FLUTTER аппе i2pd/f aka [f].

### ISSUE THREAD

**Issue by nonlinear-chaos-order-etc-etal** [PurpleI2P/i2pd#1597]
Вот линк на карточку которую надо удалить из QT проекта: https://github.com/PurpleI2P/i2pd/projects/1#card-11390992 

вот линк на сам проект QT: https://github.com/PurpleI2P/i2pd/projects/1

**Comment by nonlinear-chaos-order-etc-etal** [comment]
карточка, которую надо удалить:


[f] unloadable gui with persistent i2pd daemon
#1214 opened by pragmatic-strain

**Comment by nonlinear-chaos-order-etc-etal** [comment]
@r4sas сможешь сделать?

**Comment by nonlinear-chaos-order-etc-etal** [comment]
и вот эту карточку из QT проекта тоже удалить https://github.com/PurpleI2P/i2pd/projects/1#card-8741805

[f] app - upnp into gui #538

**Comment by r4sas** [comment]
done
