### ISSUE TITLE
Хостинг посредством i2pd

### ISSUE THREAD

**Issue by drequivalent** [PurpleI2P/i2pd#160]
Как можно, и вообще, возможно ли сейчас хостить веб-сайты при помощи i2pd? А если вывешивать не веб, а что-нибудь еще, скажем XMPP? Можно ли пробраcывать порты?
Как узнать, какой b64-адрес достался этому конкретному роутеру?

**Comment by orignal** [comment]
>Как можно, и вообще, возможно ли сейчас хостить веб-сайты при помощи i2pd?
Можно, как прокладывать тоннели читаем здесь https://github.com/PurpleI2P/i2pd/wiki/tunnels.cfg

>А если вывешивать не веб, а что-нибудь еще, скажем XMPP?
Аналогично.  Тоннелям безралично что там передается

>Можно ли пробраcывать порты?
Порты пока не сделаны. То есть на один адрес один тоннель.

>Как узнать, какой b64-адрес достался этому конкретному роутеру?
Посмотреть на http://127.0.0.1:7070/?local_destinations, но там сейчас b32.
Показ base64 туда добавлю раз нужно.
Или можно и  соотвествующего .dat файла, у него точтно такой же формат как у джавы/

**Comment by drequivalent** [comment]
А когда будут порты реализованы?
Или слишком сложно? Мне известно, что порты в ш2з можно юзать.

**Comment by orignal** [comment]
Уже есть. Параметр inport у серверного тоннеля.

**Comment by drequivalent** [comment]
Здорово, пасибочки.

**Comment by drequivalent** [comment]
А как насчет того, чтобы повесить несколько портов на один адрес? Нереально?

**Comment by orignal** [comment]
А  в чем проблема? Надо указать один и тот же файл с ключами в нескольких записях в tunnel.cfg. В SAM/BOB этого нельзя, потому что протоколом не предусмотрено.
