### ISSUE TITLE
AVX/AES for linux packaging

### ISSUE THREAD

**Issue by khumarahn** [PurpleI2P/i2pd#1602]
Hi!

I maintain i2pd for gentoo linux. I am not quite sure what I should do about AVX/AES. Can you clarify whether the package compiled on a machine with AVX/AES would work on a machine without? (Or the other way around?) Does i2pd now do the runtime detection of processor features?

This should not be a problem for gentoo most of the time because normally packages are compiled on the machine they are used (also with `-march=native`), but gentoo also supports distribution of binary packages, where this can be important.

I see that our friends from arch linux https://github.com/archlinux/svntogit-community/tree/packages/i2pd/trunk do not treat this in any special way. (And they are usually right.)

**Comment by r4sas** [comment]
Hi. Yes, now all detected at runtime correctly and extra options is added (sometimes on VMs instructions can be shown in CPU extensions, but really they are now available and vice versa) - `cpuext` block.

Little patch, added to archlinux and our trunk, is needed for correct support of old x86 processors. I'm not assumed that someone can try use such processors.

**Comment by khumarahn** [comment]
Thanks for the explanation! Can you point me to the patch? (It looks like arch folks do not apply anything related, or am I wrong?)

**Comment by yhaenggi** [comment]
I have plenty of old devices to test with, anything specific needed?

**Comment by r4sas** [comment]
> It looks like arch folks do not apply anything related, or am I wrong?

Ah, I was wrong. Here was other issue from OpenWRT, see here: https://github.com/PurpleI2P/i2pd/issues/1600.
So use that patch: https://github.com/openwrt/packages/pull/14192/files#diff-5b7978408b4816053594e5b0bdc6de16f1c3a874232ac8d54d13044da47b9866

@yhaenggi, apply patch from link above and try build/run.

**Comment by yhaenggi** [comment]
I can confirm auto-detection works on K6 (x86) and P4 (x86+x86_64).

**Comment by r4sas** [comment]
Added task on Arch bugtracker: https://bugs.archlinux.org/task/69092

**Comment by r4sas** [comment]
Fixed in Archlinux.
Closing issue as answered.
