### ISSUE TITLE
сборка под openbsd

### ISSUE THREAD

**Issue by babut85** [PurpleI2P/i2pd#161]
можно ли добавить сборку под опёнок? конкретно под амд64.
пробовал следующее:
# gmake
mkdir -p obj
g++     -c -o obj/CryptoConst.o CryptoConst.cpp
In file included from CryptoConst.cpp:2:
CryptoConst.h:4:30: error: cryptopp/integer.h: No such file or directory
In file included from CryptoConst.cpp:2:
CryptoConst.h:13: error: 'CryptoPP' has not been declared
CryptoConst.h:13: error: ISO C++ forbids declaration of 'Integer' with no type
CryptoConst.h:13: error: expected ';' before 'elgp'
CryptoConst.h:14: error: 'CryptoPP' has not been declared
CryptoConst.h:14: error: ISO C++ forbids declaration of 'Integer' with no type
CryptoConst.h:14: error: expected ';' before 'elgg'
CryptoConst.h:17: error: 'CryptoPP' has not been declared
CryptoConst.h:17: error: ISO C++ forbids declaration of 'Integer' with no type
CryptoConst.h:17: error: expected ';' before 'dsap'
CryptoConst.h:18: error: 'CryptoPP' has not been declared
CryptoConst.h:18: error: ISO C++ forbids declaration of 'Integer' with no type
CryptoConst.h:18: error: expected ';' before 'dsaq'
CryptoConst.h:19: error: 'CryptoPP' has not been declared
CryptoConst.h:19: error: ISO C++ forbids declaration of 'Integer' with no type
CryptoConst.h:19: error: expected ';' before 'dsag'
CryptoConst.cpp: In function 'const i2p::crypto::CryptoConstants& i2p::crypto::GetCryptoConstants()':
CryptoConst.cpp:67: error: too many initializers for 'i2p::crypto::CryptoConstants'
Makefile:45: recipe for target 'obj/CryptoConst.o' failed
gmake: *** [obj/CryptoConst.o] Error 1
--- установил cryptopp, заменил FreeBSD на OpenBSD в Makefile
# gmake
mkdir -p obj
g++ -O2 -std=c++11 -I/usr/include/ -I/usr/local/include/ -I/usr/local/include/cryptopp  -c -o obj/CryptoConst.o CryptoConst.cpp
cc1plus: error: unrecognized command line option "-std=c++11"
Makefile:45: recipe for target 'obj/CryptoConst.o' failed
gmake: *** [obj/CryptoConst.o] Error 1
--- на нашёл аналога и удалил -std=c++11 из Makefile.bsd
# gmake
mkdir -p obj
g++ -O2  -I/usr/include/ -I/usr/local/include/ -I/usr/local/include/cryptopp  -c -o obj/CryptoConst.o CryptoConst.cpp
CryptoConst.cpp: In function 'const i2p::crypto::CryptoConstants& i2p::crypto::GetCryptoConstants()':
CryptoConst.cpp:67: error: braces around scalar initializer for type 'const CryptoPP::Integer'
CryptoConst.cpp:67: error: braces around scalar initializer for type 'const CryptoPP::Integer'
CryptoConst.cpp:67: error: braces around scalar initializer for type 'const CryptoPP::Integer'
CryptoConst.cpp:67: error: braces around scalar initializer for type 'const CryptoPP::Integer'
CryptoConst.cpp:67: error: braces around scalar initializer for type 'const CryptoPP::Integer'
Makefile:45: recipe for target 'obj/CryptoConst.o' failed
gmake: *** [obj/CryptoConst.o] Error 1
--- больше идей не было

**Comment by orignal** [comment]
g++ какой версии? Небось 4.2?
Надо сначала более свежий компилятор поставить, 4.6 мининум, а уж потом пытаться или с -std=c++11 или -std=c++0x, по аналогии с Makefile.linux.
Специально BSD никто заниматься не станет ввиду неактульности.
