### ISSUE TITLE
Segmentation fault when calling TunnelConfig with an empty vector of peers

### ISSUE THREAD

**Issue by CajuM** [PurpleI2P/i2pd#1614]
i2pd version: 2.35.0

when calling i2p::tunnel::TunnelConfig::TunnelConfig with an empty vector of peers.
m_lastHop will be set to nullptr in CreatePeers
the following call to m_LastHop->SetNextIdent will trigger a segmentation fault due to "this" being set to nullptr

**Comment by orignal** [comment]
Thanks. It will be fixed. But what do you need it for? You have ZeroHopsInboundTunnel and ZeroHopsOutboundTunnel for it.

**Comment by CajuM** [comment]
I was debugging a coredump, I thought it was due to corrupt data. But now that you mention it, having configured zero-hop tunnels might have been the problem.

**Comment by orignal** [comment]
zero-hops should work. we tried

**Comment by CajuM** [comment]
My i2pd.conf
```
notransit = true
```
And tunnels.conf
```
[sshd]
type = server
port = 22
host = ::1
keys = sshd-keys.dat
inbound.length = 0
inbound.quantity = 5
outbound.length = 0
outbound.quantity = 5

[socks0]
type = socks
port = 4448
address = ::1
keys = socks0-keys.dat
inbound.length = 0
inbound.quantity = 5
outbound.length = 0
outbound.quantity = 5
```

Segfaults with a clean data directory.

**Comment by orignal** [comment]
What version is it? 2.35 or trunk?

**Comment by CajuM** [comment]
2.35.0

**Comment by orignal** [comment]
It's fixed in trunk already. Either build it or wait for the next release.
