### ISSUE TITLE
Can IRC server hide IP to public normal clients?

### ISSUE THREAD

**Issue by mahengrui1** [PurpleI2P/i2pd#1617]
Not download yet, read docs but don't understand, if the host uses i2pd, is the IRC server invisible from normal clients such as HexChat?

**Comment by r4sas** [comment]
Please concretise what from whom is hidden.

**Comment by mahengrui1** [comment]
> 
> 
> Please concretise what from whom is hidden.

Sorry, if the server IP is a.b.c.d:6667 for clients' HexChat seen, can i2pd change it to e.f.g.h:6667 when HexChat's connecting?

**Comment by r4sas** [comment]
i2pd is not changing IP addresses. It can tunnel access to your service thru I2P network so users wull see your service address as b32.i2p, not standart IP address. Read this: https://i2pd.readthedocs.io/en/latest/tutorials/irc/

**Comment by mahengrui1** [comment]
> 
> 
> i2pd is not changing IP addresses. It can tunnel access to your service thru I2P network so users wull see your service address as b32.i2p, not standart IP address. Read this: https://i2pd.readthedocs.io/en/latest/tutorials/irc/

Thank you very much. I heard I2P long ago but I was stupid when I questioned, now my brain is clear thank you I have no more question
