### ISSUE TITLE
Warnings and errors when running i2pd Ubuntu 18.04.4. Desktop

### ISSUE THREAD

**Issue by raphael10-collab** [PurpleI2P/i2pd#1618]
Hi!!

Being new to i2pd, but eager to learn as much as possible in order to use it soon, I tried to follow the indications here: https://i2pd.readthedocs.io/en/latest/user-guide/FAQ/

In Ubuntu 18.04.4. Desktop,
I set the number of open file descriptors allowed to a process as 4096: ulimit -n 4096

and then run i2pd : 

But from the messages I get, there must be something to fix:

    (base) marco@pc01:~$ i2pd
    19:34:59@286/warn - Family: Can't load family certificates from /home/marco/.i2pd/certificates/family
    19:34:59@286/error - Daemon: failed to start webconsole: bind: Address already in use
    19:34:59@286/error - Clients: Exception in HTTP Proxy: bind: Address already in use
    19:34:59@286/error - Clients: Exception in SOCKS Proxy: bind: Address already in use
    19:34:59@286/warn - Clients: Can't read /home/marco/.i2pd/tunnels.conf: /home/marco/.i2pd/tunnels.conf: cannot open file
    19:34:59@286/error - Clients: Exception in SAM bridge: bind: Address already in use
    19:34:59@964/warn - SSU: Missing fragments from 0 to 0 of message 2266773171
    19:34:59@336/warn - NTCP2: SessionCreated read error: End of file
    19:34:59@964/warn - SSU: Missing fragments from 0 to 0 of message 1400681332
    19:34:59@964/warn - SSU: Missing fragments from 0 to 0 of message 1657726415
    19:34:59@964/warn - SSU: MAC verification failed 62 bytes from 193.135.10.218:29650
    19:34:59@336/warn - NTCP2: SessionCreated read error: End of file
    19:34:59@336/warn - NTCP2: SessionCreated read error: End of file
    19:35:00@336/warn - NTCP2: SessionCreated read error: End of file
    19:35:00@964/warn - SSU: Missing fragments from 0 to 1 of message 898260109
    19:35:00@336/warn - NTCP2: SessionCreated read error: End of file
    19:35:00@964/warn - SSU: Missing fragments from 0 to 0 of message 946675904
    19:35:00@964/warn - SSU: Missing fragments from 0 to 0 of message 1263169916
    19:35:00@336/warn - NTCP2: SessionCreated read error: End of file
    19:35:00@336/warn - NTCP2: SessionCreated read error: End of file
    19:35:00@336/warn - NTCP2: SessionCreated read error: End of file
    19:35:00@964/warn - SSU: Missing fragments from 0 to 0 of message 3010285223
    19:35:00@964/warn - SSU: Missing fragments from 0 to 0 of message 3619049182
    19:35:00@964/warn - SSU: Missing fragments from 0 to 0 of message 2866334074
    19:35:01@964/error - SSU: unexpected peer test
    19:35:01@47/warn - Profiling: no profile yet for wFS1NSMvNDFB2GL3NtwZAsKtl0CfpF7S~jktvy~C1PA=
    19:35:04@964/warn - SSU: session with 117.20.66.251:32013 was not established after 5 seconds
    19:35:04@964/warn - SSU: session with 195.154.236.64:37924 was not established after 5 seconds
    19:35:05@964/warn - SSU: session with 45.77.250.252:11215 was not established after 5 seconds
    19:35:05@964/warn - SSU: session with 172.105.51.157:16522 was not established after 5 seconds
    19:35:05@964/warn - SSU: session with 192.222.242.17:24720 was not established after 5 seconds
    19:35:05@964/warn - SSU: session with 188.244.43.25:1025 was not established after 5 seconds
    19:35:06@47/warn - Profiling: no profile yet for noN9~dP0UNCFL~wFZh2VRkaQZ0Q5NERfPQOL64mh2FE=
    19:35:06@47/warn - Profiling: no profile yet for YDt-LJ280533BXgaWfTDGQzPTyQ6ZaEYGH-k8g8Q4Y0=
    19:35:06@47/warn - Profiling: no profile yet for uGUY5irctksaFYtSf2TdSJ-dg12tyPq5wkPB54tiDp0=
    19:35:06@47/warn - Profiling: no profile yet for 3LBfd5fPUBp0VwtQAFADaxbj~hhgkg8uOkbrryggm~w=
    19:35:06@47/warn - Profiling: no profile yet for cSmW0KD-fUa~cufkOQ-MRgxJE6NDtYe9De1lTfuGsjU=
    19:35:06@336/warn - NTCP2: SessionCreated read error: End of file
    19:35:06@336/warn - NTCP2: SessionCreated read error: End of file
    19:35:06@964/warn - SSU: Missing fragments from 0 to 0 of message 944589347
    19:35:06@964/warn - SSU: session with 78.0.11.225:28225 was not established after 5 seconds
    19:35:06@336/warn - NTCP2: SessionCreated read error: End of file
    19:35:11@47/warn - Profiling: no profile yet for qAaEOnp4U9P9dqwhZiQJAySMlyPxkD1uZnT3S7u7NL0=
    19:35:11@47/warn - Profiling: no profile yet for TSCIm1f6CwAnowxBtkO9ZSKK0kGxlvDZMJ0xT8ly4Hg=
    19:35:11@47/warn - Profiling: no profile yet for 8NVgenT7BTvGxOKld9ncUrwq7YvMLi10LE27lUAC4Uw=
    19:35:11@964/warn - SSU: session with 62.163.200.153:28858 was not established after 5 seconds
    19:35:11@964/warn - SSU: session with 14.202.191.154:36886 was not established after 5 seconds

What do I have to do to make it work properly?

**Comment by r4sas** [comment]
Hello.
One and only problem is that you trying to run i2pd from terminal as user when systemd service is already running. See for that lines:
```
19:34:59@286/error - Daemon: failed to start webconsole: bind: Address already in use
19:34:59@286/error - Clients: Exception in HTTP Proxy: bind: Address already in use
19:34:59@286/error - Clients: Exception in SOCKS Proxy: bind: Address already in use
...
```

**Comment by raphael10-collab** [comment]
@r4sas Thank you for answering and helping.

    (base) marco@pc01:~$ ps xa | grep i2pd
      1191 ?        Ssl    1:15 /snap/i2pd/100/bin/i2pd --datadir=/var/snap/i2pd/100/datadir/

So... it seems already up and working.

**Comment by danalvi** [comment]
I am having the same issue.

**Comment by r4sas** [comment]
> I am having the same issue.

Which one?

**Comment by danalvi** [comment]
I am not able to set i2pd on Mac. The same type of errors, i.e. 

```
23:18:18@272/warn - Transports: 15 ephemeral keys generated at the time
23:18:19@562/warn - SSU: Missing fragments from 0 to 0 of message 1572049251
23:18:19@562/warn - SSU: Missing fragments from 0 to 0 of message 894492021
23:18:19@562/warn - SSU: Missing fragments from 0 to 0 of message 2266775303
23:18:20@102/warn - Profiling: No profile yet for g9jNNiqadf70DBTze85MH8LIkARotoI7WfuAuB1-RrE=
23:18:20@102/warn - Profiling: No profile yet for e8CRx8yKSRyiPTfUAuXWUuZmLZ9LnDGHVco42-vLe3Y=
23:18:20@102/warn - Profiling: No profile yet for futekg4xEJEuVxFwSqh8SDn0Ohyj3MpJ3WlMPGsnePU=
23:18:20@102/error - Tunnels: Can't select next hop for rikdxvfXjzeMJ~K-RZbxXf7GDhKMXQRjHM672SHNP7M=
23:18:20@102/error - Tunnels: Can't create inbound tunnel, no peers available
23:18:20@102/error - Tunnels: Can't select next hop for rikdxvfXjzeMJ~K-RZbxXf7GDhKMXQRjHM672SHNP7M=
23:18:20@102/error - Tunnels: Can't create inbound tunnel, no peers available
23:18:20@102/warn - Profiling: No profile yet for jycM0ga1exE8m88dmbDkb3G2s8o-qRy9bdVdUoxmB5U=
23:18:20@102/warn - Profiling: No profile yet for LYjO4I6SdIwkdemi436aB~jL3pePa2IgzsOih5qtoQw=
23:18:20@102/warn - Profiling: No profile yet for fWzJSqXa89P0XxviqOULpugwgGEpaQCopLaUG6-jxtY=
23:18:20@102/warn - Profiling: No profile yet for R5QI1PGD3cZz-K5mIfYkdXHN33G9YY70023r2oUTc4Y=
23:18:20@102/warn - Profiling: No profile yet for xZ9nsAJAxQ~nrN4HBDco2BG9vwbnsaZ5uGMputC7W9g=
23:18:20@102/warn - Profiling: No profile yet for pLaR4jsPN4s7oOHVlMOIhvrmo2gi~fQa9iP2xHMagvY=
23:18:20@102/error - Tunnels: Can't select next hop for rikdxvfXjzeMJ~K-RZbxXf7GDhKMXQRjHM672SHNP7M=
23:18:20@102/error - Tunnels: Can't create inbound tunnel, no peers available
23:18:20@102/error - Tunnels: Can't select next hop for rikdxvfXjzeMJ~K-RZbxXf7GDhKMXQRjHM672SHNP7M=
23:18:20@102/error - Tunnels: Can't create inbound tunnel, no peers available
23:18:20@102/error - Tunnels: Can't select next hop for rikdxvfXjzeMJ~K-RZbxXf7GDhKMXQRjHM672SHNP7M=
23:18:20@102/error - Tunnels: Can't create inbound tunnel, no peers available
23:18:20@102/error - Tunnels: Can't select next hop for rikdxvfXjzeMJ~K-RZbxXf7GDhKMXQRjHM672SHNP7M=
23:18:20@102/error - Tunnels: Can't create inbound tunnel, no peers available
23:18:21@210/warn - NTCP2: SessionCreated read error: End of file
23:18:21@210/warn - NTCP2: SessionCreated read error: End of file
```

**Comment by r4sas** [comment]
Same answer as for TS: `Other messages is not critical and not depending from you, so there is nothing to do at current state.`

> I am not able to set i2pd on Mac

Please concretize problem. What is didn't work?

**Comment by danalvi** [comment]
> Same answer as for TS: `Other messages is not critical and not depending from you, so there is nothing to do at current state.`
> 
> > I am not able to set i2pd on Mac
> 
> Please concretize problem. What is didn't work?

Hello @r4sas , thank you so much for reaching out, and apologies, I should have been more precise. I am wanting to set up i2pd for myself, and came across the following link (https://i2pd.readthedocs.io/en/latest/tutorials/xmpp/). I followed this link precisely and exacted it, but I am receiving the error from pidgin that “unable to connect”. Also, i2pd is giving the errors which I mentioned previously.
