### ISSUE TITLE
migrating from java - how to keep the same http server address?

### ISSUE THREAD

**Issue by la11111** [PurpleI2P/i2pd#1619]
how can i tell i2pd to use the same address for my website that it uses under java?

**Comment by la11111** [comment]
okay, I got it figured out. I'm not sure if it should be classed as a bug per-se. it may be more of a package specific thing. but for more information: I'm using the debian package from the deb 10 package manager. the systemd `i2pd.service` file has a bunch of config --options hard coded into it: 

`ExecStart=/usr/sbin/i2pd --conf=/etc/i2pd/i2pd.conf --tunconf=/etc/i2pd/tunnels.conf --t
unnelsdir=/etc/i2pd/tunnels.conf.d --pidfile=/var/run/i2pd/i2pd.pid --logfile=/var/log/i
2pd/i2pd.log --daemon --service
`

which seems kinda not great as it overrides the config file. it explains why it wasn't saving the log where i asked. Also, the default `/etc/i2pd/i2p.conf` file doesn't mention the `datadir` config option nor is it a switch in the `i2p.service` file. The datadir was defaulting to `/root/.i2p` which i finally figured out by running a stack trace.

i think those switches should be taken out of the systemd script and put in the default .conf file instead and it should come with the datadir config option set at a default value.

**Comment by la11111** [comment]
leaving this open in case it pertains to you, thanks

**Comment by r4sas** [comment]
If you using i2pd as service, you can see that `--service` switch is added. In that case `datadir` will be `/var/lib/i2pd` by default.
So if you trying change any settings in `i2pd.conf`, you can get such misunderstanding.
About your question: place your old keys file in `/var/lib/i2pd`, update it's owner to `i2pd:i2pd`, chmod 644, add use it in your tunnel config by placing to `/etc/i2pd/tunnels.conf.d/`

**Comment by r4sas** [comment]
Feel ree to reopen is issue is still not solved.
