### ISSUE TITLE
Прокси

### ISSUE THREAD

**Issue by rednakse** [PurpleI2P/i2pd#162]
Возможно что-то не понимаю, или не прочитал, но поддерживается ли работа в качестве прокси? Предпосылки вроде есть, но при натравливании браузера выдает загадочное сообщение. Возможно из-за того, что пытается передать протокол, что в свою очередь, видимо, не поддерживается.
19:25:08/info - HTTP Client Request: GET //test.i2p/ HTTP/1.1
Host:ttp:
19:25:08/error - Identity buffer length 3 is too small
19:25:08/info - Unknown address ttp:

![mozilla firefox 2015-03-11 19 21 58](https://cloud.githubusercontent.com/assets/1188948/6601005/067468ae-c824-11e4-8149-d53e7bbcecde.png)

**Comment by orignal** [comment]
Я не могу понять что вы пытаетесь делать. Пропишите в настройках прокси 127.0.0.1 4446.
Пока еще никто не жаловался.

**Comment by JohnJB** [comment]
I have the same problem!
export http_proxy="http://192.168.1.1:4444/"
lynx http://zmw2...b32.i2p

Unknown address ttp:

**Comment by orignal** [comment]
let me try lynx

**Comment by JohnJB** [comment]
The problem was it seems, that we were trying to use the --httpport   port
as the proxy instead of the port specified via --httpproxyport

**Comment by orignal** [comment]
-httpport is replacing 7070, not sure is -httpproxyport work

**Comment by JohnJB** [comment]
This can be closed.
