### ISSUE TITLE
Adding prosody-s2s and prosody-c2s to /etc/i2pd/tunnels.conf doesn't give any Server Tunnel

### ISSUE THREAD

**Issue by raphael10-collab** [PurpleI2P/i2pd#1621]
Ubuntu 18.04.4 Desktop

Following the indications here: https://i2pd.readthedocs.io/en/latest/tutorials/xmpp/#decentralized-instant-messaging I modified the /var/lib/tunnels.conf as follows, adding prosody-s2s, prosody-c2s,
and a udp server as found here: https://i2pd.readthedocs.io/en/latest/user-guide/tunnels/

    [IRC-IRC2P]
    type = client
    address = 127.0.0.1
    port = 6668
    destination = irc.postman.i2p
    destinationport = 6667
    keys = irc-keys.dat

    [prosody-s2s]
    type=server
    host=127.0.0.1
    port=5269
    inport=5269
    keys=prosody.dat

    [prosody-c2s]
    type=server
    host=127.0.0.1
    port=5222
    inport=5222
    keys=prosody.dat

    [openvpn-simple-server]
    type = udpserver
    keys = openvpn.dat
    port = 1194

I restarted the service:

    ~$ sudo systemctl restart i2pd.service
and also rebooted

But I do not get any server tunnel:

![image](https://user-images.githubusercontent.com/70313067/105027559-33ed3800-5a50-11eb-8fdf-90842f1033e5.png)

What am I missing?

**Comment by orignal** [comment]
You also don't have IRC-IRC2P. That mean wrong file. Please tell me the file you've added your tunnels to.

**Comment by raphael10-collab** [comment]
Hi @orignal !! 
Thank you for helping.

Is this the wrong file?

~$ nano /var/lib/i2pd/tunnels.conf  : 

    [IRC-IRC2P]
    type = client
    address = 127.0.0.1
    port = 6668
    destination = irc.postman.i2p
    destinationport = 6667
    keys = irc-keys.dat

    # https://i2pd.readthedocs.io/en/latest/tutorials/xmpp/#decentralized-instant-messaging

    [prosody-s2s]
    type=server
    host=127.0.0.1
    port=5269
    inport=5269
    keys=prosody.dat

    [prosody-c2s]
    type=server
    host=127.0.0.1
    port=5222
    inport=5222
    keys=prosody.dat

    [openvpn-simple-server]
    type = udpserver
    keys = openvpn.dat
    port = 1194

Where should I add my tunnels?

**Comment by r4sas** [comment]
How you starting i2pd?

**Comment by raphael10-collab** [comment]
In /var/log/i2pd/ I have these logs:

    (base) marco@pc01:/var/log/i2pd$ ls -lah
    total 1,6M
    drwxr-xr-x  2 i2pd i2pd   4,0K gen 20 09:27 .
    drwxrwxr-x 17 root syslog 4,0K gen 26 08:58 ..
    -rw-r-----  1 i2pd adm       0 gen 20 09:27 i2pd.log
    -rw-r-----  1 i2pd adm    1,6M gen 20 09:27 i2pd.log.1
    -rw-r-----  1 i2pd adm     37K gen 18 07:58 i2pd.log.2.gz

Here you can find i2pd.log.1 : https://drive.google.com/file/d/1qCByTmwGHCiPMr1FnHfv5y3DAn02enpO/view?usp=sharing

But, as far as I understand, it seems that i2pd service itself is working fine:

![image](https://user-images.githubusercontent.com/70313067/105876165-f9ab0a00-5ffe-11eb-9baf-e029996889e8.png)

![image](https://user-images.githubusercontent.com/70313067/105876260-19423280-5fff-11eb-9fb9-6fbd1e19601c.png)

![image](https://user-images.githubusercontent.com/70313067/105876429-42fb5980-5fff-11eb-94f7-d0fad223f8e8.png)

![image](https://user-images.githubusercontent.com/70313067/105876572-62928200-5fff-11eb-85e6-d44efa9236cd.png)

**Comment by r4sas** [comment]
can you post /etc/i2pd/i2pd.conf, /etc/i2pd/tunnels.conf?
Also please give `ls -la /var/lib/i2pd` output.

**Comment by raphael10-collab** [comment]
After killing the specified pid : 

    (base) marco@pc01:~$ ps aux | grep i2pd
    root      1335  3.5  0.0 735564 15468 ?        Ssl  08:21   0:03 /snap/i2pd/100/bin/i2pd --datadir=/var/snap/i2pd/100/datadir/
    marco     3949  0.0  0.0  14440  1040 pts/0    S+   08:23   0:00 grep --color=auto i2pd
    (base) marco@pc01:~$ sudo kill 1335

the surver tunnels of i2pd.service appear: 

![image](https://user-images.githubusercontent.com/70313067/105958131-834bed80-607a-11eb-883b-50c4790997c7.png)

Does it mean that I have mistakly installed a second i2pd snap service?
How to definitely kill and remove it?
