### ISSUE TITLE
A general question about Prosody

### ISSUE THREAD

**Issue by raphael10-collab** [PurpleI2P/i2pd#1627]
As far as I understand, Prosody has a "federated" client-server architecture, where a server acts as middle man serving the clients.
So, if this is correct...how can Prosody be used in a decentralized peer-to-peer network?

**Comment by orignal** [comment]
How is it related to I2P or i2pd?

**Comment by raphael10-collab** [comment]
I2P and I2PD, as far as I've understood, is a decentralized network.
So...I was wondering, if and how, a "federated" client-server architecture, where a server acts as middle main serving the clients, can fit within a decentralized network like I2P and I2PD

**Comment by r4sas** [comment]
Read this: https://i2p.rocks/blog/new-life-for-xmpp-build-your-own-decentralized-messenger.html
