### ISSUE TITLE
After #1578 build broken on ix86

### ISSUE THREAD

**Issue by vitlav** [PurpleI2P/i2pd#1631]
After https://github.com/PurpleI2P/i2pd/pull/1578 build failed with follow errors:
```
Crypto.cpp:644:4: error: the register '%xmm0' cannot be clobbered in 'asm' for the current target
Crypto.cpp:661:7: error: unknown register name '%xmm0' in 'asm'

```

Is %xmm0 not applicable on ix86?

**Comment by r4sas** [comment]
Trunk? https://github.com/PurpleI2P/i2pd/issues?q=is%3Aissue+is%3Aclosed

**Comment by vitlav** [comment]
> Trunk? See #1600.
Thank you! I have checked only the last release.
