### ISSUE TITLE
NTCP2.proxy не должно влиять на работу в меш-сетях

### ISSUE THREAD

**Issue by acetoneRu** [PurpleI2P/i2pd#1637]
при `ntcp2.enabled=false` роутер через Yggdrasil (`meshnets.yggdrasil=true`) работает корретно, также должно быть и при `ntcp2.proxy=http://...`, чтобы этот параметр не препятствовал работе через меш-сеть

**Comment by orignal** [comment]
Мы вызываем ConnectWithProxy только для обычного NTCP2. Так что на Yggdrasil оно не влияет.
