### ISSUE TITLE
Unclear status and installation location and for certificates and other stuff from contrib/

### ISSUE THREAD

**Issue by AMDmi3** [PurpleI2P/i2pd#1642]
While improving FreeBSD port of i2pd, I've ran into some issues with files from contrib/, and thought that it may need to be resolved with upstream properly.

First of all, status of contrib/ files which are related to i2pd (i2pd.conf, tunnels.conf, certificates) should be cleared up. Are these official default configs or just examples not suitable for production? In the former case, these should be installed out of box. In the latter case, these should be explicitly marked as examples. At least for i2pd.conf and certificates it looks more like they are required. tunnels.conf may also be usable as default config if irc entry is commented out.

Next, a location where i2pd looks for reseed certificates is /var/lib/i2pd. This looks broken. If these are static read-only files, the correct place to install them would be DATADIR (${PREFIX}/share/i2pd). If these files may be overwritten by i2pd, installing them into var is even more broken, as software may not change files handled by packaging system, and doing so would lead to package consisteny check errors and losing changes after package reinstallation.

Summarizing, I suggest to
- move `i2pd.conf` from contrib/ to etc/ to state it's official status
- install it to `${CMAKE_INSTALL_PREFIX}/etc/i2pd`
- move certificates from contrib/ to share/ to state their official status (if that applies)
- install certificates to share/ (and not /var) directory, and look for them there as well:

https://github.com/PurpleI2P/i2pd/blob/ff9ee5873f9591cdc4704dc1deab7eabfd911199/libi2pd/Reseed.cpp#L500

**Comment by r4sas** [comment]
1. Yes, i2pd.conf is official default config, suitable for production. tunnels.conf and tunnels.conf.d (tunnels.d in repository) is example, but we install them to /etc/i2pd to make able users to see how it works and get fast access to most popular default tunnels (like in Java I2P - same tunnels preinstalled, but disabled by default).
What about certificates - that is most important thing, which make able to check if initial seeds is not modified by third-party, so as described in [official docs](https://geti2p.net/en/docs/reseed) we provide and update them, when they are published on the internal mailing lists

2. In most packages we have done the same way as you described: we install them to /usr/share/i2pd. But then we create symbolic link to make able work inside datadir without specifying path to them. **I'll add option** to make possible to use them outside of datadir, if it is not permitted to make symbolic links to static/shared files in your distribution. Anyway, package system updates them correctly without any issues and doesn't interact with them using /var/lib/i2pd path.

3. Didn't see any reason to move config files and certificates from `contrib/`, everything can be done in package specification file. What about cmake - we principle do not add the "install" target both for cmake and make and rely on the package maintainer to implement the installation in the necessary directories by itself

**Comment by AMDmi3** [comment]
> Didn't see any reason to move config files and certificates from contrib/, as everything can be done in package specification file. What about cmake - we principle do not add the "install" target both for cmake and make and rely on the package maintainer to implement the installation in the necessary directories by itself

The main point was that this is not right. This imposes additional requirements on a maintainer (and increases maintenance burden significantly), as a maintainer needs to be immersed into i2pd inner workings and keep in mind the purpose, status of all config files, and the way i2pd uses them, to package it the right way. I've stepped down as FreeBSD port maintainer as I cannot and have no intention to fulfill these requirements.

**Comment by r4sas** [comment]
Anyway, proposed option for setting certificates path was added before 2.39.0. What about `make install` - you are better to know that it is impossible to write rule, which will cover whole supported systems.
About files from contrib (as a paths, adding new files and other things) - they wasn't changed for years, and when something added, I trying to get in touch with maintainers and update package specification.
If something changes in system working way itself (due to changes of architcture and way they work, changes for directories where application files must be stored for example) that can't be monitored by our side too. Such things faster fixed by people who involved in that system rather than who not using it.

Anyway, thank you for your work on port. Please, give information about how I can propose updates to port.

**Comment by AMDmi3** [comment]
> you are better to know that it is impossible to write rule, which will cover whole supported systems

It is absolutely possible. Everybody supports `make install`.

> Please, give information about how I can propose updates to port.

https://bugs.freebsd.org/bugzilla/enter_bug.cgi?component=Individual%20Port%28s%29&product=Ports%20%26%20Packages

You may cc: amdmi3@freebsd.org
