### ISSUE TITLE
i2pd daemon openrc on artix linux

### ISSUE THREAD

**Issue by causticheshire** [PurpleI2P/i2pd#1647]
Hi
i2pd does not have a daemon script for use with openrc on artix linux
I can run it manually - /usr/bin/i2pd --conf=/var/lib/i2pd/i2pd.conf --pidfile=/run/i2pd/i2pd.pid --daemon --service
And yet could you add this opportunity out of the box?
I find [old](https://gitweb.gentoo.org/repo/gentoo.git/plain/net-vpn/i2pd/files/i2pd-2.6.0-r3.initd?id=ec49ce4a501e1bfc0c812a33e841258d4faa5ac8) openrc script and no idea, whether will works, because is from year 2016.

**Comment by r4sas** [comment]
Hi.
https://github.com/PurpleI2P/i2pd/blob/openssl/debian/i2pd.openrc
That one?

**Comment by causticheshire** [comment]
> Hi.
> https://github.com/PurpleI2P/i2pd/blob/openssl/debian/i2pd.openrc
> That one?

Yes, it is, but when starting it show me [this](https://pastebin.com/NTH0V9qf)

**Comment by r4sas** [comment]
You must read yours system manuals about targets in openrc services. `mountall` dependency is requiring for all mounts to be done before starting.
