### ISSUE TITLE
firewalled

### ISSUE THREAD

**Issue by Pepelnica1488** [PurpleI2P/i2pd#1650]
how to fix?

win10 rostelekom

**Comment by yhaenggi** [comment]
Forward the TCP and UDP port from your router to your i2pd instance. Dont post which port you use here as it may identify you.

**Comment by r4sas** [comment]
1. РТК из коробки не выдает белые IP адреса (у них, как и большей части операторов, это платная услуга)
2. Если же белый IP присутствует, то нужно либо пробросить порт в роутере, либо включить UPnP в нем же
3. Если в роутере проброс сделан, или UPnP включен и порт пробросился но статус так и висит на Firewalled, то см. п. 1
