### ISSUE TITLE
Is NTCP still supported?

### ISSUE THREAD

**Issue by LLE8** [PurpleI2P/i2pd#1652]
Why is the parameter 'ntcp = true' present in i2pd.conf?

**Comment by r4sas** [comment]
https://github.com/PurpleI2P/i2pd/commit/c359c6e634fdc106298291c8630b3a1ccb8aa131#diff-3769ddde49b461a3d42b3b264992e14fec81f13e40b9966b3beedd547efebb34L64-L68
