### ISSUE TITLE
I2PD with Ejabberd XMPP Server: how to?

### ISSUE THREAD

**Issue by raphael10-collab** [PurpleI2P/i2pd#1653]
Is there a way to use I2PD with Ejabberd XMPP Server?

Looking forward to your kind help

**Comment by r4sas** [comment]
Look at this for example: https://i2p.rocks/blog/new-life-for-xmpp-build-your-own-decentralized-messenger.html.

**Comment by raphael10-collab** [comment]
@r4sas Is there an equivalent module for Ejabberd ? https://github.com/majestrate/mod_darknet

**Comment by r4sas** [comment]
I think no.

**Comment by raphael10-collab** [comment]
Ok. Thank you for answering
