### ISSUE TITLE
Украинский перевод

### ISSUE THREAD

**Issue by click0** [PurpleI2P/i2pd#1666]
[Украинский перевод](https://github.com/PurpleI2P/i2pd/blob/openssl/i18n/Ukrainian.cpp)

Замените все `роутер` на `маршрутизатор`.

Также:
https://github.com/PurpleI2P/i2pd/blob/35ba16ff3b986749aaf1b1a2065196a1578c1be4/i18n/Ukrainian.cpp#L108
`У мережі`

https://github.com/PurpleI2P/i2pd/blob/35ba16ff3b986749aaf1b1a2065196a1578c1be4/i18n/Ukrainian.cpp#L119
`Прихований вміст. Щоб відобразити, натисніть на текст.`

https://github.com/PurpleI2P/i2pd/blob/35ba16ff3b986749aaf1b1a2065196a1578c1be4/i18n/Ukrainian.cpp#L152
`Сесії Тегів`

@r4sas

**Comment by r4sas** [comment]
Хорошо, обновлю.
