### ISSUE TITLE
 Добавить возможность в конфиге i2pd менять юзерагента (UA) при проксировании из i2p в http.

### ISSUE THREAD

**Issue by click0** [PurpleI2P/i2pd#1668]
Добавить возможность в конфиге i2pd менять юзерагента (UA) при проксировании из i2p в http.

https://github.com/PurpleI2P/i2pd/blob/openssl/libi2pd_client/HTTPProxy.cpp#L236

Например, на "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"

**Comment by r4sas** [comment]
Outproxy?

**Comment by click0** [comment]
> Зачем это надо на прокси смотрящем в i2p?

Не во все системы статистики-аналитики вот так можно добавить новый UA.
Хотя скорее это нужно добавлять не глобально, а в настройки туннеля (tunnels.d).

Туда же хочется добавлять новые http хидеры, например `i2p-proxy1` 
И переменную для host алиасов. У Апача - это аналог `Serveralias`, а у nginx - `server_name`.
Я не знаю, можно ли в `hostoverride` добавлять несколько доменов и использовать регулярку вида `.example2.i2p` или `*.example3.i2p`
Также непонятно, можно ли отправлять  траффик на несколько IP и/или портов. Эдакий балансировщик типа nginx или haproxy?

**Comment by r4sas** [comment]
Я думаю что всё это за рамками назначения приложения...

**Comment by click0** [comment]
Я думаю, вам стоит посмотреть настройки других веб-серверов.
Дадите знать, когда это реализуете.
Пока что сайты в i2p будут выглядеть как "привет из начала 90-х".

**Comment by r4sas** [comment]
При чем здесь веб-сервера и внутрисетевой мост?
Как было сказано ранее, никакой конкретики в вопросе не видно. Что, куда, каким образом, а так же что должны получить, и где - в итоге.

Зачем прикручивать прокси серверу и транспортному протоколу (то есть туннелю) то, чего они не должны делать?

**Comment by wipedlifepotato** [comment]
Можно подключаться через Socks, а user-agent менять в браузере. Всё же не понятно, зачем?

**Comment by wipedlifepotato** [comment]
@r4sas  он утверждает, что сайты должны знать что за браузеры с ними работают, что бы были хорошие сайты, а не сайты из 90. Тк типа там обрезается юзер агент.
Вроде я так понял. И добавить в конфиг по желанию обрезания данных о браузере. Но тогда, конечно, это может нарушить, некоторую, анонимность и принципы сети. Но видимо вот просят.
@click0, я правильно понял?

**Comment by r4sas** [comment]
Если требуется что либо из перечисленного в постах выше, то возможность делать Pull Request открыта.
