### ISSUE TITLE
How to be sure that all the Prosody XMPP messages are routed only through I2PD network ?

### ISSUE THREAD

**Issue by raphael10-collab** [PurpleI2P/i2pd#1670]
Following these indications: https://i2pd.readthedocs.io/en/latest/tutorials/xmpp/

I created server tunnels:

![image](https://user-images.githubusercontent.com/70313067/123407343-26624e00-d5ac-11eb-9fdb-d919461a1e6f.png)

and in prosody configuration :  

  I enabled the module `darknet` :  

    modules_enabled = {
                    "darknet";
    }

  I've set `darknet_only = true;` ,

and

  I created a VirtualHost for I2PD:

    VirtualHost "uxpug2bqoujpbjgtwogesqvixybtknziv7ieu3jfhuyxs5b4afjq.b32.i2p";
        ssl = {
            key = "/etc/prosody/certs/uxpug2bqoujpbjgtwogesqvixybtknziv7ieu3jfhuyxs5b4afjq.b32.i2p.key";
            certificate = "/etc/prosody/certs/uxpug2bqoujpbjgtwogesqvixybtknziv7ieu3jfhuyxs5b4afjq.b32.i2p.crt";
        }
    
    https_certificate = "/etc/prosody/certs/uxpug2bqoujpbjgtwogesqvixybtknziv7ieu3jfhuyxs5b4afjq.b32.i2p.crt";

In the electron app I'm developing, I'm using Strophe.js as XMPP client, and the XMPP client -> server connection seems working: 

![image](https://user-images.githubusercontent.com/70313067/123408006-d932ac00-d5ac-11eb-82c5-3065f6002fe9.png)

But how to be sure that all the XMPP messages are routed only through I2PD network?

**Comment by r4sas** [comment]
1. Use preconfigured browser, which prevents connections outside of HTTP proxies, like https://github.com/PurpleI2P/i2pdbrowser.
2. Make firewall rules to prevent user, which used for running prosody, to do any outgoing requests which not pointed to i2pd tunnel and incoming request address (created by incoming requests).

**Comment by raphael10-collab** [comment]
It's my fault... I didn't explain it fully and properly.

This is how I now connect Strophe.js client to Prosody XMPP Server : 

    let [conn, setConn] = React.useState(new Strophe.Connection("https://grasp.deals/http-bind"));
    conn.connect("raphy@grasp.deals", "devasw", onConnect);

which, as you can see, doesn't use the I2PD address.

This is the configuration of the domain name provider :  

![image](https://user-images.githubusercontent.com/70313067/123413828-7db7ec80-d5b3-11eb-9e04-c51e81d701dc.png)

So... as you explained I can say that I'm not using, at the moment, i2p routing.

The question is now: how to correctly use the i2p address?

If I set : 

      //let [conn, setConn] = React.useState(new Strophe.Connection("https://grasp.deals/http-bind"));
      let [conn, setConn] = React.useState(new
    Strophe.Connection("https://uxpug2bqoujpbjgtwogesqvixybtknziv7ieu3jfhuyxs5b4afjq.b32.i2p")); 

I get :   

![image](https://user-images.githubusercontent.com/70313067/123414379-1b132080-d5b4-11eb-93de-bb4f0e2bc259.png)

![image](https://user-images.githubusercontent.com/70313067/123414516-4564de00-d5b4-11eb-8156-43c6c1201f09.png)

**Comment by yhaenggi** [comment]
You need to use a socks/http proxy, or create a direct client tunnel.

**Comment by raphael10-collab** [comment]
@yhaenggi 

Are you referring to these clients tunnels?

![image](https://user-images.githubusercontent.com/70313067/123417234-ce314900-d5b7-11eb-8084-5ea45cf0b1cf.png)

How to use them?

**Comment by r4sas** [comment]
1. First at all, you must configure proxy to make connections to I2P addresses.
2. In `Strophe.Connection` set your server's b32 address.

**Comment by raphael10-collab** [comment]
I removed what I've set before: 
  `host = grasp.deals` in `i2pd.conf` 
and
  `http-in` in `tunnels.conf`

In `Strophe.Connection` I've already set:

    new Strophe.Connection("https://uxpug2bqoujpbjgtwogesqvixybtknziv7ieu3jfhuyxs5b4afjq.b32.i2p")

About the http proxy to configure in browser, I'm trying to understand how to correctly set HTTP proxy in electron.js.

With
    // https://www.electronjs.org/docs/api/session#sessetproxyconfig
    const ses = mainWindow.webContents.session;
    ses.setProxy({proxyRules:"127.0.0.1:4444"});

I'm getting this error: `ERR_SSL_PROTOCOL_ERROR` : 

![image](https://user-images.githubusercontent.com/70313067/123433054-5705b000-d5cb-11eb-9aab-b994d16b68bc.png)

https://www.electronjs.org/docs/api/session#sessetproxyconfig

**Comment by r4sas** [comment]
does your tunnel end (where prosody is installed) really supports `http-bind`? Maybe you must add tunnel at 80 port where all http requests will be forwarded to your plugin? 5222 doesn't support such requests I think.

**Comment by r4sas** [comment]
Read this:
https://stackoverflow.com/a/27513840
https://prosody.im/doc/setting_up_bosh

You must add server tunnel which points to 5280, like c2s ans s2s tunnels earlier.

**Comment by raphael10-collab** [comment]
I added to `/etc/i2pd/tunnels.conf` this `server tunnel`:

    [smtp-in]
    type = server
    host = 127.0.0.1
    port = 5280
    inport = 5280
    keys = prosody.dat

with `HTTP proxy settings in electron.js` , that I do hope it is in a correct form (but I get no errors): 

    ses.setProxy({proxyRules:"127.0.0.1:4444"});

and with `Strophe.connection` : 

      //let [conn, setConn] = React.useState(new Strophe.Connection("https://grasp.deals/http-bind"));
      let [conn, setConn] = React.useState(new Strophe.Connection("http://uxpug2bqoujpbjgtwogesqvixybtknziv7ieu3jfhuyxs5b4afjq.b32.i2p/http-bind"));

I get no errors but it seems not connecting: 

![image](https://user-images.githubusercontent.com/70313067/123464449-1a4ab080-d5ed-11eb-8d7e-f10735ca26ae.png)

**Comment by r4sas** [comment]
`let [conn, setConn] = React.useState(new Strophe.Connection("http://uxpug2bqoujpbjgtwogesqvixybtknziv7ieu3jfhuyxs5b4afjq.b32.i2p:5280/http-bind"));
`
^^^ add port in target address.

**Comment by raphael10-collab** [comment]
With a different key file for the `server tunnel`: `/etc/i2pd/tunnels.conf` : 
    
    [IRC-IRC2P]
    type = client
    address = 127.0.0.1
    port = 6668
    destination = irc.postman.i2p
    destinationport = 6667
    keys = irc-keys.dat
    i2cp.leaseSetType = 5
    
    [prosody-s2s]
    type=server
    host=127.0.0.1
    port=5269
    inport=5269
    keys=prosody.dat
    
    [prosody-c2s]
    type=server
    host=127.0.0.1
    port=5222
    inport=5222
    keys=prosody.dat
    
    [IRC-ILITA]
    type = client
    address = 127.0.0.1
    port = 6669
    destination = irc.ilita.i2p
    destinationport = 6667
    keys = irc-keys.dat
    
    [smtp-in]
    type = server
    host = 127.0.0.1
    port = 5280
    inport = 5280
    keys = smtp-in.dat


and  with the `port` in `server address` : 

    const onConnect = (status) => {
        if (status == Strophe.Status.CONNECTING) {
            console.log('Strophe is connecting.');
        } else if (status == Strophe.Status.CONNFAIL) {
            console.log('Strophe failed to connect.');
        } else if (status == Strophe.Status.DISCONNECTING) {
            console.log('Strophe is disconnecting.');
        } else if (status == Strophe.Status.DISCONNECTED) {
            console.log('Strophe is disconnected.');
        } else if (status == Strophe.Status.CONNECTED) {
            console.log('Strophe is connected.');
        }
    }

      //let [conn, setConn] = React.useState(new Strophe.Connection("https://grasp.deals/http-bind"));
      let [conn, setConn] = React.useState(new   
    Strophe.Connection("http://uxpug2bqoujpbjgtwogesqvixybtknziv7ieu3jfhuyxs5b4afjq.b32.i2p:5280/http-bind"));
    conn.connect("raphy@grasp.deals", "devasw", onConnect);

![image](https://user-images.githubusercontent.com/70313067/123469524-74e70b00-d5f3-11eb-9329-2de1861c52e2.png)

![image](https://user-images.githubusercontent.com/70313067/123469668-a233b900-d5f3-11eb-83dd-b804264c39a7.png)


    (base) raphy@pc:~$ sudo tail /var/log/prosody/prosody.log
    Jun 25 20:01:38 mod_bosh	info	New BOSH session, assigned it sid '32d0caa2-2415-4f6f-9adf-6ca3eee0a6dd'

It seems the right direction, but still something to fix

**Comment by r4sas** [comment]
> With a different key file for the server tunnel: /etc/i2pd/tunnels.conf 

Eh... why are you done that? Revert it back. Use prosody.dat all 3 tunnels.

**Comment by raphael10-collab** [comment]
With `/etc/i2pd/tunnels.conf` : 

    [IRC-IRC2P]
    type = client
    address = 127.0.0.1
    port = 6668
    destination = irc.postman.i2p
    destinationport = 6667
    keys = irc-keys.dat
    i2cp.leaseSetType = 5
    
    [IRC-ILITA]
    type = client
    address = 127.0.0.1
    port = 6669
    destination = irc.ilita.i2p
    destinationport = 6667
    keys = irc-keys.dat
    
    [prosody-s2s]
    type=server
    host=127.0.0.1
    port=5269
    inport=5269
    keys=prosody.dat
    
    [prosody-c2s]
    type=server
    host=127.0.0.1
    port=5222
    inport=5222
    keys=prosody.dat
    
    [prosody-bosh]
    type = server
    host = 127.0.0.1
    port = 5280
    inport = 5280
    keys = prosody.dat


client side: 
    
    const ses = mainWindow.webContents.session;
    ses.setProxy({proxyRules:"127.0.0.1:4444"});

    Strophe.Connection("http://uxpug2bqoujpbjgtwogesqvixybtknziv7ieu3jfhuyxs5b4afjq.b32.i2p:5280/http-bind"));

    // conn.connect("raphy@grasp.deals", "devasw", onConnect);

    conn.connect("raphy@uxpug2bqoujpbjgtwogesqvixybtknziv7ieu3jfhuyxs5b4afjq.b32.i2p", onConnect);

![image](https://user-images.githubusercontent.com/70313067/123477950-158ef800-d5ff-11eb-9175-507dc15806e5.png)



`prosody.log` : 


    (base) raphy@pc:~$ sudo tail /var/log/prosody/prosody.log 
    Jun 25 21:45:31 s2sin563cf8408170	warn	Received invalid XML: POST /http-bind HTTP/1.1
    Host: uxpug2bqoujpbjgtwogesqvixybtknziv7ieu3jfhuyxs5b4afjq.b32.i2p:5280
    Content-Length: 258
    User-Agent: MYOB/6.66 (AN/ON)
    Content-Type: text/xml; charset=UTF-8
    Accept-Encoding: gzip, deflate
    
    <body content="text/xml; charset=utf-8" hold="1" rid="2051961765" to="uxpug2bqoujpbjgtwogesqvixybtknziv7ieu3jfhuyxs5b4afjq.b32.i2p" ver="1.6" wait="60" xml:lang="en" xmlns="http://jabber.org/protocol/httpbind" xmlns:xmpp="urn:xmpp:xbosh" xmpp:version="1.0"/>
    Jun 25 21:45:31 s2sin563cf8408170	warn	Problem was: syntax error
    Jun 25 21:45:31 s2sin563cf8408170	info	Incoming s2s stream (unknown host)->(unknown host) closed: not-well-formed
    (base) raphy@pc:~$

**Comment by r4sas** [comment]
Are you restarted i2pd? (restarted, not reloaded)

**Comment by raphael10-collab** [comment]
Yes I did.
To be sure I repeated the whole process 

    (base) raphy@pc:~$ sudo systemctl restart i2pd.service 
    
    (base)raphy@pc:~$ sudo systemctl status i2pd.service
    ● i2pd.service - I2P Router written in C++
         Loaded: loaded (/lib/systemd/system/i2pd.service; enabled; vendor preset: enabled)
         Active: active (running) since Fri 2021-06-25 21:56:55 CEST; 1min 2s ago
           Docs: man:i2pd(1)
                 https://i2pd.readthedocs.io/en/latest/
        Process: 12841 ExecStart=/usr/sbin/i2pd --conf=/etc/i2pd/i2pd.conf --tunconf=/etc/i2pd/tunnels.conf --tunnelsdir=/etc/i2pd/tunnels.conf.d --pidfile=/var/run/i2pd/i2pd.pid --logfile=/var/log/i2pd/i2pd.log --daemon --service (code=exited, status=0/SUCCESS)
       Main PID: 12842 (i2pd)
          Tasks: 14 (limit: 38400)
         Memory: 6.1M
         CGroup: /system.slice/i2pd.service
                 └─12842 /usr/sbin/i2pd --conf=/etc/i2pd/i2pd.conf --tunconf=/etc/i2pd/tunnels.conf --tunnelsdir=/etc/i2pd/tunnels.conf.d --pidfile=/var/run/i2pd/i2pd.pid --logfile=/var/log/i2pd/i2pd.log --daemon --service
    
    giu 25 21:56:55 pc systemd[1]: Starting I2P Router written in C++...
    giu 25 21:56:55 pc systemd[1]: Started I2P Router written in C++.



    (base) raphy@pc:~$ sudo tail /var/log/prosody/prosody.log 
    Jun 25 21:45:31 s2sin563cf8408170	warn	Received invalid XML: POST /http-bind HTTP/1.1
    Host: uxpug2bqoujpbjgtwogesqvixybtknziv7ieu3jfhuyxs5b4afjq.b32.i2p:5280
    Content-Length: 258
    User-Agent: MYOB/6.66 (AN/ON)
    Content-Type: text/xml; charset=UTF-8
    Accept-Encoding: gzip, deflate
    
    <body content="text/xml; charset=utf-8" hold="1" rid="2051961765" to="uxpug2bqoujpbjgtwogesqvixybtknziv7ieu3jfhuyxs5b4afjq.b32.i2p" ver="1.6" wait="60" xml:lang="en" xmlns="http://jabber.org/protocol/httpbind" xmlns:xmpp="urn:xmpp:xbosh" xmpp:version="1.0"/>
    Jun 25 21:45:31 s2sin563cf8408170	warn	Problem was: syntax error
    Jun 25 21:45:31 s2sin563cf8408170	info	Incoming s2s stream (unknown host)->(unknown host) closed: not-well-formed
    (base) raphy@pc:~$

**Comment by r4sas** [comment]
That's strange, because as I see, request comes to s2s port....
Check webconsole `I2P tunnels` page.

**Comment by r4sas** [comment]
I successfully touched your BOSH address with URL:
`http://uxpug2bqoujpbjgtwogesqvixybtknziv7ieu3jfhuyxs5b4afjq.b32.i2p:5280/http-bind`

>It works! Now point your BOSH client to this URL to connect to Prosody.
>
>For more information see Prosody: Setting up BOSH.

**Comment by raphael10-collab** [comment]
Me too with Firefox: 

    It works! Now point your BOSH client to this URL to connect to Prosody.
    
    For more information see Prosody: Setting up BOSH.ù

What does that mean?

![image](https://user-images.githubusercontent.com/70313067/123481128-98b24d00-d603-11eb-94a1-a678c027b524.png)

Regarding the log message time, I saw this mismatching, and I do not understand why the log didn't catch up.

I'm not used to IRC... how to join ILITA IRC (tunnel at 127.0.0.1:6669) to #en channel ? 

    This address is restricted
    
    This address uses a network port which is normally used for purposes other than Web browsing. Firefox has canceled the request for your protection.

**Comment by r4sas** [comment]
Use HexChat for example, or web-based: http://irc.r4sas.i2p/ or http://irc.acetone.i2p/web/ (that's two different webirc clients to different servers of ILITA network).

**Comment by raphael10-collab** [comment]
Now it seems working: 

![image](https://user-images.githubusercontent.com/70313067/123482557-a8cb2c00-d605-11eb-9700-437e276ffbbc.png)


But still get this `not-well-formed` `s2s` in `prosody.log` :  

    (base) raphy@pc:~$ sudo tail /var/log/prosody/prosody.log 
    Upgrade-Insecure-Requests: 1
    User-Agent: MYOB/6.66 (AN/ON)
    Accept-Encoding: gzip, deflate
    dnt: 1
    sec-gpc: 1
    
    
    Jun 25 22:14:31 s2sin563cf83dfb70	warn	Problem was: syntax error
    Jun 25 22:14:31 s2sin563cf83dfb70	info	Incoming s2s stream (unknown host)->(unknown host) closed: not-well-formed
    Jun 25 22:33:39 mod_bosh	info	New BOSH session, assigned it sid '5d98da90-b76d-4355-9945-6b1a6d193fcc'
    (base) raphy@pc:~$

**Comment by r4sas** [comment]
That is old log record. See at its time.

**Comment by raphael10-collab** [comment]
After a day off, I just connected with my electron app client, and I don't know why, it gives `500` error:

![image](https://user-images.githubusercontent.com/70313067/123540137-bbe11780-d73d-11eb-9263-650122dbd746.png)

This is the `prosody.log` : 

    (base) raphy@pc:~$ sudo tail /var/log/prosody/prosody.log 
    Jun 25 22:58:38 general	info	Shutdown complete
    Jun 27 11:42:12 startup	info	Hello and welcome to Prosody version 0.11.4
    Jun 27 11:42:12 startup	info	Prosody is using the select backend for connection handling
    Jun 27 11:42:12 portmanager	info	Activated service 'c2s' on [::]:5222, [*]:5222
    Jun 27 11:42:12 portmanager	info	Activated service 'legacy_ssl' on no ports
    Jun 27 11:42:12 portmanager	info	Activated service 'console' on [::1]:5582, [127.0.0.1]:5582
    Jun 27 11:42:12 portmanager	info	Activated service 's2s' on [::]:5269, [*]:5269
    Jun 27 11:42:12 mod_s2s	warn	No local IPv4 or IPv6 addresses detected, outgoing connections may fail
    Jun 27 11:42:12 portmanager	info	Activated service 'http' on [::]:5280, [*]:5280
    Jun 27 11:42:12 portmanager	info	Activated service 'https' on no ports
    (base) raphy@pc:~$

**Comment by r4sas** [comment]
500 can be returned bacause your tunnel is not available. Try open http-bind link in browser.
If it not present after 5 minutes after starting i2pd, check if server tunnels is up and incoming and outgoing tunnels are present.

btw, you can click on request name to open information about it, and switch to preview tab to see what happened. I think you'll see here i2pd proxy error page.

**Comment by r4sas** [comment]
Closing issue as answered.

**Comment by raphael10-collab** [comment]
Thank you @r4sas for your kind help
