### ISSUE TITLE
libi2pdlang.so is installed in wrong directory?

### ISSUE THREAD

**Issue by tsjk** [PurpleI2P/i2pd#1672]
When building from git, I now cannot install i2pd because it fails a Gentoo QA check.
```
>>> Install net-vpn/i2pd-9999 into /tmp/portage/net-vpn/i2pd-9999/image
 * Working in BUILD_DIR: "/tmp/portage/net-vpn/i2pd-9999/work/i2pd-9999_build"
[0/1] Install the project...
-- Install configuration: "Gentoo"
-- Installing: /tmp/portage/net-vpn/i2pd-9999/image/usr/lib64/libi2pd.so
-- Installing: /tmp/portage/net-vpn/i2pd-9999/image/usr/lib64/libi2pdclient.so
-- Set runtime path of "/tmp/portage/net-vpn/i2pd-9999/image/usr/lib64/libi2pdclient.so" to ""
-- Installing: /tmp/portage/net-vpn/i2pd-9999/image/usr/lib/libi2pdlang.so
-- Installing: /tmp/portage/net-vpn/i2pd-9999/image/usr/bin/i2pd
-- Set runtime path of "/tmp/portage/net-vpn/i2pd-9999/image/usr/bin/i2pd" to ""
```

And then it says:
```
Files matching a file type that is not allowed:
   usr/lib/libi2pdlang.so
```

Is this something I need to fix while installing, or should it be fixed in the i2pd source?

**Comment by r4sas** [comment]
Where we can see build scripts used by gentoo?

**Comment by tsjk** [comment]
I use my own ebuild for building from git - the one in Gentoo only builds latest release. Please find my build here (which is a copy of the official one https://gitweb.gentoo.org/repo/gentoo.git/tree/net-vpn/i2pd/i2pd-2.38.0-r3.ebuild, but uses the git repo): https://github.com/tsjk/gentoo-ebuilds/blob/master/net-vpn/i2pd/i2pd-9999.ebuild

**Comment by r4sas** [comment]
ok, let me check...

**Comment by tsjk** [comment]
I've posted a build log here: https://pastebin.com/LnnBcPNq
If you want to see what is run.

**Comment by r4sas** [comment]
May be ;) Check if it helps.

**Comment by r4sas** [comment]
I think we can remove that lines.

Let's ask @ffontaine about that, he had implemented library install 3 years ago ;)
Also let's ask about removing other one members, who contributed to that file: @radfish, @AMDmi3, @klondi.
I'm doesn't use cmake, so I don't know if that lines really needed.

**Comment by tsjk** [comment]
I added a new patch (https://github.com/tsjk/gentoo-ebuilds/blob/master/net-vpn/i2pd/files/i2pd-2.39.0-lib-path.patch) that does the same modifications that were done previously. The new lib now ends up in /usr/lib64, and Gentoo's build system does not complain. :)

**Comment by ffontaine** [comment]
Sure, you can remove those lines.

**Comment by klondi** [comment]
Hello,

This patch was most likely introduced because installing the .so files on $PREFIX/lib in gentoo is broken with the 17.1 profiles.

Before 17.1 lib was a symlink to lib64 so all was fine. Afterwards, lib was the new lib32 thus an 64-bit ABI install should not be touching that folder (which is likely why the sandbox trigger the error). Hence why you need to patch the cmake so it will default to the right lib directory. To read more: https://wiki.gentoo.org/wiki/Project:AMD64/Multilib_layout#SYMLINK_LIB.3Dno_layout_.2817.1_profiles.29

**Comment by tsjk** [comment]
Yeah, seems to be Gentoo specific, and I do run the 17.1 profile (the others are deprecated). Anyways, thanks for your help. I guess this can be closed, as what was needed was an extension of a Gentoo-specific patch.

**Comment by r4sas** [comment]
@tsjk, can you try this?

```diff
--- a/build/CMakeLists.txt
+++ b/build/CMakeLists.txt
@@ -27,6 +27,9 @@ option(WITH_THREADSANITIZER "Build with thread sanitizer unix only"   OFF)
 set(CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake_modules")
 set(CMAKE_SOURCE_DIR "..")

+#Handle paths nicely
+include(GNUInstallDirs)
+
 # architecture
 include(TargetArch)
 target_architecture(ARCHITECTURE)
@@ -48,8 +51,8 @@ set_target_properties(libi2pd PROPERTIES PREFIX "")
 if(WITH_LIBRARY)
   install(TARGETS libi2pd
     EXPORT libi2pd
-    ARCHIVE DESTINATION lib
-    LIBRARY DESTINATION lib
+    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
+    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
     COMPONENT Libraries)
 # TODO Make libi2pd available to 3rd party projects via CMake as imported target
 # FIXME This pulls stdafx
@@ -63,8 +66,8 @@ set_target_properties(libi2pdclient PROPERTIES PREFIX "")
 if(WITH_LIBRARY)
   install(TARGETS libi2pdclient
     EXPORT libi2pdclient
-    ARCHIVE DESTINATION lib
-    LIBRARY DESTINATION lib
+    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
+    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
     COMPONENT Libraries)
 endif()

@@ -75,8 +78,8 @@ set_target_properties(libi2pdlang PROPERTIES PREFIX "")
 if(WITH_LIBRARY)
   install(TARGETS libi2pdlang
     EXPORT libi2pdlang
-    ARCHIVE DESTINATION lib
-    LIBRARY DESTINATION lib
+    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
+    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
     COMPONENT Libraries)
 endif()

@@ -272,9 +275,6 @@ message(STATUS "  ADDRSANITIZER    : ${WITH_ADDRSANITIZER}")
 message(STATUS "  THREADSANITIZER  : ${WITH_THREADSANITIZER}")
 message(STATUS "---------------------------------------")

-#Handle paths nicely
-include(GNUInstallDirs)
-
 if(WITH_BINARY)
   add_executable("${PROJECT_NAME}" ${DAEMON_SRC})

```

**Comment by tsjk** [comment]
@r4sas, yes - that did work as well on my Gentoo system.

**Comment by r4sas** [comment]
@tsjk thanks. I've pushed changes to repo. Don't forget to remove old patch file.
