### ISSUE TITLE
[Feature] ALFIS DNS support

### ISSUE THREAD

**Issue by cofob** [PurpleI2P/i2pd#1674]
Is it possible to introduce support for [ALFIS](https://github.com/Revertron/Alfis) DNS?  It is a blockchain-based de-centralized DNS that could replace the current implementation of domain names.

**Comment by yhaenggi** [comment]
Decentralized DNS is not something new, it exists since 2011 with Namecoin.

I2P uses .i2p TLD, how would you want to use another TLD inside i2p? As an DNS server that points to b32 addresses?

**Comment by cofob** [comment]
> Decentralized DNS is not something new, it exists since 2011 with Namecoin.
> 
> I2P uses .i2p TLD, how would you want to use another TLD inside i2p? As an DNS server that points to b32 addresses?

It is possible to add a TXT record of the _i2p.domain type containing a b32 address to domains.  This will also add support for b32 addresses to regular DNS.

**Comment by r4sas** [comment]
Closing the issue as unplanned
