### ISSUE TITLE
How to reconfigure WebConsole Service to bind either the Linux Container's address or bind all addresses ?

### ISSUE THREAD

**Issue by raphael10-collab** [PurpleI2P/i2pd#1675]
As explained here: https://webchat.freenode.net/?channels=i2pd-dev

In Ubuntu 20.04 I have a working service that has webconsole:

![image](https://user-images.githubusercontent.com/70313067/126810439-bd6282e5-164f-4851-abea-d8d4f2218759.png)

Within Ubuntu 20.04 I created a Linux Container whose O.S. is Ubuntu 20.04 as well, that I called "ubuntuone"

I installed within this Linux Container the same service `I2PD` which seems working fine as well:

    root@ubuntuone:/# systemctl status i2pd
    ● i2pd.service - I2P Router written in C++
         Loaded: loaded (/lib/systemd/system/i2pd.service; enabled; vendor preset: enabled)
         Active: active (running) since Fri 2021-07-23 15:43:40 UTC; 21min ago
           Docs: man:i2pd(1)
                 https://i2pd.readthedocs.io/en/latest/
        Process: 4937 ExecStart=/usr/sbin/i2pd --conf=/etc/i2pd/i2pd.conf --tunconf=/etc/i2pd/tunnels.con>
       Main PID: 4938 (i2pd)
          Tasks: 14 (limit: 38400)
         Memory: 7.3M
         CGroup: /system.slice/i2pd.service
                 └─4938 /usr/sbin/i2pd --conf=/etc/i2pd/i2pd.conf --tunconf=/etc/i2pd/tunnels.conf --tunn>
    
    Jul 23 15:43:40 ubuntuone systemd[1]: Starting I2P Router written in C++...
    Jul 23 15:43:40 ubuntuone systemd[1]: Started I2P Router written in C++.
    root@ubuntuone:/# 

The problem is I'm not able to use the WebConsole of this service.

This is the output of `lxc info` :  

    (base) raphy@pc:~$ lxc info
    config:
      core.https_address: 192.168.1.6
    api_extensions:
    - storage_zfs_remove_snapshots
    - container_host_shutdown_timeout
    - container_stop_priority
    - container_syscall_filtering
    - auth_pki
    - container_last_used_at
    - etag
    - patch
    - usb_devices
    - https_allowed_credentials
    - image_compression_algorithm
    - directory_manipulation
    - container_cpu_time
    - storage_zfs_use_refquota
    - storage_lvm_mount_options
    - network
    - profile_usedby
    - container_push
    - container_exec_recording
    - certificate_update
    - container_exec_signal_handling
    - gpu_devices
    - container_image_properties
    - migration_progress
    - id_map
    - network_firewall_filtering
    - network_routes
    - storage
    - file_delete
    - file_append
    - network_dhcp_expiry
    - storage_lvm_vg_rename
    - storage_lvm_thinpool_rename
    - network_vlan
    - image_create_aliases
    - container_stateless_copy
    - container_only_migration
    - storage_zfs_clone_copy
    - unix_device_rename
    - storage_lvm_use_thinpool
    - storage_rsync_bwlimit
    - network_vxlan_interface
    - storage_btrfs_mount_options
    - entity_description
    - image_force_refresh
    - storage_lvm_lv_resizing
    - id_map_base
    - file_symlinks
    - container_push_target
    - network_vlan_physical
    - storage_images_delete
    - container_edit_metadata
    - container_snapshot_stateful_migration
    - storage_driver_ceph
    - storage_ceph_user_name
    - resource_limits
    - storage_volatile_initial_source
    - storage_ceph_force_osd_reuse
    - storage_block_filesystem_btrfs
    - resources
    - kernel_limits
    - storage_api_volume_rename
    - macaroon_authentication
    - network_sriov
    - console
    - restrict_devlxd
    - migration_pre_copy
    - infiniband
    - maas_network
    - devlxd_events
    - proxy
    - network_dhcp_gateway
    - file_get_symlink
    - network_leases
    - unix_device_hotplug
    - storage_api_local_volume_handling
    - operation_description
    - clustering
    - event_lifecycle
    - storage_api_remote_volume_handling
    - nvidia_runtime
    - container_mount_propagation
    - container_backup
    - devlxd_images
    - container_local_cross_pool_handling
    - proxy_unix
    - proxy_udp
    - clustering_join
    - proxy_tcp_udp_multi_port_handling
    - network_state
    - proxy_unix_dac_properties
    - container_protection_delete
    - unix_priv_drop
    - pprof_http
    - proxy_haproxy_protocol
    - network_hwaddr
    - proxy_nat
    - network_nat_order
    - container_full
    - candid_authentication
    - backup_compression
    - candid_config
    - nvidia_runtime_config
    - storage_api_volume_snapshots
    - storage_unmapped
    - projects
    - candid_config_key
    - network_vxlan_ttl
    - container_incremental_copy
    - usb_optional_vendorid
    - snapshot_scheduling
    - snapshot_schedule_aliases
    - container_copy_project
    - clustering_server_address
    - clustering_image_replication
    - container_protection_shift
    - snapshot_expiry
    - container_backup_override_pool
    - snapshot_expiry_creation
    - network_leases_location
    - resources_cpu_socket
    - resources_gpu
    - resources_numa
    - kernel_features
    - id_map_current
    - event_location
    - storage_api_remote_volume_snapshots
    - network_nat_address
    - container_nic_routes
    - rbac
    - cluster_internal_copy
    - seccomp_notify
    - lxc_features
    - container_nic_ipvlan
    - network_vlan_sriov
    - storage_cephfs
    - container_nic_ipfilter
    - resources_v2
    - container_exec_user_group_cwd
    - container_syscall_intercept
    - container_disk_shift
    - storage_shifted
    - resources_infiniband
    - daemon_storage
    - instances
    - image_types
    - resources_disk_sata
    - clustering_roles
    - images_expiry
    - resources_network_firmware
    - backup_compression_algorithm
    - ceph_data_pool_name
    - container_syscall_intercept_mount
    - compression_squashfs
    - container_raw_mount
    - container_nic_routed
    - container_syscall_intercept_mount_fuse
    - container_disk_ceph
    - virtual-machines
    - image_profiles
    - clustering_architecture
    - resources_disk_id
    - storage_lvm_stripes
    - vm_boot_priority
    - unix_hotplug_devices
    - api_filtering
    - instance_nic_network
    - clustering_sizing
    - firewall_driver
    - projects_limits
    - container_syscall_intercept_hugetlbfs
    - limits_hugepages
    - container_nic_routed_gateway
    - projects_restrictions
    - custom_volume_snapshot_expiry
    - volume_snapshot_scheduling
    - trust_ca_certificates
    - snapshot_disk_usage
    - clustering_edit_roles
    - container_nic_routed_host_address
    - container_nic_ipvlan_gateway
    - resources_usb_pci
    - resources_cpu_threads_numa
    - resources_cpu_core_die
    - api_os
    - container_nic_routed_host_table
    - container_nic_ipvlan_host_table
    - container_nic_ipvlan_mode
    - resources_system
    - images_push_relay
    - network_dns_search
    - container_nic_routed_limits
    - instance_nic_bridged_vlan
    - network_state_bond_bridge
    - usedby_consistency
    - custom_block_volumes
    - clustering_failure_domains
    - resources_gpu_mdev
    - console_vga_type
    - projects_limits_disk
    - network_type_macvlan
    - network_type_sriov
    - container_syscall_intercept_bpf_devices
    - network_type_ovn
    - projects_networks
    - projects_networks_restricted_uplinks
    - custom_volume_backup
    - backup_override_name
    - storage_rsync_compression
    - network_type_physical
    - network_ovn_external_subnets
    - network_ovn_nat
    - network_ovn_external_routes_remove
    - tpm_device_type
    - storage_zfs_clone_copy_rebase
    - gpu_mdev
    - resources_pci_iommu
    - resources_network_usb
    - resources_disk_address
    - network_physical_ovn_ingress_mode
    - network_ovn_dhcp
    - network_physical_routes_anycast
    - projects_limits_instances
    - network_state_vlan
    - instance_nic_bridged_port_isolation
    - instance_bulk_state_change
    - network_gvrp
    - instance_pool_move
    - gpu_sriov
    - pci_device_type
    - storage_volume_state
    - network_acl
    - migration_stateful
    - disk_state_quota
    - storage_ceph_features
    - projects_compression
    - projects_images_remote_cache_expiry
    - certificate_project
    - network_ovn_acl
    - projects_images_auto_update
    - projects_restricted_cluster_target
    - images_default_architecture
    - network_ovn_acl_defaults
    - gpu_mig
    - project_usage
    - network_bridge_acl
    - warnings
    - projects_restricted_backups_and_snapshots
    - clustering_join_token
    - clustering_description
    - server_trusted_proxy
    - clustering_update_cert
    - storage_api_project
    - server_instance_driver_operational
    - server_supported_storage_drivers
    api_status: stable
    api_version: "1.0"
    auth: trusted
    public: false
    auth_methods:
    - tls
    environment:
      addresses:
      - 192.168.1.6:8443
      architectures:
      - x86_64
      - i686
      certificate: |
        -----BEGIN CERTIFICATE-----
        MIIB+TCCAX6gAwIBAgIRANjkmICsSm4cqozM/4OZs5owCgYIKoZIzj0EAwMwMDEc
        MBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEQMA4GA1UEAwwHcm9vdEBwYzAe
        Fw0yMTA3MjIxNTE3NTlaFw0zMTA3MjAxNTE3NTlaMDAxHDAaBgNVBAoTE2xpbnV4
        Y29udGFpbmVycy5vcmcxEDAOBgNVBAMMB3Jvb3RAcGMwdjAQBgcqhkjOPQIBBgUr
        gQQAIgNiAAQrkF3Bp9Y0GDmROH//hqVuD91zcBzwDJh68wuTjRIAl6uxMAPedxel
        EyMzrvX6aF/hKbcHAxprwUvt856qDvGwFEbwcsh64aA4yCWIo6Uq1ZRcB55vm/hN
        n6YqRV+y7qujXDBaMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggrBgEFBQcD
        ATAMBgNVHRMBAf8EAjAAMCUGA1UdEQQeMByCAnBjhwR/AAABhxAAAAAAAAAAAAAA
        AAAAAAABMAoGCCqGSM49BAMDA2kAMGYCMQCM6U0jXSzObbf+LiUglVwcvtJIL8kn
        D9vXaAc/dX1f98P16StCwK28qc3WYub9WLcCMQDqvVF45VMwOWDxBlL/7dpzHPAB
        P70LXb4ehc921Xontkx9SMmcodJglmQVPGKcNZ0=
        -----END CERTIFICATE-----
      certificate_fingerprint: 5a6a3d142b20c5aeb37445835b226c00ac5f9bb7740400fd8546966d8ab3d6d1
      driver: lxc
      driver_version: 4.0.10
      firewall: xtables
      kernel: Linux
      kernel_architecture: x86_64
      kernel_features:
        netnsid_getifaddrs: "true"
        seccomp_listener: "true"
        seccomp_listener_continue: "true"
        shiftfs: "false"
        uevent_injection: "true"
        unpriv_fscaps: "true"
      kernel_version: 5.8.0-63-generic
      lxc_features:
        cgroup2: "true"
        devpts_fd: "true"
        idmapped_mounts_v2: "true"
        mount_injection_file: "true"
        network_gateway_device_route: "true"
        network_ipvlan: "true"
        network_l2proxy: "true"
        network_phys_macvlan_mtu: "true"
        network_veth_router: "true"
        pidfd: "true"
        seccomp_allow_deny_syntax: "true"
        seccomp_notify: "true"
        seccomp_proxy_send_notify_fd: "true"
      os_name: Ubuntu
      os_version: "20.04"
      project: default
      server: lxd
      server_clustered: false
      server_name: pc
      server_pid: 3184
      server_version: "4.16"
      storage: zfs
      storage_version: 0.8.4-1ubuntu11.2
      storage_supported_drivers:
      - name: ceph
        version: 15.2.13
        remote: true
      - name: btrfs
        version: 5.4.1
        remote: false
      - name: cephfs
        version: 15.2.13
        remote: true
      - name: dir
        version: "1"
        remote: false
      - name: lvm
        version: 2.03.07(2) (2019-11-30) / 1.02.167 (2019-11-30) / 4.42.0
        remote: false
      - name: zfs
        version: 0.8.4-1ubuntu11.2
        remote: false

So, as far as I understand, I should be able to see the webconsole at 192.168.1.6:7070 address
but I get:
    
    This site can’t be reachedhttp://192.168.1.6:7070/ is unreachable.
    ERR_ADDRESS_UNREACHABLE

Thanks to the LXD Expert:  https://github.com/lxc/lxd/issues/9040 I discovered that I should modify the I2PD's WebConsole IP Address  in order to bind the Web Console service to the Linux Container's address.

So, I tried to modify the address in `etc/i2pd/i2pd.conf` :  

first to match the Linux Container's address:

    [http]
    ## Web Console settings
    ## Uncomment and set to 'false' to disable Web Console
    # enabled = true
    ## Address and port service will listen on
    #address = 127.0.0.1
    address = 192.168.1.6
    port = 7070

and then to match all IP addresses:

    [http]
    ## Web Console settings
    ## Uncomment and set to 'false' to disable Web Console
    # enabled = true
    ## Address and port service will listen on
    #address = 127.0.0.1
    address = ""
    port = 7070

but  when I insert in the browser 192.168.1.6:7070 I get : 
`ERR_ADDRESS_UNREACHABLE`

This is the complete /etc/i2pd/i2pd.conf ` : 

    

    # Configuration file for a typical i2pd user
    ## See https://i2pd.readthedocs.io/en/latest/user-guide/configuration/
    ## for more options you can use in this file.
    
    ## Lines that begin with "## " try to explain what's going on. Lines
    ## that begin with just "#" are disabled commands: you can enable them
    ## by removing the "#" symbol.
    
    ## Tunnels config file
    ## Default: ~/.i2pd/tunnels.conf or /var/lib/i2pd/tunnels.conf
    # tunconf = /var/lib/i2pd/tunnels.conf
    
    ## Tunnels config files path
    ## Use that path to store separated tunnels in different config files.
    ## Default: ~/.i2pd/tunnels.d or /var/lib/i2pd/tunnels.d
    # tunnelsdir = /var/lib/i2pd/tunnels.conf.d
    
    ## Where to write pidfile (don't write by default)
    # pidfile = /var/run/i2pd.pid
    
    ## Logging configuration section
    ## By default logs go to stdout with level 'info' and higher
    ##
    ## Logs destination (valid values: stdout, file, syslog)
    ##  * stdout - print log entries to stdout
    ##  * file - log entries to a file
    ##  * syslog - use syslog, see man 3 syslog
    log = file
    ## Path to logfile (default - autodetect)
     logfile = /var/log/i2pd/i2pd.log
    ## Log messages above this level (debug, *info, warn, error, none)
    ## If you set it to none, logging will be disabled
    # loglevel = info
    ## Write full CLF-formatted date and time to log (default: write only time)
    # logclftime = true
    
    ## Daemon mode. Router will go to background after start
    # daemon = true
    
    ## Specify a family, router belongs to (default - none)
    # family =
    
    ## External IP address to listen for connections
    ## By default i2pd sets IP automatically
    # host = 1.2.3.4
    
    ## Port to listen for connections
    ## By default i2pd picks random port. You MUST pick a random number too,
    ## don't just uncomment this
    # port = 4567
    
    ## Enable communication through ipv4
    ipv4 = true
    ## Enable communication through ipv6
    ipv6 = false
    
    ## Network interface to bind to
    # ifname =
    ## You can specify different interfaces for IPv4 and IPv6
    # ifname4 = 
    # ifname6 = 
    
    ## Enable NTCP transport (default = true)
    # ntcp = true
    ## If you run i2pd behind a proxy server, you can only use NTCP transport with ntcpproxy option 
    ## Should be http://address:port or socks://address:port
    # ntcpproxy = http://127.0.0.1:8118
    ## Enable SSU transport (default = true)
    # ssu = true
    
    ## Should we assume we are behind NAT? (false only in MeshNet)
     nat = true
    
    ## Bandwidth configuration
    ## L limit bandwidth to 32KBs/sec, O - to 256KBs/sec, P - to 2048KBs/sec,
    ## X - unlimited
    ## Default is X for floodfill, L for regular node
    # bandwidth = L
    ## Max % of bandwidth limit for transit. 0-100. 100 by default
    # share = 100
    
    ## Router will not accept transit tunnels, disabling transit traffic completely
    ## (default = false)
    # notransit = true
    
    ## Router will be floodfill
    # floodfill = true
    
    [http]
    ## Web Console settings
    ## Uncomment and set to 'false' to disable Web Console
    # enabled = true
    ## Address and port service will listen on
    #address = 127.0.0.1
    address = 192.168.1.6
    port = 7070
    ## Path to web console, default "/"
    # webroot = /
    ## Uncomment following lines to enable Web Console authentication 
    # auth = true
    # user = i2pd
    # pass = changeme
    
    httpproxy]
    ## Uncomment and set to 'false' to disable HTTP Proxy
    # enabled = true
    ## Address and port service will listen on
    #address = 127.0.0.1
    address = 192.168.1.6
    port = 4444
    ## Optional keys file for proxy local destination
    # keys = http-proxy-keys.dat
    ## Enable address helper for adding .i2p domains with "jump URLs" (default: true)
    # addresshelper = true
    ## Address of a proxy server inside I2P, which is used to visit regular Internet
    # outproxy = http://false.i2p
    ## httpproxy section also accepts I2CP parameters, like "inbound.length" etc.
    
    [socksproxy]
    ## Uncomment and set to 'false' to disable SOCKS Proxy
    # enabled = true
    ## Address and port service will listen on
    #address = 127.0.0.1
    address = 192.168.1.6
    port = 4447
    ## Optional keys file for proxy local destination
    # keys = socks-proxy-keys.dat
    ## Socks outproxy. Example below is set to use Tor for all connections except i2p
    ## Uncomment and set to 'true' to enable using of SOCKS outproxy
    # outproxy.enabled = false
    ## Address and port of outproxy
    # outproxy = 127.0.0.1
    # outproxyport = 9050
    ## socksproxy section also accepts I2CP parameters, like "inbound.length" etc.
    
    [sam]
    ## Uncomment and set to 'true' to enable SAM Bridge
    enabled = true
    ## Address and port service will listen on
    # address = 127.0.0.1
    address = 192.168.1.6
    port = 7656
    
    [bob]
    ## Uncomment and set to 'true' to enable BOB command channel
    # enabled = false
    ## Address and port service will listen on
    # address = 127.0.0.1
    # port = 2827
    
    [i2cp]
    ## Uncomment and set to 'true' to enable I2CP protocol
    # enabled = false
    ## Address and port service will listen on
    # address = 127.0.0.1
    # port = 7654
    
    [i2pcontrol]
    ## Uncomment and set to 'true' to enable I2PControl protocol
    # enabled = false
    ## Address and port service will listen on
    # address = 127.0.0.1
    # port = 7650
    ## Authentication password. "itoopie" by default
    # password = itoopie
    
    [precomputation]
    ## Enable or disable elgamal precomputation table
    ## By default, enabled on i386 hosts
    # elgamal = true
    
    [upnp]
    ## Enable or disable UPnP: automatic port forwarding (enabled by default in WINDOWS, ANDROID)
    # enabled = false
    ## Name i2pd appears in UPnP forwardings list (default = I2Pd)
    # name = I2Pd
    
    [reseed]
    ## Options for bootstrapping into I2P network, aka reseeding
    ## Enable or disable reseed data verification.
    verify = true
    ## URLs to request reseed data from, separated by comma
    ## Default: "mainline" I2P Network reseeds
    # urls = https://reseed.i2p-projekt.de/,https://i2p.mooo.com/netDb/,https://netdb.i2p2.no/
    ## Path to local reseed data file (.su3) for manual reseeding
    # file = /path/to/i2pseeds.su3
    ## or HTTPS URL to reseed from
    # file = https://legit-website.com/i2pseeds.su3
    ## Path to local ZIP file or HTTPS URL to reseed from
    # zipfile = /path/to/netDb.zip
    ## If you run i2pd behind a proxy server, set proxy server for reseeding here
    ## Should be http://address:port or socks://address:port
    # proxy = http://127.0.0.1:8118
    ## Minimum number of known routers, below which i2pd triggers reseeding. 25 by default
    # threshold = 25
    
    [addressbook]
    ## AddressBook subscription URL for initial setup
    ## Default: inr.i2p at "mainline" I2P Network
    # defaulturl = http://joajgazyztfssty4w2on5oaqksz6tqoxbduy553y34mf4byv6gpq.b32.i2p/export/alive-hosts.txt
    ## Optional subscriptions URLs, separated by comma
    # subscriptions = http://inr.i2p/export/alive-hosts.txt,http://stats.i2p/cgi-bin/newhosts.txt,http://rus.i2p/hosts.txt
    
    [limits]
    ## Maximum active transit sessions (default:2500)
    # transittunnels = 2500
    ## Limit number of open file descriptors (0 - use system limit)  
    # openfiles = 0
    ## Maximum size of corefile in Kb (0 - use system limit) 
    # coresize = 0
    ## Threshold to start probabalistic backoff with ntcp sessions (0 - use system limit) 
    # ntcpsoft = 0
    ## Maximum number of ntcp sessions (0 - use system limit) 
    # ntcphard = 0
    
    [trust]
    ## Enable explicit trust options. false by default
    # enabled = true
    ## Make direct I2P connections only to routers in specified Family.
    # family = MyFamily
    ## Make direct I2P connections only to routers specified here. Comma separated list of base64 identities.
    # routers = 
    ## Should we hide our router from other routers? false by default
    # hidden = true
    
    [exploratory]
    ## Exploratory tunnels settings with default values
    # inbound.length = 2 
    # inbound.quantity = 3
    # outbound.length = 2
    # outbound.quantity = 3
    
    [persist]
    ## Save peer profiles on disk (default: true)
    # profiles = true

    root@ubuntuone:/# netstat -lnp | grep i2pd
    tcp        0      0 0.0.0.0:10339           0.0.0.0:*               LISTEN      5429/i2pd           
    tcp        0      0 127.0.0.1:6668          0.0.0.0:*               LISTEN      5429/i2pd           
    udp        0      0 0.0.0.0:10339           0.0.0.0:*                           5429/i2pd           
    root@ubuntuone:/# 

How to solve the problem?

**Comment by r4sas** [comment]
> and then to match all IP addresses

You done it wrong. set to "0.0.0.0".

Secondly, current value "192.168.1.6" is correct, so I think you must see in `ufw` or `iptables` configuration of your container and host. `ERR_ADDRESS_UNREACHABLE` means only that your host can't reach container at all.

Please check requesting of webconsole with `curl` for example: `curl http://192.168.1.6:7070`. If here no result, check firewall rules as I described earlier.
