### ISSUE TITLE
15:23:22@653/error - Identity: Unknown crypto key type 4

### ISSUE THREAD

**Issue by xanoni** [PurpleI2P/i2pd#1676]
What is this? Some configuration error?

![image](https://user-images.githubusercontent.com/77220130/126886828-0c0d4c1a-d548-41d0-9fcb-0804615be812.png)

**Comment by r4sas** [comment]
Version?

**Comment by xanoni** [comment]
Default from Raspbian 32 bit repository:
```
$ i2pd --version
i2pd version 2.23.0 (0.9.38)
Boost version 1.67.0
OpenSSL 1.1.1a  20 Nov 2018
```

**Comment by r4sas** [comment]
Huh, too old.
Use our repository with latest releases: https://repo.i2pd.xyz/

**Comment by xanoni** [comment]
Meh. They also shipped an ancient version of Tor. Thank you.
