### ISSUE TITLE
Proxy error: Host is down

### ISSUE THREAD

**Issue by inaryart** [PurpleI2P/i2pd#1678]
Can't create connection to requested host, it may be down. Please try again later.

---------------
A good idea is that i2pd can connect to a third-party vpn through the (http/socket5) proxy to ensure that i2pd can be used normally, and i2pd can be connected to the Internet normally.

---------

1. vpn(Listen: http//:127.0.0.1:3333)  

2. i2pd (Listen: http//:127.0.0.1:4444)		

3. i2pd to connect to vpn(http//:127.0.0.1:3333), I2pd is now available

4. firfox to connect to i2pd (http//:127.0.0.1:4444)

5. firefox can use the i2pd network normally at this time

**Comment by r4sas** [comment]
Maybe your requested host is really down?

Don't forget that first start and integration to network requires at least 10 minutes. Later, it's enough about 3 minutes to correctly request any alive destinations.

So question is: what is your current problem? Seems like your network chain configured correctly, if i2pd is able to connect to internet.
