### ISSUE TITLE
partial deadlock when close/reset stream flags get lost

### ISSUE THREAD

**Issue by simonvetter** [PurpleI2P/i2pd#1684]
i2pd seems to partially lock up if the last packets of a stream, containing either the reset or close flag, are lost.

Steps to reproduce:
- enable either the http or socks proxy
- set loglevel to debug (not necessary to trigger the bug, merely to notice it happening)
- request any eepsite URL (i've been using curl to do this, like so:
```bash
curl --proxy http://localhost:4444 http://zzz.i2p/ --verbose
```
- repeat the request as many times as needed until curl hangs (with either a partial output or no output at all)
- on the webconsole, notice how router/tunnel statistics seem frozen and how the tunnel build queue keeps growing in size.

I've seen the bug happen with both socks and http proxies, which makes sense as the bug most likely comes from the Stream class.

See attached log (verbosity set to debug): the first requests do complete as close/reset flags are received:
```
15:38:02@7/debug - Streaming: Received seqn=23 on sSID=2943373031
15:38:02@7/debug - Streaming: Process seqn=23, flags=64
15:38:02@7/debug - Streaming: Received seqn=24 on sSID=2943373031
15:38:02@7/debug - Streaming: Process seqn=24, flags=74
15:38:02@7/debug - Streaming: FIN sent, sSID=2943373031
15:38:02@7/debug - Streaming: closing stream with sSID=2943373031, rSID=1432426555, status=5
15:38:02@7/debug - Streaming: Stream deleted
```
while the last one waits forever, waiting for close/reset flags which will never arrive:

```
15:44:25@7/debug - HTTPProxy: sock recv: 133 bytes, recv buf: 0, send buf: 0
15:44:25@7/debug - HTTPProxy: requested: http://zzz.i2p/
15:44:25@7/debug - HTTPProxy: connecting to host zzz.i2p:80
15:44:25@7/debug - HTTPProxy: Created new I2PTunnel stream, sSID=0, rSID=3190230736
15:44:26@7/debug - Streaming: Packet 0 acknowledged rtt=1198 sentTime=1628869465752
15:44:26@7/debug - Streaming: Received seqn=0 on sSID=60946884
15:44:26@7/debug - Streaming: Process seqn=0, flags=2217
15:44:26@7/debug - Streaming: Max packet size 1812
15:44:27@7/debug - Streaming: Received seqn=1 on sSID=60946884
15:44:27@7/debug - Streaming: Process seqn=1, flags=0
[...]
15:44:27@7/debug - Streaming: Process seqn=7, flags=0
15:44:27@7/debug - Streaming: Received seqn=8 on sSID=60946884
15:44:27@7/debug - Streaming: Process seqn=8, flags=0
15:44:27@7/debug - Streaming: Received seqn=9 on sSID=60946884
15:44:27@7/debug - Streaming: Process seqn=9, flags=0
```
Since those flags are usually in the very last packets of a stream, no further packet will follow. No NACK will be sent and the final packet won't ever be retransmitted.

There doesn't seem to be any idle timer in the stream handler, which is probably why my node never times out.

I haven't been able to find out why the router would stop establishing new tunnels while a stream is active (is there any lock anywhere?), but I believe it may be problematic in case of long lived streams (e.g. ssh session).

I'm using the latest version (openssl branch). My instances are ipv6-only, either on x86_64 or armhf architectures, running on up to date debian 10 systems.

[i2p.log](https://github.com/PurpleI2P/i2pd/files/6984073/i2p.log)

**Comment by simonvetter** [comment]
Relevant config file:
```ini
log = true
loglevel = debug
ipv6 = true
ipv4 = false
port = 48831
bandwidth = X
netid = 2
ssu = true
floodfill = true
daemon = false

[httpproxy]
port = 6114
enabled = true

[socksproxy]
enabled = true
port = 6115

[sam]
enabled = false

[bob]
enabled = false

[i2cp]
enabled = false

[upnp]
enabled = false

[ntcp2]
enabled = true
published = true
port = 9827
```

If that helps, I've found that I had to kill i2pd with sigkill once locked up. A graceful shutdown by way of sigterm wouldn't do.

**Comment by r4sas** [comment]
They timed out, but after ~3 minutes. Here some kind of resend algorithm present: https://github.com/PurpleI2P/i2pd/blob/openssl/libi2pd/Streaming.cpp#L898-L902

**Comment by simonvetter** [comment]
I'll try to dig deeper into the code, but as far as I can tell they never timed out in 15+ minutes.

Note that in the case I described (last packets from an HTTP request being lost), the router proxying the HTTP request most likely doesn't need to resend anything as all of its data packets have already been ACK'd.

**Comment by simonvetter** [comment]
Closing this since I haven't been able to reproduce.
