### ISSUE TITLE
Bandwidth configuration in /etc/i2pd/i2pd.conf

### ISSUE THREAD

**Issue by slrslr** [PurpleI2P/i2pd#1704]
Hello,
if i want to dedicate all available bandwidth to i2p, do i need to modify the i2pd.conf anyhow?

```
## Bandwidth configuration
## L limit bandwidth to 32KBs/sec, O - to 256KBs/sec, P - to 2048KBs/sec,
## X - unlimited
## Default is X for floodfill, L for regular node
# bandwidth = L
## Max % of bandwidth limit for transit. 0-100. 100 by default
# share = 100
bandwidth = X
## Router will be floodfill
# floodfill = true
```

i have added the "bandwidth = X" line... but i have read that "FloodFill gets enabled automatically if your router meets the requirements (>32KB/s, not using "Laptop Mode," online for at least one or two days straight, and a certain amount of reliability)" [here](https://www.reddit.com/r/i2p/comments/3jhb7k/what_speeds_help_the_network_a_lot/)

I did it right or what to do to make sure i21pd will use/relay maximum bandwidth of the computer?

In the quoted paragraph, i think the description should be improved as it confuse me whether default is X or L because line shows L ("# bandwidth = L") but earlier you mention "Default is X".

**Comment by r4sas** [comment]
No, `bandwidth = X` will be enabled automatictly if you enable `floodfill = true`, esle in `false` is set and `bandwidth = X` that will make use your whole available bandwidth without floodfill mode.

> i have added the "bandwidth = X" line... but i have read that "FloodFill gets enabled automatically if your router meets the requirements (>32KB/s, not using "Laptop Mode," online for at least one or two days straight, and a certain amount of reliability)" [here](https://www.reddit.com/r/i2p/comments/3jhb7k/what_speeds_help_the_network_a_lot/)

That correct only for Java I2P?

**Comment by slrslr** [comment]
> If floodfill = true than bandwidth defaults to X and setting in config ignored, otherwise it set to L.

then i think this i2pd.conf line:
[\## Default is X for floodfill, L for regular node](https://github.com/PurpleI2P/i2pd/blob/2bdfcedd0e7acf9616b7204896fa8497043b8b07/contrib/i2pd.conf#L84)

can be more meaningful like this:
\## Default is L and in case floodfill option below is enabled, then X is used

consider this suggestion as it is more noob friendly

So to use maximum bandwidth i need to either un-comment "floodfill" variable and make sure it is true

or

un-comment "bandwidth" variable and make sure it is X and leave floodfill disabled/commented out. 

"**Floodfill mode** is a special mode, which contributes to the I2P network more. You may want to enable floodfill mode if you have stable uptime and high bandwidth to share." [source](https://i2pd.readthedocs.io/en/latest/user-guide/FAQ/#what-is-a-floodfill-mode)

If i said something wrong, please correct it. Thank you

**Comment by slrslr** [comment]
RE: https://github.com/PurpleI2P/i2pd/commit/4ecf36fab614bf5f46967bdc12526a5048d7991a

> uncomment that line and adjust value to your possibilities

can make doubts which line and which value

**Comment by r4sas** [comment]
I think no
