### ISSUE TITLE
I2PD as library

### ISSUE THREAD

**Issue by stas29a** [PurpleI2P/i2pd#1709]
Hi. First of all you are doing a great project!)
I think it would be cool to have a dll library (.so for nix) in every release. I suggest it will help to build and distribute software that use I2P. A library should provide full API to manage.

**Comment by r4sas** [comment]
Hello.
Our `make` and `cmake` is already building libraries to make possible to link them where they are needed.
For example, you can call `make api` to build linking (`.a`) and shared (`.so` or `.dll`) libraries
