### ISSUE TITLE
AESNI ON on a system with no AESNI

### ISSUE THREAD

**Issue by driesmp** [PurpleI2P/i2pd#1711]
I have not yet scanned the source code but my question is simple.
Lets say I build the program with AESNI enabled and try to run it on a system that has no AESNI extensions.
Does it fall back to the other methods or will it fail to run?

I'm asking because I'd like to enable AESNI in the FreeBSD package by default and pick up maintainership.

Also, what is the default path of the certs dir these days, lets say we specify --datadir=bla to the daemon, is the certs dir then "bla/certificates"?

**Comment by r4sas** [comment]
Hello.

>Does it fall back to the other methods or will it fail to run?

Current code (since 2.35.0) uses cpuid detection on application start:
https://github.com/PurpleI2P/i2pd/blob/935e93eb36011e3e04413eee10fef5babe1e85fd/libi2pd/Crypto.cpp#L1383
which sets booleans in `i2p::cpu` namespace:
https://github.com/PurpleI2P/i2pd/blob/935e93eb36011e3e04413eee10fef5babe1e85fd/libi2pd/CPU.cpp#L27-L28
So if application built on AVX + AES supported host, when it starts on host without them application just run software-based encryption code. As example:
https://github.com/PurpleI2P/i2pd/blob/935e93eb36011e3e04413eee10fef5babe1e85fd/libi2pd/Crypto.cpp#L763-L779

But if application detects with cpuinfo extensions, which are really not working or blocked by kernel (we meet such situation few days ago on Ubuntu 21.10 with Linux kernel 5.13.0 inside VirtualBox), user can forcibly disable usage of CPU extensions using `[cpuext]` configuration block.

>Also, what is the default path of the certs dir these days, lets say we specify --datadir=bla to the daemon, is the certs dir then "bla/certificates"?

Yes, you're correct. By default certificates searched in `datadir/certificates`. But as you seen earlier in #1642, `certsdir` option was added. So in you do not want make symbolic link from  `/var/lib/i2pd/certificates` to  `/usr/share/i2pd/certificates`, you can use it with path where certificates was unpacked.

**Comment by r4sas** [comment]
My view of port can be found here: https://github.com/r4sas/i2pd-freebsd-port

**Comment by r4sas** [comment]
Short review of installed files and directories:
PREFIX/bin/i2pd <<< executable
PREFIX/shared/i2pd <<< here placed certificates directory from contrib
PREFIX/etc/i2pd/i2pd.conf.sample <<< updated by patch config
PREFIX/etc/i2pd/tunnels.conf.sample
PREFIX/etc/i2pd/tunnels.conf.d <<< directory for tunnels config files
PREFIX/var/db/i2pd <<< application datadir, where addressbook, netdb, keys are stored

**Comment by driesmp** [comment]
Ok I see, one problem here is that users that have a configuration file already present on their system customized will not get the new values in their config file which will lead to problems. What could work is an UPDATING entry, if we really want to take this approach. Another option is to add --certs-dir to the daemon flags, and see below so no user intervention is necessary.

What would be cool is an %%ETCDIR%% config option, this way only one --etcdir=%%ETCDIR%% is needed for the daemon, otherwise --conf=%%ETCDIR%%/i2pd.conf --tunconf=... --tunnelsdir=.. is needed. This will take care of the full correct installation of the package following ([hier](https://www.freebsd.org/cgi/man.cgi?hier(7)))

**Comment by r4sas** [comment]
>Ok I see, one problem here is that users that have a configuration file already present on their system customized will not get the new values in their config file which will lead to problems.

Isn't `.conf.sample` configs must be updated with every update when port is installed? I thought that user can apply changes only to `.conf` files, which won't be overwritten. As I see, `pkg-message` can be used for printing notifications on install, so why we wont use that ability to inform users about changes?

>What would be cool is an %%ETCDIR%% config option, this way only one --etcdir=%%ETCDIR%% is needed for the daemon, otherwise --conf=%%ETCDIR%%/i2pd.conf --tunconf=... --tunnelsdir=.. is needed. This will take care of the full correct installation of the package following (hier).

It will be a unnecessarily multiplication of entities. In most systems we are use symlinks from datadir to files where they placed (like /var/lib/i2pd/i2pd.conf -> /etc/i2pd/i2pd.conf). But configuration for old installations already set to /etc/i2pd/i2pd.conf tunnels readed from datadir/tunnels.conf (I didn't understand why no one placed that file to %%ETCDIR%% earlier), so adding only `--certsdir` will be enough.

>Another question, if we specify --certsdir or any other parameter to the startup command, and we specify it in the config file, which value is used? Do command like option get preference?

Yes, command line value is preferred.

**Comment by driesmp** [comment]
> > Ok I see, one problem here is that users that have a configuration file already present on their system customized will not get the new values in their config file which will lead to problems.
> 
> Isn't `.conf.sample` configs must be updated with every update when port is installed? I thought that user can apply changes only to `.conf` files, which won't be overwritten. As I see, `pkg-message` can be used for printing notifications on install, so why we wont use that ability to inform users about changes and propose to look to sample files

Yes thats correct, but I think the .conf file is also overwritten by the sample if the user did not modify it.

**Comment by r4sas** [comment]
I think in `files/patch-contrib_i2pd.conf` better to use %%PREFIX%% instead of using `/usr/local` in paths

**Comment by driesmp** [comment]
Ah yes good point

**Comment by r4sas** [comment]
> defaults still look at /var/db

That's why I ask about updating default path to `/var/db/i2pd/...`

**Comment by driesmp** [comment]
That's taken care of in the makefile with REINPLACE_COMMAND /VAR/LIB|..

**Comment by r4sas** [comment]
Ah, okay.

**Comment by driesmp** [comment]
Landed.
