### ISSUE TITLE
i2pd version

### ISSUE THREAD

**Issue by artenaki** [PurpleI2P/i2pd#1712]
Привет.
Скомпилировал i2pd-git + i2pd-qt-git и вижу в About, что версия i2pd 0.9.52
Это соответствует между маем (0.9.50) и августом (1.5.0) 2021 https://geti2p.net/en/blog/
В конце ноября 2021 вышла 1.6.1. Планируете ли вы обновление? Или в этом нет особого смысла? Например, если почти все изменения уже присутствуют в git. Наверное, все-таки нет, иначе бы версия изменилась.

**Comment by artenaki** [comment]
В связи с блокировкой Tor в России присматриваюсь к i2p, но Java версию использовать не хочется. Комп слабоват.
i2pd я и раньше пользовался, в мае тоже компилил i2pd-qt (в Ubuntu 16.04).

**Comment by artenaki** [comment]
Ага, запустил Java клиент i2p. По адресу http://127.0.0.1:7657/logs указано
API version: 0.9.52
Значит, 0.9.52 это версия API и она последняя.
Теперь понятно.
В оригинальном клиенте почти ничего не работает.

**Comment by r4sas** [comment]
0.9.50 - это 0.9.50 в Java версии, 0.9.51 - 1.5.0, 0.9.52 - 1.6.0/1.6.1.

**Comment by artenaki** [comment]
Спасибо за инфу. Интересно изучать i2p.
