### ISSUE TITLE
Стырить гайд в вики

### ISSUE THREAD

**Issue by ANANTASHESHALOKAGREENTARAEGPTRANSHOLON** [PurpleI2P/i2pd#1713]
RedFox пишет: Вопрос решился. Теперь при перезагрузке малинки сервис i2pd стартует и отвечает и переустнавливать систему не пришлось. Оказывается все было уже описано: https://howto.yggnode.cf/doku.php?id=i2p

**Comment by r4sas** [comment]
Гайд, который был взят из документации. Кого и куда тырить то?
