### ISSUE TITLE
ERROR 500: Internal Server Error

### ISSUE THREAD

**Issue by 3zhang** [PurpleI2P/i2pd#1715]
I followed all the instructions here:
https://i2pd.readthedocs.io/en/latest/user-guide/install/

My system is Debian 10.11.

After installation, I tried this:
http_proxy=127.0.0.1:4444 wget 102chan.i2p               
--2021-12-26 10:57:41--  http://102chan.i2p/
Connecting to 127.0.0.1:4444... connected.
Proxy request sent, awaiting response... 500 Internal Server Error
2021-12-26 10:57:41 ERROR 500: Internal Server Error.

What's wrong? Did I miss something?

**Comment by yhaenggi** [comment]
Its not reachable, use verbose mode eg via curl:
```
$ http_proxy=http://127.1:4444 curl -v http://102chan.i2p/
* Uses proxy env variable http_proxy == 'http://127.1:4444'
*   Trying 127.0.0.1:4444...
* Connected to 127.0.0.1 (127.0.0.1) port 4444 (#0)
> GET http://102chan.i2p/ HTTP/1.1
> Host: 102chan.i2p
> User-Agent: curl/7.79.1
> Accept: */*
> Proxy-Connection: Keep-Alive
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Connection: close
< Content-Length: 582
< Content-Type: text/html; charset=UTF-8
< Date: ****
< 
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>I2Pd HTTP proxy</title>
  <style type="text/css">
    body { font: 100%/1.5em sans-serif; margin: 0; padding: 1.5em; background: #FAFAFA; color: #103456; }
    h1 { font-size: 1.7em; color: #894C84; }
    @media screen and (max-width: 980px) { h1 { font-size: 1.7em; text-align: center; color: #894C84; }}
  </style>
</head>
<body><h1>Proxy error: Host is down</h1>
<p>Can't create connection to requested host, it may be down. Please try again later.</p>
</body>
</html>
* Closing connection 0
```

**Comment by 3zhang** [comment]
> Its not reachable, use verbose mode eg via curl:
> 
> ```
> $ http_proxy=http://127.1:4444 curl -v http://102chan.i2p/
> * Uses proxy env variable http_proxy == 'http://127.1:4444'
> *   Trying 127.0.0.1:4444...
> * Connected to 127.0.0.1 (127.0.0.1) port 4444 (#0)
> > GET http://102chan.i2p/ HTTP/1.1
> > Host: 102chan.i2p
> > User-Agent: curl/7.79.1
> > Accept: */*
> > Proxy-Connection: Keep-Alive
> > 
> * Mark bundle as not supporting multiuse
> < HTTP/1.1 500 Internal Server Error
> < Connection: close
> < Content-Length: 582
> < Content-Type: text/html; charset=UTF-8
> < Date: ****
> < 
> <html>
> <head>
>   <meta name="viewport" content="width=device-width, initial-scale=1.0">
>   <title>I2Pd HTTP proxy</title>
>   <style type="text/css">
>     body { font: 100%/1.5em sans-serif; margin: 0; padding: 1.5em; background: #FAFAFA; color: #103456; }
>     h1 { font-size: 1.7em; color: #894C84; }
>     @media screen and (max-width: 980px) { h1 { font-size: 1.7em; text-align: center; color: #894C84; }}
>   </style>
> </head>
> <body><h1>Proxy error: Host is down</h1>
> <p>Can't create connection to requested host, it may be down. Please try again later.</p>
> </body>
> </html>
> * Closing connection 0
> ```

This is what I get:

http_proxy=http://127.1:4444 curl -v http://102chan.i2p/
* Expire in 0 ms for 6 (transfer 0x562749e39fb0)
* Uses proxy env variable http_proxy == 'http://127.1:4444'
* Expire in 1 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 1 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 1 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 1 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 1 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 1 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 1 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 1 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 1 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 1 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 1 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 1 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 1 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 1 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 1 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 1 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 1 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 1 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 1 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 1 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 2 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 2 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 2 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 2 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 2 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 2 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 2 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 2 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 2 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 2 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 2 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 2 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 2 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 2 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 2 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 2 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 2 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 2 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 2 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 2 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 2 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 2 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 2 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 2 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 2 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 2 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 2 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 2 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 2 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 2 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 2 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 2 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 2 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 2 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 0 ms for 1 (transfer 0x562749e39fb0)
* Expire in 1 ms for 1 (transfer 0x562749e39fb0)
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x562749e39fb0)
* Connected to 127.1 (127.0.0.1) port 4444 (#0)
> GET http://102chan.i2p/ HTTP/1.1
> Host: 102chan.i2p
> User-Agent: curl/7.64.0
> Accept: */*
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 500 Internal Server Error
< Connection: close
< Content-Length: 1019
< Content-Type: text/html; charset=UTF-8
< Date: Sun, 26 Dec 2021 16:27:15 GMT
<
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>I2Pd HTTP proxy</title>
  <style type="text/css">
    body { font: 100%/1.5em sans-serif; margin: 0; padding: 1.5em; background: #                                                                             FAFAFA; color: #103456; }
    h1 { font-size: 1.7em; color: #894C84; }
    @media screen and (max-width: 980px) { h1 { font-size: 1.7em; text-align: ce                                                                             nter; color: #894C84; }}
  </style>
</head>
<body><h1>Proxy error: Host not found</h1>
<p>Remote host not found in router's addressbook</p>
<p>You may try to find this host on jump services below:</p>
<ul>
  <li><a href="http://3mzmrus2oron5fxptw7hw2puho3bnqmw2hqy7nw64dsrrjwdilva.b32.i                                                                             2p/cgi-bin/query?hostname=102chan.i2p">identiguy.i2p</a></li>
  <li><a href="http://shx5vqsw7usdaunyzr2qmes2fq37oumybpudrd4jjj4e4vk4uusa.b32.i                                                                             2p/jump/102chan.i2p">reg.i2p</a></li>
  <li><a href="http://7tbay5p4kzeekxvyvbf6v7eauazemsnnl2aoyqhg5jzpr5eke7tq.b32.i                                                                             2p/cgi-bin/jump.cgi?a=102chan.i2p">stats.i2p</a></li>
</ul>
</body>
</html>
* Closing connection 0

**Comment by yhaenggi** [comment]
Since the host isnt known to you, you need to use the jump services mentioned first or/and change your subscriptions. If it's not permanently down, you might have a chance to reach it in the future.
