### ISSUE TITLE
Handling of different destinations for the same domain name

### ISSUE THREAD

**Issue by marek22k** [PurpleI2P/i2pd#1718]
Hello,

I have a question. Unfortunately, I don't know who to put it to, so I thought I was going to open an issue. I'm sorry if this is the wrong place to do this.

You can define different registrars in the router's subscription list. These registrars offer a hosts.txt with the domain name and the destination. What happens if you have subscribed to hosts.txt from different registrars and they name different destinations for one domain? For example, a different destination for example.i2p could be entered for inr.i2p than for stats.i2p. If you have now subscribed to the hosts.txt from inr.i2p and stats.i2p, which entry would be preferred? Does the order of the subscriptions matter? If so, are the subscriptions that are listed above or below in the subscriptions.txt preferred?
What is the situation with i2pd implementation?

**Comment by r4sas** [comment]
1. pick random subscription
2. parse all records
3. replace only if destnation differs and it's type is not DSA.

**Comment by orignal** [comment]
From last update
