### ISSUE TITLE
tunnels.cfg not work

### ISSUE THREAD

**Issue by archeando** [PurpleI2P/i2pd#172]
Hi, tunnels.cfg not work, my settings:
[popi2p]
type=client      ; mandatory
port=7660   ; mandatory, bind our side of tunnel to this local port
destination=irc.echelon.i2p    ; mandatory
keys=;

Error:
warn - Unknown section type=client      ; mandatory of popi2p in tunnels.cf

**Comment by orignal** [comment]
Use
[popi2p]
type=client 
port=7660 
destination=irc.echelon.i2p

If you don't want to use shared loacl destination for irc specify keys file as well

**Comment by archeando** [comment]
Works well with this configuration, no spaces at the end of the line:

[popi2p]
type=client
port=7660
destination=pop.postman.i2p

[smpti2p]
type=client
port=7659
destination = smtp.postman.i2p

Thank you very much!
