### ISSUE TITLE
Error - Symmetric NAT

### ISSUE THREAD

**Issue by artenaki** [PurpleI2P/i2pd#1720]
Привет. Пользуюсь i2pd-qt. Иногда замечаю статус Error - Symmetric NAT. Это плохо? Но соединение с i2p сетью при этом есть. С помощью утилиты stun я проверял: у провайдера endpoint-independent NAT, то есть пробиваемый (в обычных торрентах есть входящие подключения, но только по UDP).

И еще вопрос: в Transit tunnels иногда бывает 1-2 транзита. Но передаваемый трафик там очень мал. Это плохо? Я бы хотел помогать сети, может, надо что-то подкрутить. Интересно, как в явовской версии обстоят дела. Для чего вообще эти транзиты?

**Comment by TomasGlgg** [comment]
> Привет. Пользуюсь i2pd-qt. Иногда замечаю статус Error - Symmetric NAT. Это плохо? Но соединение с i2p сетью при этом есть. 

Это из-за того, что роутер/провайдер меняет номер порта. Причин этому может быть много. Мне помогло удаление папки NetDb и ожидание.

>И еще вопрос: в Transit tunnels иногда бывает 1-2 транзита. Но передаваемый трафик там очень мал. Это плохо? Я бы хотел помогать сети, может, надо что-то подкрутить. 

Чем больше твоя активность  в сети, тем больше роутеров будут знать о твоем роутере и тем больше у тебя будет транзита. Если хочешь реально помочь сети: включай режим floodfill-а, тогда появятся и транзит и трафик и нагрузка на процессор.

> Для чего вообще эти транзиты?

Транзитные туннели - туннели проходящие через твой роутер.

Подробнее про работу i2p можешь почитать в этой [статье](https://habr.com/ru/post/552072/).
