### ISSUE TITLE
Windows XP

### ISSUE THREAD

**Issue by artenaki** [PurpleI2P/i2pd#1723]
Версия 2.40 не работает на XP SP3.

https://github.com/PurpleI2P/i2pd/releases/download/2.40.0/i2pd_2.40.0_winxp_mingw.zip
Точка входа в процедуру GetTickCount64 не найдена в библиотеке DLL KERNEL32.dll

https://github.com/PurpleI2P/i2pd/releases/download/2.40.0/i2pd_2.40.0_win32_mingw.zip
Точка входа в процедуру CancelIoEx не найдена в библиотеке DLL KERNEL32.dll

https://github.com/PurpleI2P/i2pd/releases/download/2.40.0/setup_i2pd_v2.40.0.exe
Не является приложением Win32

Версия 2.39-mingw работает, но при выходе (graceful shutdown или exit) падает с ошибкой
```
Microsoft Visual C++ Runtime Library
Runtime Error!
Program: C:\Program Files\i2pd\i2pd.exe
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```
Для сборки 2.40-mingw вы использовали [msys2](https://i2pd.readthedocs.io/en/latest/devs/building/windows/) или [cross-platform](https://i2pd.readthedocs.io/en/latest/devs/building/cross/)?
Может быть, сборочные зависимости в msys2 обновились.
Почему ошибка Microsoft Visual C++, если компилятор mingw?

**Comment by artenaki** [comment]
GetTickCount64
> Почитал про эту функцию. Она возвращает время работы в миллисекундах после запуска Windows. До висты в WinApi была аналогичная функция GetTickCount, но т.к. она возвращала 32-битное значение, после 49,7 суток аптайма возвращаемое значение из-за переполнения становилось равным 0 с понятными последствиями для программ, использующих эту функцию. Т.е. уже на уровне ядра система просто не предназначена для длительной непрерывной работы.

https://docs.microsoft.com/ru-ru/windows/win32/api/sysinfoapi/nf-sysinfoapi-gettickcount64
Requirements:
Minimum supported client - Windows Vista

**Comment by r4sas** [comment]
Я же уже писал в иссуе в репозитории i2pd-qt что для сборки для XP используется отдельный MSYS2 с частично пересобранными пакетами. Смотрите внимательно на архивы в релизе - там есть собранное приложение именно для XP.

**Comment by r4sas** [comment]
[i2pd_2.40.0-34-g53f19e40_winxp_mingw.zip](https://github.com/PurpleI2P/i2pd/files/7974678/i2pd_2.40.0-34-g53f19e40_winxp_mingw.zip)
Пересобранный транк для XP, проверен - работает.

**Comment by artenaki** [comment]
@r4sas
Спасибо за сборку.

> поддержку XP пора дропать

Не надо. Я только начал ей пользоваться :)

> Потому что линковка идет к CRT библиотекам винды

Этот момент мы обсуждали на лоре. Это открыло мне глаза на многое. Люди говорят так лучше не делать.

> * А кстати зачем эти редистры вообще нужны? Разве Студия не генерит совместимый Win32 код?
> * (ответ с сарказмом): Зачем нужен libc.so, разве gcc генерирует не совместимый Linux код?
> * Я примерно так и подумал. То есть, эти либы в системе есть, но они старые. А редистр это все равно, что libstdc++6 обновить. 

https://www.linux.org.ru/news/opensource/16124846?cid=16125928

> **Использование виндовой libc это неподдерживаемый юз-кейс. Хотя технически это можно делать, все настоятельно рекомендуют этого не делать. Она там лежит для компонентов винды, а не для тебя. В общем забудь. Или компилируй статически, или таскай DLL с собой, как положено.**

https://www.linux.org.ru/news/opensource/16124846?cid=16125934

> * Почему тогда не все проги требуют редистры и запускаются из коробки?
> * Mingw требует всякие такие библиотеки:
> libgcc_s_dw2-1.dll libstdc++-6.dll и прочие чтобы находились в папке с бинарником

https://www.linux.org.ru/news/opensource/16124846?cid=16125959

> Есть три основных способа. Первый способ это скомпилировать программу статически. Тогда libc и всё остальное будет в EXE-файле, ничего больше не нужно. Второй способ это положить несколько десятков DLL-ок рядом с EXE-файлом. Тоже ничего не нужно устанавливать. И третий способ это при инсталляции своей программы установить vcredist в системные каталоги. Преимущество третьего способа в экономии места, если несколько программ зависят от одной версии vcredist. Лично я бы использовал второй способ.
> Чисто теоретически можно ещё писать программу, используя исключительно WinAPI, без libc. Тогда зависимостей никаких не будет и EXE-файл будет крошечным. Но это довольно сложно делать.

https://www.linux.org.ru/news/opensource/16124846?cid=16125998

**Comment by artenaki** [comment]
Думаю, линуксоиды не совсем авторитетны.
Imports (functionality imported from external dynamically linked libraries)
msvcrt.dll
Я вижу во многих экзешниках в анализаторе virustotal.com
Вот так и верь людям.

**Comment by r4sas** [comment]
Могу только предложить им посмотреть в исходники mingw-w64-headers-git. В них почему то самим пакетом MinGW сделано так. Почему - мне не известно.
i2pd собирается с статичной линковкой, так что даже это делает программу зависимой от рантайма, только за местом libc в винде выступает MS Visual C RunTime. В линуксе, если вам не известно, тоже статичные программы не содержат в себе libc, а только линкуются к нему.

**Comment by artenaki** [comment]
> https://github.com/PurpleI2P/i2pd/files/7974678/i2pd_2.40.0-34-g53f19e40_winxp_mingw.zip

Та же ошибка. Заменил в двоичном редакторе FlexHEX GetTickCount64 нулями и запустился. А ошибки, которая была при выходе, здесь нет.

Кстати, поставил явовский I2P. Не тормозит, настроек много.

UPD: Microsoft совсем обнаглел. Сломал Github в Firefox 78. Еще сегодня днем все работало. Надо валить отсюда.

**Comment by r4sas** [comment]
> Та же ошибка. Заменил в двоичном редакторе FlexHEX GetTickCount64 нулями и запустился. А ошибки, которая была при выходе, здесь нет.

Нет там такого импорта.

**Comment by artenax** [comment]
Кажется, ошибка GetTickCount64 на XP вызвана новым gcc-mingw компилятором 12 версии. Часто ее стал встречать. А 10 версии в репах pacman msys уже нет*. Но вы можете кросскомпилировать в Linux любым gcc-mingw. Например, в Debian 11 сейчас версия 10.2. Хотя, конечно можно и бинарно пропатчить файлы.

* вернее, собственный gcc от msys как раз 10.2, но он привязывается к msys-2.0.dll, которая несовместима с XP. А Mingw с XP совместим. Да, там два компилятора. Да еще PATH'ы друг другу мешают, поэтому предпочитаю кросскомпиляцию и не надо виртуалку держать.

**Comment by artenax** [comment]
Ага, ясно. В дебиане за mingw-w64-headers, mingw-w64-crt и mingw-w64-winpthreads отвечает [mingw-w64-i686-dev](https://packages.debian.org/bullseye/mingw-w64-i686-dev) (source пакет mingw-w64).
И он там 8 версии, хотя gcc 10. В арче 10 версии, а gcc 12.
Так, что дело либо в версии (некоторых файлов) source mingw-w64, либо (скорее всего?) то, что в дебиане mingw более лояльно собирают, чем в арче.
Вот, например, в debian есть posix и win32 threads модели, а в арче [posix](https://github.com/archlinux/svntogit-community/blob/packages/mingw-w64-gcc/trunk/PKGBUILD). Posix вроде несовместим с XP. Хотя, это уже из другой оперы и вообще я не особо спец.
Arch (Msys) похоже не любят XP.

**Comment by artenax** [comment]
> О том как можно собрать под XP смотрите в workflow

Каждый раз пересобирать mingw-w64-* не очень весело. Нафиг этот pacman роллинг.
Пользуюясь случаем хочу спросить, а на чем вы программируете i2pd (пишете/редактируете код) и в какой ОС? Просто для интереса. В vim, наверное?
Чем собираете уже примерно ясно: Msys и OBS. А тогда получается, скорее всего на Windows программите.

Кстати, я вообще-то XP не пользуюсь. Для интереса проверяю совместимость.

**Comment by r4sas** [comment]
> Arch и Msys похоже не любят XP.

Они просто отказались от поддержки, и по идее правильно сделали, ибо система уже 8 лет как вышла из поддержки.

> Каждый раз пересобирать mingw-w64-* не очень весело. Нафиг этот pacman роллинг.

В моем случае один раз делается MSYS2 тулчейн для сборки, который пересобирается перед релизом одним батником. Никаких проблем.

> Пользуюясь случаем хочу спросить, а на чем вы программируете i2pd (пишете/редактируете код) и в какой ОС? Просто для интереса. В vim, наверное?

Стандартные текстовые редакторы, блокноты (vi/vim, nano - под линями, notepad++ под виндой). Никаких сред разработки. В основном разработка на linux идет (@orignal там пишет), а я под виндами проверяю постоянно (по крайней мере на 7, 10, 11... XP уже не проверяю давно - оно живет просто и фиксится по репортам, когда ломается там чего либо :) ).
