### ISSUE TITLE
[Feature request] Optional Prometheus metrics exposure

### ISSUE THREAD

**Issue by PoneyClairDeLune** [PurpleI2P/i2pd#1737]
I2Pd webconsole is informative, but it doesn't help much when one's running I2Pd a bunch of servers needing an overall insight.

Please consider adding an optionally enabled Prometheus metrics collection feature.

**Comment by r4sas** [comment]
You can use I2PControl for gathering information.
I don't think that someone would add Prometheus support inside i2pd because that will be external dependency for building.
