### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by thedmdim** [PurpleI2P/i2pd#1740]
Сколько не перезапускаю, i2pd живёт минут 10 макс.
Его последние слова:
```
[1232761.347821] NetDB[23709]: segfault at 0 ip 00005642979ddd48 sp 00007fb7d5ee69e0 error 6 in i2pd[564297983000+184000]
[1233237.426252] TCP: eth0: Driver has suspect GRO implementation, TCP performance may be compromised.
[1233480.286760] NetDB[23978]: segfault at 0 ip 00005574b2665d48 sp 00007f0721bb59e0 error 6 in i2pd[5574b260b000+184000]
[1235768.454931] NetDB[24267]: segfault at 0 ip 000055e67ca03d48 sp 00007fd40f6b89e0 error 6 in i2pd[55e67c9a9000+184000]
[1236190.277386] sh (25711): drop_caches: 3
```

**Comment by r4sas** [comment]
Система? Корку ловите, и бектрейс.

**Comment by thedmdim** [comment]
> Система? Версия i2pd? Корку ловите, и бектрейс в студию.
> 
> Тем более это не лог i2pd, а ваш системный, который подписывает по названиям потоков.

**Comment by thedmdim** [comment]
> Система? Версия i2pd? Корку ловите, и бектрейс в студию.
> 
> Тем более это не лог i2pd, а ваш системный, который подписывает по названиям потоков.

i2pd-2.39.0-r1 x86_64 {i2pd} (BSD-3-Clause)
alpine

Сначала думал что это из-за того, что floodfill включал, но сейчас проверил, даже с дефолтным конфигом не живёт долго

**Comment by thedmdim** [comment]
> > Система? Версия i2pd? Корку ловите, и бектрейс в студию.
> > Тем более это не лог i2pd, а ваш системный, который подписывает по названиям потоков.
> 
> i2pd-2.39.0-r1 x86_64 {i2pd} (BSD-3-Clause) alpine
> 
> Сначала думал что это из-за того, что floodfill включал, но сейчас проверил, даже с дефолтным конфигом не живёт долго

* контейнер alpine в докере - хост  centos

**Comment by thedmdim** [comment]
> > > Система? Версия i2pd? Корку ловите, и бектрейс в студию.
> > > Тем более это не лог i2pd, а ваш системный, который подписывает по названиям потоков.
> > 
> > 
> > i2pd-2.39.0-r1 x86_64 {i2pd} (BSD-3-Clause) alpine
> > Сначала думал что это из-за того, что floodfill включал, но сейчас проверил, даже с дефолтным конфигом не живёт долго
> 
> * контейнер alpine в докере - хост  centos

```
tail: /proc/17460/fd/45: No such device or address
11:11:40@784/warn - SSU: Missing fragments from 0 to 0 of message 1091401434
11:11:45@524/warn - Tunnels: test of tunnel 3582198263 failed
11:11:45@784/warn - SSU: Missing fragments from 0 to 0 of message 2261217803
11:12:00@784/warn - SSU: Missing fragments from 0 to 0 of message 2838524047
tail: /proc/17460/fd/37: No such file or directory
tail: /proc/17460/fd/37: No such device or address
tail: /proc/17460/fd/42: No such file or directory
tail: /proc/17460/fd/43: No such file or directory
tail: /proc/17460/fd/42: No such device or address
tail: /proc/17460/fd/43: No such device or address
11:13:16@401/warn - NTCP2: SessionCreated read error: End of file
11:13:16@784/warn - SSU: Missing fragments from 0 to 1 of message 2194447180
11:13:16@784/warn - SSU: Missing fragments from 0 to 0 of message 2194447180
tail: /proc/17460/fd/47: No such device or address
tail: /proc/17460/fd/39: No such file or directory
tail: /proc/17460/fd/41: No such file or directory
tail: /proc/17460/fd/38: No such file or directory
```

**Comment by r4sas** [comment]
Обновляйтесь до 2.41.0. Старые версии будут падать из-за работы над новым транспортом.

**Comment by thedmdim** [comment]
> 2.41.0

Обновил до i2pd-2.41.0-r0, теперь вообще не запускается, пишет:
`Error relocating /usr/sbin/i2pd: _ZSt28__throw_bad_array_new_lengthv: symbol not found`
