### ISSUE TITLE
i2pd router closes after a couple of minutes

### ISSUE THREAD

**Issue by Bachar-official** [PurpleI2P/i2pd#1741]
OS: Windows 11
Last version of i2pd.
After couple of minutes without any error messages program just closes.

**Comment by r4sas** [comment]
Last - 2.41.0?
Check using Event Viewer if any records can be found.

**Comment by Bachar-official** [comment]
Yep, last version is 2.41.0.
Where I can find any log files or smthng?

**Comment by r4sas** [comment]
For i2pd logs, check if you're using `loglevel = error` and check latest records from log. If nothing is here, that can only mean that something kills/stopping application. I have tested on Windows 11 build 22000.318 without any issues.

**Comment by Bachar-official** [comment]
Nothing interesting. But there is on coincidense: when I plugged in to my work VPN connection is stable. When I switch to my home provider i2pd app closes.

**Comment by Bachar-official** [comment]
Looks like without GUI i2pd works fine. At least 10 minutes without crashing. I'll keep watching, but thanks for your help!

**Comment by r4sas** [comment]
Can you try builds from CI? For example latest artifact from GitHub Actions: https://github.com/PurpleI2P/i2pd/actions/runs/2017528262.
