### ISSUE TITLE
local.csv doesn'w work

### ISSUE THREAD

**Issue by quercetum** [PurpleI2P/i2pd#1749]
Пытаюсь использовать addressbook/local.csv, но ни один локальный адрес не доступен. В логах сообщение,  что mytestsite.i2p не найден. При этом в local.csv есть запись вида 

mytestsite.i2p,<...>.b32.i2p

Подскажите, пожалуйста, куда копать.

**Comment by r4sas** [comment]
После создания файла i2pd перезапускался?

**Comment by quercetum** [comment]
Да, перезаапускался.

**Comment by r4sas** [comment]
В таком случае ищите сообщение в логе `Addressbook: XXX local addresses loaded`.

Так же проверьте права доступа если работаете на линуксе с сервисом который хранит файлы в /var/lib/i2pd. В этом случае владельцем должен быть пользователь i2pd, иначе этот файл просто не прочитает.

**Comment by quercetum** [comment]
Да, в логах есть Addressbook: 1 local addresses loaded
Я работаю под Ubuntu 21.10. Запускаю командой ./i2pd/i2pd --datadir ~/.i2pd/
При этом i2pd собран вручную из этого Гитхаба.

**Comment by quercetum** [comment]
Возможно, я туплю.
Теперь запись в local.csv выглядит так:

mytestsite.i2p,ohkycqo6wbmlctoz2wx5rq5h6pbcnf3wrt24ksbrqbmeg3stqpda

При этом всё равно выходит то же сообщение о том, что такой сайт не найден (в данном примере некоторые символы заменены). Но если такой адрес набрать в адресной строке, добавив .b32.i2 в конце, то сайт открывается.

**Comment by r4sas** [comment]
В таком случае призываю @orignal...

**Comment by orignal** [comment]
В local.csv можно прописывать только домены третьего уровня. Если на этой машине запущение mytestsite.i2p  то там можно прописать например 1.mytestsite.i2p и тогда он будет резолвиться через запрос к mytestsite.i2p

**Comment by quercetum** [comment]
Но в этом случае необходимо как-то зарегистрировать сам сайт mytestsite.i2p. Было бы неудобно, если пришлось бы регистрировать его глобально только для того, чтобы потом делать ему локальные поддомены.

Скажите, пожалуйста, а нет возможности добавлять именно локальные домены второго уровня в адресную книгу?

**Comment by orignal** [comment]
Да свой свйт сначала надо где то регистрировать. local.csv это только для поддоменов.

>Скажите, пожалуйста, а нет возможности добавлять именно локальные домены второго уровня в адресную книгу?

addressbook/addresses.csv
Просто вписать туда вручную и все.

**Comment by r4sas** [comment]
Лучше тогда воспользоваться адресхелпером.

**Comment by quercetum** [comment]
Спасибо большое! Аддресхелпер, он ведь для добавления глобального, для всех?

**Comment by r4sas** [comment]
Нет, он добавляет запись в локальную адресную книгу.

**Comment by r4sas** [comment]
Да, никакого интерфейса управления адресной книгой нет. Так что только в остановленном состоянии удаляя запись вручную из файла.

**Comment by quercetum** [comment]
Понял. Спасибо. Прикручу скриптик для удобства. :-)

Тогда уж и ещё вопрос: в веб-консоли не планируется сделать какую-нибудь статистику по тому, какие туннели/IP/страны в более-менее читаемом виде? В каком-нибудь отдалённом будущем?..

**Comment by r4sas** [comment]
Нет.
Подобное обсуждалось много раз в плане добавления каких либо интерфейсов управления, статистик и прочего, но когда предлагаешь запрfшивающим реализовывать это самостоятельно указывая на то что Pull Requests открыты, всем всё резко перестает быть подобное нужным (ага, на C++ писать же надо ;) ).

**Comment by quercetum** [comment]
Весьма разумно. Спасибо. 

Приложение действительно получилось очень и очень удобным и быстрым.
