### ISSUE TITLE
Question: how to run on remote server?

### ISSUE THREAD

**Issue by TheBjoel2** [PurpleI2P/i2pd#1750]
So, I want to host i2pd on an remote server. I set:
host = 5.6.7.8 #To my remote server's ip
Neither web console, nor proxy does not work.
There is wireguard connection configured between me and the server. What do I do wrong?

**Comment by r4sas** [comment]
You must install on your remote server.

**Comment by TheBjoel2** [comment]
It is installed. I have troubles configuring it

**Comment by TheBjoel2** [comment]
Setting addresses to 0.0.0.0 somehow makes it to work
