### ISSUE TITLE
[Question] Unable to connect to I2P

### ISSUE THREAD

**Issue by sjehuda** [PurpleI2P/i2pd#1757]
Hello,
For several weeks, I'm not avle to connect.
I'd like to inspect I2Pd for possible issues.
Is this a proper place to ask for help?

> Proxy error: Host is down
Can't create connection to requested host, it may be down. Please try again later.

**Comment by r4sas** [comment]
Are you sure that requested host is online?
What about stats on main page of Webconsole?

**Comment by r4sas** [comment]
> Proxy error: Outproxy failure Host localhost not inside I2P network, but outproxy is not enabled http://localhost:4444/

You mustn't use proxy for accesing webconsole.

**Comment by sjehuda** [comment]
As far as I know, I'm not accessing http://localhost:4444/ via proxy

**Comment by r4sas** [comment]
Webconsole is on http://127.0.0.1:7070/

**Comment by sjehuda** [comment]
On Mon, 23 May 2022 07:00:16 -0700
R4SAS ***@***.***> wrote:

> Stop i2pd, set `loglevel` to `info` in `/etc/i2pd/i2pd.conf` and
> start it again. If after restarting in 5 minutes nothing changes,
> check logs at `/var/log/i2pd/i2pd.log`. 
> 

Now, it's working, with Privoxy and directly with proxy port 4444.
I don't know why it didn't earlier.

> Are you forwarding all traffic to tor?
> 

Yes, except for port 4444 (i2p)
