### ISSUE TITLE
Upgraded to Ubuntu 22.04 and i2pd stopped working, i2pd v2.42 

### ISSUE THREAD

**Issue by jasonc741** [PurpleI2P/i2pd#1759]
I recently upgraded from Ubuntu 20.04 to Ubuntu 22.04 LTS and as soon as I did, i2pd stopped working.  I made sure i2pd was updated to the latest version V2.42 Jammy. 

i uninstalled and reinstalled per https://i2pd.readthedocs.io/en/latest/user-guide/install/#ubuntu

[i2pd.log](https://github.com/PurpleI2P/i2pd/files/8750471/i2pd.log)

**Comment by r4sas** [comment]
Ubuntu 21.10 and 22.04 has problems itself (something wrong with libc++-std) and OpenSSL 3, which haven't required APIs to add support of it. See https://github.com/PurpleI2P/i2pd/issues/1738 for more info.

**Comment by r4sas** [comment]
I've made some changes in package building process, please test package `2.42.0-2<dist>1` from PPA. Now it mustn't crash (I hope).

**Comment by jasonc741** [comment]
@r4sas 

2.42.0-1 jammy1 look stable

$ sudo systemctl status i2pd.service
● i2pd.service - I2P Router written in C++
     Loaded: loaded (/lib/systemd/system/i2pd.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2022-05-23 21:44:15 CDT; 3min 7s ago
       Docs: man:i2pd(1)
             https://i2pd.readthedocs.io/en/latest/
   Main PID: 20252 (i2pd)
      Tasks: 15 (limit: 4481)
     Memory: 16.8M
        CPU: 1.276s
     CGroup: /system.slice/i2pd.service
             └─20252 /usr/sbin/i2pd --conf=/etc/i2pd/i2pd.conf --tunconf=/etc/i2pd/tunnels.conf --tunnelsdir=/etc/i2pd/tunnels.conf>

May 23 21:44:15 server-1 systemd[1]: Starting I2P Router written in C++...
May 23 21:44:15 server-1 systemd[1]: Started I2P Router written in C++.

And Bitcoin Core was able to connect to SAM on the first try!
