### ISSUE TITLE
Too many fd i2pd

### ISSUE THREAD

**Issue by sim604** [PurpleI2P/i2pd#1764]
H!
A few hours after the start (grows at about ~7-10 per minute):
ls  -l /proc/6512/fd|wc
   3107   34168  209669

ls  -l /proc/6512/fd|tail -n10
lrwx------  990 -> anon_inode:[eventfd]
lrwx------  991 -> anon_inode:[eventpoll]
lrwx------  992 -> anon_inode:[timerfd]
lrwx------  993 -> socket:[8612623]
lrwx------  994 -> anon_inode:[eventfd]
lrwx------  995 -> anon_inode:[eventpoll]
lrwx------  996 -> anon_inode:[timerfd]
lrwx------  997 -> anon_inode:[timerfd]
lrwx------  998 -> socket:[16595300]
lrwx------  999 -> anon_inode:[eventfd]

After a day of work, virtual memory is more than 20 G.

i2pd-2.42.1
5.18.1-r2 x64
gcc (Gentoo 11.3.0 p4) 

это норм?

**Comment by r4sas** [comment]
А какая статистика на 7070?

**Comment by sim604** [comment]
> А какая статистика на 7070?

немного подождать  пока накопится 
тестирую : --limits.openfiles --limits.ntcpsoft 
gentoo по дефолту выставляет  в conf.d/i2pd system limit : max number of open files (for floodfill) 4096
уменьшил, жду когда подберётся к лимиту 

Uptime: 12 minutes, 1 second
Network status: Firewalled
Tunnel creation success rate: 52%
Received: 4.44 MiB (11.08 KiB/s)
Sent: 4.66 MiB (11.86 KiB/s)
Transit: 0.00 KiB (0.00 KiB/s)
Data path: /var/lib/i2pd
Hidden content. Press on text to see.
Routers: 1384 Floodfills: 931 LeaseSets: 0
Client Tunnels: 276 Transit Tunnels: 3

**Comment by r4sas** [comment]
> --limits.ntcpsoft

Этот параметр был актуален только для NTCP, которого уже нет.

> уменьшил, жду когда подберётся к лимиту

А зачем? У вас до 4К добирается чтоли? Надо смотреть статистику когда подобралось к этому лимиту. Еще бы посмотреть в этот момент сколько у вам NTCP2 транспортов.

**Comment by orignal** [comment]
>After a day of work, virtual memory is more than 20 G.

Это так линукс работает с памятью, это число реально никого не волнует.

**Comment by sim604** [comment]
поставил для теста (что бы долго не ждать) --limits.openfiles 1024
ограничение работает, но начинает расти потребление реальной памяти

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
27527 i2pd      20   0 9871.7m   2.0g   4364 S   17.7  54.1  81:55.67 i2pd

**Comment by orignal** [comment]
Не надо ограничивать число деcкрипторов, это будет создавать одни проблемы. Лучше ограничивать число транзитных тоннелей.

**Comment by r4sas** [comment]
Мне кажется дело в Gentoo и используемом им GCC.

**Comment by sim604** [comment]
Ок. выключу ограничение fd, тоннелей стоит по умолчанию:
## Maximum active transit sessions (default:2500)
Что то мне подсказывает, что там на один тоннель несколько fd уходит... 
Кажется ещё раутеру не очень хорошо наступает через какое то время (хотя скорость транзита стоит всего 200к)
Попробую уменьшить кол-во transit sessions
ps подсказали i2pd форум на i2p, тут наверное мне надо заканчивать флудить....

**Comment by r4sas** [comment]
Не верно, fd уходит на одно активное TCP соединение в любом месте, плюс SSU немного использует на таймеры.

**Comment by sim604** [comment]
На сколько я понял, gentoo на этот package не накладывает никаких своих патчей.
Флаги если этого достаточно, то вот :
cat ./i2pd-2.42.1/build-info/CFLAGS
-O2 -pipe -march=core2
> И попробуйте собрать бинарник собственноручно через make в папке с исходниками.
хотел так сделать, да поленился поставив в cron restart  т.к. выше  Client Tunnels > 20000 начинает глючить раутер, возрастает in/out traffic выше чем стоит в i2pd.conf bandwidth и прочие неприятности
Спасибо за мотивацию, попробую пересобрать "чистым"

**Comment by r4sas** [comment]
20000 клиентских туннелей это уже знак того что программа не работает как задумано. Обычно на 2-3 I2P туннеля это число не должно превышать 20.

**Comment by sim604** [comment]
1. Пресобрал руками из исходников, С cmake не удалось сконфигурить, собрал напрямую make (в мане пишут, что допустимо), запустил на старом конфиге и старом /var/lib/i2pd/ - результат тотже - растёт, 
Linux version 5.18.1-gentoo-r2

2. Собрал на другой машине через штатный emerge  AMD Athlon(tm) 64 X2 Dual Core Processor 4400+ 
-O2 -march=k8-sse3
gcc & boot - тотже
Linux version 5.17.5-gentoo - другой конфиг, более минималистичный
Для чистоты теста перенастроил retroshare на вторую машину.
Client Tunnels: 32 , ls /proc/20695/fd|wc болтается в районе 80-90 - тогда как на первой машине сразу начинало расти
Думаю, смотреть в сторону конфига ядра

**Comment by r4sas** [comment]
Закрываю, поскольку правки были внесены по поводу данной ситуации, а так же есть подозрение что RS не верно работает с BOB. В любом случае, BOB уже вырезан из кода там и заменен на SAM.
