### ISSUE TITLE
socks интерфейс

### ISSUE THREAD

**Issue by artenax** [PurpleI2P/i2pd#1779]
Было бы хорошо, если бы вы сделали локальный socks прокси в дополнение к http прокси 127.0.0.1:4444. Например, socks5 127.0.0.1:4445
Да, я знаю, есть socks 127.0.0.1:4447. Но в нем не работает outproxy в интернет! Потому что outproxy socks типа в живом виде не существует и предлагается перенаправлять в локальный tor socks 127.0.0.1:9050 (единственное его применение для выхода в интернет через socks 127.0.0.1:4447).
В общем, хочется, чтобы как http 127.0.0.1:4444, но только socks. Чтобы работали там outrpoxy от purokishi, acetone и прочих.
Вручную менять тип http<>socks в лисобраузерах очень хлопотно. Хотя, есть расширения, но все равно, это лишний костыль. А так поменял порт и всё (у меня всякие прокси psiphon, shadowsocks, tor и все они socks).
Что думаете?

**Comment by artenax** [comment]
В добавок, в случае с socks, можно не разрешать DNS через outproxy. Например, purokishi цензуру вводит по DNS.
Правда и по http можно не разрешать, но это очень и очень костыльно делать.

**Comment by r4sas** [comment]
duplicate https://github.com/PurpleI2P/i2pd/issues/1683

**Comment by artenax** [comment]
Вы не могли бы пояснить? Я, конечно, могу пересобрать, но что это даст? Опять же, хотелось бы для всех. Для продвижения в массы, так сказать.
Я честно говоря не понял, о каких SOCKS proxy речь идет в #1683.

Но если перефразировать всю мою писанину, мне хочется, чтобы SOCKS интерфейс 127.0.0.1:4447 мог использовать outproxy из [httpproxy] настроек. ИЛИ чтобы можно было в раздел [socksproxy] i2pd.conf вписать outproxy=purokishi.i2p (и подобное). Пока что там предлагается 127.0.0.1:9050.
Ну и чтобы addresshelper=true в [socksproxy] тоже работал (для i2p сайтов, вдруг захочу новые посетить).

**Comment by r4sas** [comment]
Если бы вы прочитали что там написано, то там сказано что проксирование через SOCKS5 **сломано**.

`addresshelper` в SOCKS прокси нет и не будет, потому что в данном виде прокси приложение не взаимодействует с передаваемыми данными.

I2P изначально не про выход в интернет, поэтому этого сделано не будет. Для таких целей используйте Firefox в совокупности с FoxyProxy и туннелем до purokishi.i2p.
