### ISSUE TITLE
[FEATURE] SSL tunnels

### ISSUE THREAD

**Issue by jiigen** [PurpleI2P/i2pd#1780]
Putting this here only a reminder following the chat we had on IRC  about implementing SSL tunnels on i2pd. :-)

**Comment by orignal** [comment]
Only server tunnels for now.

**Comment by r4sas** [comment]
e82662b3899fb9c0123e34db91c244b1fbb97162, 6b939eba597f2d6e20190464708552b5573119ec

**Comment by orignal** [comment]
ssl=true  in server tunnel
and
hostoverride="you address"  for SNI

**Comment by jiigen** [comment]
That's cool thank you!!
