### ISSUE TITLE
when linked from i2pd-qt: SIGSEGV in Garlic.cpp

### ISSUE THREAD

**Issue by nonlin-lin-chaos-order-etc-etal** [PurpleI2P/i2pd#1782]
line: 595

bottom part of call stack:

![image](https://user-images.githubusercontent.com/19966907/185220403-5fd0fd45-ee67-4178-8c0b-74b9e6e0bad0.png)

scrolled to the top of call stack:

![image](https://user-images.githubusercontent.com/19966907/185221085-66a8b77e-0985-4d39-b21f-028c41e1fadd.png)

**Comment by orignal** [comment]
"Too many open files"

ulimit -n 4096

**Comment by nonlin-lin-chaos-order-etc-etal** [comment]
тогда тут закрываем и сделаю иссуй на и2пд_куте репе
