### ISSUE TITLE
Each time i2pd update means examining differences in i2pd.conf. file, why not having different .conf file for user changes?

### ISSUE THREAD

**Issue by slrslr** [PurpleI2P/i2pd#1784]
```
Version: 2.43.0-1bullseye1
APT-Manual-Installed: yes
APT-Sources: https://repo.i2pd.xyz/debian bullseye/main amd64 Packages
```

It happens repeatedly that during i2pd package update, i am asked:
```
Configuration file '/etc/i2pd/i2pd.conf'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
```

seeing there are many changes, so i would like to have up to date version of the .conf file, yet that would erase my customizations. Or i am required to manually merge various changes in the file. That make me wonder if i can define my changes in some other .conf file which will be used as primary so i do not need to always examine differences of the main i2pd.conf file and merge it (file would be left in default state). Some other apps act like that - default file is usually left unchanged by user and user define his customization in new .conf file. https://i2pd.readthedocs.io/en/latest/user-guide/configuration/ does not suggest there is yet such option. What do you suggest?

**Comment by r4sas** [comment]
You mean something like `i2pd.local` as in Fail2Ban package (`jail.local`)?

**Comment by slrslr** [comment]
> Fail2Ban

yes, i was exactly thinking about this app. i2pd.conf gets updated without involving user action while i2pd.local (or similar) contains only user defined configuration lines which override lines in i2pd.conf

**Comment by r4sas** [comment]
Added `conffiles` list to package to prevent notification about changes in packaged conf file: https://github.com/PurpleI2P/i2pd/commit/cfb773351d5ccef338355834ba0a2302093de43c.

**Comment by slrslr** [comment]
> prevent notification about changes in packaged conf file

You can ignore this, I just wanted to say that I am wondering what does it mean. I guess either update will not replace i2pd.conf file or it will merge changes somehow. I suppose replacing user config file causing breakage of the user setup is not what it do and I probably can not use files in i2pd.conf.d/ kind of folder allowing me to leave default i2pd.conf file unmodified.
