### ISSUE TITLE
Libi2pd c++ integration updated code.

### ISSUE THREAD

**Issue by OzoneCode10** [PurpleI2P/i2pd#1787]
Hello,
Do you have an updated code example on how to use libi2pd.lib inside a c++ app? I saw code but it was from back from like 2015.

Thanks.

**Comment by r4sas** [comment]
Hello. Everything can be found in libi2pd/api.[[cpp](https://github.com/PurpleI2P/i2pd/blob/openssl/libi2pd/api.cpp)|[h](https://github.com/PurpleI2P/i2pd/blob/openssl/libi2pd/api.h)] files. As I see it, @orignal recently updated the code after reporting a bug on the IRC server
