### ISSUE TITLE
Windows service configuration folder

### ISSUE THREAD

**Issue by Vort** [PurpleI2P/i2pd#1792]
I see different behaviour of i2pd than described in documentation:

https://github.com/PurpleI2P/i2pd/wiki/Setting-up-i2pd-as-Windows-Service#service-installation:

> The service will run under special LocalService user account. Its configuration folder is likely C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\i2pd.

For me, it is created at `c:\ProgramData\i2pd`.

> But if you place i2pd.conf into binary directory, it would start work in same directory where i2pd.exe is placed.

It do not work that way.
I have binary at `d:\i2pd\i2pd.exe`, config at `d:\i2pd\i2pd.conf`, but i2pd still creates `c:\ProgramData\i2pd` folder and fills it with default data.

Please resolve differences.

OS: Win7 SP1 x64
Version: i2pd_2.43.0_win64_mingw.zip

**Comment by r4sas** [comment]
According to the current code, i2pd will create files in `CommonApplicationData` (i.e. `c:\ProgramData\`) if the `--service` switch is used. Accordingly, for use with a configuration file in the directory where the i2pd binary resides, you need to remove this switch from the service command.
https://github.com/PurpleI2P/i2pd/blob/96c4463d39ac74a8ceb7527f3619775704a52cd6/libi2pd/FS.cpp#L72-L86

I will update the wiki.
