### ISSUE TITLE
no way to bind SAM port to IPv4 and IPv6

### ISSUE THREAD

**Issue by schildbach** [PurpleI2P/i2pd#1799]
I've tried

```
--sam.enabled=true
--sam.address=0.0.0.0
--sam.address=[::]
```

That yields

`args: option '--sam.address' cannot be specified more than once`

And also `[::]` or any other IPv6 address  doesn't seem to be accepted either.

And finally, if I try to put my hostname (i2pd) into the address like this:

```
--sam.enabled=true
--sam.address=i2pd
```

I get

`error - Clients: Exception in SAM bridge: Invalid argument [system:22]`

**Comment by r4sas** [comment]
If you want to bind on all interfaces you must use single `address = [::]`.

**Comment by schildbach** [comment]
Thanks! Seems like

```
--sam.address=::
```

does the trick of binding to both address families. The `[::]` syntax seems unsupported.
