### ISSUE TITLE
[Feature request] Show firewall status for Yggdrasil

### ISSUE THREAD

**Issue by marek22k** [PurpleI2P/i2pd#1800]
Hello,

I use I2Pd with Yggdrasil. I have also enabled the ports accordingly for my Yggdrasil address, however I only see the following on the webconsole:
```
Network status: Firewalled
Network status v6: Firewalled
```

Is it perhaps possible to also show the firewall status for Yggdrasil?

**Comment by orignal** [comment]
1. There is no way to test network status for yggdrasil because it's NTCP2 only
2. It should be OK due to the nature of yggdrasil
