### ISSUE TITLE
Release Notes 2.44 missing

### ISSUE THREAD

**Issue by diva-exchange** [PurpleI2P/i2pd#1802]
For Release 2.44, https://github.com/PurpleI2P/i2pd/releases/tag/2.44.0 - the release notes are missing. This is IMHO rather critical - since documentation is key. Please let diva.exchange know, if you need help with the release notes for future releases.

**Comment by r4sas** [comment]
hm... @orignal said yesterday that he will fill it. Looks like he forgot.

**Comment by r4sas** [comment]
Ah, nevermind, he added them later.

**Comment by diva-exchange** [comment]
Very nice. Thanks a lot!
