### ISSUE TITLE
No connection after update to 2.43.0

### ISSUE THREAD

**Issue by marek22k** [PurpleI2P/i2pd#1803]
Installed from https://repo.i2pd.xyz/debian

Version 2.42.0
![i2pd_2 42_fin](https://user-images.githubusercontent.com/46723399/203089698-955f695d-967c-4c5f-bd9c-d1565a9eb88f.png)

Version 2.43.0
![i2pd_2 43](https://user-images.githubusercontent.com/46723399/203089713-a1770d46-4216-4dc2-8557-52c3bbff67c2.png)

With 2.43 there is often 0.0.0.0, this was not the case with 2.42. Now I don't get any connection to the I2P network.

Sorry if this issue already exists, however, I could not find an existing one.

**Comment by r4sas** [comment]
I think it is a bit late to make reports about 2.43.0. Please wait for 2.44.0 packages.

**Comment by marek22k** [comment]
Thanks for the answer. I will reopen when the problem is still in 2.44.0.
