### ISSUE TITLE
Debian 10: Produces corrupted static build that doesn't work on other distributions

### ISSUE THREAD

**Issue by FFighter78** [PurpleI2P/i2pd#1807]
Version: IP2D 2.44.0
OS: Debian 10 fresh install fully updated

Static bulid built according to instructions here on a brand new Debian 10 freshly updated: https://i2pd.readthedocs.io/en/latest/devs/building/unix/

> sudo apt-get install cmake build-essential debhelper libboost-date-time-dev libboost-filesystem-dev libboost-program-options-dev libboost-system-dev libssl-dev zlib1g-dev libminiupnpc-dev

> cmake . -DCMAKE_BUILD_TYPE=Release -DWITH_STATIC=ON && make

make outputs the following error:
```
[ 91%] Linking CXX executable i2pd
/usr/bin/ld: attempted static link of dynamic object `/usr/lib/x86_64-linux-gnu/libz.so'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/i2pd.dir/build.make:188: i2pd] Error 1
make[1]: *** [CMakeFiles/Makefile2:149: CMakeFiles/i2pd.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

This issue is resolved by editing src/build/CMakeFiles/i2pd.dir/link.txt apparently libz.so is being passed, so libz.so is changed to libz.a, which exists on the system.

Make is run again and it produces an i2pd binary without issues

**PROBLEM:**

The produced static i2pd binary runs on Debian 10/11. HOWEVER, I tested the same binary on Fedora and while it starts it failes with the following error:

```
16:21:25@394/none - i2pd v2.44.0 (0.9.56) starting...
16:21:25@394/warn - Family: Can't load family certificates from /home/mika/.i2pd/certificates/family
16:21:25@394/warn - Reseed: Can't load reseed certificates from /home/mika/.i2pd/certificates/reseed
16:21:25@394/error - RouterInfo: Can't open file 
Segmentation fault (core dumped)
```

I can only assume given it works on the machine that compiled and Debian 10/11, but not Fedora that the resultant binary is not truly static or something. I ran the following command

> ld ./i2pd
> not a dynamic executable

so based on my limited knowledge that means it is static, but the binary is corrupted somehow and is not really cross-distribution.

**Comment by r4sas** [comment]
https://github.com/PurpleI2P/i2pd/issues/1806#issuecomment-1325573590
