### ISSUE TITLE
Tests implementation in CMake?

### ISSUE THREAD

**Issue by barracuda156** [PurpleI2P/i2pd#1808]
@r4sas @orignal Do I get it right that there is no CMake support for tests atm?

Our PR for `i2pd` to MacPorts is basically ready, but having tests is desirable.
https://github.com/macports/macports-ports/pull/16749

**Comment by r4sas** [comment]
Yes, there is no tests support in our CMake. Anyway, tests in `tests` directory is not covering whole program, only specified functions, like some encryption algorithms and HTTP requests processing.

**Comment by barracuda156** [comment]
> Yes, there is no tests support in our CMake. Anyway, tests in `tests` directory is not covering whole program, only specified functions, like some encryption algorithms and HTTP requests processing.

@r4sas Thanks for confirmation. I will see if I can fix that today and if that works, make a PR here.

**Comment by r4sas** [comment]
PR #1812 is merged, closing issue.
