### ISSUE TITLE
Question about setting proxy-server with google-chrome

### ISSUE THREAD

**Issue by raphael10-collab** [PurpleI2P/i2pd#1809]
In order to be able to see i2p sites, I started with `Ubuntu 22.04 Desktop` `google chrome` as follows: 

    google-chrome-stable --proxy-server="http://127.0.0.1:4444/" . Tried to access this i2p site : 
    https://kmpmk2fmineaiwublteqlifg4fkmewnhmxqlcgg7qwecz6daj43a.b32.i2p/  

But I got : `"There is something wrong with the proxy server, or the address is incorrect"`

How to make it work?

**Comment by r4sas** [comment]
1. Most of I2P didn't use HTTPS. Use HTTP.
2. Address in your post is offline
3. Do not include quotation marks: `--proxy-server=http://127.0.0.1:4444`
4. Use SwitchyOmega extension for configuring proxies.

**Comment by raphael10-collab** [comment]
From this blog: https://mhatta.medium.com/the-hitchhikers-guide-to-the-i2p-eepsites-e4dfe6bb7a45 I've taken this sample i2p address: http://kmpmk2fmineaiwublteqlifg4fkmewnhmxqlcgg7qwecz6daj43a.b32.i2p/

![image](https://user-images.githubusercontent.com/70313067/204082911-51b5b5e9-bf9e-4c08-b934-8b1369f00194.png)

These are the settings of `SwitchOmega` : 

![image](https://user-images.githubusercontent.com/70313067/204082929-585e45c6-a807-48b3-aeab-a6aac3091dd0.png)

![image](https://user-images.githubusercontent.com/70313067/204082941-0acce025-2b16-406c-b895-92e12e59cb66.png)

**Comment by r4sas** [comment]
Example PAC file:
```js
var FindProxyForURL = function(init, profiles) {
    return function(url, host) {
        "use strict";
        var result = init, scheme = url.substr(0, url.indexOf(":"));
        do {
            result = profiles[result];
            if (typeof result === "function") result = result(url, host, scheme);
        } while (typeof result !== "string" || result.charCodeAt(0) === 43);
        return result;
    };
}("+Auto", {
    "+Auto": function(url, host, scheme) {
        "use strict";
        if (/:\/\/[-a-zA-Z0-9.]+\.i2p(:\d+)?\//.test(url)) return "+I2P";
        return "DIRECT";
    },
    "+I2P": function(url, host, scheme) {
        "use strict";
        if (/^127\.0\.0\.1$/.test(host) || /^::1$/.test(host) || /^localhost$/.test(host) || host[host.length - 1] >= 0 && isInNet(host, "192.168.0.0", "255.255.0.0")) return "DIRECT";
        return "PROXY 127.0.0.1:4444";
    }
});
```

**Comment by r4sas** [comment]
![image](https://user-images.githubusercontent.com/7023612/204106228-93dde75b-f333-4597-8f0f-067f7addbba0.png)
![image](https://user-images.githubusercontent.com/7023612/204106240-0206deb4-9719-4213-89f1-6ef74da90e9c.png)

URL Regex for I2P: `://[-a-zA-Z0-9.]+\.i2p(:\d+)?/`

**Comment by raphael10-collab** [comment]
I've created with three profiles:

![image](https://user-images.githubusercontent.com/70313067/204130455-4a18d894-c765-4679-8ed8-4c9e6712817f.png)


URL Regex for I2P: ://[-a-zA-Z0-9.]+\.i2p(:\d+)?/  
![image](https://user-images.githubusercontent.com/70313067/204130458-3acd9f1e-aa4b-4e98-bed7-7cacd6fc14d9.png)



![image](https://user-images.githubusercontent.com/70313067/204130481-297494f4-04e9-41a9-8f5c-f170df761850.png)

![image](https://user-images.githubusercontent.com/70313067/204130488-ae595ebb-1c14-495c-9b46-da9da7e592db.png)

But still I'm not able to see this I2P website: https://dmwqjoudwbxhqswhpitrhr6byc6afuvvja4reo7ecaoc3bpfxwdq.b32.i2p/    : 


![image](https://user-images.githubusercontent.com/70313067/204130568-979296ae-cea1-4387-bf3e-0395b18fa490.png)

![image](https://user-images.githubusercontent.com/70313067/204130587-367de59e-b6cd-4057-9819-5757ce36c688.png)

![image](https://user-images.githubusercontent.com/70313067/204130614-b434bc0c-9300-4249-9782-9da772ffa75d.png)

**Comment by r4sas** [comment]
You have not started i2pd.

**Comment by raphael10-collab** [comment]
Now it works fine

Thank you very much @r4sas
