### ISSUE TITLE
Опция --eephost принимает только IP

### ISSUE THREAD

**Issue by wasd171** [PurpleI2P/i2pd#181]
При попытке использования --eephost=localhost вываливается с ошибкой 
```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
```
Если использовать --eephost=127.0.0.1, то работает нормально. Часто в Docker нужно перенаправлять не на IP, а на хост, так что баг довольно актуальный.

**Comment by orignal** [comment]
Вообще вместо этой опции следует заполнять tunnels.cfg, но там та же самая проблема.
Починю.
