### ISSUE TITLE
Gzip: Deflate error 0

### ISSUE THREAD

**Issue by babut85** [PurpleI2P/i2pd#1810]
openbsd 7.2 stable
i2pd version 2.44.0 (0.9.56)
  WITH_BINARY=ON
  WITH_LIBRARY=ON
  WITH_STATIC=OFF
  WITH_UPNP=ON
  WITH_AESNI=ON
Boost version 1.80.0
LibreSSL 3.6.0
LibreSSL 3.6.0

appears somewhere every minute, sometimes less often. the i2p network itself is functioning. but i don't like these messages(the ssd drive won't like them either), what do i owe to their appearance?

**Comment by r4sas** [comment]
`loglevel = none`

**Comment by babut85** [comment]
> `loglevel = none`
so you want to say that constant error messages are normal, and to avoid of them i have to close my eyes? lol :D are you russian? i can't imagine who else would have thought of it

**Comment by r4sas** [comment]
These persistent messages only indicate errors when parsing I2NP messages received from other routers, which may be old and use the wrong Gzip algorithm.

**Comment by orignal** [comment]
It happens when we try to fit SessionConfirmed message and it fails because buffer is too small. Basically it's normal behavior.

**Comment by babut85** [comment]
so maybe when building specify a larger size? anyway i'm building from source code. but i do not know where to fix it

**Comment by orignal** [comment]
Let me explain. We are trying to fit it into MTU. If compressed RouterInfo fits we send it as single packet, if not we send two fragments. But we don't know it until we try to compress, e.g. if compression fails we switch to fragmentation.  If you build it from source you can comment this line
https://github.com/PurpleI2P/i2pd/blob/openssl/libi2pd/Gzip.cpp#L131

**Comment by babut85** [comment]
i understood. this is a common situation, but for some unknown reason you write about it in syslog. ok. thx ^.^
ps: in this case we are talking about mss, not mtu ;)

**Comment by orignal** [comment]
We are talking about MTU for SSU2 packets.

**Comment by orignal** [comment]
https://github.com/PurpleI2P/i2pd/commit/1ac171152a7981f4781d961802043d0a70b97ee0
