### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by ghost** [PurpleI2P/i2pd#1814]
I changed the parameters in i2pd.conf with these:
inbound.length = 7                                            inbound.quantity = 1                                          outbound.length = 7                                           outbound.quantity = 1
Then, I started i2pd, it cannot access any hidden services whether i2p-projekt.i2p or not, and later i2pd accidentally terminated with segmentation fault.
i2pd version 2.44.0 (0.9.56)
Boost version 1.80.0
OpenSSL 3.0.7 1 Nov 2022

**Comment by r4sas** [comment]
Please gather core dump and itz crash backtrace.

**Comment by Vort** [comment]
Works for me:
![image](https://user-images.githubusercontent.com/1242858/205125348-e42189f4-b845-4920-9ecc-d4350d494c33.png)
