### ISSUE TITLE
Add a wasm release target?

### ISSUE THREAD

**Issue by bmiller59** [PurpleI2P/i2pd#1817]
Is a wasm release target planned?

If it is not planned in the near future, can you provide any guidance on how difficult this might be and advise on specific considerations, challenges or suggestions?

Thank you for this project.

**Comment by r4sas** [comment]
If you know how to build wasm, you can create PR for such functional. We are not planning add it and can not say anything about difficulties and etc.

**Comment by bmiller59** [comment]
@r4sas Thank for your response. Unfortunately that is not my expertise. I hope someone else takes interest who would also be interested in using i2pd via wasm! :) I would love to see i2pd offered as wasm to support fully decentralized browser-based applications using i2pd as the communication transport layer.

**Comment by r4sas** [comment]
I looked in wasi-sdk, there is bunch of problem, like `pthread`, so I think it is not possible to make it work on wasm for now, so I'm closing issue.
