### ISSUE TITLE
SSU2 Failed to bind issue

### ISSUE THREAD

**Issue by Pryodon** [PurpleI2P/i2pd#1818]
I periodically get this error message. I uploaded the error message image to an image hosting website.
[https://ibb.co/93K3hXF](https://ibb.co/93K3hXF)

I noticed that error message again. This time, I was not even using my computer at all. My screen saver was on, and when I moved the mouse to cancel the screen saver, I saw the error message was there. I leave my computer on all the time to run I2Pd.

My I2Pd version is "2.43.0 Purple" I just run a single server on my Win10 computer.

Also, is there any way to make I2Pd take advantage of my available bandwidth? I allow the network to use more bandwidth, but it doesn't take advantage of what I have available. I don't actually use the I2P network that much... mainly because it is incredibly slow, almost as bad as dial-up Internet.

Also, I have a port open and it says it is getting incoming connections... However, sometime after I have been running the server for a while, I look at the status page and it says that it is firewalled. If I [check the port](https://portchecker.co/) from the Internet, it says the port is open. I can't figure out why it always seems to say that it is firewalled... When I first start the server, it says "OK" and is not firewalled.

I use Malwarebytes anti-virus. I am constantly getting messages from Malwarebytes saying IP addresses that I2Pd is connecting to have malware and it won't allow the connection. The I2Pd success rate is currently at 40%.

I also run I2Pd on a VPS linux server I am renting. It seems to work like a charm there.

Here is my i2pd.conf file contents: (Note that the link to the docs has been updated. The original link was broken.)

```
## Configuration file for a typical i2pd user
## See https://i2pd.readthedocs.io/en/latest/user-guide/configuration/
## for more options you can use in this file.
# https://howto.yggno.de/en:i2p


port = 55507
bandwidth = 1000
floodfill = true
insomnia = true
close = minimize

log = file
logfile = ./i2pd.log
#loglevel = info
loglevel = none

ipv4 = true
ipv6 = false

ssu = false

[limits]
openfiles = 0

[ntcp2]
enabled = true
published = true

[ssu2]
enabled = true
published = true

[precomputation]
elgamal = false

[upnp]
enabled = false
name = I2Pd

[reseed]
verify = true

[http]
## Web Console settings
## Uncomment and set to 'false' to disable Web Console
enabled = true
address = 127.0.0.1
port = 7070

[httpproxy]
enabled = true
address = 127.0.0.1
port = 4444

[socksproxy]
enabled = true
address = 127.0.0.1
port = 4447

[sam]
enabled = false
address = 127.0.0.1
port = 7656
```

**Comment by Pryodon** [comment]
Here is another log snippet of when the error happened.

[log 2.txt](https://github.com/PurpleI2P/i2pd/files/10150631/log.2.txt)

**Comment by r4sas** [comment]
That can happen if your ISP changes external address. Usually they restart session and re-assign address every 24 hours. Check this, maybe it is reason?

**Comment by Pryodon** [comment]
Here is another snippet from the log file. This time it was set to log "warn"
[log 3.txt](https://github.com/PurpleI2P/i2pd/files/10165109/log.3.txt)

Take a look at this error message. It makes my computer play an alert.
https://ibb.co/93K3hXF

I added blank lines around where the error is to make it easier to spot. It seems these 3 lines are always together which appears to me that they are related.

Is this what you are talking about if my IP changes? I'm using a VPN so I am thinking that I should have a static IP. I can't run I2Pd more than about 4 hours or so without getting this error message. I doubt my IP address is changing that often.

**Comment by r4sas** [comment]
No reply, closing.
