### ISSUE TITLE
Docker + i2pd

### ISSUE THREAD

**Issue by wasd171** [PurpleI2P/i2pd#182]
Кто-нибудь пробовал использовать i2pd внутри Docker для хостинга сайта? Конфигурация, которая прекрасно работает просто на железе, почему-то недоступна извне, при запуске внутри контейнера i2p выдаёт "Сайт недоступен, так как его LeaseSet не был найден."

У меня ощущение, что проблема с портами, но не могу понять, как поправить. Вот Dockerfile

```
FROM 	debian:wheezy


RUN 	echo "deb http://deb.i2p2.no/ wheezy main" 		>> /etc/apt/sources.list &&\
		echo 'deb-src http://deb.i2p2.no/ wheezy main'	>> /etc/apt/sources.list

RUN		apt-get update && \
		DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes i2p-keyring && \
		apt-get update && \
    	DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes i2pd && \
    	rm -rf /var/lib/apt/lists/*

ADD 	./tunnels.cfg 	/var/lib/i2pd/
ADD 	./keys.dat		/var/lib/i2pd/

CMD 	service i2pd stop && \
		echo "\nhost=$BALANCER_PORT_80_TCP_ADDR" >> /var/lib/i2pd/tunnels.cfg && \
		cat /var/lib/i2pd/tunnels.cfg && \
		i2pd --service=1 --daemon=0 --bandwidth=O --port=9876

EXPOSE 	9876
EXPOSE 	9876/udp
```
Порты пробрасываю как 
```
- '9876:9876'
- '9876:9876/udp'
```

**Comment by orignal** [comment]
А что 127.0.0.1:7070 говорит  в строке Status?

**Comment by wasd171** [comment]
```
Uptime: 00:03:41
Status: OK
Tunnel creation success rate: 1%
Received: 96K (637 Bps)
Sent: 743K (5712 Bps)
Data path: /var/lib/i2pd

Routers: 43 Floodfills: 13 LeaseSets: 0
```
Tunnel creation success rate со временем только уменьшается

**Comment by orignal** [comment]
>Tunnel creation success rate со временем только уменьшается
Это сегодня общая проблема всей сети из-за ее перегруженности.

>Routers: 160 Floodfills: 128 LeaseSets: 0
Мало роутеров. Надо подождать чтобы несколько сотен набралось.

**Comment by wasd171** [comment]
upd:
```
Uptime: 06:44:35
Status: OK
Tunnel creation success rate: 3%
Received: 79080K (1220 Bps)
Sent: 147240K (3697 Bps)
Data path: /var/lib/i2pd

Routers: 524 Floodfills: 135 LeaseSets: 0
```
Вроде достаточно набрал, но проблема сохраняется

**Comment by orignal** [comment]
Что именно происходит?

**Comment by wasd171** [comment]
Пытаюсь раздать доступ к сайту через i2pd. На сервере стоит i2pd. Если запускать его просто из OS, то доступ к сайту раздаётся. Если запускать внутри Docker, то при той же конфигурации Java-i2p на клиенте выдаёт "Сайт недоступен, так как его LeaseSet не был найден."

**Comment by wasd171** [comment]
Не знаю, связано ли это, но очень мало (и уменьшается) транзитных туннелей и все ведут в 0

**Comment by orignal** [comment]
Тоннели на этом адресе есть? (в секции Local Destinations)
С транзитными тоннелями это нормально, о вас еще мало знают и не отпрофилировали как надо.

**Comment by wasd171** [comment]
В Local Destinations тоннели есть, но почему-то 2 вместо одного. Хотя на железе тоже 2. Кстати, ещё на железе Status: Firewalled

**Comment by orignal** [comment]
То что вы видите это не тоннели - это адреса.
Один есть всегда - это shared local destination, который меняется каждый раз при рестарте.
А второй это как раз адрес вашего сайта, вот у него и надо смотреть тоннели.

Статус Firewalled как раз и означает что к вашим портам нет доступа извне, а OK что есть.

**Comment by wasd171** [comment]
В итоге при использовании Docker в External address сперва показывается и NTCP и SSU, но через пару минут остаётся  только SSU, статус Firewalled. Проброшены оба порта, и для UDP и для TCP

**Comment by orignal** [comment]
Значит UDP снаружи не проходит по каким то причинам.

**Comment by wasd171** [comment]
Скорее наоборот, почему-то TCP не проходит. Хотя в iptables прописаны оба совершенно одинаково. Как клиент, кстати, работает, флибусту открывает

**Comment by orignal** [comment]
Статус проверяется через UDP, проверка TCP не предусмотрена.
NAT для работы не помеха

**Comment by wasd171** [comment]
Если не проходит UDP, то почему в External addresses исчезает NTCP. а не  SSU? А двойной NAT не помеха? Фактически один NAT на роутере, второй NAT создаёт Docker на сервере.

**Comment by orignal** [comment]
Потому что считается что не доступа извне и можно работать только по SSU, потому что там есть механизм работаты за NAT-ом

**Comment by wasd171** [comment]
Странно, что при NAT роутера работает и NTCP и SSU, будто никакого NAT и нет

**Comment by orignal** [comment]
А входящие NTCP соединения есть?

**Comment by wasd171** [comment]
Как это понять? В транспортах NTCP есть, несмотря на то, что в external address только SSU

**Comment by orignal** [comment]
Все правильно. Он может принимать входящие соединения только по SSU, а исходящие может как по SSU, так и по NTCP.
Когда порты открыты то полно входящих по NTCP бывает.

**Comment by wasd171** [comment]
В local destinations даже есть туннели, как входящие так и исходящие, но LeaseSet всё равно не отдаётся :-(

**Comment by orignal** [comment]
В том, на котором сайт висит, есть тоннели?
Откуда известно что не отдается?

**Comment by wasd171** [comment]
Да, и входящие и исходящие. Ну я пытаюсь с другой машины Java-клиентом подключиться и получаю, что LeaseSet не найден, да и в нужном local destination LeaseSet: 0

**Comment by orignal** [comment]
У него и будет 0 - нафига ему искать самого себя?

**Comment by wasd171** [comment]
А, я думал что это количество отданных. В любом случае не проходит с внешнего клиента

**Comment by orignal** [comment]
В логах есть сообщение "Publishing confirmed" либо "Publish confirmation was not received"?

**Comment by wasd171** [comment]
В том, что выводит в консоль, есть только строчки вида "Publishing our RouterInfo to Xlce. reply token=765311121". Или в файл пишет больше и там посмотреть?

**Comment by orignal** [comment]
Это другое. У вас это точно серверный тоннель?

**Comment by wasd171** [comment]
Точно, tunnels.cfg выглядит как
```
 [WWW]
i2pproxy_1 | type=server
i2pproxy_1 | port=80
i2pproxy_1 | keys=keys.dat
i2pproxy_1 | host=172.17.0.4
```
и при запуске выдаёт
```
13:59:33/info - 0 I2P client tunnels created
13:59:33/info - 1 I2P server tunnels created
```

**Comment by orignal** [comment]
Тогда буду разбираться, потому что например orignal.i2p точно также настроен.
[orignal]
type=server
host=127.0.0.1
port=8010
keys=orignal.dat

**Comment by wasd171** [comment]
Спасибо. Пока что буду просто использовать вне контейнера, так работает как часы.

**Comment by SpontaneousOverthrow** [comment]
Работает, если docker на клиентe запущен с парметром `network_mode = host`

**Comment by r4sas** [comment]
Тут проблема в другом была - туннели не строились.
