### ISSUE TITLE
Would you rewrite it in Rust?

### ISSUE THREAD

**Issue by fndxnyxz** [PurpleI2P/i2pd#1824]
Rust focuses on safety. Android has added some Rust code, nobody found any bugs in Android Rust code.

**Comment by r4sas** [comment]
We have been hearing such ideas for 5 years now and always answer “Do it yourself”. So far no one has done it.

**Comment by serfcity** [comment]
> Rust focuses on safety.
That's not true. Please read http://rustmustdie.com. (You can use https://libretranslate.de, if needed )
