### ISSUE TITLE
Don't overwrite config files on .deb update/reinstall

### ISSUE THREAD

**Issue by RealCr4ckhead** [PurpleI2P/i2pd#1832]
I believe adding conffiles file should fix it.

Source: https://unix.stackexchange.com/questions/511862/apt-update-always-overrides-old-config-file

**Comment by r4sas** [comment]
Updated in https://github.com/PurpleI2P/i2pd/commit/cfb773351d5ccef338355834ba0a2302093de43c. Thank you.

**Comment by RealCr4ckhead** [comment]
Thank you, too, but one more thing seems to be getting overwritten, and that is the i2pd.service file.

**Comment by r4sas** [comment]
For service file please use override config.
https://askubuntu.com/questions/659267/how-do-i-override-or-configure-systemd-services

**Comment by RealCr4ckhead** [comment]
Well, that's the thing, I don't want it to override on i2pd update/reinstall.

**Comment by r4sas** [comment]
reverted adding of the conffiles, because debhelper automatically creating it from debian/files, so I got only annoying warnings at build time.
