### ISSUE TITLE
Segfaults just after launching, when UPnP is enabled, and only after upgrading to v`2.45.0`.

### ISSUE THREAD

**Issue by Supermath101** [PurpleI2P/i2pd#1837]
I'm running [I2Pd](https://copr.fedorainfracloud.org/coprs/supervillain/i2pd/) v`2.45.0` within [Toolbx](https://containertoolbx.org/) and with a host OS of [Fedora Kinoite](https://kinoite.fedoraproject.org/). I have UPnP enabled in my `i2pd.conf`, and it segfaults during the initialization of UPnP. If I disable UPnP, it seems to work fine. Here's relevant portion of the console output:
```
21:06:42@998/error - UPnP: Found Internet Gateway Device http://192.168.1.1:1931/wanIpConn
21:06:42@998/debug - UPnP: ExternalIPAddress is [REDACTED]
21:06:42@998/debug - UPnP: Port 29357 is possibly not forwarded: return code -2
21:06:42@998/info - UPnP: Port successfully forwarded ([REDACTED]:29357 type TCP -> 192.168.1.244:29357)
Segmentation fault (core dumped)
```

Also, this only happens after I upgraded from v`2.44.0` to v`2.45.0`.

**Comment by kleenexi2p** [comment]
https://copr.fedorainfracloud.org/coprs/supervillain/i2pd/package/i2pd-git/
Seems like there already is a -git package. You should install that.

**Comment by r4sas** [comment]
Closing as fixed in trunk.
