### ISSUE TITLE
WebUI says firewalld, tunnel success is low

### ISSUE THREAD

**Issue by shruuub** [PurpleI2P/i2pd#1839]
So I'm really sorry to be the 4000th guy to post this here, but I have set a static port for i2pd, forwarded that both locally with iptables as well as at my cloud provider, but the webui still says I'm firewalld on IPv4 and v6 and only has a ≈20% tunnel creation success rate. I also restarted i2pd and of course checked if the port is actually open. Maybe there are special additional rules needed?
Thanks a lot.

**Comment by r4sas** [comment]
Firewalled can happed sometimes - SSU2 is released, but old routers (which are not updating frequently) still can answer incorrectly to Peer Test requests. Low success rate happens due to Java I2P low capability and tunnels rejection by them.

**Comment by orignal** [comment]
Also if you think you are not firewalled, it doesn't mean you are not firewalled.
Some ISPs like to change your UDP port for example.

**Comment by wekoq** [comment]
@shruuub you are always firewalled, or sometimes get OK?

**Comment by shruuub** [comment]
> Also if you think you are not firewalled, it doesn't mean you are not firewalled.

I think mine shouldn't, as it is a cloud vps provider.

**Comment by shruuub** [comment]
> @shruuub you are always firewalled, or sometimes get OK?

always, sadly

**Comment by shruuub** [comment]
Got an OK for the first time! Only on IPv4, but that's okay I guess. Didn't change anything, just restarted the daemon. Closing.
