### ISSUE TITLE
Config.cpp from hell!

### ISSUE THREAD

**Issue by serfcity** [PurpleI2P/i2pd#1840]
Config.cpp have hardcoded URLs!
What do you think about config.xml, for example?

**Comment by r4sas** [comment]
All hardcoded URL can be overriden with config file.

**Comment by serfcity** [comment]
Why you can't read any file and load URLs in starting-up process? Binary versions of i2pd software can't be updated without recompiling (In debian, for example).

**Comment by r4sas** [comment]
Again: any value in Config.cpp can be changed with config file.

Example:
https://github.com/PurpleI2P/i2pd/blob/4011502f5f9a9bf18597308bc45ef20a4c4e7d85/libi2pd/Config.cpp#L209-L221

```ini
# cat i2pd.conf

[reseed]
urls = https://your.reseed.server.com/
```
