### ISSUE TITLE
Build error on 10.13–10.14 with Apple Clang: SSU2Session.cpp: error: no member named 'merge'

### ISSUE THREAD

**Issue by barracuda156** [PurpleI2P/i2pd#1846]
```
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_security_i2pd/i2pd/work/i2pd-2.45.1/libi2pd/SSU2Session.cpp:487:18: error: no member named 'merge' in 'std::__1::map<unsigned int, std::__1::shared_ptr<i2p::transport::SSU2SentPacket>, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<const unsigned int, std::__1::shared_ptr<i2p::transport::SSU2SentPacket> > > >'
                        m_SentPackets.merge (resentPackets);
                        ~~~~~~~~~~~~~ ^
```
Logs: https://build.macports.org/builders/ports-10.14_x86_64-builder/builds/152666/steps/install-port/logs/stdio
https://build.macports.org/builders/ports-10.13_x86_64-builder/builds/177202/steps/install-port/logs/stdio

On all other versions of macOS the build is fine.

**Comment by r4sas** [comment]
clang 10?
Maybe because there is no `#include <map>` in SSU2Session.cpp?

**Comment by orignal** [comment]
"merge" requires C++17 that's why. Please check if clang 10 supports it.

#if (__cplusplus >= 201703L) // C++ 17 or higher
			m_SentPackets.merge (resentPackets);

**Comment by barracuda156** [comment]
> "merge" requires C++17 that's why. Please check if clang 10 supports it.

Well, the earlier Apple Clang 9 of 10.12 builds `i2pd` fine: https://build.macports.org/builders/ports-10.12_x86_64-builder/builds/214777/steps/install-port/logs/stdio
Even Apple Clang 8 has no problem: https://build.macports.org/builders/ports-10.11_x86_64-builder/builds/207440/steps/install-port/logs/stdio

As for the standard, earlier required minimum was C++11, and that is set in the portfile. If now C++17 is required and not just optional, we should change the relevant setting – Macports chooses compilers based on that.

**Comment by orignal** [comment]
No, C++17 is not required, but for some reason clang detects C++17, but doesn't have map::merge. You  should enforce C++11 or find out what's wrong with C++17 in clang 10.

**Comment by barracuda156** [comment]
> No, C++17 is not required, but for some reason clang detects C++17, but doesn't have map::merge. You should force C++11 or find out what's wrong with C++17 in clang 10.

I guess we can just blacklist Apple Clang on 10.13–10.14 then.

**Comment by orignal** [comment]
Or always set C++11 for clang

**Comment by barracuda156** [comment]
The C++11 standard trick worked, `i2pd` builds across the board now: https://ports.macports.org/port/i2pd/details/
