### ISSUE TITLE
support literal IPv6 address syntax (square brackets)

### ISSUE THREAD

**Issue by schildbach** [PurpleI2P/i2pd#1855]
E.g. when providing `--sam.address=[::]` it fails with

> error - Clients: Exception in SAM bridge: Invalid argument [system:22]`

Just `::` however has special meaning in yaml, so it needs to be escaped within docker compose configuration for example.

**Comment by r4sas** [comment]
As we [earlier found](https://github.com/PurpleI2P/i2pd/issues/1799#issuecomment-1311418011), application waits for `::`, and we won't change this, because we use Boost and this is default behavior.
