### ISSUE TITLE
external IPv6 auto-detected as `::1`

### ISSUE THREAD

**Issue by schildbach** [PurpleI2P/i2pd#1856]
I'm running the docker image with i2pd 2.45.1.

When enabling `--ipv6` and `--nat`, i2pd always auto-detects my external IPv6 address as `::1`, which is the local loopback and obviously wrong.

I do have dynamic external IP addresses, so I can't just provide a static address as a workaround.

**Comment by r4sas** [comment]
Looks like IPv6 is not forwarded to docker containers.

**Comment by schildbach** [comment]
What do you mean by "forwarded"?

**Comment by r4sas** [comment]
RTFM: https://docs.docker.com/config/daemon/ipv6/

**Comment by schildbach** [comment]
Of course, my Docker is IPv6 enabled.
