### ISSUE TITLE
Bandwidth control problem

### ISSUE THREAD

**Issue by CountryBumkin** [PurpleI2P/i2pd#1858]
I am trying to use I2pd on a limited bandwidth service so I tried to use the 'Bandwidth' option in I2pd.conf to suit the circumstances.
The source promised this...
Transit traffic bandwidth limit: integer in KBps or letters: L (32), O (256), P (2048), X (>9000)"

However no letter or number I tried made any difference, The transit bandwidth ignored the setting and always consumed all the available upload capacity. Other config limits I set were observed.
(I2pd 2.45.1 built from source on Linux Mint 20.3)

**Comment by orignal** [comment]
No, it doesn't. Compare daily bandwidth usage for example and you will see the difference.

**Comment by Vort** [comment]
Bandwidth limiting algorithm in i2pd just stop accepting new transit tunnels when limit is exceeded.
It works well with lots of slow transits, but not so good where there are few fast connections.

**Comment by orignal** [comment]
I think it's more documentation issue. Should use "approximately".

**Comment by CountryBumkin** [comment]
Vort commented - Bandwidth limiting algorithm....

This best describes the behavior, but on my scale it only takes 1 fast connection to flood the link. I will use the router QoS to mange the flow.
