### ISSUE TITLE
cmake поддержка дефайна USE_UPNP

### ISSUE THREAD

**Issue by RomikB** [PurpleI2P/i2pd#186]
В скриптах cmake данный дефайн не поддерживается. Это сделано намеренно или недоработка?

**Comment by orignal** [comment]
Потому что UPnP еще не доделано

**Comment by RomikB** [comment]
Вот написал patch файл пока ждал ответ: https://www.dropbox.com/s/7s35ohokj5rtw5v/9999-UPNP.patch?dl=0 , вдруг кому понадобится. UPNP у меня вроде работает, порты пробрасываются.

**Comment by orignal** [comment]
Так седлайте pull request.
С UPnP там проблема в том что порт пробрасывается только если его явно указать в параметрах.

**Comment by RomikB** [comment]
у меня gentoo-like дистрибутив, явно порт нигде не указывал.
pull request(ы) никогда не делал, попробую.

**Comment by mlt** [comment]
Отчего [загрузка shared object в UPnP.cpp происходит вручную](https://github.com/PurpleI2P/i2pd/blob/master/UPnP.cpp#L67), а не просто всё слинковано?
@RomikB По-хорошему библиотеку ещё надо найти средствами CMake (find_library) а не использовать абстрактный CMAKE_DL_LIBS.

**Comment by orignal** [comment]
Потому что может не стоять miniupnp, и тогда из-за необязательной фичи ничего запускаться не станет.
