### ISSUE TITLE
<5% Tunnel success rate with "OK" Network Status

### ISSUE THREAD

**Issue by hunter2k01** [PurpleI2P/i2pd#1869]
Hello,

I'm using i2pd installed from the releases page here. I had 60% success rate initially but my network status said firewalled and it eventually went down to less than 10%. I unblocked more ports and the network status now says that its OK, but my tunnel success rate is at 2%. I can no longer access eepsites or use torrents.

Im using IPv4 only, UPNP is enabled and SSU2. Is this weird behavior, traffic congestion, or is it something Im doing wrong? Thanks.

**Comment by LLE8** [comment]
Now on my server:
Network status OK
Tunnel creation success rate 3%
Routers: 38076 Floodfills: 28411 LeaseSets: 0
Client Tunnels: 3 Transit Tunnels: 8053

Weird behavior of the i2p network, imho.
What is the i2pd memory usage?

**Comment by Aost2** [comment]
Same problems:
Network status: OK
Tunnel creation success rate: 2%
Routers: 3581 Floodfills: 3146 LeaseSets: 0
Client Tunnels: 24 Transit Tunnels: 6

Sometimes clearing the contents of netDB improves the situation. Dead routers?

**Comment by TheBjoel2** [comment]
git clone openssl branch, build and install it. Finally, run it. It will be fixed for you if you let your router run for an hour.

**Comment by Vort** [comment]
Network is under attack now. That's the reason of low success rate.
As @TheBjoel2 said, effects of attack can be partially mitigated with the use of latest version of i2pd (built from latest commit).
But more commits with fixes, most likely, will be made in following days, so it is better to check for fresh commits from time to time.

**Comment by hunter2k01** [comment]
Good to know, thanks guys. Depending on how often it needs to be rebuilt I'll probably stay offline a couple days.

**Comment by zikkuratti** [comment]
how do you check this metricks homies?

**Comment by Vort** [comment]
It is shown in webconsole (http://127.0.0.1:7070):
![image](https://github.com/PurpleI2P/i2pd/assets/1242858/44b12458-30c2-4e85-961c-badb4587d408)

**Comment by zikkuratti** [comment]
more about Routers:  Floodfills:  count

**Comment by Vort** [comment]
Floodfill count should be around thousand.

**Comment by r4sas** [comment]
Outdated, closing.
