### ISSUE TITLE
LeaseSets is 0

### ISSUE THREAD

**Issue by RomikB** [PurpleI2P/i2pd#187]
Вот имею такую проблему, прошло более 12 часов.
![i2pd1](https://cloud.githubusercontent.com/assets/6143452/7449930/44b3929e-f23f-11e4-8030-cb36d171936f.png)
![i2pd2](https://cloud.githubusercontent.com/assets/6143452/7449935/48d00a42-f23f-11e4-95ce-a7a8e02946bc.png)

тут лог: https://www.dropbox.com/s/jijynx4qu8uylux/i2pd.log.bz2?dl=0

**Comment by orignal** [comment]
А  в чем проблема?  Их и должно быть нуль если не флудфил.
Нужные вам надо смотреть в секции  Local Destinations.

**Comment by RomikB** [comment]
Просто не загружались никакие сайты, подумал что в этом может быть проблема.

**Comment by orignal** [comment]
Не загружается скорее всего потому что тоннелей нет.

**Comment by RomikB** [comment]
А есть способ добавлять свои короткие i2p адреса?

**Comment by orignal** [comment]
Куда добавлять?

**Comment by RomikB** [comment]
Ну вот например:
1) работал у меня i2pd 12 часов узнал во что ресолвить адрес http://flibusta.i2p/, потом я его перезапустил и он больше не знает такого адреса. надо или чтобы автоматом сохранялось или чтобы пользователь мог куда то внести.
2) хочу сделать короткую ссылку на некий адрес который не имеет таковой, чтобы потом иметь возможность хотить по напримерссылке a1.i2p

**Comment by orignal** [comment]
1. Узнал через jump service или как? 
2. Файл .i2pd/addressbook/addresses.csv. Туда ручками добавить соотвествующую строку.

**Comment by RomikB** [comment]
1) я не сильно разбираюсь в терминологи, как то у соседних узлов узнал, без вмешательства пользователя, я надеялся что оно где то сохранится, но увы.

**Comment by orignal** [comment]
А в addresses.csv flibusta.i2p есть? 
У соседних узлов узнать нельзя, надо запрашивать по подписке в файле subscriptions.txt

**Comment by RomikB** [comment]
В документации написано что адресами можно обмениваться, или там имеется в виду длинными адресами? Нет в адресах нет такой записи, файла subscriptions.txt тоже нет, однако утром по этому адресу ходилось. а после перезапусков уже нет.

**Comment by orignal** [comment]
Где и что именно написано?

**Comment by RomikB** [comment]
https://geti2p.net/ru/docs/naming
Адресная книга -> Входящие Подписки и Слияние

**Comment by orignal** [comment]
А i2pd тут причем?  У меня многие вещи организованы иначе, адресная книга в частоности.

**Comment by RomikB** [comment]
Я просто тогда не могу понять каким образом получается возможность ходить по коротким адресам которых нет в адресной книге.

**Comment by orignal** [comment]
Никак. Такой возможности нет.

**Comment by RomikB** [comment]
Спасибо за ответы.
