### ISSUE TITLE
не срабатывает accept на сокете

### ISSUE THREAD

**Issue by bol-van** [PurpleI2P/i2pd#1878]
Такая ситуация с 2.45.1 ( с 2.45 то же самое) , что приходит куча SYN запросов , а ответа нет
Именно такое происходит , когда listen сделан, а accept не делается.
Трафик падает до 0

**Comment by LLE8** [comment]
Похоже, 2.45.х уязвимы к DDoS, нужна более новая версия.
Сейчас
i2pd version 2.45.1-86-g86fc12e3 
В первых строчках i2pd.conf `nettime.frompeers = false`
Uptime менее 3 суток, трафик 35-40 Мбит/с

**Comment by Vort** [comment]
Видимо, дубль #1871.
Надо обновляться или до 1c4cc02c234bd8ca1bf0c7c87aee318e9fc49f43 коммита (где была исправлена проблема) или до последнего (в данный момент 1ad38c0b95edea5c578bfe9d4b7b8bd9559ce41e)

**Comment by bol-van** [comment]
Да, кажется оно. Вручную внес правку из того коммита. Сразу замечаю 40% success rate вместо 3%
и скорость помаленьку прибывает
