### ISSUE TITLE
Зависание сервиса на порту 7070

### ISSUE THREAD

**Issue by RomikB** [PurpleI2P/i2pd#188]
У меня такая проблема: i2pd запущен в режиме service daemon, захожу по адресу http://localhost:7070, вижу что всё работает, пытаюсь перейти по адресу который есть в адресной книге например http://localhost:7070/inr.i2p, через секунд 10-20 получаю ответ с желтым человечком и надписью "Not responding", повторяю запрос, после этого сервис на порту 7070 зависает навечно (запросы получает, но ответы не отсылает, в браузере выглядит как вечная загрузка), пока пока процесс i2pd не будет принудительно аварийно завершен. В логе никаких странных записей, всё живет дальше своей жизнью.

**Comment by orignal** [comment]
Там все на одном треде висит, значит где то зависает. Посмотрю.
А вообще лучше это не использовать, в свое время было сделано только для отладки когда ни прикси ни тоннелей еще не было.
