### ISSUE TITLE
Upnp is not working in windows and Android i2pd.

### ISSUE THREAD

**Issue by Sdash24** [PurpleI2P/i2pd#1900]
I've used i2pd in both windows and Android (prebuilt binary). In both cases I got this error: UPnP: Unable to find valid Internet Gateway Device: error 2. The Upnp feature is turned on in my home router because my torrent client can utilize it without any problem.The network status is always Firewalled. That's why I can't make my i2pd router floodfill although I've some spare bandwidth.

**Comment by Vort** [comment]
It is possible to try using IGD despite error 2.
I made such [changes](https://github.com/Vort/i2pd/commit/de084027b4717cfb97307b74a2ec5cc611a1532f) in my fork, binaries will be available for download [here](https://github.com/Vort/i2pd/actions/runs/4335832179) in ~15 minutes.

**Comment by r4sas** [comment]
@Vort this is bad idea...

**Comment by Vort** [comment]
> this is bad idea...

At least it is possible in such way to get further information about the problem.
What are the alternatives? Try to build debug version of miniupnp? Collect Wireshark dumps of interactions both from i2pd and libtorrent/qBittorrent?

**Comment by r4sas** [comment]
Only way to fix this - change router with something that uses correct IGD specification.

**Comment by Vort** [comment]
The question is why qBittorrent do not complain about it.

> &lt;Sdash&gt; the thing is my qbittorrent client can successfully map port but i2pd can't

**Comment by r4sas** [comment]
The answer is:
Since miniupnpc believes that if there is no real IP-address in the WAN interface, it returns code 2, which means that “IGD is found, but there is no connection to the Internet or no real IP”. In our current code, this result leads with the cessation of an attempt to make a port mapipng.

**Comment by Vort** [comment]
> &lt;Sdash&gt; the build can successfully map port
&lt;Sdash&gt; but the network status is still firewalled :(
&lt;Sdash&gt; btw it's an application in java named port mapper

PortMapper application also can show External address.
https://www.raymond.cc/wp-content/uploads/2014/08/portmapper.png
What it shows for you? Your actual external IP or something like 0.0.0.0, 192.168.\*, 10.0.* ?

**Comment by Sdash24** [comment]
> > <Sdash> the build can successfully map port
> > <Sdash> but the network status is still firewalled :(
> > <Sdash> btw it's an application in java named port mapper
> 
> PortMapper application also can show External address. https://www.raymond.cc/wp-content/uploads/2014/08/portmapper.png What it shows for you? Your actual external IP or something like 0.0.0.0, 192.168.*, 10.0.* ?

It shows 10.101.1.67 in external address.

**Comment by r4sas** [comment]
> It shows 10.101.1.67 in external address.

Q.E.D., that's why UPnP returns error 2.

**Comment by Sdash24** [comment]
> > It shows 10.101.1.67 in external address.
> 
> Q.E.D., that's why UPnP returns error 2.

so is it fixable or not?

**Comment by Vort** [comment]
It is, most likely, fixable only by asking ISP for public IP address or by changing ISP.
