### ISSUE TITLE
UPnP not working and cant compile

### ISSUE THREAD

**Issue by darkstrike420** [PurpleI2P/i2pd#192]
UPnP doesn't work On Windows 7 x64, I had to map ports manually using an open-source port mapper to become "Status: OK".

Also, can't compile using Boost 1.58 and Visual Studio 2013 for Win32.

The following are errors from compiler:
1>libboost_filesystem-vc120-mt-s-1_58.lib(operations.obj) : error LNK2038: mismatch detected for '_MSC_VER': value '1600' doesn't match value '1800' in AddressBook.obj
1>libboost_filesystem-vc120-mt-s-1_58.lib(path.obj) : error LNK2038: mismatch detected for '_MSC_VER': value '1600' doesn't match value '1800' in AddressBook.obj
1>libboost_filesystem-vc120-mt-s-1_58.lib(path_traits.obj) : error LNK2038: mismatch detected for '_MSC_VER': value '1600' doesn't match value '1800' in AddressBook.obj
1>libboost_filesystem-vc120-mt-s-1_58.lib(windows_file_codecvt.obj) : error LNK2038: mismatch detected for '_MSC_VER': value '1600' doesn't match value '1800' in AddressBook.obj
1>libboost_filesystem-vc120-mt-s-1_58.lib(codecvt_error_category.obj) : error LNK2038: mismatch detected for '_MSC_VER': value '1600' doesn't match value '1800' in AddressBook.obj
1>libboost_system-vc120-mt-s-1_58.lib(error_code.obj) : error LNK2038: mismatch detected for '_MSC_VER': value '1600' doesn't match value '1800' in AddressBook.obj
1>libboost_date_time-vc120-mt-s-1_58.lib(greg_month.obj) : error LNK2038: mismatch detected for '_MSC_VER': value '1600' doesn't match value '1800' in AddressBook.obj
1>libboost_regex-vc120-mt-s-1_58.lib(instances.obj) : error LNK2038: mismatch detected for '_MSC_VER': value '1600' doesn't match value '1800' in AddressBook.obj
1>libboost_regex-vc120-mt-s-1_58.lib(regex_raw_buffer.obj) : error LNK2038: mismatch detected for '_MSC_VER': value '1600' doesn't match value '1800' in AddressBook.obj
1>libboost_regex-vc120-mt-s-1_58.lib(regex.obj) : error LNK2038: mismatch detected for '_MSC_VER': value '1600' doesn't match value '1800' in AddressBook.obj
1>libboost_regex-vc120-mt-s-1_58.lib(w32_regex_traits.obj) : error LNK2038: mismatch detected for '_MSC_VER': value '1600' doesn't match value '1800' in AddressBook.obj
1>libboost_regex-vc120-mt-s-1_58.lib(regex_traits_defaults.obj) : error LNK2038: mismatch detected for '_MSC_VER': value '1600' doesn't match value '1800' in AddressBook.obj
1>libboost_regex-vc120-mt-s-1_58.lib(static_mutex.obj) : error LNK2038: mismatch detected for '_MSC_VER': value '1600' doesn't match value '1800' in AddressBook.obj
1>libboost_program_options-vc120-mt-s-1_58.lib(config_file.obj) : error LNK2038: mismatch detected for '_MSC_VER': value '1600' doesn't match value '1800' in AddressBook.obj
1>libboost_program_options-vc120-mt-s-1_58.lib(convert.obj) : error LNK2038: mismatch detected for '_MSC_VER': value '1600' doesn't match value '1800' in AddressBook.obj
1>libboost_program_options-vc120-mt-s-1_58.lib(value_semantic.obj) : error LNK2038: mismatch detected for '_MSC_VER': value '1600' doesn't match value '1800' in AddressBook.obj
1>libboost_program_options-vc120-mt-s-1_58.lib(cmdline.obj) : error LNK2038: mismatch detected for '_MSC_VER': value '1600' doesn't match value '1800' in AddressBook.obj
1>libboost_program_options-vc120-mt-s-1_58.lib(utf8_codecvt_facet.obj) : error LNK2038: mismatch detected for '_MSC_VER': value '1600' doesn't match value '1800' in AddressBook.obj
1>libboost_program_options-vc120-mt-s-1_58.lib(options_description.obj) : error LNK2038: mismatch detected for '_MSC_VER': value '1600' doesn't match value '1800' in AddressBook.obj
1>libboost_program_options-vc120-mt-s-1_58.lib(positional_options.obj) : error LNK2038: mismatch detected for '_MSC_VER': value '1600' doesn't match value '1800' in AddressBook.obj
1>HTTPProxy.obj : error LNK2001: unresolved external symbol "private: void __thiscall boost::re_detail::perl_matcher<class std::_String_const_iterator<class std::_String_val<struct std::_Simple_types<char> > >,class std::allocator<struct boost::sub_match<class std::_String_const_iterator<class std::_String_val<struct std::_Simple_types<char> > > > >,struct boost::regex_traits<char,class boost::w32_regex_traits<char> > >::construct_init(class boost::basic_regex<char,struct boost::regex_traits<char,class boost::w32_regex_traits<char> > > const &,enum boost::regex_constants::_match_flags)" (?construct_init@?$perl_matcher@V?$_String_const_iterator@V?$_String_val@U?$_Simple_types@D@std@@@std@@@std@@V?$allocator@U?$sub_match@V?$_String_const_iterator@V?$_String_val@U?$_Simple_types@D@std@@@std@@@std@@@boost@@@2@U?$regex_traits@DV?$w32_regex_traits@D@boost@@@boost@@@re_detail@boost@@AAEXABV?$basic_regex@DU?$regex_traits@DV?$w32_regex_traits@D@boost@@@boost@@@3@W4_match_flags@regex_constants@3@@Z)
1>HTTPProxy.obj : error LNK2001: unresolved external symbol "public: bool __thiscall boost::re_detail::perl_matcher<class std::_String_const_iterator<class std::_String_val<struct std::_Simple_types<char> > >,class std::allocator<struct boost::sub_match<class std::_String_const_iterator<class std::_String_val<struct std::_Simple_types<char> > > > >,struct boost::regex_traits<char,class boost::w32_regex_traits<char> > >::find(void)" (?find@?$perl_matcher@V?$_String_const_iterator@V?$_String_val@U?$_Simple_types@D@std@@@std@@@std@@V?$allocator@U?$sub_match@V?$_String_const_iterator@V?$_String_val@U?$_Simple_types@D@std@@@std@@@std@@@boost@@@2@U?$regex_traits@DV?$w32_regex_traits@D@boost@@@boost@@@re_detail@boost@@QAE_NXZ)
1>libboost_filesystem-vc120-mt-s-1_58.lib(path.obj) : error LNK2001: unresolved external symbol "private: static void __cdecl std::locale::facet::_Facet_Register(class std::locale::facet *)" (?_Facet_Register@facet@locale@std@@CAXPAV123@@Z)
1>libboost_date_time-vc120-mt-s-1_58.lib(greg_month.obj) : error LNK2001: unresolved external symbol "private: static void __cdecl std::locale::facet::_Facet_Register(class std::locale::facet *)" (?_Facet_Register@facet@locale@std@@CAXPAV123@@Z)
1>libboost_program_options-vc120-mt-s-1_58.lib(convert.obj) : error LNK2001: unresolved external symbol "private: static void __cdecl std::locale::facet::_Facet_Register(class std::locale::facet *)" (?_Facet_Register@facet@locale@std@@CAXPAV123@@Z)
1>libboost_program_options-vc120-mt-s-1_58.lib(options_description.obj) : error LNK2001: unresolved external symbol "private: static void __cdecl std::locale::facet::_Facet_Register(class std::locale::facet *)" (?_Facet_Register@facet@locale@std@@CAXPAV123@@Z)
1>libboost_filesystem-vc120-mt-s-1_58.lib(path.obj) : error LNK2001: unresolved external symbol "private: static class std::locale::_Locimp * __cdecl std::locale::_Init(void)" (?_Init@locale@std@@CAPAV_Locimp@12@XZ)
1>libboost_program_options-vc120-mt-s-1_58.lib(convert.obj) : error LNK2001: unresolved external symbol "private: static class std::locale::_Locimp * __cdecl std::locale::_Init(void)" (?_Init@locale@std@@CAPAV_Locimp@12@XZ)
1>libboost_program_options-vc120-mt-s-1_58.lib(options_description.obj) : error LNK2001: unresolved external symbol "private: static class std::locale::_Locimp * __cdecl std::locale::_Init(void)" (?_Init@locale@std@@CAPAV_Locimp@12@XZ)
1>libboost_program_options-vc120-mt-s-1_58.lib(options_description.obj) : error LNK2001: unresolved external symbol "public: __thiscall std::_Mutex::~_Mutex(void)" (??1_Mutex@std@@QAE@XZ)
1>libboost_program_options-vc120-mt-s-1_58.lib(options_description.obj) : error LNK2001: unresolved external symbol "public: void __thiscall std::_Mutex::_Lock(void)" (?_Lock@_Mutex@std@@QAEXXZ)
1>libboost_program_options-vc120-mt-s-1_58.lib(options_description.obj) : error LNK2001: unresolved external symbol "public: void __thiscall std::_Mutex::_Unlock(void)" (?_Unlock@_Mutex@std@@QAEXXZ)
1>libboost_program_options-vc120-mt-s-1_58.lib(options_description.obj) : error LNK2001: unresolved external symbol "public: __thiscall std::_Mutex::_Mutex(void)" (??0_Mutex@std@@QAE@XZ)
1>C:\Users\Admin\Desktop\i2pd-0.9.0\Win32\Release\i2pd.exe : fatal error LNK1120: 8 unresolved externals
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by orignal** [comment]
UPnP never worked for windows

**Comment by ygrishin** [comment]
I will take a look at the compile error in a few days. Regarding UPnP issue, not sure how much involment there is. Cannot promise anything.

**Comment by orignal** [comment]
Don't worry about UPnP. Just build errors.

**Comment by kytvi2p** [comment]
@darkstrike420, it looks like the problem is with your build environment. I *just* finished building Boost for x86 and amd64 and I was able to build I2Pd from master with it without any problems.

I followed the instructions that I wrote a few months ago: https://github.com/PurpleI2P/i2pd/blob/master/Win32/README-Build.txt

**Comment by kytvi2p** [comment]
````
error LNK2038: mismatch detected for '_MSC_VER': value '1600' doesn't match value '1800' in AddressBook.obj
````

Yes, with all of those linking errors I think it's just your build environment. I'd suggest cleaning the i2pd source and trying again. If that doesn't work, move your `Boost` libs out of the way and try rebuilding both them and i2pd. Following the instructions linked above  debug x86, debug x64, release x86, and release x64 all built fine.
