### ISSUE TITLE
Attack mitigation status

### ISSUE THREAD

**Issue by SidorKozlov** [PurpleI2P/i2pd#1920]
Please give a short update about the mitigation efforts.
Is victory in sight or should users prepare themselves for much longer unavailability?

**Comment by Vort** [comment]
Previous wave lasted for 24 hours (2023-04-30 .. 2023-05-01). It stopped before effective mitigation was developed.
New wave started today, 2023-05-03 and _it looks like_ attacker changed approach and easy half-developed mitigation do not work anymore.
So new approaches needed. There are ideas of course about how to do this, but developers do not have much time to make i2pd fixes, that's why development will take time.

**Comment by SidorKozlov** [comment]
Thank you. I noticed the change of approach too. v2.42.1 does not work anymore.
If there's anything I can do to, I'd be happy to take tasks, whatever they may be,
because I'm financially dependent on i2pd, not just I2P.

**Comment by SidorKozlov** [comment]
I have years of coding experience.

**Comment by Vort** [comment]
> I'd be happy to take tasks

> I have years of coding experience.

Here is the plan from 2023.04.30:

> [17:18:23] <~orignal> короче рассказываю план действий
[17:18:44] <~orignal> 1.на не флудфиле незапршенные флудфилы не принимаем
[17:19:07] <~orignal> 2. если флудфил то принимаем непосредственно с него естественно если совпадает адрес
[17:19:28] <~orignal> 3. если приходит через флуд то принимаем только ранее известные
[17:19:57] <~orignal> жду конструктивной критики

I doubt that anyone except him knows how to do this.

**Comment by SidorKozlov** [comment]
Let me try to work this out and to read more about i2p(d)'s intricacies. Then I'll be back hopefully with intelligent questions and approaches.

**Comment by SidorKozlov** [comment]
Sure, I'm on it.

**Comment by SidorKozlov** [comment]
Is it better to reset the state directory or not for testing changes?

**Comment by SidorKozlov** [comment]
this is the translation i got:

> [17:18:23] <~original> in short, I tell the action plan
> [17:18:44] <~original> 1.on a non-floodfile, we do not accept unsolicited floodfiles
> [17:19:07] <~orignal> 2. if the floodfil is accepted directly from it, naturally if the address matches
> [17:19:28] <~original> 3. if it comes through a flood, then we accept only previously known
> [17:19:57] <~original> waiting for constructive criticism

i will explain as far i can understand it, to make sure i'm getting it right:

1. routers should only ask floodfills for other floodfills, they will never accept a floodfill info being transmitted to them if it wasn't requested before.

2. `a router` asks **a floodfill** for *other floodfills* through `a direct connection`, if **that floodfill** returns *a (list of ?) floodfill(s)* which includes **the floodfill itself**, **the floodfill's** address in *the transmitted list* must be the same as the destination address of `the direct connection`, else it is filtered out.

3. "a flood" means `a router` publishes its own info to **a floodfill** by direct connection. after that **the floodfill** pushes that info to *a few other floodfills* it thinks are near the `publishing router`.
now: if **a floodfill** pushes/floods the router info of **itself** to *other floodfills*, **the floodfill** has to be known as a floodfill already, or it won't be attributed floodfill status when saving the router info.

have i understood everything correctly?

**Comment by SidorKozlov** [comment]
> Some people say that it helps, but not many people tested it.

Test failed:
`Tunnel creation success rate: 0%, Routers: 15798, Floodfills: 8562, LeaseSets: 28, Client Tunnels: 2, Transit Tunnels: 513`

**Comment by SidorKozlov** [comment]
and one suggestion from the last thread about the attack:
`Extending the length of the exploration tunnel and reducing the mass to 6 hop 1 tunnel also seems to mitigate the attack`

doesn't help either, at least not anymore.

**Comment by VictorBurtsev** [comment]
> @SidorKozlov can you try to test node with number `8` changed to number `1` in this line?
> 
> https://github.com/PurpleI2P/i2pd/blob/fb83ca42f418ae3fad1ca4d66b3db0b1f9ffb85c/libi2pd/NetDb.hpp#L41
> 
> Some people say that it helps, but not many people tested it.



> > Some people say that it helps, but not many people tested it.
> 
> test failed: `Tunnel creation success rate: 0%, Routers: 15798, Floodfills: 8562, LeaseSets: 28, Client Tunnels: 2, Transit Tunnels: 513`
> 
> it died a bit slower maybe, but no practical difference, practically the same as the latest commit, and still worse than v2.42.1

I am confim it. Router die slower. Build - latest commit and `rm -rf /home/i2pd/data/*` with change

`const int NETDB_MIN_TUNNEL_CREATION_SUCCESS_RATE = 1; // in percents `

`Uptime: 20 minutes, 35 seconds`
`Network status: OK`
`Tunnel creation success rate: 2%`
`Received: 20.20 MiB (100.77 KiB/s)`
`Sent: 40.31 MiB (116.82 KiB/s)`
`Transit: 5.67 MiB (46.49 KiB/s)`
`Data path: /home/i2pd/data`
`Hidden content. Press on text to see.`
`Routers: 2296 Floodfills: 1852 LeaseSets: 17`
`Client Tunnels: 17 Transit Tunnels: 120`

**Comment by SidorKozlov** [comment]
> > @SidorKozlov can you try to test node with number `8` changed to number `1` in this line?
> > https://github.com/PurpleI2P/i2pd/blob/fb83ca42f418ae3fad1ca4d66b3db0b1f9ffb85c/libi2pd/NetDb.hpp#L41
> > 
> > Some people say that it helps, but not many people tested it.
> 
> > > Some people say that it helps, but not many people tested it.
> > 
> > 
> > test failed: `Tunnel creation success rate: 0%, Routers: 15798, Floodfills: 8562, LeaseSets: 28, Client Tunnels: 2, Transit Tunnels: 513`
> > it died a bit slower maybe, but no practical difference, practically the same as the latest commit, and still worse than v2.42.1
> 
> I am confim it. Router die slower. Build - latest commit and `rm -rf /home/i2pd/data/*` with change
> 
> `const int NETDB_MIN_TUNNEL_CREATION_SUCCESS_RATE = 1; // in percents `
> 
> `Uptime: 20 minutes, 35 seconds` `Network status: OK` `Tunnel creation success rate: 2%` `Received: 20.20 MiB (100.77 KiB/s)` `Sent: 40.31 MiB (116.82 KiB/s)` `Transit: 5.67 MiB (46.49 KiB/s)` `Data path: /home/i2pd/data` `Hidden content. Press on text to see.` `Routers: 2296 Floodfills: 1852 LeaseSets: 17` `Client Tunnels: 17 Transit Tunnels: 120`

have you tested under load? because i've often had states that looked promising with various configurations, until i tried to create my incoming tunnels.

**Comment by VictorBurtsev** [comment]
> > I am confim it. Router die slower. Build - latest commit and `rm -rf /home/i2pd/data/*` with change
> > `const int NETDB_MIN_TUNNEL_CREATION_SUCCESS_RATE = 1; // in percents `
> > `Uptime: 20 minutes, 35 seconds` `Network status: OK` `Tunnel creation success rate: 2%` `Received: 20.20 MiB (100.77 KiB/s)` `Sent: 40.31 MiB (116.82 KiB/s)` `Transit: 5.67 MiB (46.49 KiB/s)` `Data path: /home/i2pd/data` `Hidden content. Press on text to see.` `Routers: 2296 Floodfills: 1852 LeaseSets: 17` `Client Tunnels: 17 Transit Tunnels: 120`
> 
> have you tested under load? because i've often had states that looked promising with various configurations, until i tried to create my incoming tunnels, then "client tunnels" went to zero.
> 
> also i did try with clean statedir, and floodfill count still went that high

Hi. I have xd-torrent-client. This is correct load for tests?

**Comment by SidorKozlov** [comment]
> Hi. I have xd-torrent-client. This is correct load for tests?

Hi. I'm not sure there is a correct and incorrect, as long as it can handle the use-case you need it for, it can be considered a partial success.

**Comment by SidorKozlov** [comment]
@Vort
looking at the code, reducing `NETDB_MIN_TUNNEL_CREATION_SUCCESS_RATE` results in dead routers being revived less aggressively. i'm going to make `GetTunnelCreationSuccessRate() ` return a floating point value instead of an integer and test with `NETDB_MIN_TUNNEL_CREATION_SUCCESS_RATE = 0.1` next.

**Comment by SidorKozlov** [comment]
before use:
Uptime: 20 minutes, 19 seconds
Network status: OK
Network status v6: Firewalled
Tunnel creation success rate: 6%
Received: 47.22 MiB (163.41 KiB/s)
Sent: 81.56 MiB (276.48 KiB/s)
Transit: 15.00 MiB (95.37 KiB/s)
Data path: /var/lib/i2pd
Routers: 3344 Floodfills: 2161 LeaseSets: 9
Client Tunnels: 31 Transit Tunnels: 466

**Comment by SidorKozlov** [comment]
from what i can tell so far the issue is **completely** gone, the network is responsive as ever.
bad routers are culled so quickly they can't pile up.
so until there is a more general solution, fine-tuning `NETDB_MIN_TUNNEL_CREATION_SUCCESS_RATE` seems to be it.
(assuming the attack hasn't stopped in the meantime)

**Comment by SidorKozlov** [comment]
it makes sense to give people with a very unstable internet connection the ability to increase that constant,
while keeping it low in most cases so that it can't be abused for denial of service

**Comment by SidorKozlov** [comment]
#1922

**Comment by SidorKozlov** [comment]
looks like 4ce2ef1d8381c2d93ebcdd77e8017123ae3a23c3 (latest commit) fixes everything,
my whole app including other peers is online again.
you are king bro @orignal
