### ISSUE TITLE
HTTP Proxy not properly handling responses

### ISSUE THREAD

**Issue by darkstrike420** [PurpleI2P/i2pd#193]
http://127.0.0.1:7070/zmw2cyw2vj7f6obx3msmdvdepdhnw2ctc4okza2zjxlukkdfckhq.b32.i2p

When you go to any I2P site like this, you will never see any images. On Firefox at finish of loading, it quickly shows error "Connection has been terminated" probably because of the malformed response.

IE says: "This page can’t be displayed

•Make sure the web address http://127.0.0.1:7070 is correct.
•Look for the page with your search engine.
•Refresh the page in a few minutes.
"

On Chrome you can see text, hehe.

**Comment by orignal** [comment]
1. That's not  about proxy.
2. That's windows

**Comment by darkstrike420** [comment]
Windows is not as supported as Linux?

It is about proxy. When going through this proxy then sites think that main page is localhost instead of their. Firefox and IE can't even load any pages through this proxy.

If i2pd was purely C++ without boost then I would fix it and make a pull request but I have no experience with boost.

**Comment by orignal** [comment]
There are no maintainers for windows part of the project. I develop for Linux only.

127.0.0.1:7070 is not proxy. It's diagnostics page accessible through clearnet only.
If you want to use proxy you must specify it in your browsers settings 127.0.0.1:4446 
Unlike Java I2P i2pd proxy doesn't allow access to clearnet resources.

Try to build release 0.9.0. It's sure buildable for Windows.

**Comment by darkstrike420** [comment]
Sorry, I thought 127.0.0.1:7070/i2p.b32.i2p was supposed to be a full proxy.

I posted in another "Issue" that 0.9.0 doesn't compile. I was able to successfully compile 0.3 some time ago.

Ill try to add UPnP support for Windows without DLL dependencies. Such a shame I don't have experience with boost.

**Comment by orignal** [comment]
Kate
127.0.0.1:7070/...b32.i2p was use for debuggign only long time ago
