### ISSUE TITLE
Changelog for release 2.48.0

### ISSUE THREAD

**Issue by SilmorSenedlen** [PurpleI2P/i2pd#1937]
Will there be a list of changes for this version?
Then it is not clear what changes to expect and what to test : /

**Comment by Vort** [comment]
You can read about changes here:
https://github.com/PurpleI2P/i2pd/blob/ca02b5d860d7989c44355f9cbc35bc0e2449638d/ChangeLog#L4-L31

**Comment by SilmorSenedlen** [comment]
> You can read about changes here:

Thx!
And I hope that changelogs will be published for future releases.
Looking for them this way is not too trivial for common user :)

**Comment by orignal** [comment]
I didn't forget, just being busy. Will finish in 1-2 days.
