### ISSUE TITLE
Crash on Win32 when no internet

### ISSUE THREAD

**Issue by darkstrike420** [PurpleI2P/i2pd#194]
I2Pd crashes on Windows when no internet connection is available.

Reproduce: Disable networking, start i2pd. It will crash.

**Comment by orignal** [comment]
please run under debugger and provide stack

**Comment by darkstrike420** [comment]
Please look https://github.com/PurpleI2P/i2pd/issues/192 and will do when you help me fix that(link errors).

**Comment by darkstrike420** [comment]
The crash cause is a failed connection to reseed. I also noticed that the reseed servers are unreachable 1/10 times.

**Comment by orignal** [comment]
comment out all http reseeds, leave https only.
Probably they shut them down.
I will add manual reseed soon and from i2pd.website

**Comment by darkstrike420** [comment]
is i2pd remembering peers by writing them to HDD? It would be cool if users could export known peers and then make seed.

If i2pd was able to know a lot of peers instantly after starting then I think it would speed it up a lot.

**Comment by orignal** [comment]
Sure it store router in ~/.i2pd/netdb same way as Java I2P does. I'm working on reseed service at i2pd.website now, but providing i2pseeds.su3 file signed by my certificate. 

If you are talking to persist list of peer of successive tunnels and bring them back after restart, I have such plan as well.

**Comment by darkstrike420** [comment]
"If you are talking to persist list of peer of successive tunnels and bring them back after restart, I have such plan as well."

This is excellent! Is there a forum for i2pd?

**Comment by orignal** [comment]
I will add the forum to i2pd.website in few days

**Comment by orignal** [comment]
http://i2pd.website/?q=forum

**Comment by darkstrike420** [comment]
I think it would be cool if the website was accessible through I2P. Its a i2p website afterall.

**Comment by orignal** [comment]
there is orignal.i2p already, I will forward it once I get this feature for I2P tunnel in place
