### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by drequivalent** [PurpleI2P/i2pd#196]
Каковы пути развития проекта?
Хотелось бы увидеть роадмап, дабы знать, каких плюшек еще ждать.

**Comment by orignal** [comment]
1. http тоннели чтобы заголовки подменял
2. EdDSA 
3. Собственные ресиды
Ну и в целом уменьшение потребленяи памяти и исправление багов.

**Comment by anonimal** [comment]
@EinMByte Can we close this now that #279 is open?

**Comment by EinMByte** [comment]
@anonimal Sure, closed.
