### ISSUE TITLE
Somebody Help!!!

### ISSUE THREAD

**Issue by watchdog1218** [PurpleI2P/i2pd#1964]
![화면 캡처 2023-08-30 172057](https://github.com/PurpleI2P/i2pd/assets/35187791/755e3712-14ef-425c-80aa-5d06bf4d5742)
I want to enable to BOB, I2CP, I2PControl :(

OS: Linux Mint
Browser: Firefox

**Comment by Vort** [comment]
These features can be enabled by editing `i2pd.conf` file.

**Comment by watchdog1218** [comment]
> These features can be enabled by editing `i2pd.conf` file.
How can I edit the file?

**Comment by watchdog1218** [comment]
hmm... Ok Thank you so Much!!
