### ISSUE TITLE
snark version for i2pd  (request)

### ISSUE THREAD

**Issue by coolst3r** [PurpleI2P/i2pd#1973]
would like to know if this is possible

**Comment by r4sas** [comment]
Use i2psnark, i2pd has full compatibility with it.

**Comment by coolst3r** [comment]
> Use i2psnark, i2pd has full compatibility with it.

i have tryed but it wont detect ip2d

**Comment by r4sas** [comment]
Looks like you haven't enabled the I2CP protocol in i2pd config file. Check it.
