### ISSUE TITLE
Questions about I2Pd in OpenWrt

### ISSUE THREAD

**Issue by Monoloshka** [PurpleI2P/i2pd#1974]
Why in OpenWRT in the i2pd.conf file when I remove the # symbol in the # subscriptions = http://reg.i2p/hosts.txt,http://identiguy.i2p/hosts.txt,http://stats.i2p/cgi-bin/newhosts.txt,http://rus.i2p/hosts.txt line, i2p access is lost. I tried removing the # in the # addressbook = true line, but that didn't help either. How do I set my subscriptions? 
Here is my list of subscriptions:
http://i2p-projekt.i2p/hosts.txt
http://identiguy.i2p/hosts.txt
http://reg.i2p/export/hosts.txt
http://inr.i2p/export/alive-hosts.txt
http://notbob.i2p/hosts.txt
http://skank.i2p/hosts.txt
http://i2pjump.i2p/hosts
http://shx5vqsw7usdaunyzr2qmes2fq37oumybpudrd4jjj4e4vk4uusa.b32.i2p/hosts.txt
https://i2pplus.github.io/hosts.txt
https://raw.githubusercontent.com/i2p/i2p.i2p/master/installer/resources/hosts.txt
How do I combine networks for simultaneous access to Tor (onion domains and bypassing site blocking (internet censorship)) and I2Pd in OpenWRT? Also I additionally put adblock package in OpenWrt.
I also additionally use the /etc/dnsmasq.conf file to access the OpenNIC network: server=/bazar/bbs/chan/coin/cyb/dyn/emc/epic/free/fur/geek/glue/gopher/indy/ko/ku/lib/libre/neo/null/o/oss/oz/parody/pirate/rm/te/ti/uu/IP address. In the torrc file I specify the VirtualAddrNetwork parameter so that when there is a call to the dns server on port 9053 the redirection goes to a specific range of ip example: 10.254.0.0/16. In the file /etc/config/dhcp I specify which domain zones and domains should go through dns Tor to get to the Tor network. In Firewall I specify redirection of all tcp connections on all ports to Tor proxy on port 9040 and there it is already decided through dns what will go through Tor and what will be available directly without Tor network.
These articles helped me to understand Tor setup: https://openwrt.org/docs/guide-user/services/tor/client and https://openwrt.org/docs/guide-user/services/tor/extras

Keep in mind that I have no education in the IT field, I am a very simple computer and Internet user

**Comment by r4sas** [comment]
1. Addresses must be comma-separated. Check i2pd docs. Only i2p subscriptions are available to use. Otherwise, you can make place `hosts.txt` file in i2pd homedir and it will be read when the application starts.
2. i2pd doesn't have any transparent proxy and internal dns, so such thing can't be done.

**Comment by Monoloshka** [comment]
I solved this problem myself. It was necessary to remove the # symbol in the string #daemon = true in order to fill the address book. Access to tor and i2p simultaneously is established through Port Forwards in Firewall and adding address=/i2p/10.253.0.1 to /etc/dnsmasq.conf. I2p stopped working incorrectly. Я решил эту проблему самостоятельно. Необходимо было убрать символ # в строке #daemon = true для того чтоб адресная книга наполнилась. Доступ одновременно в tor и i2p налажен через Port Forwards в Firewall и добавление address=/i2p/10.253.0.1 в /etc/dnsmasq.conf. I2p перестал некорректно работать

**Comment by Monoloshka** [comment]
I solved this problem myself. It was necessary to remove the # symbol in the string #daemon = true in order to fill the address book. Access to tor and i2p simultaneously is established through Port Forwards in Firewall and adding address=/i2p/10.253.0.1 to /etc/dnsmasq.conf. I2p stopped working incorrectly. Я решил эту проблему самостоятельно. Необходимо было убрать символ # в строке #daemon = true для того чтоб адресная книга наполнилась. Доступ одновременно в tor и i2p налажен через Port Forwards в Firewall и добавление address=/i2p/10.253.0.1 в /etc/dnsmasq.conf. I2p перестал некорректно работать

**Comment by r4sas** [comment]
По идее, параметр daemon передается через init.d, так что там от него нет никакого смысла.
Адресная книга заполняется автоматически через 5 минут при первом запуске.
