### ISSUE TITLE
XSS Vulnerability in Address Helper

### ISSUE THREAD

**Issue by ill5-com** [PurpleI2P/i2pd#1976]
Hello, a XSS can be triggered on any domain via the ?i2paddresshelper query.

An example URL to trigger this issue can be found below:

`http://reg.i2p/?i2paddresshelper=%22%3E%3Cscript%3Ealert(1)%3C/script%3E`

Image of the script tag embedded in the page:

![browser](https://github.com/PurpleI2P/i2pd/assets/105583568/5dc74186-0db2-4df8-b5ae-d87c3693681c)

**Comment by Vort** [comment]
Can you recheck with e1b4feb618ecd7ab9fc81c462646182224384e8c?

**Comment by ill5-com** [comment]
> Can you recheck with [e1b4feb](https://github.com/PurpleI2P/i2pd/commit/e1b4feb618ecd7ab9fc81c462646182224384e8c)?

Hi, the example I gave no longer triggers an XSS. However, the most recent commits appear to have broken the address helper entirely. Even the address helper URLs given by reg.i2p no longer work.
