### ISSUE TITLE
How to add subscriptions for automatic update of i2pd package address book in OpenWrt?

### ISSUE THREAD

**Issue by Monoloshka** [PurpleI2P/i2pd#1979]
Как добавить подписки для автоматического обновления адресной книги пакета i2pd в OpenWrt?

**Comment by r4sas** [comment]
По умолчанию они уже есть. Смотрите в конфиг.

**Comment by Monoloshka** [comment]
Why after the "site.i2p/?i2paddresshelper=code" links I still get the message: "Proxy error: Host not found". Почему после ссылок "сайт.i2p/?i2paddresshelper=код" я все равно получаю сообщение: "Proxy error: Host not found"

**Comment by r4sas** [comment]
Could you provide example?

**Comment by Monoloshka** [comment]
https://www.youtube.com/watch?v=Z7_ckpGZIJY

**Comment by r4sas** [comment]
Чего могу сразу сказать - не используйте обычный браузер, которым вы ходите в интернет, чтобы сидеть в i2p. Плюс у вас похоже браузер (или какой то аддон) режет параметры, которые передаются в addresshelper.
