### ISSUE TITLE
Address helper no longer works with Base64 destinations

### ISSUE THREAD

**Issue by ill5-com** [PurpleI2P/i2pd#1981]
In an attempt to fix #1976, something has broken the address helper functionality entirely for Base64 destinations. All address helper URLs with a base64 destination no longer work, including the address helper URLs given by reg.i2p.

Video of the issue: https://github.com/PurpleI2P/i2pd/assets/105583568/94aca81c-48b4-48d2-8f7a-656b19196b00

**Comment by orignal** [comment]
Should be fixed https://github.com/PurpleI2P/i2pd/commit/a6ee1e648e0724d7798986d1f490c22b80105dd9
