### ISSUE TITLE
Stream m_SendBufferMutex deadlock

### ISSUE THREAD

**Issue by 7lon7** [PurpleI2P/i2pd#1983]
set the SendBuffer::SendHandler call AsyncSend<br>
The following function call occur:<br>
***Stream::SendBuffer***(lock) --> ***m_SendBuffer.Get*** --> ***m_Buffers.pop_front*** --> ***~SendBuffer*** --> ***SendHandler*** --> ***AsyncSend***(lock)

**Comment by orignal** [comment]
What is your SendHandler? How do you call AsyncSend?

**Comment by orignal** [comment]
try https://github.com/PurpleI2P/i2pd/commit/8d6eb5b6b2c8f69627cefaa5b6eb4f1010c11631

**Comment by 7lon7** [comment]
> try [8d6eb5b](https://github.com/PurpleI2P/i2pd/commit/8d6eb5b6b2c8f69627cefaa5b6eb4f1010c11631)

Just delete the mutex, it's also not safe when SendBuffer.Add

**Comment by orignal** [comment]
The mutex is not needed anymore and will be deleted later. Need to redo CleanUp
