### ISSUE TITLE
Node time desynchronization

### ISSUE THREAD

**Issue by Vort** [PurpleI2P/i2pd#1988]
Yesterday my node suddenly stopped working:
1. Transit traffic dropped from about 1 MB/s to less than 1 KB/s.
2. NTCP2 transports count went from about 2000 to about 20.

After enabling debug level for logs, I figured out why it happened: node time became desynchronized.
Such messages started to appear: `NTCP2: SessionRequest time difference 58005 exceeds clock skew`.

I have `ntpd` running, so usually time on my machine differs from perfect values only by 10-100 ms.
Having 16 hours difference is almost impossible.

Looking further into logs, I found suspiciously similar values for time differences in such lines:
```text
[07/Dec/2023:21:13:46 +0200]@300/error - NTCP2: RouterInfo is from future for 57582 seconds
[07/Dec/2023:21:14:21 +0200]@300/error - NTCP2: RouterInfo is from future for 57717 seconds
[07/Dec/2023:21:15:01 +0200]@300/error - NTCP2: RouterInfo is from future for 57676 seconds
[07/Dec/2023:21:15:36 +0200]@300/error - NTCP2: RouterInfo is from future for 57642 seconds
[07/Dec/2023:21:16:35 +0200]@300/error - NTCP2: RouterInfo is from future for 57587 seconds
[07/Dec/2023:21:16:59 +0200]@300/error - NTCP2: RouterInfo is from future for 57564 seconds
```

Which means that somehow wrong time from remote node was accepted by my node.
Looks like this is the only place when such time change can happen:
https://github.com/PurpleI2P/i2pd/blob/c802c2deb0eac4e8b012939f0da6128d40bf6b8c/libi2pd/SSU2Session.cpp#L1673

What exactly triggered desynchronization - random event or intentional attack is unclear.
But in any case having such possibility looks wrong, it can be considered as bug and should be fixed.

Version: 2.49.0-34-gc215f2e8

**Comment by multikatt** [comment]
I just want to note that i'm also seeing this exact issue, but all around 58400 seconds in the future. Im also ntp-synced and ive seen this on both 2.49 and 2.50.

**Comment by Vort** [comment]
Looks like there are two varieties of this bug:
1. Node may become locked until user manually unlock it.
2. Node may drop transit to zero and then start recovering automatically.

Outcome probably depends on whether problem appeared in last peer test packet or not.

**Comment by multikatt** [comment]
Not sure if this helps at all but something I noticed; i fired up a java i2p daemon instead and now ive got around 800 banned peers. Of those around 200 are banned due to a time skew of 14, 15 or 16hrs.

**Comment by Vort** [comment]
If you know how to build i2pd from source, you can try d4c47d90cb308c9845888fcc746b30dcb1c96fdd.
There is a chance it will help with desynchronization problems.

**Comment by Vort** [comment]
Also you can try to add `nettime.frompeers = false` to `i2pd.conf` _(before first section)_ if you are sure that your time is fine.

**Comment by multikatt** [comment]
Ok, it's running now. I'm not very sure of what to look for to determine if things are better or not but so far, after running https://github.com/PurpleI2P/i2pd/commit/d4c47d90cb308c9845888fcc746b30dcb1c96fdd, with that setting, for about an hour, the tunnel success rate _seems_ better, it's at around 16% now, whereas it was dropping from 6 down to 2 sometimes before. Still seeing "RouterInfo is from future for" in the logs but they don't look as frequent as before and more evenly spread between 10-60k now. Might be early to say if there's improvements though, so i'll let it chug along.

**Comment by Vort** [comment]
> I'm not very sure of what to look for to determine if things are better or not

Node should be hanging less frequently.

Did you set `nettime.frompeers = false`?
I'm asking because my node froze today despite d4c47d90cb308c9845888fcc746b30dcb1c96fdd.
Now I'm trying with this option. Maybe it will help.

**Comment by multikatt** [comment]
yeah, ive set that now!

**Comment by Vort** [comment]
There is one more fix related to this problem: 21f41a2b2a39461a480b8539beb2f1c141bb8fe7.

**Comment by multikatt** [comment]
Ok, switched to that fix, not seeing any more "from future" or clock skew-errors anyway.

**Comment by Vort** [comment]
There will be `NTCP2: RouterInfo is from future` lines in logs anyway.
It's not a direct sign of a problem.

**Comment by r4sas** [comment]
Closing due to 2.50.2 release.
