### ISSUE TITLE
OpenSSL 3.2.0 incompatibility problem - `cannot connect to the network`

### ISSUE THREAD

**Issue by o0nd7ots** [PurpleI2P/i2pd#1993]
I have run into some problem around the 2.50 update, but that might be when I noticed that something went wrong, not when it first started.

I am using the stock config and have tried this on two different IP (local and VPN).

I get no connections: Tunnel creation date is 0-10%, most often at 0.

I have decided to check the log and here are the errors that I have found:

# For hosts
## Fail to connect
```
17:08:54@940/info - Reseed: Downloading SU3 from https://reseed2.i2p.net/i2pseeds.su3
17:08:54@940/error - Reseed: Failed to connect to reseed2.i2p.net
17:08:54@940/warn - Reseed: SU3 download failed
```
I also recall getting some 429 http error codes here.
## Fail to verify the SU3
I have also included the 10 reseed message
```
17:11:11@940/info - Reseed: Downloading SU3 from https://i2p.ghativega.in/i2pseeds.su3
17:11:11@940/debug - Reseed: Resolved to 95.216.198.59
17:11:12@940/debug - Reseed: Connected to i2p.ghativega.in:443
17:11:12@940/debug - Reseed: Got 72196 bytes of data from https://i2p.ghativega.in:443/i2pseeds.su3
17:11:12@940/warn - Reseed: Certificate for arnavbhatt288@mail.i2p not loaded
17:11:12@940/critical - Reseed: SU3 verification failed
17:11:12@940/warn - Reseed: Failed to reseed from servers after 10 attempts
17:11:12@940/warn - Reseed: Failed to reseed from servers
```
# Fail to build tunnels:
```
17:12:57@897/info - NetDb: Exploring new 9 routers ...
17:12:59@576/warn - Tunnel: Can't find any router, skip creating tunnel
17:13:04@576/debug - Tunnels: Creating destination outbound tunnel...
17:13:04@576/info - Tunnels: Can't select first hop for a tunnel. Trying already connected
17:13:04@576/error - Tunnels: Can't select next hop for XXX
17:13:04@576/error - Tunnels: Can't create outbound tunnel, no peers available
```

# My question
Do any of you know how to fix this?

**Comment by Vort** [comment]
What version of OpenSSL you have?

**Comment by o0nd7ots** [comment]
3.2.0-1 (provides libcrypto.so=3-64  libssl.so=3-64)

**Comment by Vort** [comment]
There is known incompatibility between OpenSSL 3.2.0 and i2pd 2.50.
If you know how to build i2pd from sources, then try upgrading it to latest commit (43e130ee347c9aea7a840ebfa242ec897f906886).
If not, try to downgrade either i2pd or OpenSSL.

**Comment by o0nd7ots** [comment]
> There is known incompatibility between OpenSSL 3.2.0 and i2pd ≤ 2.50.0.

Do you mean i2pd 2.50 and below or 2.50 and above?

When did this incompatibility came to be? Have I not noticed it for long?

**Comment by Vort** [comment]
> Do you mean i2pd 2.50 and below or 2.50 and above?

I mean fix in i2pd (43e130ee347c9aea7a840ebfa242ec897f906886) is made 3 days ago.
Every version including 2.50 (which was released 4 days ago) is not compatibvle with OpenSSL 3.2.

> When did this incompatibility came to be? Have I not noticed it for long?

It appeared after release of OpenSSL 3.2.
There were no such problems with OpenSSL 3.1.

**Comment by o0nd7ots** [comment]
I see, thank you for the information.

The issue can be closed from where I stand.

**Comment by orignal** [comment]
2.50.1
