### ISSUE TITLE
Crashes seemingly at random while running in a Docker container on Raspberry Pi 3 B+

### ISSUE THREAD

**Issue by Supermath101** [PurpleI2P/i2pd#1995]
After upgrading from `2.49.0` to the latest version (`2.50.1`), I2Pd crashes after a couple hours. I am running this in Portainer CE (Docker container) on a Raspberry Pi 3 B+. I've configured it to restart failed containers, and it's been restarting in intervals of two to three hours. I've set the log level to `debug`. Here is the last 3,000 lines of the log file before crashing: [i2pd_crash.log](https://github.com/PurpleI2P/i2pd/files/13789146/i2pd_crash.log)

**Comment by Vort** [comment]
If I remember correctly, to collect information about crash, version of i2pd with debug symbols should be built from source code. Then OS generates crash dump and with GDB it is possible to get stack trace of crash.
However, I have little experience with Linux and no experience with containers, so maybe someone else can provide more details.

**Comment by Vort** [comment]
It may be the same crash as in #1997.
Try 302af823a3509e5faa0e5cfcacdef2e480250d88 or latest commit if you can.

**Comment by Supermath101** [comment]
> It may be the same crash as in #1997. Try [302af82](https://github.com/PurpleI2P/i2pd/commit/302af823a3509e5faa0e5cfcacdef2e480250d88) or latest commit if you can.

Okay, it's been running for almost a day on the latest commit. Thanks for the help.
