### ISSUE TITLE
Is it possible to bind the webconsole to 2 IP addresses, specifically one IPv4 and one IPv6?

### ISSUE THREAD

**Issue by silmarine** [PurpleI2P/i2pd#2001]
I have set my network up to support both IPv4 and IPv6 and all hostnames resolve to an IP for both. I set up i2pd on a VM on my server and if I set the http.address to the IPv4 and access the webconsole with the IP, not the hostname, it works. But not with the hostname because IPv6 is prioritized when both are available. I tried setting http.address to 0.0.0.0 but then I get a "host mismatch" error. Is there a way to set http.address to 2 address, one for the IPv4 and the other for IPv6, or a better way to do this?

**Comment by Vort** [comment]
I suggest to experiment with `http.hostname` and `http.strictheaders` options.

**Comment by silmarine** [comment]
Ah thank you, having the following in my i2pd.conf file made it work in that I can access it with my preferred hostname and other hostnames or IP addresses do not.
`[http]
 enabled = true
 address = 0.0.0.0
 hostname = i2pd.domain.tld
 port = 7070
 strictheaders = true
`
There's no security issues with this, is there?

**Comment by Vort** [comment]
> There's no security issues with this, is there?

It depends on:
1. Who have access to webconsole port.
2. Who can listen to or intercept your communications with webconsole.

If communication happens only between host OS and guest OS and ports are not accessible from outside, then no security problems.
If you access webconsole over the Internet and hope that no one will find your port, then there are problems.

**Comment by silmarine** [comment]
I am not exposing this port to the internet at all, I even have the VM behind a firewall and only allow connection to the IPs and port number 7070 from my private internal networks. But I will be setting the proxy up on other systems in my network (for example my laptop will have a proxy set to the VM IP), but again only from/to private IP ranges.
