### ISSUE TITLE
SAM: can't connect to self

### ISSUE THREAD

**Issue by anikey-from-i2p** [PurpleI2P/i2pd#2005]
### Steps to reproduce:

Open three terminals, all with netcat to SAM port.

Terminal 1 (input only):
```
HELLO VERSION
SESSION CREATE STYLE=STREAM ID=testing DESTINATION=TRANSIENT SIGNATURE_TYPE=7 i2cp.leaseSetEncType=4,0 inbound.length=2 outbound.length=2 inbound.quantity=2 outbound.quantity=2
NAMING LOOKUP NAME=ME
```

Copy the VALUE of NAMING LOOKUP.

Terminal 2 (input only):
```
HELLO VERSION
STREAM ACCEPT ID=testing
```

Terminal 3 (input only):
```
HELLO VERSION
STREAM CONNECT ID=testing DESTINATION=<paste the VALUE from NAMING LOOKUP>
```

Then try communicating with terminal 2 and 3.

In java i2p, it works fine: messages from one side appear on the other with a slight delay (because of tunnels i guess).

In i2pd it does not work:

- in the terminal with STREAM ACCEPT it prints the destination, but the messages sent from the other one do not appear
- in logs it keeps saying about missing / not finding remote leaseset
- in webconsole streams list there are 2 streams: one with received=0, another with sent=0

### practical consideration

qbittorrent seems to like to connect to itself.

**Comment by Vort** [comment]
I confirm this behaviour, with 2.50.1-8-g5cf1961f.

**Comment by Vort** [comment]
Check for self address was added intentionally, with this commit: https://github.com/PurpleI2P/i2pd/pull/378/commits/d81ca5f919e1f0f7290c19e9fa379c2c1a3e7f2e.

However, no one remember why it was needed to be done this way.

I tried to disable check here:
https://github.com/PurpleI2P/i2pd/blob/dfe8b25e5ec2d0533584bf03cf0d1289bc1ca71d/libi2pd/Destination.cpp#L446-L452

Connection established correctly, nothing exploded.

But I can't be sure that is it safe to make such change of course.

**Comment by orignal** [comment]
I don't see a reason why a destination should be able to connect to itself.  For testing purposes, just create two session. Hence this check was added to avoid some potential security breaches.

**Comment by Vort** [comment]
Probably related:
https://github.com/qbittorrent/qBittorrent/issues/10791
https://github.com/arvidn/libtorrent/issues/7479

**Comment by orignal** [comment]
I would prefer to return CANT_REACH_PEER error in this case

**Comment by zzzi2p** [comment]
after discussion, Java I2P agrees with orignal that we should send CANT_REACH_PEER, and propose to make that change in our code unless somebody can come up with a good reason why we should support loopback

**Comment by orignal** [comment]
https://github.com/PurpleI2P/i2pd/commit/cd087568b55161767c6094f86054d4976e137209

**Comment by anikey-from-i2p** [comment]
I just thought i should report it because it also causes log spam with messages like "Remote LeaseSet not found" and "Can't send packets, missing remote LeaseSet, sSID=..."

**Comment by zzzi2p** [comment]
https://i2pgit.org/i2p-hackers/i2p.i2p/-/merge_requests/173
