### ISSUE TITLE
[Question] - How to backup current i2pd address and transfer to a new machine?

### ISSUE THREAD

**Issue by rmszc81** [PurpleI2P/i2pd#2008]
Hello everyone,

currently, I'm using  i2pd in arch linux arm (aarch64, in the host OS) and then, due to some hardware problems, I'm moving my i2p website to another arch linux machine (x86_64, in the host Os) that's running docker (the container is Alpine Linux, ip2d is installed via apk add i2pd).

So far, so good, i2pd works well inside a docker container, but then, there's something that's really bothering me at the moment...

The configuration files (i2pd.conf, tunnels.conf) and the keys file (hidden-service.dat) are exactly the same (their hash matches), but then, the i2p address is different. Is this by design or, am I doing something wrong here?

Thank you very much!

**Comment by Vort** [comment]
If I understand correctly, identical `.dat` files should produce identical addresses.
Probably something is wrong with file locations - maybe you are using files from different place not knowing about it.

**Comment by rmszc81** [comment]
@Vort the .dat files must have the same name, or, just the file content is enough?

**Comment by Vort** [comment]
Name should not matter.

**Comment by Vort** [comment]
For example, [this file](https://github.com/PurpleI2P/i2pd/files/14025497/private.zip) should contain keys for address `abcdentj2anebyhtt6ddliwkzq5tlhp7so3opwf26ywmqgo27ltq`. Can you check it?

**Comment by rmszc81** [comment]
@Vort sure, let me test it! Wait a bit please!

**Comment by rmszc81** [comment]
Your file matches:

![image](https://github.com/PurpleI2P/i2pd/assets/11450286/5538d4f9-79f0-4073-b224-37daf74223f9)

Let me see in my system what have may happened.

**Comment by rmszc81** [comment]
So, the problem was docker cache.  After forcing clearing the cache, everything went fine. Thanks anyway @Vort. I'm closing this issue now.
