### ISSUE TITLE
Don't send ASIO messages with buffer on local stack

### ISSUE THREAD

**Issue by mlt** [PurpleI2P/i2pd#203]
Check that buffers used to send asynchronous messages still exist after, e.g., _async_write_ calls as buffers aren't copied. For example, [here](https://github.com/PurpleI2P/i2pd/blob/master/HTTPProxy.cpp#L93) _static_ won't hurt to make sure it is always there and not destroyed. Otherwise it dies under MSVC with weird messages. I didn't check other places.

**Comment by orignal** [comment]
@klondi  !!!
