### ISSUE TITLE
[Feature] Reseed on network up

### ISSUE THREAD

**Issue by arthurmelton** [PurpleI2P/i2pd#2032]
I have I2pd start at boot, but sometimes it does not have internet at the start, so it fails reseeding. Once I do get internet, it does not have any peers.

I have created a network manager hook to launch I2pd once I get a network connection, but I was wondering if it could try to automatically reseed?

**Comment by Vort** [comment]
You can try setting `limits.zombies` option to prevent losing all routerinfo during offline period.
It specifies minimum Tunnel creation success rate, below which clearing should pause.

What amount of Routers: your web interface shows when there is no internet access for a long time?

**Comment by arthurmelton** [comment]
I should have specified this is effectively the first boot of the program as I run `/var` in a tmpfs. So the program does not have any peers that it knows of, and so when it gets connected to internet it has no one to talk to.

**Comment by arthurmelton** [comment]
I was looking into how the reseeding process works, and implementing some system to wait to reseed once there is more than just the loopback device does not look that hard. I could not find anything in boost asio to get all the interfaces and IP addresses, but I did find https://github.com/GMLC-TDC/netif, which could help. You could probe the `getInterfaceAddressesAll()` every second or so, and see if the size of the response is bigger than 2 (to confirm we have more than just `127.0.0.1` and `::1`). We can't necessarily rely on some service or IP address to always be up, for us to ping, and there is a chance someone would use i2p on a private network. I don't see the point of using i2p on the loopback device, so I think this would be the safest way to do it.

**Comment by Vort** [comment]
Main problem is that clean start every time is not intended mode of operation for I2P software.
It provides unnecessary load on reseeds and floodfills.
That's why I don't see much sense in making it easier to use.

**Comment by arthurmelton** [comment]
This is not really about the feature request anymore, and it is mainly just for me.

Roughly how long are the `.su3` reseed bundles valid for? I am wondering if I could just download the reseed bundles every once in a while and reseed off of them. I believe that would still be inefficient for floodfills though, and I don't know of any way to store the netDB in some transferable file.

**Comment by Vort** [comment]
> I don't know of any way to store the netDB in some transferable file

Just pack it with `.zip` or something like that, transfer and unpack.
