### ISSUE TITLE
Accept Contributions/PRs from Who Involved in Monero

### ISSUE THREAD

**Issue by HardenedSteel** [PurpleI2P/i2pd#2034]
Current [coding guidelines](https://github.com/PurpleI2P/i2pd/wiki/Coding-guidelines) doesn't allow someone to contribute I2Pd if someone involved in Monero but meanwhile I2Pd accepts Monero as donation.

I believe I2Pd should accept contributions or/and pull requests from who involved in Monero.

**Comment by preland** [comment]
I don’t get it. Why is this an issue?

The value of a contribution is the code itself, not the individual that makes the contribution.

Even if the individual has poor intentions, any issues with the contribution will be completely visible.

And let’s face it: everyone has their own motives for doing what they do. There are no saints, especially not in the privacy world(speaking of privacy, someone could just sockpuppet their contributions to get around this rule).

This rule should be removed, or better yet, replaced with a clause that says that one’s intention with any contribution should be explicitly stated, and that their intentions can and will be questioned by reviewers. That way, the heart of this rule remains, and the hyperspecific hate is gone.

**Comment by SamsungGalaxyPlayer** [comment]
I know i2pd and Monero (with Kovri) had a complicated history at times, but a lot has changed (for the better!) over the last few years. Kovri is dead, and both communities have moved on. The official Monero wallets and nodes support i2p. The i2p community accepts Monero donations. I think it would be good for everyone to repair relations where possible.

**Comment by orignal** [comment]
> I believe I2Pd should accept contributions or/and pull requests from who involved in Monero.

Don't we do it now?

**Comment by orignal** [comment]
> Current [coding guidelines](https://github.com/PurpleI2P/i2pd/wiki/Coding-guidelines) doesn't allow someone to contribute I2Pd if someone involved in Monero

Changed

**Comment by HardenedSteel** [comment]
Glad to hear! Thank you.
