### ISSUE TITLE
bind: address already in use

### ISSUE THREAD

**Issue by jimerickson** [PurpleI2P/i2pd#204]
i2pd starting

21:30:31/info - Version 0.9.0
21:30:31/info - data directory: /home/jim/.i2pd
21:30:31/info - CMD parameters:
21:30:31/info - 0  /home/jim/i2pd/i2p
21:30:31/info - HTTP Server started
21:30:31/warn - Unexpected SSU address brownhome.dlinkddns.com
21:30:31/warn - Unexpected SSU address pfo3a4lsg0.airdns.org
21:30:31/warn - Unexpected SSU address jihemel.com
21:30:31/warn - Unexpected SSU address home.wagner.pp.ru
21:30:31/warn - Unexpected SSU address nat128.dzx.dhcp.biz
21:30:31/warn - Unexpected SSU address cellarnet.co.uk
21:30:31/warn - Unexpected SSU address outside.sudog.com
21:30:31/info - 1311 routers loaded
21:30:31/info - 121 floodfills loaded
21:30:31/info - NetDB started
terminate called after throwing an instance of '21:30:31/info - Start listening TCP port XXXXX
boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  bind: Address already in use
Aborted (core dumped)
[jim@nuc i2pd]$ 

freshly compiled from git. fresh reboot, nothing else running. what have i done wrong? on fedora 22, kernel 4.0.4-303. i double checked and there is nothing using the port. i tried the java client and it runs fine on the same port.  using java client for now but would like to get i2pd running. sorry to bother you with this. thanks for all your work.

**Comment by orignal** [comment]
have you tried nc -l XXXXX ?

**Comment by jimerickson** [comment]
nc -l XXXXX returns the following:

[jim@nuc ~]$ nc -l XXXXX

                  [0/7]
2��!o)��        ��L
hL,Jc?5�W���O��k�l��j�e_�b9m���8ַ���%m�  �s/W��KU&j
2_�Xj[h���b���j���]y���B����g�池�_*1�ym�3�qwU7��L�<���/Z�M<��k�[B5y�ofo�d�u���@��+�_�?8[jim@nuc
~]$

**Comment by jimerickson** [comment]
sorry nc -v -l -p XXXXX returns the following

[jim@nuc ~]$ nc -v -l -p XXXXX
Ncat: Version 6.47 ( http://nmap.org/ncat )
Ncat: Listening on :::XXXXX
Ncat: Listening on 0.0.0.0:XXXXX
Ncat: Connection from 46.147.225.229.
Ncat: Connection from 46.147.225.229:52749.

^+��zUg�/ߘ*�D6�GI={�
                    I̋CmF�Öi?�w  >����H��0nnTl
���>Φ�%kW"�\m�1t��G[z�m��K�H�.\�����g[>Ѽ���J�/��▒├��29┬7�;⎼�£IV↑┐���]PQ)����2H
                                                                               �&[°b�bR��ó�һ�⎼���^`1@���H�&"���*�b"���  4I2mגg>�s       ���G[jim@nuc ~]$

**Comment by orignal** [comment]
are you sure you don't start i2pd twice?

**Comment by jimerickson** [comment]
positive even when performed after a fresh reboot it produces this result.
is there anything else i can try or any files you need to see?

**Comment by orignal** [comment]
Look into ~/.i2pd/router.info if there are two NTCP records.

**Comment by jimerickson** [comment]
yes there are. can i edit one out? or shall i delete router.info?

**Comment by orignal** [comment]
You can't edit it because it contains signature.
Either delete it, or if you want to change it you should write the code to RouterContext.cpp.
I remember I saw that issue a while ago and definitely fixed it in trunk

**Comment by jimerickson** [comment]
ok i got it running. thanks for your help. i deleted both router.info and
router.keys was that the proper way to handle it?

**Comment by orignal** [comment]
Yes, that's the best way. 
Multipple NTCP v4 records is just a bug.

**Comment by jimerickson** [comment]
thank you so much for helping me get i2pd running again. you may close the
issue if you wish.

**Comment by mlt** [comment]
Is there a separate issue? If I delete router.info, it dies on start (after issuing an info log that it failed to open that file) at memcpy in RouterInfo::Update as len was passed as negative. It should be resilient to file deletion.

**Comment by orignal** [comment]
that's separate issue due bad initial design,RouterInfo load it in the  constructor.
There is "TODO" statement in line 269 of RouterContext.cpp, I just didn't have to time to implement it properly.
