### ISSUE TITLE
[BUG] Yggdrasil crashing i2pd

### ISSUE THREAD

**Issue by LucasSnatiago** [PurpleI2P/i2pd#2046]
When I was trying to configure yggdrasil I received this error:

```
Starting i2pd.service - I2P Router written in C++...
terminate called after throwing an instance of 'boost::wrapexcept<boost::system::system_error>'
   what():  Invalid argument
```

How can I configure Yggdrasil. Both i2pd and Yggdrasil are working, but when I try to configure it gives me the above error.

```
[meshnets]
## Enable connectivity over the Yggdrasil network  (default: false)
yggdrasil = true
## You can bind address from your Yggdrasil subnet 300::/64
## The address must first be added to the network interface
yggaddress = 300:d17b:38e9:b586::/64
```

**Comment by Vort** [comment]
> yggaddress = 300:d17b:38e9:b586::/64

You need to specify exact address, not subnet.

**Comment by LucasSnatiago** [comment]
Is it possible to add this explanation to the config file? 
I don't think it's well explained in the config file. 

There is saying: "You can bind address from your Yggdrasil subnet 300::/64", and not "Specify your yggdrasil IP here" or something like this.

**Comment by LucasSnatiago** [comment]
I closed by accident, but it's working now. Thanks @Vort!
