### ISSUE TITLE
Analyse with coverity

### ISSUE THREAD

**Issue by gxcreator** [PurpleI2P/i2pd#205]
Hi, I've analysed this project with Coverity static analyser(that is free for open source) and found some bugs. But since I am not a creator of original project, bug details are not available for me. Could you please try to run coverity by yourself(https://scan.coverity.com)?
![screenshot_15](https://cloud.githubusercontent.com/assets/5941877/8147804/4d4401f2-1286-11e5-9bfb-1305976b7075.png)

**Comment by gxcreator** [comment]
Hi again,
Any progress on this?

**Comment by orignal** [comment]
I will do when I have time

**Comment by gxcreator** [comment]
Thanks

**Comment by gxcreator** [comment]
Hi again,
Could anyone perform this check?

**Comment by gxcreator** [comment]
Any progres here?

**Comment by orignal** [comment]
Недавно собирались этим заняться.
