### ISSUE TITLE
i2pd browser is dead

### ISSUE THREAD

**Issue by fu3x11** [PurpleI2P/i2pd#2054]
is anyone gonna merge pull requests on that? like the extensions and browser versions are outdated, or is that project abandoned

**Comment by r4sas** [comment]
No one have time for this.
Use trunk, not releases. Trunk repository contains latest FF, NoScript and other things.

**Comment by fu3x11** [comment]
> No one have time for this. Use trunk, not releases. Trunk repository contains latest FF, NoScript and other things.

can i have a link to it please?

**Comment by r4sas** [comment]
Just use master branch of repository: https://github.com/PurpleI2P/i2pdbrowser

**Comment by Vort** [comment]
@fu3x11, r4sas means that browser can be built with scripts like
https://github.com/PurpleI2P/i2pdbrowser/blob/master/windows/build/build.cmd
