### ISSUE TITLE
Any explanation on different performance for 2 LAN nodes running i2pd?

### ISSUE THREAD

**Issue by mlt** [PurpleI2P/i2pd#206]
I noticed that different nodes on my LAN have drastically different performance and I'm puzzled what could be the reason. One instance of i2pd is running on DD-WRT router and as of now its web interface says `Routers: 4605 Floodfills: 609 LeaseSets: 0` whereas for one started way long ago on Windows from under MSVC, I see only `Routers: 2796 Floodfills: 184 LeaseSets: 0`. Both have okay status, and all transports working (SSU and NTCP for IPv4 and IPv6).
The only issue is that i2pd somehow dies on DD-WRT and not due to OOM. Unfortunately libSegFault is not there :cry: 
I wonder if debug build for Windows has some timing/performance penalties that affect it that much. It is just strange to see 1/3 of floodfills. It is very consistent behavior.

**Comment by orignal** [comment]
Windows release never work as good as Linux, and basically  there is no maintainer for it.
I'm Linux developer only and not good in it. If you wish please investigate what's wrong. I suspect there is a race condition causes by semaphores instead conditional variables.

**Comment by mlt** [comment]
It seems that 490b65dfe233fe298df05b75294abeb1f7bc00a3 fixed this issue.
