### ISSUE TITLE
PGP signatures for verifity?

### ISSUE THREAD

**Issue by SilmorSenedlen** [PurpleI2P/i2pd#2061]
Good day, @r4sas
Once again, signatures for verifying the integrity and authenticity of binaries in releases appearing very late : /
Are there any problems with their creation?..

**Comment by r4sas** [comment]
Hello. Sorry about the delay. When we released version 2.51ю0 there was an issue with the Mageia repositories so I couldn't build packages for it. Now I have a bit of time, so I was able to build these packages and post the hashes.

**Comment by SilmorSenedlen** [comment]
Thx a lot!
