### ISSUE TITLE
Specify data directory

### ISSUE THREAD

**Issue by lcharles123** [PurpleI2P/i2pd#2063]
The default data directory as show on web console are "Data path: /root/.i2pd", even if I specify others directories, because in my setup this directory is read-only:

Command used to start the application:
/home/alice/hdd/i2pd/usr/sbin/i2pd --conf=/home/alice/hdd/i2pd/etc/i2pd/i2pd.conf --daemon

cat /home/alice/hdd/i2pd/etc/i2pd/i2pd.conf
tunconf = /home/alice/hdd/i2pd/etc/i2pd/tunnels.conf
tunnelsdir = /home/alice/hdd/i2pd/etc/i2pd/tunnels.conf.d
certsdir = /home/alice/hdd/i2pd/var/lib/i2pd/certificates

I created a link /root/.i2pd targeting /home/alice/hdd/i2pd/.i2pd, but will be better if there is an option to specify this directory.

**Comment by Vort** [comment]
> Command used to start the application:
> /home/alice/hdd/i2pd/usr/sbin/i2pd --conf=/home/alice/hdd/i2pd/etc/i2pd/i2pd.conf --daemon

Try `/home/alice/hdd/i2pd/usr/sbin/i2pd --datadir=/home/alice/hdd/i2pd/etc/i2pd --daemon` instead.

**Comment by orignal** [comment]
You can specify directory from command line param only. You can also place i2pd.conf in the the folder with i2pd.exe on Windows and it will become portable.
