### ISSUE TITLE
miniupnp-2.2.8: call of UPNP_GetValidIGD changed

### ISSUE THREAD

**Issue by khumarahn** [PurpleI2P/i2pd#2071]
Hi!

In the recent version of miniupnp, `UPNP_GetValidIGD` requires two more arguments: `char * wanaddr, int wanaddrlen`.

The change happened here: https://github.com/miniupnp/miniupnp/commit/c0a50ce33e3b99ce8a96fd43049bb5b53ffac62f

Bug found here: https://bugs.gentoo.org/934058 (i2pd does not compile against miniupnp-2.2.8)

**Comment by r4sas** [comment]
Can you provide patch with if/else for preprocessor?

**Comment by steils** [comment]
https://github.com/PurpleI2P/i2pd/pull/2072
