### ISSUE TITLE
question reg http proxy

### ISSUE THREAD

**Issue by AlekseiKhatkevich** [PurpleI2P/i2pd#2074]
This is rather question than issue, anyway

How to switch on http proxy?

```
HTTP Proxy | **Disabled**
-- | --
SOCKS Proxy | Enabled
BOB | Disabled
SAM | Enabled
I2CP | Disabled
I2PControl | Disabled

```
```
[httpproxy]
## Enable the HTTP proxy (default: true)
enabled = true
## Address and port service will listen on (default: 127.0.0.1:4444)
address = localhost
port = 4444
## Optional keys file for proxy local destination (default: http-proxy-keys.dat)
# keys = http-proxy-keys.dat
## Enable address helper for adding .i2p domains with "jump URLs" (default: true)
## You should disable this feature if your i2pd HTTP Proxy is public,
## because anyone could spoof the short domain via addresshelper and forward other users to phishing links
# addresshelper = true
## Address of a proxy server inside I2P, which is used to visit regular Internet
outproxy = purokishi.i2p
## httpproxy section also accepts I2CP parameters, like "inbound.length" etc.
```
I have as well i2p classic java based version installed and with this http proxy and outproxy works well, but not with i2pd
What should i do to switch on http proxy and outproxy?

**Comment by r4sas** [comment]
Maybe because you trying to run both Java I2P and I2Pd http proxy on same port at one time?

**Comment by AlekseiKhatkevich** [comment]
> Maybe because you trying to run both Java I2P and I2Pd http proxy on same port at one time?

Well, i2p is swithed off while i2pd is working.
Nobody uses port 4444
`sudo ss -tunlp | grep 4444 - > None`
But 4447 in use by i2pd 
```
sudo ss -tunlp | grep 4447
tcp   LISTEN 0      4096                              127.0.0.1:4447       0.0.0.0:*    users:(("i2pd",pid=5557,fd=35))                     
```

**Comment by r4sas** [comment]
Please share your i2pd.conf and check if data path on webconsole is correct.

**Comment by AlekseiKhatkevich** [comment]
Data path: -- /var/lib/i2pd
conf path -- /var/lib/i2pd/i2pd.conf
file attached. Had to zip it to pass a file type validation.

[i2pd.conf.zip](https://github.com/user-attachments/files/15937489/i2pd.conf.zip)

**Comment by r4sas** [comment]
You included symbolic link, not config itself.

**Comment by r4sas** [comment]
t/o
