### ISSUE TITLE
CPU 100% After Runtime Error

### ISSUE THREAD

**Issue by unarj** [PurpleI2P/i2pd#2078]
running docker latest-release (2.53.0)

happened a few times randomly, started monitoring.  this happened very soon after closing my i2p bittorrent client (BiglyBT), possibly a coincidence.  after this error the container locks, uses 100% CPU until killed / restarted.

Runtime exception: cannot create std::vector larger than max_size()

**Comment by Vort** [comment]
Regression is from commits d843502832e9eaf9ca969b573ef22b1221a6ecd0 and df787060c31139022a42c815408a21df7c42b37d.
