### ISSUE TITLE
Client HTTP Headers

### ISSUE THREAD

**Issue by OvercookedBeef** [PurpleI2P/i2pd#2079]
The Java I2P router sends the following headers to the server for HTTP tunnels:
`x-i2p-destb32`: The user's B32 address (ending in .b32.i2p)
`x-i2p-destb64`: The user's B64
`x-i2p-desthash`: The user's hash

Could these headers also be added to i2pd for HTTP tunnels? I'm currently having to run the Java router for certain services which I'd prefer not to do. Thanks.

**Comment by orignal** [comment]
i2pd's http tunnels also sends these headers

**Comment by OvercookedBeef** [comment]
Hmm you're right, I got it working on my server now. I'm not sure why I thought it didn't, either this is something relatively new, or more likely I'm stupid. Thanks.
