### ISSUE TITLE
ClientDestination requesting zMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMw= looks weird in logs

### ISSUE THREAD

**Issue by mlt** [PurpleI2P/i2pd#208]
Quite often I see in logs something like the following:
```
2015-Jun-18 12:47:41.949067,Thread=0x00002118,info,main,1 cloves
2015-Jun-18 12:47:41.950066,Thread=0x00002118,info,main,Garlic type local
2015-Jun-18 12:47:41.950066,Thread=0x00002118,info,ClientDestination,DatabaseSearchReply for zMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMw= num=3
2015-Jun-18 12:47:41.961067,Thread=0x00002118,info,ClientDestination,Requesting zMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMw= at TNKorDgtWuWv5rXKeaCmUZSQ5J2E6O3JhA5JCweTsUY=
2015-Jun-18 12:47:41.974068,Thread=0x00002118,info,ClientDestination,Requesting zMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMw= at TMgXGKCyUzHUuEQ-lLznyfVRIPp6i16nCDWgH9FGeh8=
2015-Jun-18 12:47:41.986068,Thread=0x00002118,info,main,No garlic tags available. Use ElGamal
2015-Jun-18 12:47:41.989069,Thread=0x00002118,info,ClientDestination,Requesting zMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMw= at TLT0mM3B~ZE7-kX7liotDGQw~2CHiJGMIMXQpH9scjM=
2015-Jun-18 12:47:42.006070,Thread=0x00002118,info,main,Garlic message 849990432 acknowledged
2015-Jun-18 12:47:42.007069,Thread=0x00002118,info,main,Garlic message 2109355744 acknowledged
```
This is not coming from SAM. It just does not look right. I think something was not initialized and was b32 encoded.
According to online b32->hex, it is `CB32CCB32CCB32CCB32CCB32CCB32CCB32CCB32CCB32CCB32CCB`. It doesn't look like one of the MSVC debug patterns.

**Comment by mlt** [comment]
Huh.. of course it is base 64 and hex is `CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC` which is uninitialized memory marker for MSVC.

**Comment by orignal** [comment]
Do you know the scenario? What this ClientDestination is refering to, e.g. SAM session, tunnel, etc.?

**Comment by mlt** [comment]
How can I check that? I do test SAM, but it doesn't show up in naming replies.
I can tell that I see 0xCC pattern starting from [GarlicDestination::HandleGarlicMessage](https://github.com/PurpleI2P/i2pd/blob/master/Garlic.cpp#L403). Although I didn't pull your recent commits. So... I'd better check if it is reproducible with those.

**Comment by orignal** [comment]
How many local destinations do you have? SAM only?

**Comment by mlt** [comment]
I have only 1 SAM app. WebConsole shows 1 SAM session but Local Destinations shows 1 more. hmm... are you saying I'm passing junk over SAM? :eyes:

**Comment by orignal** [comment]
Second one is shared local destination, but if you don't produce any activity through it (like browsing) it wouldn't not request any destination. But it's definitely a reply to your request, so we need to find out where this garbage in address comes from. I would start from "STREAM CONNECT" message.

**Comment by mlt** [comment]
I do not see zMzM in the context of `STREAM CONNECT` messages. All `STREAM CONNECT` look legit to me. Now I'm wondering if it was the remnant of pointers' use fixed by your recent commits.

**Comment by mlt** [comment]
I got it again with *master*. Payload buffer in GarlicDestination::HandleGarlicMessage has a bunch of 0xCC starting at offset 89.

**Comment by orignal** [comment]
Sure there is an uninitialized memory if it's beyond of payload. What was the value of msg->len at line 546?
I believe this code is correct, we produce such garbage in a request message and get response back.

**Comment by mlt** [comment]
len=316 online 546. On the other hand, up the stack at `InboundTunnel::HandleTunnelDataMsg(i2p::I2NPMessage * msg) Line 166` the content of `(((*((i2p::tunnel::Tunnel*)(this))).m_Config)._Ptr)->m_FirstHop` looks bizarre.

**Comment by mlt** [comment]
It is quite odd but it might be related. I see oddly named file created once in a while that looks like netDb file. However it is created in current directory.

**Comment by orignal** [comment]
It's strange because it passed verification at line 464, that means such malformed message comes from the network.

**Comment by mlt** [comment]
What file are you talking about for line 464? I suspect there is a stale pointer somewhere. Shall we use share pointer for `void InboundTunnel::HandleTunnelDataMsg (I2NPMessage * msg)` just in case?

**Comment by orignal** [comment]
Garlic.cpp
Yes, I'm in the middle of migration to shared_ptr for I2NPMessage

**Comment by mlt** [comment]
FYI I'm getting weird file names way more often then I thought. For example, `RouterInfo::SaveToFile` tried to open file with fullPath equal to `DykTqhrRyOUSM6disP6lQv7ZdKRmIHAh7hrR~FKPHaE=\\rD\\routerInfo-DykTqhrRyOUSM6disP6lQv7ZdKRmIHAh7hrR~FKPHaE=.dat`. This is odd. *p* in NetDb::SaveUpdated has correct path, however *fullDirectory* is already a garbage. *m_RouterInfos* has garbage in some *m_FullPath*.

**Comment by orignal** [comment]
I will take a look, especially since windows part was not written by me. boost::filesystem should be used a better way there

**Comment by mlt** [comment]
It is not about win32... the code is mostly the same. `fullDirectory = p.string().c_str ();` looks suspicious. `string()` return temporary object, e.g. http://stackoverflow.com/a/25788693/673826 .

**Comment by orignal** [comment]
Yes, it looks weird. Seems copy&paste from somewhere. Look at lines 55-56 of AddressBook.cpp, should work without that #ifdef

**Comment by mlt** [comment]
I suggest to use boost ofstream it can take path as an input. I'll prepare a patch.

**Comment by orignal** [comment]
please don't use boost's ofstream if there is one in std.

**Comment by mlt** [comment]
Why not? It doesn't create much overhead but makes code cleaner by using path instead of string. Otherwise we'd have to deal with string conversion and separators (though win32 generally accepts `/` in place of `\\`).
I saw that thread #3 on boost, but I think benefits of using it exceed shortcomings. Also it's logging library can completely close #174 without code rewrite and with added benefits like multiple sinks.

**Comment by orignal** [comment]
I thought boost::filesystem takes care about separator using '/' operation and you should use it.
My point is if you have something in std use it from std rather than from boost.

**Comment by mlt** [comment]
Back to topic... something is fishy going on around [HandleDecryptedTunnelDataMsg](https://github.com/PurpleI2P/i2pd/blob/master/TunnelEndpoint.cpp#L98). Just before it enters HandleNextMessage, msg looks okay,but m does not.

**Comment by orignal** [comment]
It's shared_ptr now

**Comment by mlt** [comment]
> it passed verification at line 464

I do confirm that. I tried to move EIP back and it does pass it fine. Why would someone send a buffer full of 0xCC? Any chance another windows debug build of i2pd router is sending it?

**Comment by orignal** [comment]
zzz suspects the same, that some old and bad build of i2pd is sending it.
But I didn't find anything wrong in the current code.

**Comment by mlt** [comment]
hmm... I just saw
```
0x09AA4B50  cd cd 02 80 58 1d 2d 00 00 01 4e 22 63 9d 5d 00 a8 de cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc  ÍÍ.€X.-...N"c.].¨ÞÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌ
0x09AA4B7C  cc cc cc cc cc cc 55 f7 78 24 aa 14 c1 9a d1 39 20 16 26 58 04 3e 99 8c 98 b4 1e af 6e 81 fb 6c a2 51 34 0c fa 71 07 7a aa 06 33 00  ÌÌÌÌÌÌU÷x$ª.ÁšÑ9 .&X.>™Œ˜´.¯n.ûl¢Q4.úq.zª.3.
```
as *(m)->buf* at the end of CreateLeaseSetDatabaseLookupMsg. *len* is 186. Is it something to worry about?

**Comment by orignal** [comment]
We need to find out where this address comes from? It seems SAM message is not handled properly.

**Comment by orignal** [comment]
Line 346 of SAM.cpp, we have to add check there if it was successive.

**Comment by mlt** [comment]
You are close:-) It turned out that for what whatever reason it passes b32 as destination. Thus *FromBase64* on line 357 fails to initialize *dest* from *destination*. It should return error code (or try to resolve?) if destination is not valid.

**Comment by orignal** [comment]
B32 address must be passed in .b32.i2p form. It lookups for full address through addressbook in this case. Otherwise full base64 address must be passed.
If it's not valid it should send STREAM STATUS RESULT=I2P_ERROR back.

**Comment by mlt** [comment]
I don't see an attempt to resolve b32.i2p in [SAMSocket::ProcessStreamConnect](https://github.com/PurpleI2P/i2pd/blob/master/SAM.cpp#L346)
```
2015-Jun-23 23:58:49.982268,Thread=0x000039f4,debug,SAMSocket,stream connect: ID=e3b6505fbecb44651c5ab6b5341f8431c93a5058 DESTINATION=3uesgffrem5pwfx6qi2yqs7vg73lppoevmm5vrwzl4jau66ch32q.b32.i2p
2015-Jun-23 23:58:50.004267,Thread=0x000048b4,info,main,Garlic
2015-Jun-23 23:58:50.004267,Thread=0x000039f4,error,main,Identity buffer length 45 is too small
2015-Jun-23 23:58:50.005267,Thread=0x00004930,info,main,1 cloves
2015-Jun-23 23:58:50.005267,Thread=0x00004930,info,main,Garlic type destination
2015-Jun-23 23:58:50.006268,Thread=0x00004930,debug,main,Received seqn=506
2015-Jun-23 23:58:50.006268,Thread=0x00004930,warn,main,Duplicate message 506 received
2015-Jun-23 23:58:50.008268,Thread=0x00004930,info,main,Quick Ack sent. 0 NACKs
2015-Jun-23 23:58:50.010269,Thread=0x00004930,info,main,Quick Ack sent. 0 NACKs
```
I'll see why an app failed to resolve it on its own.

**Comment by mlt** [comment]
And I'm somewhat confused about that function. *dest* always comes together with *GetIdentHash()*. Don't we need a complete destination in STREAM CONNECT?

**Comment by orignal** [comment]
It's done in naming lookup. If you have a b32 address you have to query it through "NAMING LOOKUP" first. STREAM CONNECT should take full address only.

**Comment by mlt** [comment]
We should add *SAM_STREAM_STATUS_INVALID_KEY* constant. I'll submit a patch.

**Comment by orignal** [comment]
let's merge it

**Comment by mlt** [comment]
What shall happen when *name* in *NAMING LOOKUP* has *<base64>.i2p*? Right now it fails with unknown destination. However how one could tell if *something* in *<something>.i2p* is a valid base64 destination or not?

**Comment by orignal** [comment]
I believe it must request a LeaseSet to see if particular address is online

**Comment by mlt** [comment]
Isn't it too much logic required from an app? So it has to attempt *STREAM CONNECT*, then
perform *NAMING LOOKUP* if connection failed with *SAM_SESSION_STATUS_INVALID_KEY*? I'd rather allow automatic naming resolution in *STREAM CONNECT* or bounce back base64 if requested via *NAMING LOOKUP*. But I guess such decisions shall be communicated upstream to (Get)I2P.

**Comment by orignal** [comment]
You have to discuss protocol with zzz and other guys. 
I just have to make sure it's compatible with other applications using SAM.
Usually applications try to resolve a destination through NAMING LOOKUP  and then STREAM CONNECT if successive.

**Comment by mlt** [comment]
I see your point. However if this case *NAMING LOOKUP* will return error,so there would be no reason to attempt *STREAM CONNECT*.
On the other hand one may assume if an address is (at least with optional .i2p) 516 bytes long, it got to be base64 encoding. I mean no one sane would make up name that long to be used around.

**Comment by mlt** [comment]
Is it mandatory to use lowercase alphabet for b32 names? I see that padding is optional. Specs aren't clear on that.

**Comment by orignal** [comment]
b32 is just base32 encoding or identity hash. Nothing about I2P.
Yes, it's mandatory.

**Comment by mlt** [comment]
I just wanted to double check on alphabet as I'm patching [rasterbar](https://github.com/arvidn/libtorrent/blob/master/src/escape_string.cpp#L324).

**Comment by orignal** [comment]
I meant in my implementation and probably in I2P, because I've never seen .b32 address in uppercase
