### ISSUE TITLE
Crash on Trisquel Aramo

### ISSUE THREAD

**Issue by leuchtturmsss** [PurpleI2P/i2pd#2083]
Hello everyone,
I hope this finds you in the best of health. I am having some issues running i2pd on Trisquel Aramo.

Here are the errors i am currently receiving:

```
usr@computer:~$ i2pd
22:33:39@648/none - i2pd v2.39.0 starting
22:33:39@648/warn - Family: Can't load family certificates from /home/usr/.i2pd/certificates/family
22:33:39@648/warn - Reseed: Can't load reseed certificates from /home/usr/.i2pd/certificates/reseed
22:33:39@648/error - RouterInfo: Can't open file 
22:33:39@648/warn - NetIface: interface with yggdrasil network address not found
Segmentation fault
usr@computer:~$
```

Thank you so much for all of your time and energy in creating such a wonderful program. I had just installed the software unto my machine. I immensely appreciate any support you can provide.

__________________

Laptop: x230 ThinkPad
OS: Trisquel (aramo)
Version: [From Repository](https://archive.is/JHBul)

**Comment by r4sas** [comment]
Too old version. The only way for you is building yourself.

**Comment by r4sas** [comment]
>Aramo is a long term support (LTS) version in development. It is based on Ubuntu 22.04 (Jammy Jellyfish).

https://launchpad.net/~purplei2p/+archive/ubuntu/i2pd

**Comment by leuchtturmsss** [comment]
> > Aramo is a long term support (LTS) version in development. It is based on Ubuntu 22.04 (Jammy Jellyfish).
> 
> https://launchpad.net/~purplei2p/+archive/ubuntu/i2pd

Thank you so much you are an immense treasure.

This works perfectly.
