### ISSUE TITLE
How can I make I2P use a SOCKS5 proxy for initializing network connections?

### ISSUE THREAD

**Issue by cevin** [PurpleI2P/i2pd#2086]

**Comment by Vort** [comment]
You can try this option:
https://github.com/PurpleI2P/i2pd/blob/0c924836cf9ae04cd12e2647e6edd5c0f896ff7b/contrib/i2pd.conf#L235-L237

Another option is to use [Yggdrasil](https://github.com/yggdrasil-network/yggdrasil-go).
