### ISSUE TITLE
[Bug] The directory ownership in the binary installation package is incorrect.

### ISSUE THREAD

**Issue by cevin** [PurpleI2P/i2pd#2087]
The default direcotry `/var/lib/i2pd/certificates` is owned by `root`.

**Comment by Vort** [comment]
What exact package for what exact OS are you talking about?

**Comment by cevin** [comment]
> What exact package for what exact OS are you talking about?

@Vort  [i2pd-2.53.1-1.el9.aarch64.rpm](https://github.com/PurpleI2P/i2pd/releases/download/2.53.1/i2pd-2.53.1-1.el9.aarch64.rpm)

**Comment by Vort** [comment]
@R4SAS, can you look what happened wrong here?

**Comment by cevin** [comment]
![image](https://github.com/user-attachments/assets/92ef2077-7764-44d1-b4d9-39812acb1def)
