### ISSUE TITLE
did 2.53.1 get re-tagged?

### ISSUE THREAD

**Issue by chenrui333** [PurpleI2P/i2pd#2093]
👋 seeing some checksum changed while regression build the 2.53.1 release, raise this issue to confirm if there was some re-tagging? Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/181601

**Comment by Vort** [comment]
2.53.1 tag was moved from fe740249a508b9daa4956ed327a26584938f3769 to 81cc3e3de8526b7f2ccc91053c9d1718d3293136 to include fix for LibreSSL compilation.
However, recent versions of LibreSSL have bug, so 2.53.1 is not fully functioning with LibreSSL anyway.
Workaround for LibreSSL was added in 0c924836cf9ae04cd12e2647e6edd5c0f896ff7b.

**Comment by chenrui333** [comment]
thanks @Vort @orignal! closing the issue now. (sorry about the delay)
