### ISSUE TITLE
Unsanitized input from a file flows into an addition operator (+), where it is used in integer arithmetic. This may result in an integer overflow vulnerability.

### ISSUE THREAD

**Issue by s-b-repo** [PurpleI2P/i2pd#2115]
std::string header;
					size_t contentLength = 0;
					while (!ss.eof () && header != "\r")
					{
						std::getline(ss, header);
						auto colon = header.find (':');
						if (colon != std::string::npos && header.substr (0, colon) == "Content-Length")
							contentLength = std::stoi (header.substr (colon + 1));
					}
					if (ss.eof ())
					{
						LogPrint (eLogError, "I2PControl: Malformed request, HTTP header expected");
						return; // TODO:
					}
					std::streamoff rem = contentLength + ss.tellg () - bytes_transferred; // more bytes to read

**Comment by orignal** [comment]
Please, stop posting ChatGPT's output here.

**Comment by s-b-repo** [comment]
its not chatgpt

**Comment by s-b-repo** [comment]
im using automated code analysis software

**Comment by orignal** [comment]
There is no "input from a file" in this code.
