### ISSUE TITLE
[Sorry, this isn't really an issue] Could somebody make a beginner friendly video about this project (flatpak pkg)? 

### ISSUE THREAD

**Issue by Twig6943** [PurpleI2P/i2pd#2122]
I tried setting it up (the flatpak pkg) got the web UI working and got around %70 success rate but couldnt connect to .i2p domains cuz I couldn't figure out how to set up the firefox profile :sob: (Ik skill issue)

**Comment by Vort** [comment]
> To browse anonymous websites inside Invisible Internet, configure your web browser to use HTTP proxy 127.0.0.1:4444 (available by default in i2pd).

> In Firefox: Preferences -> Advanced -> Network tab -> Connection Settings -> choose Manual proxy configuration, Enter HTTP proxy 127.0.0.1, Port 4444

https://i2pd.readthedocs.io/en/latest/tutorials/http/#browse-anonymous-websites

**Comment by Twig6943** [comment]
> > To browse anonymous websites inside Invisible Internet, configure your web browser to use HTTP proxy 127.0.0.1:4444 (available by default in i2pd).
> 
> > In Firefox: Preferences -> Advanced -> Network tab -> Connection Settings -> choose Manual proxy configuration, Enter HTTP proxy 127.0.0.1, Port 4444
> 
> https://i2pd.readthedocs.io/en/latest/tutorials/http/#browse-anonymous-websites


https://github.com/user-attachments/assets/2ba9b1d4-38a5-42ab-ae2f-aff94dfc73f5

**Comment by Vort** [comment]
You were asking about Firefox and now showing Chromium...
Anyway, try `http://git.i2p` instead of `git.i2p`.

**Comment by Twig6943** [comment]
Couldn't get it to work with firefox/librewolf thats why I tried with ungoogled chromium but yea turns out all I had to do was put http:// in front and it works like a charm  (gotta say that the flatpak package made everything a lot more easier)
![image](https://github.com/user-attachments/assets/df753d24-1ae6-4ea2-a899-0ba6f533923b)

**Comment by Twig6943** [comment]
do you know why librewolf/chromium doesn't auto do this? (the http:// stuff)

**Comment by Vort** [comment]
I suspect they do not know about `.i2p` domains and therefore direct such queries to search engine.
It is possible to "teach" browsers about these domains, but I don't remember how exactly. Someting should be changed in settings.

**Comment by Twig6943** [comment]
Sooo its an issue with all major browsers?

**Comment by Twig6943** [comment]
Also @Vort  is it safe to connect to sites if I get this error when I connect to http://127.0.0.1:4444 
![image](https://github.com/user-attachments/assets/35d03b41-a758-4941-8cd4-8121c43d3ad9)

(I have outproxy enabled tho https://github.com/PurpleI2P/i2pd/issues/1505#issuecomment-2474755645)

**Comment by Vort** [comment]
I don't know how to use i2pd_qt and I did not tried to use outproxies yet.
However, trying to connect to proxy via proxy is not a good test.
It is better to choose random clearnet website instead.
