### ISSUE TITLE
libI2pd documentation 

### ISSUE THREAD

**Issue by korolaab** [PurpleI2P/i2pd#2127]
Hi,
Where libI2pd documentation can be founded?
  irc #dev says that channel is protected.

**Comment by Vort** [comment]
I doubt #dev channel will help you in this case.
libi2pd is not well documented for many reasons.
Are you sure you need it?
Making connection to separate i2pd binary with SAM protocol may be enough for most of the cases.

**Comment by korolaab** [comment]
> I doubt #dev channel will help you in this case. libi2pd is not well documented for many reasons. Are you sure you need it? Making connection to separate i2pd binary with SAM protocol may be enough for most of the cases.

I don't know exactly what i need. My app uses proxy and server tunnel of i2pd standalone android app. That solution is suitable, but it's not user-friendly. 
I2pd app also not user friendly for non-tehnical user. I have to ask them "please run i2pd".
Also there are some problems with killing router by android.
I am thinking of implementing i2pd router into my app. I will have ability to run router from my app without any asking user to do that manually. 

Maybe there is a better solution? Can we discuss that in private chat? I can show you my app

**Comment by orignal** [comment]
There is no libi2pd documentation and no plans to write it.
