### ISSUE TITLE
IP of Client did not change in log

### ISSUE THREAD

**Issue by Playit3110** [PurpleI2P/i2pd#2141]
Hello everyone,
I host an eepsite with apache and in my logs I could track IPs in the 127.0.0.1/8 subnet. Now I only see my IP of my network (172.16.0.1/12). What can I do to see the 127.0.0.1/8 addresses again.

I tried already to find the point of error:

1. I tried Apache rewrite an proxy mods, with `LogLevel rewrite:trace7 proxy:trace7` if they change the IP, but there was no result.
2. I tried to see if `iptables` or `ip rules` or `routes` would change the IP. I used `tcpdump` to watch for requests and found that the wrong IP is already comming from I2Pd.

I looked into the source and found the function which should rewrite the IP based on the first 3 bytes of the b32 or b64 address.
[I2PTunnel.cpp#L86](https://github.com/PurpleI2P/i2pd/blob/openssl/libi2pd_client/I2PTunnel.cpp#L86)

Maybe someone can explain why I get the wrong IP?

**Comment by mittwerk** [comment]
> Not 2pd problem.

😎

**Comment by Playit3110** [comment]
Why?

**Comment by orignal** [comment]
Because there is something with your local routing. i2pd uses system TCP/IP sockets and doesn't have control over it.
