### ISSUE TITLE
Implement support for introducers (was 0.0.0.0 has been banned for 70 seconds)

### ISSUE THREAD

**Issue by mlt** [PurpleI2P/i2pd#216]
This looks suspicious in logs. For some reason m_ConnectedFrom is set to 0.0.0.0 in NTCPSession::Receive when invoked from NTCPSession::HandlePhase4Received.

**Comment by mlt** [comment]
I suspect it is related to the fact that SSUServer::Send once in a while has *to* set to 0.0.0.0 . This in turn causes `boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >`.

**Comment by orignal** [comment]
More interesting question is why it's banned. It means we get follow-up connection. Need to find out in which case remote_endpoint of boost::asio::socket is set to zero.
Like 132 of NTCPSession.cpp. It's called from acceptor meaning we must know remote endpoint by that time, otherwise we wouldn't know where we must send SYN to.

**Comment by mlt** [comment]
Is RouterInfo pointers returned by GetAddress at fault? Stale?

**Comment by orignal** [comment]
Line 285 of Transports.cpp. If address is not set, it tries to resolve from hostname if possible.

**Comment by mlt** [comment]
I'll take a look at it. I'm in the middle of SSU debug.. at SSUServer::GetSession. *router* has 3 entries and the first one has 0.0.0.0 as well as port.

**Comment by orignal** [comment]
do you know an I2P address of RouterInfo this session refers to? Look into corresponding routerInfo- file in netDb folder. 3 entries usually means introducers. Also SSU implementation contans much more bugs that NTCP

**Comment by mlt** [comment]
The filename is routerInfo-ItrV1FE~XddjGEbhMN8XbzMog18g6tr-WWklzrT4PvA=.dat . The first letter is lowercase H->I<-J . I don't think it is an introducer. It has IPv6 SSU & NTCP however the very first entry is IPv4 that is full of zeroes. In the file I see 3 IP addresses though as host0, host1, and host2.

**Comment by orignal** [comment]
ihost means introducer. I don't have it implemented if address is not specified, should be done.
m_Buffer is NULL means it has been deleted to reduce memory usage. It will be reloaded from file if a lookup messages come, but it's for floodfill only.
