### ISSUE TITLE
Implement support for IPv6 peer test as Charlie

### ISSUE THREAD

**Issue by mlt** [PurpleI2P/i2pd#217]
Once in a while a bad_cast exception is raised when [address is casted to v4](https://github.com/PurpleI2P/i2pd/blob/master/SSUSession.cpp#L947).

**Comment by orignal** [comment]
Good point. Do you want to do it?

**Comment by mlt** [comment]
Could you review it? I'm not certain about line 947. Can we have size != 4 in the beginning?

**Comment by mlt** [comment]
also there was no need to alter buffer size on line 972 :-)

**Comment by orignal** [comment]
Not sure about this line "std::copy(reinterpret_cast<const uint8_t*>(endpoint.data()), reinterpret_cast<const uint8_t*>(endpoint.data()) + ip_len, payload);". Can we rely on it meaning endpoint data layout will remain the same.
Remember ipv6 is allowed between Bob and Charlie only.

**Comment by orignal** [comment]
Per discussion with zzz, it never happens in current implementation.
