### ISSUE TITLE
Small heap memory leak

### ISSUE THREAD

**Issue by mlt** [PurpleI2P/i2pd#221]
I've noticed that memory consumption grows over time. When I just start i2pd, it uses 15-20 MB. However next day it goes up to ~100MB. I'm not sure if I pinpointed that correctly, but I feel like memory allocated in NewI2NPShortMessage is never released to the heap. With most messages being short lived, I think something is not quite right here.
![Here is a fancy screenshot of Windows Performance Analyzer](http://snag.gy/gVsCo.jpg)
60kb in one minute roughly matches 84 MB/day.
P.S. AIFO means allocated inside,free somewhere outside.

**hold on with this... there is a memory leak, I'm just not certain where**

**Comment by orignal** [comment]
That's known issue. Long live I2NP messages are located in SSUData and TunnelEndpoint when wait for other fragments of a message.
