### ISSUE TITLE
Не может найти LeaseSets

### ISSUE THREAD

**Issue by DEMIAN-8** [PurpleI2P/i2pd#223]
Собственно собрал сегодняшнюю ветку с помощью GCC 4.8.4. Запустил, подождал некоторое время а LeaseSets так и не были найдены.

![web_console](https://cloud.githubusercontent.com/assets/4211798/8498063/30c8ddea-218b-11e5-84e0-6d180e81a5df.png)

Через минут 18, после запуска, поймал Segment Fault.

Вот лог с ошибками:

14:02:18/error - No NTCP and SSU addresses available
14:02:18/error - Phase 2 read error: End of file. Wrong ident assumed
14:02:18/error - SSU unexpected message 1
14:02:18/error - Phase 2 read error: End of file. Wrong ident assumed
14:02:18/error - Phase 2 read error: End of file. Wrong ident assumed
14:02:20/error - Can't create outbound tunnel. No inbound tunnels found
14:02:20/error - Can't create outbound tunnel. No inbound tunnels found
14:02:20/error - Can't create outbound tunnel. No inbound tunnels found
14:02:20/error - Can't create outbound tunnel. No inbound tunnels found
14:02:20/error - Can't create outbound tunnel. No inbound tunnels found
14:02:20/error - Phase 2 read error: End of file. Wrong ident assumed
14:02:20/error - No NTCP and SSU addresses available
14:02:20/error - Can't create outbound tunnel. No inbound tunnels found
14:02:20/error - Can't create outbound tunnel. No inbound tunnels found
14:02:20/error - Can't create outbound tunnel. No inbound tunnels found
14:02:20/error - Can't create outbound tunnel. No inbound tunnels found
14:02:20/error - Can't create outbound tunnel. No inbound tunnels found
14:02:20/error - Phase 2 read error: End of file. Wrong ident assumed
14:02:23/error - MAC verification failed 371 bytes from 98.253.27.89:20758
14:02:23/error - No NTCP and SSU addresses available
14:02:26/error - No NTCP and SSU addresses available
14:02:26/error - MAC verification failed 375 bytes from 98.253.27.89:20758
14:02:33/error - MAC verification failed 378 bytes from 98.253.27.89:20758
14:02:35/error - Phase 2 read error: End of file. Wrong ident assumed
14:02:36/error - No NTCP and SSU addresses available
14:02:36/error - Phase 2 read error: End of file. Wrong ident assumed
14:02:36/error - Phase 2 read error: Connection reset by peer. Wrong ident assumed
14:02:38/error - MAC verification failed 56 bytes from 98.253.27.89:20758
14:02:40/error - Connect error: Connection refused
14:02:40/error - SSU unexpected message 1
14:02:40/error - No NTCP and SSU addresses available
14:02:41/error - No NTCP and SSU addresses available
14:02:50/error - Phase 2 read error: End of file. Wrong ident assumed
14:02:50/error - No NTCP and SSU addresses available
14:02:50/error - Phase 2 read error: End of file. Wrong ident assumed
14:02:50/error - Phase 2 read error: End of file. Wrong ident assumed
14:02:56/error - No NTCP and SSU addresses available
14:02:56/error - No NTCP and SSU addresses available
14:03:05/error - No NTCP and SSU addresses available
14:03:05/error - Phase 2 read error: End of file. Wrong ident assumed
14:03:05/error - Phase 2 read error: Connection reset by peer. Wrong ident assumed
14:03:08/error - Session to peer CI8uRl7sx2rbaokUdawrGBQhQMUwweETiJJLcMPxfF4= has not been created in 10 seconds
14:03:08/error - Session to peer S438LlxMZQ8shwrDfmOsjspWleVc02-7-HWhklxV5cY= has not been created in 10 seconds
14:03:08/error - Session to peer 4QBKGoP7lhMjtoSM5SV7Ulmc8NBweyYWTBH2oJomtAc= has not been created in 10 seconds
14:03:08/error - Session to peer 4yFMdw8Jz~uo11u1LD8-5nTOYN0AkLinepinoDlMYgg= has not been created in 10 seconds
14:03:10/error - No NTCP and SSU addresses available
14:03:11/error - Connect error: Connection refused
14:03:12/error - Connect error: Connection refused
14:03:12/error - Connect error: Connection refused
14:03:35/error - Read error: Operation canceled
14:03:36/error - Read error: Operation canceled
14:03:36/error - Read error: Operation canceled
14:03:43/error - Read error: Operation canceled
14:03:50/error - Read error: Operation canceled
14:03:50/error - Read error: Operation canceled
14:03:50/error - Read error: Operation canceled
14:04:05/error - Read error: Operation canceled
14:04:05/error - Read error: Operation canceled
14:04:08/error - SSU message has not been ACKed after 5 attempts. Deleted
14:04:09/error - Read error: Operation canceled
14:04:20/error - Phase 2 read error: End of file. Wrong ident assumed
14:04:20/error - Phase 2 read error: Operation canceled. Wrong ident assumed

**Comment by orignal** [comment]
Они там будут только если флудфил.

**Comment by DEMIAN-8** [comment]
Судя по скрину они у меня появились или это не то? Куда смотреть, как можно отладить?

**Comment by orignal** [comment]
Вот так оно выглядит на флудфиле:
Routers: 5477 Floodfills: 789 LeaseSets: 463
потому что туда их публикуют другие.

Для своих целей они сидят не в общей базе, а внутри каждого локального адреса.
Смотреть Local destination там LeaseSets есть для каждого по отдельности.

**Comment by DEMIAN-8** [comment]
На данный момент в Local destination у меня одна запись с LeaseSets: 0 внутри.

**Comment by orignal** [comment]
Так надо куда нибудь попытаться зайти.
Там тоннели вообще есть?

**Comment by DEMIAN-8** [comment]
Да, тоннели есть:

LeaseSets: 0
Tunnels:
-->4244251914:oiyx-->3687118284:~93l-->392405635:uv-F-->934483820:me
-->3000633180:hF0--->2877292269:6wM9-->3563755505:4xzG-->3908065551:me

Streams:

**Comment by orignal** [comment]
Только входящие. Исходящих нет. Потому и не может.

**Comment by DEMIAN-8** [comment]
Что стоит первым делом проверить, какие нужны порты для корректной работы?

**Comment by orignal** [comment]
12089 TCP и UDP надо пробросить, иначе там и будет Firewalled.
Потом надо подождать сколько то чтобы нормально отпрофилировал узлы

**Comment by DEMIAN-8** [comment]
Странно, порты открыты, т.е. у меня правил в iptalbes вовсе нету (разрешены любы входящие/исходящие подключения), а результат тот же:

LeaseSets: 0
Tunnels:
me-->3856788498:gHPG-->1133857407:q-b~-->3497080604:0Ava-->
me-->1835997751:q0ge-->4245888443:2-27-->4094038387:XDas-->
me-->2412904965:acF7-->2968269768:IgqP-->3589362538:0Ava-->
me-->2100208566:oiyx-->3094901269:c96T-->3073387639:atjG-->
me-->2126911798:iNC5-->136353695:Gpof-->3487167483:iBQB-->
-->3125856068:rqsC-->1001260954:IkWF-->1687517284:IE5o-->2331201316:me
-->232280597:Gpof-->2878857089:wXNc-->1083018550:HnFc-->993361699:me
-->3290424925:QXdz-->2457239859:64fN-->1539308368:c1Jq-->1159061566:me
-->932388186:U9S--->2723913130:wXNc-->3795343460:IYzH-->4041370677:me

Streams:

**Comment by orignal** [comment]
Возможно провайдер что то делает. Я этот порт тоже стукнуть не могу. 
Все тоннели есть это хорошо, теперь надо попробовать куда то обратиться. Например через прокси.

**Comment by DEMIAN-8** [comment]
Медленно, но все заработало через 20 минут ожидания. И снова вопрос, хорошо или плохо, что у меня при работающем соединении нету LeaseSets?

**Comment by orignal** [comment]
Если не флудфил то их быть не должно или крайне мало,

**Comment by DEMIAN-8** [comment]
Понятно, спасибо!

**Comment by tung88889999** [comment]
why is LeaseSets: 0 ?

**Comment by orignal** [comment]
Because you are not a floodfill
