### ISSUE TITLE
Test GetMTUWindows

### ISSUE THREAD

**Issue by EinMByte** [PurpleI2P/i2pd#232]
Someone should test `GetMTUWindows`.
mlt pointed out some errors, and I have made some obvious corrections but I don't have anything setup on Windows to test.

Errors should be reported if the MTU can't be detected, so you should notice if it doesn't work.

**Comment by mlt** [comment]
I have tests for loopback though that it is not default, i.e. >576. Give me some time. I can't catch up :panda_face:

**Comment by EinMByte** [comment]
Done.
