### ISSUE TITLE
Use boost for logging

### ISSUE THREAD

**Issue by EinMByte** [PurpleI2P/i2pd#234]
We should migrate to boost for logging, and there should be an option to turn off logging at compile time (I suppose a macro would do).

We might keep `Log` as a wrapper. If we don't, boost probably has some functionality to get rid of all the calls to the logging function.

**Comment by meeh420** [comment]
How big is the logging library for boost? Recall one of the goals was to get it running on small devices, like openwrt routers, which often are limited to say 8Mb in total space.

**Comment by mlt** [comment]
@meeh420 It can be done as an option, so once stable enough, it can be compiled without any logging whatsoever for wireless routers.

**Comment by orignal** [comment]
Let's switch to gcc 4.8 and boost 1.54
