### ISSUE TITLE
client tunnels bind to 0.0.0.0 rather than 127.0.0.1

### ISSUE THREAD

**Issue by Gnos1s** [PurpleI2P/i2pd#235]
This is a security and anonymity risk. Please have them bind to 127.0.0.1. Thanks :)

**Comment by EinMByte** [comment]
The same goes for the HTTP server.

**Comment by edwtjo** [comment]
Also please make this configurable. I thought the port declarations were relative to `--host`..

**Comment by EinMByte** [comment]
Please test the changes in my fork:
- Addresses should be configurable now, use options like `--bobaddress` (see README.md).
- I might be possible to specify IPv6 addresses not (not sure about this, need to test).
- It's not possible yet to have two or more services on different addresses with the same port (will fix soon).

**Comment by lcharles123** [comment]
Hello, specifying `host = 0.0.0.0` in a tunnel.conf specification, the tunnel was still binding to 127.0.0.1 address. 

Testing: 
nmap -p 5000 localhost # port open
nmap -p 5000 my.external.IP # inside same machine, port closed

Below the workaround for this.
ssh -N -L my.external.IP:5000:127.0.0.1:5000 root@localhost

**Comment by Vort** [comment]
@lcharles123 what tunnel type are you trying to create? `client`?
If yes, then try `address = 0.0.0.0` instead.

**Comment by lcharles123** [comment]
Yes, worked now, thank you!
