### ISSUE TITLE
Fix clang warnings

### ISSUE THREAD

**Issue by EinMByte** [PurpleI2P/i2pd#264]
Although  #260 is fixed for gcc, there are still some clang warnings left.
All of them seem to be from `-Woverloaded-virtual`.

**Comment by manasb** [comment]
FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
    Target: x86_64-unknown-freebsd10.1
    Thread model: posix

I see the following warning:

    clang++ -O2 -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -DWITH_AESNI=ON -I/usr/include/ -/usr/local/include/   -c -o obj/Reseed.o Reseed.cpp
    In file included from Reseed.cpp:4:
    In file included from /usr/local/include/boost/regex.hpp:31:
    In file included from /usr/local/include/boost/regex/v4/regex.hpp:48:
    /usr/local/include/boost/regex/v4/regex_raw_buffer.hpp:132:7: warning: 'register' storage class specifier is deprecated [-Wdeprecated-register]
      register pointer result = end;
      ^~~~~~~~~
    1 warning generated.

**Comment by manasb** [comment]
https://gist.github.com/manasb/85dff3dd7edae0686391dac68dbf3535

I'm not seeing the warning I saw earlier :+1:
