### ISSUE TITLE
Expired sertificate *(

### ISSUE THREAD

**Issue by herrniemand** [PurpleI2P/i2pd#266]
https://privacysolutions.no/

NET::ERR_CERT_DATE_INVALID
Subject: *.privacysolutions.no
Issuer: COMODO RSA Domain Validation Secure Server CA

**Comment by meeh420** [comment]
Gonna fix it.

**Comment by meeh420** [comment]
SSL is renewed :)

**Comment by herrniemand** [comment]
JAJ!!!! TA *)

2015-09-10 5:55 GMT+12:00, Meeh <notifications@github.com>:
