### ISSUE TITLE
Need option to specify datadir from command line

### ISSUE THREAD

**Issue by blacklion** [PurpleI2P/i2pd#290]

**Comment by mlt** [comment]
How about `HOME=/my/favorite/path ./i2pd` ?

**Comment by zlatinb** [comment]
Speaking of data dirs, don't forget on OSX the "official" data dir is $HOME/Library/Application Support/$APPNAME, not $HOME/.$APPNAME

**Comment by orignal** [comment]
@zlatinb, we handle it this way now, if you look at util.cpp
