### ISSUE TITLE
Divide datadir into two

### ISSUE THREAD

**Issue by blacklion** [PurpleI2P/i2pd#291]
There should be two independent directories with data: one with persistend data (WebUI, certificates from source tarball) and one for transient data (netDB, SU3, etc).

It allows to install i2pd into routers with read-only root and memory-based /var filesystem.

**Comment by orignal** [comment]
Single directory is the way how Java I2P handles it.

**Comment by blacklion** [comment]
So what? It could be set to one path by default.

I could not use Java I2P on router box either, due to Java size itself :-)

**Comment by orignal** [comment]
They were compatible, so you could switch between Java and i2pd using same directory.
It's not the case anymore, I will think about it.

**Comment by blacklion** [comment]
Oh, I see! Thank you.

**Comment by hagen-i2p** [comment]
@blacklion You may achive this by moving static parts to other place and symlinking it back to datadir.

This method now used in debian package.
