### ISSUE TITLE
Uninitialized members with =default constructor (HTTP Request & others)

### ISSUE THREAD

**Issue by mlt** [PurpleI2P/i2pd#292]
Default constructor should call clear() or something. As of now, Request::update fails to do the right things as has_header is uninitialized (0xcd on Windows debug) when called from HTTPConnection::HandleReceive . In the end web console is inaccessible on master.

**Comment by orignal** [comment]
Are talking about HTTP server implementation? What branch are you referring to?

**Comment by mlt** [comment]
It is about current *master* branch here. `= default` does not initialize members [AFAIK](http://stackoverflow.com/q/15212261/673826). I don't know if things have changed in C++11 or MS ignores it, or there other places to check  (RouterProfile, RouterInfo and alike that have `= default`).

**Comment by orignal** [comment]
default invokes default constructors of members

**Comment by mlt** [comment]
```
#include <stdio.h>


class A {
    int me;
public:
    A() = default;
    void show() {
        printf("0x%x", me);
    }
};

int _tmain(int argc, _TCHAR* argv[])
{
    A surprise;
    surprise.show();
	return 0;
}
```
yields `0xcccccccc`.

**Comment by orignal** [comment]
It works as expected, if you want to have "me" initialized you must write "int me = 0; "

**Comment by mlt** [comment]
Well, I don't see it [there](https://github.com/PurpleI2P/i2pd/blob/master/core/util/HTTP.h#L58) ;-) Perhaps the following classes should be checked as well
- [ ] DaemonLinux
- [ ] SessionTag
- [ ] Response
- [ ] Tag
- [ ] Identity
- [ ] RouterProfile
- [ ] RouterInfo
- [ ] Fragment

**Comment by orignal** [comment]
Please check if you see it in the  openssl branch
