### ISSUE TITLE
Does this project gives access to .i2p sites?

### ISSUE THREAD

**Issue by shackra** [PurpleI2P/i2pd#293]
That's my question.

**Comment by orignal** [comment]
Indeed

**Comment by mlt** [comment]
You'd also want to configure a proxy in your web browser, e.g. FoxyProxy for Firefox.
Alternatively, if you have DHCP, DNS, and Web server in your LAN, e.g. by running DD-WRT with dnsmasq, and you trust your LAN you may consider using WPAD with PAC.

dnsmasq extra config
```
dhcp-option=252,http://<web server ip>/wpad.dat
address=/wpad.<you lan domain>/<web server ip>
dhcp-host=<web server MAC>,<web server ip>
```
And wpad.dat
```
function FindProxyForURL(url, host) {
        if (shExpMatch(host, "*.i2p"))
        {
                return "PROXY 192.168.1.132:4444";
        }

        return "DIRECT";
}
```

**Comment by shackra** [comment]
So, basically yes.

Thank you :)
