### ISSUE TITLE
http tunnel

### ISSUE THREAD

**Issue by igran** [PurpleI2P/i2pd#297]
whether it is possible to use  tunnels in i2pd as  http?
example host:9079 ->forum.i2p
I tried to open the tunnel 
````ini
[forum]
type = client
address = 0.0.0.0
port = 9079
destination = forum.i2p
````

but it's not work
```curl
localhost ~ # curl -vv http://172.17.0.3:9079
* Rebuilt URL to: http://172.17.0.3:9079/
* Hostname was NOT found in DNS cache
*   Trying 172.17.0.3...
* Connected to 172.17.0.3 (172.17.0.3) port 9079 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.39.0
> Host: 172.17.0.3:9079
> Accept: */*
>
* Empty reply from server
* Connection #0 to host 172.17.0.3 left intact
curl: (52) Empty reply from server
```

**Comment by orignal** [comment]
https://github.com/PurpleI2P/i2pd/wiki/tunnels.cfg

Most likely you don't have forum.i2p in your addressbook yet.
Please check ~/.i2pd/addressbook/addresses.csv if it's there

**Comment by igran** [comment]
grep "forum.i2p" /data/2p/pi2p/data/addressbook/addresses.csv
forum.i2p,33pebl3dijgihcdxxuxm27m3m4rgldi5didiqmjqjtg4q6fla6ya

and i  checked curl with http proxy and it work
````curl
# curl -v -I http://forum.i2p -x http://172.17.0.3:4444
* Rebuilt URL to: http://forum.i2p/
* Hostname was NOT found in DNS cache
*   Trying 172.17.0.3...
* Connected to 172.17.0.3 (172.17.0.3) port 4444 (#0)
> HEAD http://forum.i2p/ HTTP/1.1
> User-Agent: curl/7.39.0
> Host: forum.i2p
> Accept: */*
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Date: Sat, 21 Nov 2015 19:11:56 GMT
Date: Sat, 21 Nov 2015 19:11:56 GMT
< Server: Apache
Server: Apache
< Set-Cookie: phpbb2mysql_data=a%3A0%3A%7B%7D; expires=Sun, 20-Nov-2016 19:11:56 GMT; path=/
Set-Cookie: phpbb2mysql_data=a%3A0%3A%7B%7D; expires=Sun, 20-Nov-2016 19:11:56 GMT; path=/
< Set-Cookie: phpbb2mysql_sid=eb7f582e43af1129eb6e36517b8485a9; path=/
Set-Cookie: phpbb2mysql_sid=eb7f582e43af1129eb6e36517b8485a9; path=/
< Cache-Control: private, pre-check=0, post-check=0, max-age=0
Cache-Control: private, pre-check=0, post-check=0, max-age=0
< Expires: 0
Expires: 0
< Pragma: no-cache
Pragma: no-cache
< Connection: close
Connection: close
< Content-Type: text/html
Content-Type: text/html

<
* Closing connection 0
````
but direct not work

**Comment by orignal** [comment]
This is the issue with forum.i2p itself, it doesn't like Host: 172.17.0.3:9079
I've tried zzz.i2p instead forum.i2p
[forum]
type=client
port=9079
destination=zzz.i2p

curl -vv http://127.0.0.1:9079
* Rebuilt URL to: http://127.0.0.1:9079/
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 127.0.0.1 (127.0.0.1) port 9079 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 127.0.0.1:9079
> Accept: */*
> 
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0< HTTP/1.1 200 OK
< ETag: "7a74b8ddb65b9b20390306ad69f2c535"
< Content-Type: text/html; charset=utf-8
< Content-Length: 24122
< Cache-Control: private, max-age=0, must-revalidate
< X-Runtime: 152
< Connection: close

**Comment by igran** [comment]
this is magic. some sites work with direct tunnel some only with http proxy. i  want make LAN mirror some sites, but nginx can't make proxy_pass over http_proxy or i don't know about this

**Comment by orignal** [comment]
"Host:" matters

**Comment by igran** [comment]
If you mean proxy_set_header Host zzz.i2p; it does not work I get 500

```curl
root@94359c75a5ff:/data/orignal/i2pd/bin# curl -vI http://127.0.0.1:4444 -H  "Host: stats.i2p"
* Rebuilt URL to: http://127.0.0.1:4444/
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 4444 (#0)
> HEAD / HTTP/1.1
> User-Agent: curl/7.38.0
> Accept: */*
> Host: stats.i2p
>
* HTTP 1.0, assume close after body
< HTTP/1.0 500 Internal Server Error
HTTP/1.0 500 Internal Server Error
< Content-type: text/html
Content-type: text/html
< Content-length: 0
Content-length: 0
* Closing connection 0
```
and valid request
````curl
curl -vIx http://127.0.0.1:4444 http://stats.i2p
* Rebuilt URL to: http://stats.i2p/
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 4444 (#0)
> HEAD http://stats.i2p/ HTTP/1.1
> User-Agent: curl/7.38.0
> Host: stats.i2p
> Accept: */*
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Date: Sun, 22 Nov 2015 17:41:04 GMT
Date: Sun, 22 Nov 2015 17:41:04 GMT
< Content-Type: text/html
Content-Type: text/html
< Last-Modified: Thu, 22 Oct 2015 14:50:34 GMT
Last-Modified: Thu, 22 Oct 2015 14:50:34 GMT
< Content-Length: 13181
Content-Length: 13181
< Accept-Ranges: bytes
Accept-Ranges: bytes
< Cache-Control: max-age=3600,public
Cache-Control: max-age=3600,public
< Connection: close
Connection: close

<
* Closing connection 0
````
