### ISSUE TITLE
error: ‘sleep_for’ is not a member of ‘std::this_thread’

### ISSUE THREAD

**Issue by grumbler66rus** [PurpleI2P/i2pd#299]
(gcc version 4.7.2 20121109, linux)

Tunnel.cpp:387:3: error: ‘sleep_for’ is not a member of ‘std::this_thread’
AddressBook.cpp:186:5: error: ‘sleep_for’ is not a member of ‘std::this_thread’
I2PControl.cpp:115:4: error: ‘sleep_for’ is not a member of ‘std::this_thread’

Solution:

    NEEDED_CXXFLAGS=-D_GLIBCXX_USE_NANOSLEEP make obj/Tunnel.o obj/AddressBook.o obj/I2PControl.o obj/i2pd.o
    make

or

    NEEDED_CXXFLAGS=-D_GLIBCXX_USE_NANOSLEEP make

or change Makefile.linux:

    diff --git a/Makefile.linux b/Makefile.linux
    index 78dcaaf..72170f6 100644
    --- a/Makefile.linux
    +++ b/Makefile.linux
    @@ -24,7 +24,7 @@ else # not supported
     	$(error Compiler too old)
     endif
     
    -NEEDED_CXXFLAGS += -fPIC
    +NEEDED_CXXFLAGS += -fPIC -D_GLIBCXX_USE_NANOSLEEP
     
     ifeq ($(USE_STATIC),yes)
       LIBDIR := /usr/lib

**Comment by orignal** [comment]
which Linux are you using?

**Comment by grumbler66rus** [comment]
ALT Linux 7.0.5 Centaurus  (Pholus)

**Comment by grumbler66rus** [comment]
I use GNU C 4.7.2 and 'sleep_for' declared in the file /usr/include/c++/4.7.2/thread. Code of declaration:
    
    #ifdef _GLIBCXX_USE_NANOSLEEP
        /// sleep_for
        template<typename _Rep, typename _Period>
          inline void
          sleep_for(const chrono::duration<_Rep, _Period>& __rtime)
          {
    	chrono::seconds __s =
    	  chrono::duration_cast<chrono::seconds>(__rtime);
    
    	chrono::nanoseconds __ns =
    	  chrono::duration_cast<chrono::nanoseconds>(__rtime - __s);
    
    	__gthread_time_t __ts =
    	  {
    	    static_cast<std::time_t>(__s.count()),
    	    static_cast<long>(__ns.count())
    	  };
    
    	::nanosleep(&__ts, 0);
          }
    
        /// sleep_until
        template<typename _Clock, typename _Duration>
          inline void
          sleep_until(const chrono::time_point<_Clock, _Duration>& __atime)
          { sleep_for(__atime - _Clock::now()); }
    #endif

**Comment by mlt** [comment]
FYI this define does exist as of eddb5fa9 in CMake files as a workaround for older compilers.

**Comment by orignal** [comment]
I'm not sure it's older compiler seems it's older libstd
