### ISSUE TITLE
Избавиться от буста

### ISSUE THREAD

**Issue by KOLANICH** [PurpleI2P/i2pd#3]
Считаю, что буст следует заменить на С++11 везде, где возможно.

**Comment by mittorn** [comment]
Поддерживаю, сборка буста утянула мою систему в лютый oom несколько раз, да и пр времени сборка - сутки.

**Comment by orignal** [comment]
Пока для этого возможностей нет.

**Comment by ryzhovau** [comment]
Успешно нативно собирается на WD My Book Live с 256MB RAM, 512MB Swap без каких-либо вылетов. В своп залезал, да, но oom не было.

**Comment by orignal** [comment]
Собираться то он собирается, просто с бустом бинарники получаются большими.

**Comment by ryzhovau** [comment]
~5MB для PowerPC с glibc и ~3MB для MIPS с uClibc.

**Comment by orignal** [comment]
А PPC откуда? У меня под G3 получилось существенно больше.
В любом случае несколько мегабайт это много, нормально должно быть пара сотен.

**Comment by ryzhovau** [comment]
PPC  — NAS WD My Book Live.

**Comment by ryzhovau** [comment]
К слову, приведены размеры stripped бинарников.

**Comment by orignal** [comment]
Тем более от буста надо будет избавляться :)

**Comment by mittorn** [comment]
https://github.com/PurpleI2P/i2pd/issues/3#issuecomment-78248388
Это он наверное без отладки собирается. Так у меня тоже умеет. А вылетает когда включена отладка.

**Comment by orignal** [comment]
На какой плаформе вылетает?

**Comment by mittorn** [comment]
В смысле, если собирается с отладкой в 2 потока, на гигабайте памяти сборка съедает всю память и падает - т.е более 400 мб на один поток с отладкой. В один вроде уместилось.

**Comment by orignal** [comment]
Это про gcc что ли речь? Я думал падает само приложение если собрано без отладки.
Вообще под слабое железо надо кросс-компилятором собирать.

**Comment by mittorn** [comment]
Ну один гигабайт - не такое уж слабое железо. Конечно для игорь и фраерфокса этого мало, но для задач попроще хватит всем. Фокс ксатаи вполне умещается при использовании zram, если не загружать жидхаб, остальные сайты вроде не роняют его..
