### ISSUE TITLE
Regular segfaults during signature verifying from i2p::transport::SSUSession::ProcessSessionCreated

### ISSUE THREAD

**Issue by alxchk** [PurpleI2P/i2pd#303]
I'm testing i2pd on my beaglebone-black. I2pd crashes with 3-4h period. Here is two sample backtraces.
[bt2.txt](https://github.com/PurpleI2P/i2pd/files/44650/bt2.txt)
[bt.txt](https://github.com/PurpleI2P/i2pd/files/44651/bt.txt)

For me it looks like something in not threadsafe

**Comment by orignal** [comment]
Is it trunk or 2.1.0?

**Comment by orignal** [comment]
Try to change line 390 of Signature.cpp from
static std::unique_ptr<Ed25519> g_Ed25519;
to
static thread_local std::unique_ptr<Ed25519> g_Ed25519;
and see if the problem still exists

**Comment by orignal** [comment]
Rebuild trunk with gcc 4.8 and higher. Should be fixed.

**Comment by alxchk** [comment]
Now it crashes even faster. 

[i2pd.6829.txt](https://github.com/PurpleI2P/i2pd/files/46012/i2pd.6829.txt)
[i2pd.6603.txt](https://github.com/PurpleI2P/i2pd/files/46017/i2pd.6603.txt)
[i2pd.6235.txt](https://github.com/PurpleI2P/i2pd/files/46014/i2pd.6235.txt)
[i2pd.5848.txt](https://github.com/PurpleI2P/i2pd/files/46013/i2pd.5848.txt)
[i2pd.5732.txt](https://github.com/PurpleI2P/i2pd/files/46015/i2pd.5732.txt)
[bt3.txt](https://github.com/PurpleI2P/i2pd/files/46016/bt3.txt)
[i2pd.7047.txt](https://github.com/PurpleI2P/i2pd/files/46018/i2pd.7047.txt)
[i2pd.6987.txt](https://github.com/PurpleI2P/i2pd/files/46019/i2pd.6987.txt)

**Comment by orignal** [comment]
Most likely it's #220, not EdDSA. You see this trace a lot because it consumes a lot of time at weak CPU

**Comment by orignal** [comment]
Made openssl thread-safe, should try trunk
