### ISSUE TITLE
I2pd should listen on 127.0.0.1 by default (or at least be able to do so)

### ISSUE THREAD

**Issue by alxchk** [PurpleI2P/i2pd#305]
Probably it's a bit bad idea to share your IRC / Socks to everyone. Isn't it?

**Comment by orignal** [comment]
You might need to run I2P at separate device. But yes, it must be configurable.
@majestrate has made this change already, I will beckport it from master soon

**Comment by orignal** [comment]
https://github.com/PurpleI2P/i2pd/pull/306
