### ISSUE TITLE
Добавление адреса в адресную книгу

### ISSUE THREAD

**Issue by rrouk** [PurpleI2P/i2pd#309]
Добрый день, не подскажете - пытаюсь добавить адрес в адресную книгу, не выходит. Она у вас как то совсем по другому устроена нежели чем в обычном i2p

**Comment by orignal** [comment]
файл, ~/.i2pd/addressbook.csv
Действительно устроена сильно по другому.

**Comment by rrouk** [comment]
Разобрался) Спасибо. Кстати - раз уж пляски пошли - не подскажете, можно как то с i2pd подключиться к i2p-bote либо стандартной суси почте?

**Comment by orignal** [comment]
Смотря по какому протоколу он работает.
SAM, BOB можно, I2CP нельзя

**Comment by rrouk** [comment]
Ммм я разобрался. Последний вопрос - есть ли какой нибудь вебинтерфейс с бекджеком.. с кнопками и прочим? Привык просто к ява интерфейсам роутера..

**Comment by orignal** [comment]
Так как в джаве не будет, в том смысле чтобы конфиги через веб заполянть - в любом случае придется ручками.
Для управления работой есть недоделанный webui, работающий через I2PControl.
