### ISSUE TITLE
Eliminate util.h/.cpp

### ISSUE THREAD

**Issue by orignal** [PurpleI2P/i2pd#314]
Code from there should be moved to relevant places.

**Comment by hagen-i2p** [comment]
Proposal: extract new namespace i2p::fs from this file and ClientContext's functions LoadLocalDestination() and ReadTunnels().

Also: DaemonLinux.cpp contains some code to direct work with pidfile.

**Comment by hagen-i2p** [comment]
Another part of code in util.* is handling cmdline args. Now i'm working on another realization with boost::program_options.

P.S. Just reminder.

**Comment by l-n-s** [comment]
Any updates? Should we close it?

**Comment by orignal** [comment]
Закрывать не надо. Надо довести дело до конца
