### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by donat-b** [PurpleI2P/i2pd#316]
Was compiled at 9cc592b
https://bpaste.net/raw/4f26c238d406

Please, ask if you need any additional info.

**Comment by orignal** [comment]
Thread #7 I guess.  I saw that issue as well and investigating.
If you need a workaround pass copy of p in line 263 of Signature.cpp.
You can make this copy outside  the loop like EDDSAPoint p1(p) and pass p1.
It sure solves the problem, why p gets corrupted in the middle of a loop is good question

**Comment by orignal** [comment]
Fixed. Please take lastest version from trunk

**Comment by donat-b** [comment]
Great. (:
I'll keep you posted if something goes wrong.
