### ISSUE TITLE
Please verify the link on Crypto++ website

### ISSUE THREAD

**Issue by noloader** [PurpleI2P/i2pd#324]
I'm looking at Crypto++'s [Related Links](https://www.cryptopp.com/wiki/Related_Links) page. It provides a sounding board for those using the Crypto++ library, and provides an opportunity for folks to advertise their programs and services.

There is/was an entry for [Privacy Solutions](http://privacysolutions.no/) using ***`http://privacysolutions.no/`***. The entry is still present but the link was changed and it looks suspicious to me:

* Old link: ***`http://privacysolutions.no/`***
* New link: ***`http://i2pd.website/`***
* [Difference between revisions of "Related Links"](http://www.cryptopp.com/w/index.php?title=Related_Links&diff=prev&oldid=12316)

The new link is suspicious because [Privacy Solutions](http://privacysolutions.no/) does not link to it from the i2pd logo on its homepage, and I'm not sure about the sites in vanity domains like ***`.website`***.

Please verify the link.

**Comment by orignal** [comment]
i2pd is not part of privacysolutions.no anymore for more than year now.
 The  new organization is PurpleI2P and i2pd.website is correct one. 
You can see link from the main gihub page at this project.
However i2pd doesn't use crypto++ anymore, we have switched to openssl recently.
Old releases up to 0.10.0 did.
If you wish you can remove it from that list.
