### ISSUE TITLE
Документация на русском языке

### ISSUE THREAD

**Issue by orignal** [PurpleI2P/i2pd#325]
Каждый может принять участие в ее создании.
Надо не переводить что есть с английского, а написать более качественную и подробную, пользуясь данной свыше способностью говорить по-русски.

**Comment by iShift** [comment]
т.е перевести с английского? 
PS В последней версии родной webui был выпилен ?

**Comment by l-n-s** [comment]
https://github.com/PurpleI2P/i2pd_docs_ru

https://i2pd.readthedocs.io/ru/latest/

набигаем@контрибьютим

**Comment by l-n-s** [comment]
Markdown на GitHub и ReadTheDocs несовместимы. Яркий пример тому -- файл docs/usage.md -- по разному рендерится нумерованный список, на гитхабе отображается криво.

Надо делать совместимо с ReadTheDocs.

**Comment by orignal** [comment]
А что конкретно надо делать?
