### ISSUE TITLE
Client tunnels with same keys file

### ISSUE THREAD

**Issue by thekurych** [PurpleI2P/i2pd#331]
Unexpected behavior i2pd with two client tunnels that have been configured with the same "keys" options. For example

$cat tunnels.cfg
[IRC_0]
type = client
address = 192.168.1.1
port = 6668
destination = irc.postman.i2p
keys = irc-keys.dat

[IRC_1]
type = client
address = 192.168.1.1
port = 6669
#destination = irc.dg.i2p
destination = irc.echelon.i2p
keys = irc-keys.dat

We have two different local destinations:
Client Tunnels:
IRC_0 ⇐ nzntmd4wabw2mghv7g2hopxm3htgq5oc2v3tv3zulikzpabvdp2q.b32.i2p
IRC_1 ⇐ oahtxscbwl5q3jqchpipm5e566nclo5m4co5p6jpcqxhv2laul4a.b32.i2p

and the first LD will remain the same address after restart i2pd, but second LD change value.
Is it right?

**Comment by orignal** [comment]
fixed
