### ISSUE TITLE
Building 2.3.0 on FreeBSD 10.2 amd64

### ISSUE THREAD

**Issue by stargrave** [PurpleI2P/i2pd#332]
Greetings!

I have got FreeBSD 10.2 amd64 OS with latest gcc47, boost-libs and cmake installed from ports. I checkouted 2.3.0 tag from i2pd repository.

Then, following docs/build_notes_unix.md I tried to build it with gcc:

    $ mkdir build/tmp
    $ cd build/tmp/
    $ CC=/usr/local/bin/gcc47 CXX=/usr/local/bin/g++47 cmake -DCMAKE_BUILD_TYPE=Release ..
    $ gmake
    $ gmake
    [  2%] Building CXX object CMakeFiles/libi2pd.dir/tmp/i2pd/Reseed.cpp.o
    /tmp/i2pd/Reseed.cpp: In member function 'std::string i2p::data::Reseeder::HttpsRequest(const string&)':
    /tmp/i2pd/Reseed.cpp:373:53: error: 'to_string' is not a member of 'std'
    /tmp/i2pd/Reseed.cpp:373:85: error: unable to deduce 'auto' from '<expression error>'
    CMakeFiles/libi2pd.dir/build.make:302: recipe for target 'CMakeFiles/libi2pd.dir/tmp/i2pd/Reseed.cpp.o' failed
    gmake[2]: *** [CMakeFiles/libi2pd.dir/tmp/i2pd/Reseed.cpp.o] Error 1
    CMakeFiles/Makefile2:142: recipe for target 'CMakeFiles/libi2pd.dir/all' failed
    gmake[1]: *** [CMakeFiles/libi2pd.dir/all] Error 2
    Makefile:149: recipe for target 'all' failed
    gmake: *** [all] Error 2

Then, I removed tmp, created it again, call cmake without CC/CXX, leading to building with clang. It builds successfully.

    [...]
    18 warnings generated.
    [100%] Linking CXX executable i2pd
    [100%] Built target i2pd

**Comment by orignal** [comment]
Please try regular Makefile.

**Comment by stargrave** [comment]
You mean using of "make" instead of "gmake". Tried it, from the clean directory, the same error occurs.

**Comment by orignal** [comment]
without cmake.
just run gmake it invokes Makefile.bsd
I was able to build it for 10.1, not sure about 10.2

**Comment by stargrave** [comment]
The same thing:

    $ git status
    HEAD detached at 2.3.0
    nothing to commit, working directory clean
    $ gmake CC=/usr/local/bin/gcc47 CXX=/usr/local/bin/g++47 -j4
    mkdir -p obj
    /usr/local/bin/g++47 -O2 -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -I/usr/include/ -I/usr/local/include/  -c -o obj/Crypto.o Crypto.cpp
    /usr/local/bin/g++47 -O2 -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -I/usr/include/ -I/usr/local/include/  -c -o obj/Datagram.o Datagram.cpp
    /usr/local/bin/g++47 -O2 -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -I/usr/include/ -I/usr/local/include/  -c -o obj/Garlic.o Garlic.cpp
    /usr/local/bin/g++47 -O2 -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -I/usr/include/ -I/usr/local/include/  -c -o obj/I2NPProtocol.o
    I2NPProtocol.cpp
    /usr/local/bin/g++47 -O2 -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -I/usr/include/ -I/usr/local/include/  -c -o obj/LeaseSet.o LeaseSet.cpp
    /usr/local/bin/g++47 -O2 -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -I/usr/include/ -I/usr/local/include/  -c -o obj/Log.o Log.cpp
    /usr/local/bin/g++47 -O2 -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -I/usr/include/ -I/usr/local/include/  -c -o obj/NTCPSession.o NTCPSession.cpp
    /usr/local/bin/g++47 -O2 -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -I/usr/include/ -I/usr/local/include/  -c -o obj/NetDb.o NetDb.cpp
    /usr/local/bin/g++47 -O2 -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -I/usr/include/ -I/usr/local/include/  -c -o obj/NetDbRequests.o NetDbRequests.cpp
    /usr/local/bin/g++47 -O2 -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -I/usr/include/ -I/usr/local/include/  -c -o obj/Profiling.o Profiling.cpp
    /usr/local/bin/g++47 -O2 -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -I/usr/include/ -I/usr/local/include/  -c -o obj/Reseed.o Reseed.cpp
    /usr/local/bin/g++47 -O2 -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -I/usr/include/ -I/usr/local/include/  -c -o obj/RouterContext.o RouterContext.cpp
    Reseed.cpp: In member function 'std::string i2p::data::Reseeder::HttpsRequest(const string&)':
    Reseed.cpp:373:53: error: 'to_string' is not a member of 'std'
    Reseed.cpp:373:85: error: unable to deduce 'auto' from '<expression error>'
    /usr/local/bin/g++47 -O2 -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -I/usr/include/ -I/usr/local/include/  -c -o obj/RouterInfo.o RouterInfo.cpp
    /usr/local/bin/g++47 -O2 -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -I/usr/include/ -I/usr/local/include/  -c -o obj/Signature.o Signature.cpp
    /usr/local/bin/g++47 -O2 -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -I/usr/include/ -I/usr/local/include/  -c -o obj/SSU.o SSU.cpp
    Makefile:50: recipe for target 'obj/Reseed.o' failed
    gmake: *** [obj/Reseed.o] Error 1
    gmake: *** Waiting for unfinished jobs....

**Comment by orignal** [comment]
Please use clang rather than g++

**Comment by stargrave** [comment]
With clang it builds without any problems.

If clang is ok for the usage, then I think this issue can be closed. And mirrored in the build documentation for FreeBSD.

**Comment by orignal** [comment]
Yes, clang is assumed for FreeBSD and Mac OS X.
