### ISSUE TITLE
Не работает imule

### ISSUE THREAD

**Issue by Agagamand** [PurpleI2P/i2pd#334]
Через минуту после запуска imule вылетает с ошибкой.
Nodes list заполняется. В логе пишет:
2016-01-22 09:54:20: Connection to the underlying I2P network successful
2016-01-22 09:54:20: Autoconnect to the Kad indexing network (see Preferences if you want to disable it).
2016-01-22 09:54:22: Kad запущена.
Но в статусной строке написано "Идёт подключение" - http://i.imgur.com/JH9IkV6.png
И через секунду возникает такая вот ошибка, кликнув OK на которой, imule закрывается http://i.imgur.com/32mFKs1.png

Сведения с i2pd webconsole
Uptime: 00:10:09
Status: Firewalled
Tunnel creation success rate: 24%
Received: 4022K (1686 Bps)
Sent: 5831K (2156 Bps)
Routers: 1419 Floodfills: 916 LeaseSets: 0

Запускал i2pd с параметром -samport=7656, imule тоже настроен работать через этот порт. В чём проблема?

**Comment by orignal** [comment]
imule и раньше грохался с этой ошибкой когда пытался начальный список узлов скачать. Их надо откуда то скачать (вроде у эшелено лежат) и положить вручную.
Раньше точно работал, но сам давно не запускал. Возможно что то поломал с датаграммами. Проверю.

**Comment by Agagamand** [comment]
Забыл уточнить важный нюанс. С официальной реализацией i2p (на Java) imule работает идеально. Нет и намёка на какие-либо проблемы. Список узлов я ему уже давно скачал и он с ними нормально качает и раздаёт.

Возможно так же имеет значение операционная ситстема. У меня Windows 7 x64.

**Comment by orignal** [comment]
Вообщем запущу и разберусь, если что то не работает то поправлю.

**Comment by orignal** [comment]
Счас запустил. Показывает 17K файлов и 160 пользователей.
Файлы качает.  
Но это линукс

**Comment by Agagamand** [comment]
Ну я как бы и вчера вечером тестировал, и сегодня утром... При том вчера только после двух часов работы i2pd начал тестировать. На i2p сайты заходить получается без проблем, но imule не хочет работать. Пробывал сбрасывать в муле настройки и использовать свежескачаный. Если сбросить ему настройки то ошибку уже не показывает, но и к сети не подключается. В общем тестируйте на Win7, ошибка точно есть.

**Comment by orignal** [comment]
@mlt, можешь попробовать у себя?

**Comment by orignal** [comment]
А можно пример живой ссылки где пиры есть?

**Comment by Agagamand** [comment]
Вот тут вроде раздающие есть:
ed2k://|file|game.of.thrones.s04e10.720p.hdtv.x264-killers.ENG.srt|45072|BAA26EF33C670A48392A3007BB4679FD|/

Но вообще проблема не в том, скачивает или нет, проблема в том что просто к сети не подключается. То есть вот здесь не меняется статус на "подключено" - http://i.imgur.com/JH9IkV6.png

**Comment by orignal** [comment]
Я понимаю в чем проблема, но мне надо убедиться, что все остальное тоже работает если я этим займусь,

**Comment by orignal** [comment]
Запустил i2pd под виндой, а iMule с линукса. Вижу что при получении первой датаграммы imule грохается, почему -  не знаю. Судя по логам вполне заурядная датаграмма, и подпись проходит.

**Comment by orignal** [comment]
Починил в транке. Либо собирать, либо ждать следующего релиза
