### ISSUE TITLE
Ничего не работает)

### ISSUE THREAD

**Issue by Vasa231313** [PurpleI2P/i2pd#336]
Поставил себе на убунту вашу штуку, все по инструкции сделал, жду весь день когда хоть на какой ни будь сайт в i2p зайдет с браузера(на нем настроил все как надо), но ничего не работает. Терминал постоянно что-то там делает, а толку нет, что мне делать?)

**Comment by orignal** [comment]
на inr.i2p пробовали?

**Comment by Vasa231313** [comment]
Да, конечно. Просто белый экран, не один из i2p сайтов не работает.

Может быть в роутере нужно как-то порты пробрасывать? В описании не нашел про это. В статусе написано "Status: Firewalled" 

"Routers: 1407 Floodfills: 593 LeaseSets: 0." Если от этого как-то зависит, то наверное уже должно работать.

**Comment by orignal** [comment]
а если так? http://127.0.0.1:7070/zzz.i2p ?

**Comment by Vasa231313** [comment]
написано "Unknown address zzz.i2p" и картинка сервиса)

**Comment by orignal** [comment]
значит адресную книгу не смог загрузить. посмотрю

**Comment by Vasa231313** [comment]
В папке i2pd я такой дерриктории визуально не вижу, но если нажать команду в консоли "CD ~/.i2pd/addressbook" то он переходит в эту папку

**Comment by orignal** [comment]
там есть addressbook.cvs?

**Comment by Vasa231313** [comment]
Сори что так долго, я думал что нажать) если нажать ls ~/.i2pd/addressbook
то ответ будет такой:
addresses.csv  b3  b7  bc  bg  bj  bp  bq  br  bw

**Comment by Vasa231313** [comment]
если открыть http://inr.i2p/ то в терминале пишит: 
"HTTP Proxy Issue when creating the stream, check the previous warnings for more info"

если открыть http://127.0.0.1:7070/zzz.i2p то пишит такое))
01:01:50/info - HTTPServer: client request: GET / HTTP/1.1
Host:zzz.i2p
01:01:50/warn - HTTPServer: Unknown address zzz.i2p

**Comment by orignal** [comment]
Все понятно. У вас начальный список адресов не заргузился (может тот адресс оффлайн был).
Совет: остановить, удалить директорию ~/.i2pd/addressbook  и запустить снова.
Возможно все получится.
Но определенный огрвывод из этого я сделал - будем так кое что менять.

**Comment by Vasa231313** [comment]
Спасибо все починил)

Значит эти файлы(subscriptions.txt, tunnels.cfg) нужно было кидать в скрытую папку, а не открытую, убунта же для новичков, зачем так все усложнять)) и зачем тогда открытая папка нужна) Спасибо)

**Comment by orignal** [comment]
в открытой только бинарник, он вообще может быть где угодно

**Comment by orignal** [comment]
Все работает
