### ISSUE TITLE
Proposal: set Tor as outproxy in Socks proxy

### ISSUE THREAD

**Issue by l-n-s** [PurpleI2P/i2pd#338]
This trick works with Java I2P, it would be great if it works with i2pd too.

Point here is setting outproxy to local proxy, for example 127.0.0.1:9050. All i2p traffic goes through i2p, all clearnet/onion traffic goes through Tor.

With that we can easily build I2P+Tor browser bundle on top of modified TorBrowser. Just modify "Browser/TorBrowser/Data/Tor/torrc-defaults" to listen on 9153, set that address as outproxy and run i2pd socks proxy at 9150. TorBrowser displays like browser isn't working through Tor, but actually it works fine (so some UI modifications should be done too). 

Who use both i2pd and TorBrowser, please try if it works!

**Comment by orignal** [comment]
@klondi, do you have any suggestions?

**Comment by klondi** [comment]
So the idea is setting a default SOCKS proxy for non i2p traffic going through i2pd or just through i2pd's SOCK proxy? If it's the first I believe it can be fixed easily, if it's the second though it may be a bit more complicated (although  it could be done).

**Comment by l-n-s** [comment]
@klondi idea here is so user can set outproxy variable to  "127.0.0.1:9050", so all non-i2p traffic go through Tor. This works for Java I2P already.

User will set browser to use i2pd SOCKS proxy and i2pd will route everything for you. This way we can easily integrate i2pd to TorBrowser. :wink:

**Comment by klondi** [comment]
Okay I think I see what you mean now. I think this is feasible. @orignal I'm not familiar with i2pd's parameter handling but if you add the parameter to ip2d I believe I can write the SOCKS client to proxy requests.

**Comment by orignal** [comment]
@klondi, I have added two parameters -socksoutproxyaddress and socksoutproxyport
socksoutproxyaddress is empty by default and socksoutproxyport is zero be default.
I pass them to SOCKSServer as outAddress and outPort

**Comment by klondi** [comment]
@orignal I have started working on this, I can take care of stablishing the new tunnel on the remote SOCKS5 server, but I'm not sure if we have a class allowing connection of two TCP sockets as I2PTunnelConnection does for a socket and an I2PTunnel.

**Comment by orignal** [comment]
Please explain how it should work? Two TCP sockets mapped to one I2P destination or what? Please elaborate and I will add one for you.

**Comment by klondi** [comment]
I need a class with an interface similar to I2PTunnelConnection but that forwards traffic from a socket to another socket (instead of from a socket to a open I2P tunnel).

This is because once the negotiation is done with the remote SOCKS server traffic has to be forwarded afterwards to and from the new socket established to the remote SOCKS server, but we'd like to keep having properties like being able to shutdown gracefully.

**Comment by majestrate** [comment]
initial parts added in https://github.com/PurpleI2P/i2pd/commit/f339544256842ef984abb4b9b15600819e1b66c8
