### ISSUE TITLE
Crash on close (Windows)

### ISSUE THREAD

**Issue by redmanmale** [PurpleI2P/i2pd#341]
On close (plain close or ctrl-c) app crashes with system error:
![screen](https://puu.sh/mGNVT/0b0f9ff22c.png)

Win 8.1 x64.

**Comment by orignal** [comment]
same for me. Will try under debugger

**Comment by webserfer** [comment]
Same on Windows 7 x64

Сигнатура проблемы:
  Имя события проблемы:	APPCRASH
  Имя приложения:	i2pd.exe
  Версия приложения:	0.0.0.0
  Отметка времени приложения:	569556ea
  Имя модуля с ошибкой:	i2pd.exe
  Версия модуля с ошибкой:	0.0.0.0
  Отметка времени модуля с ошибкой:	569556ea
  Код исключения:	40000015
  Смещение исключения:	0028287d
  Версия ОС:	6.1.7601.2.1.0.256.1
  Код языка:	1049
  Дополнительные сведения 1:	2362
  Дополнительные сведения 2:	2362f8261fb9595e1bd140298fbbe318
  Дополнительные сведения 3:	e6b0
  Дополнительные сведения 4:	e6b07337a11b0e09ad36107a2a40023d
