### ISSUE TITLE
Библеотеку UPnP надо загружать по полному пути

### ISSUE THREAD

**Issue by evgkrsk** [PurpleI2P/i2pd#342]
AFAIK, библиотеки обычно упаковываются в пакеты по полным путям, в то время как симлинки на эти пути с расширением **.so** упаковываются в отдельный подпакет для разработки (**devel**). Т.к. сейчас (на релиз 2.3.0) i2pd загружает **libminiupnpc.so**, то перенаправление UPnP на маршрутизаторе не работает, пока не установишь пакет разработчика:

```bash
evg@thinkpad ~ $strace i2pd 2>&1 |egrep -i upnp    
open("/lib64/tls/x86_64/libminiupnpc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib64/tls/libminiupnpc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib64/x86_64/libminiupnpc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib64/libminiupnpc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib64/tls/x86_64/libminiupnpc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib64/tls/libminiupnpc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib64/x86_64/libminiupnpc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib64/libminiupnpc.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
mmap(NULL, 8392704, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 002:27:18/error - UPnP: Error loading UPNP library, version mismatch?
^C
```

**Comment by orignal** [comment]
А как это поправить в общем случае?

**Comment by evgkrsk** [comment]
Честно говоря, не знаю. Я не программист :-)

Обычно программы с библиотеками линкуются. С таким впервые сталкиваюсь.

**Comment by orignal** [comment]
Здесь проблема была в том,чтобы не тащить лишнюю зависимость с билдом.
Возможно надо переделать.

**Comment by evgkrsk** [comment]
Как пользователю, мне конечно нравится идея что i2pd не тянет libminiupnpc, но подхватывает, если она есть.

Но как администратора и паранойка несколько пугает список путей, по которым ищется libminiupnpc.so, который ещё неизвестно куда может указывать. Да и неочевидным становится, как заставить работать функционал upnp.

Я за то, чтобы динамически линковать бинарник i2pd с libminiupnpc.so.X.Y

**Comment by hagen-i2p** [comment]
Что за дистр такой? В devel-пакеты пихаются хидеры (.h/.hpp), и статические библиотеки (.a).
Возможно всякие полезные штуки, типа настроек для pkg-config'а.
Но вышеописанная идея с "симлинками отдельно" - это какое-то извращение.

Вот для примера:

```
me@localhost:~$ dpkg -L libgif4
/.
/usr
/usr/share
...
/usr/lib
/usr/lib/libgif.so.4.1.6
/usr/lib/libgif.so.4
/usr/lib/libgif.so.4.1
/usr/lib/libungif.so.4.1
/usr/lib/libungif.so.4
/usr/lib/libungif.so.4.1.6
me@localhost:~$ ls -l /usr/lib/libgif.so*
lrwxrwxrwx 1 root root    15 Окт 20  2012 /usr/lib/libgif.so.4 -> libgif.so.4.1.6
lrwxrwxrwx 1 root root    15 Окт 20  2012 /usr/lib/libgif.so.4.1 -> libgif.so.4.1.6
-rw-r--r-- 1 root root 36256 Окт 20  2012 /usr/lib/libgif.so.4.1.6
```

**Comment by evgkrsk** [comment]
В приведённом (мной) фрагменте видно, что ищется libminiupnpc.so (наверное, как то, что нашлось на стадии конфигурации). А он у меня принадлежит как раз devel-пакету:
```
evg@thinkpad ~ $rpm -qvl libminiupnpc-devel |grep libminiupnpc.so
lrwxrwxrwx    1 root    root               18 янв 24 22:06 /usr/lib64/libminiupnpc.so -> libminiupnpc.so.10
```
В то время как сама динамическая библиотека в другом пакете:
```
evg@thinkpad ~ $rpm -qvl libminiupnpc |grep libminiupnpc.so 
-rw-r--r--    1 root    root            64200 янв 24 22:06 /usr/lib64/libminiupnpc.so.1.9
lrwxrwxrwx    1 root    root               19 янв 24 22:06 /usr/lib64/libminiupnpc.so.10 -> libminiupnpc.so.1.9
```
Итого, для работы с UPNP на роутере требуется devel-пакет (или ручной симлинк).

Дистрибутив обычный, вот [этот](http://packages.altlinux.org/). Все основные RPM-дистрибутивы так делают (смотрю Fedora/RHEL), насколько понимаю уже много лет как.

**Comment by hagen-i2p** [comment]
А, этот-то. Это, извините, не "все основные rpm-дистрибутивы", а наши посконные и заслуженные велосипедостроители.

Однако, я кажется понял их мотивацию. .so - это на самом деле "любая версия либы".
Интерфейс у них будет почти гарантированно отличаться от версии к версии.
Поэтому обычно используют .so.X, а всё что после - это уже номера фиксов, не ломающих совместимость.
Надо будет исправить код, чтоб искал более специфичную версию либы.

@orignal, загрузку через dlopen так и будем оставлять или сделаем через обычную линковку + опцию при сборке, как для всех остальных?

**Comment by evgkrsk** [comment]
Я просто хотел сказать, что в Fedora/RHEL это делается точно также (я проверял) и странно, что этого ещё никто не зарепортил.

**Comment by orignal** [comment]
@hagen-i2p, думаю можно с опцией при компиляции сделать.

**Comment by orignal** [comment]
Сделал чтобы линковалось с бинарником если USE_UPNP=1
