### ISSUE TITLE
При завершении работы Windows версии - бьется базу netdb.

### ISSUE THREAD

**Issue by Niktka** [PurpleI2P/i2pd#343]
Система - Windows7. 
Версия i2pd - 2.3.0
Завершил i2pd при помощи комбинации клавиш Ctrl+C
При следующем запуске - crash с ошибкой:

error - Identity: Certificate length 12129 exceeds buffer length 608 terminate called after throwing an instance of 'std::length_error' what<>: basic_string::_S_create
This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information.

**Comment by orignal** [comment]
should be fixed
