### ISSUE TITLE
Mutex

### ISSUE THREAD

**Issue by AntonGG** [PurpleI2P/i2pd#344]
Сделай чтобы две копии не запускались, мелочь а приятно)

**Comment by xcps** [comment]
Иногда надо две копии запустить. Может ключ сделать такой.

**Comment by thekurych** [comment]
Запрещать запуск нескольких копий - плохая идея. Мало ли какие задачи на ум придут? Да и *nix среды изначально многопользовательские. Может, на сервере много пользователей, и каждый хочет свою версию запустить? Со своими портами и туннелями.
Избежать запуска копий можно средствами ОС. В линуксах, например, один из способов такой:
pgrep i2pd &>/dev/null || /usr/bin/i2pd

**Comment by hagen-i2p** [comment]
See DaemonLinux.cpp#L89

IMHO, this should be changed.

**Comment by l-n-s** [comment]
Две копии и так будет проблематично запусить, т.к. порты сервисов будут заняты и второй i2pd вывалит exception. Спасибо за предложение.
