### ISSUE TITLE
Плохо работает DNS

### ISSUE THREAD

**Issue by strannik-j** [PurpleI2P/i2pd#346]
Вчера собрал свежую версию, но как и прежде (я давно пользую сабж), весьма погано работает DNS. 
На текущий момент работают: forum.i2p, echelon.i2p, hq.postman.i2p, i2p2.i2p, tracker2.postman.i2p, i2host.i2p, inr.i2p, bob.i2p, freedomforum.i2p, no.i2p, anoncoin.i2p, stats.i2p

Не работают: flibusta.i2p (b32.i2p работает), freezone.i2p, direct.i2p, test.i2p, nnm-club.i2p, rus.i2p, lenta.i2p, speedtest.i2p, i2pbote.i2p, privacybox.i2p,progromore.i2p
и многие другие из списка активных на irn.i2p

Кстати, скорость, относительно java, довольно низкая. Что можно сделать?

**Comment by orignal** [comment]
Прописать в subscriptions.txt.
По поводу низкой скорости относительно джавы #318.
Как будет сделано - станет также.

**Comment by Genues** [comment]
Доброе время суток.
Я только начал осваивать эту загадочную i2p, прошу отнестись снисходительно.
Вот у меня тоже мало сайтов открываются, а что надо прописать subscriptions.txt?
Я залез в файлик addresses.csv, там вроде есть например тот же search.i2p, который не открывается при этом.

**Comment by orignal** [comment]
Да реальности может десятая часть из списка открывается.
Народ регистрирует, потом надоедает и бросают это дело, а адреса остаются.

**Comment by khumarahn** [comment]
ответил в #377 , хотя оно и закрыто
