### ISSUE TITLE
Пищит в динамики от большого количества сообщений в консоль. Отключение лога не работает.

### ISSUE THREAD

**Issue by Niktka** [PurpleI2P/i2pd#349]
OS - Windows 7.
Через какое-то время после запуска, при большом количестве соединений в консоль выводится слишком много системных сообщений. От этого ОСь пищит.
Отключение логгирования - хоть -log=0 хоть -log=1 не работает. Лог-файл не создаётся. Сообщения по-прежнему сыплются в консоль.

**Comment by orignal** [comment]
параметр -log=1 будет заставлять писать в файл, а не на консоль
