### ISSUE TITLE
error - NTCP: Read error: Unknown error 158

### ISSUE THREAD

**Issue by gxcreator** [PurpleI2P/i2pd#351]
Faced this issue while running i2pd on openWrt (158 == boost::asio::error::operation_aborted)
Is that means operation was cancelled by i2pd process? 
Should it be uncommented?

```
    void NTCPSession::HandleReceived (const boost::system::error_code& ecode, std::size_t bytes_transferred)
    {
        if (ecode)
        {
            LogPrint (eLogInfo, "NTCP: Read error: ", ecode.message ());
            if (!m_NumReceivedBytes) m_Server.Ban (m_ConnectedFrom);
            //if (ecode != boost::asio::error::operation_aborted)
                Terminate ();
        }
```

**Comment by orignal** [comment]
"operation_aborted" means socket got closed explicitly but calling "close" somewhere. Why Terminate must be invoke even in this case, I need to remember the reason.
