### ISSUE TITLE
[FR] Возможность переоткрыть лог-файл на ходу

### ISSUE THREAD

**Issue by evgkrsk** [PurpleI2P/i2pd#355]
Нужна возможность сказать демону "Мы ротировал лог-файл, открой его заново". Без даунтайма. Сейчас для этого приходится демон рестартовать.

Обычно такое делают обработкой сигнала (SIGHUP, SIGUSR1, SIGUSR2, ...).

**Comment by orignal** [comment]
Что требуется? По сигналу закрыть предыдущий и открыть его заново?

**Comment by evgkrsk** [comment]
Я так понимаю, да.
