### ISSUE TITLE
Сломали конфигурацию

### ISSUE THREAD

**Issue by thekurych** [PurpleI2P/i2pd#356]
Последние коммиты сломали возможность конфигурирования.
1). Несмотря на явное указание конфигурационного файла, i2pd при запуске игнорирует его.
```
$ /usr/bin/i2pd --conf=/var/lib/i2pd/i2pd.conf --service --pidfile=/run/i2pd/i2pd.pid
11:22:02/info - i2pd v2.3.0 starting
11:22:02/debug - FS: main config file:
11:22:02/debug - FS: tunnels config: /var/lib/i2pd/tunnels.cfg
11:22:02/debug - FS: data directory: /var/lib/i2pd
11:22:03/info - Log: min messages level set to info
11:22:03/info - Daemon: starting HTTP Server at 127.0.0.1:7070
```
Если запускать как указано в i2pd --help (--conf file - без знака "="), то получаем ошибку
```
args: unknown option -- /var/lib/i2pd/i2pd.conf
args: unknown option -- /run/i2pd/i2pd.pid
```
2). Непонятно, что указывать теперь в --log: это переключатель, или же, все-таки, 0/1, или yes/no? В документации и в примерах конфигурации неоднозначности.
3). Косметическое замечание: b1cc1db967 коммит вроде бы должен быть в 2.4.0, а в лог выдает 2.3.0:
```
11:22:02/info - i2pd v2.3.0 starting
```

**Comment by hagen-i2p** [comment]
2), 3) -- fixed, pls re-check 1)
