### ISSUE TITLE
Ошибки связывания....

### ISSUE THREAD

**Issue by majioa** [PurpleI2P/i2pd#372]
Пытаюсь собрать i2pd в altlinux p7. Компиляция проходит нормально, однако на этапе связывания вылазят множественные ошибки:

    CMakeFiles/i2pd.dir/usr/local/home/majioa/git/i2pd/Daemon.cpp.o: In function `i2p::util::Daemon_Singleton::IsService() const':
    Daemon.cpp:(.text+0x18e2): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
    CMakeFiles/i2pd.dir/usr/local/home/majioa/git/i2pd/Daemon.cpp.o: In function `bool i2p::config::GetOption<bool>(char const*, bool&)':
    Daemon.cpp:(.text._ZN3i2p6config9GetOptionIbEEbPKcRT_[_ZN3i2p6config9GetOptionIbEEbPKcRT_]+0x92): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
    CMakeFiles/i2pd.dir/usr/local/home/majioa/git/i2pd/Daemon.cpp.o: In function `bool i2p::config::GetOption<unsigned short>(char const*, unsigned short&)':
    Daemon.cpp:(.text._ZN3i2p6config9GetOptionItEEbPKcRT_[_ZN3i2p6config9GetOptionItEEbPKcRT_]+0x92): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
    CMakeFiles/i2pd.dir/usr/local/home/majioa/git/i2pd/Daemon.cpp.o: In function `bool i2p::config::GetOption<std::string>(char const*, std::string&)':
    Daemon.cpp:(.text._ZN3i2p6config9GetOptionISsEEbPKcRT_[_ZN3i2p6config9GetOptionISsEEbPKcRT_]+0x92): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
    CMakeFiles/i2pd.dir/usr/local/home/majioa/git/i2pd/Daemon.cpp.o: In function `bool i2p::config::GetOption<char>(char const*, char&)':
    Daemon.cpp:(.text._ZN3i2p6config9GetOptionIcEEbPKcRT_[_ZN3i2p6config9GetOptionIcEEbPKcRT_]+0x92): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
    libi2pd.a(Config.cpp.o): In function `i2p::config::old_syntax_parser(std::string const&)':
    Config.cpp:(.text+0x763): undefined reference to `boost::program_options::options_description::find_nothrow(std::string const&, bool, bool, bool) const'
    Config.cpp:(.text+0x962): undefined reference to `boost::program_options::options_description::find_nothrow(std::string const&, bool, bool, bool) const'
    libi2pd.a(Config.cpp.o): In function `i2p::config::Init()':
    Config.cpp:(.text+0x119a): undefined reference to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
    Config.cpp:(.text+0x17e4): undefined reference to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
    Config.cpp:(.text+0x1930): undefined reference to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
    Config.cpp:(.text+0x1add): undefined reference to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
    Config.cpp:(.text+0x1c9a): undefined reference to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
    libi2pd.a(Config.cpp.o):Config.cpp:(.text+0x1de7): more undefined references to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)' follow
    libi2pd.a(Config.cpp.o): In function `boost::program_options::typed_value<bool, char>::xparse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&) const':
    Config.cpp:(.text._ZNK5boost15program_options11typed_valueIbcE6xparseERNS_3anyERKSt6vectorISsSaISsEE[_ZNK5boost15program_options11typed_valueIbcE6xparseERNS_3anyERKSt6vectorISsSaISsEE]+0x26): undefined reference to `boost::program_options::validate(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool*, int)'
    libi2pd.a(Config.cpp.o): In function `boost::program_options::typed_value<std::string, char>::xparse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&) const':
    Config.cpp: (.text._ZNK5boost15program_options11typed_valueISscE6xparseERNS_3anyERKSt6vectorISsSaISsEE[_ZNK5boost15program_options11typed_valueISscE6xparseERNS_3anyERKSt6vectorISsSaISsEE]+0x26): undefined reference to `boost::program_options::validate(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, std::string*, int)'
    libi2pd.a(Config.cpp.o): In function `boost::program_options::validation_error::validation_error(boost::program_options::validation_error::kind_t, std::string const&, std::string const&, int)':
    Config.cpp:(.text._ZN5boost15program_options16validation_errorC2ENS1_6kind_tERKSsS4_i[_ZN5boost15program_options16validation_errorC5ENS1_6kind_tERKSsS4_i]+0x20): undefined reference to `boost::program_options::validation_error::get_template(boost::program_options::validation_error::kind_t)'
    Config.cpp:(.text._ZN5boost15program_options16validation_errorC2ENS1_6kind_tERKSsS4_i[_ZN5boost15program_options16validation_errorC5ENS1_6kind_tERKSsS4_i]+0x30): undefined reference to `boost::program_options::error_with_option_name::error_with_option_name(std::string const&, std::string const&, std::string const&, int)'
    libi2pd.a(Config.cpp.o): In function `boost::program_options::basic_parsed_options<char> boost::program_options::parse_command_line<char>(int, char const* const*, boost::program_options::options_description const&, int, boost::function1<std::pair<std::string, std::string>, std::string const&>)':
    Config.cpp:(.text._ZN5boost15program_options18parse_command_lineIcEENS0_20basic_parsed_optionsIT_EEiPKPKS3_RKNS0_19options_descriptionEiNS_9function1ISt4pairISsSsERKSsEE[_ZN5boost15program_options18parse_command_lineIcEENS0_20basic_parsed_optionsIT_EEiPKPKS3_RKNS0_19options_descriptionEiNS_9function1ISt4pairISsSsERKSsEE]+0x1aa): undefined reference to `boost::program_options::to_internal(std::string const&)'
    Config.cpp:(.text._ZN5boost15program_options18parse_command_lineIcEENS0_20basic_parsed_optionsIT_EEiPKPKS3_RKNS0_19options_descriptionEiNS_9function1ISt4pairISsSsERKSsEE[_ZN5boost15program_options18parse_command_lineIcEENS0_20basic_parsed_optionsIT_EEiPKPKS3_RKNS0_19options_descriptionEiNS_9function1ISt4pairISsSsERKSsEE]+0x280): undefined reference to `boost::program_options::detail::cmdline::cmdline(std::vector<std::string, std::allocator<std::string> > const&)'
    Config.cpp:(.text._ZN5boost15program_options18parse_command_lineIcEENS0_20basic_parsed_optionsIT_EEiPKPKS3_RKNS0_19options_descriptionEiNS_9function1ISt4pairISsSsERKSsEE[_ZN5boost15program_options18parse_command_lineIcEENS0_20basic_parsed_optionsIT_EEiPKPKS3_RKNS0_19options_descriptionEiNS_9function1ISt4pairISsSsERKSsEE]+0x3c5): undefined reference to `boost::program_options::detail::cmdline::set_additional_parser(boost::function1<std::pair<std::string, std::string>, std::string const&>)'
    libi2pd.a(Config.cpp.o): In function `boost::program_options::typed_value<char, char>::name() const':
    Config.cpp:(.text._ZNK5boost15program_options11typed_valueIccE4nameEv[_ZNK5boost15program_options11typed_valueIccE4nameEv]+0x26): undefined reference to `boost::program_options::arg'
    libi2pd.a(Config.cpp.o): In function `boost::program_options::typed_value<unsigned short, char>::name() const':
    Config.cpp:(.text._ZNK5boost15program_options11typed_valueItcE4nameEv[_ZNK5boost15program_options11typed_valueItcE4nameEv]+0x26): undefined reference to `boost::program_options::arg'
    libi2pd.a(Config.cpp.o): In function `boost::program_options::typed_value<std::string, char>::name() const':
    Config.cpp:(.text._ZNK5boost15program_options11typed_valueISscE4nameEv[_ZNK5boost15program_options11typed_valueISscE4nameEv]+0x26): undefined reference to `boost::program_options::arg'
    libi2pd.a(Config.cpp.o): In function `boost::program_options::typed_value<bool, char>::name() const':
    Config.cpp:(.text._ZNK5boost15program_options11typed_valueIbcE4nameEv[_ZNK5boost15program_options11typed_valueIbcE4nameEv]+0x26): undefined reference to `boost::program_options::arg'
    libi2pd.a(Config.cpp.o): In function `boost::program_options::typed_value<char, char>::xparse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&) const':
    Config.cpp:(.text._ZNK5boost15program_options11typed_valueIccE6xparseERNS_3anyERKSt6vectorISsSaISsEE[_ZNK5boost15program_options11typed_valueIccE6xparseERNS_3anyERKSt6vectorISsSaISsEE]+0x176): undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::string const&)'
    libi2pd.a(Config.cpp.o): In function `void boost::program_options::validate<unsigned short, char>(boost::any&, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, unsigned short*, long)':
    Config.cpp:(.text._ZN5boost15program_options8validateItcEEvRNS_3anyERKSt6vectorISbIT0_St11char_traitsIS5_ESaIS5_EESaIS9_EEPT_l[_ZN5boost15program_options8validateItcEEvRNS_3anyERKSt6vectorISbIT0_St11char_traitsIS5_ESaIS5_EESaIS9_EEPT_l]+0x695): undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::string const&)'
    libi2pd.a(Config.cpp.o):(.data.rel.ro._ZTVN5boost16exception_detail19error_info_injectorINS_15program_options20invalid_option_valueEEE[_ZTVN5boost16exception_detail19error_info_injectorINS_15program_options20invalid_option_valueEEE]+0x18): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
    libi2pd.a(Config.cpp.o):(.data.rel.ro._ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options20invalid_option_valueEEEEE[_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options20invalid_option_valueEEEEE]+0x1c): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
    libi2pd.a(Config.cpp.o):(.data.rel.ro._ZTVN5boost16exception_detail19error_info_injectorINS_15program_options16validation_errorEEE[_ZTVN5boost16exception_detail19error_info_injectorINS_15program_options16validation_errorEEE]+0x18): undefined reference to     `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
    libi2pd.a(Config.cpp.o):(.data.rel.ro._ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options16validation_errorEEEEE[_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options16validation_errorEEEEE]+0x1c): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
    libi2pd.a(Config.cpp.o):(.data.rel.ro._ZTVN5boost15program_options16validation_errorE[_ZTVN5boost15program_options16validation_errorE]+0x18): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
    libi2pd.a(Config.cpp.o):(.data.rel.ro._ZTVN5boost15program_options20invalid_option_valueE[_ZTVN5boost15program_options20invalid_option_valueE]+0x18): more undefined references to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const' follow
    libi2pd.a(Config.cpp.o):(.data.rel.ro._ZTVN5boost15program_options11typed_valueISscEE[_ZTVN5boost15program_options11typed_valueISscEE]+0x1c): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool) const'
    libi2pd.a(Config.cpp.o):(.data.rel.ro._ZTVN5boost15program_options11typed_valueItcEE[_ZTVN5boost15program_options11typed_valueItcEE]+0x1c): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool) const'
    libi2pd.a(Config.cpp.o):(.data.rel.ro._ZTVN5boost15program_options11typed_valueIbcEE[_ZTVN5boost15program_options11typed_valueIbcEE]+0x1c): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool) const'
    libi2pd.a(Config.cpp.o):(.data.rel.ro._ZTVN5boost15program_options11typed_valueIccEE[_ZTVN5boost15program_options11typed_valueIccEE]+0x1c): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool) const'
    libi2pd.a(Profiling.cpp.o): In function `unsigned short boost::date_time::month_str_to_ushort<boost::gregorian::greg_month>(std::string const&)':
    Profiling.cpp:(.text._ZN5boost9date_time19month_str_to_ushortINS_9gregorian10greg_monthEEEtRKSs[_ZN5boost9date_time19month_str_to_ushortINS_9gregorian10greg_monthEEEtRKSs]+0x13c): undefined reference to `boost::gregorian::greg_month::get_month_map_ptr()'
    libi2pdclient.a(HTTPProxy.cpp.o): In function `boost::re_detail::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::match_prefix()':
    HTTPProxy.cpp:(.text._ZN5boost9re_detail12perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcSsEESaINS_9sub_matchIS6_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE12match_prefixEv[_ZN5boost9re_detail12perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcSsEESaINS_9sub_matchIS6_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE12match_prefixEv]+0x133): undefined reference to `boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > >::maybe_assign(boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > > const&)'
    libi2pdclient.a(HTTPProxy.cpp.o): In function `bool boost::regex_search<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >(__gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>, boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > >&, boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags, __gnu_cxx::__normal_iterator<char const*, std::string>)':
    HTTPProxy.cpp:(.text._ZN5boost12regex_searchIN9__gnu_cxx17__normal_iteratorIPKcSsEESaINS_9sub_matchIS5_EEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEEEbT_SD_RNS_13match_resultsISD_T0_EERKNS_11basic_regexIT1_T2_EENS_15regex_constants12_match_flagsESD_[_ZN5boost12regex_searchIN9__gnu_cxx17__normal_iteratorIPKcSsEESaINS_9sub_matchIS5_EEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEEEbT_SD_RNS_13match_resultsISD_T0_EERKNS_11basic_regexIT1_T2_EENS_15regex_constants12_match_flagsESD_]+0xd5): undefined reference to `boost::re_detail::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
    libi2pdclient.a(HTTPProxy.cpp.o): In function `boost::re_detail::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::match_match()':
    HTTPProxy.cpp:(.text._ZN5boost9re_detail12perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcSsEESaINS_9sub_matchIS6_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE11match_matchEv[_ZN5boost9re_detail12perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcSsEESaINS_9sub_matchIS6_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE11match_matchEv]+0x182): undefined reference to `boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > >::maybe_assign(boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>,     std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > > const&)'
    collect2: ошибка: выполнение ld завершилось с кодом возврата 1
    make[2]: *** [i2pd] Ошибка 1
    make[1]: *** [CMakeFiles/i2pd.dir/all] Ошибка 2

Собирал таким:

    -- The C compiler identification is GNU 5.3.1
    -- The CXX compiler identification is GNU 4.9.2

Что  оное может значить?

**Comment by orignal** [comment]
Означает что буст линкуется не в той последлвательности.
Что происходит при компиляции с обычным Makefile-ом?

**Comment by majioa** [comment]
@orignal этот лог как раз после запуска `make`.

**Comment by orignal** [comment]
Попробовать поменять порядок здесь
https://github.com/PurpleI2P/i2pd/blob/openssl/Makefile.linux#L43
и здесь
https://github.com/PurpleI2P/i2pd/blob/openssl/Makefile#L60

**Comment by majioa** [comment]
@orignal  Проблема была видимо в несостыковке версий gcc (4 и 5). Все поставил на 4.9.5, теперь так, символ ему нужен из gcc 3.4:

    /usr/bin/ld: libi2pd.a(util.cpp.o): неопределённая ссылка на символ «_ZNSolsEPSt15basic_streambufIcSt11char_traitsIcEE@@GLIBCXX_3.4»
    /usr/lib/libstdc++.so.6: error adding symbols: DSO missing from command line
    collect2: ошибка: выполнение ld завершилось с кодом возврата 1
    make[2]: *** [i2pd] Ошибка 1
    make[1]: *** [CMakeFiles/i2pd.dir/all] Ошибка 2

**Comment by orignal** [comment]
Надо правильный путь к либам прописать через -L.
Который стоит первым - там и будет искать в первую очередь.
