### ISSUE TITLE
where should I put I2CP parameters in?

### ISSUE THREAD

**Issue by XL2014** [PurpleI2P/i2pd#374]
https://github.com/PurpleI2P/i2pd/wiki/tunnels.cfg

> I2CP parameter are common for all tunnel types and specify setting for a local destination.
> 
> 'inbound.length' - number of hops of an inbound tunnel. 3 by default
> 'outbound.length' - number of hops of an outbound tunnel. 3 by default
> 'inbound.quantity' - number of inbound tunnels. 5 by default
> 'outbound.quantity' - number of outbound tunnels. 5 by default
> 'crypto.tagsToSend' - number of ElGamal/AES tags to send. 40 by default 

where should I put these parameters in?

I tried 
> [http-in]
> type = http
> host = website.i2p
> port = 80
> keys = our-website.dat
> inbound.length = 1
> outbound.length = 1

but does not work....
thank you so much.....

**Comment by orignal** [comment]
it should work. why do you think it doesn't?
Here is my config
type=http
host=127.0.0.1
port=80
inport=80
keys=site.dat
inbound.length=1
outbound.length=1
inbound.quantity=3
outbound.quantity=3
crypto.tagsToSend=20

And I see 1 hops tunnels there.
However I see something wrong in your config
host = website.i2p
Unless you have a record in /ects/hosts it goes nowhere

**Comment by XL2014** [comment]
my fault.. I forgot to set --tunconf=
