### ISSUE TITLE
Азбука Морзе в Windows версии

### ISSUE THREAD

**Issue by Agagamand** [PurpleI2P/i2pd#375]
Несколько напрягает черезмерная информативность i2pd. Мало того что он в консоль выводит слишком много информации, так когда её становится ещё больше (к примеру, при скачивании с imule), i2pd переходит на новый уровень - расказывает пользователю о том, что он делает с помощью азбуки Морзе. Вот, послушайте http://rghost.ru/6PPqJf7gX Спасает только отлючение системных звуков.

**Comment by orignal** [comment]
Известная проблема что валится мусор на консоль. 
Не было времени разобраться откуда он берется.
Можно кстати запускать с параметров --log=file тогда сообщения пойдут в файл но от мусора это не избавляет.

**Comment by Agagamand** [comment]
Хотелось бы команду полностью отключающую вывод информации (и в консоль и в файл), для простого смертного она всё равно бесполезна.

**Comment by orignal** [comment]
Так в консоль в этом случае не должно ничего выводиться. Это бага.

**Comment by Agagamand** [comment]
Ещё хотел бы пожаловатся на две ошибки:
1. При использовании i2pd imule почему-то подключается к сети в разы дольше, чем при использовании официальной реализации i2p.
2. Если запущен imule, то i2pd через некоторое время просто молча закрывается. Пока что несмог точно выявить условия для воспроизведения ошибки, однако полагаю что её провоцируют множественные одновременные скачивания в imule (от 5 файлов и выше).

**Comment by orignal** [comment]
2. А под gdb нельзя запустить чтобы увидеть на чем падает?

**Comment by Agagamand** [comment]
Я не знаю ни что такое этот gdb, ни как под ним что-то запустить.

**Comment by orignal** [comment]
хорошо. тогда набор ed2k линков на которых падает.
А то там в imule обычно все мертвое

**Comment by Agagamand** [comment]
На самом деле по запросу всякой попсы, вроде "eminem", "simpsons", "Gameof thrones" файлы находятся практически всегда. Но так чтобы сразу много скачивалось, должно повезти.

**Comment by orignal** [comment]
С параметром --log=file теперь мусор выводиться не будет, но до источника проблемы пока не докопался.
