### ISSUE TITLE
Cannot make static ip2d on Fedora23

### ISSUE THREAD

**Issue by jrthwk** [PurpleI2P/i2pd#379]
Help me please.
I wan to build static binary i2pd for machine with centos6.
I try to build that on the fedora23.
cmake gcc gcc-c++ - has been inslalled and latest version.
boost-devel, openssl-devel  has been installed  and latest version.

With option(WITH_STATIC    "Static build" OFF) - i2pd compiled ok.
When i set up option(WITH_STATIC    "Static build" ON) it shows error below.:

 cmake -DCMAKE_BUILD_TYPE=Release

-- Performing Test CXX11_SUPPORTED
-- Performing Test CXX11_SUPPORTED - Success
-- Performing Test CXX0X_SUPPORTED
-- Performing Test CXX0X_SUPPORTED - Success
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
CMake Error at /usr/share/cmake/Modules/FindBoost.cmake:1247 (message):
  Unable to find the requested Boost libraries.
  Boost version: 1.58.0
  Boost include path: /usr/include
  Could not find the following static Boost libraries:
          boost_system
          boost_filesystem
          boost_regex
          boost_program_options
          boost_date_time
  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  CMakeLists.txt:237 (find_package)
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES) (found
  version "1.0.2f")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindOpenSSL.cmake:357 (find_package_handle_standard_args)
  CMakeLists.txt:242 (find_package)
-- Configuring incomplete, errors occurred!
See also "/1/i2pd-openssl/build/CMakeFiles/CMakeOutput.log".
See also "/1/i2pd-openssl/build/CMakeFiles/CMakeError.log".

**Comment by orignal** [comment]
static build doesn't work due some systems calls. will be fixed later
