### ISSUE TITLE
Proposal: Create official Docker image for i2pd

### ISSUE THREAD

**Issue by l-n-s** [PurpleI2P/i2pd#382]
Docker image could be very useful for 3rd party app developers (for example, Retroshare or torrent clients), also for some service operators

https://hub.docker.com/explore/
https://github.com/docker-library/official-images <-- Official Docker images repo

https://github.com/docker-library/php/blob/b4aeb948e2e240c732d78890ff03285b16e8edda/5.6/Dockerfile <-- Good example of Docker file (official docker image of php)

**Comment by l-n-s** [comment]
@hideman-ltd orignal said you have great Docker experience, can you help us with that issue?

**Comment by hideman-ltd** [comment]
i'll be on irc today and we will talk about it.
