### ISSUE TITLE
Can't make i2pd under centos6 with devtoolset.

### ISSUE THREAD

**Issue by jrthwk** [PurpleI2P/i2pd#390]
Can't make i2pd under centos6 with devtoolset:
I'd install devtoolset and export paths:

export CC=/opt/centos/devtoolset-1.1/root/usr/bin/gcc
export CPP=/opt/centos/devtoolset-1.1/root/usr/bin/cpp
export CXX=/opt/centos/devtoolset-1.1/root/usr/bin/c++

cmake  -DCMAKE_BUILD_TYPE=Release  -DBoost_NO_BOOST_CMAKE=BOOL:ON

-- Performing Test CXX11_SUPPORTED
-- Performing Test CXX11_SUPPORTED - Success
-- Performing Test CXX0X_SUPPORTED
-- Performing Test CXX0X_SUPPORTED - Success
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Boost version: 1.41.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   regex
--   program_options
--   date_time
-- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.1e")
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.3")
-- ---------------------------------------
-- Build type         : Release
-- Compiler vendor    : GNU
-- Compiler version   : 4.7.2
-- Compiler path      : /opt/centos/devtoolset-1.1/root/usr/bin/c++
-- Install prefix:    : /usr/local
-- Options:
--   AESNI            : OFF
--   HARDENING        : OFF
--   LIBRARY          : OFF
--   BINARY           : ON
--   STATIC BUILD     : OFF
--   UPnP             : OFF
--   PCH              : OFF
-- ---------------------------------------
-- Configuring done
-- Generating done
-- Build files have been written to: /home/media/media/wget/4/i2pd-openssl/build

[root@linux build]# make
Scanning dependencies of target libi2pd
[  2%] Building CXX object CMakeFiles/libi2pd.dir/home/media/media/wget/4/i2pd-openssl/NetDb.cpp.o
/home/media/media/wget/4/i2pd-openssl/NetDb.cpp: In member function 'void i2p::data::NetDb::Load()':
/home/media/media/wget/4/i2pd-openssl/NetDb.cpp:316:46: error: invalid initialization of reference of type 'const string& {aka const std::basic_string<char>&}' from expression of type 'const boost::filesystem::basic_path<std::basic_string<char>, boost::filesystem::path_traits>'
make[2]: *** [CMakeFiles/libi2pd.dir/home/media/media/wget/4/i2pd-openssl/NetDb.cpp.o] Error 1
make[1]: *** [CMakeFiles/libi2pd.dir/all] Error 2
make: *** [all] Error 2

**Comment by orignal** [comment]
Try regular Makefile

**Comment by jrthwk** [comment]
Error all the same:


export CC=/opt/centos/devtoolset-1.1/root/usr/bin/gcc
export CPP=/opt/centos/devtoolset-1.1/root/usr/bin/cpp
export CXX=/opt/centos/devtoolset-1.1/root/usr/bin/c++
make

mkdir -p obj
/opt/centos/devtoolset-1.1/root/usr/bin/c++ -g -Wall -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/Crypto.o Crypto.cpp
/opt/centos/devtoolset-1.1/root/usr/bin/c++ -g -Wall -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/Datagram.o Datagram.cpp
/opt/centos/devtoolset-1.1/root/usr/bin/c++ -g -Wall -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/Garlic.o Garlic.cpp
/opt/centos/devtoolset-1.1/root/usr/bin/c++ -g -Wall -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/I2NPProtocol.o I2NPProtocol.cpp
/opt/centos/devtoolset-1.1/root/usr/bin/c++ -g -Wall -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/LeaseSet.o LeaseSet.cpp
/opt/centos/devtoolset-1.1/root/usr/bin/c++ -g -Wall -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/Log.o Log.cpp
/opt/centos/devtoolset-1.1/root/usr/bin/c++ -g -Wall -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/NTCPSession.o NTCPSession.cpp
/opt/centos/devtoolset-1.1/root/usr/bin/c++ -g -Wall -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/NetDb.o NetDb.cpp
NetDb.cpp: In member function 'void i2p::data::NetDb::Load()':
NetDb.cpp:316:46: error: invalid initialization of reference of type 'const string& {aka const std::basic_string<char>&}' from expression of type 'const boost::filesystem::basic_path<std::basic_string<char>, boost::filesystem::path_traits>'
make: *** [obj/NetDb.o] Error 1

**Comment by orignal** [comment]
which branch are you trying to build?

**Comment by majestrate** [comment]
can you give us the git revision you checked out?

``git show HEAD``

**Comment by hagen-i2p** [comment]
-- Boost version: 1.41.0

Use at least 1.49.0
