### ISSUE TITLE
Reseed improvements

### ISSUE THREAD

**Issue by hagen-i2p** [PurpleI2P/i2pd#396]
New config section requested: `reseed`. Example one:

``` ini
[reseed]
enabled = yes
# 'file' or 'http'
source = http
# for 'http' - file with list of urls
hosts = subscriptions.txt
# for 'file' - path to user's .su3 file
file = hosts.su3
# if set - fetch files using http proxy
proxyaddress = 127.0.0.1
proxyport = 8080
```

All parameters above is subject of change. Discuss.

**Comment by orignal** [comment]
We don't need 'enabled' because it's always enabled.
hosts = subscriptions.txt
better to change to 
hosts = reseeds.txt

Should be option
proxy  = yes

**Comment by hagen-i2p** [comment]
It builds, but i've got the same warning:

```
/usr/lib/x86_64-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
(.text+0x11): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
libi2pd.a(Reseed.o): In function `boost::asio::detail::socket_ops::getaddrinfo(char const*, char const*, addrinfo const&, addrinfo**, boost::system::error_code&)':
/usr/include/boost/asio/detail/impl/socket_ops.ipp:3177: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```

**Comment by l-n-s** [comment]
@orignal is there a reason we keep reseed "hostnames" (which are in fact incomplete URLs) and file name separated in  `ReseedFromSU3`?

[This](https://github.com/PurpleI2P/i2pd/blob/openssl/Config.cpp#L168) and [this](https://github.com/PurpleI2P/i2pd/blob/openssl/Reseed.cpp#L55)

IMO function `ReseedFromSU3` should accept full URLs, so you could reseed from url like that:

    ./i2pd --reseed.urls https://legit-website.com/cute_cat.jpg

**Comment by orignal** [comment]
No specific reason, just how it was taken from Java
