### ISSUE TITLE
Setting "datadir" and "service" options in i2pd.conf has no effect

### ISSUE THREAD

**Issue by khumarahn** [PurpleI2P/i2pd#408]
This may be by design, but then it would be nice to have a note in the documentation.

**Comment by orignal** [comment]
it doesn't work as windows service at all, it will be removed soon

**Comment by khumarahn** [comment]
I have read the source code. The situation I am talking about appears on linux, if datadir is not set in the command line. Then datadir is detected before reading the config file, and if config file has "service = 1", this is not used.

**Comment by khumarahn** [comment]
In fact, datadir is always set before reading the config file, so datadir in config file is also not used.

**Comment by orignal** [comment]
yes, that's bug

**Comment by p4bl0-** [comment]
I can confirm that I have this same behavior with 2.9.0 on Debian.

**Comment by r4sas** [comment]
Requesting current state of that problem.

**Comment by l-n-s** [comment]
I think we can just explicitly define this behavior in documentation and close the issue.

**Comment by l-n-s** [comment]
updated docs and example config file
