### ISSUE TITLE
Как изменить путь к Data Dir?

### ISSUE THREAD

**Issue by r44083** [PurpleI2P/i2pd#411]
Не понятно как задать свой собственный (желательно относительный) путь к Data Dir.

Я пробовал ключ ```--datadir=%~dp0```, а также пробовал указывать абсолютный путь вида 
``` --datadir=D:\i2pd ```, но это не даёт никакого результата.

Путь к Data Dir по прежнему ```C:\users\ИМЯ_ПОЛЬЗОВАТЕЛЯ\AppData\Roaming\i2pd```.

**Comment by orignal** [comment]
По виндой что ли? Может и не работать. Разберемся

**Comment by mlt** [comment]
По мне так всё работает. `--datadir=.` создаёт всё в исходном каталоге.

**Comment by r44083** [comment]
Я пробую запускать i2pd версии 2.3 из консоли следующим образом ```i2pd --datadir=.``` и ничего не меняется (в папке с i2p ничего не создаётся, но зато он лезит в пользовательскую папку с создаёт там datadir). Что я делаю не так?
Вот скриншот:

![](https://habrastorage.org/files/8b2/0cc/a20/8b20cca205914e21a62e546cb7f92269.jpg "Лог консоли")

**Comment by orignal** [comment]
Так в 2.3 этого еще не было. Сейчас уже 2.5

**Comment by r44083** [comment]
Попробовал на 2.5.1 версии и всё получилось.
Но при запуске через консоль не отображается лог, то есть при запуске появляется пустое GUI окошко.
i2pd уже не консольный?

**Comment by orignal** [comment]
Уже нет. Лог теперь в data dir.
Есть возможность собирать как консольное приложение, если нужно.

**Comment by r44083** [comment]
Понятно. А почему вы по умолчанию отказываетесь от консоли в выкладываемых на сайте билдах?

**Comment by orignal** [comment]
Потому что она многим не нравилась.
Если нужно я могу счас собрать и выложить туда.

**Comment by r44083** [comment]
Было бы неплохо (с пометочкой CLI).
А в чём разница между "i2pd_2.5.1_win32_mingw.zip" и "i2pd_2.5.1_win32_mingw_aesni.zip"?

**Comment by orignal** [comment]
первый это для всех, а второй для процессоров с AESNI
счас соберу

**Comment by orignal** [comment]
http://i2pd.website/releases/2.5.1/i2pd_2.5.1_win32_mingw_cli.zip

**Comment by r44083** [comment]
Спасибо вам большое.
