### ISSUE TITLE
Как попасть в веб-интерфейс i2p роутера?

### ISSUE THREAD

**Issue by Lichtenshtein** [PurpleI2P/i2pd#415]
Извиняюсь за нубский вопрос. Установил пакет i2pd на роутере и не могу попасть в его веб-интерфейс с основной локальной машины. Что надо прописать в конфиге? Мне надо зайти с адреса 192.168.1.18 в локальной сети, я пробовал например прописать http.address=192.168.1.1, http.port=7070 и потом подключиться через 192.168.1.1:7070, но у меня ничего не выходит.

**Comment by gxcreator** [comment]
http.address=192.168.1.0 или http.address=0.0.0.0

**Comment by orignal** [comment]
в конфиге или командной строке? 
в конфиге 
[http]
address

В командной строке --http.address

**Comment by Lichtenshtein** [comment]
Не получается. Пробовал и так и сяк прописывать адрес, пробовал в конфиге /opt/etc/i2p.conf   прописывать как показано выше - не открывается. Пробовал в командной строке указывать путь к конфигу - ничего не выходит. Роутер Xiaomi-Mi Mini с прошивкой Padavan, процессор загружается на 100%.

**Comment by orignal** [comment]
а в ~/.i2pd/i2p.conf ?

**Comment by Lichtenshtein** [comment]
Файл конфига создаётся в /opt/etc/, я и его пробовал редактировать, но это тоже ничего не дало. Data dir находится в /opt/var/i2pd, скопировал конфиг туда - ничего. Указал на него в консоли - опять ничего. Как-будто ни консольные команды, ни конфиги программой не воспринимаются..
```
16:51:08/info - Version 2.2.0
16:51:08/info - data directory: /opt/var/i2pd
16:51:08/info - CMD parameters:
16:51:08/info - 0  i2pd
16:51:08/info - 1  -–conf=/opt/var/i2pd/i2p.conf
```

**Comment by mlt** [comment]
> Version 2.2.0

Много чего поменялось с тех пор. Надо бы обновиться.

**Comment by orignal** [comment]
Точнее поменялось все

**Comment by Lichtenshtein** [comment]
Понятно... Видимо репозиторий entware обновляется нечасто. Последняя и единственная доступная версия под mipsel - 2.2.0, других просто нет.

**Comment by mlt** [comment]
Я было обрадовался что у них сборки с musl есть... Всегда можно PR отправить или тикет создать https://github.com/Entware/rtndev/issues

**Comment by Lichtenshtein** [comment]
Спасибо, оставил реквест на обновление.

**Comment by orignal** [comment]
Тогда для старых конфигурации
https://github.com/PurpleI2P/i2pd/blob/6d8b0e3a5d0df673f85c1f1a389eaea03513d24d/docs/configuration.md

**Comment by Lichtenshtein** [comment]
Хм. А теперь ему что нужно?
<a href="https://imgdepo.com/show/9113235" target="_blank"><img src="http://imgdepo.com/thumb/2016/Mar/28/ee8c9abc.jpg"/></a>

**Comment by ryzhovau** [comment]
i2pd в Entware-ng [обновлён](https://github.com/Entware-ng/rtndev/commit/22933122d65168c078b4ac1ed99aa502c55e492b) до последней версии. Видимо, эту issue можно закрыть.

**Comment by orignal** [comment]
@ryzhovau что там с производительностью?

**Comment by ryzhovau** [comment]
В двух последних релизах значительно веселее, чем раньше. Два-три наиболее популярных сайта, вроде флибусты открываются в ста процентах случаев. Гораздо меньше стало отвалов туннелей по таймаутам. На Zyxel Keenetic Ultra II (MIPS, 800MHz, 2 cores, 256MB RAM) работающего в фоне `i2pd` не чувствуется. 

![Статистика](http://forum.keenetic.net/uploads/monthly_2016_05/57849a58378c4_.PNG.734e94b07a38540b4582d0038abf560b.PNG)

Если нужны будут какие-нибудь специфичные тесты дай знать, потому что я кроме подкладывания addressbook я ничего для запуска демона не настраивал.

**Comment by orignal** [comment]
Я вот про это https://github.com/PurpleI2P/i2pd/issues/345
С тех пор было много по этой части переделано, но там никто не ответил как повлияли измненения на работу на OpenWrt. Вот теперь знаю :)
