### ISSUE TITLE
Aggregation of features present in i2prouter and missing in i2pd

### ISSUE THREAD

**Issue by Adonai** [PurpleI2P/i2pd#422]
Don't know whether this issue is created already.

- From Wiki I do know that the only torrent client compatible with i2pd is Robert.
What is the reason of this?

- I also don't see anywhere whether i2pd can be used for i2p IRC servers.
Is there any possibility?

**Comment by Adonai** [comment]
Please close it if it's already tracked somewhere or add related labels if not

**Comment by orignal** [comment]
1. Because I2CP is not implemented
2. Yes. See specs https://github.com/PurpleI2P/i2pd/wiki/tunnels.cfg#serverirc-tunnels.  
walker.i2p is i2pd's IRC server
