### ISSUE TITLE
Add possibility to log to syslog

### ISSUE THREAD

**Issue by Faruduvawe** [PurpleI2P/i2pd#423]
It will be useful if i2pd could log to syslog instead of file and stout only.

**Comment by orignal** [comment]
@hagen-i2p can we do it?

**Comment by mlt** [comment]
And on Windows, it would be nice to use Event Log. :+1: for boost log #234

**Comment by hagen-i2p** [comment]
I vote against boost logs -- it's too bloat for such simple task. Another point is requirement of boost > 1.54.

Upgrade of current system will be preferrable.

**Comment by mlt** [comment]
@hagen-i2p Sooner or later even <del>Debian</del> conservative distros will catch up on boost version. Reinventing the universal logging It is like rowing against the flow - just more stuff to maintain. As I mentioned in 234, it can be ifdef'ed with existing logging mechanism by default, so no one gets hurt, but whomever wants can use boost logging.

**Comment by hagen-i2p** [comment]
@mlt The most annoying thing in each new projects trying to become "killer-of-X"* is requirement of newest of even development versions of libraries. It may be funny for developer, but it is not fucking funny for end-user, which have to upgrade his system twice in week.

Do you think he definitely does that? 50% chance that he just throw away your software without install. Tox is good example.

My point is keeping compatibility with old systems as long as possible.

* Where X is skype, telegram, dropbox, <whatever>.

**Comment by majestrate** [comment]
@hagen-i2p has a good point and syslog is a function you can call in place of printf, not sure about window's eventlog.

excerpt from man 3 syslog:

    void syslog(int priority, const char *format, ...);
