### ISSUE TITLE
Что такое 'NTCP or SSU addresses available'? Как узнать состояние сети?

### ISSUE THREAD

**Issue by ernado** [PurpleI2P/i2pd#430]
```
Mar 21 13:22:43 nexus i2pd[1704]: 13:22:41/error - Transports: No NTCP or SSU addresses available
Mar 21 13:22:43 nexus i2pd[1704]: 13:22:41/error - NTCP: Connect error: Connection timed out
```

1. Это глобальная ошибка или в контексте подключения к кому-то?
2. Как узнать статус своего подключения? У меня проброшены порты и статический IPv4, доступный извне (и IPv6 через 6to4), но я не уверен, насколько хорошо работает всё.

`i2pd v2.5.1, Ubuntu 16.04 x64, Linux 4.4.0-14`

![screenshot from 2016-03-21 13-28-48](https://cloud.githubusercontent.com/assets/866677/13915977/e2bbf16c-ef68-11e5-9fbc-83caac6c2eab.png)

_Еще для интереса:
16GB RAM, SSD, AMD FX 8320;
Memory: 38MB
CPU: 12-14% of 1 core_

**Comment by orignal** [comment]
1. Это не ошибка. Просто не удалось достучаться до  определнного узла
2. Status: OK. Все прекрасно

**Comment by ernado** [comment]
Спасибо за ответ.
Такой success rate нормален?
Если бы не получилось port-forwarding, то статус был бы другой?

**Comment by orignal** [comment]
33% это отличный рейт для i2pd
Статус был бы Firewalled
