### ISSUE TITLE
How am I'm supposed to enable the IRC in the new versions of i2pd?

### ISSUE THREAD

**Issue by shackra** [PurpleI2P/i2pd#434]
I cannot understand what to do :-/

I wrote on `i2pd.conf`:

```
[IRC]
enabled = true
```

and this on tunnels.cfg:

```
[IRC]
type = client
address = 127.0.0.1
port = 6668
destination = irc.postman.i2p
keys = irc-keys.dat
```

but I get this from starting i2pd:

```
 unrecognised option '%canonical_option%'
```

**Comment by majestrate** [comment]
the entery in i2pd.conf is not needed I believe

**Comment by orignal** [comment]
In tunnels.i2p only

**Comment by shackra** [comment]
@majestrate seems like the solution to my issue. My IRC client can't stablish a connection though:

```
* Connecting to localhost.localdomain (::1:6668)
* Connection failed (connection refused)
```

@orignal is okay if I just use the generic tunnel or am I'm to expect failure with the connection to any IRC server?

**Comment by majestrate** [comment]
looks like your irc client is trying ipv6 first and it fails since the tunnel is bound to ipv4 loopback.

**Comment by shackra** [comment]
Oh, if that's the case maybe I can fix that quickly.

El jueves 24 de marzo del 2016 a las 1407 horas, Jeff escribió:

> looks like your irc client is trying ipv6 first and it fails since the tunnel is bound to ipv4 loopback.
>
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/PurpleI2P/i2pd/issues/434#issuecomment-200999044


-- 
👋 Pax et bonum.
Jorge Araya Navarro
https://es.gravatar.com/shackra
