### ISSUE TITLE
crash in i2p::transport::Transports::HandleNTCPResolve

### ISSUE THREAD

**Issue by maxis11** [PurpleI2P/i2pd#435]
Got a SIGSEGV in i2p::transport::Transports::HandleNTCPResolve
[backtrace.txt](https://github.com/PurpleI2P/i2pd/files/188734/backtrace.txt)
[log.txt](https://github.com/PurpleI2P/i2pd/files/188735/log.txt)

g++ -v: gcc version 5.3.1 20160320 (Ubuntu/Linaro 5.3.1-12ubuntu4)
i2pd version: 0.9.25(commit b28208d1bf6afdff97a5e7227c9f33a6a699ef61)

**Comment by orignal** [comment]
Try now

**Comment by maxis11** [comment]
За ночь ничего не отвалилось, а значит проблема, скорее всего, пофикшена. Поставлю днем на floodfill для тестирования и если до вечера все нормально будет, думаю тикет можно будет закрыть

**Comment by maxis11** [comment]
Проблема решена
