### ISSUE TITLE
Graceful Shutdown upon a specific signal

### ISSUE THREAD

**Issue by manasb** [PurpleI2P/i2pd#445]
Hello,

I am not sure if this is possible already, I would like to run i2pd with no web interface and with configuration files only.

I am currently using ```kill -TERM $i2pd_pid``` and I don't know if this is a graceful shutdown. Is there a specific signal I can send so that i2pd shuts down gracefully?

Thanks

**Comment by orignal** [comment]
http://127.0.0.1:7070/?stop_accepting_tunnels
and shutdown after 10 minutes

**Comment by majestrate** [comment]
what about via SIGUSR1 or something for when running without web ui?

**Comment by orignal** [comment]
good point. let's agree on signals

**Comment by orignal** [comment]
Let's use SIGINT

**Comment by manasb** [comment]
Thanks, this makes it easier for me to manage multiple nodes.

**Comment by manasb** [comment]
Just tested this and it works beatifully. Thank you.
