### ISSUE TITLE
segfault after failing to open router.info

### ISSUE THREAD

**Issue by radfish** [PurpleI2P/i2pd#447]
On first run, if i2pd fails (for example due to syntax error in config file), it does not get to creating router.info, but does create router.keys. On second run, after fixing syntax error in config file, error happens: cannot open router.info AND i2pd segfaults. So, this issue is just to handle 'router.info not found' case without segfaulting.

**Comment by orignal** [comment]
Just delete router.keys for now.
Will be fixed

**Comment by radfish** [comment]
yeah, i did that, all good. Just wanted to report to put on todo fix list.

**Comment by hagen-i2p** [comment]
It's here:

```c++
	void RouterContext::Init ()
	{
		if (!Load ())
			CreateNewRouter ();
```

need more reliable way to detect loading RI from file.

**Comment by orignal** [comment]
fixed
