### ISSUE TITLE
gmake fails on FreeBSD 10.1

### ISSUE THREAD

**Issue by manasb** [PurpleI2P/i2pd#449]
% gmake
    clang++ -O2 -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -I/usr/include/ -I/usr/local/include/  -c -o obj/Crypto.o Crypto.cpp
    In file included from Crypto.cpp:13:
    ./Log.h:143:105: error: field of type 'std::thread::id' (aka 'std::__1::__thread_id') has private constructor
      ...LogMsg (LogLevel lvl, std::time_t ts, const std::string & txt): timestamp(ts), text(txt), level(lvl), tid(0) {};
                                                                                                               ^
    /usr/include/c++/v1/thread:229:5: note: declared private here
        __thread_id(pthread_t __id) : __id_(__id) {}
        ^
    1 error generated.
    Makefile:50: recipe for target 'obj/Crypto.o' failed
    gmake: *** [obj/Crypto.o] Error 1

This was compiling fine just a few hours ago.

The reference is to this line https://github.com/PurpleI2P/i2pd/blob/openssl/Log.h#L143

**Comment by manasb** [comment]
[commit 1fae3baaa3270081c68c645c1db03ecce9dc6d24](https://github.com/PurpleI2P/i2pd/commit/1fae3baaa3270081c68c645c1db03ecce9dc6d24)

**Comment by majestrate** [comment]
try https://github.com/PurpleI2P/i2pd/commit/68c789dceb905f02b3b4aaa543c4ef64e174d83e

**Comment by manasb** [comment]
https://github.com/PurpleI2P/i2pd/pull/451/commits/0a3c4f131e16ea2e44b826ddd3ab9fec13f7a680 doesn't fix things completely.

I'm seeing a core dump when I try and do '--help'
Core dump is here: https://transfer.sh/ylbW4/i2pd-new.core

**Comment by majestrate** [comment]
I'll get back to you on that core dump, currently setting up some infrastructure for testing i2pd with freebsd
