### ISSUE TITLE
check that the "host" ip is legitimate

### ISSUE THREAD

**Issue by weekendi2p** [PurpleI2P/i2pd#465]
it may or may not be a known issue, but it's possible to put a random ip as "host" parameter in i2pd.conf (the external ip to listen on), no check seems to be done to verify that it's the legitimate one

**Comment by hagen-i2p** [comment]
When this parameter is empty, i2pd will try to autodetect ip.

Yes, you may set wrong one, and no one can forbid you doing so, but then i2pd will not work fast enough to use it. :-)

Simple iteration over addresses on host's interfaces not cover cases with NAT (on your router or your provider).
