### ISSUE TITLE
daemon access to subscriptions.txt, i2pd.conf, tunnels.conf

### ISSUE THREAD

**Issue by khumarahn** [PurpleI2P/i2pd#469]
Hi! I have been working on updating the gentoo ebuild for i2pd. We have a working package, with all user changeable files (`subscriptions.txt`, `i2pd.conf` and `tunnels.conf`) in `/etc/i2pd/`, support of graceful shutdown on `rc-service i2pd graceful`, and other stuff. It seems to work well without spending time on initial configuration.

Currently we make files `/etc/i2pd/subscriptions.txt`, `/etc/i2pd/i2pd.conf` and `/etc/i2pd/tunnels.conf` owned by i2pd user. I wonder if this is necessary. Does the daemon need write access to these files? Can you clarify?

Спасибо.

**Comment by orignal** [comment]
No, they can be read-only

**Comment by khumarahn** [comment]
ok, thank you!
