### ISSUE TITLE
UI: Low quality icon in Notification area

### ISSUE THREAD

**Issue by yfdyh000** [PurpleI2P/i2pd#471]
i2pd_2.6.0_win32_mingw on Windows 10.

![Running notification in Windows 10](https://cloud.githubusercontent.com/assets/1769875/14422928/b309f74e-000b-11e6-892f-fc6e77e231fc.png)
![Tray icon](https://cloud.githubusercontent.com/assets/1769875/14422929/b345dd68-000b-11e6-9052-80525e0829ec.png)

**Comment by orignal** [comment]
changed back to ictoopie
