### ISSUE TITLE
Cannot open localhost:7070

### ISSUE THREAD

**Issue by khumarahn** [PurpleI2P/i2pd#472]
Привет. У меня не получается зайти на http://localhost:7070

```
# curl -v http://localhost:7070
* Rebuilt URL to: http://localhost:7070/
*   Trying ::1...
* connect to ::1 port 7070 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 7070 (#0)
> GET / HTTP/1.1
> Host: localhost:7070
> User-Agent: curl/7.45.0
> Accept: */*
> 
```
и очень долго ничего не происходит (я ждал минут 20). При этом 
```
curl -v -x localhost:4444 http://forum.i2p/
```
срабатывает, я вижу многа букв исходного текста странички.

Я вижу эту проблему в первый раз, возможно это связано с тем, что я сегодня добавил в конфиг
```
bandwidth = P
floodfill = true
```
Часов 9 назад, когда я только сделал эти изменения и перезапустил демон, http://localhost:7070 открывался нормально.

Я пытался найти что-то полезное в логе, но не смог. Кстати, лог файл за 1 или 2 дня уже набрал 170 мегабайт. Да и пока я писал этот репорт, он успел набрать несколько мегабайт.

Версия 2.6.0

**Comment by orignal** [comment]
Надо число дескрипторов 4096 поставить для флудфила.

**Comment by khumarahn** [comment]
как ставить число дескрипторов?

**Comment by orignal** [comment]
командой ulimit -n 4096

**Comment by khumarahn** [comment]
Вот, я проверил, что у меня было:
```
# cat /proc/sys/fs/file-max 
206467
# ulimit 
unlimited
```

**Comment by khumarahn** [comment]
а, понял. `ulimit -n` стояло 1024. увеличил до 4096

**Comment by khumarahn** [comment]
Вроде после увеличения числа дескрипторов работает лучше, локалхост открывается. По крайней мере, через 9 часов после старта. Я напишу ещё, если проблема вдруг вернётся.

Кстати, добавь пробел перед "already" в https://github.com/PurpleI2P/i2pd/blob/ca10dfeb5f9991d756d42fcecbbdc332aa1b34f2/TunnelEndpoint.cpp#L122

**Comment by orignal** [comment]
поправил

**Comment by khumarahn** [comment]
Похоже, что с `ulimit -n 4096` всё работает! Более 12 ГБ за сутки в каждую сторону, скорость нормальная, веб-интерфейс открывается.

Правда, не открываются direct.i2p и 333.i2p, но зато открываются forum.i2p и flibusta.i2p.

**Comment by orignal** [comment]
C 333.i2p я там малость с настройками перемудрил :)  Счас поправлю.
direct.i2p вроде бы уже несколько дней лежит

**Comment by khumarahn** [comment]
ок, 333.i2p открывается :-) 

Может, стоит добавить в документацию про `ulimit -n` для флудфила?

**Comment by orignal** [comment]
Да, надо добавить. А то для большинтсва это неочевидно. Что под виндами надо ставить я не знаю - надо @mlt спросить.

**Comment by mlt** [comment]
Я не пробовал как флудфил гонять под виндой. Вроде под более-менее свежими виндами таких ограничений нет http://superuser.com/q/4582/106115 .

**Comment by orignal** [comment]
так попробуй. это был бы хороший тест
