### ISSUE TITLE
cannot reuse same port on different interface

### ISSUE THREAD

**Issue by weekendi2p** [PurpleI2P/i2pd#479]
In tunnels.conf when trying

[something]
...
address = 127.0.0.1
port = 6668
...

[something-else]
...
address = 127.0.0.2
port = 6668
...

→ the second service won't start, even if it could theoretically bind to this address/port

**Comment by orignal** [comment]
I think because 127.0.0.* means the same interface. Try really different interfaces line 127.0.0.1 and 192.168.0.1 or whatever.

**Comment by weekendi2p** [comment]
yeah sorry I should have written "on different ip", but even with totally different interfaces (lo and eth0), it won't load the second service if it's using the same port.

The issue seems to occur only with clients (type = client)
