### ISSUE TITLE
iMule & SAM: runtime exception: bad lexical cast

### ISSUE THREAD

**Issue by mathiasfriman** [PurpleI2P/i2pd#482]
Firstly, thanks for a kick-ass software! 

I've compiled iMule daemon on a raspberry pi 2 and when trying to open a connection to the Kad network via iMuleGUI it fails with

`2016-04-27 08:24:15: External Connection: ProcessRequest2 with opcode a`
`2016-04-27 08:24:16: External Connection: ProcessRequest2 with opcode 52`
`[...]`
`2016-04-27 08:24:16: UDP server cannot connect to the I2P network (Unknown error)`

Error message in i2pd console:
 
`07:19:03@132/error - SAM: runtime exception: bad lexical cast: source type value could not be interpreted as target`

I've also installed the java i2p router and the compiled iMule daemon works fine with it. 

I've compiled the i2pd daemon myself according to [this instruction](https://www.reddit.com/r/i2p/comments/43f6ng/how_to_install_i2pd_tutorial_for_debianubuntu/)

Let me know if you need more information and (if it's non-trivial) how I do to get it to you.

**Comment by orignal** [comment]
I guess RPi2 splits datagram packets at RPI2 and i2pd's SAM doesn't handle this case properly.
Needs to be implemented.

**Comment by majestrate** [comment]
I have an RPI, I can debug this today.

**Comment by orignal** [comment]
@majestrate I think it happens when RPi eats around 100% cpu

**Comment by majestrate** [comment]
pcap of imule sam handshake

        0x03d0:  7837 2049 443d 694d 756c 655f 356a 3367  x7.ID=iMule_5j3g
        0x03e0:  5663 6168 7648 2069 3263 702e 6d65 7373  VcahvH.i2cp.mess
        0x03f0:  6167 6552 656c 6961 6269 6c69 7479 3d4e  ageReliability=N
        0x0400:  6f6e 6520 2069 3270 2e73 7472 6561 6d69  one..i2p.streami
        0x0410:  6e67 2e63 6f6e 6e65 6374 5469 6d65 6f75  ng.connectTimeou
        0x0420:  743d 3630 3030 3030 2069 6e62 6f75 6e64  t=600000.inbound
        0x0430:  2e6c 656e 6774 683d 0220 696e 626f 756e  .length=..inboun
        0x0440:  642e 6e69 636b 6e61 6d65 3d69 4d75 6c65  d.nickname=iMule
        0x0450:  5f55 4450 2069 6e62 6f75 6e64 2e71 7561  _UDP.inbound.qua
        0x0460:  6e74 6974 793d 0220 6f75 7462 6f75 6e64  ntity=..outbound
        0x0470:  2e6c 656e 6774 683d 0220 6f75 7462 6f75  .length=..outbou
        0x0480:  6e64 2e71 7561 6e74 6974 793d 0220 7361  nd.quantity=..sa
        0x0490:  6d2e 666f 7263 6546 6c75 7368 3d74 7275  m.forceFlush=tru
        0x04a0:  6520 0a                                  e..


https://github.com/PurpleI2P/i2pd/blob/941f30d1ea17c8bf63b856ee8d91e949804d11d7/Destination.cpp#L39 

when creating destination imule gives bad parameters to sam, Destination tries to do lexical cast on empty string, fails.

**Comment by majestrate** [comment]
fix inbound, testing it now

**Comment by mathiasfriman** [comment]
Thank you for a swift response! I've git pulled and compiled the new code and it now connects to the kad network.

I even downloaded a 169kb file through imuled -> iMuleGUI so it seems to work properly.

Had some error messages though, and not sure whether the problem is with i2pd or iMule.

iMule log:
`!2016-04-28 04:08:43: Sam session: Read(p,1) failed. wxSOCKET error : Input/Output error.`
`!2016-04-28 04:08:43: Sam session: SAM session just died`

i2pd log:
`05:56:41@216/error - Destination: Suggested floodfills are not presented in netDb`
`05:56:41@216/error - SAM: destination to connect not found`
`05:56:41@750/error - NTCP: Connect error: Connection refused`

Didn't seem to impact the transfers in the long run. I run the i2pd as Firewalled and the uptime at that time was just around an hour after restart, so it might be related to that.
