### ISSUE TITLE
Support zero-downtime settings reload

### ISSUE THREAD

**Issue by ernado** [PurpleI2P/i2pd#486]
Like nginx. I know that it is not trivial, but will be very useful for i2p, because i2pd should keep tunnels until they are closed.

**Comment by majestrate** [comment]
would require a lot of thought and possibly quite a few architectural changes.
i.e. what happens if we need to change something related to participating tunnel logic?

**Comment by ernado** [comment]
Maybe i2pd can utilize fallback logic for things that hard to change in realtime, i.e. do "full reset" instead of "reload".
I think it's better to wait until it is clear that this feature is needed/not needed. I'm not C++ programmer, so i don't know how hard is to implement this feature in i2pd stack.

Just came to this while turning off BOB interface, which is impossible without restart of i2pd.

**Comment by majestrate** [comment]
we do have stuff for configuration reloading via SIGHUP but upgrading the actual binary on runtime like with nginx is another thing that's probably out of scope of what we can pull of at the moment.

**Comment by ernado** [comment]
Upgrading without reload is overkill, i just need SIGHUP-stuff

**Comment by orignal** [comment]
It's relatively easy to implement tunnels persistance

**Comment by l-n-s** [comment]
Duplicate #384
