### ISSUE TITLE
Proxying i2p requests from remote machines - bug?

### ISSUE THREAD

**Issue by mathiasfriman** [PurpleI2P/i2pd#488]
Attempted to connect to a i2pd http proxy service from a remote machine, both running on my local network. Tried to configure the i2pd.conf as I thought it should be:

    [httpproxy]
    port = 4444
    address = 192.168.1.200

It doesn't work. Also tried setting the address to **0.0.0.0** but still I got "Connection refused" from the server.

I guess I could do some ssh forwarding to get it to work, but is this not a valid configuration scenario? Is it not possible to connect to a remote i2pd http proxy or am I just doing it wrong?

Sorry for making this a support forum... Feel free to close this issue.

**Comment by alexeicolin** [comment]
Strange. I am doing exactly that (0.0.0.0), and it works fine (I access the proxy from LAN and from VPN). What interface does `lsof -i -P -n` say `i2pd` is bound to and listening on? Also, try testing with `telnet host 4444` from your remote machine, just to verify and cut down on possibilities.

**Comment by majestrate** [comment]
are you using it as a transparent proxy or a regular http proxy?

**Comment by mathiasfriman** [comment]
Weird, After a couple of restarts of i2pd it works using **0.0.0.0**. I have no firewall or anything like that running so I'm not sure what was wrong. Probably some PEBKAC issue.

Sorry for the trouble, and thanks for the help.
