### ISSUE TITLE
Problems with misconfigured(?) locale and maybe more problems

### ISSUE THREAD

**Issue by anon5** [PurpleI2P/i2pd#498]
01:32:55/info - Log: min msg level set to debug
01:32:55/info - Daemon: starting HTTP Server at 127.0.0.1:15555
01:32:55/info - Daemon: starting NetDB
01:32:55/warn - Reseed: Can't load reseed certificates from ./certificates/family
01:32:55/error - RouterInfo: File./netDb/rF/routerInfo-F9tZgxYN5NPalVvrDQd4WEXRBWnue0gLHwT9CEmSAdA=.dat is malformed
01:32:55/warn - NetDb: RI from ./netDb/rF/routerInfo-F9tZgxYN5NPalVvrDQd4WEXRBWnue0gLHwT9CEmSAdA=.dat is invalid. Delete
01:32:55/error - RouterInfo: File./netDb/rF/routerInfo-F9szKuW8tCUoiLsjLn8bjgX62sOTxuV9QXbyOyL3Xis=.dat is malformed
01:32:55/warn - NetDb: RI from ./netDb/rF/routerInfo-F9szKuW8tCUoiLsjLn8bjgX62sOTxuV9QXbyOyL3Xis=.dat is invalid. Delete
01:32:55/error - RouterInfo: File./netDb/rV/routerInfo-VeiInx2elIhJ9N6yhESG94ey339QNG59R-lQ2FaONS4=.dat is malformed
01:32:55/warn - NetDb: RI from ./netDb/rV/routerInfo-VeiInx2elIhJ9N6yhESG94ey339QNG59R-lQ2FaONS4=.dat is invalid. Delete
01:32:55/error - RouterInfo: File./netDb/rV/routerInfo-VQguV-tr5CbFv17GQBfLqOksMlcixxfirUfYbfNxkT8=.dat is malformed
01:32:55/warn - NetDb: RI from ./netDb/rV/routerInfo-VQguV-tr5CbFv17GQBfLqOksMlcixxfirUfYbfNxkT8=.dat is invalid. Delete
01:32:55/warn - NetDb: RI from ./netDb/r2/routerInfo-2p-JGeijXuWilHc-wpjwpzyod93Q-q5emfrlcuMyWVI=.dat is invalid. Delete
01:32:55/error - RouterInfo: File./netDb/r~/routerInfo-~C-7bTIWaNjTYkH1vpuktQxmdm6ulaAw7bsU52NnHL0=.dat is malformed
01:32:55/warn - NetDb: RI from ./netDb/r~/routerInfo-~C-7bTIWaNjTYkH1vpuktQxmdm6ulaAw7bsU52NnHL0=.dat is invalid. Delete
01:32:55/error - RouterInfo: File./netDb/r~/routerInfo-~d6fY6bJblTbWlOwWycoygBIN2N81HNmaaXc7AIG3EY=.dat is malformed
01:32:55/warn - NetDb: RI from ./netDb/r~/routerInfo-~d6fY6bJblTbWlOwWycoygBIN2N81HNmaaXc7AIG3EY=.dat is invalid. Delete
01:32:55/error - RouterInfo: File./netDb/r~/routerInfo-~LtMe0GjgJRZo6jwMMs-CvHocHxQmG2RXLxX3j-SMIk=.dat is malformed
01:32:55/warn - NetDb: RI from ./netDb/r~/routerInfo-~LtMe0GjgJRZo6jwMMs-CvHocHxQmG2RXLxX3j-SMIk=.dat is invalid. Delete
01:32:55/error - RouterInfo: File./netDb/r~/routerInfo-~dPhQRGvP3i2TpMWEJ2g2a3qKbzWpM8QrQUwvwkMaYg=.dat is malformed
01:32:55/warn - NetDb: RI from ./netDb/r~/routerInfo-~dPhQRGvP3i2TpMWEJ2g2a3qKbzWpM8QrQUwvwkMaYg=.dat is invalid. Delete
01:32:55/error - RouterInfo: File./netDb/r~/routerInfo-~RBLWu7e8Z5afcN2jAVdMXhIpY06tdvS92wvyvsoCNE=.dat is malformed
01:32:55/warn - NetDb: RI from ./netDb/r~/routerInfo-~RBLWu7e8Z5afcN2jAVdMXhIpY06tdvS92wvyvsoCNE=.dat is invalid. Delete
01:32:55/info - NetDb: 392 routers loaded (283 floodfils)
01:32:55/info - Daemon: starting Transports
01:32:55/info - NTCP: Start listening TCP port 24760
01:32:55/info - Transports: Start listening UDP port 24760
01:32:55/info - SSU: Creating new session to [CztU] 95.44.90.252:34314
01:32:55/info - Daemon: starting Tunnels
01:32:55/info - Daemon: starting Client
01:32:55/info - SSU: Creating new session to [~~9m] 80.119.157.67:27972
01:32:55/info - SSU: Creating new session to [Wd~X] 31.129.189.155:23802
01:32:55/info - SSU: Creating new session to [tm-2] 212.71.255.148:10051
01:32:55/info - SSU: Creating new session to [AnYC] 77.84.11.159:29910
01:32:55/info - Addressbook: using index file ./addressbook/addresses.csv
01:32:55/info - Addressbook: 964 addresses loaded from storage
01:32:55/info - Addressbook: 3 subscriptions urls loaded
01:32:55/info - Clients: starting HTTP Proxy at 127.0.0.1:14444
01:32:55/info - Clients: starting SOCKS Proxy at 127.0.0.1:4447
Waiting for data... (interrupt to abort)

и так висело до 02:47:15

```
next actions
```

sudo killall i2pd
READY
sudo killall i2pd
i2pd: no process found
READY
rm -Rf netDb/
READY
далее запустил и2пд

Далее:

02:49:08/info - Log: min msg level set to debug
02:49:08/info - Daemon: starting HTTP Server at 127.0.0.1:15555
02:49:08/info - Daemon: starting NetDB
Waiting for data... (interrupt to abort)

и так висело до  02:51:17

sudo killall i2pd выдал:
i2pd: no process found
READY
ls core
core

gdb ./i2pd core
[...]
Core was generated by `./i2pd --conf=./i2p.conf --tunconf=./tunnels.cfg --datadir=. --service'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f7499ca9cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56

56  ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007f7499ca9cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f7499cad218 in __GI_abort () at abort.c:118
#2  0x00007f749a2ae535 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f749a2ac6d6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f749a2ac703 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f749a2ac922 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x000000000042b296 in boost::throw_exceptionboost::system::system_error (e=...) at /usr/include/boost/throw_exception.hpp:67
#7  0x00000000004218e1 in boost::asio::detail::do_throw_error (err=..., location=0x6458ed "bind") at /usr/include/boost/asio/detail/impl/throw_error.ipp:38
#8  0x00000000004214ed in boost::asio::detail::throw_error (err=..., location=0x6458ed "bind") at /usr/include/boost/asio/detail/throw_error.hpp:42
#9  0x000000000042cf8e in boost::asio::basic_socket_acceptor<boost::asio::ip::tcp, boost::asio::socket_acceptor_service<boost::asio::ip::tcp> >::basic_socket_acceptor (this=0x239e630, io_service=...,

```
endpoint=..., reuse_addr=true) at /usr/include/boost/asio/basic_socket_acceptor.hpp:151
```
#10 0x00000000005f6d9d in i2p::client::TCPIPAcceptor::TCPIPAcceptor (this=0x239e5c0, address="127.0.0.1", port=4447, localDestination=<error reading variable: Cannot access memory at address 0x115f023592b8>)

```
at I2PService.h:111
```
#11 0x0000000000621be5 in i2p::proxy::SOCKSServer::SOCKSServer (this=0x239e5c0, address="127.0.0.1", port=4447, outAddress="127.0.0.1", outPort=9050, localDestination=

```
std::shared_ptr (count 36607472, weak -1) 0x7ffe40d52100) at SOCKS.cpp:772
```
#12 0x00000000005e8268 in i2p::client::ClientContext::Start (this=0x9b8cc0 i2p::client::context) at ClientContext.cpp:73
#13 0x000000000049895e in i2p::util::Daemon_Singleton::start (this=0x9b74a0 i2p::util::DaemonLinux::Instance()::instance) at Daemon.cpp:195
#14 0x00000000004acdf1 in i2p::util::DaemonLinux::start (this=0x9b74a0 i2p::util::DaemonLinux::Instance()::instance) at DaemonLinux.cpp:113
#15 0x00000000004ac855 in main (argc=5, argv=0x7ffe40d52938) at i2pd.cpp:8

(gdb) 

и далее

i2pd  
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
Aborted (core dumped)

./i2pd 
02:56:35/info - i2pd v2.5.1 starting

which i2pd
/usr/sbin/i2pd
READY
pwd
/home/anon5/.i2pd
READY

./i.sh 
02:58:06/info - i2pd v2.5.1 starting
02:58:06/debug - FS: main config file: ./i2p.conf
02:58:06/debug - FS: data directory: .
02:58:06/info - Daemon: router will be floodfill
02:58:06/info - Daemon: floodfill bandwidth set to 'extra'
02:58:06/warn - Addressbook: not saving empty addressbook
READY
ls core*
core  core.1

cat i.sh 
ulimit -n 4096
ulimit -c unlimited
./i2pd --conf=./i2p.conf --tunconf=./tunnels.cfg --datadir=. --service
READY

gdb ./i2pd core 
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/.
Find the GDB manual and other documentation resources online at:
http://www.gnu.org/software/gdb/documentation/.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./i2pd...done.
[New LWP 7849]
[New LWP 7851]
[New LWP 7850]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./i2pd --conf=./i2p.conf --tunconf=./tunnels.cfg --datadir=. --service'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f0741793cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56

56  ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007f0741793cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f0741797218 in __GI_abort () at abort.c:118
#2  0x00007f0741d98535 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f0741d966d6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f0741d96703 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f0741d96922 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007f0741de84e7 in std::__throw_runtime_error(char const*) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007f0741db3f24 in std::locale::facet::_S_create_c_locale(__locale_struct_&, char const_, __locale_struct*) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007f0741da9149 in std::locale::_Impl::_Impl(char const*, unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007f0741daa27b in std::locale::locale(char const*) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007f07427dd2c2 in boost::filesystem::path::codecvt() () from /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.54.0
#11 0x00007f07427ded8f in boost::filesystem::path::parent_path() const () from /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.54.0
#12 0x00007f07427d7f2d in boost::filesystem::detail::create_directories(boost::filesystem::path const&, boost::system::error_code*) () from /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.54.0
#13 0x0000000000570288 in boost::filesystem::create_directories (p=...) at /usr/include/boost/filesystem/operations.hpp:399
#14 0x000000000056f74a in i2p::fs::HashedStorage::Init (this=0x9b79f0 i2p::data::netdb+560, chars=0x663200 i2p::data::T64 "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-~\002", count=64)

```
at FS.cpp:118
```
#15 0x00000000004b703c in i2p::data::NetDb::Start (this=0x9b77c0 i2p::data::netdb) at NetDb.cpp:40
#16 0x00000000004988fe in i2p::util::Daemon_Singleton::start (this=0x9b74a0 i2p::util::DaemonLinux::Instance()::instance) at Daemon.cpp:182
#17 0x00000000004acdf1 in i2p::util::DaemonLinux::start (this=0x9b74a0 i2p::util::DaemonLinux::Instance()::instance) at DaemonLinux.cpp:113
#18 0x00000000004ac855 in main (argc=5, argv=0x7ffd3857e038) at i2pd.cpp:8

(gdb) 

less ~/.bash_profile
[...]
export LANG=en_US.ASCII
export LANGUAGE=en
export LOCALE=C
[...]

echo $LANG
en_US.ASCII
READY
echo $LANGUAGE
en
READY
echo $LOCALE
C
READY

edited .bash_profile, restarted bash

echo $LANG
ru_RU.UTF-8
READY
echo $LANGUAGE
ru:en
READY
echo $LOCALE

READY
echo x $LOCALE y
x y
READY

echo $PS1
READY\n
READY

cd ~/.i2pd
READY
./i.sh 
03:05:40/info - i2pd v2.5.1 starting
03:05:40/debug - FS: main config file: ./i2p.conf
03:05:40/debug - FS: data directory: .
03:05:40/info - Daemon: router will be floodfill
03:05:40/info - Daemon: floodfill bandwidth set to 'extra'
03:05:40/warn - Addressbook: not saving empty addressbook
READY

далее i2pd вроде нормально фунциклировал.

**Comment by anon5** [comment]
далее. в 23 мая 03:18:07 не может приконнектиться к ирц2п

cat ~/.i2pd/tunnels.cfg 
[IRC]
type = client
port = 16668
destination = irc.postman.i2p
keys = irc-keys.dat
[...]

**Comment by anon5** [comment]
к валкеру однако законнектилось быстро.

**Comment by aa6** [comment]
Также испытывал проблемы из-за локали, не позволявшие запустить i2pd, однако их удалось преодолеть:

```
root@raspberrypi:~# i2pd
12:28:11@33/info - Log: min messages level set to info
12:28:11@33/info - i2pd v2.14.0 starting
12:28:12@33/info - Daemon: bandwidth set to 'low'
12:28:12@33/info - Daemon: using system limit in 65536 max open files
12:28:12@33/info - Daemon: starting NetDB
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
Aborted

root@raspberrypi:~# locale-gen en_US en_US.UTF-8
Generating locales (this might take a while)...
  en_GB.UTF-8... done
Generation complete.

root@raspberrypi:~# locale-gen ru_RU ru_RU.UTF-8
Generating locales (this might take a while)...
  en_GB.UTF-8... done
Generation complete.

root@raspberrypi:~# dpkg-reconfigure locales
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
  LANGUAGE = (unset),
  LC_ALL = (unset),
  LC_PAPER = "ru_RU.UTF-8",
  LC_ADDRESS = "ru_RU.UTF-8",
  LC_MONETARY = "ru_RU.UTF-8",
  LC_NUMERIC = "ru_RU.UTF-8",
  LC_TELEPHONE = "ru_RU.UTF-8",
  LC_IDENTIFICATION = "ru_RU.UTF-8",
  LC_MEASUREMENT = "ru_RU.UTF-8",
  LC_TIME = "ru_RU.UTF-8",
  LC_NAME = "ru_RU.UTF-8",
  LANG = "en_GB.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_GB.UTF-8").
locale: Cannot set LC_ALL to default locale: No such file or directory
/usr/bin/locale: Cannot set LC_ALL to default locale: No such file or directory
Generating locales (this might take a while)...
  en_GB.UTF-8... done
  ru_RU.UTF-8... done
Generation complete.

root@raspberrypi:~# i2pd
12:38:13@456/info - Log: min messages level set to info
12:38:13@456/info - i2pd v2.14.0 starting
12:38:13@456/error - router.info is malformed. Creating new
12:38:14@456/info - Daemon: bandwidth set to 'low'
12:38:14@456/info - Daemon: using system limit in 65536 max open files
12:38:14@456/info - Daemon: starting NetDB
12:38:14@456/warn - Family: Can't load family certificates from /root/.i2pd/certificates/family
12:38:14@456/error - Family: 347f69139bc02660c00fb9694c7561a382d6a637708638f3480306482d233ba0 is too long
12:38:14@456/warn - RouterInfo: family signature verification failed
12:38:14@456/info - NetDb: 174 routers loaded (129 floodfils)
12:38:14@456/info - Daemon: starting Transports
...
```
Несмотря на преодолимость, было бы весьма хорошо, если бы успешный запуск программы не зависел от этого фактора.

**Comment by l-n-s** [comment]
If I'm correct, this code is causing the bug:

```
ag "local_time"
                                                                                                                         
libi2pd/Profiling.cpp
16:             m_LastUpdateTime (boost::posix_time::second_clock::local_time()),
24:             return boost::posix_time::second_clock::local_time();

daemon/I2PControl.cpp
6:#include <boost/date_time/local_time/local_time.hpp>
304:                    auto facet = new boost::local_time::local_time_facet ("%a, %d %b %Y %H:%M:%S GMT");
306:                    header << boost::posix_time::second_clock::local_time() << "\r\n";

```

**Comment by l-n-s** [comment]
Looks like an [old upstream boost bug](https://svn.boost.org/trac10/ticket/4688).

Solution is to have all locales generated and configured correctly on your system.

    locale-gen en_US en_US.UTF-8
    export LC_ALL="C"
