### ISSUE TITLE
Недопустимая инструкция

### ISSUE THREAD

**Issue by strannik-j** [PurpleI2P/i2pd#499]
После последнего обновления на одной из машин i2pd рушится:
./i2pd  

10:54:34@40/info - Log: min messages level set to info
10:54:34@40/info - i2pd v2.7.0 starting
10:54:35@40/info - Daemon: bandwidth set to 'low'
10:54:35@40/info - Daemon: starting HTTP Server at 127.0.0.1:7070
10:54:35@40/info - Daemon: starting NetDB
10:54:35@40/warn - Reseed: Can't load reseed certificates from /home/strannik/.i2pd/certificates/family
10:54:35@40/info - NetDb: 0 routers loaded (0 floodfils)
10:54:35@40/warn - Reseed: Can't load reseed certificates from /home/strannik/.i2pd/certificates/reseed
10:54:35@40/info - Reseed: Downloading SU3 from https://uk.reseed.i2p2.no:444/
10:54:35@40/info - Reseed: Connected to uk.reseed.i2p2.no:444
10:54:35@40/warn - Reseed: Certificate for meeh@mail.i2p not loaded
10:54:35@40/info - NetDb: RouterInfo added: 23zyRLaPwhE9Z7vkKMcJvR8QoMVanPrAGoYSrFQqx4o=
10:54:35@40/info - NetDb: RouterInfo added: qDloXVg0CzF6nP-tzNHDWyadmj~WzoEr98at9uFLDoY=
10:54:35@40/info - NetDb: RouterInfo added: NAHaYBTxEfzdJiM5NZx2F42qE8ns~~Q0uRShEBhSFok=
10:54:35@40/info - NetDb: RouterInfo added: jdMrFN9Z~2KawvhCfEOUo26z0I~~CBwKcn2zMlpft68=
10:54:35@40/info - NetDb: RouterInfo added: SGTXmuTMZ4HqvDld96meia9WFL367LIqWdgkqZfu398=
10:54:35@40/info - NetDb: RouterInfo added: kNiWwWS6F5jH2hyX9FlKW936T3byHRG2~4fE58nVtRo=
10:54:35@40/info - NetDb: RouterInfo added: yYSZhZO37fD4IDQF99~4x3rIx6w6dVWeH63s7650zIo=
10:54:35@40/info - NetDb: RouterInfo added: MgdtsjVZnqJBX~QHH8Bt3KuDFL2R7EpUtRzYFpDcEEI=
10:54:35@40/info - NetDb: RouterInfo added: 1y~cUPRw6FY4PrlY8jAc-LnvQiBGYKKT37M6SWCgFI4=
10:54:35@40/info - NetDb: RouterInfo added: 6lela6yR6h7DcrLoEGuLH3g6W~--jITBy6S-3xzsPwk=
10:54:35@40/info - NetDb: RouterInfo added: ebKzXSkaJGjIdNaM~UpolueSdahbZ-XbKM4fttgQwok=
10:54:35@40/info - NetDb: RouterInfo added: orQheTgC-807g57yBLSbgdelVfncjrMGq~5ewqB-3x4=
10:54:35@40/info - NetDb: RouterInfo added: kUVF1hbiuTXtnvuFOQcexGzFKaD95K4V3kztsgfjXa0=
10:54:35@40/info - NetDb: RouterInfo added: uq1csROd4oMNgbXvNhZxZ9Tj4oJeUHGTtr~SKuWw4Q0=
10:54:35@40/info - NetDb: RouterInfo added: wiBwl4LLMNWjiJZPKYtNANyrbS5WPpR4D~Ass~9jJfQ=
10:54:35@40/info - NetDb: RouterInfo added: cquYyirP28ltzbjNWLIH2jo4YmafK~MooN3oktbFogg=
10:54:35@40/info - NetDb: RouterInfo added: ~C-7bTIWaNjTYkH1vpuktQxmdm6ulaAw7bsU52NnHL0=
10:54:35@40/info - NetDb: RouterInfo added: Pgj8-rwntc0jk-7zqYbcGFFnb9dwie1T2c1dBB1DUXY=
10:54:35@40/info - NetDb: RouterInfo added: iizwKORmqEi4cJM8SN2pEAN~UKAHCnvmxPAnAnyn3fA=
10:54:35@40/info - NetDb: RouterInfo added: d-h5AB~WeQmgFYpdWU8lahhAdZamf94OJyCUZ1GeGI8=
10:54:35@40/info - NetDb: RouterInfo added: uXHQB3JV~r3gGtEJTBnj0WAm4srOIu25fVw8RsOAmwc=
10:54:35@40/info - NetDb: RouterInfo added: gDZqaNJE-0b32FhOrW59MUDiR0hTUTokvWqKWd2ao9o=
10:54:35@40/info - NetDb: RouterInfo added: WXDbix4jEm0c5WdgTjxVNOr0uIql78~fFNPnbz21W6g=
10:54:35@40/info - NetDb: RouterInfo added: T3h6mjoV8-8Yi2uvxLMSNhk3ORzNMw0~43cBfzCigJ0=
10:54:35@40/info - NetDb: RouterInfo added: 2XvBpFjR03yelxvodl1MCumpPW0LA2Z~Lat8IKXUbyA=
10:54:35@40/info - NetDb: RouterInfo added: j~zSIDFoQypEWy0yAAv~2I7y1Zg-K8rlt8~g~RZueMM=
10:54:35@40/info - NetDb: RouterInfo added: nC6wryH1sRLOxVytDgrZ8m~7ALkMGi5PBYnubtxx5Ps=
10:54:35@40/info - NetDb: RouterInfo added: UmwJqha4yNPaNyXnvudW86ncXthtEIKyN9Md9fDUhbo=
10:54:35@40/info - NetDb: RouterInfo added: 8lknUgG8y2tAIvmq5i2yOok2~GwHtyLrdMitXq8Dxe4=
10:54:35@40/info - NetDb: RouterInfo added: XsBEpuka2pb40TGFN-do6bN7zw8wfcHriK22GxrCgvU=
10:54:35@40/info - NetDb: RouterInfo added: rUKZNcw~r2gzc9OQlmt-NgV4KtqN0U47pYrdIWrxou4=
10:54:35@40/info - NetDb: RouterInfo added: -M72lVbezPbgeTNmFindowvJwrTaDZO7KHZNZJVkof8=
10:54:35@40/info - NetDb: RouterInfo added: quiBXwSQAgiBz~DlAjYfJF4zjBtSqatUqcs3mN2HzqY=
10:54:35@40/info - NetDb: RouterInfo added: 0p48siiBXCqJZIJRJyKxFoTnQ1zn~D-fUilXhWwiaUg=
10:54:35@40/info - NetDb: RouterInfo added: 9d26Q7BCTxBBDWKsvD8C6hHUOkbP0E7MDX3HD4GA5fs=
10:54:35@40/info - NetDb: RouterInfo added: IE5oVr6GTXfWvS7vfIlj1Xd9pBkiSDlI5ZVfkoacOQI=
10:54:35@40/info - NetDb: RouterInfo added: -Jbag2UDQuVT9~ibyY0SPEKb3PPRJ~DHpbADUgeIfKc=
10:54:35@40/info - NetDb: RouterInfo added: ANqabTrUULeNw7B9ZrnK6YJrmDUPnVmmHAcHSdE-hv0=
10:54:35@40/info - NetDb: RouterInfo added: 9z9fnMa4aMMSOx45V1s9gqN-7rI8~TaX9bPDijKO1xE=
10:54:35@40/info - NetDb: RouterInfo added: 331QnCn-PMVLXXT64KJax9nTZKQCEXQRDXrOFCpqak4=
10:54:35@40/info - NetDb: RouterInfo added: ~F1-1lYUkSdHe6ZX81PbSqFZzzxScgOgTOL64BuzYYE=
10:54:35@40/info - NetDb: RouterInfo added: Phbdqz7ddZDG7V9tE6dpouWmopJHPRw8fxwC3SJY6WM=
10:54:35@40/info - NetDb: RouterInfo added: m8hVPTgN9o0adPqNgQqX0YP6IMB9mpzvMJJmsg5ojJc=
10:54:35@40/info - NetDb: RouterInfo added: V8~XpIqZ~Qj7p5rToj3358KBGTkZ24bjXJ2gv8RW4tw=
10:54:35@40/info - NetDb: RouterInfo added: piT~rmY4Gf-NnKYeiyX~omRoaZN3IOrLyZJK~CvpT0Y=
10:54:35@40/info - NetDb: RouterInfo added: -gzBadVB417Z8SbleYfCCwgU6UPNhQfidlWc0JSgps4=
10:54:35@40/info - NetDb: RouterInfo added: 7YCI9BVdsbU9Tzx4~gfFwBresBr6VWhyf-OPvVh5e2E=
10:54:35@40/info - NetDb: RouterInfo added: mgs5GTirgcS9-CmMwPpb3nwh3muRgiKSxtxYPIvveX8=
10:54:35@40/info - NetDb: RouterInfo added: 4yH5-4qEOAOV5fgalKFLtNbULsMeI~5U86FZZxTIu0E=
10:54:35@40/info - NetDb: RouterInfo added: zRAzTntJm8tUWuaXEGjKWFXH92a22KLWiIawudeXv0E=
10:54:35@40/info - NetDb: RouterInfo added: YfDTS5a34k84AEFQ-9TQVLeF2hYqUN36ePilWRvk1NE=
10:54:35@40/info - NetDb: RouterInfo added: qiosO5Ea9pIvaoc7moVChTZjJya~5WSTAyDaeESQi3w=
10:54:35@40/info - NetDb: RouterInfo added: Z48E483BdWefd1RHd-bN2acCNrITedk2qabagPuP~NU=
10:54:35@40/info - NetDb: RouterInfo added: 5UHVubRxnohwp1-MyjPzWQqZ5ypmRK2pMVTWsm~IV00=
10:54:35@40/info - Daemon: starting Transports
10:54:35@40/info - NTCP: Start listening TCP port 25662
10:54:35@40/info - Transports: Start listening UDP port 25662
10:54:35@40/info - Daemon: starting Tunnels
10:54:35@74/info - SSU: Creating new session to [-Jba] 37.110.241.249:48825
10:54:35@40/info - Daemon: starting Client
Недопустимая инструкция

Ubuntu 14.04 x86, Intel Pentium(R) Dual-Core CPU E5

**Comment by orignal** [comment]
процессор AES-NI не поддерживает
Пересобрать из исходников - тогда собретеся без него. 
В следующем релизе сделаю определение в рантайме.

**Comment by strannik-j** [comment]
Дык проблема в том, что я собирал из исходников. А вот вчера поставил готовый бинарник - всё работает!

**Comment by orignal** [comment]
На той же самой машине?

**Comment by strannik-j** [comment]
ага

**Comment by orignal** [comment]
при компиляции -DAESNI вылазит?
