### ISSUE TITLE
Поддержка Windows (компилятор vs2013)

### ISSUE THREAD

**Issue by chertov** [PurpleI2P/i2pd#5]
Собрал исходники с помощью Visual Studio 2013. Вроде бы компилируется, запускается, но есть проблемы. При первом запуске создает два файла **router.info** и **router.keys** (в них какая-то каша). Виндовский фаервол спросил разрешить или нет, видимо сервер открыл порт.
Пишет такой лог:

```
netDb doesn't exist
Start listening port 17007
Creating zero hops inbound tunnel...
I2NP msg received len=545, type=23, msgID=0
VariableTunnelBuild
VariableTunnelBuild 1 records
Record 0 is ours
TransitTunnel gateway: 1736841068 created
I2NP msg received len=545, type=23, msgID=555
VariableTunnelBuild
VariableTunnelBuild 1 records
VariableTunnelBuild reply for tunnel 1847386387
TunnelBuildResponse 1 records.
Ret code=0
Inbound tunnel 1847386387 has been created
I2NP msg received len=545, type=23, msgID=1
VariableTunnelBuild
VariableTunnelBuild 1 records
Record 0 is ours
TransitTunnel endp
```

и падает в **void Tunnel::Build (uint32_t replyMsgID, OutboundTunnel \* outboundTunnel)** в этой точке:

``` cpp
EncryptBuildRequestRecord (*hop->router,
    CreateBuildRequestRecord (hop->router->GetIdentHash (),
...
```

При последующих запусках не может распарсить **router.info** и соответственно вылетает.

При компиляции был собран boost 1.55 и crypto++ 5.6.2 и возникли следующие проблемы:
1) Компилятор vs2013 пока не умеет спецификаторы **default**, но, к счастью, их всего несколько. В коде эти конструкторы не использовались, поэтому большую часть просто закомментил (классы **IdentHash** и **RouterInfo**).

2) В винде нету **endian.h**, использовал такую версию https://gist.github.com/panzi/6856583

3) тип **ssize_t** отсутствует, не разбирался пока, просто убрал одну s)

4) Отсутствует gmtime_r. Пока оставил так:

``` cpp
#ifdef _WIN32
        gmtime_s(&tm, &t);
#else
        gmtime_r(&t, &tm);
#endif
```

5) функция **sleep** в винде начинается с заглавной буквы **Sleep**

Под линуксом не собирал, думаю стоит поставить линукс и искать 10 отличий)
Очень бы хотелось иметь кросплатформенные исходники и собирать проект родным компилятором под виндой.

**Comment by ygrishin** [comment]
original, а где та проблема с SSU detection под Windows, уже есть созданная issue?

**Comment by orignal** [comment]
Наверное не с SSU, а с MTU

https://github.com/PurpleI2P/i2pd/issues/107

**Comment by ygrishin** [comment]
Спешу сообщить что концепция определения MTU под Windows отработана на прототипах, теперь код из прототипов переносится непосредственно в рабочую функцию. Когда точно будет завершена работа -- пока не буду обещать, есть шанс что совсем скоро.
Спешу сообщить что концепция определения MTU под Windows отработана на прототипах, теперь код из прототипов переносится непосредственно в рабочую функцию. Когда точно будет завершена работа -- пока не буду обещать, если повезет то совсем скоро.

**Comment by ygrishin** [comment]
Готово https://github.com/PurpleI2P/i2pd/pull/163

**Comment by l-n-s** [comment]
Windows should work fine now.
