### ISSUE TITLE
Extremely large e-tag file

### ISSUE THREAD

**Issue by vampik** [PurpleI2P/i2pd#500]
i2pd-2.7.0, чистая установка (старый профиль удален), ОС Gentoo x86, gcc-4.9.3, glibc-2.22-r4, boost-1.56.0-r1.
При первом запуске из-за пустой адресной книги и невозможности отрезолвить доменные имена из дефолтного subscriptions.txt, i2pd пытался скачать (и через какое-то количество попыток успешно скачал) список хостов с зашитого в коде адреса http://joajgazyztfssty4w2on5oaqksz6tqoxbduy553y34mf4byv6gpq.b32.i2p/export/alive-hosts.txt.
Через некоторое время в папке etags был обнаружен файл joajgazyztfssty4w2on5oaqksz6tqoxbduy553y34mf4byv6gpq.txt размером более 1 гигабайта, полностью состоящий из пробелов.

```
helena etags # ls -la
total 1194340
drwxr-x---  2 i2pd i2pd       4096 May 23 18:33 .
drwxr-x--- 35 i2pd i2pd       4096 May 23 18:33 ..
-rw-r-----  1 i2pd i2pd 1222989680 May 23 18:33 joajgazyztfssty4w2on5oaqksz6tqoxbduy553y34mf4byv6gpq.txt
helena etags # tr -cd ' ' < joajgazyztfssty4w2on5oaqksz6tqoxbduy553y34mf4byv6gpq.txt | wc -c
1222989680
```

**Comment by orignal** [comment]
Это где такая папка располагается?

**Comment by khumarahn** [comment]
наверное, `/var/lib/i2pd/addressbook/etags/`?

**Comment by khumarahn** [comment]
у меня тоже есть такой файл, но он маленький
```
# ls -alh /var/lib/i2pd/addressbook/etags/
total 20K
drwxr-x---  2 i2pd i2pd 4.0K May 19 03:08 .
drwxr-x--- 35 i2pd i2pd 4.0K May 18 14:47 ..
-rw-r-----  1 i2pd i2pd   14 May 24 04:13 7tbay5p4kzeekxvyvbf6v7eauazemsnnl2aoyqhg5jzpr5eke7tq.txt
-rw-r-----  1 i2pd i2pd   47 May 18 14:52 joajgazyztfssty4w2on5oaqksz6tqoxbduy553y34mf4byv6gpq.txt
-rw-r-----  1 i2pd i2pd   70 May 23 16:13 udhdrtrcetjm5sxzskjyr5ztpeszydbh4dpl3pl4utgqqw2v4jna.txt
```

**Comment by orignal** [comment]
а все понял. починю
