### ISSUE TITLE
HTTP proxy redirects to 0.0.0.0:7070/?page=jumpservices

### ISSUE THREAD

**Issue by radfish** [PurpleI2P/i2pd#504]
i2pd is probably using the bind address in the URL. This works if the bind address is 127.0.0.1 and browser is on same host, or if bind is the local LAN address and browser is on LAN, but is not correct if bind address is 0.0.0.0.

Instead, i2pd should get the hostname from headers sent by the browser in its requests. Then, use this hostname whenever it has to construct a URL.

**Comment by orignal** [comment]
It's not in a header, it should take it from local endpoint

**Comment by hagen-i2p** [comment]
It's temporary solution, proxy refactoring still in process.

Jumservices should be moved directly to proxy error page. Instead "addressbook" page should be added to webconsole.

**Comment by xcps** [comment]
I made a temporary solution.
