### ISSUE TITLE
Status при мягком выключении

### ISSUE THREAD

**Issue by atnaguzin** [PurpleI2P/i2pd#506]
Добавьте в вебконсоль соответствующее сообщение статуса при мягком выключении, с таймером со страницы команд.

**Comment by hagen-i2p** [comment]
Currently "Status" is the network status (OK, Firewalled, Unreachable, ...)

Maybe add some ``<span>`` notice at top of the page (visible only on shutdown)?

**Comment by atnaguzin** [comment]
Решать тебе. Я бы отнес это так же к статусу. Но если говоришь, что этот пункт относится чисто к сети, то можно и добавить новый <span>
