### ISSUE TITLE
HTTPProxy: unable to parse request

### ISSUE THREAD

**Issue by vampik** [PurpleI2P/i2pd#508]
В последних ревизиях возникла проблема с http proxy. В коммите 5ad10955be548691b667ad2b043c6a837f1a1556 все работает нормально, а в a62720b9d8e3d72050d38aed792c59e1028350fa  ("Merge branch 'new-proxy' into openssl") затруднения - сайты иногда загружаются, иногда - нет, в логах есть сообщения вида:
00:25:41@383/error - HTTPProxy: unable to parse request
00:26:03@383/error - HTTPProxy: unable to parse request
00:28:45@383/error - HTTPProxy: unable to parse request
00:28:52@383/error - HTTPProxy: unable to parse request
00:28:54@383/error - HTTPProxy: unable to parse request
00:40:39@383/error - HTTPProxy: unable to parse request
00:41:00@383/error - HTTPProxy: unable to parse request
Откат до 5ad10955be548691b667ad2b043c6a837f1a1556 - все ок.

**Comment by orignal** [comment]
Еще вот такая фигня

 GET http://hashshop.i2p/ HTTP/1.1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Connection: close
User-Agent: MYOB/6.66 (AN/ON)
Host: hashshop.i2p
Host: hashshop.i2p
Accept-Encoding: gzip, deflate
Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3

**Comment by hagen-i2p** [comment]
@vampik, see patch above.

Can you provide an example for unparseable request?

If you use Firefox, you can obtain request via Ctrl-Shift-K / Network tab. In chrome it calls "Network inspector" or similar.

**Comment by vampik** [comment]
Build e50c35d38c81314be5d674a197334da3df5e86fa

GET / HTTP/1.1
Host: forum.i2p
User-Agent: Mozilla/5.0 (Windows NT 5.1; rv:46.0) Gecko/20100101 Firefox/46.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: ru,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
Cookie: phpbb2mysql_data=a%3A0%3A%7B%7D
Connection: keep-alive

HTTP/1.1 500 Internal Server Error
Content-Length: 17
Content-Type: text/plain
Date: Fri, 03 Jun 2016 22:03:52 GMT

invalid request


GET / HTTP/1.1
Host: flibusta.i2p
User-Agent: Mozilla/5.0 (Windows NT 5.1; rv:46.0) Gecko/20100101 Firefox/46.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: ru,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
Connection: keep-alive

HTTP/1.1 500 Internal Server Error
Content-Length: 17
Content-Type: text/plain
Date: Fri, 03 Jun 2016 22:03:52 GMT

invalid request

After these errors http proxy doesn't respond at all (page loading takes forever).

**Comment by vampik** [comment]
I'm using a transparent proxy setup: all requests for .i2p domains are routed to my_router_ip:8888 (tinyproxy). i2pd is configured as the upstream proxy for .i2p domains (Upstream 127.0.0.1:4444 ".i2p" in tinyproxy config).

**Comment by vampik** [comment]
Here is a request as it arrives to i2pd (captured by tcpdump):

GET http://flibusta.i2p:80/new HTTP/1.0
Host: flibusta.i2p
Connection: close
If-None-Match: "1464995387"
If-Modified-Since: Fri, 03 Jun 2016 23:09:47 +0000

HTTP/1.1 500 Internal Server Error
Connection: close
Content-Length: 17
Content-Type: text/plain
Date: Fri, 03 Jun 2016 23:10:28 GMT

invalid request

**Comment by vampik** [comment]
Build a4dc67cba0b85e266b69778fa27a84618bca39bf - no change. 
66c301c03109088dc7b44f5708fa50b58440cdb6 should not affect my issue. Relative URL is sent by Firefox, but it is converted to an absolute URL by the intermediate proxy (tinyproxy).
I've already provided a sample (not very good though, because tcpdump dropped a number of packets).

Here is a good example:

Request from Firefox to tinyproxy:

GET / HTTP/1.1
Host: forum.i2p
User-Agent: Mozilla/5.0 (Windows NT 5.1; rv:46.0) Gecko/20100101 Firefox/46.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: ru,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
Cookie: phpbb2mysql_data=a%3A0%3A%7B%7D; phpbb2mysql_sid=87a50fe281c1d7e7397c36088f281740
Connection: keep-alive

Request from tinyproxy to i2pd (this is what you get):

GET http://forum.i2p:80/ HTTP/1.0
Host: forum.i2p
Connection: close
Accept-Encoding: gzip, deflate
Cookie: phpbb2mysql_data=a%3A0%3A%7B%7D; phpbb2mysql_sid=87a50fe281c1d7e7397c36088f281740
Accept-Language: ru,en-US;q=0.7,en;q=0.3
User-Agent: Mozilla/5.0 (Windows NT 5.1; rv:46.0) Gecko/20100101 Firefox/46.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8

There are two problems:
- I randomly get "invalid request" response
- web pages are loading VERY slow, and often hang at a white screen and "Waiting for response". It is not a network problem, because reverting to 5ad10955be548691b667ad2b043c6a837f1a1556 instantly fixes the issue!

**Comment by vampik** [comment]
Screenshots of page loading.

Old proxy ( 5ad10955be548691b667ad2b043c6a837f1a1556 )

Page is loaded fully and fast.

![oldproxy](https://cloud.githubusercontent.com/assets/726409/15801890/ba330dce-2aab-11e6-93fe-da0418bdf781.png)

New proxy ( a4dc67cba0b85e266b69778fa27a84618bca39bf )

One "invalid request" (error 500), and the page is not fully loaded.

![newproxy](https://cloud.githubusercontent.com/assets/726409/15801903/f1111296-2aab-11e6-8438-132322908bcc.png)

**Comment by orignal** [comment]
rolled back to 2.7.0
