### ISSUE TITLE
implement fixed first hop (restricted routes)

### ISSUE THREAD

**Issue by majestrate** [PurpleI2P/i2pd#514]
java i2p is/was planning on implementing a mode of operation similar to tor bridge where i2p router has 1 "trusted" first hop that is always used. This would be useful to routers that do not participate in routing by cutting node churn to 0 for those routers limiting the negative effects of network enumeration.

Initial Issues that I can think of:

1) bootstrap would need to be manually configured by user
2) network may (or may not) need more participating routers to prevent network overload
3) first hop may reject tunnel builds a lot more often.

possible solutions:

1a) add more documentation for manual bootstrap
1b) begin implementation of i2p bridge infrastructure (?)
2) add more reliable high capacity i2p routers (?)
3a) relax tunnel build reject limits for "hidden" routers (?)
3b) add manual config options to "unlimited" tunnel builds for explicitly defined addresses

**Comment by l-n-s** [comment]
@majestrate I guess it is implemented with `--trust.routers=` option. Should we close the issue?

**Comment by majestrate** [comment]
yes
