### ISSUE TITLE
Android — release doesn't build on arm 7a

### ISSUE THREAD

**Issue by anon5** [PurpleI2P/i2pd#519]
[orignal] arkestra:  посмотри почему релиз не собирается

**Comment by anon5** [comment]
BUILD SUCCESSFUL, всё собирается уже

**Comment by atnaguzin** [comment]
ReUp.
Doesn't builds for arm.

**Comment by hypnosis-i2p** [comment]
короче на x86 собирается. а на арме 7a нет. не собирается на версиях ндк 11b и 11c

**Comment by anon5** [comment]
для разных ос и разных версий qt поддерживаются разные версии ндк:
http://wiki.qt.io/Qt-5.6.0-tools-and-versions#Software_configurations_with_Qt_5.6

ндк 9с например на убунте трасти - не поддерживается в qt 5.6.0.

**Comment by anon5** [comment]
пофиксал. ща закоммичу
