### ISSUE TITLE
Android - required files

### ISSUE THREAD

**Issue by r4sas** [PurpleI2P/i2pd#532]
(Hypnosis) MXPLRS|Kirill, открывай иссуй про файлы. потому што я не понял это раз и два я отдыхаю щас не до и2пд
(orignal_) Hypnosis:  надо чтобы при установке пакета эти файлы кллались в /sdcard/i2pd
(MXPLRS|Kirill) debian/tunnels.conf -> /sdcard/i2pd/tunnel.conf
(MXPLRS|Kirill) debian/subscriptions.txt -> /sdcard/i2pd/subscriptions.txt
(MXPLRS|Kirill) docs/i2pd.conf -> /sdcard/i2pd/i2pd.conf
(MXPLRS|Kirill) contrib/certificates -> /sdcard/i2pd/certificates

**Comment by l-n-s** [comment]
Done.
