### ISSUE TITLE
i2pd & hyperboria (cjdns)

### ISSUE THREAD

**Issue by strannik-j** [PurpleI2P/i2pd#543]
Есть идея запуска i2p поверх cjdns. Помимо практической цели (есть несколько машин с доступом в cjdns, но без интернета) есть и теоретические: в случае глобальной катастрофы и падения интернета, будет возможность после поднятия cjdns поднять и i2p. Но на форуме, посвящённом cjdns, мне [сказали](http://cjdroute.net/forum/viewtopic.php?f=5&t=362), что нужно править исходники. Так ли это? И что нужно сделать для работы i2pd поверх cjdns?

**Comment by orignal** [comment]
У меня нет этой проверки.

**Comment by majestrate** [comment]
i2p over cjdns would require a separate i2p network because fc00::/8 is a private address range which is non reachable without the vpn tunnel.
It's an interesting idea that I have explored in the past but what is lacking is initial infrastructure, specifically reseed and initial floodfills.

**Comment by orignal** [comment]
We can place some nodes to netdb folder manually.

**Comment by majestrate** [comment]
I have bootstrapped a new i2p network complete with 1 reseed, please keep in mind right now all the nodes are mine right now so please treat it as a demo/toy.

build:

    git clone https://github.com/majestrate/i2pd -b meshnet i2pd-meshnet
    cd i2pd-meshnet 
    make USE_MESHNET=yes
    cp i2pd /usr/local/bin

set up:

    echo "host=your:cjdns:ipv6:address:goes:here" >> ~/.i2pd/i2pd.conf
    
run:

    i2pd

**Comment by orignal** [comment]
@strannik-j , все должно работать

**Comment by majestrate** [comment]
instructions updated, see above

**Comment by strannik-j** [comment]
Если я правильно понял, meshnet добавлен в openssl ветку, и теперь i2pd работает сразу и mesh и с интернетом.

If I understand correctly, meshnet added in openssl branch, and now i2pd works with mesh and with Internet.

**Comment by orignal** [comment]
Сразу нет. Нужно два экземпляра собранные с разными ключами собирать.

**Comment by strannik-j** [comment]
Вот сейчас не понял. Можно подробнее?
Почему и как?

Now I do not understand. Can you tell more ?
Why and how?

**Comment by orignal** [comment]
В двух сетях с разными netId одновременно работать не может.

**Comment by majestrate** [comment]
I saw some machines reseeding but not staying on the network. if you need to test the network try connecting to this irc server, (won't work on mainline i2p)

    irc://ehwfsvap4ubfvzgjcbiahfq6adb45ciuldzs4kfspvqlzig3y3mq.b32.i2p/i3p

**Comment by l-n-s** [comment]
You can create your own I2P network with i2pd now -- over any connection. LAN/CJDNS/etc

See [this blogpost](https://i2p.rocks/blog/diy-darknet-for-fun-and-profit.html) for tutorial.

Also, there is [wiki page](https://github.com/PurpleI2P/i2pd/wiki/testnet), work in progress.
