### ISSUE TITLE
windows7 - missing libgcc dll error

### ISSUE THREAD

**Issue by anon5** [PurpleI2P/i2pd#545]
![image](https://cloud.githubusercontent.com/assets/16508513/16377663/ff959ef4-3c99-11e6-9e44-344c07c61b4a.png)

from https://github.com/PurpleI2P/i2pd/releases/download/2.8.0/i2pd_2.8.0_win32_mingw_upnp.zip

clean non-developer win7 prof

**Comment by orignal** [comment]
собери из транка. тот кривой

**Comment by K1773R** [comment]
This can be fixed by compiling with:
-static-libgcc -static-libstdc++

**Comment by orignal** [comment]
@K1773R the source of issue is that i2pd in 2.8.0 loads miniupnpc.dll dynamically, and one comes with MSYS2 depends on extra dlls.
I have changed it to link the app with it. 
Rebuilt and uploaded.
Should work now
