### ISSUE TITLE
windows - broken cyrillic chars in paths at webconsole

### ISSUE THREAD

**Issue by anon5** [PurpleI2P/i2pd#546]
Screenshot of webconsole: ![image](https://cloud.githubusercontent.com/assets/16508513/16377776/92ade962-3c9a-11e6-80cd-959b3f7cb4f2.png)

Real path: C:\Users\Администратор\AppData\Roaming\i2pd\

from https://github.com/PurpleI2P/i2pd/releases/download/2.8.0/i2pd_2.8.0_win32_mingw_upnp.zip

**Comment by atnaguzin** [comment]
That problem on webconsole side.
Needed to add auto windows-1251 if defined WIN32, else UTF-8
