### ISSUE TITLE
Java Socket irc2p

### ISSUE THREAD

**Issue by hypnosis-i2p** [PurpleI2P/i2pd#559]
orignal, обнаружил с явой такую особенность - когда java.net.Socket создаёшь эксплуатируешь и закрываешь, и открываешь другой с теми же параметрами, то ирц2п лагает бесконечно. Если повторно закрываешь и создаёшь - снова лагает бесконечно. И далее по циклу. 

Если убить жвм и запустить и в новом жвм снова создать такой же сокет, то ирц2п не лагает. Это и в жава и2п и в и2пд. 

Это про ирц2п бота на жаве

**Comment by hypnosis-i2p** [comment]
лагает именно при ИРЦ логин последовательности. то есть при лаге после выполнения конструктора сокета и отсылки начальных ИРЦ команд в аутпутстрим ява сокета — в инпутстрим ява сокета не приходит ничего (то есть после конструктора сокета сокет.гетИнпутСтрим() возвращает инпутстрим, и ничего в этом инпутстриме не появляется.

**Comment by l-n-s** [comment]
any updates?

**Comment by hypnosis-i2p** [comment]
P.S. это не андройд. это видимо ява бот которого я писал давно

**Comment by hypnosis-i2p** [comment]
это скорее глюканы жава нет сокета
