### ISSUE TITLE
на андройдной хардвари еррор — library "libminiupnpc.so.16" not found

### ISSUE THREAD

**Issue by hypnosis-i2p** [PurpleI2P/i2pd#564]
E/art     ( 4965): dlopen("/data/app/org.purplei2p.i2pd-1/lib/arm/libi2pd_qt.so", RTLD_LAZY) failed: dlopen failed: library "libminiupnpc.so.16" not found

**Comment by orignal** [comment]
Ты с чем собирал? Надо вот отсюда брать либы https://github.com/PurpleI2P/MiniUPnP-for-Android-Prebuilt
