### ISSUE TITLE
I2P enabled Transmission 2.82 does not work with i2pd

### ISSUE THREAD

**Issue by mathiasfriman** [PurpleI2P/i2pd#568]
I've compiled the I2P enabled version of Transmission 2.82 and successfully been able to run transmission-cli in the I2P network using the Java version of I2P. 

However, when trying the same setup with i2pd, transmission-cli spouts out "Starting up I2P tunnel for session." every 10 seconds and nothing gets downloaded. This is my `.config/transmission/settings.json` : http://paste.debian.net/780227/

### How to reproduce

* Start I2P and i2pd respectively. (enable BOB!)

* Download the I2P enabled Transmission via torrent: http://zzz.i2p/files/transmission-2.82.tar.xz.torrent

* Install prerequisites. (In Ubuntu/Debian it's) : `apt-get install build-essential automake autoconf libtool pkg-config intltool libcurl4-openssl-dev libglib2.0-dev libevent-dev libminiupnpc-dev libminiupnpc5 libappindicator-dev`

* Compile Transmission with `./configure && make && sudo make install`

* Download a torrent file from tracker2.postman.i2p

* Paste the settings.json settings to a file (e.g. .config/transmission/settings.json)

* Enable debugging of transmission by running `export TR_DEBUG_FD=2`

* run `/usr/local/bin/transmission-cli -g /path/to/.config/transmission/settings.json whichever.torrent 2>transmission-run.log

* Try out with Java I2P router and i2pd in turn.

* check transmission-run.log

i2pd console gives me:

    20:30:55@295/error - BOB: unknown command test
    20:30:55@295/error - BOB: unknown command test
    20:30:55@295/error - BOB: unknown command test
    20:30:55@295/error - BOB: unknown command test 
    20:30:55@295/error - BOB: unknown command test
    20:30:55@295/error - BOB: unknown command test
    20:30:55@295/error - BOB: unknown command test 
    20:30:55@295/error - BOB: unknown command test
    20:30:55@295/error - BOB: unknown command test
    20:30:55@295/error - BOB: unknown command test 
    20:30:55@295/error - BOB: unknown command test
    20:30:55@295/error - BOB: unknown command test
    20:30:55@295/error - BOB: unknown command test
    20:30:55@295/error - BOB: unknown command test
    20:30:55@295/error - BOB: unknown command test
    20:30:55@295/error - BOB: unknown command test
    20:30:55@295/error - BOB: unknown command test
    20:30:55@295/error - BOB: unknown command test
    20:30:55@295/error - BOB: unknown command test

And transmission debug log gives me:

    [20:30:55.013] Starting up I2P tunnel for session.
    [20:30:55.366] 0 peers to go round-robin for upload (bandwidth.c:220)
    [20:30:55.366] 0 peers to go round-robin for upload (bandwidth.c:220)
    [20:30:55.366] 0 peers to go round-robin for upload (bandwidth.c:220)
    [20:30:55.366] 0 peers to go round-robin for download (bandwidth.c:220)
    [20:30:55.366] 0 peers to go round-robin for download (bandwidth.c:220)
    [20:30:55.366] 0 peers to go round-robin for download (bandwidth.c:220)
    [20:30:55.581] [?---?] announceMore: slotsAvailable is 52 (announcer.c:1538)
    [20:30:55.867] 0 peers to go round-robin for upload (bandwidth.c:220)
    [20:30:55.867] 0 peers to go round-robin for upload (bandwidth.c:220)
    [20:30:55.867] 0 peers to go round-robin for upload (bandwidth.c:220)
    [20:30:55.867] 0 peers to go round-robin for download (bandwidth.c:220)
    [20:30:55.867] 0 peers to go round-robin for download (bandwidth.c:220)
    [20:30:55.867] 0 peers to go round-robin for download (bandwidth.c:220)

I am happy to supply more logs if you would like.

**Comment by orignal** [comment]
where can I get the transmission's source code from?

**Comment by mathiasfriman** [comment]
If I'm not completely mistaken, by downloading the torrent in the above post?

http://zzz.i2p/files/transmission-2.82.tar.xz.torrent

**Comment by mathiasfriman** [comment]
If the above does not work: http://bioq5jbcnfopqwvk7qssaxcl7avzeta6mu72jmxjeowflpcrhf6q.b32.i2p/transmission

**Comment by majestrate** [comment]
it seems that bob has an undocumented command called `test`, not sure what it does but i'll check.

**Comment by majestrate** [comment]
actually no i am wrong, huh

**Comment by orignal** [comment]
I doubt that's a command, I think that's result of a malformed message

**Comment by orignal** [comment]
@mathiasfriman where do you specify BOB's IP/Port?
@majestrate I see the mess in libbob
if( firsttimever || cctx->socket == -1 || write( cctx->socket, "test\n", 5) != 5 ) {

I don't know what is it for and how I should handle it

**Comment by majestrate** [comment]
yeah i can't make sense of transmission either, not sure what it's doing

**Comment by mathiasfriman** [comment]
@orignal It is specified in a settings.json file which default location is `~/.config/transmission/settings.json` 

I've made mine available here: http://paste.debian.net/780227/

The critical settings in question are 

    "i2p-bob-port": 2827,
    "i2p-enabled": true,
    "i2p-proxy-port": 2827,
    "i2p-router": "127.0.0.1",
    "i2p-tunnel-mode": 1,

One would think that i2p-proxy-port would be 4444, but that does not work. This config file works, with Java I2P that is.

**Comment by majestrate** [comment]
try i2p-proxy-port to be an unused port like 51515

**Comment by majestrate** [comment]
i think i see the problem, bob creates tunnel and does not wait until tunnels are ready to return success or error.

**Comment by majestrate** [comment]
i see another problem, when doing tcpdump, transmission sends `setport -2` which should be disallowed by bob

**Comment by orignal** [comment]
BOB should wait for at least one IB and OB

**Comment by orignal** [comment]
@majestrate why should it be disallowed?

**Comment by majestrate** [comment]
port number is negative. that shouldn't happen.

**Comment by orignal** [comment]
How can it be a negative? -2 or 65534?

**Comment by majestrate** [comment]
when investigating trafic with tcpdump i see `outport -2` in the traffic

**Comment by mathiasfriman** [comment]
If it's of any help, I think the developer of I2PTransmission can be reached in this thread: http://zzz.i2p/topics/2141-i2p-and-transmission

**Comment by mathiasfriman** [comment]
Sorry for posting quotes, but may be nice to know.

Developer writes in first response:
> The real problem is that i2pd cannot create the tunnel for bob. I try to investigate. 
i2pd error?, bob-transmission implementation error? or both?

Second response:
> No commandhandler found for "status" in BOB.cpp for i2pd, the tunnel is not started by bob-transmission without this "status" response 
Will try to implement and test

**Comment by orignal** [comment]
let me check

**Comment by orignal** [comment]
Implemented

**Comment by mathiasfriman** [comment]
Thanks for a quick response! I pulled, compiled and tried for a couple of hours, but your fix doesn't seem to solve the problem. All I get from i2pd is

`xx:xx:xx@151/info - BOB: New command connection from 127.0.0.1:41416`

And then nothing happens. No status message from your newly implemented StatusCommandHandler ... :/

**Comment by orignal** [comment]
Please run it with debug logs

**Comment by mathiasfriman** [comment]
AFAICT, this is the output from BOB in i2pd:

    21:06:50@92/info - BOB: New command connection from 127.0.0.1:51498
    21:06:50@92/debug - BOB: getnick TRZ-2d545232-5235
    21:06:50@92/debug - BOB: quiet
    21:06:50@92/debug - BOB: setnick TRZ-2d545232-5235
    21:06:50@92/debug - BOB: quiet
    21:06:50@92/debug - BOB: newkeys
    21:06:50@92/debug - BOB: quiet
    21:06:50@92/debug - BOB: outhost 127.0.0.1
    21:06:50@92/debug - BOB: quiet
    21:06:50@92/debug - BOB: outport -2
    21:06:50@92/debug - BOB: quiet
    21:06:50@92/debug - BOB: inhost 127.0.0.1
    21:06:50@92/debug - BOB: quiet
    21:06:50@885/warn - Tunnel: tunnel not found, tunnelID=3452903362 previousTunnelID=0 type=19
    21:06:50@92/debug - BOB: inport -1
    21:06:50@92/debug - BOB: quiet
    21:06:50@92/debug - BOB: option i2cp.gzip=False
    21:06:50@92/debug - BOB: quiet
    21:06:50@92/debug - BOB: option outbound.quantity=3
    21:06:50@92/debug - BOB: quiet
    21:06:50@906/debug - SSU: Process data, flags=132, len=347
    21:06:50@92/debug - BOB: option inbound.quantity=3
    21:06:50@885/warn - Tunnel: tunnel not found, tunnelID=3452903362 previousTunnelID=0 type=19
    21:06:50@92/debug - BOB: quiet
    21:06:50@92/debug - BOB: option outbound.backupQuantity=0
    21:06:50@92/debug - BOB: quiet
    21:06:50@92/debug - BOB: option inbound.backupQuantity=0
    21:06:50@92/debug - BOB: quiet
    21:06:50@92/debug - BOB: option outbound.length=1
    21:06:50@92/debug - BOB: quiet
    21:06:50@92/debug - BOB: option inbound.length=1
    21:06:50@92/debug - BOB: quiet
    21:06:51@92/debug - BOB: option outbound.lengthVariance=1
    21:06:51@92/debug - BOB: quiet
    21:06:51@92/debug - BOB: option inbound.lengthVariance=1
    21:06:51@92/debug - BOB: quiet
    21:06:51@92/debug - BOB: getnick TRZ-2d545232-5235
    [..]
    21:06:53@92/debug - BOB: quiet
    21:06:53@92/debug - BOB: getnick TRZ-2d545232-5235
    21:06:53@92/debug - BOB: quiet
    21:06:53@92/debug - BOB: setnick TRZ-2d545232-5235
    21:06:53@92/debug - BOB: quiet
    21:06:53@92/debug - BOB: newkeys
    21:06:53@92/debug - BOB: quiet
    21:06:53@92/debug - BOB: outhost 127.0.0.1
    21:06:53@92/debug - BOB: quiet
    21:06:53@92/debug - BOB: outport 51411
    21:06:53@92/debug - BOB: quiet
    21:06:53@92/debug - BOB: inhost 127.0.0.1
    21:06:53@92/debug - BOB: quiet
    21:06:53@92/debug - BOB: inport 51412
    21:06:53@92/debug - BOB: quiet
    21:06:53@92/debug - BOB: option i2cp.gzip=False
    21:06:53@92/debug - BOB: quiet
    21:06:53@92/debug - BOB: option outbound.quantity=3
    21:06:53@92/debug - BOB: quiet
    21:06:53@92/debug - BOB: option inbound.quantity=3
    21:06:53@92/debug - BOB: quiet
    21:06:53@92/debug - BOB: option outbound.backupQuantity=0
    21:06:53@92/debug - BOB: quiet
    21:06:53@92/debug - BOB: option inbound.backupQuantity=0
    21:06:53@92/debug - BOB: quiet
    21:06:53@92/debug - BOB: option outbound.length=1
    21:06:53@885/debug - TunnelMessage: handle fragment of 28 bytes, msg type 10
    21:06:53@92/debug - BOB: quiet
    21:06:53@885/debug - I2NP: Handling message with type 10
    21:06:53@885/debug - Tunnels: test of 2726890627 successful. 1236 milliseconds
    21:06:53@92/debug - BOB: option inbound.length=1
    21:06:53@92/debug - BOB: quiet
    21:06:53@92/debug - BOB: option outbound.lengthVariance=1
    21:06:53@92/debug - BOB: quiet
    21:06:53@92/debug - BOB: option inbound.lengthVariance=1
    21:06:53@92/debug - BOB: quiet
    21:06:53@92/debug - BOB: getnick TRZ-2d545232-5235

A bigger chunk of the debug-log: http://paste.debian.net/782083/

**Comment by orignal** [comment]
I don't see see any 'start' command, but settings for a destination. That's probably the reason.

**Comment by mathiasfriman** [comment]
The dev writes:

> the bridge must return a message like this "OK DATA NICKNAME: TRZ-7f000001-5495 STARTING: false RUNNING: true STOPPING: false KEYS: true QUIET: false INPORT: 51414 INHOST: 127.0.0.1 OUTPORT: 51413 OUTHOST: 127.0.0.1" to Transmission

In accordance with the data in the second BOB call, that is. 

> The good news is that i2pd SAM bridge works fine with hacked libtorrent (for qbittorrent, deluge or flush) after 5~10 minutes

However, for me, it's not working regardless of how long I try.

**Comment by orignal** [comment]
what command this reply is supposed to be sent to?

**Comment by mathiasfriman** [comment]
Not sure, I've asked but not gotten any response yet. However, there is a function transmission source code in `third-party/libbob/bob.c`:

    // OK DATA NICKNAME: TRZ-7f000001-5495 STARTING: false RUNNING: true STOPPING: false KEYS: true QUIET: false INPORT: 51414 INHOST: 127.0.0.1 OUTPORT: 51413 OUTHOST: 127$
    int _bob_status_response(char *response,_bob_tunnel_t *tunnel) {
        while(response[0]=='\n')
                response++;
        char *starting=strstr(response,"STARTING: ");
        char *running=strstr(response,"RUNNING: ");
        char *stopping=strstr(response,"STOPPING: ");

        tunnel->status=0;
        if(starting && running && stopping) {
                if(strncmp(starting+strlen("STARTING: "),"true",4)==0)
                        tunnel->status|=TUNNEL_STATUS_STARTING_FLAG;
                if(strncmp(running+strlen("RUNNING: "),"true",4)==0)
                        tunnel->status|=TUNNEL_STATUS_RUNNING_FLAG;
                if(strncmp(stopping+strlen("STOPPING: "),"true",4)==0)
                        tunnel->status|=TUNNEL_STATUS_STOPPING_FLAG;

        } 
        return BOB_OK;
    }

**Comment by orignal** [comment]
I will take a  look at Java source code

**Comment by orignal** [comment]
Try now

**Comment by mathiasfriman** [comment]
No immediate success. I've had some general issues with i2pd so I deleted my whole .i2pd directory and started over. I'll let it run a couple of hours and try again later.

**Comment by mathiasfriman** [comment]
Seems to be the same as before. The i2pd debug log prints:

    17:05:00@526/error - BOB: unknown command test
    17:05:00@526/error - BOB: unknown command test
    17:05:00@526/debug - BOB: getnick TRZ-2d545232-22915
    17:05:00@526/error - BOB: unknown command test
    17:05:00@526/debug - BOB: getnick TRZ-2d545232-22915
    17:05:00@526/error - BOB: unknown command test
    17:05:00@526/debug - BOB: setnick TRZ-2d545232-22915
    17:05:00@526/error - BOB: unknown command test
    17:05:00@526/debug - BOB: newkeys
    17:05:00@526/error - BOB: unknown command test
    17:05:00@526/debug - BOB: outhost 127.0.0.1
    17:05:00@526/error - BOB: unknown command test
    17:05:00@526/debug - BOB: outport 51411
    17:05:00@526/error - BOB: unknown command test
    17:05:00@526/debug - BOB: inhost 127.0.0.1
    17:05:00@526/error - BOB: unknown command test
    17:05:00@526/debug - BOB: inport 51412
    17:05:00@526/error - BOB: unknown command test
    17:05:00@526/debug - BOB: option i2cp.gzip=False
    17:05:00@526/error - BOB: unknown command test
    17:05:00@526/debug - BOB: option outbound.quantity=3
    17:05:00@526/error - BOB: unknown command test
    17:05:00@526/debug - BOB: option inbound.quantity=3
    17:05:00@526/error - BOB: unknown command test
    17:05:00@526/debug - BOB: option outbound.backupQuantity=0
    17:05:00@526/error - BOB: unknown command test
    17:05:00@526/debug - BOB: option inbound.backupQuantity=0
    17:05:00@526/error - BOB: unknown command test
    17:05:00@526/debug - BOB: option outbound.length=1
    17:05:00@526/error - BOB: unknown command test
    17:05:00@526/debug - BOB: option inbound.length=1
    17:05:00@526/error - BOB: unknown command test
    17:05:00@526/debug - BOB: option outbound.lengthVariance=1
    17:05:00@526/error - BOB: unknown command test
    17:05:00@526/debug - BOB: option inbound.lengthVariance=1
    17:05:00@526/error - BOB: unknown command test
    17:05:00@526/debug - BOB: getnick TRZ-2d545232-22915

And transmission prints 

    Starting up I2P tunnel for session

every 10 seconds. But is it something else I should look for?

**Comment by orignal** [comment]
Is there a way to log all BOB messages at transmission's side against Java router?

**Comment by mathiasfriman** [comment]
Ok. So this is what I can decipher from wireshark to and from port 2827 (BOB (B)) <-> 37828 (Transmission (T)):

T->B: getnick TRZ-2d545232-16821
B->T: ERROR no nickname has been set
T->B: quiet
B->T: ERROR no nickname has been set
T->B: setnick TRZ-2d545232-16821
B->T: OK Nickname set to TRZ-2d545232-16821
T->B: quiet
B->T: OK Quiet set
T->B: newkeys
B->T: OK QLTjum[..]guAAAAA
T->B: quiet
B->T: OK Quiet set
T->B: outhost 127.0.0.1
B->T: OK outhost set 
T->B: outport -2
B->T: ERROR port out of range
T->B: getnick TRZ-2d545232-16821
B->T: OK Nickname set to TRZ-2d545232-16821
T->B: stop
B->T: ERROR tunnel is inactive
T->B: clear
B->T: OK cleared
T->B: quiet
B->T: ERROR no nickname has been set
T->B: setnick TRZ-2d545232-16821
B->T: OK Nickname set to TRZ-2d545232-16821
T->B: newkeys
B->T: OK zYQ4G[..]VAAAA
T->B: outhost 127.0.0.1
B->T: OK outhost set
T->B: outport 51411
B->T: OK outbound port set
T->B: inhost 127.0.0.1
B->T: OK inhost set
T->B: inport 51412
B->T: OK inbound port set
T->B: option i2cp.gzip=False
B->T: OK i2pc.gzip set to False
T->B: option outbound.quantity=3
B->T: OK outbound.quantity set to 3
[..]
T->B: option inbound.lengthVariance=1
B->T: OK inbound.lengthVariance set to 1
T->B: getnick TRZ-2d545232-16821
B->T: OK Nickname set to TRZ-2d545232-16821
T->B: start
B->T: OK Tunnel starting 
T->B: quiet
B->T: ERROR tunnel is active
T->B: quiet
B->T: ERROR tunnel is active
T->B: getnick TRZ-2d545232-16821
B->T: OK Nickname set to TRZ-2d545232-16821
T->B: quiet
B->T: ERROR tunnel is active
T->B: status TRZ-2d545232-16821
B->T: OK
T->B: [ACK-package]
B->T: DATA NICKNAME: TRZ-2d545232-16821 STARTING: false RUNNING: true STOPPING: false KEYS: true QUIET: false INPORT: 51412 INHOST: 127.0.0.1 OUTPORT: 51411 OUTHOST: 127.0.0.1
T->B: [ACK-package]
quiet
getnick
etc etc..

pcap file:
http://s000.tinyupload.com/?file_id=70815123121931971932

**Comment by orignal** [comment]
Thanks. Will implement it accordingly

**Comment by mathiasfriman** [comment]
Please note (if it wasn't obvious) that [ACK]-package is no actual BOB command. In the text I've also left out a number of "quiet" commands that seems to have no real function. See the pcapng file for the whole set.

**Comment by orignal** [comment]
Try again. If still doesn't work, please run sniffer again with i2pd. We need to see the difference

**Comment by mathiasfriman** [comment]
Ok, here goes:

T->B: getnick TRZ-2d545232-31907
B->T: ERROR no nickname has been set
T->B: quiet
B->T: ERROR no nickname has been set
T->B: setnick TRZ-2d545232-31907
B->T: OK Nickname set to TRZ-2d545232-31907
T->B: quiet
B->T: OK quiet set
T->B: newkeys
B->T: OK a4ZXB[..]8AAAA
T->B: quiet
B->T: OK Quiet set
T->B: outhost 127.0.0.1
B->T: OK outhost set
T->B: outport -2
B->T: ERROR port out of range
T->B: quiet
B->T: OK Quiet set
T->B: getnick TRZ-2d545232-31907
B->T: ERROR no nickname has been set
T->B: quiet
B->T: OK Quiet set
T->B: setnick TRZ-2d545232-31907
B->T: OK Nickname set to TRZ-2d545232-31907
T->B: quiet
B->T: OK Quiet set
T->B: newkeys
B->T: OK eVEP2[..]1AAAA
T->B: quiet
B->T: OK Quiet set
T->B: outhost 127.0.0.1
B->T: OK outhost set
T->B: outport 51411
B->T: OK outbound port set
T->B: inhost 127.0.0.1
B->T: OK inhost set
T->B: inport 51412
B->T: OK inbound port set
T->B: option i2cp.gzip=False
B->T: OK i2pc.gzip set to False
T->B: option outbound.quantity=3
B->T: OK outbound.quantity set to 3
[..]
T->B: option inbound.lengthVariance=1
B->T: OK inbound.lengthVariance set to 1
**T->B: getnick TRZ-2d545232-31907**
**B->T: ERROR no nickname has been set**
T->B: quiet
B->T: OK Quiet set
T->B: quiet
B->T: OK Quiet set
T->B: getnick TRZ-2d545232-31907
B->T: ERROR no nickname has been set
T->B: quiet
B->T: OK Quiet set
T->B: setnick TRZ-2d545232-31907
B->T: OK Nickname set to TRZ-2d545232-31907

And then it loops forever. Seems that the java I2P retains the nickname and recognizes it with the **getnick** command, but i2pd does not recognize it in the bold command sequence above. So no **start** command is sent from Transmission.

That is at least my interpretation of this. 

Here is the pcapng file: http://s000.tinyupload.com/?file_id=42688421792163383236

**Comment by orignal** [comment]
That explains. Will change the logic

**Comment by orignal** [comment]
Try now, if still doesn't work, I will have to do some refactoring

**Comment by mathiasfriman** [comment]
Nope, still doesn't work. Seems that the commands come in a weird order. This is what I get from the i2pd debug log:

    14:02:01@222/debug - BOB: quiet
    14:02:01@222/debug - BOB: getnick TRZ-2d545232-14128
    14:02:01@222/debug - BOB: quiet
    14:02:01@222/debug - BOB: stop TRZ-2d545232-14128
    14:02:02@222/debug - BOB: quiet
    14:02:02@222/debug - BOB: clear
    14:02:02@222/debug - BOB: quiet
    14:02:02@222/debug - BOB: setnick TRZ-2d545232-14128
    14:02:02@222/debug - BOB: quiet
    14:02:02@222/debug - BOB: newkeys
    14:02:02@222/debug - BOB: quiet
    14:02:02@222/debug - BOB: outhost 127.0.0.1
    14:02:02@222/debug - BOB: quiet
    14:02:02@222/debug - BOB: outport 51411
    14:02:02@222/debug - BOB: quiet
    14:02:02@222/debug - BOB: inhost 127.0.0.1
    14:02:02@222/debug - BOB: quiet
    14:02:02@222/debug - BOB: inport 51412
    14:02:02@222/debug - BOB: quiet
    14:02:02@222/debug - BOB: option i2cp.gzip=False
    14:02:02@222/debug - BOB: quiet
    14:02:02@222/debug - BOB: option outbound.quantity=3
    14:02:02@222/debug - BOB: quiet
    14:02:02@222/debug - BOB: option inbound.quantity=3
    14:02:02@222/debug - BOB: quiet
    14:02:02@222/debug - BOB: option outbound.backupQuantity=0
    14:02:02@222/debug - BOB: quiet
    14:02:02@222/debug - BOB: option inbound.backupQuantity=0
    14:02:02@222/debug - BOB: quiet
    14:02:02@222/debug - BOB: option outbound.length=1
    14:02:02@222/debug - BOB: quiet
    14:02:02@222/debug - BOB: option inbound.length=1
    14:02:02@222/debug - BOB: quiet
    14:02:02@222/debug - BOB: option outbound.lengthVariance=1
    14:02:02@222/debug - BOB: quiet
    14:02:02@222/debug - BOB: option inbound.lengthVariance=1
    14:02:02@222/debug - BOB: quiet
    14:02:02@222/debug - BOB: getnick TRZ-2d545232-14128
    14:02:02@222/debug - BOB: quiet
    14:02:02@222/debug - BOB: start TRZ-2d545232-14128
    14:02:03@222/debug - BOB: quiet
    14:02:03@222/debug - BOB: quiet
    14:02:03@222/debug - BOB: getnick TRZ-2d545232-14128
    14:02:03@222/debug - BOB: quiet
    14:02:03@222/debug - BOB: status TRZ-2d545232-14128
    14:02:03@222/debug - BOB: quiet
    14:02:03@222/debug - BOB: getnick TRZ-2d545232-14128
    14:02:03@222/debug - BOB: quiet
    14:02:03@222/debug - BOB: start TRZ-2d545232-14128
    14:02:03@222/debug - BOB: quiet
    14:02:03@222/debug - BOB: getnick TRZ-2d545232-14128
    14:02:03@222/debug - BOB: quiet
    14:02:03@222/debug - BOB: start TRZ-2d545232-14128
    14:02:04@222/debug - BOB: quiet
    14:02:04@222/debug - BOB: quiet
    14:02:04@222/debug - BOB: getnick TRZ-2d545232-14128
    14:02:04@222/debug - BOB: quiet
    14:02:04@222/debug - BOB: status TRZ-2d545232-14128
    14:02:04@222/debug - BOB: quiet
    14:02:04@222/debug - BOB: getnick TRZ-2d545232-14128
    14:02:04@222/debug - BOB: quiet
    14:02:04@222/debug - BOB: start TRZ-2d545232-14128
    14:02:04@222/debug - BOB: quiet
    14:02:04@222/debug - BOB: getnick TRZ-2d545232-14128
    14:02:04@222/debug - BOB: quiet
    14:02:04@222/debug - BOB: start TRZ-2d545232-14128
    14:02:05@222/debug - BOB: quiet
    14:02:05@222/debug - BOB: quiet
    14:02:05@222/debug - BOB: getnick TRZ-2d545232-14128
    14:02:05@222/debug - BOB: quiet
    14:02:05@222/debug - BOB: status TRZ-2d545232-14128
    14:02:05@222/debug - BOB: quiet
    14:02:05@222/debug - BOB: getnick TRZ-2d545232-14128
    14:02:05@222/debug - BOB: quiet
    14:02:05@222/debug - BOB: start TRZ-2d545232-14128

I'll run another round of wireshark and see the responses.

**Comment by mathiasfriman** [comment]
The response from Java I2P BOB is:
B->T: DATA NICKNAME: TRZ-2d545232-16821 **STARTING: false RUNNING: true** STOPPING: false KEYS: true QUIET: false INPORT: 51412 INHOST: 127.0.0.1 OUTPORT: 51411 OUTHOST: 127.0.0.1

And from i2pd BOB:
B->T: DATA NICKNAME: TRZ-2d545232-15923 **STARTING: true RUNNING: false** STOPPING: false KEYS: true QUIET: false INPORT: 51412 INHOST: 127.0.0.1 OUTPORT: 51411 OUTHOST: 127.0.0.1

Not sure if this is significant, but in Transmission source code (`third-party/libbob/bob.c`) it says **STARTING: false RUNNING: true**

**Comment by orignal** [comment]
That's important part.
STARTING: true and RUNNING:false means we are starting tunnels but don't have them ready it.
Not sure if Java waits and doesn't respond to 'strart' until tunnels got built.
In my opinion it should respond immediately, but maybe Java  does it different.

**Comment by mathiasfriman** [comment]
If this refers to the BOB tunnel, it is already started in previous commands, and therefore maybe it should be RUNING: true as a response to the status command?

**Comment by orignal** [comment]
Than how how you know if it's ready to use? I believe that's what 'status' command for.
I can change the code to wait for it but not sure if it's right

**Comment by mathiasfriman** [comment]
I changed the code in BOB.cpp on row 574 here on my machine to read: 
`s << " STARTING:false RUNNING:true STOPPING:false";`
and it made no difference. Still not discovering peers. So I guess you're right.

I'm stumped and have no idea how to move forward..

**Comment by orignal** [comment]
If it start but doesn't discover peers you should look at web-console or log file if it requests LeaseSets and create streams.
Or even better to run wireshark against a second connection. It listens port 51412 according to your log. See if anything goes through it. You should see connection and first message must be an adresses of your peer.

**Comment by mathiasfriman** [comment]
What I can see from scanning port 51412 when running i2pd:
B->T: TCP 74 [SYN]
T->B: TCP 74 [SYN, ACK]
B->T: TCP 66 [ACK]
B->T: TCP 922 [PSH, ACK] <- Tracker request
T->B: TCP 66 [ACK]
T->B: TCP 66 [FIN, ACK]
B->T: TCP 66 [ACK]
B->T: TCP 66 [FIN, ACK]
T->B: TCP 54 [RST]

When I run java I2P I get (B: 44553 (BOB) T: 51412 (Transmission) D: 44554 (BOB data?):
B->T: TCP 74 [SYN]
T->B: TCP 74 [SYN, ACK]
B->T: TCP 66 [ACK]
B->T: HTTP 922 [Continuation or non-HTTP traffic] <- tracker request
T->B: TCP 66 [ACK]
T->B: HTTP 837 [HTTP/1.1 200 OK (text/plain)]
B->T: TCP 66 [ACK]
B->T: TCP 66 [FIN, ACK]
T->B: TCP 66 [FIN, ACK]
B->T: TCP 66 [ACK]
D->T: TCP 74 [SYN]
T->D: TCP 74 [SYN, ACK]
D->T: TCP 66 [ACK] 
D->T: TCP 127 [hwixsdlkjsflkjsdlje3icp7oemn8cuewieoa.b32.i2p]
and so on..

**Comment by orignal** [comment]
Looks like the direction should be inverted.
As I see "B->T: TCP 922 [PSH, ACK] <- Tracker request" is actually tracker request from Transmission to I2P and it was not responded. 
We need to look at the content and streams created by it.

**Comment by mathiasfriman** [comment]
Poor wording on my part. 

It is a GET request for `/announce.php?info_hash=` 

In Java I2P it is the same direction, and Transmission responds with a HTTP/1.1 200 OK stating the number of peers etc.

**Comment by orignal** [comment]
Who creates this session? Transmission or BOB?

**Comment by mathiasfriman** [comment]
The first command is sent from BOB to Transmission in both cases, have no idea who creates the session.

Transmission debug log states:
`Tracker gave an error:: Tracker gave HTTP response code 0 (No Response)`
when i2pd BOB tries to GET and gets nothing back.

i2pd pcap: http://s000.tinyupload.com/?file_id=49711181834715823764
java i2p pcap: http://s000.tinyupload.com/?file_id=87090168022605935536

**Comment by orignal** [comment]
That means Transmission sends request to tracker through th I2P and doesn't get a response back.
Probably I would have to run Transmission myself to find out what's wrong.

**Comment by mathiasfriman** [comment]
Yeah, if you run any debian based distro the instructions in the first post here should make a good starting point. I'm afraid my skills are inadequate when it comes to these things.

**Comment by mathiasfriman** [comment]
I guess you saw that java I2P sends announce GET request identified as HTTP by Wireshark, while i2pd sends it as TCP? Could that impact what kind of response (response code 0 (Empty Response)) we get?

**Comment by orignal** [comment]
If you still believe it goes that direction(e.g. from I2P to transmission) that's probably about 'quiet' setting. Quiet basically tells if a remote address must be sent first or not

**Comment by mathiasfriman** [comment]
I have linked the capture files here: https://github.com/PurpleI2P/i2pd/issues/568#issuecomment-234620611 so you can see for yourself if you have Wireshark available.

**Comment by mathiasfriman** [comment]
according to Transmission dev. QUIET must be set to **false** in the status response in order for Transmission to work. In my last test, it was set to **true**.

**Comment by orignal** [comment]
I have fixed both issues with I2P connection status and no reponse.
Basically last one is Transmission's bug, they send '\r\n' terminated address instead '\n\' as required by BOB protocol. Please let them know. I have placed the workaround in my code.
However one Transmission get announce from tracker it crashes. That's beyond of my knowledge.

**Comment by mathiasfriman** [comment]
It may be that the segfault happens because of a malformed settings.json file. However, it worked for me and I actually got transmission-cli to download a file! 

Thanks a lot for your tenacious work! :)

**Comment by orignal** [comment]
Can we close the issue?

**Comment by mathiasfriman** [comment]
Yes, of course. :)

**Comment by faissaloo** [comment]
Why has this been closed? It's still an issue. I haven't been able to get I2PD working with transmission at all, I keep getting the same error OP described.

**Comment by orignal** [comment]
@faissaloo because it worked from many people.
Try to use transmission from https://github.com/l-n-s/transmission-i2p

**Comment by faissaloo** [comment]
@orignal I just did, I'm still getting the same issue.

**Comment by orignal** [comment]
Have you enabled BOB?

**Comment by faissaloo** [comment]
Yes, I even double checked by starting i2pd like this:  
```
i2pd --bob.enabled 1 --bob.address 127.0.0.1 --bob.port 2827
```  
I'm still getting:  
```
15:47:00@821/error - BOB: unknown command test
```

**Comment by orignal** [comment]
unknown command 'test' is fine.  transmission really sends this message just to get error message back.
Than what's the issue? It doesn't connect to the network, doesn't download or what?

**Comment by faissaloo** [comment]
It seems to be stuck at 'I2P tunnel is starting up'.

**Comment by orignal** [comment]
probably it can't build tunnels.
Does anything else work, like eepsites or other?

**Comment by faissaloo** [comment]
Ok, if I leave I2PD on for a while before I start Transmission-I2P I get "I2P Tunnel is up and running". But if I try to start a torrent anything Transmission-I2P segfaults.

**Comment by orignal** [comment]
I can't help with Transmission itself.
AFAIK it's a configuration issue.

**Comment by faissaloo** [comment]
Well, thanks for your time anyway :)
