### ISSUE TITLE
Не запускается на андроиде 4.1 (API 16)

### ISSUE THREAD

**Issue by orignal** [PurpleI2P/i2pd#573]
При  старте кидает эксепшин со словами
Cannot load library: link_image[1891]: 85 could not load needed library 'libgnustl_shared.so' for 'libi2pd.so'(load_library[1093]: Library 'libgnustl_shared.so' not found)

**Comment by hypnosis-i2p** [comment]
http://stackoverflow.com/questions/11058898/loading-shared-libs-that-depend-on-other-shared-libs
