### ISSUE TITLE
Missing ipv6 support causes exception: "Address family not supported by protocol"

### ISSUE THREAD

**Issue by lehitoskin** [PurpleI2P/i2pd#579]
I have compiled and installed i2pd on my Raspberry Pi 1 (model B). I start the daemon, but after a little while I get this error:

```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  open: Address family not supported by protocol
```

Interesting. Address family not supported? That probably means IPv6.

Sure enough, disabling IPv6 in the config helped. Does anyone know why this might be? It works just fine on my PC, which is on the same network.

**Comment by orignal** [comment]
I don't see any ipv6 addresses at my RPi either (Raspbian).
Probably you need to change something in OS's config

**Comment by atnaguzin** [comment]
Does your network has IPv6 support?
Check, what IPv6 address getting your RaspberryPi. If it starts from fe80: - you havent access to clearnet via them, and i2pd woudnt work with IPv6 => you see that error.

**Comment by lehitoskin** [comment]
On the pi there isn't an IPv6 address.

**Comment by ZenifiedFromI2P** [comment]
Should I2Pd find it on runtime that if IPv6 is available, do IPv6-related stuffs, otherwise not.

**Comment by r4sas** [comment]
Reopen if problem still exists. Too much changes in sockets was done in last year.
