### ISSUE TITLE
Android — на апи9 не встает

### ISSUE THREAD

**Issue by hypnosis-i2p** [PurpleI2P/i2pd#582]
[06:01:00] MXPLRS|Kirill> на 9й не встает

**Comment by atnaguzin** [comment]
Перекомпилил на armeabi (без v7a).
Приложение терминируется после запуска:

> 01-03 05:11:31.500 W/dalvikvm(11364): VFY: unable to resolve virtual method 11175: Lorg/purplei2p/i2pd/I2PD;.finishAndRemoveTask ()V
> 01-03 05:11:31.500 D/dalvikvm(11364): VFY: replacing opcode 0x6e at 0x0006
> 01-03 05:11:31.507 W/dalvikvm(11364): VFY: unable to resolve virtual method 11174: Lorg/purplei2p/i2pd/I2PD;.finishAffinity ()V
> 01-03 05:11:31.507 D/dalvikvm(11364): VFY: replacing opcode 0x6e at 0x0019
> 01-03 05:11:31.507 D/dalvikvm(11364): VFY: dead code 0x001c-001c in Lorg/purplei2p/i2pd/I2PD;.quit ()V
> 01-03 05:11:31.507 I/i2pd    (11364): daemon state change: starting
> 01-03 05:11:31.515 D/dalvikvm(11364): Trying to load lib /data/data/org.purplei2p.i2pd/lib/libgnustl_shared.so 0x40516d70
> 01-03 05:11:31.523 D/dalvikvm(11364): Added shared lib /data/data/org.purplei2p.i2pd/lib/libgnustl_shared.so 0x40516d70
> 01-03 05:11:31.523 D/dalvikvm(11364): No JNI_OnLoad found in /data/data/org.purplei2p.i2pd/lib/libgnustl_shared.so 0x40516d70, skipping init
> 01-03 05:11:31.523 D/dalvikvm(11364): Trying to load lib /data/data/org.purplei2p.i2pd/lib/libi2pd.so 0x40516d70

**Comment by orignal** [comment]
9 фтопку

**Comment by hypnosis-i2p** [comment]
не, не фтопку нифига
