### ISSUE TITLE
Постоянные падения без объяснения причины (win7x64)

### ISSUE THREAD

**Issue by randomboygh** [PurpleI2P/i2pd#585]
Очень часто вылетает: от вылета сразу же после запуска до пары часов. В логах ничего необычного - крашится каждый раз на разных моментах.
Конфиг:
```
log = file
loglevel = debug
ipv4 = true
ipv6 = false
bandwidth = X

[http]
address = 127.0.0.1
port = 7070

[httpproxy]
address = 127.0.0.1
port = 4444

[socksproxy]
enabled = false
```

**Comment by orignal** [comment]
ОС?

**Comment by randomboygh** [comment]
win7x64
Microsoft Windows [Version 6.1.7601]

**Comment by orignal** [comment]
2.8.0 или транк?

**Comment by randomboygh** [comment]
Перебрал все релизы отсюда: https://github.com/PurpleI2P/i2pd/releases/tag/2.8.0
Самым стабильным оказывается вариант с консолью - i2pd_2.8.0_win32_mingw_cli.zip

**Comment by orignal** [comment]
Это известная проблема с виндой. Я вроде починил, по крайней мере у меня в течение 5 часов не упало. Потом остановил.
Счас  я соберу текущий и выложу

**Comment by randomboygh** [comment]
Спасибо. Жду для проверки.
А то ведь даже к стороннему софту пришлось прибегнуть, чтобы перезапускалось при падениях, но он, почему-то тоже не сильно помог.

**Comment by orignal** [comment]
https://github.com/PurpleI2P/i2pd/releases/download/2.8.0/i2pd_2.9.0_RC_win32_mingw.zip

Сразу с встроенным UPnP

**Comment by randomboygh** [comment]
Запустил. О результатах отпишусь.

**Comment by randomboygh** [comment]
Снова вылет :crying_cat_face:

**Comment by orignal** [comment]
Тут непонятно почему происходил. У некоторых вылетает у некоторых нет.
Я бы для начала убрал bandwidth=X

**Comment by randomboygh** [comment]
Сейчас попробую уменьшить пропускную способность, но вот не повлияет ли это на доступ к веб-серверу, который смотрит внутрь i2p?
И да, нет ли какой дебаг-версии, чтобы хоть понимать, из-за чего падения?

**Comment by orignal** [comment]
Не повлияет. Только на транзит.
Можно запустить из-за под gdb, но там обычно показывает падение в каком то дурацком месте типа чтения символа из потока, что мало говорит о причинах.
Сейчас попробую собрать 64

**Comment by randomboygh** [comment]
Поменял bandwidth на P - пока работает, но надолго ли. В среднем вылеты от 10 минут до двух часов - дольше продержаться не выходило.
Хорошо, спасибо.

**Comment by orignal** [comment]
Не надо на P, лучше пока на L.

**Comment by randomboygh** [comment]
Сделал.

**Comment by orignal** [comment]
Собрал под 64
https://github.com/PurpleI2P/i2pd/releases/download/2.8.0/i2pd_2.9.0_RC_win64_mingw.zip

**Comment by randomboygh** [comment]
После выставления на L 32-битная версия еще не вылетела. Сейчас попробую эту, но верну bandwidth снова на Х в целях эксперимента.

**Comment by orignal** [comment]
Так сеть устроена, что роутеры начиная с 'O' гораздо более популярные для транзита чем более низкие. А если уже экспериментировать с X, то может быть имеет смысл и флудфил включить? @mlt успешно запускал виндовый флудфил но он собирал под 64  с помощью Visual Studio.

**Comment by randomboygh** [comment]
floodfill = true
Поехали.

**Comment by randomboygh** [comment]
Пока все на удивление хорошо: ест 26 МБ памяти и 3% ЦП. Но и нагрузка, вроде, небольшая:
```
Uptime: 11 min, 52 seconds
Status: OK
Tunnel creation success rate: 34%
Received: 17.41 MiB (21.76 KiB/s)
Sent: 16.00 MiB (25.66 KiB/s)

Routers: 4607 Floodfills: 1356 LeaseSets: 47
Client Tunnels: 49 Transit Tunnels: 329
```

**Comment by orignal** [comment]
А когда он столько ротутеров успел насобирать? Routers: 4607 Floodfills: 1356
Это же надо несколько часов работы.

**Comment by randomboygh** [comment]
Я просто на М9 сижу :smile_cat: 
А вообще, это не может быть его работа в предыдущие часы?

**Comment by orignal** [comment]
Может. Но это значит что он не сразу падал, а работал довольно долго.

**Comment by randomboygh** [comment]
Хм, то есть каждый раз он начинает собирать router'ы и floodfill'ы с нуля? Я могу перезапустить и посмотреть, что он покажет при запуске - может быть наведет на какие-нибудь мысли по поводу вылетов

**Comment by randomboygh** [comment]
```
Uptime: 3 seconds
Status: OK
Tunnel creation success rate: 0%
Received: 53.69 KiB (0.00 KiB/s)
Sent: 42.97 KiB (0.00 KiB/s)

Routers: 4668 Floodfills: 1361 LeaseSets: 0
Client Tunnels: 2 Transit Tunnels: 0
```

**Comment by orignal** [comment]
Разумеется не с нуля, просто чтобы набралось достаточно роутеров надо чтобы  довольно трафика прошло.

**Comment by randomboygh** [comment]
А, если об этом речь, то я его мучаю уже дня 4, периодически перезапуская либо вручную, либо скриптом, который следит, не повисло ли все снова.
Но вот эта последняя версия за полчаса не вылетала ни разу - надеюсь, что проблема сама собой разрешилась. Посмотрим.

**Comment by orignal** [comment]
возможно кстати потому что MSYS более свежий

**Comment by randomboygh** [comment]
Прошел час без вылетов - все стабильно. Огромное спасибо за помощь в частности и за всю разработку в целом.
```
Uptime: 1 hours, 3 seconds
Status: OK
Tunnel creation success rate: 30%
Received: 200.35 MiB (68.71 KiB/s)
Sent: 214.97 MiB (78.99 KiB/s)

Routers: 5072 Floodfills: 1418 LeaseSets: 60
Client Tunnels: 52 Transit Tunnels: 376
```

**Comment by randomboygh** [comment]
```
Uptime: 2 days, 2 hours, 8 min, 30 seconds
Status: OK
Tunnel creation success rate: 50%
Received: 25.40 GiB (174.50 KiB/s)
Sent: 29.64 GiB (187.24 KiB/s)

Routers: 4161 Floodfills: 1414 LeaseSets: 72
Client Tunnels: 55 Transit Tunnels: 1190
```
