### ISSUE TITLE
Can't bind I2P to XMPP

### ISSUE THREAD

**Issue by johnmiller92** [PurpleI2P/i2pd#587]
The I2P service won't bind to the socket for XMPP on localhost:5222.

Tunnels:

[xmpp-in]
type = server
host = localhost
port = 5222
keys = xmpp-in.dat

netstat:

tcp        0      0 localhost:xmpp-client   0.0.0.0:*               LISTEN

**Comment by orignal** [comment]
Sure it doesn't. It should connect to localhost:5222, rather than listen.

**Comment by johnmiller92** [comment]
The entry I posted for netstat is the XMPP server listening for inbound connections. I2P never creates the established connection that hooks to XMPP.

**Comment by orignal** [comment]
have you tried to his I2P from xmpp-in.dat?
Once you do it will connect

**Comment by johnmiller92** [comment]
Not sure what you meant. I have I2Pd and the XMPP server on the same machine trying to tunnel it over the I2P network. The link between I2P and XMPP server seems to never be established.

**Comment by orignal** [comment]
XMPP and server tunnel are not enough to establish this link.
Somebody must connect to you XMPP server through the I2P.
Once server tunnel get SYN message from an incoming I2P stream it will connect to you XMPP server as specified in config. 
Simply speaking you must create a client tunnel to the I2P address of your I2P server, then forward your XMPP client to that port and try to connect

**Comment by johnmiller92** [comment]
I also earlier received

15:51:58@900/error - SSU: v6 server runtime exception: send_to: Network is unreachable
15:53:13@900/error - SSU: v6 server runtime exception: send_to: Network is unreachable
15:53:28@900/error - SSU: v6 server runtime exception: send_to: Network is unreachable
15:54:32@900/error - SSU: v6 server runtime exception: send_to: Network is unreachable
15:55:12@900/error - SSU: v6 server runtime exception: send_to: Network is unreachable
15:57:14@900/error - SSU: v6 server runtime exception: send_to: Network is unreachable
15:57:49@900/error - SSU: v6 server runtime exception: send_to: Network is unreachable

**Comment by orignal** [comment]
Don't enable ipv6 if you don't have it. And it seems you don't

**Comment by johnmiller92** [comment]
I've disabled IPv6 yet no one an connect to my server. I've installed i2pd from the gentoo's portage package manager. My friend which installed it a server on an ARM system is running Ubuntu and latest copy of I2Pd from git and I'm able to connect to his setup.

**Comment by orignal** [comment]
Please provide .b32 address of your XMPP server and I will try.
I don't know what's inside gentoo package manager, what they provide as tunnel configuration, etc.

**Comment by khumarahn** [comment]
Hi, I am a maintainer of i2pd in gentoo. We try to stay close to upstream. The latest version in portage is 2.8.0, and as of now we don't tweak the configuration in any way. By default we use the following configuration files:
```
docs/i2pd.conf
debian/tunnels.conf
debian/subscriptions.txt
```

**Comment by johnmiller92** [comment]
ejrrau6jgp5upn2zoofcwyvez3wijrhfsitoiywufua26my2maga.b32.i2p:5222

**Comment by orignal** [comment]
It looks like your address is not published, at least I can't find it's LeaseSet

**Comment by johnmiller92** [comment]
<b>Routers:</b> 21 <b>Floodfills:</b> 17 <b>LeaseSets:</b> 0<br>

Could that be the issue?

**Comment by orignal** [comment]
Try to re-create xmpp-in.dat, for some reason it doesn't publish properly. That needs to be investigated. Look like to wrong floodfill. If you create new keys file it might generate better address

**Comment by johnmiller92** [comment]
I've recreated the file and restarted the service and it says on status testing for about 3 minutes which my client goes to OK almost immediately. Here's the current status now

<div class=right><b>Uptime:</b> 3 min, 1 seconds<br>
<b>Status:</b> Firewalled<br>
<b>Tunnel creation success rate:</b> 0%<br>

Client and server are both virtual machines in a datacenter environment on sequentially assigned addresses. No firewall is placed in front of them, client is i2pd on Windows though.

**Comment by atnaguzin** [comment]
Check system time. Maybe you have incorrect time.
Configure to use NTP servers.

**Comment by orignal** [comment]
Check "Transports" at the web console. If you have nothing here it means something wrong either with your network or system time

**Comment by johnmiller92** [comment]
Syncing the clock via NTP did the trick thanks!
