### ISSUE TITLE
cmake can not compile i2pd on debian

### ISSUE THREAD

**Issue by senovr** [PurpleI2P/i2pd#589]
Иду по туториалу с хабра по сборке i2pd под дебиан.
после команды cmake вываливается следующая ошибка:
cmake -DCMAKE_BUILD_TYPE=Release
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Performing Test CXX11_SUPPORTED
-- Performing Test CXX11_SUPPORTED - Success
-- Performing Test CXX0X_SUPPORTED
-- Performing Test CXX0X_SUPPORTED - Success
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   program_options
--   date_time
CMake Error at /usr/share/cmake-3.0/Modules/FindOpenSSL.cmake:293 (list):
  list GET given empty list
Call Stack (most recent call first):
  CMakeLists.txt:259 (find_package)

CMake Error at /usr/share/cmake-3.0/Modules/FindOpenSSL.cmake:294 (list):
  list GET given empty list
Call Stack (most recent call first):
  CMakeLists.txt:259 (find_package)

CMake Error at /usr/share/cmake-3.0/Modules/FindOpenSSL.cmake:296 (list):
  list GET given empty list
Call Stack (most recent call first):
  CMakeLists.txt:259 (find_package)

CMake Error at /usr/share/cmake-3.0/Modules/FindOpenSSL.cmake:298 (list):
  list GET given empty list
Call Stack (most recent call first):
  CMakeLists.txt:259 (find_package)

-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version ".0.0`")
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8")
-- ---------------------------------------
-- Build type         : Release
-- Compiler vendor    : GNU
-- Compiler version   : 4.9.2
-- Compiler path      : /usr/bin/c++
-- Install prefix:    : /usr/local
-- Options:
--   AESNI            : OFF
--   HARDENING        : OFF
--   LIBRARY          : ON
--   BINARY           : ON
--   STATIC BUILD     : OFF
--   UPnP             : OFF
--   PCH              : OFF
--   MESHNET          : OFF
-- ---------------------------------------
-- Configuring incomplete, errors occurred!
See also "/home/debian/i2pd/build/CMakeFiles/CMakeOutput.log".
See also "/home/debian/i2pd/build/CMakeFiles/CMakeError.log".

Если необходимо, могу выложить логи.

**Comment by orignal** [comment]
собрать с помощью make
скорее всего ругнется на отсуствие openssl
поставить
