### ISSUE TITLE
[minor bug] Error on config reload by SIGHUP

### ISSUE THREAD

**Issue by l-n-s** [PurpleI2P/i2pd#592]
In *tunnels.conf* I have client tunnel to IRC server.

I've changed destination from **walker.i2p** to **mv4vrczqpiq27qzzfdepefxhfkl7p45ep5nm4wvbh4i6cb5xhr4a.b32.i2p**

Sending SIGHUP to reload configuration and error shows up in log:

    @989/info - Daemon: Got SIGHUP, reopening log...
    @989/info - Clients: Local address xxx.b32.i2p loaded
    @989/error - Clients: Can't read tunnel walker-irc params: bind: Address already in use

The problem seems to be that destination changes, but port number remains and is still in use.
Using latest i2pd from git.

**Comment by orignal** [comment]
It doesn't work properly yet
