### ISSUE TITLE
Does not shutdown correctly on Linux

### ISSUE THREAD

**Issue by l-n-s** [PurpleI2P/i2pd#593]
After i2pd works for a while, I'm trying to shutdown it with Ctrl-C

It shows warning about Graceful shutdown, but after 600 seconds it still runs. i2pd stops responding to Ctrl-C, continues to work and can be stopped only by SIGKILL

If I run i2pd and imidiately press Ctrl-C it shuts down as expected.
Using latest version from git.

**Comment by l-n-s** [comment]
Doesn't shutdown gracefully from WebConsole either.

**Comment by orignal** [comment]
I've tried. Got it down exactly after 10 minutes
