### ISSUE TITLE
i2pd игнорирует директиву port

### ISSUE THREAD

**Issue by drequivalent** [PurpleI2P/i2pd#601]
В конфиге:
```
## Port to listen for connections
## By default i2pd picks random port. You MUST pick a random number too,
## don't just uncomment this
port = 6678
```
В netstat:
```
tcp        0      0 127.0.0.1:6668          0.0.0.0:*               LISTEN      12037/i2pd      
tcp        0      0 0.0.0.0:4567            0.0.0.0:*               LISTEN      12037/i2pd      
tcp        0      0 127.0.0.1:4444          0.0.0.0:*               LISTEN      12037/i2pd      
tcp        0      0 0.0.0.0:7070            0.0.0.0:*               LISTEN      12037/i2pd      
tcp        0      0 127.0.0.1:4447          0.0.0.0:*               LISTEN      12037/i2pd      
tcp6       0      0 :::4567                 :::*                    LISTEN      12037/i2pd      
udp        0      0 0.0.0.0:4567            0.0.0.0:*                           12037/i2pd      
udp6       0      0 :::4567                 :::*                                12037/i2pd  
```
В консоли:
```
Our external address:
SSU     <IP-адрес>:4567
NTCP  <IP-адрес>:4567
```

Как заставить его таки поменять внешний порт?

**Comment by orignal** [comment]
Таки удалить router.info в ~/.i2pd и стартовать снова.
Если не поможет то буду разбираться.

**Comment by drequivalent** [comment]
`/var/lib/i2pd# rm router.info ; service i2pd restart` не помогло

**Comment by orignal** [comment]
Порт при первом запуске выбирается, а потом читается из файла.
Посмотрю что не так

**Comment by drequivalent** [comment]
И да, в таком случае он обещает выбрать рандомный, а на деле почему-то все время 4567, уже на двух инстансах.

**Comment by orignal** [comment]
Вот такое есть в логе?
Daemon: accepting incoming connections at port

Должно работать.
Почему все время 4567 надо тоже посмотреть.

**Comment by l-n-s** [comment]
$ grep -r '4567' *
    debian/i2pd.upstart:env I2PD_PORT="4567"
    debian/i2pd.default:I2PD_PORT="4567"
    docs/i2pd.conf:# port = 4567

**Comment by atnaguzin** [comment]
Но тебя косается только файл /etc/default/i2pd, если ты в debian подобных системах

**Comment by drequivalent** [comment]
Вопрос не по теме: кроме как через веб-консоль, возможно посмотреть статус роутера и Rx/Tx?

**Comment by orignal** [comment]
Через I2PControl разумеется. Но там свой протокол.

**Comment by drequivalent** [comment]
Что касается порта, дело оказалось действительно в /etc/default/i2pd.
```
I2PD_PORT="4567"
```
Я что-то может быть не понимаю, но зачем это было городить, друзья?

**Comment by orignal** [comment]
I2PControl и в официальном I2P есть. Через него приложение itoopie работает и показывает статиттику

**Comment by drequivalent** [comment]
Да не, это-то ясно. Я про /etc/default. Дублирование одной настройки в двух местах.

**Comment by drequivalent** [comment]
Закрываю, крч, всем спасибо, все свободны.

**Comment by l-n-s** [comment]
Дождемся комментария @hagen-i2p и тогда можно закрыть. Там не все так очевидно.

**Comment by hagen-i2p** [comment]
Эта опция была сделана, чтобы специально выделить настройку порта.

Примерно до 2.3.0 - был совершенно необязателен конфиг, опций было мало, и с ними творился форманный бардак.
Настройка порта - по сути единственное что требовалось от юзера, чтобы получить минимально работающий i2p-роутер
(с учётом прокидываний на всяких вышестоящих д-линках).

Рассчёт был на то, что юзер всё равно полезет в /etc/default/i2pd, менять I2PD_ENABLED в этом же файле.
(за основу бралось оформление rsync, там сделано так же)

Ну а MXPLRS недолго думая грохнул её совсем, по репорту юзера, который тот файлик не увидел.

Предлагаю закомментировать, но оставить в качестве примера, чтоб по дефолту выставлялось рандомно или в соответствии с конфигом, если задано там.
Потому что уже есть юзеры, которые задали порт ЗДЕСЬ, а в следующем релизе оно внезапно перестанет работать.

Файлик этот считается конфигом и не переустанавливается, если он менялся юзером.

**Comment by janicez** [comment]
i thought i2pd was primarily used by english speakers and thus must have bug reports in English. Feel free to shoot me if I'm mistaken.

**Comment by orignal** [comment]
@janicez mostly by Russians and some of users just don't know English, so they report issues in Russian, thus we respond in Russian as well.
