### ISSUE TITLE
High CPU

### ISSUE THREAD

**Issue by johnmiller92** [PurpleI2P/i2pd#617]
Running version 2.9.0 without AESNI and the process continuously locks 1 core at 100%, is this normal behavior?

**Comment by majestrate** [comment]
how much bandwidth is being used?

**Comment by johnmiller92** [comment]
Received: 696.59 KiB (1.24 KiB/s)
Sent: 815.90 KiB (1.42 KiB/s)

**Comment by majestrate** [comment]
os / arch ?

**Comment by johnmiller92** [comment]
win32 x64

**Comment by majestrate** [comment]
upnp enabled or disabled?

**Comment by johnmiller92** [comment]
I believe it's enabled by default on the precompiled binary. This machine is in a datacenter without a firewall so there's nothing to forward.

**Comment by orignal** [comment]
Does it start using 100% immediately or after running for a while?

**Comment by johnmiller92** [comment]
Immediately

**Comment by atnaguzin** [comment]
Place i2pd.conf in %APPDATA%/i2pd/ & try to enable:
[precomputation]
elgamal = true

**Comment by johnmiller92** [comment]
Same, when I start it the CPU usage creeps from around 2% to 100% in about 5 seconds.

**Comment by orignal** [comment]
what happens after 5-10 minutes?

**Comment by majestrate** [comment]
any error log messages ?

**Comment by orignal** [comment]
@majestrate  seems he uses VPS, it migh be the same issue as with Raspberry PI.
Just lack of CPU since it's a virtual host.
However if it's a case it should get back to normal after few minutes once most of the tunnels got built.

**Comment by johnmiller92** [comment]
It has 2 cores assigned from an intel e5-2630, even after 6 hours cpu is still high.

**Comment by majestrate** [comment]
sounds like a thread is stuck somewhere, not crypto overhead.

**Comment by johnmiller92** [comment]
Would a dump help?

**Comment by orignal** [comment]
Yes, it would

**Comment by johnmiller92** [comment]
https://www.dropbox.com/s/hdegsnp76jyhdor/i2pd.DMP?dl=0

**Comment by Arthur111** [comment]
Same thing with osx (latest), very high cpu used immediately, with precompiled binary or built from source code.

**Comment by orignal** [comment]
How about linux?

**Comment by majestrate** [comment]
i am seeing this on linux too now

**Comment by orignal** [comment]
@majestrate please provide call stack from gcore

**Comment by Arthur111** [comment]
> It's normal it uses higher CPU at start-up, should be lower later.

Yes but this issue is : it stay 99 - 100 % all the time it's running with few kbps bandwidth.

**Comment by orignal** [comment]
I can't reproduce the problem. That's the issue.
Basically I need to see what it is busy in

**Comment by Arthur111** [comment]
I just comment "daemon = true" and now its ok.
Seems daemon mode use lot of cpu.

**Comment by orignal** [comment]
Maybe daemonization for OS X should be implemented differently

**Comment by Arthur111** [comment]
Yes, i don't know how they did it but in squid (http://www.squid-cache.org/Versions/) there is a daemon mode (-N) and its ok.

**Comment by majestrate** [comment]
dumped core
found where it's hanging
https://github.com/PurpleI2P/i2pd/blob/26440d94f1ea4c75cf9a450eeb9c7c2a70f8ec4e/Streaming.cpp#L661

	void Stream::ScheduleResend ()
	{
		m_ResendTimer.cancel ();
		m_ResendTimer.expires_from_now (boost::posix_time::milliseconds(m_RTO)); // <-- here
		m_ResendTimer.async_wait (std::bind (&Stream::HandleResendTimer,
			shared_from_this (), std::placeholders::_1));
	}



if `m_RTO` is 0 it will spam
