### ISSUE TITLE
Can't connect anymore

### ISSUE THREAD

**Issue by dauphin327** [PurpleI2P/i2pd#619]
Hello,

I was able to connect successfully with i2pd about 2 weeks ago, but now its stuck on firewalled and 0% status. I tried my old config and i2pd build (with upnp enabled) and latest i2pd from github but still the same result. Time is also synced via ntp service.

Log: http://pastebin.com/raw/RKKyu5nz

Uptime: 2 min, 52 seconds
Status: Firewalled
Tunnel creation success rate: 0%
Received: 0.72 KiB (0.00 KiB/s)
Sent: 16.36 KiB (0.05 KiB/s)
Data path: /home/ubuntu/.i2pd

Routers: 46 Floodfills: 24 LeaseSets: 0
Client Tunnels: 2 Transit Tunnels: 0

**Comment by orignal** [comment]
Looks like your network connections are all stuck.
Try to delete ~/.i2pd/netdb and reseed again first.
Then try to hit those IPs/ports using telnet.

**Comment by dauphin327** [comment]
Yup, thanks. Deleting netdb folder another time did it!

**Comment by atnaguzin** [comment]
Party Van is known you ...dot.dotdot...
> Log: http://pastebin.com/raw/RKKyu5nz

![image](https://cloud.githubusercontent.com/assets/7023612/17939131/beeea632-6a31-11e6-9a14-fe3f01cdd7fa.png)

**Comment by orignal** [comment]
@atnaguzin, MGIMO? :)

**Comment by dauphin327** [comment]
![obamashhh1-e1351527807932](https://cloud.githubusercontent.com/assets/2873429/17972860/43854942-6aae-11e6-919b-709f26b3f596.jpg)

On a serious note, thanks for developing i2pd. Me and my friends love it ))
