### ISSUE TITLE
Where is the i2pd config file for Android?

### ISSUE THREAD

**Issue by mathiasfriman** [PurpleI2P/i2pd#621]
I've installed i2pd for Android and cannot seem to find the config file. Since I couldn't find an issue on this I thought i'd file an issue so more people looking for it may find it.. 

Is there an i2pd.conf somewhere or do I have to create one myself?

**Comment by orignal** [comment]
you should create one in /sdcard/i2pd

**Comment by mathiasfriman** [comment]
Great, thanks!
