### ISSUE TITLE
Reseed: Certificate for xxx@mail.i2p not loaded

### ISSUE THREAD

**Issue by l-n-s** [PurpleI2P/i2pd#622]
Ресид клиент не может найти нужный сертификат, чтобы проверить подпись su3 файла, так что он скипает проверку полностью, даже если правильные серты лежат в нужных папках.

**Comment by l-n-s** [comment]
Когда подписываю su3 сертификатом, который не лежит в папке  (Reseed: Certificate for user@mail.i2p not loaded) - все равно добавляет routerinfo в netDb

**Comment by atnaguzin** [comment]
@l-n-s, orignal вроде говорил что если нету сертификата, то проверка просто пропускается.

**Comment by orignal** [comment]
Там на самом деле другая проблема: даже если он есть но подпись неверна все равно добавляется. Осталось с тех пор когда проверка подписи не работала.

**Comment by l-n-s** [comment]
Предлагаю сделать опцию:

    reseed.check=1

Если 1 - то проверяет, загружен ли такой сертификат, верна ли подпись, т.е. все по-строгому. Дает ошибку в случае любой проблемы и ничего не добавляет.

Если 0, то проверка reseed файла пропускается.

**Comment by orignal** [comment]
reseed.verify  true или false
