### ISSUE TITLE
IPv6 Peer Testing gives: Network is unreachable

### ISSUE THREAD

**Issue by obscuratus-i2p** [PurpleI2P/i2pd#624]
I've set up a sandboxed I2P network running about 10 Java I2P peers and about 20 I2PD peers.

I have a few of the I2PD peers testing the latest I2PD code from the openssl branch, and I've enabled IPv6 on them to see how the I2PD IPv6 Peer Testing works with the IPv6 Java-I2P peers.

Whenever I2PD is choosen to perform as a Charlie for an IPv6 test, I'm getting errors in my log such as the following:

14:09:15@696/debug - SSU: peer test received
14:09:15@696/debug - SSU: peer test from Bob. We are Charlie
14:09:15@696/error - SSU: HandleReceivedPackets send_to: Network is unreachable

Alice will never receive anything from the I2PD-Charlie, and conclude that she is IPv6-firewalled until that peer runs the IPv6 peer test again later.

I can see several examples of successful IPv4 peer testing for the I2PD clients, but I have not found any examples of successfully performing as a Charlie.

**Comment by orignal** [comment]
Can you print out 'addr' right before this line?
https://github.com/PurpleI2P/i2pd/blob/openssl/SSUSession.cpp#L997
like LogPrint(eLogDebug, "Alice's address ", addr);
I want to know what Alice's address we get.

**Comment by orignal** [comment]
Please get the lastest code and try again
