### ISSUE TITLE
Lots of errors and irresponsive web console

### ISSUE THREAD

**Issue by p4bl0-** [PurpleI2P/i2pd#625]
Hello,

I'm switching from the I2P Java implementation to i2pd on the server that serves the EepSite version of my personal website.
I was really expecting that i2pd would be less resource-greedy, but it's not the case: after a time (between 30 minutes and 2 hours) i2pd uses a lot of CPU and is making the I/O very slow, and when that happens, the web console does not respond anymore.

Here is what happens:

When I start i2pd, I get these kind of errors (quite a lot, like 1 every 10 seconds) from the beginning:
- NTCP: runtime exception: remote_endpoint: Transport endpoint is not connected
- Transports: No NTCP or SSU addresses available
- Garlic: Failed to decrypt message
- ElGamal decrypt hash doesn't match
- NetDb: database store with own RouterInfo received, dropped

These errors never stop, but after a few hours I also have a _lot_ (sometimes multiples per second) of these:
- Profiling: /var/lib/i2pd/peerProfiles/pM/profile-M _…xxx…_ .txt: cannot open file

and my load average goes from approximately 0 to something > 1 and sometimes event close to 4.

It is not a permission problem so maybe there is a kind of leak that makes i2pd run out of file descriptors? (Wild random guess.)

The strange thing is that meanwhile, my EepSite works perfectly well.

Oh, and this is with i2pd 2.9.0 installed from the .deb on Debian Wheezy.

I don't mind my EepSite being offline a little so I can perform any necessary tests and report the results :).

**Comment by p4bl0-** [comment]
Actually I think my issue is a lot like #575.

I'm trying to increase i2pd user's nofile's ulimit and will report change.

**Comment by atnaguzin** [comment]
@p4bl0- try to build package by yourself. Since release fixed some errors.

**Comment by orignal** [comment]
@p4bl0- these errors is not a problem. That's how I2P operates

**Comment by p4bl0-** [comment]
Hello again,

So, it seems better with the new settings but it still crashed at some point with

    *** glibc detected *** i2pd: free(): corrupted unsorted chunks: 0x00007f554c28beb0 ***

The errors that "are not a problem" are still a problem if one wants to log to a file as the file grows ways too big very quickly (sometimes multiples MB per hour, even with loglevel set to error).

If I find the time to build i2pd myself I will try that. But maybe if some of these bugs have been fixed it would be nice to release a 2.9.1 or something like that? :)

**Comment by khumarahn** [comment]
Can't say anything about the crash, but using `loglevel = error` in `i2pd.conf` helps me to keep the log file within a few megabytes (it is rotated weekly):
```
# ls -alh /var/log/i2pd*
-rw-r----- 1 i2pd i2pd 2.6M Sep  4 11:35 /var/log/i2pd.log
-rw-r----- 1 i2pd i2pd 1.5M Aug 15 03:10 /var/log/i2pd.log-20160815.gz
-rw-r----- 1 i2pd i2pd 1.4M Aug 21 03:10 /var/log/i2pd.log-20160821.gz
-rw-r----- 1 i2pd i2pd 5.8M Aug 29 03:09 /var/log/i2pd.log-20160829.gz
-rw-r----- 1 i2pd i2pd 1.8M Sep  4 03:10 /var/log/i2pd.log-20160904.gz
```

@orignal why not change `loglevel = error` in the default `i2pd.conf`? Users are typically not interested to see lots of errors which are "not a problem".

**Comment by orignal** [comment]
@p4bl0-  do you have a stack trace?

**Comment by orignal** [comment]
@khumarahn  I agree that some messages marked as "error" are no actually errors. Need to revise it again, although I've changed a lot before

**Comment by p4bl0-** [comment]
@orignal sorry nope, I lost the stack trace :(.

I agree to changing the status of message that are normal to "info" or maybe "warn" rather than "error".

@khumarahn I already set the loglevel to error and still got too much logs (at least 1 line per second), so I currently output the error log to stdout in a screen…

**Comment by khumarahn** [comment]
I also have around one line per second. It is not a problem, only takes a few megabytes to store.

**Comment by majestrate** [comment]
I suspect that a contributing factor to the webui is ssu session timers eating up file descritors

working on fixing that today.

**Comment by majestrate** [comment]
found that web console freezes after a while even when open file count is very low, probably not related to open files being eaten up.

**Comment by uaply** [comment]
What about httpproxy? Is it freeze also?

**Comment by majestrate** [comment]
@uaply i haven't checked if it does but if it does too then #626 should help with it.

**Comment by l-n-s** [comment]
Seems to be fixed.
