### ISSUE TITLE
Через какое-то время перестаёт открываться веб-консоль и i2p ресурсы

### ISSUE THREAD

**Issue by vladns** [PurpleI2P/i2pd#630]
Примерно через 3-4 дня непрерывной работы, перестаёт открывать веб-консоль, а так же сайты сети. При этом порт 7070 (и ip) продолжают прослушиваться и лог пишется как обычно, т.е. ничего там не замечаю подозрительного. Всё началось с 2.90 версии, до неё все (по крайней мере с 2.5) работали нормально. Система Debian 8.5 64 бит.

**Comment by orignal** [comment]
Уже починили. Будет в следующем релизе.
