### ISSUE TITLE
Падает при запуске последняя версия из ветки openssl на windows 8.1 x64

### ISSUE THREAD

**Issue by AlexBeLi** [PurpleI2P/i2pd#634]
Началось вроде после вливания ветки majestrate/merge_udp_tunnel.
(gdb) run
Starting program: C:\dev\i2pd\i2pd\i2pd.exe
[New Thread 3888.0x1728]
[New Thread 3888.0x151c]

Thread 1 received signal SIGSEGV, Segmentation fault.
boost::date_time::int_adapter<long long>::is_special (this=0x2f262d19eb46803)
    at C:/msys64/mingw64/include/boost/date_time/int_adapter.hpp:131
131         return(is_infinity() || is_nan());

(gdb) bt
#0  boost::date_time::int_adapter<long long>::is_special (
    this=0x2f262d19eb46803)
    at C:/msys64/mingw64/include/boost/date_time/int_adapter.hpp:131
#1  0x00000000006a3a68 in boost::date_time::time_duration<boost::posix_time::time_duration, boost::date_time::time_resolution_traits<boost::date_time::time_resolution_traits_adapted64_impl, (boost::date_time::time_resolutions)5, 1000000ll, (unsigned short)6, int> >::is_special (this=<optimized out>)
    at C:/msys64/mingw64/include/boost/date_time/time_duration.hpp:210
#2  boost::date_time::counted_time_system<boost::date_time::counted_time_rep<boost::posix_time::millisec_posix_time_system_config> >::add_time_duration (
    base=..., td=...)
    at C:/msys64/mingw64/include/boost/date_time/time_system_counted.hpp:226
#3  0x0000000000460c83 in boost::date_time::base_time<boost::posix_time::ptime, boost::date_time::counted_time_system<boost::date_time::counted_time_rep<boost::posix_time::millisec_posix_time_system_config> > >::operator+ (td=...,
    this=0x23fcd8) at C:/msys64/mingw64/include/boost/date_time/time.hpp:163
#4  boost::asio::time_traits<boost::posix_time::ptime>::add (d=..., t=...)
    at C:/msys64/mingw64/include/boost/asio/time_traits.hpp:57
#5  boost::asio::detail::deadline_timer_service<boost::asio::time_traits<boost::posix_time::ptime> >::expires_from_now (ec=..., expiry_time=..., impl=...,
    this=0x3f4818)
    at C:/msys64/mingw64/include/boost/asio/detail/deadline_timer_service.hpp:160
#6  boost::asio::deadline_timer_service<boost::posix_time::ptime, boost::asio::time_traits<boost::posix_time::ptime> >::expires_from_now (ec=...,
    expiry_time=..., impl=..., this=<optimized out>)
    at C:/msys64/mingw64/include/boost/asio/deadline_timer_service.hpp:129
#7  boost::asio::basic_deadline_timer<boost::posix_time::ptime, boost::asio::time_traits<boost::posix_time::ptime>, boost::asio::deadline_timer_service<boost::posix_time::ptime, boost::asio::time_traits<boost::posix_time::ptime> > >::basic_deadline_timer (expiry_time=..., io_service=...,
    this=0x8be678 <i2p::client::context+568>)
    at C:/msys64/mingw64/include/boost/asio/basic_deadline_timer.hpp:187
#8  boost::asio::basic_deadline_timer<boost::posix_time::ptime, boost::asio::time_traits<boost::posix_time::ptime>, boost::asio::deadline_timer_service<boost::posix_time::ptime, boost::asio::time_traits<boost::posix_time::ptime> > >::basic_deadline_timer (expiry_time=..., io_service=...,
    this=0x8be678 <i2p::client::context+568>)
    at C:/msys64/mingw64/include/boost/asio/basic_deadline_timer.hpp:189
#9  i2p::client::ClientContext::ClientContext (
    this=0x8be440 <i2p::client::context>) at ClientContext.cpp:21
#10 0x000000000077413b in __static_initialization_and_destruction_0 (
    __initialize_p=1, __priority=65535) at ClientContext.cpp:16
#11 _GLOBAL__sub_I__ZN3i2p6client7contextE () at ClientContext.cpp:576
#12 0x000000000063c145 in __do_global_ctors ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/gccmain.c:44
#13 0x000000000063c19c in __main ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/gccmain.c:60
#14 0x00000000004013c0 in __tmainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:324
#15 0x00000000004014fb in WinMainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:184

**Comment by orignal** [comment]
Ну понятно.  Счас починим.
