### ISSUE TITLE
BOB Interface is not working 

### ISSUE THREAD

**Issue by mppdidi** [PurpleI2P/i2pd#651]
Hey i2pd,
thanx for the effort you put into i2pd. 
BOB Interface is not working on the current git commit e4d60929392de06f9430ca5e442746f9aab133c6
the commands need a space at the end - after a few commands the i2pd dies suddenly.

**Comment by majestrate** [comment]
os/arch/boost version?

**Comment by mppdidi** [comment]
os = ubuntu 16.04
arc x86_64
boost = 1.58.0.1ubuntu1

**Comment by orignal** [comment]
What's wrong with BOB?

**Comment by mppdidi** [comment]
it crashes the router with a segfault after a few minutes

**Comment by orignal** [comment]
with what? transmission?

**Comment by orignal** [comment]
Please provide the list of commands

**Comment by mppdidi** [comment]
setnick nick
newkeys
status nick

after the last command i2pd crashes with segfault

i2pd[20023]: segfault at 0 ip 000000000042a9d6 sp 00007f03f4a41510 error 4 in i2pd[400000+47c000]

**Comment by orignal** [comment]
yes, I'm able to reproduce

**Comment by mppdidi** [comment]
okay this one is fixed. 
but if do a getkeys when there are none present, it segfaults again.

**Comment by mppdidi** [comment]
it appears that if keys or dests do not exist for some commands, it segfaults instead of throwing out ERROR.
for example if you do start nick when nick is not set, it segfaults. same goes for getkeys.
i'll run all available bob commands in a script and see if ERROR is outputed or segfaulted.
thank you very much for fixing stuff !
