### ISSUE TITLE
more than one http proxy

### ISSUE THREAD

**Issue by mppdidi** [PurpleI2P/i2pd#655]
ist it possible to have more than one http proxy instance ?

**Comment by majestrate** [comment]
at the moment there is only 1 http proxy instance.
this is a good feature idea.

**Comment by mppdidi** [comment]
would it be possible to put this into the i2pd.conf - so we can have mulitple ?

**Comment by majestrate** [comment]
if it goes anywhere i think that it would go into tunnels.conf

**Comment by l-n-s** [comment]
Done.
