### ISSUE TITLE
close tunnel when idle

### ISSUE THREAD

**Issue by mppdidi** [PurpleI2P/i2pd#657]
in order to save ressources closing tunnels when idle would be very nice ?

**Comment by l-n-s** [comment]
What tunnels are you talking about? HTTP/Socks proxy and IRC?

**Comment by orignal** [comment]
it doesn't consume any

**Comment by mppdidi** [comment]
is was thinking especially about the http proxy

**Comment by orignal** [comment]
what kind of tunnels you are talking about?
