### ISSUE TITLE
bandwidth class

### ISSUE THREAD

**Issue by mppdidi** [PurpleI2P/i2pd#658]
allthoug my i2pd runs 24/7 on a high bandwidth server, the amount of traffic processed is very low.

Uptime: 23 hours, 11 min, 38 seconds
Network status: OK
Tunnel creation success rate: 62%
Received: 85.79 MiB (8.10 KiB/s)
Sent: 78.25 MiB (7.70 KiB/s)
...
...
Router Caps: OfR

i am on the latest build of openssl branch.
ssu and ntcp is activated 

any hints ?

**Comment by atnaguzin** [comment]
Transit and FloodFill enabled?

**Comment by mppdidi** [comment]
yes ...

![purple_i2p_2 9 0_webconsole](https://cloud.githubusercontent.com/assets/15330503/19197921/bc39c4c8-8cbc-11e6-8a0a-1e909ccd6b71.png)

**Comment by majestrate** [comment]
looks like you do have some participating traffic, just not a lot. about
how much uptime do you have? more than 1 day? more than 1 week?

**Comment by mppdidi** [comment]
about 3 days. i guess i'll let it run for a week and report back if it is not improving.
thanks a lot.

**Comment by mppdidi** [comment]
reproting back on this issue. with the latest openssl branch and a couple of things fixed, the node is running perfectly. tunnel creating succes rate is at ~60%. i also observed that the number of routers and floodfills remains constantly high. in previous commits the dropped significantly every 15 minutes or so.
the cpu and memory load is way smaller then the original java implementation ( about 50% )
i'll look forward to more exciting improvements.
hughe thanks to all coders !!!

![2016_10_12_12_39_56_purple_i2p_2 9 0_webconsole](https://cloud.githubusercontent.com/assets/15330503/19307239/b914c37c-9079-11e6-8e4b-9297bbc4317b.png)
