### ISSUE TITLE
Bootstrap a new node

### ISSUE THREAD

**Issue by mppdidi** [PurpleI2P/i2pd#665]
Doing a fresh install of the git/openssl branch ( Ubuntu 14.04 LTS latest updates - ordinary home router = NATed ), the new node could not bootstrap because it could not reach any other nodes. 
After a few minutes the known routers went to 2.
I then copied a netDb directory from another healthy node and restarted the i2pd.
That solved the problem but the point is that a fresh installation could not bootstrap into the i2p network on it's own.
Also upnp does not register at the internet router allthough it is UPNP enabled ( works with all other programs ).

**Comment by orignal** [comment]
You had to delete netdb in this case and it would force to reseed and get list of currently active nodes

**Comment by orignal** [comment]
check your clock first

**Comment by mppdidi** [comment]
checked - ntpd stratum 2

**Comment by mppdidi** [comment]
this is what it looks like after roughly an hour

![2016_10_11_16_16_15_purple_i2p_2 9 0_webconsole](https://cloud.githubusercontent.com/assets/15330503/19273825/4599a922-8fce-11e6-9202-83f67593928b.png)

**Comment by orignal** [comment]
Because it is not able to connect to anybody

**Comment by mppdidi** [comment]
i now, but as i point out above, giving it some working netDb entries solves the issue.
so either the built in mechanism to boostrap does not work or the seedlist from the builtin server has no healthy nodes to help the node to integrate.

**Comment by l-n-s** [comment]
@mppdidi logs?

Try using i2pd with option
 
    --reseed.urls=https://reseed.i2p-projekt.de/,https://i2p.mooo.com/netDb/,https://netdb.i2p2.no/

or config item

    [reseed]
    urls = https://reseed.i2p-projekt.de/,https://i2p.mooo.com/netDb/,https://netdb.i2p2.no/

watch logs with debug level. Wireshark can be useful to investigate why it can't connect to reseeds.

**Comment by mppdidi** [comment]
these reseed urls don't work anymore - and the haven't for some time now.

**Comment by mppdidi** [comment]
at least the do not work with i2pd because they only provide signed .su3 urls

**Comment by l-n-s** [comment]
Can you provide debug level logs?

**Comment by mppdidi** [comment]
coming up shortly. but i already figured out what is happening.
i encountered the same problem on another node that had no firewalled port for i2pd.
when i ran i2pd from scratch it was stuck with ssu and ntcp running on address 127.0.0.1
once i manually changed the ip address with host=a.b.c.d everything was running fine.

**Comment by mppdidi** [comment]
okay made some progress. when the router got stuck on ssu and ntcp with 127.0.0.1 i killed and restarted it. after that it recognized the internet ip correctly and bootstrapped into the network.
maybe this is related to the upnp changes ?

**Comment by orignal** [comment]
@mppdidi  please take last commit. It should fix the issue

**Comment by mppdidi** [comment]
@orignal  yep - it's fixed now.
;-)
