### ISSUE TITLE
ntcp disabled not working

### ISSUE THREAD

**Issue by mppdidi** [PurpleI2P/i2pd#667]
allthough i've set ntcp to false, the router page says ntcp is reachable.

**Comment by l-n-s** [comment]
Config options seem to work, but console option --ntcp false not.

Also, when setting both transports to false in config, I can't stop i2pd with ctrl+C (it hangs), only sending SIGKILL stops i2pd. Not critical thou.

**Comment by mppdidi** [comment]
the i2pd still tries to connect outgoing connections to ntcp destinations as i can tell from the log. does it advertise itself as ntcp ?

**Comment by orignal** [comment]
NTCP address in RouterInfo and outgoing sessions are different things

**Comment by mppdidi** [comment]
I disagree, it still advertises to other routers that it is ntcp enabled.
![2016_10_13_22_37_03_i2p_router_console_network_database](https://cloud.githubusercontent.com/assets/15330503/19366077/fc7b3700-9195-11e6-959f-535b1cec6919.png)

**Comment by orignal** [comment]
Than it's bug

**Comment by l-n-s** [comment]
Done.
