### ISSUE TITLE
torrent client

### ISSUE THREAD

**Issue by mppdidi** [PurpleI2P/i2pd#672]
just want to report that the i2psnark standalone version is working via I2CP interface.
robert on the other hand is segfaulting via BOB. i suspect the ending " " space in i2pd is the issue.

**Comment by orignal** [comment]
Robert or i2pd?

**Comment by orignal** [comment]
I have tried with Robert 0.0.40.
Download few torrents with 100Kb/s average.
Don't see any issues

**Comment by atnaguzin** [comment]
And I used I2PSnark with I2Pd, using I2CP. It works  without issues.
