### ISSUE TITLE
b64 адрес для регистрации eepsite

### ISSUE THREAD

**Issue by dimzon** [PurpleI2P/i2pd#673]
Поднял eepsite, сгенерился ключ. По SECRET.b32.i2p все работает.
по адресу http://127.0.0.1:7070/?page=local_destination&b32=SECRET  есть поле base64
Попробовал вставить в b64 - на no.i2p ругалось на "левые символы" - удалил замыкающие "===" - вроде взлетело, сформировало ссылку для адресхелпера но  не открывает ( SECRET.b32.i2p работает)
На reg.rus.i2p ругается что b64 адрес должен быть 516 символов

**Comment by orignal** [comment]
так это проблема с reg.rus.i2p
516 это  только для DSA, который давно уже устарел

**Comment by l-n-s** [comment]
Регистрируйтесь на inr.i2p, там все отлично. Админам других регистраторов стоит обновить py-i2phosts.
