### ISSUE TITLE
Ошибка при компиляции armel

### ISSUE THREAD

**Issue by wmlex** [PurpleI2P/i2pd#675]
При сборке пакета (debuild) для armel на базе процессора kirkwood процесс завершается с ошибкой. При компиляции бинарника make-ом ситуация та же. На архитектуре amd64 собралось без проблем. Подскажите в чем причина?

` ~/i2pd# debuild --no-tgz-check
 dpkg-buildpackage -rfakeroot -D -us -uc
dpkg-buildpackage: warning: using a gain-root-command while being root
dpkg-buildpackage: source package i2pd
dpkg-buildpackage: source version 2.10.0-1
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by orignal <orignal@i2pmail.org>
 dpkg-source --before-build i2pd
dpkg-buildpackage: host architecture armel
dpkg-source: info: applying 01-tune-build-opts.patch
 fakeroot debian/rules clean
dh clean --parallel
   dh_testdir -O--parallel
   dh_auto_clean -O--parallel
make[1]: Entering directory '/root/i2pd'
rm -rf obj
rm -rf docs/generated
rm -f i2pd libi2pd.so libi2pd.a libi2pdclient.so libi2pdclient.a
make[1]: Leaving directory '/root/i2pd'
   dh_clean -O--parallel
 dpkg-source -b i2pd
dpkg-source: info: using source format `3.0 (quilt)'
dpkg-source: info: building i2pd using existing ./i2pd_2.10.0.orig.tar.gz
dpkg-source: info: building i2pd in i2pd_2.10.0-1.debian.tar.xz
dpkg-source: info: building i2pd in i2pd_2.10.0-1.dsc
 debian/rules build
make: 'build' is up to date.
 fakeroot debian/rules binary
dh binary --parallel
   dh_testdir -O--parallel
   dh_auto_configure -O--parallel
   dh_auto_build -O--parallel
make[1]: Entering directory '/root/i2pd'
g++ -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -DUSE_UPNP -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/Gzip.o Gzip.cpp
g++ -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -DUSE_UPNP -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/Crypto.o Crypto.cpp
g++ -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -DUSE_UPNP -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/Datagram.o Datagram.cpp
g++ -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -DUSE_UPNP -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/Garlic.o Garlic.cpp
g++ -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -DUSE_UPNP -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/I2NPProtocol.o I2NPProtocol.cpp
g++ -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -DUSE_UPNP -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/LeaseSet.o LeaseSet.cpp
g++ -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -DUSE_UPNP -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/Log.o Log.cpp
g++ -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -DUSE_UPNP -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/NTCPSession.o NTCPSession.cpp
g++ -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -DUSE_UPNP -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/NetDb.o NetDb.cpp
g++ -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -DUSE_UPNP -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/NetDbRequests.o NetDbRequests.cpp
g++ -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -DUSE_UPNP -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/Profiling.o Profiling.cpp
g++ -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -DUSE_UPNP -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/Reseed.o Reseed.cpp
g++ -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -DUSE_UPNP -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/RouterContext.o RouterContext.cpp
g++ -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -DUSE_UPNP -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/RouterInfo.o RouterInfo.cpp
g++ -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -DUSE_UPNP -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/Signature.o Signature.cpp
g++ -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -DUSE_UPNP -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/SSU.o SSU.cpp
g++ -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -DUSE_UPNP -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/SSUSession.o SSUSession.cpp
g++ -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -DUSE_UPNP -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/SSUData.o SSUData.cpp
g++ -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -DUSE_UPNP -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/Streaming.o Streaming.cpp
g++ -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -DUSE_UPNP -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/Identity.o Identity.cpp
g++ -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -DUSE_UPNP -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/TransitTunnel.o TransitTunnel.cpp
g++ -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -DUSE_UPNP -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/Transports.o Transports.cpp
g++ -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -DUSE_UPNP -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/Tunnel.o Tunnel.cpp
g++ -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -DUSE_UPNP -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/TunnelEndpoint.o TunnelEndpoint.cpp
g++ -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -DUSE_UPNP -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/TunnelPool.o TunnelPool.cpp
g++ -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -DUSE_UPNP -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/TunnelGateway.o TunnelGateway.cpp
g++ -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -DUSE_UPNP -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/Destination.o Destination.cpp
Destination.cpp: In member function 'void i2p::client::ClientDestination::HandleCheckForReady(const boost::system::error_code&, i2p::client::ClientDestination::ReadyPromise*)':
Destination.cpp:738:5: error: invalid use of incomplete type 'i2p::client::ClientDestination::ReadyPromise {aka class std::promise<std::shared_ptr<i2p::client::ClientDestination> >}'
    p->set_value(nullptr);
     ^
In file included from NetDb.h:11:0,
                 from Destination.cpp:8:
/usr/include/c++/4.9/future:123:11: error: declaration of 'i2p::client::ClientDestination::ReadyPromise {aka class std::promise<std::shared_ptr<i2p::client::ClientDestination> >}'
     class promise;
           ^
Destination.cpp:740:5: error: invalid use of incomplete type 'i2p::client::ClientDestination::ReadyPromise {aka class std::promise<std::shared_ptr<i2p::client::ClientDestination> >}'
    p->set_value(std::shared_ptr<ClientDestination>(this));
     ^
In file included from NetDb.h:11:0,
                 from Destination.cpp:8:
/usr/include/c++/4.9/future:123:11: error: declaration of 'i2p::client::ClientDestination::ReadyPromise {aka class std::promise<std::shared_ptr<i2p::client::ClientDestination> >}'
     class promise;
           ^
Makefile:60: recipe for target 'obj/Destination.o' failed
make[1]: *** [obj/Destination.o] Error 1
make[1]: Leaving directory '/root/i2pd'
dh_auto_build: make -j1 returned exit code 2
debian/rules:14: recipe for target 'binary' failed
make: *** [binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -D -us -uc failed`

`~/i2pd-2.10.0/build# cmake -DCMAKE_BUILD_TYPE=Release -DWITH_UPNP=ON -DWITH_STATIC=ON
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   program_options
--   date_time
-- Found MiniUPnP headers: /usr/include
-- Found MiniUPnP library: /usr/lib/arm-linux-gnueabi/libminiupnpc.a
-- ---------------------------------------
-- Build type         : Release
-- Compiler vendor    : GNU
-- Compiler version   : 4.9.2
-- Compiler path      : /usr/bin/c++
-- Install prefix:    : /usr/local
-- Options:
--   AESNI            : OFF
--   HARDENING        : OFF
--   LIBRARY          : ON
--   BINARY           : ON
--   STATIC BUILD     : ON
--   UPnP             : ON
--   PCH              : OFF
--   MESHNET          : OFF
--   ADDRSANITIZER    : OFF
--   THEADSANITIZER   : OFF
-- ---------------------------------------
-- Configuring done
-- Generating done
-- Build files have been written to: /root/i2pd-2.10.0/build

~/i2pd-2.10.0/build# make
Scanning dependencies of target libi2pd
[  2%] Building CXX object CMakeFiles/libi2pd.dir/root/i2pd-2.10.0/Config.cpp.o
[  4%] Building CXX object CMakeFiles/libi2pd.dir/root/i2pd-2.10.0/Crypto.cpp.o
[  6%] Building CXX object CMakeFiles/libi2pd.dir/root/i2pd-2.10.0/Garlic.cpp.o
[  8%] Building CXX object CMakeFiles/libi2pd.dir/root/i2pd-2.10.0/Gzip.cpp.o
[ 10%] Building CXX object CMakeFiles/libi2pd.dir/root/i2pd-2.10.0/I2NPProtocol.cpp.o
[ 12%] Building CXX object CMakeFiles/libi2pd.dir/root/i2pd-2.10.0/Identity.cpp.o
[ 14%] Building CXX object CMakeFiles/libi2pd.dir/root/i2pd-2.10.0/LeaseSet.cpp.o
/root/i2pd-2.10.0/LeaseSet.cpp:176:60: warning: unused parameter 'l' [-Wunused-parameter]
     return GetNonExpiredLeasesExcluding( [] (const Lease & l) -> bool { return false; }, withThreshold);
                                                            ^
[ 16%] Building CXX object CMakeFiles/libi2pd.dir/root/i2pd-2.10.0/FS.cpp.o
[ 18%] Building CXX object CMakeFiles/libi2pd.dir/root/i2pd-2.10.0/Log.cpp.o
[ 20%] Building CXX object CMakeFiles/libi2pd.dir/root/i2pd-2.10.0/NTCPSession.cpp.o
[ 22%] Building CXX object CMakeFiles/libi2pd.dir/root/i2pd-2.10.0/NetDbRequests.cpp.o
[ 24%] Building CXX object CMakeFiles/libi2pd.dir/root/i2pd-2.10.0/NetDb.cpp.o
[ 26%] Building CXX object CMakeFiles/libi2pd.dir/root/i2pd-2.10.0/Profiling.cpp.o
[ 28%] Building CXX object CMakeFiles/libi2pd.dir/root/i2pd-2.10.0/Reseed.cpp.o
[ 30%] Building CXX object CMakeFiles/libi2pd.dir/root/i2pd-2.10.0/RouterContext.cpp.o
/root/i2pd-2.10.0/RouterContext.cpp:429:69: warning: unused parameter 'len' [-Wunused-parameter]
  void RouterContext::HandleI2NPMessage (const uint8_t * buf, size_t len, std::shared_ptr<i2p::tunnel::InboundTunnel> from)
                                                                     ^
[ 32%] Building CXX object CMakeFiles/libi2pd.dir/root/i2pd-2.10.0/RouterInfo.cpp.o
[ 34%] Building CXX object CMakeFiles/libi2pd.dir/root/i2pd-2.10.0/SSU.cpp.o
[ 36%] Building CXX object CMakeFiles/libi2pd.dir/root/i2pd-2.10.0/SSUData.cpp.o
[ 38%] Building CXX object CMakeFiles/libi2pd.dir/root/i2pd-2.10.0/SSUSession.cpp.o
/root/i2pd-2.10.0/SSUSession.cpp:539:68: warning: unused parameter 'len' [-Wunused-parameter]
  void SSUSession::ProcessRelayRequest (const uint8_t * buf, size_t len, const boost::asio::ip::udp::endpoint& from)
                                                                    ^
/root/i2pd-2.10.0/SSUSession.cpp:640:69: warning: unused parameter 'len' [-Wunused-parameter]
  void SSUSession::ProcessRelayResponse (const uint8_t * buf, size_t len)
                                                                     ^
/root/i2pd-2.10.0/SSUSession.cpp:692:66: warning: unused parameter 'len' [-Wunused-parameter]
  void SSUSession::ProcessRelayIntro (const uint8_t * buf, size_t len)
                                                                  ^
[ 40%] Building CXX object CMakeFiles/libi2pd.dir/root/i2pd-2.10.0/Streaming.cpp.o
/root/i2pd-2.10.0/Streaming.cpp:732:68: warning: unused parameter 'ecode' [-Wunused-parameter]
  void Stream::HandleAckSendTimer (const boost::system::error_code& ecode)
                                                                    ^
[ 42%] Building CXX object CMakeFiles/libi2pd.dir/root/i2pd-2.10.0/Destination.cpp.o
/root/i2pd-2.10.0/Destination.cpp:273:75: warning: unused parameter 'len' [-Wunused-parameter]
  void LeaseSetDestination::HandleI2NPMessage (const uint8_t * buf, size_t len, std::shared_ptr<i2p::tunnel::InboundTunnel> from)
                                                                           ^
/root/i2pd-2.10.0/Destination.cpp:361:90: warning: unused parameter 'len' [-Wunused-parameter]
  void LeaseSetDestination::HandleDatabaseSearchReplyMessage (const uint8_t * buf, size_t len)
                                                                                          ^
/root/i2pd-2.10.0/Destination.cpp: In member function 'void i2p::client::ClientDestination::HandleCheckForReady(const boost::system::error_code&, i2p::client::ClientDestination::ReadyPromise*)':
/root/i2pd-2.10.0/Destination.cpp:738:5: error: invalid use of incomplete type 'i2p::client::ClientDestination::ReadyPromise {aka class std::promise<std::shared_ptr<i2p::client::ClientDestination> >}'
    p->set_value(nullptr);
     ^
In file included from /root/i2pd-2.10.0/NetDb.h:11:0,
                 from /root/i2pd-2.10.0/Destination.cpp:8:
/usr/include/c++/4.9/future:123:11: error: declaration of 'i2p::client::ClientDestination::ReadyPromise {aka class std::promise<std::shared_ptr<i2p::client::ClientDestination> >}'
     class promise;
           ^
/root/i2pd-2.10.0/Destination.cpp:740:5: error: invalid use of incomplete type 'i2p::client::ClientDestination::ReadyPromise {aka class std::promise<std::shared_ptr<i2p::client::ClientDestination> >}'
    p->set_value(std::shared_ptr<ClientDestination>(this));
     ^
In file included from /root/i2pd-2.10.0/NetDb.h:11:0,
                 from /root/i2pd-2.10.0/Destination.cpp:8:
/usr/include/c++/4.9/future:123:11: error: declaration of 'i2p::client::ClientDestination::ReadyPromise {aka class std::promise<std::shared_ptr<i2p::client::ClientDestination> >}'
     class promise;
           ^
/root/i2pd-2.10.0/Destination.cpp: At global scope:
/root/i2pd-2.10.0/Destination.cpp:745:73: warning: unused parameter 'len' [-Wunused-parameter]
  void ClientDestination::HandleDataMessage (const uint8_t * buf, size_t len)
                                                                         ^
CMakeFiles/libi2pd.dir/build.make:514: recipe for target 'CMakeFiles/libi2pd.dir/root/i2pd-2.10.0/Destination.cpp.o' failed
make[2]: *** [CMakeFiles/libi2pd.dir/root/i2pd-2.10.0/Destination.cpp.o] Error 1
CMakeFiles/Makefile2:131: recipe for target 'CMakeFiles/libi2pd.dir/all' failed
make[1]: *** [CMakeFiles/libi2pd.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by orignal** [comment]
gcc какой версии?

**Comment by wmlex** [comment]
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabi/4.9/lto-wrapper
Target: arm-linux-gnueabi
Configured with: ../src/configure -v --with-pkgversion='Debian 4.9.2-10' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libitm --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-armel/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-armel --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-armel --with-arch-directory=arm --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-sjlj-exceptions --with-arch=armv4t --with-float=soft --enable-checking=release --build=arm-linux-gnueabi --host=arm-linux-gnueabi --target=arm-linux-gnueabi
Thread model: posix
gcc version 4.9.2 (Debian 4.9.2-10)

**Comment by orignal** [comment]
http://stackoverflow.com/questions/31184853/multithreaded-code-wont-compile-using-g-but-is-fine-with-clang

Посмотрю можно ли этот кусок исключить с помощью #ifdef

**Comment by orignal** [comment]
Поправил

**Comment by wmlex** [comment]
Большое спасибо! Все успешно собралось.
