### ISSUE TITLE
Getting i2pd into Debian repository

### ISSUE THREAD

**Issue by l-n-s** [PurpleI2P/i2pd#682]
Having our I2P client in Debian/Ubuntu repositories will boost user experience a lot. Currently, I don't see any problems with i2pd which will make it difficult. We need a package maintainer and then apply to [Debian Mentors](https://mentors.debian.net/).

Can you be our package maintainer? Or if you know someone who can, please, help us with this issue.

**Comment by majestrate** [comment]
ubuntu maybe
debian stable would mean no one updates i2pd for a long long time.

**Comment by l-n-s** [comment]
Ubuntu takes packages from Debian Unstable. I think we should be there, at least. Stable could be possible when we will support LTS versions.

**Comment by r4sas** [comment]
I hope it builded correctly:
http://repo.r4sas.i2p/debian

**Comment by majestrate** [comment]
`repo.r4sas.i2p` doesn't seem to be registered anywhere as of right now.

**Comment by r4sas** [comment]
@majestrate i2pd must find it from top-level domain.

**Comment by romx** [comment]
Can you add build for armhf into your repository?

**Comment by r4sas** [comment]
@romx I haven't armhf devices to build on. I tried to build cross-compile, but haven't success.

**Comment by radfish** [comment]
If you have a buildbot-like system, I can run a slave on my armv7h (Scaleway).

They also have aarch64 since recently, with hourly pricing, so that can be hooked up too either with some effort to launch server for each build, or with some 3eu/mo to keep the server always up.

**Comment by romx** [comment]
@r4sas 
> I haven't armhf devices to build on
Any new Raspberry Pi board is a good sample, musthave for any geek ;-)

**Comment by r4sas** [comment]
@radfish I use sbuild only, on Debian 8/amd64.
@romx not everyone have ability to buy things like that 😿.

**Comment by LLE8** [comment]
@r4sas 
@romx 
Is it helpful for arm build?
http://www.opennet.ru/opennews/art.shtml?num=46745

**Comment by r4sas** [comment]
https://packages.debian.org/search?keywords=i2pd
