### ISSUE TITLE
How stop I2pd ?

### ISSUE THREAD

**Issue by merlinnusr** [PurpleI2P/i2pd#688]
I dont see in the i2p --help any option to reset or stop i2pd

**Comment by orignal** [comment]
kill, kill -s HUP, kill -s INT

**Comment by atnaguzin** [comment]
Or using command 'Force Shutdown' - http://127.0.0.1:7070/?cmd=terminate

**Comment by manasb** [comment]
There is a 'graceful shutdown' signal, I think @orignal added it

**Comment by merlinnusr** [comment]
thx

**Comment by merlinnusr** [comment]
Another question why i2pd add to startup by default (I have linux mint rosa)

**Comment by majestrate** [comment]
why or how?

**Comment by atnaguzin** [comment]
@merlinnusr, If u install package, it always will install init.d startup scripts.
But u can disable auto starting with command `update-rc.d i2pd disable`

**Comment by manasb** [comment]
If the question is "how?", then answer would be make a script and add it to `/etc/rc.d/` or similar?
I'm not sure what the process is for Linux but on FreeBSD, you would add a line to `/etc/rc.conf` for auto-run on boot.

**Comment by merlinnusr** [comment]
the question is how? and thx for your replies

**Comment by merlinnusr** [comment]
update-rc.d: warning:  start runlevel arguments (none) do not match i2pd Default-Start values (2 3 4 5)
update-rc.d: warning:  stop runlevel arguments (none) do not match i2pd Default-Stop values (0 1 6)
 System start/stop links for /etc/init.d/i2pd do not exist.

**Comment by atnaguzin** [comment]
@merlinnusr 
> the question is how?
> i2pd add to startup by default (I have linux mint rosa)
That's changes point of view.
Simply - install package for Ubuntu 14.04 (Trusty Tahr).
Latest avaliable here: https://github.com/PurpleI2P/i2pd/releases
See for i2pd_2.10.0-1trusty1_<ARCH>.deb, where <ARCH> is your architecture.

**Comment by manasb** [comment]
Make sure you overwrite the i2pd binary after installing the package, I guess.

**Comment by senovr** [comment]
manasb, 
about adding a line to /etc/rc.conf- you mean standard
 i2pd_enable="YES" ?
or we have some different syntax?
I tried as above on freebsd, and i2pd is not going alive after reboot.

**Comment by l-n-s** [comment]
It is now documented at https://i2pd.readthedocs.io/en/latest/usage.html
