### ISSUE TITLE
Documentation issues: missing docs, improvement requests, etc

### ISSUE THREAD

**Issue by l-n-s** [PurpleI2P/i2pd#691]
Leave here any requests for documentation improvements.

**Comment by l-n-s** [comment]
> <psi> trust.routers=base64ident,base64ident,base64ident
> <psi> or in the ini file
> <psi> [trust]
> <psi> enabled=true
> <psi> routers=ident,ident,ident
> <psi> it's the base64 encoded ident

**Comment by majestrate** [comment]
systemd unit should also be added if possible

**Comment by atnaguzin** [comment]
@majestrate, @hagen-i2p: view #697 and check it before merging.

**Comment by l-n-s** [comment]
Read the Docs are broken, need to investigate. Probably `docs/build/windows.md` involved?

https://readthedocs.org/projects/i2pd/builds/4564419/

https://readthedocs.org/projects/i2pd/builds/

**Comment by l-n-s** [comment]
Read The Docs fixed. Please, use 4 spaces to indent the code in docs in future. 

Note, that Read The Docs uses standard Markdown, GitHub-flavored markdown is not standard.

**Comment by l-n-s** [comment]
Documentation issues went to separate repository https://github.com/PurpleI2P/i2pd_docs_en
