### ISSUE TITLE
Desktop GUI - Discussion

### ISSUE THREAD

**Issue by mikalv** [PurpleI2P/i2pd#693]
I'm opening this issue to discuss the desktop GUIs.

I'm hoping we can find a way to have a common codebase for the different platforms. Like Windows, Mac OS X and Linux (GTK/QT wm's)

However we will need a feature list / roadmap for this.

I've compiled a speclist here based on the configuration options for the router, and would like feedback on it. We would also need to define what should be done in what order.

**Specs**
- Built-in, not a router wrapper
- Log viewer
- Statistics view
- Tunnel statistics view
- Settings
  - Tunnels
    - Add new tunnel
    - Edit tunnel
    - Delete tunnel
  - Clients
    - SAM address/port
    - BOB address/port
    - I2CP address/port
    - HTTP Proxy address/port
  - Router
    - UPnP
      - Enable/Disable
      - UPnP name
    - Reseed
      - Edit URLs
      - Upload su3
    - Addressbook subscriptions
      - Edit subscription URLs

**Comment by lpze4jwhda5el3zxs1** [comment]
That would be really awesome, looking forward to that!

**Comment by hypnosis-i2p** [comment]
I had a config editing gui form for qt somewhere. Not sure whether I lost the form file

**Comment by hypnosis-i2p** [comment]
the place to place this code is /qt/i2pd_qt/

—Сapt.Obvious.

**Comment by hypnosis-i2p** [comment]
Please translate from Russ. yourself if you need.

Work notes.

[...]
<orignal> комменты в кофигах через гуй? фтопку
<abyss5> не
<abyss5> парсер конфигов после гуи эдитинга после записи в конфиг типа комменты должен сохранить, нэ?
<abyss5> orignal, 
<orignal> нет
<abyss5> ок
<orignal> с гуем не надо
<abyss5> а вообще - делать эту фигу?
<orignal> делать конечно
<orignal> ибо гуй есть а с него править настройки нельзя это некомильфо

**Comment by hypnosis-i2p** [comment]
abyss5> ну что orignal 
orignal> что?
abyss5> бэкэнд чтения-записи конфигов мне делать?
orignal> сделай внутри QT
abyss5> эээ не
orignal> не в основном коде пока
abyss5> блин
abyss5> ты хочешь дублировать код что ль
abyss5> ?
orignal> да
orignal> пусть будет пока старый
orignal> ты сделаешь в QT
orignal> мы обкатаем там
orignal> а потом перенесем
abyss5> ок

**Comment by hypnosis-i2p** [comment]
Some preliminary results (mainwindow.ui, .cpp, .h) are here https://github.com/hypnosis-i2p/i2pd/tree/openssl/qt/i2pd_qt 

I pause the work for some time.

**Comment by masaykh** [comment]
wxWidgets smaller and lighter but have needed functionality - isnt it will be better?

qt will make from light and fast i2p router - slow monster...

**Comment by majestrate** [comment]
wxWidgets has the "same" problem as qt does when it comes to "bloat"

**Comment by hypnosis-i2p** [comment]
<villain> Hypnosis: там метод в Reseed.h int ProcessZIPFile (const char * filename)
<villain> пабличный
<villain> его дергать и збс

**Comment by masaykh** [comment]
wxWidgets have bloat sure, but it is smaller.

**Comment by hypnosis-i2p** [comment]
<anon1> http://rgho.st/89fTdFynN
...
<anon1> стащить из HTTPServer.cpp готовый код

<Hypnosis> на чём кодишь это
<anon1> winapi
<Hypnosis> язык какой?
<anon1> C++
<Hypnosis> пиздить буду код у вас. у меня статус страничка по дефолту будет в qt аппе. загребу кот

**Comment by ChrisFernandez** [comment]
as long the desktop app is separated from the main i2pd daemon I am ok... reason? I am very happy with i2pd as is, because I can run it on remote servers with out the need to install or have to pull GTK/QT/TK etc etc crap into my servers...

**Comment by hypnosis-i2p** [comment]
@ChrisFernandez qt app is different from CLI (commandline interface) one

**Comment by orignal** [comment]
@ChrisFernandez it's not worth to run i2pd without GUI on windows and android.
That's not what users expect. So we must provide GUI there, it's minimal right now but should be better

**Comment by hypnosis-i2p** [comment]
Pending feature: Log viewer.

All other (of listed/requested above) is done at the desktop Qt GUI. Beautifications of the desktop GUI pending.

**Comment by hypnosis-i2p** [comment]
Also pending: Android GUI.

**Comment by ChrisFernandez** [comment]
What you mean? @orignal some people like to run i2pd on a "server" with no Xorg and no Desktop enviroment.. as a real unix daemon, that we connect to by openvpn from "anywhere"  do not force us to run a stupid GUI please, make it as an "option" for those who rather use it on their desktop

**Comment by orignal** [comment]
@ChrisFernandez, nobody is going to change the way how it works. However we use GUI for:
1. Windows
2. Android
3. QT as separate application (from qt folder)

**Comment by ChrisFernandez** [comment]
@orignal ahh ok sorry I misunderstood you. QT for desktop makes sense, but for server I like to keep using it as a daemon. cheers!

**Comment by hypnosis-i2p** [comment]
```
<мир_кудес> чёта беззвёздно и беспонтово
<мир_кудес> надо больше звёздности и понтов
```
а именно — сделать модный гуй как в телеграме

**Comment by cyisfor** [comment]
> Built-in, not a router wrapper

So wait... you mean if we want to leave i2p running when we're logged out, or have a dedicated i2p user, then we can't have a GUI? If we want to log out, we aren't allowed to for 10 minutes because of i2p? [Java I2P has built-in applications for torrents, e-mail and so on. i2pd is just a router which you can use with other software through I2CP interface.](/PurpleI2P/i2pd/wiki/Differences-between-i2pd-and-Java-I2P-router) So it'd make sense if the GUI was at least an I2CP client, and didn't require running a whole router of its own.

**Comment by hypnosis-i2p** [comment]
@cyisfor AFAIU Java has a built-in internal web gui, not i2cp one.

**Comment by mewmew-i2p** [comment]
@cyisfor Please discuss that with @orignal . If he agrees to include that into the repo, you could implement that as code.

**Comment by mewmew-i2p** [comment]
```
<Hypnosis_> orignal, чо думаешь про qt гуй?
<Hypnosis_> надо же его в релизы собирать
<orignal> надо
<orignal> я даже иногда собираю ))
```

**Comment by mewmew-i2p** [comment]
all done

admins please close this ticket

**Comment by l-n-s** [comment]
Yep, looks like we have QT GUI working now :champagne:
