### ISSUE TITLE
Error while trying to  install i2pd in ubuntu using sudo dpkg -i i2pd_2.10.0-1(    )1_i386.deb 

### ISSUE THREAD

**Issue by lpze4jwhda5el3zxs1** [PurpleI2P/i2pd#702]
Error while trying to  install i2pd in ubuntu using sudo dpkg -i i2pd_2.10.0-1(    )1_i386.deb 

I tried jessie, wheezy, trusty, xenial but none were working. This is error
>
Preparing to unpack i2pd_2.10.0-1xenial1_i386.deb ...
Unpacking i2pd (2.10.0-1jessie1) over (2.10.0-1trusty1) ...
dpkg: dependency problems prevent configuration of i2pd:
 i2pd depends on libboost-date-time1.55.0; however:
  Package libboost-date-time1.55.0 is not installed.
 i2pd depends on libboost-filesystem1.55.0; however:
  Package libboost-filesystem1.55.0 is not installed.
 i2pd depends on libboost-program-options1.55.0; however:
  Package libboost-program-options1.55.0 is not installed.
 i2pd depends on libboost-system1.55.0; however:
  Package libboost-system1.55.0 is not installed.
>
dpkg: error processing package i2pd (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for systemd (231-9ubuntu1) ...
Errors were encountered while processing:
 i2pd

**Comment by majestrate** [comment]
have you tried:

    apt-get -f install

**Comment by K1773R** [comment]
dpkg is only the package manager. apt is downloading and maintaining the dependencies. the command above will install all missing dependencies or remove problematic packages (in this case, the first).

**Comment by lpze4jwhda5el3zxs1** [comment]
@majestrate @K1773R Thanks. Should I use jessie, wheezy, trusty or xenial?

**Comment by atnaguzin** [comment]
@lpze4jwhda5el3zxs1 What version of your ubuntu?

11 нояб. 2016 г. 12:46 AM пользователь "lpze4jwhda5el3zxs1" <
notifications@github.com> написал:

**Comment by lpze4jwhda5el3zxs1** [comment]
@atnaguzin 16.10 32bits.

**Comment by majestrate** [comment]
have you tried installing the packages that it says are missing?

**Comment by atnaguzin** [comment]
@lpze4jwhda5el3zxs1 install packages by command:
```
sudo apt-get install libboost-date-time1.58.0 libboost-filesystem1.58.0 \
libboost-program-options1.58.0 libboost-system1.58.0
```

**Comment by lpze4jwhda5el3zxs1** [comment]
I solved the problem using i2pd ppa packages for Ubuntu https://i2p.rocks/blog/ppa-repository-for-i2pd-is-available.html

@l-n-s You can mark this as closed
