### ISSUE TITLE
TODO: Find something to parse html/template system. This is horrible.

### ISSUE THREAD

**Issue by timewall** [PurpleI2P/i2pd#705]
how about with TNTNET

http://www.tntnet.org/

Tntnet

Tntnet is a web server which allows users to develop web applications using C++. It has a template language ecpp where C++ code can be embedded into html similar to php or jsp. The pages are compiled and linked into a shared library. The result is a native web application which is compact and fast.

of tntnet comes cxxtools a nice framework for many thinks

**Comment by majestrate** [comment]
also the webui doesn't have CORS or CSRF tokens which is something to do.

**Comment by l-n-s** [comment]
Do we need to pull another dependency to i2pd just for simple WebUI? It's not complex and feature rich by design, only has very basic commands and displays statistics.

**Comment by majestrate** [comment]
we do need csrf protection at least
