### ISSUE TITLE
add CSRF tokens and CORS to webui

### ISSUE THREAD

**Issue by majestrate** [PurpleI2P/i2pd#706]

**Comment by l-n-s** [comment]
@orignal added CSRF tokens in https://github.com/PurpleI2P/i2pd/commit/10d6cd989608d85dd80ec19433ca66f817a73bbf

There needs to be CORS and protection from clickjacking?

For click-jacking protection, HTTPServer needs to always send header `X-Frame-Options: "SAMEORIGIN"`
