### ISSUE TITLE
i2pd.website should be in HTTPS

### ISSUE THREAD

**Issue by ultraviolet891** [PurpleI2P/i2pd#707]
As everyone knows there's little excuse today to not use HTTPS. https://letsencrypt.org/ would be sufficient here, it's a free, automated, and open Certificate Authority.

**Comment by manasb** [comment]
I would agree that having a letsencrypt cert on it would be useful, especially if serving binaries for i2pd.

**Comment by orignal** [comment]
binaries are in this repository, not at the website

**Comment by manasb** [comment]
Oh yeah, you're right. Looks like there's just 1 JS file? Yeah.. I don't know if a single mostly-static HTML page needs a cert, haha. Probably good for preventing the webpage from being altered in transit?

**Comment by l-n-s** [comment]
It will be nice. But since we use GitHub pages, it is not possible to enable HTTPS right now. Read: https://github.com/isaacs/github/issues/156

We must move to another hosting for that static HTML file to enable HTTPS. The question is: is it really worth it?

**Comment by orignal** [comment]
If github doesn't allow it, no reason
