### ISSUE TITLE
i2pd: high memory usage on load

### ISSUE THREAD

**Issue by kayrus** [PurpleI2P/i2pd#711]
640K is not enough...

Not sure why but on high load it consumes lot of memory thus other processes get OOM killed.

```sh
$ ps aux --sort -rss | head -2
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
i2pd     22596 28.7 47.3 2460880 966484 ?      Ssl  00:44 148:03 /usr/sbin/i2pd --service --daemon --log=file --logfile=/var/log/i2pd.log --conf=/etc/i2pd/i2pd.conf --tunconf=/etc/i2pd/tunnels.conf
```

Bob along with transmission-i2p are used. Let me know which logs/statistics do you need.

**Comment by orignal** [comment]
Can you provide more details from webconsole like bandwidth, number of client and transit tunnels, transports?
And what are you trying do? How many torrents you are downloading?
Basically I need steps to reproduce.

**Comment by kayrus** [comment]
```
Uptime: 1 days, 20 hours, 33 min, 35 seconds
Network status: Firewalled
Tunnel creation success rate: 58%
Received: 7.72 GiB (17.14 KiB/s)
Sent: 35.36 GiB (130.31 KiB/s)
Data path: /var/lib/i2pd

Hidden content. Press on text to see.

Routers: 1508 Floodfills: 896 LeaseSets: 0
Client Tunnels: 55 Transit Tunnels: 2
```

14 torrents are seeding, 1 is downloading.

for now memory usage is 1.3Gb:

```sh
$ ps aux --sort -rss | head -2
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
i2pd       985 36.5 64.0 4140864 1306960 ?     Ssl  Nov16 979:06 /usr/sbin/i2pd --service --daemon --log=file --logfile=/var/log/i2pd.log --conf=/etc/i2pd/i2pd.conf --tunconf=/etc/i2pd/tunnels.conf
```

**Comment by kayrus** [comment]
![memory-day](https://cloud.githubusercontent.com/assets/4047483/20440681/5b1bdc8c-adc1-11e6-9e31-3d80afe0f768.png)

**Comment by orignal** [comment]
Please provide details of  your local destination. Number of LeaseSets, number of incoming tags.

**Comment by kayrus** [comment]
Lease sets tab doesn't show anything even when I click on it.

**Comment by orignal** [comment]
Find it in the Local Destinations list. One corresponding to your BOB session.

**Comment by orignal** [comment]
One more question: is it a floodfill?

**Comment by kayrus** [comment]
No, it is not floodfill. I use `bandwidth = P`. 
![screenshot 2016-12-21 at 21 44 39](https://cloud.githubusercontent.com/assets/4047483/21405531/b826d2f0-c7c6-11e6-9d9e-f1da53c45c59.png)
![screenshot 2016-12-21 at 21 44 20](https://cloud.githubusercontent.com/assets/4047483/21405532/b83d102e-c7c6-11e6-84e5-0ef1da4bab5c.png)
![screenshot 2016-12-21 at 21 44 02](https://cloud.githubusercontent.com/assets/4047483/21405533/b8615858-c7c6-11e6-8ee1-8f2103e5185e.png)
![screenshot 2016-12-21 at 21 45 21](https://cloud.githubusercontent.com/assets/4047483/21405542/ce668524-c7c6-11e6-86a9-343798e03e7e.png)

**Comment by majestrate** [comment]
to clarify, this is while using transmission-i2p right?

**Comment by kayrus** [comment]
@majestrate yes

**Comment by majestrate** [comment]
i think i have a patch, if you want to try it out it's at https://github.com/majestrate/i2pd/tree/fix-garlic-leak

**Comment by kayrus** [comment]
@majestrate ok, will let you know the results.

**Comment by kayrus** [comment]
@majestrate i2pd failed after ~2h:

```
22:56:56@4/error - Streaming: No packets have been received yet
22:56:56@4/error - Streaming: No packets have been received yet
22:56:56@4/error - I2PTunnel: stream read error: Connection timed out
22:56:56@4/error - Streaming: No packets have been received yet
22:56:56@4/error - Streaming: No packets have been received yet
22:56:56@4/error - Streaming: No packets have been received yet
22:56:56@4/error - Streaming: No packets have been received yet
22:56:56@4/error - I2PTunnel: stream read error: Connection timed out
```

And now transmission can not connect to daemon

**Comment by orignal** [comment]
Do you have a core file and stack trace?
That's probably the reason of that memory leak.

**Comment by kayrus** [comment]
nope, coredumps were disabled. will enable them and try to get one.

**Comment by kayrus** [comment]
[this](https://github.com/majestrate/i2pd/tree/fix-garlic-leak) build doesn't work well. I got segfault only once on high throughput and then I was not able to reproduce it. But I have to restart it manually becausethe process is still running but the i2p network doesn't work.

**Comment by kayrus** [comment]
It is not possible to use neither patched release nor latest 2.11.0. It works only for 1h and then I have to restart both i2pd and transmission-daemon-i2pd.
Rolled back to 2.10. It consumes memory, but at least I can restart it every day, not every hour.

**Comment by majestrate** [comment]
@kayrus try using what's in HEAD right now in purplei2p/i2pd repo, that branch of mine is out of date at the moment.

**Comment by orignal** [comment]
@kayrus that's know issue with torrents in 2.11. Trunk fixes the issue

**Comment by kayrus** [comment]
@majestrate @orignal seems better. at least it doesn't consume lot of memory. it does, but not much. sometimes client can not connect to i2pd. consider resolved. thanks, guys.

**Comment by orignal** [comment]
@kayrus the question is not if it consumes a lot of memory but if memory usage keeps growing that's still a issue

**Comment by kayrus** [comment]
@orignal not yet
