### ISSUE TITLE
rekey http proxy destination

### ISSUE THREAD

**Issue by mppdidi** [PurpleI2P/i2pd#717]
Is there a way to rekey the destination key of the http proxy besides restarting the router ?
If not could you implement this feature ?

Kind regards.

**Comment by majestrate** [comment]
I was toying with a feature like this but having it as an option for any client tunnel where the keys rotate every $interval.

I think i had a branch for this with it implemented half way.

**Comment by r4sas** [comment]
Tunnels reloading was implemented.
