### ISSUE TITLE
Ext address 127.0.0.1

### ISSUE THREAD

**Issue by bol-van** [PurpleI2P/i2pd#720]
Is it normal having 127.0.0.1 as external address ?
It detected ipv6 address but not ipv4.
Device has external IPv4 address with inet on l2p interace, 10.x address without inet on eth1, 192.168.x address on eth0.

Our external address:
SSU     127.0.0.1:12
NTCP  127.0.0.1:12
NTCP6  2001:470:yyyy:xxxx::1:12
SSU6     2001:470:yyyy:xxxx::1:12

I'm on LEDE mips32  musl  i2pd 2.10.1.

See errors in log :

17:37:55@855/warn - SSU: session with 5.138.221.232:29451 was not established after 5 seconds
17:37:55@855/warn - SSU: session with 178.32.217.168:21424 was not established after 5 seconds
17:37:55@140/error - Transports: No NTCP or SSU addresses available
17:37:55@140/error - Transports: No NTCP or SSU addresses available
17:37:55@855/warn - SSU: session with 178.62.4.205:9793 was not established after 5 seconds
17:37:55@140/error - Transports: No NTCP or SSU addresses available
17:37:58@855/warn - SSU: session with 47.90.1.26:19514 was not established after 5 seconds
17:37:58@140/error - Transports: No NTCP or SSU addresses available

**Comment by majestrate** [comment]
what is default route for ipv4?

looks like a bug.

**Comment by bol-van** [comment]
I specified ifname value and ipv4 address appeared.
But log errors still appear.
And 2 more issues I posted in separate topics -  dynamic IP and separate v4/v6 ifname.

**Comment by bol-van** [comment]
I have 2 default routes with different metric.
This situation is common for all VPN connections.
VPN metric is less (more priority).

**Comment by nephros** [comment]
Can confirm.

I have a rather complex setup with several ifaces (LAN, WLAN, VPN, other tunnels etc) and use policy routing. Details below.

I specify in the config file:

ipv4 = true
ipv6 = false
ifname = tun1
host = 192.1.2.3

BUT, in my case i2pd always selects the wlan0 interface / 192.168.0.1, not the fallback 127.0.0.1 address to connect over, and of course not the specified device/interface from config.

# ip route show looks something like this, there's also several "ip rules" and additional tables to direct stuff to the correct routes.

default via 192.168.0.30 dev wlan0  metric 2003 
10.10.1.0/24 dev tun0  proto kernel  scope link  src 10.10.1.16 
127.0.0.0/8 via 127.0.0.1 dev lo 
192.168.0.0/24 dev wlan0  proto kernel  scope link  src 192.168.0.1 
192.168.1.0/30 dev lan0  proto kernel  scope link  src 192.168.1.1 
192.168.100.0/27 via 192.168.100.2 dev vpn0 
192.168.100.2 dev vpn0  proto kernel  scope link  src 192.168.100.1 

# ip addr looks like this (snipped):

2: lan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    inet 192.168.1.1/30 brd 192.168.1.3 scope global lan0
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    inet 192.168.0.1/27 brd 192.168.0.255 scope global wl1
4: tun0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1
    link/ipip 0.0.0.0 brd 0.0.0.0
5: vpn0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 100
        inet 192.168.100.1 peer 192.168.100.2/32 scope global vpn0
6: tun0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 100
    inet 10.10.1.16/24 brd 10.10.1.255 scope global tun0
8: tun1@NONE: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1480 qdisc noqueue state UNKNOWN group default qlen 1
    link/ipip 192.1.2.3 peer 10.10.35.35
    inet 192.1.2.3/32 scope global tun1
