### ISSUE TITLE
dynamic IP problem

### ISSUE THREAD

**Issue by bol-van** [PurpleI2P/i2pd#721]
On configurations with dynamic IP i2pd remembers old IP address in router.info file and displays it in "our external addresses". Until I delete router.info manually and restart daemon. Probably some functionality is broken.

**Comment by orignal** [comment]
This is UDP connectivity issue, it simply can't establish any SSU session.
Check if Status is "Testing" and also your system clock

**Comment by bol-van** [comment]
>  Transports: No NTCP or SSU addresses available

I suppose its answer to another problem related to config file errors.
Network status: OK , time is NTP synced - its ok.
So I assume its related to unreachability of invidual peers

**Comment by orignal** [comment]
If network status OK it should get correct IP

**Comment by bol-van** [comment]
Returning to the main question what about checking  if current IP is not the same as in router.info ?

**Comment by orignal** [comment]
That's what we always do.
If we see it changed we update router.info and republish it.
It works for years now

**Comment by bol-van** [comment]
OK. It seems address gets updated in time, not immediately.

**Comment by bol-van** [comment]
But still  there's a problem. If interface get restarted with new IP  i2pd doesnt track this change. It needs to be restarted on interface restart

**Comment by orignal** [comment]
It does, once it tries to connect to any SSU.
Agree it might not happen immediately (but it should).
Let me think what can be done.

**Comment by bol-van** [comment]
It does not happen for minutes. Browsing i2p sites change nothing. Still old address on web panel

**Comment by orignal** [comment]
go to webconsole/Router commands/Run peer test

**Comment by bol-van** [comment]
Pressed that.

22:37:54@988/info - I2NP: Outbound tunnel 3919777150 has been declined
22:37:54@988/info - I2NP: Inbound tunnel 24586594 has been created
22:37:54@988/info - I2NP: Outbound tunnel 564820420 has been created

IP does not change.
It changes after long wait. I waited ~30 mins , looked there again and ip was new

**Comment by orignal** [comment]
Next time when you click on "Run peer test", see if you have any SSU sessions in Transports

**Comment by bol-van** [comment]
Checked. Several SSUs appear and disappear soon.
But ip still the same. It change after some time only (minutes)

**Comment by l-n-s** [comment]
Any updates? Can you change issue title to be more specific? Or should we close it?
