### ISSUE TITLE
Separate ipv4 and ipv6 ifname

### ISSUE THREAD

**Issue by bol-van** [PurpleI2P/i2pd#722]
On configuration with tunneled ipv6  ipv4 and ipv6 addresses can be on different interfaces.
Its not enough to have ifname. Need ifname4 and ifname6

**Comment by majestrate** [comment]
adding now

**Comment by bol-van** [comment]
Its not working correctly.

ifname = l2tp-bee
ifname4 = l2tp-bee
ifname6 = 6in4-he

SSU     37.144.70.186:12
NTCP  37.144.70.186:12
SSU6     :::12
NTCP6  :::12
SSU     37.144.70.186:12
NTCP  37.144.70.186:12
SSU6     2001:470:xxxx:yyyy::2:12
NTCP6  2001:470:xxxx:yyyy::1:12

ifname4 = l2tp-bee
ifname6 = 6in4-he


and always
21:07:08@470/info - NTCP: Start listening TCP port 12
21:07:08@470/info - NTCP: Start listening V6 TCP port 12
21:07:08@470/error - NTCP: Failed to bind to ip4 port 12bind: Address in use
21:07:08@470/error - NTCP: failed to bind to ip6 port 12

there's nothing on port 12. Changing port does not help. Looks like it has duplicate addresses in the list and tries to bind several times. Second and later times fail.
Also not clear why zero ipv6 is still present

**Comment by l-n-s** [comment]
Looks like it is implemented. Any updates? Does it work correct now? Should we close the issue?
