### ISSUE TITLE
wtf? error - Destination: runtime exception: bad_function_call

### ISSUE THREAD

**Issue by hypnosis-i2p** [PurpleI2P/i2pd#727]
i2pd v2.10.1 / ubuntu trusty

is using the exception mechanism the best way to implement / handle things?

**Comment by majestrate** [comment]
i have been hunting this for a long time, it happens somewhere in the boost::asio::io_service.run loop, because of that i can't get it to yield a proper backtrace yet.

**Comment by orignal** [comment]
scenario, please
Basically it happens if an instance doesn't exist anymore

**Comment by l-n-s** [comment]
Can you change the title to a more correct description of the problem? Or should we even keep it open?

**Comment by r4sas** [comment]
I think we can close. 4 releases - too big time.

**Comment by majestrate** [comment]
This is probably fixed.
