### ISSUE TITLE
Load tunnel configuration files from directory /etc/i2pd/tunnel.conf.d

### ISSUE THREAD

**Issue by l-n-s** [PurpleI2P/i2pd#728]
Probably, good idea to manage tunnel configuration files dynamically from directory `tunnel.conf.d/*`

Like it is done in Nginx/Apache - you can create different configuration files for various web apps in folder `conf.d` and they will auto-load after restart/config reload.

It will help with end-user apps distribution. For example, one could create package for self-hosted anon IRC server, which will only need to create `/etc/i2pd/tunnel.conf.d/ircserver.conf` and reload i2pd.

**Comment by orignal** [comment]
so, per file rather than per record in .ini

**Comment by l-n-s** [comment]
@orignal nignx/apache does it with "include" config item, like

    include /etc/nginx/conf.d/*.conf;

Tunnel settings are not "one per file", they can be grouped in files in any order, so its more flexible.

**Comment by l-n-s** [comment]
Thats why they use LUA-like syntax to write configs, it may be hard to do with boost configurator

**Comment by orignal** [comment]
please do research of available boost parsers. there are ini, xml and json for sure

**Comment by majestrate** [comment]
@l-n-s related to i2lua how so?

**Comment by l-n-s** [comment]
@majestrate I mean not i2lua issue currently. But possibly in future, do all configuration with Lua... Imagine super flexible anon-network framework :wink:
