### ISSUE TITLE
мешается в таскбаре инстанс и2пд + под виндой у меня daemon=true фэйлится

### ISSUE THREAD

**Issue by hypnosis-i2p** [PurpleI2P/i2pd#730]
попозже точную мессагу лога добуду

**Comment by hypnosis-i2p** [comment]
orignal> не надо там daemon=true
abyss5_> мешается в таскбаре инстанс и2пд
abyss5_> прятать бы его кудато

**Comment by hypnosis-i2p** [comment]
orignal_> abyss5_ там не допилено
orignal_> есть как то service
orignal_> кстати ты можешь собрать чисто коносльный
abyss5_> да не, чисто консольный не хотю
orignal_> тогда разбирайся в коде DaemonWin32
orignal_> там как то можно сервисом делать
orignal_> mlt даже как то делал

**Comment by orignal** [comment]
@mlt не подскажешь как его как сервис запустить?

**Comment by mlt** [comment]
ку! Я давно не пересобирал проект... надо бы попробовать.
Если всё сильно не поменялось с тех пор, то [моя писанина](https://github.com/PurpleI2P/i2pd/wiki/Setting-up-i2pd-as-Windows-Service) должно быть всё ещё актуальна. Я бы не совал daemon=true в конфиг, а передовал бы как аргумент сервису, как описано по ссылке. Я бы держал 2 дата-папки. Отдельно для сервиса (в `C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\i2pd`) и отдельно для гуя. Чтоб на разных портах и не мешались в параллель.

**Comment by orignal** [comment]
версия пол винды работает уже настолько хорошо, что мы даже бандлы с ней выпускаем :)

**Comment by r4sas** [comment]
xD
Здарова. Сервис надо будет переделывать. Что то он не правильно инсталлится.

**Comment by hypnosis-i2p** [comment]
с появлением qt гуя данная фича неактуальна, я думаю
