### ISSUE TITLE
HTTPServer Authentication silently fails open if user and pass config items are too long

### ISSUE THREAD

**Issue by klampworks** [PurpleI2P/i2pd#732]
When using Authentication on the HTTP Server component, if the combined length of the real Username and Password exceeds 48 characters, the authentication mechanism will check client supplied credentials against a predictable string instead of the real username and password.

Impact
A legitimate user will not be able to log in with the correct credentials and a malicious actor will be able to log in using no credentials at all. However, since authentication is off by default and a legitimate user is likely to notice that Authentication has stopped working this not that serious.

To reproduce

    $ ./i2pd --http.user=user --http.pass=$(perl -e "print 'a' x 44") --http.auth=true
    $ curl -H "Authorization: Basic " 127.0.0.1:7070

Full access is granted without providing a username and password.

Cause

This is the relevant code:
-------------------------------[ HTTPServer.cpp ]-------------------------------

    bool HTTPConnection::CheckAuth (const HTTPReq & req) {
      (...)
      /* method #2: 'Authorization' header sent */
      if (req.headers.count("Authorization") > 0) {
        std::string provided = req.headers.find("Authorization")->second;
        std::string expected = user + ":" + pass;
        char b64_creds[64];
        std::size_t len = 0;
        len = i2p::data::ByteStreamToBase64((unsigned char *)expected.c_str(), expected.length(), b64_creds, sizeof(b64_creds));
        b64_creds[len] = '\0';
        expected = "Basic ";
        expected += b64_creds;
        if (provided == expected)
          return true;
-------------------------------------[ EOF ]------------------------------------

----------------------------------[ Base.cpp ]----------------------------------

    size_t                                /* Number of bytes in the encoded buffer */
    ByteStreamToBase64 ( 
          const uint8_t * InBuffer,           /* Input buffer, binary data */
          size_t    InCount,              /* Number of bytes in the input buffer */ 
          char  * OutBuffer,          /* output buffer */
      size_t len         /* length of output buffer */               
    )

    {
      (...)
      n = InCount/3;
      m = InCount%3;
      if (!m)
           outCount = 4*n;
      else
           outCount = 4*(n+1);
      if (outCount > len) return 0;
-------------------------------------[ EOF ]------------------------------------

The `ByteStreamToBase64` will return `0` if the combined length of `user` and `pass` after Base64 encoding would be too big to fit inside the output buffer (`b64_creds`). Afterwards, the `CheckAuth` function will not check for failure and blindly use the empty `b64_creds` and wind up checking the user input against the string `Basic ` without the username and password.

This could be fixed by having the `ByteStreamToBase64` return `outCount` in the case that `OutBuffer` is `NULL`. This would allow the caller to allocate a correctly sized buffer. Since the calling code is C++, perhaps `std::vector<char>` could be used instead of a plain array. Per the standard, `std::vector` is allocated contiguously so taking the address of the first element will give you the `char*` required to call `ByteStreamToBase64` without modifying this function.

**Comment by majestrate** [comment]
changing the behavior of `ByteStreamToBase64` would impact a lot of other components.

(heh that's a really boneheaded bug, will fix shortly)

**Comment by klampworks** [comment]
Fair enough.

I'm glad my report was useful.
