### ISSUE TITLE
Android and QT should take list of files from filelist.mk

### ISSUE THREAD

**Issue by orignal** [PurpleI2P/i2pd#735]

**Comment by hypnosis-i2p** [comment]
Вероятно, Qt Creator не умеет с такими вещами работать. qmake переварит, а вот креатор нет

**Comment by nonlinear-chaos-order-etc-etal** [comment]
see also: https://github.com/PurpleI2P/i2pd/commit/7e0ae4c60198c78443665310db7aabedd4504646#diff-4b9861a8f6b686ab2aba51f5a437784fbb3fadb6f1a7b6e17c02de8195d99474 for bit of slightly related(?) example

**Comment by r4sas** [comment]
Qt uses libraries built by i2pd's makefile. Android can't use such thing I think, but current usage model works correctly so closing that issue for future work.
