### ISSUE TITLE
Any chances to add PPA repository?

### ISSUE THREAD

**Issue by transifex3** [PurpleI2P/i2pd#736]
For now we need to build i2pd ourselves or use deb file, but ppa would be way to more clear and simpler.

I found [KYTV's Repo](https://launchpad.net/~i2p.packages/+archive/ubuntu/i2p) and [purplei2p's Repo](https://launchpad.net/~purplei2p/+archive/ubuntu/i2pd/+packages) but seems both are just dead.

**Comment by orignal** [comment]
kytv has left I2P almost an year ago,  purplei2p's is mine, but I don't have enough skills and time to run it.
If you agree to be maintainer I can give you an access

**Comment by transifex3** [comment]
@orignal 
Unfortunately I don't know how to make and maintain PPA too. :(
I just asked as normal user, but if there are not developers that want to maintain this, i can search and learn how to make this 🔥

**Comment by orignal** [comment]
@transifex3 https://launchpad.net/~purplei2p/+archive/ubuntu/i2pd
We have it now
