### ISSUE TITLE
I2PdBrowserPortable Linux Support & L18N

### ISSUE THREAD

**Issue by transifex3** [PurpleI2P/i2pd#737]
I just have used I2PdBrowser, and found it's really handy and simple way to use i2p network 👏 
But for now, only available lang is only Russian.
Of course we can download language xpi manually for Firefox 45 ESR, and enter about:config and modify settings.. (Or just download local switcher, manually) but It's long way to go for newbies that want to use simpler one.
It would be nice to add options for selecting locale for newbies!

Oh, and if possible, linux support will be great too. Separating I2PdBrowser project from i2pd repo also makes some notable steps.

Thanks for maintaining, and developing great project guys. God bless you

**Comment by orignal** [comment]
English and Linux support can be added easily.
It just matter of target group. Simply speaking there are a lot of Russian Windows users. That's the reason.

**Comment by majestrate** [comment]
I also would like an english/linux version

**Comment by transifex3** [comment]
@orignal 
In [I2p Reddit](https://www.reddit.com/r/i2p/) many guys want to get I2p Bundle :)
I think making I2PdBrowser repository would impress many users. still they don't know I2PdBrowser existing.

@majestrate Hell yeah xD

**Comment by r4sas** [comment]
@transifex3 @majestrate, I really dont know where find Firefox portable for linux. If you have any ideas how to make it portable, please write about that.

**Comment by transifex3** [comment]
@r4sas I hope [This](https://gist.github.com/rubo77/b999c1bc6d10ab802536) or [THIS](http://unix.stackexchange.com/questions/73123/portable-firefox-linux) can be helpful for you

**Comment by r4sas** [comment]
https://github.com/PurpleI2P/i2pdbrowser/tree/master/linux
https://github.com/PurpleI2P/i2pdbrowser/releases/download/1.1.2/I2PdBrowserPortable_1.1.2-linux.tar.gz

**Comment by transifex3** [comment]
@r4sas Splendid!! Can't wait to try that XD
Thanks for your effort r4sas :)

**Comment by ChrisFernandez** [comment]
I also vote for English/Spanish/Linux version

**Comment by orignal** [comment]
new release is multilang

**Comment by r4sas** [comment]
@ChrisFernandez in windows version?

**Comment by ChrisFernandez** [comment]
@r4sas on Linux version, we do not own any windows computer.

**Comment by r4sas** [comment]
bash detects system language and downloading FF based on that info.
