### ISSUE TITLE
PPA 2.10.2-1trusty1 version crash

### ISSUE THREAD

**Issue by hypnosis-i2p** [PurpleI2P/i2pd#740]
see screenshot
![screenshot-i2pdcrash1](https://cloud.githubusercontent.com/assets/19966907/21293357/f18752de-c55c-11e6-9fbc-6797bfb78151.png)

**Comment by r4sas** [comment]
Причину уже обнаружили, далее будет исправлено.
2.10.2 загружался в качестве теста.
