### ISSUE TITLE
I2PMessenger SAM should be working

### ISSUE THREAD

**Issue by hypnosis-i2p** [PurpleI2P/i2pd#741]
```
orignal ( 21:26:17 ): 
в i2pd бага в сэме

orignal ( 21:37:28 ): 
ее надо воспроизвести

orignal ( 21:37:31 ): 
с падениями
```

**Comment by r4sas** [comment]
https://github.com/PurpleI2P/i2pd/commit/05c914156a572d2983b60863400267ccdfa6b100, https://github.com/PurpleI2P/i2pd/commit/259a63e61237b0222b4096a73e3bda8a5a4dfa8b
