### ISSUE TITLE
Win64 AES-NI build: high CPU usage

### ISSUE THREAD

**Issue by dimqua** [PurpleI2P/i2pd#744]
Заметил, что сборка i2pd_2.11.0_win64_mingw_aesni значительно (по сравнению с 32-битными билдами и версией win64 без aes-ni) нагружает процессор. Это норма?

**Comment by orignal** [comment]
нет. надо будет разбираться что там не так

**Comment by r4sas** [comment]
@dimqua процессор какой?

**Comment by dimqua** [comment]
Intel [Core i5-4310M](http://ark.intel.com/products/80373/Intel-Core-i5-4310M-Processor-3M-Cache-up-to-3_40-GHz)

**Comment by r4sas** [comment]
А значительно, это сколько в среднем?

**Comment by dimqua** [comment]
Win64-билд без aes-ni даёт нагрузку максимум в несколько процентов, а зачастую и вообще 0-1%, согласно диспетчеру задач Windows.

Для сборки с aes-ni это значение всегда было в несколько десятков, в среднем, 20-40%.

**Comment by orignal** [comment]
Так может быть и реально поток данных разные.
Это бы сравнить как то.

**Comment by arabesc** [comment]
Не [такая же](https://svnweb.freebsd.org/ports?view=revision&revision=429360), случаем, проблема?

**Comment by orignal** [comment]
@arabesc, а почему все остальные билды нормально?

**Comment by arabesc** [comment]
@orignal, остальные, это без AES-NI? Не знаю, просто факт, фряшный порт i2pd-2.11.0_1 грузил на ~ 100%, а после патча в i2pd-2.11.0_2 болтается около нуля.

**Comment by orignal** [comment]
так я фряшным то понятно в чем была проблема
с виндовыми той проблемы никогда не наблюдалось

**Comment by dimqua** [comment]
На 100% никогда не грузил, поэтому и не думал, что это проблема. Пока не попробовал поставить другой билд или предыдущую версию.

**Comment by orignal** [comment]
@dimqua на 100% имеется ввиду одно ядро, то есть на 4-х ядрах будет 25%

**Comment by dimqua** [comment]
Похоже проблема специфична для ОС, т.е. Windows 8.1. На Windows 10 v1607 всё нормально.

**Comment by majestrate** [comment]
related, get this and a 100% cpu use after a bit

    HTTP Server: error handling accept too many open files
