### ISSUE TITLE
how to move a eepsite previously hosted with vanilla i2p to i2pd

### ISSUE THREAD

**Issue by saveyour** [PurpleI2P/i2pd#745]
hello,

i'm switching from the java i2p client to this i2pd client and i'd like to also move my i2p eepsite with it. is there a way to move the key (or whatever is necessary) that the vanilla i2p client that i used to create the eepsite over to i2pd so i can continue hosting the same website? 

thanks for the help

**Comment by orignal** [comment]
Same format of .dat file/
Just  copy it to ~/.i2pd and specify it as "keys" parameter of corresponding http tunnel

**Comment by majestrate** [comment]
if you know which file java i2p uses you can copy that file into `~/.i2pd/` and add a new entry to `tunnels.conf`

i.e. let's say your private key file from java i2p is `~/.i2p/my-eepsite.dat`

copy `~/.i2p/my-eepsite.dat` to `~/.i2pd/` directory

add a new entry to `~/.i2pd/tunnels.conf` create the file if it's not there.


    [eepsite-on-i2pd]
    type=http
    host=127.0.0.1
    port=8080
    keys=my-eepsite.dat


you'll need to configure an http server like nginx or lighttpd to use port 8080, or use `python3 -m http.server --bind 127.0.0.1 8080` to serve a directory

**Comment by l-n-s** [comment]
@majestrate, I've created wiki page based on your reply: [migrating hidden services from Java](https://github.com/PurpleI2P/i2pd/wiki/Migrating-hidden-services-from-Java-I2P)

**Comment by saveyour** [comment]
thanks, this helped alot!
