### ISSUE TITLE
Domain fronting as a transport

### ISSUE THREAD

**Issue by l-n-s** [PurpleI2P/i2pd#747]
Signal messenger [implemented](https://whispersystems.org/blog/doodles-stickers-censorship/) technique called "domain fronting" for beating censorship in Egypt

> We describe “domain fronting,” a versatile censorship circumvention technique that hides the remote endpoint of a communication. Domain fronting works at the application layer, using HTTPS, to communicate with a forbidden host while appearing to communicate with some other host, permitted by the censor. The key idea is the use of different domain names at different layers of communication. One domain appears on the “outside” of an HTTPS request—in the DNS request and TLS Server Name Indication—while another domain appears on the “inside”—in the HTTP Host header, invisible to the censor under HTTPS encryption. A censor, unable to distinguish fronted and non-fronted traffic to a domain, must choose between allowing circumvention traffic and blocking the domain entirely, which results in expensive collateral damage. Domain fronting is easy to deploy and use and does not require special cooperation by network intermediaries. We identify a number of hard-to-block web services, such as content delivery networks, that support domain-fronted connections and are useful for censorship circumvention. Domain fronting, in various forms, is now a circumvention workhorse. We describe several months of deployment experience in the Tor, Lantern, and Psiphon circumvention systems, whose domain-fronting transports now connect thousands of users daily and transfer many terabytes per month. 

[Paper](https://www.bamsoftware.com/papers/fronting/)

Could I2P do something like that? Add special transport, ship i2pd with pre-installed router info's with that transport. Switch to "domain fronting" transport if NTCP/SSU fails. Is that possible?

**Comment by Barack0bama** [comment]
@l-n-s Is this referring to enabling a domain fronting technique to download the reseed file as in https://github.com/PurpleI2P/i2pd/issues/836 ?
