### ISSUE TITLE
pidfile cannot be written — a type of failure

### ISSUE THREAD

**Issue by hypnosis-i2p** [PurpleI2P/i2pd#748]
when there is no permission to write the pidfile, i2pd silently exits and doesn't report about the no-permission-error anywhere. Should not be silent and should report that the pidfile cannot be written.

maybe this was already been fixed - i use old non-updated git version

**Comment by LLE8** [comment]
Debian Jessie
i2pd version  2.11.0-1jessie1
-rw-r--r-- 1 i2pd adm 0 янв 28 00:21 i2pd.pid

But its empty!
