### ISSUE TITLE
Bandwidth limit between 256 and 2048

### ISSUE THREAD

**Issue by v2e** [PurpleI2P/i2pd#749]
Since the bandwidth limit may be set in numbers instead of the letters (L, O, P, X), it would be very good to be able to set the bandwidth limit between the 256kbps and 2048 kbps, because the difference between them is considerable.

By the way, why isn't it possible to set ANY value for this parameter?
Thanks!

**Comment by orignal** [comment]
You can set 'P' now.
'X' will be implemented soon

**Comment by v2e** [comment]
If I understand the comments in the config file correctly, 'P' actually means 2048kbps (by the way, is it kilobit or kilobyte?), and I am looking for a setting **_between_** 'O' (256kbps) and 'P' (2048). Just like I mentioned in the beginning.

**Comment by majestrate** [comment]
the bandwidth letter is put in the router info and is used by other routers as hints when building tunnels.

**Comment by r4sas** [comment]
>Oh, and by the way, 'X' seems to be implemented already. I put it in the config file, and in the log I saw a message that the bandwidth limit was set at 9999KBps.

As I know, you can set number. All values in bytes.

**Comment by l-n-s** [comment]
Looks the same as #863
