### ISSUE TITLE
Local i2pd stops proxying after a few minutes

### ISSUE THREAD

**Issue by v2e** [PurpleI2P/i2pd#769]
My local i2pd daemon works perfectly fine first several minutes (as an http proxy for browsing .i2p sites in Firefox). After that it continues working as an i2p node (showing a considerable transit traffic), but stops proxying my requests for .i2p sites.

It may be associated with the number of connections or tunnels (I don't know). But even if it is the case, why don't my proxy requests for my local daemon have higher priority? Or maybe some nonzero priority at least?

Thanks!

**Comment by orignal** [comment]
what does it mean "stops"? Connection refused? Reset? No reponse?

**Comment by majestrate** [comment]
i get this too, i suspect it's related to hitting open file limit.

**Comment by v2e** [comment]
@orignal I wish I could answer anything smart to this question...
In fact, after some minutes after start, if I try to open some .i2p site, the browser tries to connect for a very very long time, and does not succeed. And no message. So I am not sure of what kind of error it is.

**Comment by orignal** [comment]
That's another issue I need to take a look at. Looks like LeaseSet request never finishes.

**Comment by randomboygh** [comment]
Have a same issue as v2e. Infinite page loading after a few mins/hours.

**Comment by orignal** [comment]
Infinite or just longer? Wait for few minutes and see the result.

**Comment by majestrate** [comment]
it's because of hitting open file limit

**Comment by orignal** [comment]
@randomboygh @v2e have you tried ulimit -n 4096 before start?

**Comment by randomboygh** [comment]
So how to do it?
I'm using a i2pd_2.11.0_win64_mingw on win7

**Comment by orignal** [comment]
than never mind. try win32 just in case

**Comment by randomboygh** [comment]
Nothing changed :(

**Comment by orignal** [comment]
go there http://127.0.0.1:7070/?page=i2p_tunnels
Find one called "HTTP Proxy" and see what's going on.
Tunnels? LeaseSets? Number of tags?

**Comment by randomboygh** [comment]
![](http://storage7.static.itmages.ru/i/17/0113/h_1484350475_5794611_15079204c3.png)
Some site is loading about 15 minutes and doesn't load yet

**Comment by randomboygh** [comment]
So i2pd_2.11.0_win64_mingw after run 32-bit version force closes. But pre-release 64-bit ver 2.10.2 stil works.

**Comment by randomboygh** [comment]
And i2pd_2.11.0_win64_mingw_no-avx works good.

**Comment by orignal** [comment]
do you see .b32 address of your site your are connecting to among LeaseSets?
How about streaming section? Do you see that connection there?

**Comment by randomboygh** [comment]
Можно я по-русски буду, пока v2e молчит?
Да, адреса своего сайта есть и LeaseSets, и в Tags Outgoing, но я только что перезапустил i2pd, поэтому пока все работает хорошо и нужно подождать по моим наблюдениям около часа.

**Comment by orignal** [comment]
Можно разумеется :) Вот когда проблема возникнет надо посмотреть:
1. Если ли лизсет запрашиваемого адреса
2. Если есть то есть ли стрим к нему и какие там значения

**Comment by randomboygh** [comment]
Так, все снова отвалилось.
Соответственно, в LeaseSets и Streams запрашиваемые сайты присутствуют:
![](http://storage1.static.itmages.ru/i/17/0114/h_1484355974_1381588_dd66cca649.png)

**Comment by orignal** [comment]
Какой статус стримов?

**Comment by randomboygh** [comment]
А где это увидеть?

**Comment by orignal** [comment]
прокрутить правее

**Comment by randomboygh** [comment]
Да, извиняюсь, не заметил прокрутку:
![](http://storage7.static.itmages.ru/i/17/0114/h_1484357054_3853534_cefa1fb67f.png)

**Comment by orignal** [comment]
А если попробовать другим браузером? Я не вижу никаких проблем. Ощущение что браузер по какой то причине не отобразил.
curl есть? Хорошо бы им увидеть что там

**Comment by r4sas** [comment]
И что за браузер кстати?
Что если попробовать из [бандла](https://github.com/PurpleI2P/i2pdbrowser/releases/latest) запустить браузер? (чисто его, а i2pd запускаете какой вам угодно отдельно)?

**Comment by randomboygh** [comment]
Ок, сейчас проверю браузером из бандла. Сам пользуюсь Firefox 50.1.0.
Так. Это странно, но да, проблема в браузере. И сайте, на который я пытался зайти.

**Comment by r4sas** [comment]
@randomboygh кстати от 50й версии для бандла я решил отказаться лишь из-за того, что как раз там что то странное с серфингом происходит. Сейчас там используется 45.6.0ESR.

**Comment by randomboygh** [comment]
В таком случае, спасибо. 
Проблема есть, но она, как оказалось, не в i2pd.

**Comment by orignal** [comment]
Странно лишь что, что с 50-ой версией под линукс таких проблем не наблюдается

**Comment by l-n-s** [comment]
I've been experiencing same problems as @v2e, problem was with open file descriptors limit.

It's always very frustrating and not obvious how to fix. I suggest running i2pd with such script:

    #!/bin/bash
    ulimit -n 4096
    /path/to/i2pd [your options here]
