### ISSUE TITLE
Firewalled when it is not firewalled

### ISSUE THREAD

**Issue by Saeltis** [PurpleI2P/i2pd#776]
Hello, developers!

I have noticed, that after version 1.10.1 all new versions of the client display in a line of the status "**Firewalled**" whereas version 1.10.1 and previous displayed "**OK**".
Used firewall - latest version of "**Firewall Plus**" (by "PC Tools"). All ports for i2pd.exe are opened, all types of connection are resolved.

In what the reason of such behaviour of the program?

**Comment by Saeltis** [comment]
Если удобно, можно и по-русски :)

**Comment by majestrate** [comment]
local firewall rules do not guarantee external connectivity, i.e. when
behind NAT.

**Comment by ChrisFernandez** [comment]
I have notice the same behavior ....  I am in a VPS server 24/7 not in my home lan nor anyplace behind a firewall and says "firewalled" FYI.

**Comment by majestrate** [comment]
os / arch ?

**Comment by Saeltis** [comment]
My OS is Win7 x86 SP1

**Comment by ChrisFernandez** [comment]
Base OS in this particular instance is Ubuntu.

**Comment by Saeltis** [comment]
Wildly I apologise, it was version 2.10.1, and current version on my personal computer - 2.11.1

**Comment by Saeltis** [comment]
oops. 2.11.0

**Comment by majestrate** [comment]
is ntcp disabled in these cases?

**Comment by Saeltis** [comment]
In 2.10.1 - it's enabled, as I can see.
In 2.11.0 - it's disabled

**Comment by orignal** [comment]
@Saeltis because it was bug in previous version that made it malfuctioning
It shows correct status now

**Comment by orignal** [comment]
А если по русски кто то режет значит. Опсос наверное

**Comment by Saeltis** [comment]
Да, непонятно, что там с этим файрволлом. Скорее всего да, провайдер блокирует, а не мой ПК. Жаль, если так, конечно. Однако, и с этим статусом I2Pd работает на ура (особенно последние версии). Буду считать, что проблемы здесь нет, большое спасибо.

Yes, not clearly, that there with this firewall. Most likely yes, the provider blocks, instead of my personal computer. It is a pity, if so, certainly. However, and with this status I2Pd works on hurrah (especially last versions). I will consider, that the problem here is not present, many thanks.
