### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by zzydog** [PurpleI2P/i2pd#780]
1. Consider changing the definition of `SSUHeader`, then remove `SSUSession::GetSSUHeaderSize` and simplify the code. 
```
struct SSUHeader
{
	unsigned char mac[16];
	unsigned char iv[16];
	union {
		struct {
			struct {
				unsigned char reserved : 2;
				unsigned char extended : 1;
				unsigned char rekeying : 1;
				unsigned char datatype : 4;
			} flag;
			unsigned char time[4];	
			unsigned char body[0];
		} playload;
		unsigned char encrypted[0];
	};
	size_t size() const { 
		size_t rekey = 0, extend = 0;
		if (playload.flag.rekeying) { rekey = 64; }
		if (playload.flag.extended) { extend = playload.body[rekey] + 1; }
		return sizeof(SSUHeader) + rekey + extend;
	}
};
```
2. Consider changing the design of `SSUServer`, it should be divided into 3 parts(not necessary, I know):
```
class SSUServer
class SSUServerV4 : public SSUServer
class SSUServerV6 : public SSUServer
// controlled by this class or other components
class SSUManager 
```
3. Consider using `Asio`(just header files) instead of `boost.Asio`
4. About the `Queue` i2pd used, Consider using `Lock-Free Queue` instead.

**Comment by orignal** [comment]
2. Good idea. Initially it was v4 only, v6 was added later on. Same for NTCP
3. what for? 
4. It requires boost 1.53 but we still support 1.49

**Comment by zzydog** [comment]
3. `Asio` is a header-file-only library, copy these files to the project, then you can use the latest features of  `Asio` without caring the `Boost` version. `http://think-async.com/Asio`
4. Free your mind, bro. You don't have to use the whole `Boost` library, just copy what you need(`i2p::util::`←_←) and say goodbye to these compatibility issues.^_^

**Comment by orignal** [comment]
FYI, you can't pass shared_ptr through the boost's lock-free queue

**Comment by zzydog** [comment]
Oh, that's a problem.
Well, I am still learning the i2p project, How about keeping this issue open and let's discuss it later ?

**Comment by l-n-s** [comment]
Thanks for suggestions. Create separate issues for each point if it is still relevant.
