### ISSUE TITLE
андройд заменить чб иконку

### ISSUE THREAD

**Issue by hypnosis-i2p** [PurpleI2P/i2pd#784]
![logo1](https://cloud.githubusercontent.com/assets/19966907/22301671/ca1520aa-e366-11e6-969d-b116d02b269b.png)

**Comment by hypnosis-i2p** [comment]
https://developer.android.com/guide/practices/ui_guidelines/icon_design_status_bar.html
«Status bar icons are composed simply of white pixels on a transparent backdrop, with alpha blending used for smooth edges and internal texture where appropriate.»

**Comment by r4sas** [comment]
https://github.com/PurpleI2P/i2pd/commit/a840ed06b7abd8cec373dac209c6f935136941bb
