### ISSUE TITLE
pidfile is empty

### ISSUE THREAD

**Issue by LLE8** [PurpleI2P/i2pd#785]
Debian Jessie 8.7
i2pd 2.11.0-1jessie1

 cat /var/run/i2pd/i2pd.pid
*NOTHING!*

 ls -l /var/run/i2pd/i2pd.pid
-rw-r--r-- 1 i2pd adm 0 янв 28 00:21 /var/run/i2pd/i2pd.pid

 ps ax | grep i2pd
17365 ?        Ssl    0:16 /usr/sbin/i2pd --service --daemon --log=file --logfile=/var/log/i2pd/i2pd.log --conf=/etc/i2pd/i2pd.conf --tunconf=/etc/i2pd/tunnels.conf

**Comment by r4sas** [comment]
Try add `--pidfile $PIDFILE` [here](https://github.com/PurpleI2P/i2pd/blob/openssl/debian/i2pd.init#L56) before `$DAEMON_OPTS`.

**Comment by LLE8** [comment]
да, вот так 
  start-stop-daemon --start --quiet --exec $DAEMON --chuid "$USER" -- \
    --service --daemon --log=file --logfile=$LOGFILE --conf=$I2PCONF --tunconf=$TUNCONF \
    --pidfile $PIDFILE $DAEMON_OPTS > /dev/null 2>&1 \
    || return 2
заработало, в  /var/run/i2pd/i2pd.pid находится PID, совпадающий с выводом ps

**Comment by r4sas** [comment]
Хорошо, добавлю в транк.

**Comment by LLE8** [comment]
Странно то, что опция --pidfile=$PIDFILE в инит-скрипте уже была ранее, но в другом месте, и в таком варианте был баг с пустым пидфайлом. Баг исправился переносом опции ближе к концу оператора, как вы порекомендовали. Или это нормально и только я что-то не понимаю?

**Comment by r4sas** [comment]
@LLE8, дело в том, что до этого оно, по моему мнению, было сделано некорректно.
Ранее порт был, и указывался через "дополнительные" параметры (последняя переменная). Но дело в том что порт можно так сказать "был зашит" в /etc/default/i2pd и был выставлен на 4567. Из-за этого кстати были даже тёрки.

То что есть параметр --pidfile выше - это пид, указываемый для демона init.d. По нему система отслеживает состояние приложения. А вот параметр для самого приложения не передавался после изменений (если глянете в /var/lib/i2pd, увидите тот самый i2pd.pid).

**Comment by LLE8** [comment]
Насколько я помню, для каждого демона существует только один пид-файл, и он традиционно находится в /var/run или в /var/run/<name> и существует  единственная опция --pidfile в соответствующей строчке в скрипте.
Вот на свежеустановленном Jessie 
# find -L  /var -name *.pid -print
/var/run/privoxy.pid
/var/run/i2pd/i2pd.pid
/var/run/ntpd.pid
/var/run/exim4/exim.pid
/var/run/rsyslogd.pid
/var/run/acpid.pid
/var/run/sshd.pid
/var/run/atd.pid
/var/run/crond.pid
/var/run/sm-notify.pid
/var/run/rpc.statd.pid
/var/run/rpcbind.pid
/var/lib/i2pd/i2pd.pid

Подозреваю, что баг прячется где-то глубже инитскриптов, предлагаю считать решение временным и снова открыть этот баг. Может и до него дойдет очередь.

**Comment by r4sas** [comment]
@LLE8 если бы вы сейчас пересобрали бы пакет сами, то там бы этой проблемы уже не было бы. Мне кажется что вы последний релизный (2.11) взяли, или же собрали его?

**Comment by LLE8** [comment]
Да, 2.11, установил из  repo.lngserv.ru

**Comment by r4sas** [comment]
Ну тогда всё ясно. В репозитории обновление пакетов будет производиться только после релиза/пре-релиза.
Было в планах сделать ежедневную сборку i2pd-git, но это проблемнее, так как надо ежедневно подписывать, собирать и тд и тп (сборочная машина не резиновая =) ).

**Comment by LLE8** [comment]
А все-таки в  2.12.0  странная конструкция в /etc/init.d/i2pd 
```
  start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --chuid "$USER" -- \
    --service --daemon --log=file --logfile=$LOGFILE --conf=$I2PCONF --tunconf=$TUNCONF \
    --pidfile=$PIDFILE $DAEMON_OPTS > /dev/null 2>&1 \
    || return 2
```
нигде такого не встречал

**Comment by r4sas** [comment]
`start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --chuid "$USER"` - параметры для демона сервисов.
`--` - окончание его параметров.
`--service --daemon --log=file --logfile=$LOGFILE --conf=$I2PCONF --tunconf=$TUNCONF --pidfile=$PIDFILE $DAEMON_OPTS` - параметры, передаваемые запускаемому приложению

**Comment by LLE8** [comment]
это понятно по --
я по поводу двойного указания пидфайла удивляюсь, ну  работает вроде и пусть будет.

**Comment by r4sas** [comment]
В первый раз мы указываем менеджеру демонов считывать pid приложения из указанного файла
Во второй раз мы указываем i2pd куда ему писать свой pid

**Comment by LLE8** [comment]
Да, я это уже раньше понял, просто такого хитрого приема нигде вокруг не видел.
