### ISSUE TITLE
Feature request dynamic hostname 

### ISSUE THREAD

**Issue by mppdidi** [PurpleI2P/i2pd#787]
Ability to have a (dynamic) dns record as listening interface ( host setting in i2pd.conf )

**Comment by l-n-s** [comment]
If I understand correctly, you want to be able to setup "homebox.dyndns.org" as a hostname in a config file, so it will be advertised to the network, instead of dynamic IP adress?

**Comment by orignal** [comment]
doesn't "host" parameter do it? If not, we can fix it

**Comment by mppdidi** [comment]
when using using a dns name as host parameter this error occurs:

terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  Invalid argument

**Comment by l-n-s** [comment]
Feature exists. Invalid argument probably means you are doing something wrong. If issue is still relevant, update its title with more correct description and reopen it.
