### ISSUE TITLE
Too many open files   Не открываются сайты

### ISSUE THREAD

**Issue by LLE8** [PurpleI2P/i2pd#795]
Через некоторое время после старта (неслолько часов) перестает открывать сайты, в т.ч. флибусту, проверял на ней. При этом потребляет 96-99% CPU, хотя до обнаружения проблемы было около 20 %. В браузере сообщений об ошибках нет. 
Количество соединений при этом достигает 900 с чем-то.
В i2pd.log регулярно, приблизительно ежесекундно, сообщения
21:33:19@911/info - NTCP: Connect error Too many open files
При открытии веб-интерфейса в i2pd.log непрерывно
21:33:13@984/error - HTTP Server: error handling accept Too many open files
веб-интерфейс при этом работает на первый взгляд нормально.
Также время от времени 
18:07:36@487/error — Transports: Unable to resolve NTCP address: Too many open files 

В i2pd.conf установил такие параметры перед запуском
nat = false
bandwidth = 20480
notransit = false
floodfill = true

 cat /proc/sys/net/core/somaxconn
32768
 cat /proc/sys/net/ipv4/tcp_max_orphans
65536

 su -l i2pd -s /bin/bash

 cat /proc/sys/fs/file-nr
1664    0       48903

 ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 1911
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65536
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1911
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

Где и чего ей не хватает?

**Comment by orignal** [comment]
ulimit -n 4096 не хватает

**Comment by LLE8** [comment]
Где именно? Как посмотреть?
Я у себя увидел
 ulimit -n
65536

**Comment by orignal** [comment]
Нет не нужно. Где то явно еще лимитирует, причем лимит в 1024

**Comment by LLE8** [comment]
Выше я писал про Debian Jessie  8.7, в нем 65536.
Сейчас заглянул в Debian Wheezy 7.11, вот в нем ulimit -n действительно 1024, по крайней мере у меня. Но баг вылезал на Jessie.
Я правильно понимаю, что при необходимости этот параметр настраивается в /etc/default/i2pd ?

**Comment by LLE8** [comment]
> Где то явно еще лимитирует
PAM?

**Comment by LLE8** [comment]
Да, вы похоже правы, непорядок

 cat /proc/7404/cmdline
/usr/sbin/i2pd--service--daemon--log=file--logfile=/var/log/i2pd/i2pd.log--conf=/etc/i2pd/i2pd.conf--tunconf=/etc/i2pd/tunnels.conf--pidfile/var/run/i2pd/i2pd.pid

 cat /proc/7404/limits
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        0                    unlimited            bytes
Max resident set          unlimited            unlimited            bytes
Max processes             1911                 1911                 processes
Max open files            1024                 4096                 files
Max locked memory         65536                65536                bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       1911                 1911                 signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us

 ulimit -n
65536

**Comment by r4sas** [comment]
@LLE8 для этого специально переменная вынесена в /etc/defaults/i2pd - раскоментируйте её там.

**Comment by LLE8** [comment]
@r4sas   Да, уже заметил раньше. Написал 8192, запустил.
При этом оставил на всякий случай 
/proc/sys/net/core/somaxconn   32768
/proc/sys/net/ipv4/tcp_max_orphans   32768
Полсуток полет нормальный, флибуста открывается, netstat показывает около 1500 соединений, проц занят процентов на 20, iftop показывает 3-4 мбит/с.

**Comment by r4sas** [comment]
4096 хватает для обычного роутера с транзитом. 8192 желателен в случае транзит+флудфил

**Comment by LLE8** [comment]
на данный момент с момента запуска прошло более 40 часов. Сообщений "too many open files" не наблюдается, сайты открываются. Самая популярная ошибка в логе - 
"18:10:12@327/error - Transports: No NTCP or SSU addresses available"
Думаю, можно закрывать.
