### ISSUE TITLE
Windows 32-bit aesni build crashes

### ISSUE THREAD

**Issue by vaik228** [PurpleI2P/i2pd#800]
валится 32-битная сборка под вену с aesni.
валится тихонько...
та же сборка, но без aesni не валится.
проц как будто бы в полной мере aesni поддерживает - это атом x5-z8300
это беда началась недавно, с полгода где-то. до того сборки с aes-ni работали.
не знаю какую еще инфу приложить, я не знаю совершенно как тут в венде дебажить и отлаживать..

**Comment by orignal** [comment]
а зачем нужно именно с aesni ?

**Comment by r4sas** [comment]
@vaik228 ось? Как понять "валится"?
Падает SuccessRate? Выпадает с эксепшеном или что то еще?
Синхронизируется ли время на системе?
Лучше писать логи (log = file && loglevel = debug)

**Comment by vaik228** [comment]
> зачем нужно именно с aesni?
ну так вроде бы быстрее. или я что-то не так понимаю?)
> как понять "валится".
в общем-то не валится, да. то есть сообщения об ошибке нет. но и не запускается, то есть иконки в трее не появляется.
ОС - вин10 32бит.
никаких логов от i2pd я не нашел, потому и пишу - валится.
а что бы логи писались, это параметр командной строки задать? попробую...

**Comment by orignal** [comment]
оно быстрее только на сильно большом потоке.  на домашнем компе с небольшой нагузкой разницы почти нет

**Comment by r4sas** [comment]
>никаких логов от i2pd я не нашел, потому и пишу - валится.
>а что бы логи писались, это параметр командной строки задать? попробую...

Все файлы располагаются в %APPDATA%/i2pd/
В эту папку надо положить [конфиг](https://github.com/PurpleI2P/i2pd/blob/openssl/docs/i2pd.conf), [конфиг туннелей](https://github.com/PurpleI2P/i2pd/blob/openssl/docs/tunnels.conf), и [сертификаты](https://github.com/PurpleI2P/i2pd/tree/openssl/contrib) (папка certificates с подпапками).

**Comment by vaik228** [comment]
о!
дело было в avx, а не в aes-ni.
в предыдущих релизах, как я понимаю, вы выкладывали только версию avx+aesni. а сегодня вот в релизе 2.12.0 я увидел что вы расширили сборки, теперь есть aesni, avx и avx_aesni.
в общем версия aesni нормально запустилась.
спасибо!

**Comment by vaik228** [comment]
странно. писал пост, а его нет...
в общем из нового релиза сборка с aesni запустилась. я уже было обрадовался, предположил что предыдущие не запускались потому как вы по-видимому не разделяли раньше сборки на aesni и aesni+avx, а в новом релизе начали разделять.. и чистая AES запустилась...
короче говоря запустилась и опять молча отвалилась.
в логе ничего "такого", кроме в самом начале 
---------------------------------------------
11:49:54@367/error - RouterInfo: Can't open file 
---------------------------------------------
хотя этот файл (router.info) есть.
а дальше вроде бы как все норм:
---------------------------------------------
11:50:17@367/info - UPnP: starting
11:50:19@367/info - Daemon: starting Transports
11:50:19@367/info - NTCP: Start listening TCP port 10981
11:50:19@367/info - Transports: Start listening UDP port 10981
11:50:19@367/info - Daemon: Transports started
11:50:19@43/debug - SSU: Creating new session to [98gl] 31.15.217.88:27821
11:50:19@367/info - Daemon: starting HTTP Server at 127.0.0.1:7070
11:50:19@367/info - Daemon: starting Tunnels
11:50:19@367/info - Daemon: starting Client
11:50:19@392/debug - UPnP: ExternalIPAddress is х.х.х.х
11:50:19@392/debug - UPnP: Port Mapping successful. (192.168.1.2:10981 type UDP -> х.х.х.х:10981)
11:50:19@392/debug - UPnP: Port Mapping successful. (192.168.1.2:10981 type TCP -> х.х.х.х:10981)
---------------------------------------------
и тупо молча валится...

> оно быстрее только на сильно большом потоке. на домашнем компе с небольшой нагузкой разницы почти нет
все же хотелось бы по максимуму утилизировать возможности и без того весьма дохлого процессора))

**Comment by orignal** [comment]
Тупо валится скорее всего потому что недопустимая инструкция процессора. Видимо поддерживает как то не так или не полностью.

**Comment by l-n-s** [comment]
Any updates? Should we close it?
