### ISSUE TITLE
CMake warnings about unused parameters

### ISSUE THREAD

**Issue by mppdidi** [PurpleI2P/i2pd#802]
got a warning during compilation:

`/home/i2pd/i2pd/LeaseSet.cpp:176:60: warning: unused parameter ‘l’ [-Wunused-parameter]
     return GetNonExpiredLeasesExcluding( [] (const Lease & l) -> bool { return false; }, withThreshold);
`

**Comment by mppdidi** [comment]
actually there are more warnings about unused parameters - is it worth posting them or is this a known issue ?

**Comment by Markovskij** [comment]
Yes:
http://pastebin.com/8wWe4Af7

**Comment by r4sas** [comment]
https://github.com/PurpleI2P/i2pd/commit/100f3380c4dfb1e89da3305e3753f6937a292116
