### ISSUE TITLE
Number of network connections greatly exceeds max number of transit tunnels

### ISSUE THREAD

**Issue by LLE8** [PurpleI2P/i2pd#804]
За 5-6 суток непрерывной работы набралось около 4000 активных соединений, несмотря на то, что значение 2500 по умолчанию не менял. Так и должно быть?  Баг или не баг?
В ulimit -n 8192  пока не уперлось, работает.
В iftop видно 8-9 Мбит/с
i2pd ver 2.11.0-1jessie1 amd64

 netstat  -nap |  grep i2pd | grep ESTABLISHED  | wc -l
4091

В i2pd.conf сейчас такое

```
## Should we assume we are behind NAT? (false only in MeshNet)
# nat = true
nat = false

## Bandwidth configuration
## L limit bandwidth to 32Kbs/sec, O - to 256Kbs/sec, P - to 2048Kbs/sec,
## X - unlimited
## Default is X for floodfill, L for regular node
# bandwidth = L
bandwidth = 20480

## Router will not accept transit tunnels at startup
# notransit = true
notransit = false

## Router will be floodfill
# floodfill = true
floodfill = true

[limits]
## Maximum active transit sessions (default:2500)
# transittunnels = 2500
```

**Comment by l-n-s** [comment]
> transittunnels = 2500

Это лимит транзитных туннелей (когда через тебя транзитный траффик ходит), а не лимит сетевых соединений вообще.

>nat = false

Зачем? Эта опция актуальна только в локальных и Mesh сетях.

**Comment by LLE8** [comment]
Да, возможно я неправильно понимаю. Кроме туннелей что еще дает большое количество соединений? И 1 туннель - это 2 соединения, т.е. вход и выход?

**Comment by orignal** [comment]
один тоннель может давать много сеодинений если явлеется концом тоннеля

**Comment by l-n-s** [comment]
Туннели это такие абстракции в I2P, их количество напрямую не связано с кол-вом активных соединений. И туннели разные бывают - зондирующие, клиентские. серверные, транзитные.

Это абсолютно нормально, что флудфил много создает соединений.

**Comment by orignal** [comment]
флудфил вообще к тоннелям не имеет отношения

**Comment by LLE8** [comment]
@l-n-s 
> nat = false
> Зачем? Эта опция актуальна только в локальных и Mesh сетях.

Пожалуйста, ткните пальцем, в чем отличие VDS с белым IP со всеми 64К (или большинством) открытыми TCP/UDP портами от машинки в mesh-сети. Конкретно в нашем случае. Общее понятие о mesh-сетях вроде бы имею.

**Comment by l-n-s** [comment]
@LLE8 В таком случае, разницы не должно быть. Закрываем issue?

**Comment by LLE8** [comment]
Количество одновременно установленных сетевых соединений превысило 6300.
При этом количество одновременно открытых файлов около 7000.
Понемногу продолжают расти. И это при том, что IPv6 сейчас отключен.
iftop говорит о 7-8 Мбит/с в сумме.
Занято около 256 МБ ОЗУ и 25-30 % такого одноядерного процессора
vendor_id       : GenuineIntel
cpu family      : 6
model           : 13
model name      : QEMU Virtual CPU version 2.5+
stepping        : 3
microcode       : 0x1
cpu MHz         : 2099.996
cache size      : 4096 KB

Предлагаю прямо сейчас не закрывать, немного подождать до достижения лимита открытых файлов 8192 или падения.

**Comment by orignal** [comment]
>QEMU Virtual CPU version 2.5+
Это еще что такое?

**Comment by LLE8** [comment]
Вот такое https://itldc.com/vds/
512MB  3.5 евро

**Comment by LLE8** [comment]
```
# netstat -nap | grep i2pd | wc -l
7459
# cat /proc/sys/fs/file-nr
8032    0       48903
```
количество транзитных туннелей 1580-1600
флибуста открывается через раз

**Comment by r4sas** [comment]
а здесь: http://127.0.0.1:7070/?page=transports - сколько в сумме?

**Comment by LLE8** [comment]
NTCP 18885
SSU 1265

**Comment by LLE8** [comment]
Его убил ООМ-killer
Неожиданно
В /var/log/messages 
watch invoked oom-killer: gfp_mask=0x2000d0, order=2, oom_score_adj=0
(watch был запущен в соседнем окошке)
Незадолго до смерти i2pd занял около 65% ОЗУ и открыл приблизительно 7800 файлов, проц был занят процентов на 30.

**Comment by r4sas** [comment]
> NTCP+SSU. Правильно понимаю?
Это я просто взял со страницы той значения, которые указаны прямо там:
NTCP (число) и SSU (число)

**Comment by LLE8** [comment]
у меня не указано
![default](https://cloud.githubusercontent.com/assets/25343511/23096873/ecc6deb2-f636-11e6-9b99-09e922aca64d.png)

**Comment by LLE8** [comment]
Установлю 2.12, добавлю ipv6, продолжу наблюдать

**Comment by LLE8** [comment]
В 2.12 уже написано, предыдущий скриншот был с 2.11
NTCP  1262,   SSU  528
А вот SSU6 ничего не написано, но в списке штук 20 перечислено
Про NTCP6 вообще ни слова 
uptime 4 дня 3 часа
Транзитных туннелей 780-820
Сетевых соединений около 2000-2200

**Comment by LLE8** [comment]
Версия 2.11 непрерывно проработала 21 день 6 часов.  Вероятно была запущена еще до выхода 2.12.   
В /etc/default/i2pd  написано ulimit -n 8192
При попытке открыть сайт в i2p в логе появляются записи  NTCP: Connect error Too many open files, 
при этом i2pd сайты уже не открываются.
команда  ls -l   /proc/16848/fd/  | wc -l   дает от 8048 до 8193
# netstat -nap | grep i2pd | wc -l
8107
ОЗУ около 400M
Iftop говорит о 3 MB/c (примерно 1.5+1.5)
CPU (реальный E6750  @ 2.66GHz) около 20%

**Comment by LLE8** [comment]
Версия 2.12 
Debian Jessie 64 bit

ipv4 = true
ipv6 = true
ifname4 = eth0
ifname6 = eth0
nat = false
bandwidth = 20480
notransit = false
floodfill = true


ulimit -n 8192
uptime 33 суток с минутами


top говорит
VIRT    RES    SHR 
786280  91292   1676

http://127.0.0.1:7070/?page=transports
NTCP  230,   SSU  1380

Транзитных туннелей 344

~# ls -l /proc/29819/fdinfo/ | wc -l
8193

# netstat -nap | grep i2pd | wc -l
8160
из них tcp6 3382, tcp4  4778

В логе   множество  NTCP: Connect error Too many open files
Проц занят на 95-98 % 

Думаю, ulimit -n 8192 маловато может быть

**Comment by LLE8** [comment]
prlimit    --pid=29819  --nofile=16384
улучшило ситуацию

**Comment by orignal** [comment]
У меня сейчас точно такая же впс так что поглядим.

**Comment by LLE8** [comment]
uptime 33 дня наблюдается здесь
https://itldc.com/vds/   KVM VDS512  €3,5/ месяц
подключено 1 шт ipv4 и 1 шт ipv6

**Comment by LLE8** [comment]
uptime 34 суток 21 час 31 минута
~# ls -l /proc/29819/fdinfo/ | wc -l
9591

**Comment by LLE8** [comment]
2.12,  64 bit
uptime 40 дней
~# netstat -nap | grep EST | grep i2pd | wc -l
11325
~# netstat -nap | grep EST | grep i2pd | grep tcp6 |  wc -l
4888
~# netstat -nap | grep EST | grep i2pd | grep -v tcp6 |  wc -l
6407
~# ls -l /proc/29819/fdinfo/ | wc -l
11198
Памяти съедено 110 МБ
Туннели клиентские 35, транзитные 615, ntcp 970, ssu 1379 
Флибуста открывается.
Дальше интересно наблюдать? Или убить эту 2.12?

**Comment by orignal** [comment]
думаю стоит продолжить

**Comment by LLE8** [comment]
Продолжаю
uptime 47 дней 22 часа 45 мин
Туннели клиентские 37, транзитные 550
NTCP  1107, вперемешку ipv4 и ipv6,  SSU  1423, SSU6 около 50 
~# netstat -nap | grep EST | grep i2pd | wc -l
13258
~# netstat -nap | grep EST | grep i2pd | grep tcp6 | wc -l
6418
~# netstat -nap | grep EST | grep i2pd | grep "tcp " | wc -l
6855
~# ls -l /proc/29819/fdinfo/ | wc -l
13350

**Comment by LLE8** [comment]
~# ls -l /proc/29819/fdinfo/ | wc -l
14062

**Comment by LLE8** [comment]
uptime 53 дня 4 часа 15 минут
~# ls -l /proc/29819/fdinfo/ | wc -l
15205
Туннели кл 29, тр 642
NTCP 1310, SSU 1546, SSU6 на вид около 60.
Отожрало  118436 КБ ОЗУ.
Флибуста открывается.
Ждем достижения лимита открытых файлов 16384 и характерных проблем или сразу увеличить его до 20000 например?

**Comment by orignal** [comment]
подождем пока не перестанет работать как надо

**Comment by LLE8** [comment]
Нет смысла. Мы такое уже видели 8192 файла назад :)
https://github.com/PurpleI2P/i2pd/issues/804#issuecomment-289223451
Начнет писать в лог "too many open files", жрать проц, не будет открывать сайты.
В тот раз помогло   prlimit --pid=29819 --nofile=16384
Сделаю  prlimit --pid=29819 --nofile=20000 и подожду еще.

**Comment by LLE8** [comment]
Переползло за предыдущее ограничение 16384
~# ls -l /proc/29819/fdinfo/ | wc -l
16472
Если правильно понимаю, сожрало треть общесистемного лимита по умолчанию
~# cat /proc/sys/fs/file-max
48903
top
  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
29819 i2pd      20   0  786652 122048   1760 S 13.2 24.1  16628:03 i2pd
Флибуста открывается
Туннели кл 31, тр 735

**Comment by LLE8** [comment]
Продолжает расти, но не монотонно, а пилообразным образом
~# ls -l /proc/29819/fdinfo/ | wc -l
16602

**Comment by khumarahn** [comment]
У меня была куча дескрипторов на 2.12 тоже. Сейчас на 2.13:
```
# ls -al /proc/$(pidof i2pd)/fdinfo | wc -l
303
```
```
Uptime: 8 days, 11 min, 24 seconds
Network status: OK
Tunnel creation success rate: 27%
Received: 13.86 GiB (19.02 KiB/s)
Sent: 18.15 GiB (25.26 KiB/s)
Data path: /var/lib/i2pd
Hidden content. Press on text to see.
Routers: 2309 Floodfills: 1153 LeaseSets: 85
Client Tunnels: 33 Transit Tunnels: 138
```

**Comment by LLE8** [comment]
А в конфиге что? См. первое сообшение.

**Comment by khumarahn** [comment]
@LLE8 
```
bandwidth = X
floodfill = true
```
полный конфиг: https://pastebin.com/iDDUY5Zj

**Comment by LLE8** [comment]
а мой вариант, тот, который наверху, можете попробовать?

**Comment by khumarahn** [comment]
ок, скопировал ваш вариант, перезапустил

**Comment by khumarahn** [comment]
после 10 часов работы: порядка 600 открытых дескрипторов.

вот график, количество дескрипторов измеряется каждые 15 секунд где-то с середины февраля, с рестартами, сменами версий и, возможно, перерывами
![i](https://cloud.githubusercontent.com/assets/5206045/25177038/4879d1f2-24f8-11e7-8640-2ae08085d530.png)

**Comment by LLE8** [comment]
горизонтальная ось в каких единицах?
правый хвостик - это 2.13?

**Comment by LLE8** [comment]
И забыл добавить, что в обсуждаемом конфиге еще
ipv6 = true
ifname4 = eth0
ifname6 = eth0

**Comment by khumarahn** [comment]
горизонтальная ось - просто номер точки, точки каждые 15 секунд. Правый хвостик - да, 2.13. Самый конец хвостика - последние 10 часов с вашим конфигом.

P.S.: ipv6 у меня нет

**Comment by LLE8** [comment]
Uptime 59 дней 21 час
~# ls -l /proc/29819/fdinfo/ | wc -l
17044
Туннели кл 32, тр 591
ОЗУ 124992 КБ
Есть смысл продолжать это созерцание 2.12?
Или убить и запустить 2.13 на этом же месте с этим же конфигом?

**Comment by LLE8** [comment]
```
~# ss -s
Total: 16964 (kernel 17007)
TCP:   16976 (estab 16866, closed 24, orphaned 70, synrecv 0, timewait 24/0), ports 1562

Transport Total     IP        IPv6
*         17007     -         -
RAW       0         0         0
UDP       17        9         8
TCP       16952     8225      8727
INET      16969     8234      8735
FRAG      0         0         0
```

**Comment by LLE8** [comment]
Достигло ограничения 20000 открытых файлов и перестало работать как надо, что и ожидалось.
Картина та же: процессор занят на 96% и больше, to many open files в логе, флибуста не открывается.
На самом деле сайты перестали открываться чуть раньше.

**Comment by LLE8** [comment]
Можно убивать 2.12, чтобы не мучился?

**Comment by orignal** [comment]
да

**Comment by LLE8** [comment]
Кстати, на этот раз ему не помогло    prlimit --pid=29819 --nofile=24000 , просто из любопытства сделал.
Ни флибуста, ни zzz не открываются все равно, Видимо где-то что-то еще сломалось кроме достижения предела в 20000 открытых файлов. Это согласуется с тем, что сайты перестали открываться несколько ранее достижения 20000. Но думаю, сейчас на этом 2.12 это искать бесполезно.
```
~# cat /proc/29819/limits
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        unlimited            unlimited            bytes
Max resident set          unlimited            unlimited            bytes
Max processes             1911                 1911                 processes
Max open files            24000                24000                files
Max locked memory         65536                65536                bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       1911                 1911                 signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us
```

**Comment by LLE8** [comment]
2.13 там же, uptime 5 дней 17 часов
Туннели 36 и 722
NTCP 1365,  SSU 466
Флибуста открывается.
```
~# ls -l /proc/1972/fdinfo/ | wc -l
1420

~# ss -s
Total: 1430 (kernel 1443)
TCP:   1407 (estab 1328, closed 41, orphaned 18, synrecv 0, timewait 41/0), ports 665

Transport Total     IP        IPv6
*         1443      -         -
RAW       0         0         0
UDP       17        9         8
TCP       1366      1028      338
INET      1383      1037      346
FRAG      0         0         0
```
Продолжаю наблюдать.

**Comment by LLE8** [comment]
2.13
Uptime 11 дней 18 часов
Туннели: 33 и 860
NTCP 1176, SSU 627
```
~# ls -l /proc/1972/fdinfo/ | wc -l
1560
~# ss -s
Total: 1489 (kernel 1515)
TCP:   1482 (estab 1391, closed 44, orphaned 30, synrecv 0, timewait 44/0), ports 640

Transport Total     IP        IPv6
*         1515      -         -
RAW       0         0         0
UDP       17        9         8
TCP       1438      1028      410
INET      1455      1037      418
FRAG      0         0         0
```
Флибуста открывается, ОЗУ 34 МБ

Думаю, пора закрывать этот баг.

**Comment by orignal** [comment]
Действительно можно закрывать
