### ISSUE TITLE
Windows GUI: traffic counter error

### ISSUE THREAD

**Issue by f242** [PurpleI2P/i2pd#807]
Гигабайтов многовато за 1 день, должен быть 1гб и сколько-то мегабайт
![i2pd](https://cloud.githubusercontent.com/assets/10371194/23015386/a4d5e2aa-f443-11e6-9205-508af99c36b4.png)

**Comment by r4sas** [comment]
Воу... :D
Весьма забавный баг =)
Когда за гиг перевалит, посмотрите, всё ли нормально будет показывать.

**Comment by f242** [comment]
нашёл более ранний скрин, это всё та же запущенная версия i2pd
windows 10 x64 и i2pd_2.12.0_win64_mingw_avx_aesni
![2017-02-14 14_58_13-operating system market share](https://cloud.githubusercontent.com/assets/10371194/23020731/80c0c9f0-f459-11e6-90c0-dd665e60a1c0.png)

**Comment by l-n-s** [comment]
@r4sas  s/Recvieved/Received

**Comment by r4sas** [comment]
@l-n-s thx :D

**Comment by r4sas** [comment]
@f242 я в данный момент примерно на тех же количествах переданных данных, но такой проблемы не наблюдаю.
Если у вас оно до сих пор показывает так же, проверьте какое количество показывается в вебконсоли (http://127.0.0.1:7070)

**Comment by f242** [comment]
@r4sas вот так сейчас
![2017-02-16 16_32_43-purple i2p 2 12 0 webconsole - waterfox](https://cloud.githubusercontent.com/assets/10371194/23023237/9d64e49a-f465-11e6-9859-8f3d028ac51d.png)

**Comment by r4sas** [comment]
fix - https://github.com/PurpleI2P/i2pd/commit/16fa10b056f8590673e5c6ec0ee8ee6505fb08a0

**Comment by r4sas** [comment]
Перезалил виндовые в релизе.
