### ISSUE TITLE
I2pd daemon randomly listen or does not listen on the IPv6 and IPv4 interfaces

### ISSUE THREAD

**Issue by LLE8** [PurpleI2P/i2pd#811]
В i2pd.conf
```
ipv6 = true
# ifname = 
```
На eth0 сконфигурированы белые 1 шт IPv4 и 1 шт IPv6, оба доступны снаружи.
Других интерфейсов нет, кроме lo.
При этом в выводе netstat отсутствует занятый демоном i2pd tcp6-порт в состоянии LISTEN.
Сетевые соединения по ipv6 устанавливаются в небольшом количестве, т.е. ipv6 в принципе работает.
Если явно указать ifname = eth0, tcp6-порт, занятый i2pd, в состоянии LISTEN появляется.
Раздельное указание ifname4=eth0  ifname6=eth0 тоже работает.
Версия 2.12

Дополнение
Есть подозрение, что это проявляется только при запуске командой systemctl start i2pd.service.
Если запускать /etc/init.d/i2pd start, то похоже все нормально.
Debian Jessie

**Comment by l-n-s** [comment]
Проблема с systemd сервисом что ли?

**Comment by LLE8** [comment]
Много воды с тех пор утекло. При случае проверю на Stretch c 2.15.
Вероятно дело не или не только в systemd, с ipv6 вообще все странно https://github.com/PurpleI2P/i2pd/issues/851

**Comment by r4sas** [comment]
@LLE8 ping

**Comment by LLE8** [comment]
Посмотрю на это еще раз, как время будет.

**Comment by LLE8** [comment]
Такое впечатление, что эффект проявляется через раз, В netstat IPv6
`tcp6       0      0 :::16755                :::*                    LISTEN      22172/i2pd`
то есть, то нет.
При этом IPv4 
`tcp        0      0 0.0.0.0:16755           0.0.0.0:*               LISTEN      22172/i2pd`
есть всегда.
Причем неважно как запускать, `systemctl start i2pd.service` или `/etc/init.d/i2pd start`.

i2pd 2.18.0, Debian Jessie 64bit

Кстати, сегфолтится при завершении. Это тот же старый недобитый баг с SSU? Backtrace не нужен?

**Comment by LLE8** [comment]
i2pd 560ebcec8d51a193eedec8000a19c4aaf98e0ab0 
VDS с  /64 ipv6
запуск с ipv6=true, до этого работало с ipv6=false
```
root@srv1:/etc/i2pd# netstat  -napt6 | grep LIST
tcp6       0      0 :::22                   :::*                    LISTEN      401/sshd
tcp6       0      0 ::1:25                  :::*                    LISTEN      645/exim4
```

**Comment by orignal** [comment]
Возможно я накосячил. Посмотрю

**Comment by LLE8** [comment]
Предположение @r4sas https://github.com/PurpleI2P/i2pd/issues/851#issuecomment-466665724 о соединениях, которые остаются после остановки, не подтверждается

**Comment by LLE8** [comment]
LISTEN-порты на tcp4 и tcp6 разные, это нормально?
```
root@debian:~# netstat -napt | grep LIST
tcp        0      0 127.0.0.1:7656          0.0.0.0:*               LISTEN      17371/i2pd
tcp        0      0 127.0.0.1:6668          0.0.0.0:*               LISTEN      17371/i2pd
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      540/sshd
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      804/exim4
tcp        0      0 127.0.0.1:4444          0.0.0.0:*               LISTEN      17371/i2pd
tcp        0      0 0.0.0.0:15613           0.0.0.0:*               LISTEN      17371/i2pd
tcp        0      0 127.0.0.1:7070          0.0.0.0:*               LISTEN      17371/i2pd
tcp        0      0 127.0.0.1:4447          0.0.0.0:*               LISTEN      17371/i2pd
tcp6       0      0 :::29162                :::*                    LISTEN      17371/i2pd
tcp6       0      0 :::22                   :::*                    LISTEN      540/sshd
tcp6       0      0 ::1:25                  :::*                    LISTEN      804/exim4
```

**Comment by r4sas** [comment]
Если порт фактически не указан - то норма.

**Comment by LLE8** [comment]
Странное поведение ipv6 воспроизводится.
Нужен VDS с реальным IPv6 без следов работы i2pd (можно сделать apt-get purge i2pd или взять новый VDS с посуточной оплатой). У меня Debian Stretch 64 bit
В мсходниках в contrib/i2pd.conf установить такие значения у меня так получилось, (возможно могут быть и другие): 
```
loglevel = debug
logclftime = true
ipv6 = false
# ifname в соответствии с имеющимся vds, бывают разные варианты
ifname = eth0
nat = false
bandwidth = X
notransit = false
floodfill = false
```
Собрать пакет по инструкции как обычно debuild --no-tgz-check -us -uc -b
Установить полученный пакет, убедиться в том, что демон автоматически запустился, дождаться инициализации, заглядывая в вывод netstat. В web-интерфейсе отдать команду «Start graceful shutdown», дождаться полного закрытия всех открытых i2pd соединений, обычно около 2 минут, заглядывая в вывод netstat.
В /etc/i2pd/i2pd.conf установить ipv6 = true. Запустить i2pd systemctl start i2pd, дождаться инициализации, заглядывая в вывод netstat. В выводе netctat –napt обратить внимание на отсутствие связанного с i2pd tcp6-сокета в состоянии Listen и наличие такого Listen tcp4-сокета.
После 1-2 перезапусков Listen tcp6-сокет появляется.

**Comment by r4sas** [comment]
> После 1-2 перезапусков Listen tcp6-сокет появляется, порт обычно не совпадает с tcp4.

Мне кажется это как раз из-за router.info, я расказывал о примрно таком же @orignal -у.

> В процессе заметил, что https://itoopie.atomike.ninja/ не работает, ошибка 403.

Это возможно потому что он не принимает HTTP/1.1

**Comment by LLE8** [comment]
Описанный выше опыт можно продолжить. 
Остановить i2pd (systemctl stop i2pd). Запретить в конфиге IPv6. Для чистоты эксперимента можно дождаться полного закрытия всех соединений в состоянии TIME_WAIT, оставшихся от i2pd. Запустить i2pd. 
Через некоторое время остановить i2pd (systemctl stop i2pd). Разрешить в конфиге IPv6. Для чистоты эксперимента можно дождаться полного закрытия всех соединений в состоянии TIME_WAIT, оставшихся от i2pd. Запустить i2pd.  Снова обратить внимание на отсутствие связанного с i2pd tcp6-сокета в состоянии Listen. 
Презапустить i2pd 1-2 раза при помощи systemctl, не меняя конфиг, при этом можно не дожидаться закрытия соединений в состоянии TIME_WAIT. Обратить внимание на неожиданное появление tcp6-сокета в состоянии Listen.  В процессе эксперимента обратить внимание, что LISTEN tcp4-сокет появляется всегда, даже если не делать паузу при перезапусках для закрытия соединений.

**Comment by LLE8** [comment]
Думаю, что этот баг не minor, и вероятно не packaging.

при последовательных перезапусках демона (systemd stop i2pd, systemd start i2pd или systemd restart i2pd) tcp6-сокет в состоянии LISTEN может пропасть, а потом может появиться.  При этом tcp4-сокет появляется всегда.

**Comment by LLE8** [comment]
2.31, Buster 64 bit.
Не воспроизводится. При ipv4=true и ipv6=true tcp6-сокет в состоянии LISTEN появляется всегда.
Зато при этих же усвиях всегда НЕ появляется  tcp4-сокет в состоянии LISTEN, чего ранее не наблюдалось. 
inet6 2a0a:xxxx:yyyy:zzzz::1  prefixlen 48  scopeid 0x0<global>
Можно закрывать этот баг и открывать новый?

**Comment by r4sas** [comment]
эм... странное поведение...
надо бы глянуть чего в логе пишет, сейчас отлова событий достаточно.

**Comment by LLE8** [comment]
Уточнение. Не "всегда НЕ появляется tcp4-сокет в состоянии LISTEN", а псевдослучайным образом появляется или не появляется. В общем ipv4 и ipv6 в контексте этого бага поменялись ролями.

**Comment by LLE8** [comment]
loglevel = debug
ipv4 = true
ipv6 = true

i2pd.log
```
[21/May/2020:19:02:24 +0000]@948/info - Log: min messages level set to debug
[21/May/2020:19:02:24 +0000]@948/info - Log: will send messages to /var/log/i2pd/i2pd.log
[21/May/2020:19:02:24 +0000]@948/info - i2pd v2.31.0 starting
[21/May/2020:19:02:24 +0000]@948/debug - FS: main config file: /etc/i2pd/i2pd.conf
[21/May/2020:19:02:24 +0000]@948/debug - FS: data directory: /var/lib/i2pd
[21/May/2020:19:02:24 +0000]@948/info - Daemon: bandwidth set to 1000000KBps
[21/May/2020:19:02:24 +0000]@948/info - Daemon: using system limit in 4096 max open files
[21/May/2020:19:02:24 +0000]@948/info - Daemon: starting NetDB
[21/May/2020:19:02:24 +0000]@948/info - Family: 5 certificates loaded
[21/May/2020:19:02:24 +0000]@948/info - NetDb: 77 routers loaded (35 floodfils)
[21/May/2020:19:02:24 +0000]@948/info - Daemon: starting Transports
[21/May/2020:19:02:24 +0000]@948/info - Daemon: ntcp disabled
[21/May/2020:19:02:24 +0000]@948/error - NTCP2: NOTUSING PROXY
[21/May/2020:19:02:24 +0000]@948/info - NTCP2: Start listening V6 TCP port 16327
[21/May/2020:19:02:24 +0000]@948/info - Transports: Start listening UDP port 16327
[21/May/2020:19:02:24 +0000]@948/info - Daemon: Transports started
[21/May/2020:19:02:24 +0000]@948/info - Daemon: starting HTTP Server at 127.0.0.1:7070
[21/May/2020:19:02:24 +0000]@948/info - Daemon: starting Tunnels
[21/May/2020:19:02:24 +0000]@948/info - Daemon: starting Client
[21/May/2020:19:02:24 +0000]@185/debug - SSU: Creating new session to [rKZb] 2a01:xxxxxxxxxxxxxxxxxxxxxx
[21/May/2020:19:02:24 +0000]@185/debug - SSU: Creating new session to [~9XE] 2003:xxxxxxxxxxxxxxxxxxxxxx
[21/May/2020:19:02:24 +0000]@185/debug - SSU: Creating new session to [yRxx] 2001:xxxxxxxxxxxxxxxxxxxxxx
[21/May/2020:19:02:24 +0000]@948/warn - Addressbook: Can't open /var/lib/i2pd/addressbook/addresses.csv
[21/May/2020:19:02:24 +0000]@948/error - Addressbook: resetting eTags
[21/May/2020:19:02:24 +0000]@948/info - Addressbook: 3 subscriptions urls loaded
[21/May/2020:19:02:24 +0000]@948/warn - Addressbook: subscriptions.txt usage is deprecated, use config file instead
[21/May/2020:19:02:24 +0000]@948/info - Clients: starting HTTP Proxy at 127.0.0.1:4444
[21/May/2020:19:02:24 +0000]@948/info - Clients: starting SOCKS Proxy at 127.0.0.1:4447
[21/May/2020:19:02:24 +0000]@948/debug - Clients: tunnels config file: /etc/i2pd/tunnels.conf
[21/May/2020:19:02:24 +0000]@948/info - Clients: Local address xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.b32.i2p loaded
[21/May/2020:19:02:24 +0000]@948/info - Destination: parameters for tunnel set to: 5 inbound (3 hops), 5 outbound (3 hops), 40 tags
[21/May/2020:19:02:24 +0000]@948/error - Addressbook: Can't find domain for irc.postman.i2p
[21/May/2020:19:02:24 +0000]@948/warn - I2PTunnel: Remote destination irc.postman.i2p not found
[21/May/2020:19:02:24 +0000]@948/debug - Clients: tunnels extra config file: /etc/i2pd/tunnels.conf.d/README
[21/May/2020:19:02:24 +0000]@948/info - Clients: 1 I2P client tunnels created
[21/May/2020:19:02:24 +0000]@948/info - Clients: 0 I2P server tunnels created
[21/May/2020:19:02:24 +0000]@948/info - Clients: starting SAM bridge at 127.0.0.1:7656
```

**Comment by LLE8** [comment]
получилось даже такое при ipv4 = true и ipv6 = false
```
# netstat -napt | grep LIST | grep i2pd
tcp        0      0 127.0.0.1:4444          0.0.0.0:*               LISTEN      6961/i2pd
tcp        0      0 127.0.0.1:7070          0.0.0.0:*               LISTEN      6961/i2pd
tcp        0      0 127.0.0.1:4447          0.0.0.0:*               LISTEN      6961/i2pd
tcp        0      0 127.0.0.1:7656          0.0.0.0:*               LISTEN      6961/i2pd
tcp        0      0 127.0.0.1:6668          0.0.0.0:*               LISTEN      6961/i2pd
```
Оно не совсем псевдослучано, похоже есть некая закономерность, точнее комбинация параметров в i2pd.conf и предыдущего состояния.

**Comment by LLE8** [comment]
Примерно такая закономерность.
Если запустить с ipv4=false и ipv6=true, то появляется только tcp6-сокет, это нормально (появляющиеся tcp4-соединения - отдеьная тема). Если остановить, я использовал systemctl stop i2pd, написать в конфиге  ipv4=true и ipv6=true, то после старта  tcp4-сокет не появляется, при перезапусках (systemctl stop i2pd, systemctl start i2pd) также не появляется, пробовал несколько раз подряд. Способ егл вернуть -  запустить 2 раза с  ipv4=true и ipv6=false, причем при первом запуске не появятся ни tcp4-сокет, ни tcp6-сокет, см выше, и только при втором запуске появится tcp4-сокет.
После этого можно перезапускать с  ipv4=true и ipv6=true, будут оба сокета. 
Насколько помню, год назад похожим образом так работал ipv6.

**Comment by r4sas** [comment]
м, это не транк как я понимаю?
Просто эти сообщения в лог были добавлены позже.

https://github.com/PurpleI2P/i2pd/blob/46ee427ee33c8a727a9bb838b5d5961145d917c3/libi2pd/NTCP2.cpp#L1196-L1201

https://github.com/PurpleI2P/i2pd/blob/46ee427ee33c8a727a9bb838b5d5961145d917c3/libi2pd/NTCP2.cpp#L1222-L1227

**Comment by LLE8** [comment]
Это 2.31 из repo.i2pd.xyz

**Comment by LLE8** [comment]
Где-то в /var/lib/i2pd между запусками сохраняется что-то, что в зависимости от предыдущего состояния ipv4/v6 прямо или косвенно определяет состояние ipv4/v6 при новом запуске?

**Comment by r4sas** [comment]
Максимум - router.info, но, фактически - нет таких файлов.

**Comment by LLE8** [comment]
2.32
Проблема с ipv4 остается. В логе по этой теме ничего интересного, записей "Failed to bind", "Unable to start" нет.
В i2pd.conf ipv4 = true и ipv6 = true
```
21:10:16@326/info - Log: min messages level set to debug
21:10:16@326/info - Log: will send messages to /var/log/i2pd/i2pd.log
21:10:16@326/info - i2pd v2.32.0 starting
21:10:16@326/debug - FS: main config file: /etc/i2pd/i2pd.conf
21:10:16@326/debug - FS: data directory: /var/lib/i2pd
21:10:16@326/info - Daemon: bandwidth set to 'low'
21:10:16@326/info - Daemon: using system limit in 4096 max open files
21:10:16@326/info - Daemon: starting NetDB
21:10:16@326/info - Family: 5 certificates loaded
21:10:17@326/info - NetDb: 3316 routers loaded (1705 floodfils)
21:10:17@326/info - Daemon: starting Transports
21:10:17@326/info - Daemon: ntcp disabled
21:10:17@326/info - NTCP2: Proxy is not used
21:10:17@326/info - NTCP2: Start listening v6 TCP port 15369
21:10:17@326/info - SSU: Start listening v6 port 15369
21:10:17@326/info - Transports: Start listening UDP port 15369
21:10:17@326/info - Daemon: Transports started
21:10:17@326/info - Daemon: starting webconsole at 127.0.0.1:7070
21:10:17@326/info - Daemon: starting Tunnels
21:10:17@361/debug - SSU: Creating new session to [2MnS] 200*:****:****:****:****:****:****:****
21:10:17@326/info - Daemon: starting Client
```

**Comment by r4sas** [comment]
Могу догадываться лишь о старом баге с подгрузкой router.info с устаревшей информацией без обновления. Попробуй дропнуть этот файл в выключенном состоянии.

**Comment by LLE8** [comment]
Интересно, по какой причине ipv4 и ipv6 поменялись местами в этом баге.

**Comment by LLE8** [comment]
Кстати, router.info при наблюдении этого бага выглядит так (фрагменты из hd /var/lib/i2pd/router.info)
```
00000190  0a 00 00 00 00 00 00 00  00 03 53 53 55 00 55 04  |..........SSU.U.|
000001a0  63 61 70 73 3d 02 42 43  3b 04 68 6f 73 74 3d 03  |caps=.BC;.host=.|
000001b0  3a 3a 31 3b 03 6b 65 79  3d 2c 34 6c 54 49 32 69  |::1;.key=,xxxxxx|
```
```
000001f0  34 31 33 3b 03 00 00 00  00 00 00 00 00 05 4e 54  |413;..........NT|
00000200  43 50 32 00 6c 04 68 6f  73 74 3d 03 3a 3a 31 3b  |CP2.l.host=.::1;|
```

**Comment by LLE8** [comment]
Да, удаление router.info помогает, в netstat появляется `tcp        0      0 0.0.0.0:27558           0.0.0.0:*               LISTEN      4947/i2pd`

**Comment by LLE8** [comment]
2.34
проблема выглядит так же, tcpv4 LISTEN не появляется там, где должен.

Наверное как-то переименовать этот баг?

**Comment by LLE8** [comment]
2.35 
баг наблюдается

**Comment by r4sas** [comment]
Проверь транк. Слишком много было переписано с работе с сетью в данный момент после 2.35.0

**Comment by LLE8** [comment]
Проверил свежий транк. Особенности проявления проблемы изменились, но сама проблема осталась.
Возможна ситуация, когда ipv4=true, но tcp4-сокета в состоянии listen нет.

**Comment by LLE8** [comment]
Похоже исправлено?

**Comment by orignal** [comment]
Не до конца. Еще может слушать все ipv6, а не только конкретный адрес.

**Comment by LLE8** [comment]
Баг https://github.com/PurpleI2P/i2pd/issues/1613 про это?

**Comment by orignal** [comment]
Для ipv4 должно работать все корректно.

**Comment by r4sas** [comment]
@LLE8 проверь на транке с https://github.com/PurpleI2P/i2pd/commit/631c8c9870bf48b9a4ff7f57daf82ae28c783251, должно быть пофикшено отсутствие NTCP2v6 сокета.

**Comment by LLE8** [comment]
Похоже исправлено, как и https://github.com/PurpleI2P/i2pd/issues/1613, и по ipv4, и по ipv6.
Но есть пара особенностей.
1. При ipv4=false и ipv6=false  tcp-соединения вообще не образуются, даже исходящие, по крайней мере за 30 минут работы при имеющейся ранее наполненой netdb. Это нормально?
2. Самопроизвольно при некоторых условиях изменяется порт, без удаления router.info.
По предварительным наблюдениям это происходит при пкрезапуске с изменением ipv4=false, ipv6=false на  ipv4=true, ipv6=true. Это нормально?

**Comment by orignal** [comment]
1. Так и должно быть если не включен yggdrasil
2. А параметр port в конфиге есть?

**Comment by LLE8** [comment]
1. Ygg не включен. Если не ошибаюсь, раньше такого поведения не было, исходящие соединения образовывались. И почему бы и нет?
2. Порт в конфиге не указан.

**Comment by orignal** [comment]
1. Раньше это было ошибкой. Если кто то не хочет светить свой ipv4 адрес и отключает его, то никаких соединений с его участием быть не должно
2. Из-за этого и возникает проблема, что если нет никаких адресов то и порту сохраняться негде. Поэтому, если хочется, чтобы порт был один и тот же, следует явно указывать его в параметре port

**Comment by LLE8** [comment]
1. По ipv6 то же самое? Логично, если false, значит отключено полностью.
2. При смене  ipv4=false, ipv6=true на  ipv4=true, ipv6=false порт тоже меняется (явно не указан).

Думаю , можно закрывать.

**Comment by orignal** [comment]
>Yggdrasil это какой-то особый ipv6, не управляемый ipv6=true/false?

Он не управляется параметром ipv6, для него meshnets.yggdrasil

**Comment by xanoni** [comment]
Is this the same issue? Sorry, don't speak enough Russian.

https://github.com/PurpleI2P/i2pd/issues/1686

**Comment by r4sas** [comment]
> Is this the same issue? Sorry, don't speak enough Russian.

No.
