### ISSUE TITLE
Making a hardened version 

### ISSUE THREAD

**Issue by Barack0bama** [PurpleI2P/i2pd#813]
i2pd is written in C++, integrating [Selfrando](https://github.com/immunant/selfrando) may help a lot from the security point of view. Splitting it into a hardened version to keep testing the integration would be ideal.

**Comment by majestrate** [comment]
How much of a perf impact would there be? In general I think that i2pd focuses on being fast `and` secure so any features that add significant perf degradation would need to be amended to lessen perf degradation as much as possible.

**Comment by Barack0bama** [comment]
@majestrate They're stating that,

> `selfrando` has an imperceptible effect on program initialization and runtime performance. When using the SPEC CPU2006 suite suite, `selfrando` adds less than a 1% overhead to most of the benchmark running times.

And as I said, you can make it into a hardened series and another normal one, so even if there was a noticeable performance impact you could always recommend the normal version for performance.

**Comment by majestrate** [comment]
Try a build with it and let us know, it'd be interested in the results.

**Comment by Barack0bama** [comment]
Selfrando fails for some reason on my Debian 8 machine, 

```
ar: out/x86_64/RandoLib/RandoLib.o: No such file or directory
scons: *** [out/x86_64/RandoLib/posix/libselfrando_noprefix.a] Error 1
scons: building terminated because of errors.

```

I'll try later on Ubuntu. In the meantime anyone can follow the instructions for building with Selfrando here: https://github.com/immunant/selfrando/blob/master/docs/linux-build-instructions.md

**Comment by janicez** [comment]
Oh I really hope that dude isn't the real former president. He must be really worried about his successor if he is. :/

**Comment by Barack0bama** [comment]
@majestrate I finally got the time to try out again, Selfrando compiled without errors. I went to compile i2pd with Selfrando, everything was going correctly until this point:

```
g++ -g -Wall -Wextra -Wno-unused-parameter -pedantic -Wno-misleading-indentation -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/i2pd.o i2pd.cpp
g++ -g -Wall -Wextra -Wno-unused-parameter -pedantic -Wno-misleading-indentation -std=c++11 -D_GLIBCXX_USE_NANOSLEEP=1 -fPIC   -c -o obj/DaemonLinux.o DaemonLinux.cpp
g++ -o i2pd obj/HTTPServer.o obj/I2PControl.o obj/UPnP.o obj/Daemon.o obj/i2pd.o obj/DaemonLinux.o libi2pd.a libi2pdclient.a -lcrypto -lssl -lz -lboost_system -lboost_date_time -lboost_filesystem -lboost_program_options -lpthread 
ar: creating /tmp/traparchive-C681dNogBf
ar: creating /tmp/traparchive-eevYF0i6Ke
ar: creating /tmp/traparchive-D4w2evSz1K
ar: creating /tmp/traparchive-rbP0zMgM2Y
ar: creating /tmp/traparchive-B6wPwWYBsb
/usr/include/boost/asio/detail/keyword_tss_ptr.hpp:48: error: TLS relocation against invalid instruction
/usr/include/boost/asio/detail/keyword_tss_ptr.hpp:48: error: TLS relocation against invalid instruction
/usr/include/boost/asio/detail/keyword_tss_ptr.hpp:54: error: TLS relocation against invalid instruction
/usr/include/boost/asio/detail/keyword_tss_ptr.hpp:54: error: TLS relocation against invalid instruction
/usr/include/boost/asio/detail/keyword_tss_ptr.hpp:48: error: TLS relocation against invalid instruction
/usr/include/boost/asio/detail/keyword_tss_ptr.hpp:48: error: TLS relocation against invalid instruction
/usr/include/boost/asio/detail/keyword_tss_ptr.hpp:54: error: TLS relocation against invalid instruction
/usr/include/boost/asio/detail/keyword_tss_ptr.hpp:54: error: TLS relocation against invalid instruction
Linker execution failed: Unknown error 256
ld.gold: src/Support/Debug.cpp:35: void Error::printf(const char*, ...): Assertion `false' failed.
/home/user/selfrando-master/Tools/Wrappers/ld: line 14: 18826 Aborted                 "$SR_PATH/ld.gold" -rpath "$SR_PATH" --traplinker-original-linker "$GOLD" "$@"
collect2: error: ld returned 134 exit status
Makefile:73: recipe for target 'i2pd' failed
make: *** [i2pd] Error 1
```

**Comment by majestrate** [comment]
@Barack0bama can you provide some documentation and scripts for this in that repo?

valgrind makes the program (val)grind to a halt perf wise, so it doesn't get any participating traffic.

**Comment by Barack0bama** [comment]
@majestrate  I just wrote a short doc on that https://github.com/Barack0bama/i2pd-selfrando/blob/master/README.md

**Comment by majestrate** [comment]
awesome, I'll see if I can get a build going later on.

**Comment by majestrate** [comment]
Just tried a selfrando build of i2pd, it was unusably slow.

**Comment by r4sas** [comment]
@Barack0bama you can replace [here](https://github.com/PurpleI2P/i2pd/blob/openssl/Makefile.linux#L2) `-g` to `-Os` to get more compact binary.

**Comment by Barack0bama** [comment]
@majestrate You mean the build process?

@r4sas Thanks, I will recompile it with that.

**Comment by janicez** [comment]
@Barack0bama Prove you're not Obama by posting a voice recording. Seriously. Your English is perfect. Also I'm British and I live in Canada. Also I love mangoes.

**Comment by orignal** [comment]
He also can write Russian, we will recognize :)

**Comment by janicez** [comment]
@orignal I was half joking.

**Comment by Barack0bama** [comment]
@janicez What prevents me from providing you with voice recordings from the buffoon that I wiretapped? :)

**Comment by orignal** [comment]
If  we get any advantages  from it, like getting in to Tails or other paranoid distros

**Comment by Barack0bama** [comment]
@orignal Anyway I'll keep making compiled versions with Selfrando each month and I'll release them [here](https://github.com/Barack0bama/i2pd-selfrando/releases/tag/2.12.0-hardened).

**Comment by Barack0bama** [comment]
Made a small shell script to make the build process automatic: https://github.com/Barack0bama/i2pd-selfrando/blob/master/script.sh

**Comment by orignal** [comment]
@Barack0bama to be able to investigate crashes

**Comment by Barack0bama** [comment]
@l-n-s 

You may add this in the documentation,

How to manually compile it with Selfrando https://gist.github.com/anonymous/5fb2a1796e6f67420a661153bfa19833

Script.sh to automatically compile it with Selfrando https://gist.github.com/anonymous/dfc59ce8fc009f580af2d5c01bcfd6d7

**Comment by janicez** [comment]
wtf is @ghost
