### ISSUE TITLE
add keywords to this github repository

### ISSUE THREAD

**Issue by l-n-s** [PurpleI2P/i2pd#819]
I'd suggest adding such keywords: 

    privacy, security, cryptography, p2p, decentralized, vpn, anonymity, c-plus-plus, openssl, anticensorship

**Comment by orignal** [comment]
where?

**Comment by l-n-s** [comment]
@orignal 
![qwe](https://cloud.githubusercontent.com/assets/13422305/23368415/afb997aa-fd05-11e6-92ab-08363399cbef.png)

**Comment by l-n-s** [comment]
neat
