### ISSUE TITLE
I2P Snark, I2P Mail, I2P Bote, ... should be bundled by default.

### ISSUE THREAD

**Issue by verystr0ngp4ssw5ord** [PurpleI2P/i2pd#820]
I2P Snark, I2P Mail, I2P Bote, ... should be bundled by default, and there should be a link for them in the web interface.

It's been a very hard experience for me to set them up, and I'm sure lots of less technical users would appreciate such addition.

**Comment by majestrate** [comment]
disagree, at least until there are non java implementations of each. I do have them for each written in go but idk if they should be bundled at the moment if ever.

[bdsmail](https://github.com/majestrate/bdsmail) mail server (working)
[XD](https://github.com/majestrate/xd) bittorrent (partially functional)
[i2pboted](https://github.com/majestrate/i2pboted) i2p bote implementation (non functional)

**Comment by verystr0ngp4ssw5ord** [comment]
@majestrate That is an even better suggestion!

**Comment by l-n-s** [comment]
i2pd is I2P network client, it does one job and does it well (Unix philosophy).

End-user apps are very important, but that is not an issue of i2pd itself.

**Comment by l-n-s** [comment]
We have created community forum, to discuss i2p-related topics.

Just created [End-user apps topic](https://github.com/PurpleI2P/community/issues/1)

**Comment by anotherdoesnm** [comment]
found this project - https://github.com/PurpleBote/pboted
Written in C++, didn't checked is it working
