### ISSUE TITLE
floodfill nodes use less bandwidth than non floodfill ones

### ISSUE THREAD

**Issue by randomrng** [PurpleI2P/i2pd#822]
It seems that floodfill nodes use less bandwidth than non floodfill ones

*nodeA in location A was switched from floodfill to non floodfill and now uses more bw than before. NodeB in location B was switched the opposite, and now uses less bw than before*

**Comment by LLE8** [comment]
I also noticed this in 2019

**Comment by orignal** [comment]
Works as designed. Floodfills have less priority on Java routers.
