### ISSUE TITLE
HTTP Proxy: HTTP_REFERER stripping has changed in Java I2P

### ISSUE THREAD

**Issue by l-n-s** [PurpleI2P/i2pd#823]
https://trac.i2p2.de/ticket/1862

> Client proxy changed to pass through relative referer URIs, and convert same-origin absolute URIs to relative. Absolute non-same-origin URIs are still stripped. This should work for any server software checking referers, but I didn't install FluxBB to test. In 9cf04201b4d100b0b635270a29892728f4933934 to be 0.9.28-6

**Comment by r4sas** [comment]
https://github.com/i2p/i2p.i2p/commit/da893452ea8c1be7bde450e864c3ee2d04e84222
