### ISSUE TITLE
In /var/log/messages      TCP: too many orphaned sockets

### ISSUE THREAD

**Issue by LLE8** [PurpleI2P/i2pd#825]
Debian Jessie, default values too small

May be add in   /etc/sysctl.conf  or in  /etc/sysctl.d/
```
net.core.somaxconn = 32768
net.ipv4.tcp_max_orphans = 32768
```
or any other values?

Здесь https://github.com/PurpleI2P/i2pd/issues/575  уже было

**Comment by r4sas** [comment]
@LLE8 это выходит за рамки приличия, лазить по системе пользователя и менять все параметры.

**Comment by LLE8** [comment]
Согласен
Пусть сам пользователь лазит, но ему это подсказать как-то.
Если не ошибаюсь, у меня по умолчанию  net.core.somaxconn = 1024, несерьезно как-то.
```
# netstat  -nap | grep EST | grep i2pd | wc -l
1063
```
И это при bandwith=L и floodfill=false
А кроме i2pd еще кто-то живой есть.

**Comment by l-n-s** [comment]
Это проблема i2pd или Debian Jessie?

**Comment by r4sas** [comment]
@l-n-s это общая проблема.

**Comment by r4sas** [comment]
status?

**Comment by LLE8** [comment]
Причем непонятно, что происходит. Обычно все выглядит примерно так так
```
~# ss -s
Total: 1663 (kernel 1689)
TCP:   1655 (estab 1556, closed 39, orphaned 40, synrecv 0, timewait 39/0), ports 0

Transport Total     IP        IPv6
*         1689      -         -
RAW       0         0         0
UDP       19        11        8
TCP       1616      1612      4
INET      1635      1623      12
FRAG      0         0         0
```
```
~# sysctl -a | grep orph
net.ipv4.tcp_max_orphans = 1024
net.ipv4.tcp_orphan_retries = 0
```

**Comment by LLE8** [comment]
Эффект какой-то плавающий, сейчас проявился после 9 суток аптайма

**Comment by r4sas** [comment]
Как тут дела?)

**Comment by LLE8** [comment]
Сейчас не могу сказать ничего определенного.
Эффект возникает кратковремменно, нерегулярно, неожиданно. Сейчас в логах этого нет, однако логи есть только за последние 6 часов, т.к. loglevel=debug.
А что-то нашли и исправили?

**Comment by r4sas** [comment]
Ну пол-года прошло, я не знаю статуса проблемы ибо сам не встречал подобного.

**Comment by r4sas** [comment]
@LLE8 есть ли смысл держать иссуй?

**Comment by LLE8** [comment]
Было множество таких сообщений 8 апреля и 10 апреля.

**Comment by r4sas** [comment]
А мы что можем сделать? Поднимаь лимит, как было ранее сказано, точно не будем.
@orignal можно ли как нибудь лимитировать количество соединений?

**Comment by LLE8** [comment]
Да, только включен только NTCP2, только ipv4. ни ntcp, ни ipv6 нет.
Лимит и по умолчанию кажется немаленький, у других так же?
Debian Buster 64 bit
`# sysctl -a | grep orph`
`net.ipv4.tcp_max_orphans = 2048`
Это какую пачку сокетов надо закрыть разом?
 Может быть причина в https://github.com/PurpleI2P/i2pd/issues/977 ?

Заметил, что количество транзитных туннелей изменяется пилообразно: монотонно растет, а в какой-то момент мгновенно уменьшается на 100-150 штук, период несколько минут. Может быть связано?

**Comment by r4sas** [comment]
Так это обычное дело, туннели же протухают каждые 12 минут.

Я такое не встречаю у себя ни на одной машине, на debian buster у меня из коробки стоит 4096 (даже не трогал).
```
~# sysctl -a | grep orph
net.ipv4.tcp_max_orphans = 4096
net.ipv4.tcp_orphan_retries = 0
```

**Comment by LLE8** [comment]
Ошибся, сейчас уточнил, период пилы секунд 15-20.

В Stretch tcp_max_orphans по умолчанию кажется тоже было 2048, не уверен, что у вас значение по умолчанию, но это не особо важно.

В нормальном состоянии так, предпосылок не видно
```
# ss -s
Total: 3278
TCP:   3206 (estab 3096, closed 45, orphaned 37, timewait 45)

Transport Total     IP        IPv6
RAW       2         1         1
UDP       7         4         3
TCP       3161      3159      2
INET      3170      3164      6
FRAG      0         0         0
```
Эффект трудно уловимый, даже не ежедневный.

Возможно, но маловероятно, причина была в https://github.com/PurpleI2P/i2pd/issues/1500 
Понаблюдаю.

**Comment by LLE8** [comment]
Новый vds со Stretch - tcp_max_orphans=2048

**Comment by LLE8** [comment]
Похоже, эти сообщения в логе появляются при завершении процесса i2pd, вероятно так и должно быть.

**Comment by r4sas** [comment]
Учитывая что в момент остановки мы останавливаем передачу и после отсылки FIN почти сразу закрываем сокет - возможно что да. Я уже предложил @orignal вариант решения, посмотрим что он решит сделать.

**Comment by LLE8** [comment]
Может быть здесь нечего исправлять, если это только при остановке.
