### ISSUE TITLE
i2pd doesn't start when /var/run/i2pd/ doesn't exist

### ISSUE THREAD

**Issue by kayrus** [PurpleI2P/i2pd#828]
and it has `--pidfile=/var/run/i2pd/i2pd.pid` parameter.
Besides it doesn't provide any error message even with `--logleve=debug` and its return code is 0.

**Comment by r4sas** [comment]
That happens only if you start i2pd not via init script.
https://github.com/PurpleI2P/i2pd/blob/openssl/debian/i2pd.init#L48

**Comment by kayrus** [comment]
@r4sas I suppose you understand that this is not an answer. Application has to detect whether it cannot create a file and show an error message.

**Comment by r4sas** [comment]
https://github.com/PurpleI2P/i2pd/commit/c7db9010ad36cbe11d503de186a23bf746b3e3af
