### ISSUE TITLE
Tor -> TCP i2p doesn't work with i2pd, but works with the Java client

### ISSUE THREAD

**Issue by lassword** [PurpleI2P/i2pd#834]
I have not been able to get i2pd working in a virtual machine where everything is routed through Tor.

One would expect that TCP would work, just like with the Java client for i2p, but that's not the case.

**Comment by majestrate** [comment]
are you using an LD_PRELOAD shim like `torify` or a transparent proxy setup? pretty sure that latter works, not sure about the former.

**Comment by lassword** [comment]
@majestrate I'm using Whonix.

Tested Java i2p client that was installed inside the Whonix Workstation (where all its traffic is routed through the separate Whonix Gateway virtual machine that runs the Tor daemon) and TCP traffic worked (but not UDP of course), I could get to forum.i2p and a bunch of other eepsites.

However when installing i2pd inside Whonix Gateway I can't get to anything, I always get "Host is down" even for forum.i2p.

Here's my i2pd.log: https://ghostbin.com/paste/ggrcy

**Comment by majestrate** [comment]
try disabling ssu in `i2pd.conf`

    ssu=false

**Comment by lassword** [comment]
@majestrate Just tested, it does work with `ssu = false`! Is there any particular reason why it is enabled by default?

**Comment by majestrate** [comment]
@lassword most users don't run i2p over tor.

**Comment by lassword** [comment]
@majestrate Fair enough, closing this issue.
