### ISSUE TITLE
Reseed file should be by default downloaded from Github

### ISSUE THREAD

**Issue by ghost** [PurpleI2P/i2pd#836]
Github isn't blocked (as far as I know) by all govs, and a request to Github would trigger far less suspicion than one to a i2p-projekt.de or i2p2.no.

TL;DR: [This should be the default](https://i2p.rocks/blog/connecting-to-i2p-network-through-restrictive-firewalls.html).

**Comment by r4sas** [comment]
https://github.com/PurpleI2P/i2pd/commit/0487e730ba18cdbace213f4a957b74ae80be7983
