### ISSUE TITLE
With ipv4=false i2pd still makes IPv4 connections

### ISSUE THREAD

**Issue by LLE8** [PurpleI2P/i2pd#837]
Ver 2.12
real hardware PC, 2 GB RAM, Core2Duo E6750 @ 2.66GHz
Debian Jessie 32 bit

part of i2pd.conf:
ipv4 = false
ipv6 = true
ifname6 = tun0 (pc behind nat, real ipv6 by vpn)
nat = false (i have real ipv6, ipv4 disabled)
bandwidth = 20480
notransit = false
floodfill = true

uptime 22 days 4 hours
~# netstat -nap | grep "tcp " | grep i2pd | grep EST | wc -l
496
~# netstat -nap | grep "tcp6" | grep i2pd | grep EST | wc -l
1570
IPv4 disabled in config. Why tcpv4 connections established?

Client tunnels 70, Transit tunnels 126
NTCP 335, SSU 0, SSU6 about 20 as i see, number is missing on webpage
And what about NTCP6?

**Comment by LLE8** [comment]
On VDS behavior is similar (ipv4 = false, but ipv4 connections exists)

**Comment by LLE8** [comment]
Попробовал запустить i2pd **исключительно** поверх yggdrasil. Не удалось.
Наблюдаю этот же баг с наличием соединений по ipv4 при `ipv4 = false`.

**Comment by r4sas** [comment]
Можете попробовать текущий код из ветки `transports_and_ri`?

**Comment by LLE8** [comment]
Попробовал.  При ipv4=false и ipv6=true образуются ipv4-соединения.


.

**Comment by r4sas** [comment]
А они какого типа? SSU или NTCP/2 ?

**Comment by LLE8** [comment]
Transports: NTCP2 - 15-25 шт ipv4, NTCP2v6 и SSUv6 в сумме менее 10

**Comment by LLE8** [comment]
2.31, Buster
Эффект по прежнему наблюдается. Причем за несколько первых минут ipv4 соединений образовалось значительно больше, чем ipv6, 24 против 4.

**Comment by r4sas** [comment]
Подниму этот иссуй.

```
15:02:25 <~R4SAS> а разве в Transports::ConnectToPeer мы не должны проверять включен ли ipv4/6?
15:02:42 <~orignal> не помню
15:02:44 <~R4SAS> это самое банальное место
15:02:48 <~orignal> я ж ленивый ))
15:03:21 <~R4SAS> так я думаю дело всё тут
15:03:33 <~R4SAS> мы просто берем и коннектимся повсюду
15:05:42 <~R4SAS> https://github.com/PurpleI2P/i2pd/blob/openssl/libi2pd/Transports.cpp#L394
15:06:06 <~orignal> наверное
```

**Comment by LLE8** [comment]
i2pd 2.34, Debian Buster
эффект наблюдается

**Comment by r4sas** [comment]
Необходимо перепроверить, в транке добавлены проверки на транспорты.

**Comment by LLE8** [comment]
На свежем транке этот баг у меня не воспроизводится.

**Comment by r4sas** [comment]
Тоже не наблюдаю на данный момент подобного у себя.
@LLE8, если баг не проявился, закрывай.

**Comment by LLE8** [comment]
Работа хостера, на котором проверял, вызывает подозрение. В сочетании с соседним багом https://github.com/PurpleI2P/i2pd/issues/811 я уже не уверен в этом. Посмотрю на каком-нибудь другом vds.

**Comment by LLE8** [comment]
Попутно заметил, что IPv6 без IPv4 работает очень слабо, 20-30 соединений и единицы транзитных туннелей. Проверил на 3 разных хостерах. Это так и должно быть?

**Comment by LLE8** [comment]
Обычно при одновременной работе соотношение ipv4 к ipv6 примерно 4 к 1, например
```
# ss -s
Total: 1896
TCP:   1981 (estab 1778, closed 178, orphaned 6, timewait 178)

Transport Total     IP        IPv6
RAW       0         0         0
UDP       13        5         8
TCP       1803      1448      355
INET      1816      1453      363
FRAG      0         0         0
```
По моим наблюдениям без работающего IPv4 почти не работает IPv6. 
Баг?
