### ISSUE TITLE
Can't connect to irc.postman.i2p through i2pd's tunnel

### ISSUE THREAD

**Issue by vi** [PurpleI2P/i2pd#840]
Nothing is received on socket for some time, then I get `ERROR :Closing Link: [127.0.0.1] (Registration Timeout)` and socket gets closed. The `tunnels.conf` is:

    [IRC]
    type = client
    address = 127.0.0.1
    port = 6668
    destination = irc.postman.i2p
    eys = irc-keys.dat

SOCKS5 connection to irc.postman.i2p with `connect-proxy -S 127.0.0.1:4447 irc.postman.i2p 12345` does work although.

**Comment by vi** [comment]
Seems like the problem is not I2Pd-related. Closing.

**Comment by mppdidi** [comment]
I have the same problem. 
When i connect to via a tunnels.conf client to the destination nothing happens.
To confirm that this is not an issue with the destination or the client application I connected via the http proxy and it did go through.
Also the client tunnel does not get ANY tags - but why is this ?

Thanx

**Comment by majestrate** [comment]
probably related to lack of hosts file on startup. maybe we could bundle a snapshot every release?
