### ISSUE TITLE
android — add #APP_ABI := x86_64 to jni/App*.mk

### ISSUE THREAD

**Issue by hypnosis-i2p** [PurpleI2P/i2pd#841]
https://developer.android.com/ndk/guides/x86-64.html

**Comment by orignal** [comment]
И что хотел сказать?

**Comment by hypnosis-i2p** [comment]
запланировал добавить коммент в App*.mk =)

**Comment by hypnosis-i2p** [comment]
оно ускоряет работу эмулятора android 5+ на x86_64
