### ISSUE TITLE
Build package on debian sid didn't work like the documentation says

### ISSUE THREAD

**Issue by whocares0101** [PurpleI2P/i2pd#847]
Doing `debuild --no-tgz-check` will always fail with `dpkg-source: error: can't build with source format '3.0 (quilt)': no upstream tarball found` doing `dpkg-buildpackage -b -rfakeroot -us -uc` instead worked for me.
Maybe someone can update the documentation and add a note.

source: https://askubuntu.com/a/675211

**Comment by LLE8** [comment]
In Jessie and Wheezy 
 debuild --no-tgz-check -b
