### ISSUE TITLE
Any "--bandwidth [integer]" value will report as "bandwidth set to 9999 KBps"! What's wrong, fix?

### ISSUE THREAD

**Issue by mlmikael** [PurpleI2P/i2pd#848]
The spec for --bandwidth is

>   --bandwidth arg                       Bandwidth limit: integer in kbps or
>                                         letters: L (32), O (256), P (2048), X
>                                         (>9000)

I want to give it 20MBPS, so i do i2pd --floodfill --bandwidth 20480 . When starting, I get this

> 05:45:01@684/info - Log: min messages level set to info
> 05:45:01@684/info - i2pd v2.12.0 starting
> 05:45:01@684/info - Daemon: router will be floodfill
> 05:45:01@684/info - Daemon: bandwidth set to 9999 KBps
> 05:45:01@684/info - Daemon: using system limit in 100000 max open files
> 05:45:01@684/info - Daemon: starting NetDB

Why is it reporting 9999kbps, is this a bug in the printout routine or in the bandwidth argument reading logics, or does i2pd have a transparent cap of 10mbps, or it can't quantify so high so it transparently assumes an "unlimited bandwidth" setting??

I want to give exactly 20mbps.

Btw, the data communication that I do (to any services I run and within any channels that I open), can go beyond 20mbps, so 20mbps is the amount that I give away during the periods that I do less than 20mbps myself, right?

**Comment by mlmikael** [comment]
Ah right, i2pd accepts both "--bandwidth 20480" and "--bandwidth=20480". So I presume both forms are explicitly supported.

**Comment by mlmikael** [comment]
Doing "i2pd --floodfill --bandwidth 2048" also gives me "Daemon: bandwidth set to 9999 KBps", duh!

What's going on?

**Comment by orignal** [comment]
Find it in the code and fix it. Also be aware that bandwidth limitation is approximate, you can't limit it exactly

**Comment by mlmikael** [comment]
I'm not so deep in the code that i'm competent to do this. Would anyone in particular be good to involve now?

**Comment by majestrate** [comment]
I think that it's set based on the bandwidth capacity flags right now. technically `X` cap should be unlimited not 9999

**Comment by majestrate** [comment]
@mlmikael i can guide you through the code if you want and got some spare time.

**Comment by mlmikael** [comment]
@majestrate Hi Jeff, thank you very much for the offer to do that. I pinged you off-thread now. Right now though my TODO is totally jammed and I cannot immerse in I2PD's sourcecode.

**Comment by l-n-s** [comment]
Looks the same as #863
