### ISSUE TITLE
Hammering CTRL+C caused this SIGSEGV

### ISSUE THREAD

**Issue by mlmikael** [PurpleI2P/i2pd#849]
Hammering CTRL+C caused this SIGSEGV:

10:17:13@904/warn - SSU: MAC verification failed 390 bytes from 90.36.140.119:24128
^Cassertion "mutex->count > 0" failed: file "/usr/src/lib/librthread/rthread_sync.c", line 116, function "_rthread_mutex_lock"
Abort trap (core dumped)

Unfortunately my i2pd was not compiled with debugging symbols. Will recompile it that way for if this happens again.

**Comment by mlmikael** [comment]
Looks like the shutdown code not is 100% effective, here I got it to initiate shutdown but not complete it at least in ~4 minutes:

^C^C^C13:01:19@5/info - Daemon: shutting down
13:01:19@5/info - Daemon: stopping Client
13:01:19@5/info - Clients: stopping HTTP Proxy
13:01:19@5/info - Clients: stopping SOCKS Proxy
13:01:19@5/info - Clients: stopping AddressBook
13:01:19@5/info - Addressbook: 433 addresses saved
13:01:19@5/info - Daemon: stopping Tunnels
13:01:19@986/info - SSU: Introduce new session to [tG3t] through introducer 45.32.148.78:15603
^C^C^C13:01:19@5/info - Daemon: stopping Transports
13:01:19@772/info - NTCP: Connect error Operation canceled
13:01:19@772/info - NTCP: Connect error Operation canceled
13:01:19@772/info - NTCP: Connect error Operation canceled
13:01:19@772/info - NTCP: Phase 2 read error: Operation canceled. Wrong ident assumed
13:01:19@772/info - NTCP: Connect error Operation canceled
13:01:19@772/error - NTCP: Phase 4 read error: Operation canceled. Check your clock
13:01:19@772/info - NTCP: Phase 2 read error: Operation canceled. Wrong ident assumed
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
c^C^C^C^C^C^C^C^C^C^C^C^C13:02:19@260/info - NetDb: saved 6 new/updated routers
13:02:19@260/info - NetDb: deleting 22 unreachable routers
^C^C^C^C^C^C^C^C^C^C^C^C13:02:49@260/info - NetDb: exploring new 1 routers ...
13:02:49@864/info - Transports: No NTCP or SSU addresses available
^C13:04:19@260/info - NetDb: exploring new 1 routers ...
13:04:19@864/info - Transports: No NTCP or SSU addresses available

**Comment by orignal** [comment]
You need to find out which thread hangs

**Comment by mlmikael** [comment]
@orignal , how do I do that using gdb or other extremely standard tools?

**Comment by mlmikael** [comment]
(or by sending i2pd SIGUSER1 etc.! that would be a nice way to do it if that's a common debugging Q and gdb not offers it in any straightforward way)

**Comment by majestrate** [comment]
i use [gdb dashboard](https://github.com/cyrus-and/gdb-dashboard) personally, great ui for this.

**Comment by orignal** [comment]
@mlmikael just join with gdb to pid

**Comment by mlmikael** [comment]
Please suggest the commands I should run in that "gdb -p PID" and provide you with copies of here?

**Comment by r4sas** [comment]
t/o. Please open new issue if still happen.

**Comment by LLE8** [comment]
Возможно, это было то же, что https://github.com/PurpleI2P/i2pd/issues/867
