### ISSUE TITLE
Hw to compile I2PD in debugging mode (i.e. how add the "-g" CXXFLAGS" & how make make script show the g++ arguments?

### ISSUE THREAD

**Issue by mlmikael** [PurpleI2P/i2pd#850]
Hi!

Please clarify how to compile I2PD in debugging mode (i.e. how add the "-g" CXXFLAGS"?

I'm used to autotools' configure.ac/configure with "CXXFLAGS="-g" ./configure", but that's not what's going on here. Please clarify the best practice, also feel free to write it up in https://media.readthedocs.org/pdf/i2pd/latest/i2pd.pdf .

Also just for clarity, I'd like to see the individual g++ calls and calls to other tools, with calling arguments, printed out. How do I do that?

Thanks!

**Comment by majestrate** [comment]
`make CXXFLAGS='-g'`

**Comment by majestrate** [comment]
our build system right now are raw makefiles, we have cmake build files too in `build` directory

    cd build && cmake . -DCMAKE_BUILD_TYPE=Debug && make

**Comment by mlmikael** [comment]
cool, right, "gmake CXX='g++' CXXFLAGS='-g'" works, neat! didn't even realize that. maybe mention it in your documentation file.

a last question on the topic of the build process, if I want to use your cmake route, how can I make it print out the individual g++ etc. commands including arguments? and also, how do I add more CXXFLAGS of any other type to the make process when using the cmake route?


anyhow, clearly using your raw makefile seems like the most convenient way. you will not "discontinue support" for your raw makefile-based way right, or will you?

thanks :D

**Comment by majestrate** [comment]
raw makefiles are the default build system at the moment

i think the command for cmake you want is

    make VERBOSE=1

or something like that

**Comment by mlmikael** [comment]
@majestrate thanks for clarifying, it works well.

Also it appears that "cmake . -DCMAKE_BUILD_TYPE=Debug" switches a permanent change to Debug mode, so even if you do "cmake ." it's still in debug mode?

Anyhow thanks for clarifying all.

**Comment by majestrate** [comment]
you can change it back to release by running `cmake . -DCMAKE_BUILD_TYPE=Release`

**Comment by LLE8** [comment]
If you are Debian user, you may 
debuild --no-tgz-check -b
At the end of package building you can see file i2pd in directory i2pd
```
~/src/i2pd$ file i2pd
i2pd: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=43b56f996bca627790479739454106991d968e6b, not stripped
```

**Comment by l-n-s** [comment]
looks like resolved
