### ISSUE TITLE
Archlinux packaging issues

### ISSUE THREAD

**Issue by shpinog** [PurpleI2P/i2pd#852]
Есть ли возможность собирать пакеты для арча? В aur все гнилое и не пашет, было бы идеально замутить реп в OBS

**Comment by orignal** [comment]
вроде собирали раньше

**Comment by shpinog** [comment]
Ну там прошлый релиз  лежит, новому 10 дней вроде как. И старый не работает из коробки, вроде и ошибок нет и не работает . Роутер поднимается , сеть цепляет , но тунели не строит. java-клиент при этом работает.

**Comment by l-n-s** [comment]
Предлагаю вам написать мейнтейнеру AUR пакета и выяснить у него, в чем проблема. Из разработчиков никто арчем не пользуется.
