### ISSUE TITLE
Add "make install" target to Makefile

### ISSUE THREAD

**Issue by xxzure** [PurpleI2P/i2pd#853]
1.cd i2pd/
2.make
After successfull build i2pd could be installed with:
3.make install
The 1st and 2nd steps success，but on the 3rd step：make: *** No rule to make target 'install'。stop。
How to install it？

**Comment by LLE8** [comment]
Try to build package
debuild --no-tgz-check -b
https://i2pd.readthedocs.io/en/latest/devs/building/unix/
