### ISSUE TITLE
--bandwidth documentation is contradictory 

### ISSUE THREAD

**Issue by robsmith11** [PurpleI2P/i2pd#854]
According to `https://i2pd.readthedocs.io/en/latest/user-guide/configuration/`, the unit for --bandwidth is "KBps" (kilobytes per second), but according to the output of `i2pd --help`, the unit is "kbps" (kilobits per second).

**Comment by v2e** [comment]
I also asked a similar question some time ago and was given an [answer](https://github.com/PurpleI2P/i2pd/issues/749#issuecomment-281515321) that it was kilobytes. This needs to be fixed in the documentation though.

**Comment by robsmith11** [comment]
Thanks.
