### ISSUE TITLE
TunnelMessage: I2NP message size 1078 is not enough

### ISSUE THREAD

**Issue by robsmith11** [PurpleI2P/i2pd#857]
I'm running a 2.12 node with the default configuration on a high-bandwidth 64-bit linux server.  It seems to be working fine, but I'm getting spammed with the warning in the title at a rate of over 10 per second.  I'm not sure what it means, but it seems excessive.

**Comment by orignal** [comment]
already fixed

**Comment by LLE8** [comment]
Не хочет этот баг умирать
`17:15:11@300/warn - TunnelMessage: Tunnel endpoint I2NP message size 1078 is not enough`
Версия 2.14

**Comment by LLE8** [comment]
И за компанию
`17:14:07@615/warn - SSU: I2NP message size 4096 is not enough`
`17:14:13@344/warn - Transports: delayed messages queue size exceeds 50`
но эти значительно реже
