### ISSUE TITLE
Allow for more granular bandwidth control

### ISSUE THREAD

**Issue by robsmith11** [PurpleI2P/i2pd#863]
It appears that when passing a value to `--bandwidth`, the actual limit applied is one of only four values: L (32), O (256), P (2048), X (>9000).  Is it possible to use a more granular limit?

For example, I'd like to use a limit of 700 KB/s, but that gets rounded up to 2048 KB/s, which is quite a bit more.

**Comment by l-n-s** [comment]
Bandwidth limit can be either integer in KBps or letters.

**Comment by robsmith11** [comment]
Your response doesn't address the issue.
Are you suggesting that the *effective* limit can take more than one of the four values?  That is not consistent with my testing.

**Comment by l-n-s** [comment]
Now I understand what you meant. Yes, it is an issue.

**Comment by lehitoskin** [comment]
My network is absolutely awful, so having a bandwidth limit _lower_ than `L` would be mighty helpful. Specifying the exact transfer rate I know my network can take would do wonders for my network reliability.

**Comment by orignal** [comment]
We can't handle such level of granularity
