### ISSUE TITLE
Android tunnel.conf question

### ISSUE THREAD

**Issue by Rifes0ne** [PurpleI2P/i2pd#864]
// HELP REQUIRED, NOT AN ISSUE

Hi there, i have an issue about creating server tunnel on Android (tunnels.conf not exist), maybe. cus of Android port forwarding...
Trying to implement secured p2p messenger :)

[RUS] Привет ребят, делаю по диплому безопастный мессенджер, хочу реализовать андроид версию p2p через i2pd, никак не найду как поднять серверный тунель, можете подсказать? :)

Буду трижды признателен за ссылку на либы/реализацию/пример на java, c++, golang. (Десктопные примеры не взлетели, как и с java i2p)

**Comment by hypnosis-i2p** [comment]
Вот , портируйте десктопный массагер на андройд https://github.com/hypnosis-i2p/i2pchat . Там юзается sam

**Comment by hypnosis-i2p** [comment]
Если сохраните протокол, получится общая сеть

**Comment by Rifes0ne** [comment]
Немного другое хотел узнать, как на андроиде поднимать серверный тунель? Пробовал портировать различные десктоповские реализации этого процесса, не взлетает. Как и по ману поднятие серверного тунеля ручками (tunnels.conf на андройде нету).
Если пример кода есть то вообще огонь.

**Comment by hypnosis-i2p** [comment]
так создайте tunnels.conf ручками. его там нету потому что Вы его не создали

**Comment by orignal** [comment]
tunnels.conf в директории /sdcard/i2pd
В нем как везде https://github.com/PurpleI2P/i2pd/wiki/tunnels.conf
