### ISSUE TITLE
make unsuccessful in armhf-ARMv7/Debian Jessie 

### ISSUE THREAD

**Issue by romx** [PurpleI2P/i2pd#866]
Starting a make in armhf/Debian Jessie system prematurely finished with gcc errors after a bunch of warnings ("unused parameter", etc)

tail of console messages:

[ 92%] Building CXX object CMakeFiles/i2pd.dir/root/i2pd/daemon/HTTPServer.cpp.o
[ 94%] Building CXX object CMakeFiles/i2pd.dir/root/i2pd/daemon/I2PControl.cpp.o
/root/i2pd/daemon/I2PControl.cpp:318:98: warning: unused parameter ‘bytes_transferred’ [-Wunused-parameter]
  void I2PControlService::HandleResponseSent (const boost::system::error_code& ecode, std::size_t bytes_transferred,
                                                                                                  ^
/root/i2pd/daemon/I2PControl.cpp:319:31: warning: unused parameter ‘socket’ [-Wunused-parameter]
   std::shared_ptr<ssl_socket> socket, std::shared_ptr<I2PControlBuffer> buf)
                               ^
/root/i2pd/daemon/I2PControl.cpp:319:73: warning: unused parameter ‘buf’ [-Wunused-parameter]
   std::shared_ptr<ssl_socket> socket, std::shared_ptr<I2PControlBuffer> buf)
                                                                         ^
/root/i2pd/daemon/I2PControl.cpp:483:40: warning: unused parameter ‘ecode’ [-Wunused-parameter]
    [](const boost::system::error_code& ecode)
                                        ^
/root/i2pd/daemon/I2PControl.cpp:497:40: warning: unused parameter ‘ecode’ [-Wunused-parameter]
    [](const boost::system::error_code& ecode)
                                        ^
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
CMakeFiles/i2pd.dir/build.make:100: recipe for target 'CMakeFiles/i2pd.dir/root/i2pd/daemon/I2PControl.cpp.o' failed
make[2]: *** [CMakeFiles/i2pd.dir/root/i2pd/daemon/I2PControl.cpp.o] Error 4
CMakeFiles/Makefile2:61: recipe for target 'CMakeFiles/i2pd.dir/all' failed
make[1]: *** [CMakeFiles/i2pd.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: *** [all] Error 2

full log in attachment
[i2pd make errors.txt](https://github.com/PurpleI2P/i2pd/files/953351/i2pd.make.errors.txt)

CPU: armhf ARMv7
OS: Debian Jessie
gcc: 4.9.2

How to fix it?

**Comment by orignal** [comment]
You need more memory. Either enable swap or build somewhere else
