### ISSUE TITLE
Make NTCP more scalable with multi-core usage

### ISSUE THREAD

**Issue by dvacet** [PurpleI2P/i2pd#876]
I am using the current release version 2.13.0 on Linux 4.4. The program is very stable so far, runs without problems for many days under heavy load (more than 1 MiB/s in each direction). There is still enough bandwidth left so it seems the limit is CPU. This is a multi-core machine and I suspect only a single thread can be active at any time.

Is it correct? If so is multi-core support planned?
Thanks

**Comment by majestrate** [comment]
Participating traffic i think that is single threaded but everything else has its own thread. Biggest cpu bottleneck is probably elgamal.

**Comment by dvacet** [comment]
Now I watched with htop to see individual threads. It is probably co-incidence thread usage adds-up so as to look as a single core (in the current steady state).

Six threads consume the most, with the most hungry two having total cumulative time a quarter of the process sum (each). Therefore I suspect the process may not scale with more than two cores. Unfortunately I have not compiled with symbols so cannot see more.

**Comment by LLE8** [comment]
My experience is similar. Bandwidth is not more than 9-11 Mbit/s (5 up + 5 down), CPU usage is not more than 50-60%. Single core vds.

**Comment by orignal** [comment]
Basically DH key agreement is std::async so it's executed in a separate thread.

The most CPU-consuming thread is NTCP.

**Comment by dvacet** [comment]
NTCP serves the transit traffic? As currently the most traffic is transit. There are some local destination(s) but no downloads/uploads are running.

**Comment by orignal** [comment]
NTCP serves all TCP communications with other nodes

**Comment by dvacet** [comment]
OK, so there is a single NTCP thread which is probably heavily loaded. Then it explains why the performance does not scale with more cores.

**Comment by orignal** [comment]
There are two NTCP threads if you have ipv6 enabled.
That's how it was implemented initially. I will try to make it scalable.

**Comment by dvacet** [comment]
Just wanted to know reason for the current behaviour. I am perfectly fine with the current performance (not a dedicated machine anyway).

Thanks for such great program.

**Comment by orignal** [comment]
That's just how it was implemented initially
