### ISSUE TITLE
Exclude router classes for tunnel building

### ISSUE THREAD

**Issue by ghost** [PurpleI2P/i2pd#877]
Is it possible to filter routers based on their class ?

**Comment by majestrate** [comment]
No.

What scope should that operate at? Per Destination?

**Comment by mppdidi** [comment]
filter peers for tunnel building - i2p java has such a filter.

**Comment by majestrate** [comment]
at what scope does this filter operate at? per destination?

**Comment by mppdidi** [comment]
no it's generic for all tunnels client tunnels 

i2p.i2p/router/java/src/net/i2p/router/tunnel/pool/TunnelPeerSelector.java
...
char excl[] = excludeCaps.toCharArray(); */
...

but per destination would also be really cool.

**Comment by mppdidi** [comment]
the reason i'm asking for this is because in the unpatched version the java i2p router selects peers of levels lower than 'O' allthoug there are enough fast peers available - so i want to see if the java i2p profiler/peer selection is making the wrong decision in some cases.

**Comment by majestrate** [comment]
I'll see if I can add this today.

**Comment by l-n-s** [comment]
Can you change title for more correct description of the issue?

**Comment by r4sas** [comment]
ping?
