### ISSUE TITLE
Improve transports display in webconsole

### ISSUE THREAD

**Issue by mppdidi** [PurpleI2P/i2pd#879]
it would be great to see the number of transports on the landing page of the webconsole.

**Comment by l-n-s** [comment]
What do you mean by "number of transports"? Transports are SSU and NTCP protocols + their ipv6 versions. You can see all of them in webconsole.

**Comment by LLE8** [comment]
На страничке  http://127.0.0.1:7070/?page=transports
NTCP4 и NTCP6 вперемешку, количество скорее всего общее, до SSU4 трудно добраться, не проскочив мимо, особенно в текстовом браузере типа w3m, SSU6 вообще без количества.
Возможно, было бы разумно показывать эти 4 числа прямо на  http://127.0.0.1:7070/
Не самый страшный баг, я думаю.

**Comment by r4sas** [comment]
https://github.com/PurpleI2P/i2pd/commit/d9b9457b5617435ee411a0e94d20cb4bd7c4e349
