### ISSUE TITLE
warning

### ISSUE THREAD

**Issue by gongzisun** [PurpleI2P/i2pd#882]
Founded latest version 
accessing unknow domains such as *.pudge.xyz

Closely monitor your DNS resovle result, possible malware in this version.
Don't know what the I2P is sending to *.pudge.xyz

Beware You might be watched already.

Name: pudge.xyz
Address: 83.212.97.149

Name: v6-187.e2.pudge.xyz
Address: 143.215.215.187

Name: v6-165.e2.pudge.xyz
Address: 143.215.215.165

Name: v6-167.e2.pudge.xyz
Address: 143.215.215.167

Name: v6-141.e2.pudge.xyz
Address: 143.215.215.141

ISP Organization Latitude Longitude
Greek Research and Technology Network S.A Greek Research and Technology Network S.A 37.9833 23.7333

General Info
remarks: ==============
remarks: GRNET donwstream customers are Greek Universities, Academic
remarks: and Research Institutes
remarks: GRNET has GEANT as its upstream; it also connects to GRIX
remarks: Internet Exchange

**Comment by K1773R** [comment]
thats not an issue.

there are routers in the NetDB which have this:
Published: 24 min ago
Signing Key: EdDSA_SHA512_Ed25519
Address(es): SSU: [caps=BC] [host=v6-166.e2.pudge.xyz] [key=8I6HnbN0p1gWfjYDmcCR32TxkPFld3B7c8T7vLxU1WY=] [port=17167] NTCP: [host=v6-166.e2.pudge.xyz] [port=17167]

Obviously to connect, the IP has to be resolved. They got quite some routers (18 for me, right now).

**Comment by majestrate** [comment]
i2pd developers don't have any control over who runs what on the network,
suggesting there are malware laced releases is a claim that requires proof,
traffic to 'wierd nodes' isn't proof.

**Comment by gongzisun** [comment]
Sorry，I'm too suspicious
And made it wrong
