### ISSUE TITLE
Are HTTP and SOCKS proxies broken in 2.14 ?

### ISSUE THREAD

**Issue by LLE8** [PurpleI2P/i2pd#890]
How to reproduce:
`curl  --socks5-host  127.0.0.1:4447   http://inr.i2p/export/alive-hosts.txt`
and
`curl  -x  http://127.0.0.1:4444/   http://inr.i2p/export/alive-hosts.txt`
doesn't work in 2.14 but works in 2.13
Machines configs and i2pd,conf are identical.
Default configs i2pd was modified on both computers equally
```
/etc/i2pd# diff i2pd.conf  000_i2pd.conf
28d27
< loglevel = warn
58d56
< ifname = eth0
67d64
< nat = false
74d70
< bandwidth = 5000
78d73
< notransit = false
82d76
< floodfill = true
```

**Comment by orignal** [comment]
Tried now. Everything works fine

**Comment by LLE8** [comment]
На другом вдс работает нормально. Странно.

**Comment by LLE8** [comment]
[copy_of_i2pd.log.gz](https://github.com/PurpleI2P/i2pd/files/1071458/copy_of_i2pd.log.gz)

Мне это в i2pd.log показалось странным
`16:04:23@955/warn - SSU: Missing fragments from 0 to 0 of message 1725499929`

```
~# curl --socks5-host 127.0.0.1:4447 http://inr.i2p/export/alive-hosts.txt
curl: (7) Can't complete SOCKS5 connection to inr.i2p:11881. (4)

~# curl  -x  http://127.0.0.1:4444/   http://inr.i2p/export/alive-hosts.txt
<html>
<head>
  <title>I2Pd HTTP proxy</title>
  <style type="text/css">
    body { font: 100%/1.5em sans-serif; margin: 0; padding: 1.5em; background: #FAFAFA; color: #103456; }
    .header { font-size: 2.5em; text-align: center; margin: 1.5em 0; color: #894C84; }
  </style>
</head>
<body><h1>Proxy error: Host not found</h1>
<p>Remote host not found in router's addressbook</p>
<p>You may try to find this host on jumpservices below:</p>
<ul>
  <li><a href="http://joajgazyztfssty4w2on5oaqksz6tqoxbduy553y34mf4byv6gpq.b32.i2p/search/?q=inr.i2p">inr.i2p</a></li>
  <li><a href="http://7tbay5p4kzeekxvyvbf6v7eauazemsnnl2aoyqhg5jzpr5eke7tq.b32.i2p/cgi-bin/jump.cgi?a=inr.i2p">stats.i2p</a></li>
</ul>
</body>
</html>
```
Традиционные сайты с помощью w3m открываются.
Что и где еще посмотреть, пока этот vds хостер не перезагрузил?

**Comment by LLE8** [comment]
Заодно заметил, что https://github.com/PurpleI2P/i2pd/issues/857 никуда не делся, как мне кажется.
Может снова его открыть?

**Comment by orignal** [comment]
inr.i2p в адресной книге нету

**Comment by LLE8** [comment]
Вероятно, вы правы, что-то не то с адресной книгой. а не с проксями.
На другой машинке открывается и http://zzz.i2p/, и http://echelon.i2p/,
и эти трое из subscriptions.txt печатаются на stdout
http://inr.i2p/export/alive-hosts.txt
http://stats.i2p/cgi-bin/newhosts.txt
http://i2p-projekt.i2p/hosts.txt

А на прблемной машинке открывается только таким образом 
curl -x http://127.0.0.1:4444/ http://afvtspvugtd32rsalxircjglh3fhcjzk7gxrm3gw4s2yrpvzk6wq.b32.i2p
и
curl -x http://127.0.0.1:4444/ http://joajgazyztfssty4w2on5oaqksz6tqoxbduy553y34mf4byv6gpq.b32.i2p/export/alive-hosts.txt

Конфиги одинаковые, как исходном i2pd.conf.
```
[addressbook]
## AddressBook subscription URL for initial setup
## Default: inr.i2p at "mainline" I2P Network
# defaulturl = http://joajgazyztfssty4w2on5oaqksz6tqoxbduy553y34mf4byv6gpq.b32.i2p/export/alive-hosts.txt
## Optional subscriptions URLs, separated by comma
# subscriptions = http://inr.i2p/export/alive-hosts.txt,http://stats.i2p/cgi-bin/newhosts.txt,http://rus.i2p/hosts.txt
```
 В связи с этим вопрос: если ничего не написано, адресная книга все равно берется из joajgazyztfssty4w2on5oaqksz6tqoxbduy553y34mf4byv6gpq.b32.i2p ?

На всякий случай, флибуста вероятно лежит, даже http://zmw2cyw2vj7f6obx3msmdvdepdhnw2ctc4okza2zjxlukkdfckhq.b32.i2p не отзывается.

**Comment by orignal** [comment]
Да, загружается с .b32 inr.i2p. Кстати можно этот адрес и в конфиге задать.
Если не загрузилась то только jump-ом aka addresshelper.

Флибуста несколько дней уже лежит - написал им в твиттере

**Comment by LLE8** [comment]
subscriptions.txt читается толькоодин раз, при старте?

**Comment by orignal** [comment]
Да. Только при старте. Но вообще он является устаревшим, а правильно его содержимое писать в конфиг

**Comment by LLE8** [comment]
Добавление http://joajgazyztfssty4w2on5oaqksz6tqoxbduy553y34mf4byv6gpq.b32.i2p/export/alive-hosts.txt в начало subscriptions.txt помогло, правда не сразу. Странно.
А вобщем можно закрыть эту тему, я поспешил с выводами о неработоспособности проксей.
И следует ли обращать внимание на "Tunnel endpoint I2NP message size 1078 is not enough" ? https://github.com/PurpleI2P/i2pd/issues/857

**Comment by LLE8** [comment]
Во вчерашнем транке
15:40:55@727/warn - TunnelMessage: Tunnel endpoint I2NP message size 1078 is not enough

**Comment by LLE8** [comment]
И еще 
15:41:02@510/warn - SSU: I2NP message size 4096 is not enough

**Comment by orignal** [comment]
а вот это плохой симптом - это значит что сеть не справляется

**Comment by LLE8** [comment]
на разных vds у разных хостеров iftop и atop показывают 2-3 Mbit\s up + 2-3 Mbit\s down. С чем она не справляется?  Или в i2pd чрезвычайно мелкие пакеты байт по 50? Имеет смысл что-то спрашивать у хостера?
Сейчас в i2pd.conf bandwidth = 5000, я правильно понимаю, что это ограничение приблизительно 50 мегабит в секунду, т.е. половина от традиционного 100-мегабитного ethernet-а?
Вообще больше 5-6 up + 5-6 down не видел.
Причем включение aes и avx производительность сети не увеличивает, как мне показалось, зато несколько снижает загрузку cpu, которая в любом случае далека от 100%.

**Comment by orignal** [comment]
Я думаю это проблема с каким то конкретным линком

**Comment by LLE8** [comment]
itldc.com, vscale.io, takewyn.com, arubacloud.com
Да, все недорогие, но не сговорились же они все.

**Comment by orignal** [comment]
сообщения не уходят к ним достаточно быстро. возможно хостер чего то мутит

**Comment by LLE8** [comment]
Мутят все четверо? Рига, Москва, Днепр, где-то в Италии.
Посмотреть еще на кого-то?
Подозреваю, что имеет смысл оформить отдельный баг на эту тему.

**Comment by orignal** [comment]
Я имел ввиду мутит свой. Либо тред в этот момент занимет ядро целиком

**Comment by LLE8** [comment]
При поверхностном наблюдении на arubacloud самый тяжелый тред занимает не более 10% cpu. Сомневаюсь, что могут быть внезапные кратковременные пики 100%.
Типично верхушка top выглядит так 
```
  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
 3863 i2pd      20   0  712368  28476   6884 S  7.3  2.8 109:28.83 i2pd
 3861 i2pd      20   0  712368  28476   6884 S  3.7  2.8  87:05.23 i2pd
 3865 i2pd      20   0  712368  28476   6884 S  2.0  2.8  43:47.89 i2pd
 3860 i2pd      20   0  712368  28476   6884 S  1.7  2.8  29:12.78 i2pd
 3867 i2pd      20   0  712368  28476   6884 S  1.0  2.8  21:37.78 i2pd
 3509 root      20   0   93584   8044   7112 S  0.3  0.8   1:46.20 vmtoolsd
 3862 i2pd      20   0  712368  28476   6884 S  0.3  2.8   4:21.07 i2pd
    1 root      20   0   28568   4724   3108 S  0.0  0.5   0:02.23 systemd
```

**Comment by LLE8** [comment]
И на Linode в Японии тоже
```
10:39:29@385/warn - NTCP: outgoing messages queue size exceeds 200
10:40:04@912/warn - Transports: delayed messages queue size exceeds 50
```
Самый тяжелый тред жрет не более 7% cpu на первый взгляд. Транк от 23 июня, собран без aes-avx.

Может быть имеет смысл завести на эту тему баг?

**Comment by orignal** [comment]
Лучше в лог добавить IP адрес того у кого очередь

**Comment by LLE8** [comment]
Как это сделать?

Заодно
Этот Linode умеет aes, avx, но трафика дают всего лищь 1 ТБ/мес.
```
~# cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 79
model name      : Intel(R) Xeon(R) CPU E5-2697 v4 @ 2.30GHz
stepping        : 1
microcode       : 0x1
cpu MHz         : 2299.986
cache size      : 4096 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat
bugs            :
bogomips        : 4601.63
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:
```

**Comment by orignal** [comment]
В коде поправить

**Comment by LLE8** [comment]
Думаю, стоит закрыть эту тему.
А про
```
10:39:29@385/warn - NTCP: outgoing messages queue size exceeds 200
10:40:04@912/warn - Transports: delayed messages queue size exceeds 50
```
завести отдельный баг.
