### ISSUE TITLE
посоны, помогите мне

### ISSUE THREAD

**Issue by mista-twista** [PurpleI2P/i2pd#895]
чё такое? я этим вашим и2пд не пользовался долго, решил зайти вас попроведать...
сделал git pull
сделал make install
и не могу подключится к ирке.
потом увидел, что у вас репозиторий появился и вообще много чего....
снёс всё и поставил из репозитория.
теперь при запуске:

639/info - NetDb: RouterInfo added: cMX3oLphZ8CmJYIFvqvx0U=
@639/info - NetDb: RouterInfo added: bEqBo7h8O6AWPc5fIkOI=
@639/info - Daemon: starting Transports
@639/info - NTCP: Start listening TCP port 
@639/info - Transports: Start listening UDP port 
@639/info - Daemon: Transports started
@639/info - Daemon: starting HTTP Server at 127.0.0.1:7070
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  bind: Address already in use
Aborted (core dumped)

старый и2пд я вычистил полностью.
перезагружался.
2 раза он не запущен.

хули делать?

Искренне Ваш,
Мистер Твистер.

**Comment by l-n-s** [comment]
Похоже, порт какой-то занят из стандартных - 4444, 4447, 7656, 7070

**Comment by orignal** [comment]
Смотри кто занимает порт "what(): bind: Address already in use".
Загляни в router.info нету ли там NTCP сессии дважды

**Comment by mista-twista** [comment]
ни один из стандартных не занят.
те, которые слушает ntcp и udp тоже 

вот такая ещё херня в начале:
@639/info - Log: min messages level set to info
@639/info - i2pd v2.14.0 starting
@639/info - Daemon: bandwidth set to 'low'
@639/info - Daemon: using system limit in 1024 max open files
@639/info - Daemon: starting NetDB
@639/warn - Family: Can't load family certificates from /home/xxx/.i2pd/certificates/family
@639/info - NetDb: 0 routers loaded (0 floodfils)
@639/warn - Reseed: Can't load reseed certificates from /home/xxx/.i2pd/certificates/reseed
@639/error - RouterInfo: Can't open file 
@639/info - Reseed: Downloading SU3 from https://itoopie.atomike.ninja/i2pseeds.su3
@639/info - NetDb: RouterInfo added: и бла-бла-бла загрузка до той выдачи, что выше...

**Comment by mista-twista** [comment]
как мне вычистить всё наголо?
моя интуиция говорит, что старая версия, которую я с гитхаба собирал оставила говна.
я ставил по той старой инструкции с хабра.

**Comment by l-n-s** [comment]
Для начала, `rm -rf $HOME/.i2pd`

**Comment by mista-twista** [comment]
это я сделал. и для /home/i2pd сделал

**Comment by l-n-s** [comment]
А из какого конкретно репозитория ты ставил? Ubuntu?

**Comment by mista-twista** [comment]
который в документации - purplei2p/i2pd от R4SAS

**Comment by mista-twista** [comment]
потом сносил через apt-get remove и ставил из deb-пакета. тоже самое.

**Comment by mista-twista** [comment]
у меня по старой инструкции с хабра соберётся?

**Comment by orignal** [comment]
/var/lib/i2pd почисти

**Comment by LLE8** [comment]
dpkg --purge i2pd  может помочь

**Comment by orignal** [comment]
@LLE8 да он уже разобрался :)
