### ISSUE TITLE
undefined reference to `__atomic_load_8' on ARMv6

### ISSUE THREAD

**Issue by v2e** [PurpleI2P/i2pd#897]
Hello!
I encountered the following linker problem with the [recent](https://github.com/PurpleI2P/i2pd/releases/tag/2.14.0) i2pd sources:

```
HTTPServer.cpp:(.text+0x7e2c): undefined reference to `__atomic_load_8'
I2PControl.cpp:(.text+0xddc): undefined reference to `__atomic_load_8'
I2PControl.cpp:(.text+0xe74): undefined reference to `__atomic_load_8'
NTCPSession.cpp:(.text+0x5a00): undefined reference to `__atomic_fetch_add_8'
TransitTunnel.cpp:(.text+0x5c): undefined reference to `__atomic_fetch_add_8'
Transports.cpp:(.text+0x4bc): undefined reference to `__atomic_load_8'
SSUSession.cpp:(.text+0x370): undefined reference to `__atomic_fetch_add_8'
```
and so on.
So I had to add the `-latomic` to the following [line](https://github.com/PurpleI2P/i2pd/blob/openssl/build/CMakeLists.txt#L443) in the `CMakeLists.txt` in order to build the executable:

`target_link_libraries( "${PROJECT_NAME}" libi2pd i2pdclient ${DL_LIB} ${Boost_LIBRARIES} ${OPENSSL_LIBRARIES} ${ZLIB_LIBRARY} ${CMAKE_THREAD_LIBS_INIT} ${MINGW_EXTRA} ${DL_LIB} -latomic )`

I doubt this is a correct solution -- just reporting the result. This issue looks very similar to [another](https://github.com/PurpleI2P/i2pd/issues/285) one which was closed some time ago, but for another CPU architecture. So it might be worth making some kind of a universal solution to it.

**Comment by orignal** [comment]
don't use cmake but Makefile

**Comment by v2e** [comment]
I tried to add `LDLIBS += -latomic` to `Makefile.linux` at first, but it did not work. Then I tried to add `-latomic` to the root `Makefile`, it did not work also. So the only way I managed to get the i2pd executable built is to edit the `CMakeLists.txt`.

**Comment by strasharo** [comment]
Same here on Arch Linux ARM running on arvm6h.  Adding -latomic to CMakeLists.txt as suggested by @v2e resolved the issue for me.
