### ISSUE TITLE
deps as gitmodules

### ISSUE THREAD

**Issue by hypnosis-i2p** [PurpleI2P/i2pd#898]
надо вот так же в и2пд депенденсиз оформить https://github.com/nicehash/sgminer/blob/master/.gitmodules

**Comment by majestrate** [comment]
do we really want to statically compile in libssl ?

**Comment by SOUx4cx4fx56x69** [comment]
What for?

**Comment by orignal** [comment]
I don't see any point of it, and we do it in i2pd-tools

**Comment by SOUx4cx4fx56x69** [comment]
Why issue already not closed?
