### ISSUE TITLE
Is it possible in principle to implement i2pd directly in browser using Mozilla HumbleNet network library?

### ISSUE THREAD

**Issue by LLE8** [PurpleI2P/i2pd#899]
About HumbleNet
http://www.opennet.ru/opennews/art.shtml?num=46793

**Comment by majestrate** [comment]
It wouldn't be able to talk to any other routers.

**Comment by LLE8** [comment]
Why?

**Comment by majestrate** [comment]
it uses websockets and webrtc on the lower layers, it doesn't seem to be plain tcp/udp

**Comment by LLE8** [comment]
i2pm network?  m - Mozilla
