### ISSUE TITLE
[testnet] Floodfill creates too much transit tunnels

### ISSUE THREAD

**Issue by l-n-s** [PurpleI2P/i2pd#905]
Running a docker testnet, it runs fine for a minute, then floodfills start to create transit tunnels like crazy - 2000+ transits for tiny testnet of 2 floodfills and 8 regular nodes.

At the same time, regular nodes tunnel success rate drops from 80% to 3%.

[Floodfill log](https://github.com/l-n-s/funny-cats/releases/download/v1.0/hue.txt.gz)

[Top log messages](https://gist.githubusercontent.com/l-n-s/b4412f39a4709438286b96a5fe944c00/raw/0d6ed9c54a120af694354dd5e26265a62c276e64/top.txt)

**Comment by majestrate** [comment]
probably related to the lack of soft limiting.

**Comment by l-n-s** [comment]
Looks like it was my mistake, now it works perfect.
