### ISSUE TITLE
"error: cannot install libboost-date-time1.55.0"

### ISSUE THREAD

**Issue by beng7** [PurpleI2P/i2pd#921]
Hi
struggling to install latest (2.15.0) & previous version (2.14.0).
My distro is bunsenlab (jessie based + openbox) & kernel Linux 4.9.0-0.bpo.3-amd64.

deb package requires "error: cannot install libboost-date-time1.55.0"; obviously I tried to install the package / dependency but to no avail 
and in terminal: "i2pd : Depends: libboost-date-time1.55.0 but it is not going to be installed"

Anyone experiencing this too?
thanks

**Comment by majestrate** [comment]
have you tried an `apt-get install -f` ?

**Comment by beng7** [comment]
I did.

**Comment by majestrate** [comment]
I guess this means the debian packages don't work on old-stable... huh.

**Comment by beng7** [comment]
:( thanks

**Comment by majestrate** [comment]
will look into it, we should be able to support back to wheezy (i think).

**Comment by beng7** [comment]
please let me know if you need any logs from me

**Comment by majestrate** [comment]
what version is `libboost-all-dev` package at?

**Comment by beng7** [comment]
1.55.0.2

**Comment by majestrate** [comment]
looks like your distro uses weird package versions, could be the problem.
if that is the problem that would be funny.

**Comment by beng7** [comment]
duh! but thanks for your help
got to go now sorry - will check back tomorrow

**Comment by beng7** [comment]
~$ aptitude why-not libboost-date-time1.55.0
i   libstdc++6 Breaks libboost-date-time1.55.0

**Comment by LLE8** [comment]
Debian Jessie, upgraded without problems
```
~# apt-get upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  linux-image-amd64
The following packages will be upgraded:
  i2pd linux-libc-dev
2 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Need to get 1,805 kB of archives.
After this operation, 9,216 B of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 http://security.debian.org/ jessie/updates/main linux-libc-dev amd64 3.16.43-2+deb8u3 [1,060 kB]
Get:2 http://repo.lngserv.ru/debian/ jessie/main i2pd amd64 2.15.0-1jessie1 [744 kB]
Fetched 1,805 kB in 0s (2,059 kB/s)
Reading changelogs... Done
(Reading database ... 42996 files and directories currently installed.)
Preparing to unpack .../i2pd_2.15.0-1jessie1_amd64.deb ...
Unpacking i2pd (2.15.0-1jessie1) over (2.14.0-1jessie1) ...
Preparing to unpack .../linux-libc-dev_3.16.43-2+deb8u3_amd64.deb ...
Unpacking linux-libc-dev:amd64 (3.16.43-2+deb8u3) over (3.16.43-2+deb8u2) ...
Processing triggers for man-db (2.7.0.2-5) ...
Processing triggers for systemd (215-17+deb8u7) ...
Setting up i2pd (2.15.0-1jessie1) ...

Configuration file '/etc/i2pd/i2pd.conf'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** i2pd.conf (Y/I/N/O/D/Z) [default=N] ?
usermod: no changes
Setting up linux-libc-dev:amd64 (3.16.43-2+deb8u3) ...

~# dpkg -l | grep i2pd
ii  i2pd                                 2.15.0-1jessie1                  amd64        A full-featured C++ implementation of I2P client.

~# dpkg -l | grep libboost
ii  libboost-date-time1.55.0:amd64       1.55.0+dfsg-3                    amd64        set of date-time libraries based on generic programming concepts
ii  libboost-dbg:amd64                   1.55.0.2                         amd64        Boost C++ Libraries with debug symbols (default version)
ii  libboost-dev:amd64                   1.55.0.2                         amd64        Boost C++ Libraries development files (default version)
ii  libboost-filesystem1.55.0:amd64      1.55.0+dfsg-3                    amd64        filesystem operations (portable paths, iteration over directories, etc) in C++
ii  libboost-iostreams1.55.0:amd64       1.55.0+dfsg-3                    amd64        Boost.Iostreams Library
ii  libboost-program-options1.55.0:amd64 1.55.0+dfsg-3                    amd64        program options library for C++
ii  libboost-system1.55.0:amd64          1.55.0+dfsg-3                    amd64        Operating system (e.g. diagnostics support) library
ii  libboost1.55-dbg:amd64               1.55.0+dfsg-3                    amd64        Boost C++ Libraries with debug symbols
ii  libboost1.55-dev:amd64               1.55.0+dfsg-3                    amd64        Boost C++ Libraries development files
```

**Comment by LLE8** [comment]
Debian Wheezy, upgrade from 2.14 to 2.15 without problems

**Comment by majestrate** [comment]
he's running some fork of debian jessie that bumped boost's version wierdly. maybe have him submit a bug to his distro? idk.

**Comment by beng7** [comment]
opened a topic at [BL forums
](https://forums.bunsenlabs.org/viewtopic.php?pid=58571#p58571)

**Comment by majestrate** [comment]
i get an http 403 ... huh

**Comment by beng7** [comment]
https://forums.bunsenlabs.org/viewtopic.php?pid=58571#p58571

**Comment by majestrate** [comment]
![403](https://user-images.githubusercontent.com/499653/29459887-afedecf6-83f3-11e7-8aea-30965a409df1.jpeg)

**Comment by beng7** [comment]
try [this](https://forums.bunsenlabs.org/viewtopic.php?id=4075)

**Comment by majestrate** [comment]
same

**Comment by beng7** [comment]
![image](https://user-images.githubusercontent.com/7857676/29462471-c4d9d152-842f-11e7-9b53-962f452e238a.png)
will keep you updated on answers

**Comment by beng7** [comment]
Hi majestrate
so at the BL forums I was asked to provide the output of
```
apt-cache policy libstdc++6
apt-cache policy
```
and from the output told to 

> to remove the current libstdc++6 package (which seems to have been installed from a .deb) and then re-install it again using `apt-get` (or possibly `aptitude`), that should give you the correct version.
> 
> Also, please note that the use of the deb-multimedia repositories is discouraged by the BunsenLabs developers because they have been known to cause dependency chain problems in the past

let me try this tonight and get back to you then.

**Comment by r4sas** [comment]
@beng7 ping!

**Comment by l-n-s** [comment]
Looks like it is not an i2pd issue, but issue of BL distro. Reopen if I'm wrong.
