### ISSUE TITLE
websockets - explain?

### ISSUE THREAD

**Issue by khumarahn** [PurpleI2P/i2pd#922]
Hi!

I update i2pd ebuilds in gentoo. I did not turn on support for websockets yet (I did not have much time to look at it carefully).

Can I ask for some basic info? What are websockets used for in i2pd? Do they improve anything? Are there any risks? Do you thing that i2pd should be built with websocket support by default?

**Comment by r4sas** [comment]
Websockets enables optional UI based on websockets events. Requires [websocketpp](https://github.com/zaphoyd/websocketpp/)
Better to ask about that @majestrate

**Comment by majestrate** [comment]
The websocket ui provides a base for building a real time web ui, demo code is in the i2pd-tools repo https://github.com/PurpleI2P/i2pd-tools/tree/master/websocket-ui
I never expanded on it because people seemed to not be very interested in helping flesh it out.

**Comment by majestrate** [comment]
the websocket log source basically spews a full log of events that the router receives, for security reasons it's best to have it compiled out unless you're doing work on the websocket ui.
