### ISSUE TITLE
qt: build on windows

### ISSUE THREAD

**Issue by hypnosis-i2p** [PurpleI2P/i2pd#924]
R4SAS> make -f Makefile.Release
R4SAS> make[1]: Entering directory '/c/devel/project/i2pd/qt/i2pd_qt'
R4SAS> 'C:\Qt\5.8_Static\bin\uic.exe' mainwindow.ui -o ui_mainwindow.h
R4SAS> C:/Qt/5.8_Static/bin/uic.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
R4SAS> make[1]: *** [Makefile.Release:1330: ui_mainwindow.h] Error 127
orignal> ну тут я не знаю
R4SAS> и как его собирать то?
R4SAS> у него ващета нет целей для выни
orignal> а как ты госткойн собрал?
orignal> да пох
orignal> соберу только под линукс
R4SAS> гостоин это госткоин
R4SAS> а тут он не описывал для винды
R4SAS> ща соображу попробую
R4SAS> крч я хз
R4SAS> Hypn, 
R4SAS> windows {
R4SAS>  message("Using Windows settings")
R4SAS>  BOOST_SUFFIX = -mt
R4SAS>  LIBS += -lboost_system$(BOOST_SUFFIX) -lboost_date_time$(BOOST_SUFFIX) -lboost_filesystem$(BOOST_SUFFIX) -lboost_program_options$(BOOST_SUFFIX) \
R4SAS>   -lssl -lcrypto -lz -lwsock32 -lws2_32 -lgdi32 -liphlpapi -lstdc++ -lpthread
R4SAS>  CXXFLAGS += -Os -D_MT -DWIN32 -D_WINDOWS -DWIN32_LEAN_AND_MEAN
R4SAS> }
R4SAS> остальное сам думай
orignal> да пусть он думает

**Comment by mewmew-i2p** [comment]
fixed

**Comment by mewmew-i2p** [comment]
someone with admin right please close this issue
