### ISSUE TITLE
127.0.0.1 SOCKS Proxy will stop responding after at most 17 hours

### ISSUE THREAD

**Issue by myfingerhurt** [PurpleI2P/i2pd#937]
I found a problem, but not sure how to nail it.

127.0.0.1 SOCKS Proxy will stop responding after at most 17 hours
at the same time, HTTP Proxy is good, Server Tunnels is also good.
SOCKS and HTTP Proxy were tested through firefox browser each alone to access i2pwiki.i2p, 
Server Tunnels was tested by retroshare i2p hidden node, other node can find the hidden node and link through the Server Tunnels address.

After restart i2pd, the SOCKS Proxy will become accessible.

I run i2pd in this way.
`./i2pd -conf ~/.i2pd/i2pd.conf  -tunconf ~/.i2pd/tunnels.conf -bandwidth X `

```
Client Tunnels:
HTTP Proxy ⇐ bhkvluqe6vixxxxxxxxxxxxxxxxxxxxxxxxxx.b32.i2p    4444
SOCKS Proxy ⇐ bhkvluqe6vi3c6xxxxxxxxxxxxxxxxxxxxxxx.b32.i2p  4447

Server Tunnels:
RetroShare-I2p-CentralHub ⇒ r7aiyfcxxxxxxxxxxxxxxxxxxxxxxxxxxxx.b32.i2p:4449
```

The source was checked out from the latest openssl branch. 
```
$ git rev-parse HEAD
543566840c6938c160a432fc9737b590611026b6
```
and `$ make` with all default switches settings

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

```
$ free -m
              total        used        free      shared  buff/cache   available
Mem:            488         283          43           1         162         163
Swap:          2047         297        1750
```

One special error occurred a lot, I noticed.
`11:29:33@312/error - HTTP Server: error handling accept Too many open files`

```
$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 1794
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 4095
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1794
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

```
Uptime: 18 hours, 54 seconds
Network status: OK
Tunnel creation success rate: 35%
Received: 11.20 GiB (113.24 KiB/s)
Sent: 12.80 GiB (121.29 KiB/s)
Transit: 9.95 GiB (99.36 KiB/s)
Data path: /home/ben/.i2pd
Hidden content. Press on text to see.
Routers: 3618 Floodfills: 1689 LeaseSets: 0
Client Tunnels: 38 Transit Tunnels: 448
```

**Comment by LLE8** [comment]
show ss -s output

**Comment by myfingerhurt** [comment]
```
$ sudo ss -s
Total: 1210 (kernel 1216)
TCP:   1311 (estab 1005, closed 116, orphaned 32, synrecv 0, timewait 97/0), ports 0

Transport Total     IP        IPv6
*         1216      -         -
RAW       0         0         0
UDP       21        16        5
TCP       1195      958       237
INET      1216      974       242
FRAG      0         0         0
```
## _Question:_
How can I restart failed SOCKS Proxy without needing to restart the i2pd just like what i2p is doing?

**Comment by LLE8** [comment]
Are there any i2pd related records in /var/log/messages* or in /var/log/kern.log* ?

**Comment by K1773R** [comment]
```11:29:33@312/error - HTTP Server: error handling accept Too many open files```
increase the ulimit -n (number of max file handles)

**Comment by myfingerhurt** [comment]
> increase the ulimit -n (number of max file handles)

It has been set to 4095, more than that is not allowed.
```
$ ulimit -n 4096
-bash: ulimit: open files: cannot modify limit: Operation not permitted
```

**Comment by myfingerhurt** [comment]
>Are there any i2pd related records in /var/log/messages* or in /var/log/kern.log* ?

This time I didn't save any logs, but since I can reproduce this issue every time, so I will restart i2pd and enable logs. I will report later.

**Comment by K1773R** [comment]
you can change the limits in /etc/security/limits.conf

**Comment by LLE8** [comment]
To increase limit of open files for running process
from root
 prlimit --pid <PID_of_i2pd> --nofile=8192

man prlimit

**Comment by LLE8** [comment]
https://github.com/PurpleI2P/i2pd/issues/937#issuecomment-325594410
NO!

**Comment by myfingerhurt** [comment]
I restart i2pd, as I expected, SOCKS and HTTP Proxy Proxy immediately go back online.

```
LeaseSets: 7
Hidden content. Press on text to see.
Inbound tunnels:
⇒ YToT ⇒ 88pt ⇒ Jev6 ⇒ 3673146971:me ( 2178ms ) established, 359 KiB
⇒ uiT4 ⇒ aH63 ⇒ 2BqF ⇒ 3737312310:me ( 1803ms ) established, 362 KiB
⇒ 8oIn ⇒ X5g6 ⇒ YlEE ⇒ 277623788:me ( 3704ms ) established, 128 KiB
⇒ Mc8N ⇒ 6JGO ⇒ 2tkr ⇒ 1629119821:me ( 563ms ) established, 224 KiB
⇒ K4Dr ⇒ FX58 ⇒ aquc ⇒ 594062590:me ( 1193ms ) established, 932 KiB

Outbound tunnels:
998240811:me ⇒ 6NJB ⇒ XQse ⇒ -p1H ⇒ ( 2169ms ) established, 36 KiB
2691246013:me ⇒ 241w ⇒ sBVK ⇒ iuC- ⇒ ( 1809ms ) established, 728 KiB
3311872183:me ⇒ ejiu ⇒ gDvr ⇒ LEwu ⇒ ( 3698ms ) established, 1444 KiB
2448965477:me ⇒ XfID ⇒ 26R4 ⇒ tifO ⇒ ( 567ms ) established, 1372 KiB
1344112407:me ⇒ 6dy7 ⇒ 0qH9 ⇒ H1oR ⇒ ( 1189ms ) established, 15 KiB

Tags
Incoming: 1134
Outgoing:
byhjun6hrzlf6gyai4zjifmd4dsnjxiuttpb63jbcwymzmqi5bfq.b32.i2p 3
byo53io7vrfzzumbkdsh4a5f2pemzodio4es4armrq2fxas4pgoq.b32.i2p 3
b2bdyx4iiv7rf3pbwq2dkocmh55kcpaydhk6a5sh3zyi6thnby7q.b32.i2p 0
b3cbwv6oqbvnqpyroxo7xyx5ex2peh64gylvbshbflhd4lpghwlq.b32.i2p 7
b3flggzu5g7jlfncat4rcdbad4kzmp5l4blihkbkfudzct2cpq4q.b32.i2p 6
```

**Comment by LLE8** [comment]
There are was two bugs https://github.com/PurpleI2P/i2pd/issues/804 and https://github.com/PurpleI2P/i2pd/issues/795 but they are closed

**Comment by majestrate** [comment]
Perhaps we should implement soft limits soon... :+D

**Comment by LLE8** [comment]
@majestrate 
Why?

**Comment by myfingerhurt** [comment]
So far so good, both HTTP and SOCKS Proxy are still working.
```
Uptime: 21 hours, 6 min, 14 seconds
Network status: OK
Tunnel creation success rate: 43%
Received: 21.81 GiB (374.43 KiB/s)
Sent: 24.52 GiB (427.62 KiB/s)
Transit: 20.40 GiB (369.90 KiB/s)
Data path: /home/ben/.i2pd
Hidden content. Press on text to see.
Routers: 3932 Floodfills: 1604 LeaseSets: 0
Client Tunnels: 35 Transit Tunnels: 761
```

HTTP/SOCKS Proxy 
```
Tags
Incoming: 14156
Outgoing:
nrbnshsndzb6homcipymkkngngw4s6twediqottzqdfyvrvjw3pq.b32.i2p 28
r7aiyfcekx5qgjjp5ok45q3i4qvxj3gy5srxelmz7ii2dv5orpna.b32.i2p 1247
subdwxrx25do5bksp52jzyagejxpzqtd52m7wc7jlmlxess4seba.b32.i2p 1525
ympoq6eqpgcgdfxcgwgbid7fwlb53f4q7bpsfc7fgtwncihwyv2a.b32.i2p 4
```

```
$ sudo netstat -nap | grep i2pd | grep ESTABLISHED | wc -l
1658
```

It seems OK since I did this yesterday.
```
$ ps -a
  PID TTY          TIME CMD
 9570 pts/1    00:04:37 i2pd
$ sudo prlimit -p9570 -n8192
$ sudo prlimit -p9570 -n
RESOURCE DESCRIPTION              SOFT HARD UNITS
NOFILE   max number of open files 8192 8192
```
No more `Too many open files` since I applied the new prlimit yesterday after launched an new i2pd session.
```
$ grep -c "Too many" .i2pd/i2pd.log
720
ben@rs:~$ grep "Too many" .i2pd/i2pd.log |tail -n 10
18:09:10@955/info - NTCP: Connect error Too many open files
18:09:10@955/info - NTCP: Connect error Too many open files
18:09:11@955/info - NTCP: Connect error Too many open files
18:09:14@955/info - NTCP: Connect error Too many open files
18:09:14@955/info - NTCP: Connect error Too many open files
18:09:16@955/info - NTCP: Connect error Too many open files
18:09:17@955/info - NTCP: Connect error Too many open files
18:09:46@955/info - NTCP: Connect error Too many open files
18:09:47@955/info - NTCP: Connect error Too many open files
18:09:47@955/info - NTCP: Connect error Too many open files
```

Now searching logs for `HTTP Server: error handling accept Too many open files`
`$ grep "accept Too many open files" -m3 .i2pd/i2pd.log` Returns 0 result.

**Comment by LLE8** [comment]
@myfingerhurt 
Check you  net.core.somaxconn  and net.ipv4.tcp_max_orphans  (sysctl -a from root)
Yuo may need to increase this values.
See https://github.com/PurpleI2P/i2pd/issues/825

**Comment by myfingerhurt** [comment]
Here is the orignal values, I don't have problems about `Too many open files` today, even with the default setting shown as below:
```
$ sudo sysctl -a |grep "net.ipv4.tcp_max"
net.ipv4.tcp_max_orphans = 2048
net.ipv4.tcp_max_reordering = 300
net.ipv4.tcp_max_syn_backlog = 128
net.ipv4.tcp_max_tw_buckets = 2048

$ sudo sysctl -a |grep "net.core.somaxconn"
net.core.somaxconn = 128
```
But as you suggessted, I crank them up, here is the new settings.
```
~$ sudo sysctl -w net.core.somaxconn=32768
net.core.somaxconn = 32768
$ sudo sysctl -w net.ipv4.tcp_max_orphans=32768
net.ipv4.tcp_max_orphans = 32768
```

```
$ sudo netstat  -nap | grep EST | grep i2pd | wc -l
1801
```

**Comment by myfingerhurt** [comment]
After 30 hours, the SOCKS Proxy is down again. HTTP Proxy is OK.
After restarting i2pd this time, the curl test can't pass, but Retroshare i2p node can link each other.

```
$ curl -v -x 127.0.0.1:4447 -L http://i2pwiki.i2p 
* Rebuilt URL to: http://i2pwiki.i2p/
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 4447 (#0)
> GET http://i2pwiki.i2p/ HTTP/1.1
> Host: i2pwiki.i2p
> User-Agent: curl/7.47.0
> Accept: */*
> Proxy-Connection: Keep-Alive
>
* Recv failure: Connection reset by peer
* Closing connection 0
```

```
$ sudo netstat  -nap | grep EST | grep i2pd | wc -l
1994
```

### Question:
Why the `Outgoing` can be a couple dozens of items when I just started i2pd and drops to one or two after several hours. 
```
Tags
Incoming: 3890
Outgoing:
r7aiyfcekx5qgjjp5ok45q3i4qvxj3gy5srxelmz7ii2dv5orpna.b32.i2p 869
```

The log is 387MByte, so I just abstract all errors into one file.
Yesterday :[i2pd.error.yesterday.log.txt](https://github.com/PurpleI2P/i2pd/files/1265520/i2pd.error.yesterday.log.txt)

Today:  After restart [i2pd.error.today.log.txt](https://github.com/PurpleI2P/i2pd/files/1265522/i2pd.error.today.log.txt)
The `Too many open files` around 03:12 am was before `sudo prlimit -p29263 -n8192` was applied. But this was just starting i2pd, comparing to yesterday, this doesn't look good, maybe this is the reason why SOCKS Proxy can not pass the curl test at beginning.

**Comment by l-n-s** [comment]
It is a classic "open files limit" issue. [Recommended way of running i2pd](https://i2pd.readthedocs.io/en/latest/user-guide/run/#recommended-way-to-run-i2pd-built-from-source) is defined in documentation, also there is an entry about this problem in [FAQ](https://i2pd.readthedocs.io/en/latest/user-guide/FAQ/#help-i2pd-is-not-working-what-to-do).

IDK what else can be done, any program will go crazy when it reaches the system limit. 

    <html><body><H1>I2P SOCKS PROXY ERROR: REQUEST DENIED</H1>

i2pd works correctly, this is server response here.

**Comment by myfingerhurt** [comment]
>`<html><body><H1>I2P SOCKS PROXY ERROR: REQUEST DENIED</H1>`

If I confused you, my apologies, that's i2p's response. not i2pd's. I put that for example because I want to show what i2pd should response. 

>It is a classic "open files limit" issue. Recommended way of running i2pd is defined in documentation, also there is an entry about this problem in FAQ.

These have already been done. Didn't solve the issues. Even without exceeding the upper limits, SOCKS Proxy still fails to respond after 30 hours.

**Comment by majestrate** [comment]
I suspect that SOCKS proxy server crashes and does not properly recover, I'll check the code this morning and get back to you.

**Comment by majestrate** [comment]
socks proxy is blocked by java i2p's http server tunnel because of user agent and other headers

**Comment by myfingerhurt** [comment]
Strange, I had stopped i2p service before running i2pd, and had never started it during the time when i2pd was running.

**Comment by l-n-s** [comment]
<html><body><H1>I2P SOCKS PROXY ERROR: REQUEST DENIED</H1>

Looks like it is webserver on the other end which is refusing connection. Not i2pd issue.

You need to spoof User-Agent and other http headers so that they don't deny your connection.

So, if socks proxy works, and this answer is correct, may we close the issue?

**Comment by myfingerhurt** [comment]
After running for 30 hours.
```
curl -v  --socks5-hostname 10.9.8.10:4447 -L telnet://iaghdds4rbdvxfeazrdv356uyca7g6zmvs6izt34ntn4n6r6fyra.b32.i2p:41222
* Rebuilt URL to: telnet://iaghdds4rbdvxfeazrdv356uyca7g6zmvs6izt34ntn4n6r6fyra.b32.i2p:41222/
*   Trying 10.9.8.10...
* TCP_NODELAY set
* SOCKS5 communication to iaghdds4rbdvxfeazrdv356uyca7g6zmvs6izt34ntn4n6r6fyra.b32.i2p:41222
* Unable to receive initial SOCKS5 response.
* Closing connection 0
curl: (7) Unable to receive initial SOCKS5 response.
```
1 minutes after restart.
```
curl -v  --socks5-hostname 10.9.8.10:4447 -L telnet://iaghdds4rbdvxfeazrdv356uyca7g6zmvs6izt34ntn4n6r6fyra.b32.i2p:41222
* Rebuilt URL to: telnet://iaghdds4rbdvxfeazrdv356uyca7g6zmvs6izt34ntn4n6r6fyra.b32.i2p:41222/
*   Trying 10.9.8.10...
* TCP_NODELAY set
* SOCKS5 communication to iaghdds4rbdvxfeazrdv356uyca7g6zmvs6izt34ntn4n6r6fyra.b32.i2p:41222
* SOCKS5 request granted.
* Connected to 10.9.8.10 (10.9.8.10) port 4447 (#0)
```
