### ISSUE TITLE
Cannot start, "Failed with result 'core-dump'."

### ISSUE THREAD

**Issue by fedorkov** [PurpleI2P/i2pd#938]
Arch Linux. [This](https://aur.archlinux.org/packages/i2pd/) package was installed smoothly, but when I try to launch the service, it fails with "Job for i2pd.service failed because a fatal signal was delivered causing the control process to dump core."

See [the log here](https://pastebin.com/raw/S01Sd0Sc).

**Comment by majestrate** [comment]
do your cpu have AVX/AES-NI support? If not that's probably going to be a problem as arch's build enables those by default i think.

**Comment by fedorkov** [comment]
Indeed, `cat /proc/cpuinfo |grep aes` shows nothing.
I don't have much experience with this toolchain. Can I pass some flags to cmake to disable AVX/AES-NI?

**Comment by majestrate** [comment]
the cmake flags you are looking for are -DWITH_AVX=NO and -DWITH_AESNI=NO

**Comment by majestrate** [comment]
rather, OFF not NO

**Comment by fedorkov** [comment]
DWITH_AVX was explicitly set to ON in the package. I removed this flag and now everything's working fine.
I'll report to the maintainer about this.
Thanks a lot for your help.
