### ISSUE TITLE
Qt крашится при добавлении/удалении тоннеля

### ISSUE THREAD

**Issue by anon-anon** [PurpleI2P/i2pd#945]
Еще крашится при kill -s HUP, в CLI подобных проблем нет.

**Comment by hypnosis-i2p** [comment]
Просьба приложить бэктрейс крэша при добавлении/удалении тоннеля (вроде команда bt в gdb с корефайлом). У меня ни разу не крэшалось

**Comment by orignal** [comment]
@anon-anon распиши сценарий что ты пытаешься сделать

**Comment by anon-anon** [comment]
@orignal пытаюсь добавить или удалить новый тоннель.
UPD: Сигнал - SIGSERV. Ошибка - Segmentation fault (core dumped).

**Comment by orignal** [comment]
Какой именно тоннель? Клиентский? Серверный? Тот же адрес или другой?

**Comment by anon-anon** [comment]
@orignal любой. Абсолютно любой.

**Comment by anon-anon** [comment]
@hypnosis-i2p 
Этого хватит?
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff560a3b9 in QObject::disconnect(QObject const*, char const*, QObject const*, char const*) () from /home/anon/Qt/5.8/gcc_64/lib/libQt5Core.so.5
#2  0x00005555558e4711 in widgetlock::~widgetlock (this=0x555556119580, __in_chrg=<optimized out>) at ../i2pd_qt/widgetlock.h:29
#3  0x00005555558e4740 in widgetlock::~widgetlock (this=0x555556119580, __in_chrg=<optimized out>) at ../i2pd_qt/widgetlock.h:30
#4  0x00005555555986b4 in widgetlockregistry::~widgetlockregistry (this=0x555556112588, __in_chrg=<optimized out>) at ../i2pd_qt/widgetlockregistry.h:14
#5  0x00005555558e2834 in TunnelPane::~TunnelPane (this=0x555556112570, __in_chrg=<optimized out>) at ../i2pd_qt/TunnelPane.h:32
#6  0x00005555558e2abe in ClientTunnelPane::~ClientTunnelPane (this=0x555556112570, __in_chrg=<optimized out>) at ../i2pd_qt/ClientTunnelPane.h:18
#7  0x00005555558e2ada in ClientTunnelPane::~ClientTunnelPane (this=0x555556112570, __in_chrg=<optimized out>) at ../i2pd_qt/ClientTunnelPane.h:18
#8  0x00005555555953a3 in MainWindow::deleteTunnelForms (this=0x7fffffffd9e0) at ../i2pd_qt/mainwindow.cpp:729
#9  0x000055555559543a in MainWindow::reloadTunnelsConfigAndUI (this=0x7fffffffd9e0, tunnelNameToFocus="") at ../i2pd_qt/mainwindow.cpp:738
#10 0x000055555559c837 in MainWindow::DeleteTunnelNamed (this=0x7fffffffd9e0, name="name5") at ../i2pd_qt/mainwindow.h:550
#11 0x0000555555595a16 in MainWindow::TunnelsPageUpdateListenerMainWindowImpl::needsDeleting (this=0x7fffffffdb28, oldName="name5")
    at ../i2pd_qt/mainwindow.cpp:784
#12 0x0000555555896eba in TunnelPane::deleteButtonReleased (this=0x5555561b60d0) at ../i2pd_qt/TunnelPane.cpp:195
#13 0x00005555558e3b55 in TunnelPane::qt_static_metacall (_o=0x5555561b60d0, _c=QMetaObject::InvokeMetaMethod, _id=1, _a=0x7fffffffcc60)
    at moc_TunnelPane.cpp:80

**Comment by hypnosis-i2p** [comment]
@anon-anon Ага, огромное спасибо! Посмотрю

**Comment by hypnosis-i2p** [comment]
пофиксал вроде. в https://github.com/PurpleI2P/i2pd/pull/948

**Comment by hypnosis-i2p** [comment]
@anon-anon креша при -s HUP не обнаружил в пофиксанной версии, просьба тоже приложить bt

**Comment by anon-anon** [comment]
@hypnosis-i2p 
Вот при "kill -s HUP"
(gdb) bt
#0  0x00007ffff48e2d8d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff1685576 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff168568c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff562dcbf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/anon/Qt/5.8/gcc_64/lib/libQt5Core.so.5
#4  0x00007ffff55db9ca in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/anon/Qt/5.8/gcc_64/lib/libQt5Core.so.5
#5  0x00007ffff55e39f4 in QCoreApplication::exec() () from /home/anon/Qt/5.8/gcc_64/lib/libQt5Core.so.5
#6  0x000055555558a01e in i2p::qt::RunQT (argc=1, argv=0x7fffffffdc68) at ../i2pd_qt/DaemonQT.cpp:169
#7  0x00005555558b1c9b in main (argc=1, argv=0x7fffffffdc68) at ../../daemon/i2pd.cpp:15

**Comment by hypnosis-i2p** [comment]
@anon-anon думаю Qt app незачем атаковать через kill -s HUP... проще сделать кнопку Reload Configuration..

**Comment by hypnosis-i2p** [comment]
@anon-anon это фишка для безгуёвого i2pd
