### ISSUE TITLE
[qt gui] Deal with "Hidden content" in the status console

### ISSUE THREAD

**Issue by nonlinear-chaos** [PurpleI2P/i2pd#949]

**Comment by l-n-s** [comment]
Заголовок иссуя лучше на английском написать, но тут я не знаю что имеется в виду.

**Comment by r4sas** [comment]
@l-n-s имеется в виду скрытый текст, как в вебморде, открываемый по нажатию на `Hidden content. Press on text to see.`

**Comment by nonlinear-chaos** [comment]
already works as expected.
