### ISSUE TITLE
how to get server tunnel b32 automatically?

### ISSUE THREAD

**Issue by igran** [PurpleI2P/i2pd#953]
if i want will create permanent tunnel i can edit tunnel config file with script on bash or python, but i can't get b32 destination address.
so i have have question:how to create permanent tunnel and get b32 address  wiith python? 
--------------------------------------RUSSIAN --------------------------------------------------
Задача создать постоянный серверный туннель с помощью скрипта на питоне, отредактировать tunnel.cfg и отправить SIGHUP не проблема, а вот адрес получить сложнее я видел keyinfo,но я надеюсь есть более простой вариант.

**Comment by orignal** [comment]
В веб морде он есть

**Comment by r4sas** [comment]
@l-n-s insecure.

**Comment by l-n-s** [comment]
@r4sas insecure what?

**Comment by igran** [comment]
google translate:
it's really not safe with this approach, an attacker can learn the tunnel addresses remotely with ajax but you can do RESTlike token authentication that will improve security and save  backward compatibility with i2pcontrol.

**Comment by orignal** [comment]
@l-n-s yes we can

**Comment by l-n-s** [comment]
@igran мы уже обсудили, там есть авторизация, так что все норм.

@orignal я попробую тогда, посмотрим, что получится.

**Comment by igran** [comment]
ну что там

**Comment by l-n-s** [comment]
Refer to #954
