### ISSUE TITLE
Feature request: Trusted jump service for auto-resolving .i2p domains

### ISSUE THREAD

**Issue by igran** [PurpleI2P/i2pd#955]
example i
`18:46:20@369/info - SOCKS: requested pop.postman.i2p:80
18:46:20@369/error - Addressbook: Can't find domain for pop.postman.i2p
18:46:20@369/warn - I2PService: Remote destination not found: pop.postman.i2p
18:46:20@369/error - SOCKS: error when creating the stream, check the previous warnings for more info
`
this addrees is not my address book 
Whether it is possible to make resolv and add in address book in an automatic mode through the trusted jump service if address not find in address book?

**Comment by majestrate** [comment]
How do you authenticate that you got the address right?

The http tunnel has manual user confirmation, what would this do?

**Comment by orignal** [comment]
What is "trusted jump service"?

**Comment by Zero3K** [comment]
I think he means that it should auto-resolve a .i2p domain via a jump service that is added to its configuration file.
