### ISSUE TITLE
Bind to alias IP does not works

### ISSUE THREAD

**Issue by saspol** [PurpleI2P/i2pd#959]
Hello,
I want i2pd makes all outgoing connections from specific IP address.
So, i add alias IP to eth0 interface and then set in i2pd config:
```
## Network interface to bind to
ifname = eth0:0
```
But no success, all outgoing connections still from eth0 IP address.
```
## External IP address to listen for connections
## By default i2pd sets IP automatically
host = 192.168.1.2
```
Setting this to alias IP also does not change anything. I think is unexpected behaviour.
```
i2pd version 2.15.0 (0.9.31)
```

**Comment by l-n-s** [comment]
What IP address `eth0` has and what do you try to accomplish with those aliases? Are both IP addresses in LAN?

**Comment by saspol** [comment]
Hello,
```eth0``` have IP from same subnet. I want bind i2pd to dedicated IP to route this traffic separately on gateway router. I already found can catch this traffic by port number, but anyway.

**Comment by majestrate** [comment]
I don't think our current code handles virtual network interfaces addresses.

Probably should fix that.

**Comment by r4sas** [comment]
addressv4/addressv6 was added.
