### ISSUE TITLE
i2pd.log warns of missing streaming messages then crashes

### ISSUE THREAD

**Issue by mathiasfriman** [PurpleI2P/i2pd#968]
I've run i2pd (2.15.0) for a long time without any troubles. Now I test-run XD go torrent client, and the i2pd daemon crashes at least once every day.

Yesterday (i2pd.log.1): 

    07:35:03@95/warn - Streaming: Missing messages on sSID=775050352: from 20582 to 20584
    07:35:03@95/warn - Streaming: Missing messages on sSID=775050352: from 20582 to 20585
    [EOF]

Today (i2pd.log):

    07:51:26@95/error - Streaming: No packets have been received yet
    07:51:26@95/error - Streaming: No packets have been received yet
    07:51:26@95/warn - Streaming: Another outbound tunnel has been selected for stream with sSID=1739679813
    07:51:26@95/warn - Streaming: Missing messages on sSID=3158541086: from 59439 to 59441
    [EOF]

Not sure if one should lend any significance to the log messages, but it's worth a try anyway.

**Comment by orignal** [comment]
Please provide call stack of the crash. 
Missing messages is nornal behaviour

**Comment by l-n-s** [comment]
@mathiasfriman any updates?

**Comment by r4sas** [comment]
t/o.
If any new info or issue repeats, please reopen.
