### ISSUE TITLE
systemctl: `service i2pd restart` does graceful shutdown, instead of restarting instantly

### ISSUE THREAD

**Issue by hypnosis-i2p** [PurpleI2P/i2pd#970]
It doesn't stop i2pd

**Comment by hypnosis-i2p** [comment]
system: xenial

**Comment by majestrate** [comment]
I think it tries to do a graceful shutdown by default which takes 10 minutes

**Comment by r4sas** [comment]
https://github.com/PurpleI2P/i2pd/blob/openssl/debian/i2pd.init#L109 ->
https://github.com/PurpleI2P/i2pd/blob/openssl/debian/i2pd.init#L69   ->
https://github.com/PurpleI2P/i2pd/blob/openssl/debian/i2pd.init#L114 ->
https://github.com/PurpleI2P/i2pd/blob/openssl/debian/i2pd.init#L32

So when used restart command, init trying to stop process with SIGTERM, wait 30 seconds, and after that SIGKILL.

**Comment by l-n-s** [comment]
Is this even an issue?

**Comment by r4sas** [comment]
If any issues, please reopen.
