### ISSUE TITLE
Follow XDG standard for creating datadir in $HOME

### ISSUE THREAD

**Issue by l-n-s** [PurpleI2P/i2pd#971]
https://standards.freedesktop.org/basedir-spec/latest/ar01s03.html

https://wiki.archlinux.org/index.php/XDG_Base_Directory_support

i2pd should search `$HOME/.config/i2pd` for config files and `$HOME/.local/share/i2pd` for data files.

(it is similar standard as Windows has with %APPDATA%)

**Comment by abcdw** [comment]
Any updates on this?

**Comment by r4sas** [comment]
I think that idea abandoned because current directory widely used in current installations.
