### ISSUE TITLE
how to know base 64 hash  of hidden service ?

### ISSUE THREAD

**Issue by bol-van** [PurpleI2P/i2pd#973]
Sorry for asking here but havent found answer anywhere.
I created hidden service in i2pd. I got b32.i2p address from http://localhost:7070 "local destinations".
inr.i2p asks me base64 hash.
How do I get it ?
I have private key .dat file, I have b32.i2p address

**Comment by r4sas** [comment]
Open i2pd [webconsole](http://127.0.0.1:7070), goto I2P Tunnels page and find your predefined in config by `[XXXXX]` tunnel name.
Click on their name and find Base64 raw text block.
