### ISSUE TITLE
AppArmor Profile for Debian/Ubuntu issues

### ISSUE THREAD

**Issue by chris-barry** [PurpleI2P/i2pd#974]
Please assign it to me 👍

**Comment by r4sas** [comment]
Already here: https://github.com/PurpleI2P/i2pd/blob/openssl/contrib/apparmor/usr.sbin.i2pd

**Comment by l-n-s** [comment]
@chris-barry I've added this basic profile long time ago, using it right on regular basis - it works fine. Is there anything to improve?

**Comment by LLE8** [comment]
Теперь не собирается
dpkg-checkbuilddeps: Unmet build dependencies: dh-apparmor
Надо в документацию добавить
apt-get install dh-apparmor

**Comment by l-n-s** [comment]
@LLE8 https://github.com/PurpleI2P/i2pd_docs_en/commit/9c8e6029c7b7d6b01b511df6a1bd2aa6d129c21e так?

**Comment by LLE8** [comment]
похоже

**Comment by r4sas** [comment]
@l-n-s да

**Comment by l-n-s** [comment]
looks resolved, thanks @chris-barry

**Comment by r4sas** [comment]
Few days ago at #i2pd-dev one man said that have problems with writing to $HOME/.i2pd
As later we found, apparmor started use profile after installing new version of i2pd.
User's system: Ubuntu 16.04. Need to workaroud that problem.

**Comment by l-n-s** [comment]
If he is running i2pd from package non-standard way, he must change his profile manually. There is nothing wrong with the package, user is just doing it wrong.

BTW, isn't profile disabled by default?

**Comment by r4sas** [comment]
Yes, it enabled atomaticly.

**Comment by r4sas** [comment]
Ubuntu Artful (17.10) couldn't start i2pd as service untill disabling apparmor profile.

**Comment by r4sas** [comment]
После [обновления](https://github.com/PurpleI2P/i2pd/pull/1082) не слыхать в эту сторону возражений, так что закрываю. Если будут дополнительные проблемы, просьба писать здесь.
