### ISSUE TITLE
Limit tcp and udp connections

### ISSUE THREAD

**Issue by mppdidi** [PurpleI2P/i2pd#980]
On my raspberry i need to be able to limit the number of tcp and udp connections without involving the number of open file descriptors.
Is it possible to implement this in the i2pd code ?

Thanx.

**Comment by majestrate** [comment]
this is something i've been waiting for someone to ask for.

i'll see if i can add it today.

**Comment by mppdidi** [comment]
spasiba ... :-)

**Comment by orignal** [comment]
@majestrate doesn't speak Russian :)

**Comment by l-n-s** [comment]
@mppdidi ping

Test if your request is satisfied

**Comment by majestrate** [comment]
I added NTCP limits, not sure what kind of limits SSU should have since i don't think it has an open file limit problem

**Comment by mppdidi** [comment]
Working great.
Now my raspi is much more calm...
About the SSU - the number of udp sesssions seems to be very valid.
I have the impression that i2pd tries to avoid SSU as much as possible - maybe a design goal of i2pd ?
I dont't know why - probably due to the lack of architectural understanding of the i2pd inner workings.
Anyways - I would personally welcome an SSU / udp limit - combined with share and transittunnels limiting the i2pd has gained more of my attention than ever before ;-)

**Comment by orignal** [comment]
i2pd prefers NTCP vs. SSU

**Comment by mppdidi** [comment]
Got it.
The only problem with tcp is that it consumes a lot of open file descriptors.
On my raspberry this is a serious limitation - so limiting tcp is improving things for me.
Have a good one.
