### ISSUE TITLE
Tunnel quantity

### ISSUE THREAD

**Issue by mppdidi** [PurpleI2P/i2pd#981]
I've being doing some load tests with i2pd.
Allthough i specified inbound and outbound tunnel quantities of more then 5, this setting seems to be ignored.
Am I missing something or is there a hard coded limitation on the tunnel quantities ?

**Comment by orignal** [comment]
yes, more then 5 is ignored now. We just don't use this I2NP message yet

**Comment by l-n-s** [comment]
Should we keep this issue open? Then we need to have more verbose description.

**Comment by orignal** [comment]
I don't see any reason why one might need more than 5 hops, better to specify in the docs we limit number of hops to 5.

**Comment by majestrate** [comment]
maybe for now 5 hops is good but in the future higher capacity services would get congested fast.

for now it's probably a fine limit as i2pd has to maintain 10 tunnels minimum (5 out / 5 in) in that case

**Comment by mppdidi** [comment]
Just to be sure on this - I didn't mean hops but rather tunnels.
Tunnel length of three is fine.
What i mean't was quantity - how many (3-hop) tunnels can be in a leaseset.
