### ISSUE TITLE
Backup for failed tunnels

### ISSUE THREAD

**Issue by mppdidi** [PurpleI2P/i2pd#984]
Is there a backup tunnel concept within i2pd - I mean within a lease set ?

Thanx.

**Comment by orignal** [comment]
No. We use all available tunnels.

**Comment by mppdidi** [comment]
My question was more from the perspective of the application connecting to a destination.
Does a failed tunnel lead to a connection timeout - like e.g. http connection error or something ?

**Comment by orignal** [comment]
It tries to switch to another tunnel first. Also i2pd always tests tunnels and discovers failed tunnels quickly.
