### ISSUE TITLE
why running './i2pd' failed?

### ISSUE THREAD

**Issue by luckypoem** [PurpleI2P/i2pd#990]
HI.

yudeMacBook-Air:i2pd_2.15.0_osx brite$ ls
i2pd			libc++.1.dylib
libSystem.B.dylib	libz.1.dylib
yudeMacBook-Air:i2pd_2.15.0_osx brite$ ./i2pd
dyld: Library not loaded: /usr/local/lib/libcrypto.1.1.dylib
  Referenced from: /Users/brite/Downloads/i2pd_2.15.0_osx/./i2pd
  Reason: image not found
Abort trap: 6
yudeMacBook-Air:i2pd_2.15.0_osx brite$

how to fix it?

**Comment by majestrate** [comment]
looks like th mac build isn't done right, you can build i2pd with homebrew and it'll work fine that way.

    brew install libressl boost 
    
then get i2pd source code and do:

    make HOMEBREW=1

**Comment by orignal** [comment]
will include this dlyb tommorow  and upload 2.15 for mac os x again

**Comment by orignal** [comment]
Built non-static by mistake. Uploaded. Please trt now.
