### ISSUE TITLE
BOB inhost not honored

### ISSUE THREAD

**Issue by mppdidi** [PurpleI2P/i2pd#993]
Despite defining inhost as 127.0.0.1 - BOB ingores this and listens on all interfaces.

**Comment by orignal** [comment]
Probably. Where is it specified?

**Comment by mppdidi** [comment]
You mean like libi2pd_client/BOB.h + cpp ?

**Comment by orignal** [comment]
I mean BOB specs describing fields like "inhost"

**Comment by mppdidi** [comment]
I'm not sure there is an actual specification other than https://geti2p.net/en/docs/api/bob
