### ISSUE TITLE
More than one http proxy

### ISSUE THREAD

**Issue by mppdidi** [PurpleI2P/i2pd#995]
Is it possible to extend i2pd to run more than one http proxy instance ?

Thanx

**Comment by majestrate** [comment]
we already have that, use tunnels.conf entries of type `httpproxy`

**Comment by mppdidi** [comment]
The tunnels.conf defined httpproxy uses the same shared tunnels as the 'builtin' httpproxy - where is the point in that ?

**Comment by majestrate** [comment]
it doesn't if you give it destination keys
