### ISSUE TITLE
Disable logging via option

### ISSUE THREAD

**Issue by mppdidi** [PurpleI2P/i2pd#998]
Afaikt logging occurs regardless of the level set.
If I want to disable logging /dev/null seems to be the only solution here.
Could you implement an option to disable logging completely ?

**Comment by hypnosis-i2p** [comment]
Да, я тоже голосую за такую опцию

**Comment by orignal** [comment]
неужели нету?

**Comment by r4sas** [comment]
@mppdidi, `log = stdout` ?

**Comment by mppdidi** [comment]
As loglevel = error still spills the log I'd like to disable logging completely ...
Maybe I misunderstood the comments ( I don't speak russian :-( )

**Comment by LLE8** [comment]
@r4sas 
В лог действительно обычно падает довольно много записей об ошибках, возможно в связи с проблемами "на том конце".
В каких-то случаях это может быть нежелательно, кроме тощих маршрутизаторов, где этот лог некуда положить?

**Comment by r4sas** [comment]
ну у линуксоидовских поделий есть /dev/null, но мы уже думаем как прикрутить (возможно будет loglevel = none).

**Comment by r4sas** [comment]
https://github.com/PurpleI2P/i2pd/commit/a6fb3b602e5030e06a902f264c35f59f670e2006
https://github.com/PurpleI2P/i2pd/commit/7477d2c2198a154bdfeebb92cdd3bfde24191b2d
